### ISSUE TITLE
No Unicode Support in Variations Bookmark to Avalon Playlist SQL Script

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1001]
### Steps to Reproduce
Run the [SQL Code](https://gist.github.com/mcwhitaker/03cab8a63bf80d431fa915b235522814) on a database of Variations bookmarks that contain Unicode characters. The json file will have incorrect, ASCII only versions of the characters in strings.

#### Examples
Original Unicode Value----     |    Value In JSON Export
--- | ---
Così fan tutte |  Cosi? fan tutte 
Saint François d'Assise | Saint Franc?ois d'Assise 

### Done Looks Like
SQL script is changed to use nvarchar instead of varchar for Unicode support

**Comment by bkeese** [comment]
I have added a comment to the gist that should fix this:
https://gist.github.com/mcwhitaker/03cab8a63bf80d431fa915b235522814#file-runeverything-sql-L3
