### ISSUE TITLE
Long titles and numbers wrapped improperly in facets

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1025]

**Comment by davidschober** [comment]
Per discussion we will wait until upgrade of Blacklight.

**Comment by carrickr** [comment]
<img width="217" alt="screen shot 2016-08-03 at 12 33 13 pm" src="https://cloud.githubusercontent.com/assets/5350060/17405233/c2783d46-5a2c-11e6-9026-ccb9e2ba111e.png">

**Comment by davidschober** [comment]
see @mbklein  comment on the dupe #1054
