### ISSUE TITLE
communicate variations migration path and end of development

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1034]
## DONE
- [x]  Blog post about IU migration
- [ ] Separate Announcement from Jon Dunn (NOT Avalon) about sunsetting Variations

**Comment by davidschober** [comment]
@Debs4Avalon This is yours for this sprint. Jon still has to sign off on it.

**Comment by mcwhitaker** [comment]
@Debs4Avalon As mentioned in our Sprint planning meeting, Jon has signed off on this.  Will this be completed this week?

**Comment by davidschober** [comment]
just spoke with @Debs4Avalon she's going to get final sign off, hopefully today.

**Comment by mcwhitaker** [comment]
@davidschober What is a "final sign off"? We have a sign off already...

**Comment by mcwhitaker** [comment]
Jon D is working with Phil Ponella on the right language for the announcement and is fine with closing since it is more a Variations task than an Avalon task.

**Comment by jwd** [comment]
Email sent 12/8
