### ISSUE TITLE
Derivative class predicate review

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1042]
- [x] duration - http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#duration (ebucore:duration)

- [x] derivativeFile - http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#filename (ebucore:filename)

Suggested if needed  for external sharing/use (chose these over hlsURL and hlsTrackID as being properties that would like be shared externally):

- [x] locationURL - http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#locator (ebucore:locator)

- [x] trackID - http://www.ebu.ch/metadata/ontologies/ebucore/ebucore#identifier (ebucore:identifier)

**Comment by joncameron** [comment]
It's up to MBK to put points on this. Assigning 2 preliminarily.
