### ISSUE TITLE
Fix Format Facet on Avalon Fix

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1043]
## Done Looks Like

- [x] refactor from tesim to sim so it facets properly
- [x] Format facet changed to avalon_resource_type_sim
- [x] avalon_resource_type_sim set to titleize

**Comment by jlhardes** [comment]
MODS typeOfResource is imported from MARC record on bib import in Avalon but is not being used for anything. It represents the type of resource declared for the original physical item on the bib record but once in Avalon is not accurate for the different types of digital files that might exist (sound recording and moving image). Items created directly in Avalon do not get MODS typeOfResource but do have Avalon's type of resource set.

To provide accurate type of resource information, Avalon's type of resource should be used for format faceting and MODS typeOfResource should be ignored. When metadata export functionality is added, Avalon's type of resource information will need to be incorporated into descriptive metadata (either as part of MODS or whatever descriptive standard is being exported).
