### ISSUE TITLE
As an administrator I want to make IU specific reindexing and pruning tools public

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1070]
IU has a number of internal tools used to reindex its Avalon installs and prune out duplicate items in the event the same item is posted to the Avalon Ingest API multiple times.  These tools though are specific to the IU server environment.  They can be gentrified and made public as they reduce reindexing times and provide useful functionality for larger installs with automatic ingest.  
## Done Looks Like
- [ ] Single Threaded Media Objects only script tool is released
- [ ] Multithreaded Media Object Objects only reindex script is released
- [ ] Multithreaded Reindex All Fedora Objects script is released
- [ ] Script for pruning based on other identifier is released

(Note: These could all be broken up into their own issues.  I'm just putting this issue in for POs to consider and prioritize)

**Comment by joncameron** [comment]
We haven't done reindexing in a while, and the scripts will need work to be made public. We've also been moving these things into rake tasks.
