### ISSUE TITLE
Special Access Permissions with Start/End Times Do Not Show In LTI

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1072]
### Description
When Avalon's LTI capability is used on an LTI-enabled site like Canvas, media objects with time-based permissions do not appear.

### Steps to Reproduce

*  Assign time-based permissions on an External Group corresponding to a Canvas course for a Media Object
* Go to the Canvas course and click a view in Avalon for LTI
* All items with External Group permissions corresponding to the course are able to be seen—except for those set with time-based permission

### Example
* Here's an item in Media Collections Online with time-based permissions for our test course in Canvas, 'MCO LTI Test': https://media.dlib.indiana.edu/media_objects/avalon:16243/edit?step=access-control
* When clicking 'Media Collections Online' in the Canvas course, the view referencing  the search "External Group > MCO LTI Test" displays media objects with 'MCO LTI Test' added to the External Group permissions, but not for the above item with time-based permissions.
![screen shot 2016-08-17 at 1 15 47 pm](https://cloud.githubusercontent.com/assets/1406618/17746654/02d8f84c-647f-11e6-9d8e-85274f0e9cce.png)

**Comment by davidschober** [comment]
This should be worked on in 6.0.

**Comment by davidschober** [comment]
The issue is that the time-based content does not show. A user can access the item directly. @joncameron can you verify?

**Comment by mcwhitaker** [comment]
The code fix worked in mallorn after re-merging code. Carrick said he will try to understand what went wrong on the initial merge to mallorn.

**Comment by joncameron** [comment]
Moving to done since this fix was confirmed as working by Maria.
