### ISSUE TITLE
Compare descriptive metadata fields mappings for RDF

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1073]
Compare EBUCore and MODS/RDF Subgroup mappings for Avalon descriptive metadata fields to inform what to use for RDF properties in Fedora 4.

**Comment by davidschober** [comment]
@jlhardes is this still valid (just cleaning up)

**Comment by jlhardes** [comment]
We've used MODS/RDF Subgroup mappings but we haven't tried EBUCore mappings. Do we want to look at EBUCore for descriptive metadata @jenyoung? I feel like the MODS/RDF Subgroup mappings work pretty well and will keep Avalon closer to what the community is using but it's not necessarily a community-set path to go with that mapping yet.
