### ISSUE TITLE
Back Button causing data integrity error

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1078]
Steps to reproduce the error:

Sign in (mallorn)
Click Browse
Select one item
Click “manage selected items”
Click “clear selected items”
Click ok
From this page that tells you that you have not selected any items, if you click the browser back button, you get back to the browse page where you had selected one item and that item is still checked. The problem is that if you try to un-check that box you get an error message. If you click Select All once and then again to try to clear the checkbox you get the error again. Basically, there is a data integrity issue in the page which can only be cleared by clicking away from the page, or clicking Browse to reload the page. Simply refreshing the page does not resolve this issue.

**Comment by davidschober** [comment]
is this a blacklight core thing?

**Comment by cjcolvar** [comment]
You can always test blacklight core on http://demo.projectblacklight.org/

**Comment by davidschober** [comment]
@cjcolvar this is occurring on blacklight core. I say we close and either a, open an issue or b, assume it's an edge case.

**Comment by mcwhitaker** [comment]
@davidschober The difference between blacklight core and mallorn is that in blacklight core refreshing clears the checkboxes and in mallorn it does not. Our users have no way of clearing that other than navigating away from the page and coming back.

**Comment by davidschober** [comment]
When I refresh on Mallorn, the boxes clear. I'm seeing the identical behavior in blacklight core. (video of mallorn attached). 

![selected_items_blacklight](https://cloud.githubusercontent.com/assets/4803230/20231728/80f303d8-a829-11e6-87a4-c09267b1eff6.gif)

**Comment by davidschober** [comment]
closing this for 6.x it's working as it works on blacklight core.

**Comment by mcwhitaker** [comment]
The problem still occurs in mallorn on windows 10 with firefox (several last versions):

![mallorn](https://user-images.githubusercontent.com/16720883/30937541-1be87f04-a3a5-11e7-85e2-ffa1e0bec6b3.gif)
