### ISSUE TITLE
Can't upload Video files in to Avalon Media Systems version 5.1

### ISSUE THREAD

**Issue by jogiraju** [avalonmediasystem/avalon#1081]
Hi, I have installed Avalon Media Systems Version 5.1 successfully on CentOS 6 using puppet installation option. I was able to upload audio files (tried mp3) without any error and could playback using the Avalon Web Interface. However, I was not able to upload Video files (mp4, flv, etc.). It is giving an internal server error (504). The same thing happened with Avalon VirtualBox appliance installation.

Can any body help ?

**Comment by cjcolvar** [comment]
If audio files are working for you, then I suspect the problem is with the video files you are trying to upload.  There could be a few reasons for your video files not working: file is too large, special characters in the filename, or unsupported codecs.  Try uploading our test video (https://github.com/avalonmediasystem/avalon/raw/master/spec/fixtures/videoshort.mp4) and see if that works.

**Comment by jogiraju** [comment]
I installed avalon using manual instructions. I created a sample collection
and an item. And when I uploaded your suggested video I got the following
error output:

NoMethodError in MasterFilesController#create undefined method `[]' for
nil:NilClass
Extracted source (around line *#483*):

481482483484485486

  def mediainfo
    @mediainfo ||= Mediainfo.new file_location
  end
  def find_frame_source(options={})

Rails.root: /var/www/avalon
Application Trace <http://localhost/master_files#> | Framework Trace
<http://localhost/master_files#> | Full Trace
<http://localhost/master_files#>

app/models/master_file.rb:483:in `new'
app/models/master_file.rb:483:in `mediainfo'
app/models/master_file.rb:619:in `reloadTechnicalMetadata!'
app/models/master_file.rb:132:in `setContent'
app/controllers/master_files_controller.rb:191:in `block in create'
app/controllers/master_files_controller.rb:179:in `each'
app/controllers/master_files_controller.rb:179:in `create'
lib/avalon/stream_auth.rb:55:in `call'

Request

*Parameters*:

{"utf8"=>"✓",
 "authenticity_token"=>"0r+wVmuRSadZ5T1U2arAwr5lKGUNdTr24IPVQpcfmEg=",
 "container_id"=>"avalon:2",
 "step"=>"file_upload",
 "upload_file"=>"upload_file",
 "Filedata"=>[#<ActionDispatch::Http::UploadedFile:0x007f3fea1aa910
@tempfile=#<Tempfile:/tmp/RackMultipart20160824-24224-1k4id1i
(closed)>,
 @original_filename="videoshort.mp4",
 @content_type="video/mp4",
 @headers="Content-Disposition: form-data; name=\"Filedata[]\";
filename=\"videoshort.mp4\"\r\nContent-Type: video/mp4\r\n">],
 "id"=>"avalon:2",
 "original"=>""}

Toggle session dump <http://localhost/master_files#>
Toggle env dump <http://localhost/master_files#>

Please help

**Comment by jogiraju** [comment]
Full trace :
NoMethodError in MasterFilesController#create undefined method `[]' for
nil:NilClass
Extracted source (around line *#483*):

481482483484485486

  def mediainfo
    @mediainfo ||= Mediainfo.new file_location
  end
  def find_frame_source(options={})

Rails.root: /var/www/avalon
Application Trace <http://localhost/master_files#> | Framework Trace
<http://localhost/master_files#> | Full Trace
<http://localhost/master_files#>

mediainfo (0.7.2) lib/mediainfo.rb:105:in `version'
mediainfo (0.7.2) lib/mediainfo.rb:446:in `mediainfo_version'
mediainfo (0.7.2) lib/mediainfo.rb:379:in `initialize'
app/models/master_file.rb:483:in `new'
app/models/master_file.rb:483:in `mediainfo'
app/models/master_file.rb:619:in `reloadTechnicalMetadata!'
app/models/master_file.rb:132:in `setContent'
app/controllers/master_files_controller.rb:222:in `block in create'
app/controllers/master_files_controller.rb:217:in `each_value'
app/controllers/master_files_controller.rb:217:in `create'
actionpack (4.0.13)
lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (4.0.13) lib/abstract_controller/base.rb:189:in `process_action'
actionpack (4.0.13) lib/action_controller/metal/rendering.rb:10:in
`process_action'
actionpack (4.0.13) lib/abstract_controller/callbacks.rb:18:in `block
in process_action'
activesupport (4.0.13) lib/active_support/callbacks.rb:414:in `block
in _run__1516668536162223381__process_action__callbacks'
activesupport (4.0.13) lib/active_support/callbacks.rb:215:in
`_conditional_callback_around_68'
activesupport (4.0.13) lib/active_support/callbacks.rb:393:in
`_run__1516668536162223381__process_action__callbacks'
activesupport (4.0.13) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.13) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (4.0.13) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (4.0.13)
lib/action_controller/metal/instrumentation.rb:31:in `block in
process_action'
activesupport (4.0.13) lib/active_support/notifications.rb:159:in
`block in instrument'
activesupport (4.0.13)
lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (4.0.13) lib/active_support/notifications.rb:159:in `instrument'
actionpack (4.0.13)
lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (4.0.13)
lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
activerecord (4.0.13)
lib/active_record/railties/controller_runtime.rb:18:in
`process_action'
actionpack (4.0.13) lib/abstract_controller/base.rb:136:in `process'
actionpack (4.0.13) lib/abstract_controller/rendering.rb:44:in `process'
actionpack (4.0.13) lib/action_controller/metal.rb:195:in `dispatch'
actionpack (4.0.13)
lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
actionpack (4.0.13) lib/action_controller/metal.rb:231:in `block in action'
actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:82:in `call'
actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:50:in `call'
actionpack (4.0.13) lib/action_dispatch/journey/router.rb:71:in `block in call'
actionpack (4.0.13) lib/action_dispatch/journey/router.rb:59:in `each'
actionpack (4.0.13) lib/action_dispatch/journey/router.rb:59:in `call'
actionpack (4.0.13) lib/action_dispatch/routing/route_set.rb:676:in `call'
xray-rails (0.1.15) lib/xray/middleware.rb:37:in `call'
omniauth (1.2.2) lib/omniauth/strategy.rb:404:in `call_app!'
omniauth-identity (1.1.1) lib/omniauth/strategies/identity.rb:43:in
`other_phase'
omniauth (1.2.2) lib/omniauth/strategy.rb:185:in `call!'
omniauth (1.2.2) lib/omniauth/strategy.rb:164:in `call'
meta_request (0.3.4)
lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
meta_request (0.3.4)
lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
rack (1.5.5) lib/rack/etag.rb:23:in `call'
rack (1.5.5) lib/rack/conditionalget.rb:35:in `call'
rack (1.5.5) lib/rack/head.rb:11:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/flash.rb:241:in `call'
rack (1.5.5) lib/rack/session/abstract/id.rb:225:in `context'
rack (1.5.5) lib/rack/session/abstract/id.rb:220:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/cookies.rb:486:in `call'
activerecord (4.0.13) lib/active_record/query_cache.rb:36:in `call'
activerecord (4.0.13)
lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in
`call'
actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:29:in
`block in call'
activesupport (4.0.13) lib/active_support/callbacks.rb:373:in
`_run__3305679312891721272__call__callbacks'
activesupport (4.0.13) lib/active_support/callbacks.rb:80:in `run_callbacks'
actionpack (4.0.13) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/reloader.rb:64:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
actionpack (4.0.13)
lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
actionpack (4.0.13)
lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
railties (4.0.13) lib/rails/rack/logger.rb:38:in `call_app'
railties (4.0.13) lib/rails/rack/logger.rb:20:in `block in call'
activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in
`block in tagged'
activesupport (4.0.13) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (4.0.13) lib/active_support/tagged_logging.rb:68:in `tagged'
railties (4.0.13) lib/rails/rack/logger.rb:20:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/request_id.rb:21:in `call'
rack (1.5.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.5.5) lib/rack/runtime.rb:17:in `call'
activesupport (4.0.13)
lib/active_support/cache/strategy/local_cache.rb:83:in `call'
rack (1.5.5) lib/rack/lock.rb:17:in `call'
actionpack (4.0.13) lib/action_dispatch/middleware/static.rb:84:in `call'
rack (1.5.5) lib/rack/sendfile.rb:112:in `call'
railties (4.0.13) lib/rails/engine.rb:511:in `call'
railties (4.0.13) lib/rails/application.rb:97:in `call'
railties (4.0.13) lib/rails/railtie/configurable.rb:30:in `method_missing'
lib/avalon/stream_auth.rb:55:in `call'
passenger (5.0.30)
src/ruby_supportlib/phusion_passenger/rack/thread_handler_extension.rb:97:in
`process_request'
passenger (5.0.30)
src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:160:in
`accept_and_process_next_request'
passenger (5.0.30)
src/ruby_supportlib/phusion_passenger/request_handler/thread_handler.rb:113:in
`main_loop'
passenger (5.0.30)
src/ruby_supportlib/phusion_passenger/request_handler.rb:416:in `block
(3 levels) in start_threads'
passenger (5.0.30)
src/ruby_supportlib/phusion_passenger/utils.rb:113:in `block in
create_thread_and_abort_on_exception'

Request

*Parameters*:

{"utf8"=>"✓",
 "authenticity_token"=>"0r+wVmuRSadZ5T1U2arAwr5lKGUNdTr24IPVQpcfmEg=",
 "workflow"=>"",
 "container_id"=>"avalon:8",
 "selected_files"=>{"0"=>{"url"=>"file:///var/avalon/dropbox/My_Videos/videoshort.mp4",
 "file_name"=>"videoshort.mp4"}}}

**Comment by jogiraju** [comment]
I verified mediainfo gem is installed correctly. In the manual installation
I am getting the above error for both video and audio file uploads.

In the Avalon Virtual Appliance Installation I verified with your sample
video file. It gives the same error.

**Comment by bkeese** [comment]
When you run mediainfo --version, what version do you get? If it fails to find mediainfo, you’ll need to install mediainfo itself (yum install mediainfo).

-Brian

Brian Keese
Programmer/Analyst: Digital Media Applications
Indiana University Library Technologies
Bloomington, Indiana
