### ISSUE TITLE
[Marker] User is able to enter invalid time on editing existing marker.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1083]
Environment:- mallorn.dlib.indiana.edu
                       media.dlib.indiana.edu
                       All Devices/ Browsers

Steps to Reproduce

1. Launch URL on any browser mentioned above.
2. Login with valid credentials and access Playlists from nav bar.
3. Access and play any playlist.
4. Access video with marker.
5. Edit existing marker.
6. Enter invalid time.

Observe User is able to enter invalid length under time and save.

Please refer link below for video:-

https://drive.google.com/drive/folders/0B-Lv-tiSRqEuMEtlMkYyRkVUYlE

Video name :- Marker_time

**Done looks like**

User should not be able to enter invalid length under time.

**Comment by csyversen** [comment]
so i found out the app doesn't actually update the marker time if it's invalid, but it doesn't communicate the error condition back to the user at all. I'm working on that now
