### ISSUE TITLE
As a SaaS customer, I want transcoding services that are not prohibitively expensive

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1093]
### So That
I can use the SaaS model.

### Done looks like

- [x] get a sense of pricing for AWS Elastic Transcoding 
- [x] place real numbers from NU's pilot in document. 
- [x] if needed, suggest an alternative that makes pricing acceptable and SaaS still a desirable solution

**Comment by joncameron** [comment]
We'll check this one off when we have real numbers for transcoding.

**Comment by mcwhitaker** [comment]
250 days of video - 20K to transcode all of that
