### ISSUE TITLE
Accordion in Structural Metadata Visual Editor Collapses Prematurely

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1102]
### Environment

Avalon 5.1.4 on Mallorn
### Steps to Reproduce
1. Launch the structural metadata editor from the Edit page of a media object
2. Place the cursor in the XML on an empty line
3. Click "Span" under the "Add Top Element" accordion
4. Click "label" under the "Add Attribute" accordion
5. The "Add Attribute" accordion goes gray and collapses
### Done Looks Like

When an attribute is added, the "Add Attribute" accordion should remain open so "begin" or "end" values can be added by clicking the buttons under the accordion.

**Comment by davidschober** [comment]
Won't fix, pivoted Structural Metadata Editor.
