### ISSUE TITLE
Collection class predicate review

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1108]
- [ ] name - http://purl.org/dc/terms/title (dcterms:title)
- [x] unit - http://id.loc.gov/ontologies/bibframe/heldBy (bf:heldBy) (value needs to be URI, such as http://id.loc.gov/authorities/names/no2006117440)
- [x] description - http://purl.org/dc/terms/description (dcterms:description)

Properties that do not have a mapping to an external ontology:

- dropbox_directory_name
- default_read_users
- default_read_groups
- default_visibility
- default_hidden

**Comment by mbklein** [comment]
@jlhardes: Is `isPartOf` the right choice for the name of the collection? This isn't how we're linking the item to the collection; this is just the collection asserting its own name.

**Comment by jenyoung** [comment]
@jlhardes By name, do you really mean title of a collection and want to use http://purl.org/dc/terms/title instead?

**Comment by mbklein** [comment]
Yes. Collection#name is really the title. :) But we call it name, because we're bad like that.

**Comment by cjcolvar** [comment]
Should we change it to title?

**Comment by jlhardes** [comment]
The avalon predicate is "name" and it is meant to be the collection title. I went the wrong direction trying to think of these predicates in terms of the digital media object (like the DPLA MAP does) when they are actually just predicates for the collection as its own thing, so dcterms:isPartOf is not the predicate we want to use. Since this is the title of the collection, Jen is right, we should go with http://purl.org/dc/terms/title (dcterms:title) instead. I'm updating the checklist.

@cjcolvar the avalon predicate should go away once we change this over so I don't think it matters, as long as Michael knows what to change.

**Comment by mbklein** [comment]
I think @cjcolvar is asking if we should change the Collection property name to `title`, since we're using the `dcterms:title` predicate. I don't think it matters one way or the other.

**Comment by jlhardes** [comment]
OK, that makes sense. And I think I accidentally deleted one of the comments on this issue but I'm not sure, it kind of looks like everything is still there?
