### ISSUE TITLE
Previous track remains highlighted sometimes when user accesses new track from different section.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1109]
Environment:- mallorn.dlib.indiana.edu
                       media.dlib.indiana.edu

**Steps to Reproduce**
1. Launch URL in any browser.e.g:- Chrome
2. Access any audio or video with multiple sections.
3. While it's playing, switch sections and track randomly.
4. Repeat step 3 (4- 5 times)

Observe sometimes player shows previous track highlighted (time is correct on progress bar) even though new track from different section is accessed.

**Note**:- Repeatability of this issue is 2/5.

**Done looks like**
Correct track from section should be highlighted when user accesses it.

**Comment by joncameron** [comment]
Stale—will reopen if reported again.

**Comment by cjcolvar** [comment]
@joncameron @davidschober Should we also remove this from the Known Issues?

**Comment by joncameron** [comment]
Removed from Known Issues.
