### ISSUE TITLE
Closed captions aren't visible for audio files in the embedded view.

### ISSUE THREAD

**Issue by mikedurbin** [avalonmediasystem/avalon#1110]
I suspect they're being rendered off of the top of the page.

**Comment by davidschober** [comment]
@anirudhpillai16 can you reproduce this?

**Comment by davidschober** [comment]
Closed captions currently aren't being supported on audio. We will grab for release 7.0

**Comment by joncameron** [comment]
This will need a lot more teasing out before design and implementation, if we decide to do this. As it stands it feels very low priority and may be done with means beyond just what Avalon provides in an iframe player.
