### ISSUE TITLE
Discuss video sitemaps and schema.org metadata for videos

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1115]
See https://groups.google.com/forum/#!msg/iiif-discuss/Y42yd2hjkjM/llKIlJZiBwAJ for relevant discussion

**Comment by jlhardes** [comment]
Is this still relevant/needed?

**Comment by cjcolvar** [comment]
We already have some schema.org meta tags but we'll need to revisit them when we work on these other related (and potentially duplicative) issues:
https://github.com/avalonmediasystem/avalon/issues/2175
https://github.com/avalonmediasystem/avalon/issues/2176
"rich media metadata/previews (not IIIF)" mentioned for 0.2 at the F2F but I don't see an issue for it yet

**Comment by davidschober** [comment]
3 year old discussion, abandoned.
