### ISSUE TITLE
deploy to nutest on commit to develop?

### ISSUE THREAD

**Issue by csyversen** [avalonmediasystem/avalon#1142]
We were tossing around this idea of keeping nutest and spruce in sync. We could have travis deploy to nutest upon a successful build maybe?

**Comment by mbklein** [comment]
nutest has some customizations (notably ldap auth and pgsql db), but we can probably figure something out.

**Comment by davidschober** [comment]
adding jim as an assignee

**Comment by csyversen** [comment]
were we talking about spinning up a new nutest server? or am i making things up?

**Comment by davidschober** [comment]
I thought we were talking about nuking the current one.. Correct @mbklein?

**Comment by davidschober** [comment]
moving into sprint 113. Wasn't ready for sprint 112.
