### ISSUE TITLE
Spruce Has IP Permissions Error

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1143]
When creating a new collection in Spruce:

Started POST "/admin/collections.json" for IP_REMOVED at 2016-09-14 11:13:39 -0400
Cannot render console from IP_REMOVED! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255
Processing by Admin::CollectionsController#create as JSON
  Parameters: {"utf8"=>"✓", "admin_collection"=>{"managers"=>["archivist1@example.com"], "name"=>"Carrick Test", "description"=>"Test", "unit"=>"Default Unit"}, "commit"=>"Create Collection"}
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
Processing by Admin::CollectionsController#create as JSON
  Parameters: {"utf8"=>"✓", "admin_collection"=>{"managers"=>["archivist1@example.com"], "name"=>"Carrick Test", "description"=>"Test", "unit"=>"Default Unit"}, "commit"=>"Create Collection"}
  User Load (0.1ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
Completed 500 Internal Server Error in 16ms (ActiveRecord: 0.1ms)
Completed 500 Internal Server Error in 15ms (ActiveRecord: 0.1ms)

**Comment by davidschober** [comment]
This is currently not blocking anything right now. Carrick will check and close.
