### ISSUE TITLE
Add Marker Icon Moves Outside Of Media Player

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1155]
### Environment 
Firefox 48.0.1 on OS 10.11.6

### Steps to Reproduce
* Go to a Playlist item in a Playlist
* Size the browser window so that the media player is slightly less than maximum width
* Expand the "Source Item Details" section of the accordion element beneath the media player
* The "Add Marker" icon breaks out of the media player area and wraps down into the accordion div

### Example
![GIF](https://cloud.githubusercontent.com/assets/1406618/18645103/dd175242-7e79-11e6-955d-893fe9f7b5ba.gif)

**Comment by bkeese** [comment]
Also affects the 'Add to Playlist' button. And it has only to do with the window width. In the example above, the scrollbar is affecting the width when the Source Item Details section is expanded.  On my Windows 7, Chrome browser, it can easily be seen by slowing changing the width of the browser window.  The button moves in and out of its correct position as the width changes. Seems like some sort of rounding error.

**Comment by bkeese** [comment]
A fix for this is in the master branch of avalonmediasystem/mediaelement_rails. Palm is currently using the captions branch, which does not have this fix.

**Comment by joncameron** [comment]
I tested 10/14/2016 on Spruce and this bug reappeared for me. I tried in both Firefox and Chrome on macOS.

**Comment by bkeese** [comment]
@joncameron can you give a link to the item you're seeing this on?

**Comment by joncameron** [comment]
@joncameron Put a specific example to an item here for further review.
