### ISSUE TITLE
As a database admin I want Avalon to clean up its Active Record Session Data

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1167]
## So That

Avalon no longer creates session tables in SQL that are millions of rows long and are problematic for running queries against.
## Done Looks Like
- [ ] A rake that task that cleans out all sessions that are over X days old and runs every Y hours (using schedule.rb)
- [ ] An easy way for a sysadmin to configure X days and Y hours in the Avalon config files.

**Comment by davidschober** [comment]
@carrickr is this causing major issues?

**Comment by joncameron** [comment]
Stale—closing.
