### ISSUE TITLE
As a user I want to be able to use Avalon even though my LDAP groups have bad characters in their names

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1176]
## So That

Even when people are bad and make LDAP groups with special characters ( ) [ ] { } etc in them, these are escaped prior to doing permissions look up in solr.  Otherwise the solr query bombs.

## Done Looks Like

Even though MS says they aren't allowed, [special characters](http://social.technet.microsoft.com/wiki/contents/articles/11216.active-directory-requirements-for-creating-objects.aspx) are escaped in solr queries.

Note:  This was hacked into 5.x for production purposes but needs to be done right in 6.0.

**Comment by mcwhitaker** [comment]
@carrickr  Needs Review: technical or QA? If QA, how might one test this?

**Comment by davidschober** [comment]
We have to verify in 6.0
