### ISSUE TITLE
[6.0 Specific]:- Page freezes when user accesses "Open Dropbox" while uploading video.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1177]
Environment:- spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**

1. Launch URL on any browser.e.g:- Chrome.
2. Login with valid credentials.
3. Navigate to Manage content and create new collection or use existing collection.
4. Create new item.
5. Access "Open Dropbox" from Manage files page.

Observe page freezes and user is not able to upload video from Dropbox.

Note:-  This issue is not observed on mallorn.dlib.indiana.edu

**Done looks like**
User should be able to upload videos from Dropbox without any freeze on the page.

**Comment by anirudhpillai16** [comment]
Please refer screenshot for details:


![freeze_dropbox](https://cloud.githubusercontent.com/assets/15963595/18848382/193aa22e-83fc-11e6-9a88-add01061b3e9.jpg)

**Comment by bkeese** [comment]
This was a configuration issue on spruce. It should work now (but there are currently no items in the dropbox).

**Comment by anirudhpillai16** [comment]
Open Dropbox is working fine now. Issue is no longer reproducible and can be closed.
