### ISSUE TITLE
[6.0 Specific]:- Error Message is displayed when user tries to Import using Biblographic id.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1178]
Environment:- spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**

1. Launch URL on any browser.
2. Login with valid credentials.
3. Navigate to Manage content and create new collection or use existing collection.
4. Create new item and upload any video.
5. Enter Bibliographic id and click Import.

Observe error message when user tries to import using Bibliographic id.

**Done looks like**
User should be able to auto-fill fields by importing using Bibliographic id.

Please refer attached screenshot for details:

**Comment by anirudhpillai16** [comment]
![import_biblographic](https://cloud.githubusercontent.com/assets/15963595/18848711/9da2e020-83fd-11e6-8db5-9210ec68b86e.jpg)

**Comment by mcwhitaker** [comment]
This worked for me today on the three items I created via uploading to my collection.

**Comment by anirudhpillai16** [comment]
Issue is no longer reproducible hence closing it.
