### ISSUE TITLE
[6.0 Specific]:- Error Message is thrown when user accesses "View Raw Metadata" under any video.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1181]
Environment:- spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**

1. Launch URL on any browser.e.g:- Chrome.
2. Login with valid credentials.
3. Access and play any video.
4. Access " View Raw Metadata".

Observe Error message is thrown on accessing "View Raw Metadata" under any video.

Note:- Issue is not reproducible on mallorn.

**Done looks like**
User should be able to access and view Raw Metadata information.

Please refer attached screenshot for details:-

**Comment by anirudhpillai16** [comment]
![view_raw_metadata](https://cloud.githubusercontent.com/assets/15963595/18850706/aed27028-8406-11e6-9bf9-f7a8f6f799c5.jpg)

**Comment by kdid** [comment]
This is fixed with #1179 and was merged to develop.
