### ISSUE TITLE
Player API

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1185]
We have several use cases come up that we need to address of applications that embed an Avalon player and need to control the player by calls to an API. The API will need to handle calls to:

- [ ] start the player
- [ ] stop the player
- [ ] read the player's current offset
- [ ] set the player's current offset
- [ ] loop player

**Comment by davidschober** [comment]
Example: Vimeo API

https://player.vimeo.com/playground

**Comment by davidschober** [comment]
closing as dupe
