### ISSUE TITLE
[6.0-specific]: Help tips not showing

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1191]
In the Resource Description page, the "?" icons are not showing the corresponding tips when clicked on. Instead, the cursor moves to the corresponding field, which gets highlighted.

The attached image is from mallorn, where the help text is displayed correctly.

**Comment by mcwhitaker** [comment]
![capture](https://cloud.githubusercontent.com/assets/16720883/18889688/1087a7fa-84cc-11e6-9c22-2b5c2fce56b5.PNG)

**Comment by anirudhpillai16** [comment]
This issue is no longer reproducible hence closing it.
