### ISSUE TITLE
[6.0-specific]: Conversion process issue

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1192]
URL:- spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**

1. Access URL in any browser.
2. Login with valid credentials.
3. Create New item in any collection by uploading any video or audio.
4. Wait for Conversion process.

 The conversion scrubber never shows the item being processed and we don't get the sense that the transcoding worked. 

Note:- 1. When going to the item via browsing the collection, one sees the item there. However, the player starts from 00:02 instead of 00:00. 
2. Issue is not reproducible on mallorn.

**Done looks like**
Conversion process should show progress to notify user .

Please refer attached screenshot for details:

**Comment by mcwhitaker** [comment]
![capture](https://cloud.githubusercontent.com/assets/16720883/18890971/693d1e16-84d1-11e6-9a2c-880cd218643c.PNG)

**Comment by mcwhitaker** [comment]
I have looked at items uploaded by other users and none of them starts playing at 00:00.

**Comment by davidschober** [comment]
Backlog Refinement:
CC: Reload of page gives progress. It also seems like if we reload the app it drops it. There are some quirks that... Breaking out it
