### ISSUE TITLE
[6.0-specific]: Thumbnail/poster generator not working

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1193]
Environment:- spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**

1. Access URL in any browser.
2. Login with valid credentials.
3. Play any video from any Collection.
4. Try clicking on "Create thumbnail" button (Camera button)

The camera icon used for generating the thumbnail and poster images is not working in spruce. Nothing happens when you click on it. As a consequence, all items in any of the collections there currently do not have thumbnails and posters.

**Done looks like**
User should be able to create thumbnail and thumbnails should be displayed for all videos.

Please refer attached screenshot for details:

![capture](https://cloud.githubusercontent.com/assets/16720883/18891411/1b17ac86-84d3-11e6-9b61-d6848ba22069.PNG)

**Comment by bkeese** [comment]
I thought this was fixed a while ago, but the reason the create-thumbnail button isn't working is that there is no poster to begin with, which is a problem with ingest (which I thought was fixed recently in the R6 branch).

**Comment by mcwhitaker** [comment]
@bkeese Is the ingest issue you are referring to the same reported on #1192 ?

**Comment by bkeese** [comment]
Possibly, though that one suggests that ingest fails completely. I'm referring to a more specific problem of posters and thumbnails not being generated on ingest.

**Comment by mcwhitaker** [comment]
@bkeese It does not fail completely. It actually succeeds as later in the ticket I say that after browsing to the item I can play actually it but it starts playing from 00:02 instead of 00:00. 
The two issues may be related.

**Comment by cjcolvar** [comment]
The configuration appears to be fine.   If you enter a time different than the default of 2 sec on the manage files page and save it will generate poster and thumbnail and save it in fedora.  So what needs to be fixed is making this fire by default when processing finishes, fixing the search results so it shows the thumbnail, and making sure the camera grab tool works once these other two are fixed.  (It could be that the thumbnail doesn't work if the poster/thumbnail have never been generated.)

**Comment by bkeese** [comment]
thumbnails and posters are now being generated automatically. the thumbnail button works insofar as the dialog appears with the correct snapshot. It also save the new poster image. however, the old thumbnail continues to appear in search results.

**Comment by bkeese** [comment]
Also, the new thumbnail is saved in fedora, even though the old one shows in search results.

**Comment by bkeese** [comment]
Today when I tested this again, the thumbnail appears as it should. Poster too. I think this is good to go.

**Comment by mcwhitaker** [comment]
@bkeese Brian, in spruce I was not able to create a new poster/thumbnail for this item: https://spruce.dlib.indiana.edu/media_objects/b6%2F4e%2F05%2F72%2Fb64e0572-8f3d-406c-9152-f8e2629966f4 (currently item #8 in Leah's collection). I clicked the camera icon multiple times and it did not do anything.

It does not have a poster or thumbnail to begin with. Does it need the upload to generate the first one before you can "change" it?

**Comment by bkeese** [comment]
I think this is one that was imported before poster/thumbnail ingest was fixed. So, you're right, since it never had a poster, a new one cannot be selected.
