### ISSUE TITLE
[6.0 Specific]:- Error Message is displayed when accesses Import under Bibliographic ID without any input.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1195]
Environment:-  spruce.dlib.indiana.edu
Devices:- All Devices/Browsers
**Steps to Reproduce**

1.Launch URL on any browser.
2.Login with valid credentials.
3.Navigate to Manage content and create new collection or use existing collection.
4.Create new item and upload any video.
5.Click import without input (or with blank field)

Observe "NoMethodError inMediaObjectsController#update" error on accessing import after leaving field blank.

Note:- Proper error message is thrown on performing same steps on mallorn.

**Done looks like**
Proper error message should be shown to user when fields are incomplete. 

Please refer attached screenshots for error messages on mallorn and spruce.

**Comment by anirudhpillai16** [comment]
![spruce](https://cloud.githubusercontent.com/assets/15963595/18926224/f85c1f1c-8584-11e6-9ee3-3cad306b713e.jpg)
![mallorn](https://cloud.githubusercontent.com/assets/15963595/18926225/fb332dfc-8584-11e6-8b4b-7b61a6695656.jpg)

**Comment by davidschober** [comment]
Discussion: Possibly disable the import the button when the field is empty and then handle better when there's bad data in the field.

**Comment by anirudhpillai16** [comment]
Import button is disabled when there is no input hence closing this issue.

![fixed_biblographic_id](https://cloud.githubusercontent.com/assets/15963595/19660219/e2e690fe-99fc-11e6-9b60-fb28c98f11c2.jpg)
