### ISSUE TITLE
Investigate Why Playback Starts from something other than zero on Spruce

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1198]
When a user loads a page and presses play it starts from other than 0.0
- [ ] Investigate whether this due to Red5. If so, kill. 
- [ ] Investigate on Lancelot with specific files. (pull from #1192

**Comment by carrickr** [comment]
This seems to be a Red 5 thing, we've seen the same on Lancelot before.  It happens currently on avalon:426 on Lancelot (jumps directly to two seconds)

http://i.imgur.com/FxLjXFL.png

Does not seem to happen on anything running Wowza or AMS

**Comment by lealeelu** [comment]
It's not happening on the test servers that run on Wowza and AMS. This is a Red5 issue.
