### ISSUE TITLE
Web Upload Creates Master File Even If File Is Too Large

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1201]
## Steps to Reproduce
1. Get a file that is over 250 MB
2. Upload it to Spruce
3. You'll see a flash message saying the file  was too large
4. An empty master file is created

## Done Looks Like
A master file should not be created if the file size is too large for web upload; it should simply not create that object at all.

**Comment by joncameron** [comment]
Might be part of a larger issue; needs more review.

**Comment by joncameron** [comment]
Stale bug.

**Comment by joncameron** [comment]
@cjcolvar Couldn't reproduce. Master file wasn't created. Uploading a 3 GB video I got this response:
<img width="554" alt="Screen Shot 2019-05-23 at 3 06 50 PM" src="https://user-images.githubusercontent.com/1406618/58279526-a2a25b80-7d6c-11e9-88f4-b7c8a75d6e27.png">

And then then back on the item's edit page, nothing present:
<img width="581" alt="Screen Shot 2019-05-23 at 3 08 54 PM" src="https://user-images.githubusercontent.com/1406618/58279573-bcdc3980-7d6c-11e9-989f-09b2aa70f181.png">
