### ISSUE TITLE
As a sysadmin I want better purging of Avalon's Session Table

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1220]
## So That

We don't have a bunch of stale sessions hanging out in Avalon and potential security flaws due to session IDs being a month or two old.
## Done Looks Like
- [ ] Any session that has not been modified in more than 48 hours is purged automatically by a chron job
- [ ] Any session whose creation date is more than 7 days old is purged automatically by a chron job
- [ ] These changes are documented somewhere on the wiki so that other adopters who about this behavior

**Comment by joncameron** [comment]
Stale (and perhaps no longer an issue?)—closing.
