### ISSUE TITLE
[6.0 Specific]:- No confirmation message is shown to user before deleting playlist.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1227]
Environment:- https://spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**

1. Launch URL in any browser.e.g:- Chrome
2. Login with valid credentials.
3. Navigate to Playlist page.
4. Try deleting existing playlist by clicking delete button.

Observe playlist is deleted without any confirmation.

Note:-

1. Same behavior is observed when playlist is deleted from edit playlist page.
2. This issue is not reproducible on mallorn.

**Done looks like**

Confirmation message should be thrown to user before deleting playlist.

Please refer screenshot for confirmation on mallorn:

![mallorn_confirmation](https://cloud.githubusercontent.com/assets/15963595/19128051/9f4ef512-8b0f-11e6-8671-fe16750708bb.jpg)

**Comment by joncameron** [comment]
@anirudhpillai16 Please check whether this same issue occurs when deleting a masterfile from a media object and create a new item if needed.

**Comment by anirudhpillai16** [comment]
@joncameron :- observed same behavior on deleting master file from media object hence created https://github.com/avalonmediasystem/avalon/issues/1282

**Comment by lealeelu** [comment]
Verified it works on the develop branch. Brian thinks it's because of the asset pipeline pull request Chris did earlier fixed it. It's also fixed on the masterfile deletion too.
