### ISSUE TITLE
Discuss Testing Strategy

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1229]
The team needs to discuss general testing strategy, both for the 6.0 release and the migration tool.
- [x] schedule meeting with @anirudhpillai16 @mcwhitaker  @joncameron @carrickr 
- [x] @phuongdh investigating how to restore hemlock
- [x] write tasks to complete
- Who will do testing?
- How will we track it?
- Will we use previous methods (spreadsheet with manual steps) or an alternative method?
- What template for bug reporting should be created/used/followed?
- How will we do migration tool testing? (Hemlock?)

**Comment by davidschober** [comment]
@anirudhpillai16 can you update with your schedule?

**Comment by anirudhpillai16** [comment]
Monday: - 1 pm - 5 pm 
Wednesday: - 1 pm - 5 pm
Thursday :- 9:30 am - 1:30 pm

**Comment by joncameron** [comment]
One thing that we'll need to test: bad group names in LDAP (characters that throw an error in Avalon). This has been a major issue in IU production instances and we'll need to test that the fix we've done is also working in 6.0.
