### ISSUE TITLE
[6.0 Specific]:- User is unable to delete collection if collection has untitled video under it.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1231]
Environment:- https://spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**
1. Launch URL on any browser.e.g:- Chrome.
2. Login with valid credentials.
3. Upload video to collection and don't provide any title or choose any collection with untitled video.
4. Try deleting collection and moving its content to different collection.

Observe error message is displayed when user tries to delete collection with untitled video under it.

Note:- This issue is also reproducible on mallorn but error message is different.

**Done looks like**
User should be able to delete particular collection and move its item to different collection.

Please refer attached screenshot for details:-
![error_message](https://cloud.githubusercontent.com/assets/15963595/19161302/41adcf98-8bc1-11e6-874b-fafda28a29c8.jpg)

**Comment by davidschober** [comment]
Discussion:

Having deal with valid or invalid objects. We are allowing anything to be invalid. We should be stricter about things being invalid now.

**Comment by joncameron** [comment]
I've looked at and approved of this change. All good! In the future we'd like to go back to the drawing board regarding workflow of object creation and validation, but for right now this is an edge case and I'm happy enough with the error message displaying in this particular case.
