### ISSUE TITLE
[6.0 Specific] [Minor issue]:- Moving Image and Sound Recording under Format should have first letter capitalized.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1232]
Environment:- https://spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**
1. Launch URL on any browser.e.g:- Chrome.
2. Expand Format under Browse by on the left side.

Observe moving image and sound recording are in lower case.

Note:- Issue is not reproducible on mallorn. Both moving image and sound recording have first letters in upper case.

**Done looks like**
moving image and sound recording should have first letters in upper case.

Please refer attached screenshot for details:-
![format_lower_case](https://cloud.githubusercontent.com/assets/15963595/19161451/d23f802e-8bc1-11e6-9ca3-185cde4668a2.jpg)

**Comment by lealeelu** [comment]
I have a fix started in this pull request: https://github.com/avalonmediasystem/avalon/pull/1316
I need to do more testing once some other bugs are cleaned up.

**Comment by anirudhpillai16** [comment]
Issue is verified and found fixed hence closing it. Please refer screenshot for fix:

![fixed_capitalized](https://cloud.githubusercontent.com/assets/15963595/19863564/0f598f2e-9f6b-11e6-834e-603c8fc0fc0c.jpg)
