### ISSUE TITLE
As a devops person I want to dockerize all non Ruby services on Lancelot

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1234]
## So that

They are easier to manage and update using docker containers we'll be building anyway.
## Done Looks Like
- [ ] Red5 container for streaming
- [ ] matterhorn container for transcoding

**Comment by carrickr** [comment]
This either needs to be updated to be spruce or abandon

**Comment by davidschober** [comment]
Try on Lancelot first.

**Comment by phuongdh** [comment]
Lancelot is RHEL6, which doesn't support docker-compose very well. I tried upgrading Lancelot to 7 but had to give up mid way.  I'm doing this on an EC2 box instead.
