### ISSUE TITLE
Upload Text Is Lost After a Failed Upload

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1238]
## To Reproduce
1. Select a file that is too large (> 250 MB) and upload it Spruce
2. Select another file of the proper size and upload it.  With the error flash message on the screen, the Upload text is lost.

<img width="1221" alt="screen shot 2016-10-07 at 12 53 28 pm" src="https://cloud.githubusercontent.com/assets/5350060/19198455/41d3ce6a-8c8d-11e6-9999-85e2510a1a0d.png">

**Comment by davidschober** [comment]
discussion:

possibly a css bug.

**Comment by davidschober** [comment]
Possibly fixed. @anirudhpillai16 please reverify.

**Comment by anirudhpillai16** [comment]
Issue is verified and found fixed on spruce hence closing it. Please refer attached screenshot for fix:
![fixed_upload_button](https://cloud.githubusercontent.com/assets/15963595/19864425/9da3218e-9f6e-11e6-957e-66430df4736f.jpg)
