### ISSUE TITLE
As a developer I need to fix intermittent test failures

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1239]
This is more of an issue for discussion than any specific bug.  Originally in 6.0 we had not worried too much about the timeouts and other weirdness we had with tests intermittently failing on Travis since we planned to abandon the code.  Now with point releases for 6.0 coming out and potentially keeping the current codebase alive as a backend for an extended period of time, these failing tests become more of a blocker.  The developers should probably have a discussion about dealing with this generating actionable tickets.

- [ ] id tests that fail
- [ ] figure out how long it will take to fix
- [ ] move to pending if we decide not to fix them
- [ ] Check with MBK about RSPEC Bisect

**Comment by davidschober** [comment]
intermittent has become all the time. We've had red all week.

**Comment by davidschober** [comment]
@mbklein do you have data from RSPEC bisect?

**Comment by davidschober** [comment]
time boxed at big.

**Comment by cjcolvar** [comment]
These seem to have resolved themselves and most builds run successfully.
