### ISSUE TITLE
Update Release Documentation To Have Users Install Nginx, not Red5, for Streaming

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1242]
## Done Looks Like

Whereever we're hosting our 6.0 release documentation tells user to use Nginx, not Red5, for streaming.  Nginx install directions are at: https://github.com/avalonmediasystem/avalon/wiki/Installing-nginx-for-Avalon

**Comment by joncameron** [comment]
Changed to 6.x as we will be continuing to go with Red5 for R6.0.
