### ISSUE TITLE
Select All button missing from search results

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#1245]
In search results view, no 'Select All' button is present.

**Comment by davidschober** [comment]
@bkeese where is it missing from? Can you add a "to recreate"

**Comment by bkeese** [comment]
It's missing from the search results view. To recreate, log into spruce, click browse. At the top of the search results page, there should be a 'select all' button.

**Comment by bkeese** [comment]
![image](https://cloud.githubusercontent.com/assets/7440154/19286224/e0a68d6c-8fca-11e6-99a6-1ab1204ccf8f.png)
