### ISSUE TITLE
Scale Fedora horizontally on ECS

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1249]
### Description
Fedora scaled horizontally will improve performance and load, and may be worthwhile especially for large amounts of data.

### Done Looks Like
Setup a scalability-enabled Fedora. Notch8 has done this with EFS but said latency was too high. Erin has some luck with local EBS.

**Comment by phuongdh** [comment]
We need to make sure performance doesn't degrade on Fedora cluster, there's some report that it does with new Fedora . https://wiki.duraspace.org/display/FEDORA471/Response+Time+Comparison+of+Single+Fedora+VS+Cluster

**Comment by davidschober** [comment]
Abandoned. This isn't currently an issue.
