### ISSUE TITLE
Package 6.0 OVA

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#1253]
- [x] Use Packer to build an OVA with Docker and docker-compose
- [x] Remove firstboot script for simpler experience
- [x] Standup Avalon containers in OVA script
- [x] Update OVA
- [x] Get batch ingest running on OVA
- [x] Test OVA (moved to #1542)
- [x] Push OVA to server

**Comment by joncameron** [comment]
This needs to be broken out.

**Comment by joncameron** [comment]
@phuongdh Send me the OVA whenever it's ready and I should be able to test it out within a day or two.
