### ISSUE TITLE
Specs for Customer Dashboard for Avalon SaaS

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1254]
We need to have a better idea of what type of metrics we will provide to the SaaS pilot users. There may be some sort of google analytics mixed in with some AWS resource usage offerings.

**Comment by mcwhitaker** [comment]
@jwd  - At one point I thought that this was one of our deliverables, but after the last conversation with Lyrasis, I got the impression that this is actually one of their deliverables. Am I right?

**Comment by davidschober** [comment]
Lyrasis should handle this. It will fold into whatever billing and stats dashboard they offer.
