### ISSUE TITLE
[6.0 Specific]:- Uploading new video or removing existing video from collection throws error intermittently.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1269]
Environment :- https://spruce.dlib.indiana.edu
Browsers:- Chrome, Firefox, Safari, IE11, Edge

**Steps to Reproduce**
1. Launch URL on browser.e.g:- Chrome
2. Navigate to Manage content and access any collection.e.g:- Anirudh Test Collection.
3. Create an item.
4. Upload any video under 250 MB.

Alternate steps
3. Access any item under collection.
4. Try removing item from Manage files page.

Observe error message on trying to upload new video or delete existing video.

Note:- 1. This issue is not reproducible on mallorn.
2. Reproducibility for this issue is 60%.

**Done looks like**

User should be able to create or remove videos without any error messages.

Please refer attached screenshot for details:-

![upload_error_message](https://cloud.githubusercontent.com/assets/15963595/19361998/d102e5e8-9152-11e6-9e5a-aaeaa7b817df.jpg)
![error_destroy](https://cloud.githubusercontent.com/assets/15963595/19362037/f85aaf4a-9152-11e6-84b4-5dc1e40caf59.JPG)

**Comment by davidschober** [comment]
@anirudhpillai16 can you retest? is this still happening?

**Comment by anirudhpillai16** [comment]
Issue was not observed while testing hence closing it.
