### ISSUE TITLE
Create Simple Player API

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1271]
### Description
We want to create a simple player API that allows control of embedded players for use with tools like OHMs or other ad-hoc articles where a user might want to scan, play, or jump the player based on user input in text.

## Done Looks Like
A player API that allows via post:
- [x] start the player
- [x] stop the player
- [x] read the player's current offset
- [x] set the player's current offset
- [x] loop playback

## Use cases
Integration with OHMS (the Oral History Metadata Synchronizer)
Increased control for embedded media in partners like Cultural Anthropology, allowing them to provide enhanced navigation by elements outside the media player and for things like looped playback, playback beginning at a certain time point.

## Note
The basic set of functions above is very similar to existing APIs used by YouTube, Vimeo, Soundcloud etc.

**Comment by davidschober** [comment]
https://player.vimeo.com/playground

**Comment by davidschober** [comment]
per #1440 is media element's existing player enough (after we figure out the cross doc issue?

**Comment by bkeese** [comment]
An example embedded Avalon player that uses the new Avalon postMessage API can be seen here: https://wiki.dlib.indiana.edu/display/AvalonIU/Test+Embed

**Comment by davidschober** [comment]
Cool. I'll review today.

**Comment by joncameron** [comment]
@bkeese Awesome! Looks good and worked great for me on the Confluence page. So it's the case that our current mediaelement version doesn't support looping? And would there be any way to put in a workaround to make that happen in the current player even though there's no built-in way to do it?

**Comment by bkeese** [comment]
Looping is actually in the version of the player we're using, but I think we're doing something (something to do with play-though, I think) that breaks it. Will look into it further.

**Comment by davidschober** [comment]
@joncameron and @bkeese let's break out looping into a separate issue and move this to done.
