### ISSUE TITLE
Thumbnail disappears after moving item

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1275]
This is for R5.

In mallorn I moved an item from one collection to another. When I did that, the thumbnail disappeared. I moved it back to the original collection and the thumbnail is still missing. I then tried updating the poster image, which succeeded, but the thumbnail is still missing.

The item I used for this testing is avalon:8527 titled "Free demo video".

Ref #1066 (This was the story for fixing this bug in R6)

**Comment by cjcolvar** [comment]
I reindexed this one object from the console and then it started working again so I wonder if this is an issue with delayed_job running an old version of the code which indexes differently and not an actual code problem.

**Comment by davidschober** [comment]
@anirudhpillai16 can you verify fix?

**Comment by anirudhpillai16** [comment]
Issue is verified and found fixed on mallorn. Thumbnail no longer disappears when an item is moved from one collection to another hence closing this issue.
