### ISSUE TITLE
Meeting for  bullet points about docker/puppet

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1277]
Debs needs some information bout Docker/Puppet and the new  install methods.

**Comment by davidschober** [comment]
@mbklein can you add the bullets to this ticket for Debs?

**Comment by davidschober** [comment]
This was for a blog post.

**Comment by phuongdh** [comment]
Bullets about why we're moving away from Puppet, why Docker, how Docker will be used, possible production?

**Comment by davidschober** [comment]
get a 30 minute meeting on the table to knock this out. with @joncameron

**Comment by Debs4Avalon** [comment]
From @mbklein: 
Docker images are small, efficient, self-contained applicaton instances with minimal OS overhead and all their dependencies. They’re quicker and easier to set up, tear down, scale, deploy, move, and replace than puppet-based instances.
 
Puppet is great for maintaining a given server in a well-defined state and making sure things don’t get changed that shouldn’t. It would be a great mechanism for deploying a Dockerized Avalon to one or more servers. But as a primary deployment mode, it’s proven to be complicated, cumbersome, and time consuming to maintain.
 
Is that enough?

**Comment by phuongdh** [comment]
@Debs4Avalon I feel like we should mention that our Docker stuff currently is a way for people to quickly try Avalon, it isn't production-ready. Also Docker makes building the OVA a breeze using Packer.
