### ISSUE TITLE
Collection unit name needs Bibframe 2.0 property

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1286]
Collection property for unit name can only be expressed in RDF using a property that requires URI value (bf:heldBy or dcterms:provenance). MODS and RDF group is recommending bf:heldBy from BF2.0: http://id.loc.gov/ontologies/bibframe.html#p_heldBy

rdf-vocab gem is currently using BF1.0: https://github.com/ruby-rdf/rdf-vocab

A new vocabulary needs to be added to this gem to allow for BF2.0 properties.

child of #1763

**Comment by jenyoung** [comment]
related #1763

**Comment by jlhardes** [comment]
bf:heldBy property should be added to AdminSet properties as URI value in Avalon 7/Hyrax

**Comment by davidschober** [comment]
@jenyoung @jlhardes is this a model tweak we want to move on now? I'm trying to move the very old issues.

**Comment by jlhardes** [comment]
It would be great if we could have this as part of Avalon 7. We already have the bf:heldBy property in place, we're just using it incorrectly (with text instead of URI values). https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+Metadata+Profile

**Comment by joncameron** [comment]
In Avalon 7
