### ISSUE TITLE
Value for Collection unit name should only be URI

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1287]
Property to be used for unit name on Collection is bibframe:heldBy which requires a URI (Agent class) as its value. Unit names for collections should be limited to a controlled list of names from a linked data source (LCNAF, for example).
child of #1763

**Comment by jenyoung** [comment]
related #1763

**Comment by jlhardes** [comment]
bf:heldBy property should be added to AdminSet properties as URI value in Avalon 7/Hyrax

**Comment by joncameron** [comment]
In Avalon 7
