### ISSUE TITLE
Default Fedora 4 Identifiers Discussion

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1291]
In the move from Fedora 3 Identifiers (avalon:####) to Fedora 4 Identifiers (a full UUID-type string), Avalon's usual behavior of putting the identifier in the URL is  problematic. In particular, Fedora 4 identifiers have forward slashes which need to be escaped.

**\* Done Looks Like
- [ ] A meeting is scheduled between developers and metadata experts about how to transform the Fedora 4 identifiers for use  in URLS. Further stories are written for the work after decisions are made about how to proceed.

**Comment by davidschober** [comment]
@cjcolvar has a PR for Avalon that follows Lerna's approach if we want to merge it. Add a discussion. PR for generating a noid for avalon similar to lerna/sufia

**Comment by jlhardes** [comment]
Include @mcwhitaker in this discussion

**Comment by cjcolvar** [comment]
Email sent to avalon-core.
