### ISSUE TITLE
Implement "About" Page

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1292]
The Avalon About page (the gem that Brendan refers to below) needs to be implemented in R6.
### Done Looks Like

About page implemented in 6.0

**Comment by bmquinn** [comment]
@joncameron is this referring to the about_page gem (https://github.com/sul-dlss/about_page) or a generic "about" page with acknowledgements and that sort of thing?

**Comment by joncameron** [comment]
Authorization to be added later in 6.x. #1294

**Comment by davidschober** [comment]
about page gem is Fedora 3 only. Need to update.
