### ISSUE TITLE
Default users and groups aren't automatically tracking dirty status

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1293]
https://github.com/avalonmediasystem/avalon/pull/1288 manually flags the default users and groups fields as changing when deleting values.  We should figure out why the automatic dirty tracking isn't working and fix it.

**Comment by davidschober** [comment]
@cjcolvar is this critical for 6.0?

**Comment by joncameron** [comment]
The workaround isn't pretty - we need to figure out how to work around this.

**Comment by davidschober** [comment]
Note, these are not critical for 6.0. If we're able to work on these, we should not merge into 6.0.

**Comment by cjcolvar** [comment]
I'm going to put a comment in the code with a TODO and mark this abandoned.  In 7.x this will probably be a non-issue.

**Comment by cjcolvar** [comment]
@davidschober @joncameron ^^^ Is this okay with you two?

**Comment by joncameron** [comment]
@cjcolvar OK with me. I'll move this to done.
