### ISSUE TITLE
[6.0 Specific] Video upload fails because of endless loop in trying to get a thumbnail

### ISSUE THREAD

**Issue by lealeelu** [avalonmediasystem/avalon#1303]
When I try to upload a video onto spruce, it spins for too long on "Uploading...Please wait." After a while, this error pops up:

![image](https://cloud.githubusercontent.com/assets/5091130/19701719/9990a056-9aca-11e6-8384-e9d1a6f90d2d.png)

It looks like it's getting stuck on an endless loop.

**Comment by davidschober** [comment]
@carrickr This may be a duplicate. Let's verify #1306. 

@csyversen probably related but getting there two different ways.
