### ISSUE TITLE
[6.0 Specific]:- Uploading any media (audio/video) normally or through batch ingest fails on spruce.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1306]
Environment:- https://spruce.dlib.indiana.edu
Devices:- All Devices/ Browsers

**Steps to Reproduce**

**Step A**
1. Launch URL on any browser.e.g:- Chrome.
2. Login with valid credentials.
3. Navigate to any collection.
4. Create an item and try uploading audio or video.

**Alternate steps B**
1. Try batch ingests using audio files.
2. Make sure to change email address in order to receive error message. 
3. Check email after batch ingest

Observe error message on trying to upload audio/video manually or through batch ingest. 

**Note**:- Error message is same in both cases.

**Done looks like**

User should be able to upload any media manually or through batch ingest without any error.

Please refer attached screenshots for details:-

![error_message](https://cloud.githubusercontent.com/assets/15963595/19739815/6c01feb2-9b8a-11e6-804e-224702551ff6.jpg)
![batch_ingest_fail](https://cloud.githubusercontent.com/assets/15963595/19739828/72464eb8-9b8a-11e6-99fc-14863b0ae938.jpg)

**Comment by davidschober** [comment]
Per @carrickr this may be related to active job. We can possibly revert active job.

**Comment by joncameron** [comment]
@anirudhpillai16 Can you check this again and move to Done if resolved? Thanks!

**Comment by cjcolvar** [comment]
Changes have been merged and deployed to spruce which should fix this.  Please retest.

**Comment by anirudhpillai16** [comment]
This issue is no longer reproducible, user is able to upload media normally as well as through batch ingest hence closing this issue.
