### ISSUE TITLE
As an installation manager I want an easy way to turn off all ingestation

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1308]
## So That:

As Avalons have grown in size, migration from one version to another has moved more toward spinning up a new Avalon and then copying the data to it.  The only problem is during this process users can be uploading content or content can be ingested via the API, batch, etc.  Leading to a diff of content that needs to be migrated (or users have to be informed everything after Date X will be lost and need to be re-ingested into the new Avalon).  So it would be useful to have one option we can set in Avalon that disables all forms of ingest.
## Note

This one can probably be broken down in the planning stage with:
- [ ] Create the read only setting
- [ ] Make user upload respect the read only setting
- [ ] Make batch ingest respect read only
- [ ] Make the ingest API respect read only

**Comment by davidschober** [comment]
@carrickr do you see this as critical for 6.0. Or are we looking at this for 6.0?

**Comment by joncameron** [comment]
Closing as stale (and irrelevant for Avalon 7).
