### ISSUE TITLE
Analyse errors from Migration

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1311]
### Description
Any errors from migration need to be evaluated.

### Done Looks Like
- [x] developers go through errors
- [x] write issues based on errors, develop timeline

To be completed after #1262.

**Comment by cjcolvar** [comment]
@joncameron @davidschober Is this story done given our discussion this morning?  Are there bugs still needing to be written?

**Comment by davidschober** [comment]
I think so.

**Comment by davidschober** [comment]
Chatted with Jon. Calling it done.
