### ISSUE TITLE
[6.0 Specific]:-  There are two instances of "Moving Image" and "Sound Recording" under Format.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1325]
Environment:- https://spruce.dlib.indiana.edu
Devices:- All Devices/ Browsers

**Steps to Reproduce**

1. Launch URL on any browser.e.g:- Chrome
2. Login with valid credentials.

Observe "Moving Image" and "Sound recording" appear twice under Format with first word upper cased  and lower cased.

Note:- Issue is not reproduible on mallorn.

**Done looks like**

" Moving Image" and "Sound Recording" should appear only once under Format.

Please refer attached screenshot for details:-
![multiple_format](https://cloud.githubusercontent.com/assets/15963595/19943757/3e96bf3c-a10f-11e6-8be3-053e14eac15d.jpg)

**Comment by cjcolvar** [comment]
This is a temporary issue that will be resolved when all of the items get reindexed.
