### ISSUE TITLE
[6.0 Specific]: - Video doesn't upload intermittently (thumbnail, placeholder doesn't appear) after conversion process gets completed.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1326]
Environment:- https://spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**

1. Launch URL on browser.e.g:- Chrome.
2. Login with valid credentials.
3. Create new item under any collection.
4. Upload any video and follow steps for uploading.
5. Observe conversion process appears and wait till conversion is completed.

Observe Video doesn't upload after conversion and no poster/thumbnail is displayed along with title.

Note:- Issue is not reproducible on mallorn.
2. Reproducibilty for this issue is 2/5. 

**Done looks like**
Video should upload properly after conversion process is completed.

Please refer attached screenshot for details:
![failed_upload](https://cloud.githubusercontent.com/assets/15963595/19945393/507d1ece-a116-11e6-907c-7a395deab788.jpg)

**Comment by davidschober** [comment]
Some work has been done @anirudhpillai16 retest please.

**Comment by anirudhpillai16** [comment]
I was able to reproduce this issue once though repeatability is still low. Please refer attached screenshot for details:

![reproducible](https://cloud.githubusercontent.com/assets/15963595/20071685/6b108092-a4f3-11e6-8653-490dae800436.jpg)

**Comment by joncameron** [comment]
We'll keep testing—when it fails to upload, copy the PID of the object and send it to devs so they can check the logs.

**Comment by bkeese** [comment]
Quotes in the item title is the likely culprit.

**Comment by carrickr** [comment]
If desired POs should test this with a special character video and ensure message is to their satisfaction.
