### ISSUE TITLE
As a developer I want to know why any invocation of ActiveFedora::Base throws errors

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1327]
## Example

[11] pry(main)> ActiveFedora::Base.delete_all
ERROR Lexer error: With input '<http://projecthydra.org/ns/auth/group#Group with> ;
	a ldp:RDFSource , ldp:Container ;
	fedora:writa': Invalid token "<http://projecthydra.org/ns/auth/group": {:production=>:object, :token=>"<http://projecthydra.org/ns/auth/group"}: 
ERROR Expected predicateObjectList: {:production=>:triples, :token=>";"}: 
ERROR Lexer error: With input '<http://projecthydra.org/ns/auth/group#Group with> ;
	a ldp:RDFSource , ldp:Container ;
	fedora:writa': Invalid token "<http://projecthydra.org/ns/auth/group": {:production=>:object, :token=>"<http://projecthydra.org/ns/auth/group"}: 
ERROR Expected predicateObjectList: {:production=>:triples, :token=>";"}: 
ERROR Lexer error: With input '<http://projecthydra.org/ns/auth/group#Group with> ;
	a ldp:RDFSource , ldp:Container ;
	fedora:writa': Invalid token "<http://projecthydra.org/ns/auth/group": {:production=>:object, :token=>"<http://projecthydra.org/ns/auth/group"}: 
ERROR Expected predicateObjectList: {:production=>:triples, :token=>";"}: 
ERROR Lexer error: With input '<http://projecthydra.org/ns/auth/group#Group with> ;
	a ldp:RDFSource , ldp:Container ;
	fedora:writa': Invalid token "<http://projecthydra.org/ns/auth/group": {:production=>:object, :token=>"<http://projecthydra.org/ns/auth/group"}: 
ERROR Expected predicateObjectList: {:production=>:triples, :token=>";"}: 
ERROR Lexer error: With input '<http://projecthydra.org/ns/auth/group#Group with> ;
	a ldp:RDFSource , ldp:Container ;
	fedora:writa': Invalid token "<http://projecthydra.org/ns/auth/group": {:production=>:object, :token=>"<http://projecthydra.org/ns/auth/group"}: 
ERROR Expected predicateObjectList: {:production=>:triples, :token=>";"}: 
ERROR Lexer error: With input '<http://projecthydra.org/ns/auth/group#Group with> ;
	a ldp:RDFSource , ldp:Container ;
	fedora:writa': Invalid token "<http://projecthydra.org/ns/auth/group": {:production=>:object, :token=>"<http://projecthydra.org/ns/auth/group"}: 
ERROR Expected predicateObjectList: {:production=>:triples, :token=>";"}: 
ERROR Lexer error: With input '<http://projecthydra.org/ns/auth/group#Group with> ;
	a ldp:RDFSource , ldp:Container ;
	fedora:writa': Invalid token "<http://projecthydra.org/ns/auth/group": {:production=>:object, :token=>"<http://projecthydra.org/ns/auth/group"}: 
ERROR Expected predicateObjectList: {:production=>:triples, :token=>";"}: 
ERROR Lexer error: With input '<http://projecthydra.org/ns/auth/group#Group with> ;
	a ldp:RDFSource , ldp:Container ;
	fedora:writa': Invalid token "<http://projecthydra.org/ns/auth/group": {:production=>:object, :token=>"<http://projecthydra.org/ns/auth/group"}: 
ERROR Expected predicateObjectList: {:production=>:triples, :token=>";"}: 
ERROR Lexer error: With input '<http://projecthydra.org/ns/auth/group#Group with> ;
	a ldp:RDFSource , ldp:Container ;
	fedora:writa': Invalid token "<http://projecthydra.org/ns/auth/group": {:production=>:object, :token=>"<http://projecthydra.org/ns/auth/group"}: 
ERROR Expected predicateObjectList: {:production=>:triples, :token=>";"}: 
ERROR Lexer error: With input '<http://projecthydra.org/ns/auth/group#Group with> ;
	a ldp:RDFSource , ldp:Container ;
	fedora:writa': Invalid token "<http://projecthydra.org/ns/auth/group": {:production=>:object, :token=>"<http://projecthydra.org/ns/auth/group"}: 
ERROR Expected predicateObjectList: {:production=>:triples, :token=>";"}: 
<< BEFORE_SAVE (IngestStatus) >>
<< last_completed_step => ["access-control"] >>
  Bookmark Load (0.2ms)  SELECT "bookmarks".* FROM "bookmarks" WHERE "bookmarks"."document_id" = ?  [["document_id", "2b/58/91/ab/2b5891ab-c8d2-4b45-8040-5912265f5ac3"]]

**Comment by cjcolvar** [comment]
This is the problem that I ran into earlier this week dealing with reindex_everything.  This is solved by projecthydra/hydra-head#386 and we can update to fix this problem once that gets merged.
