### ISSUE TITLE
Update Captions via API 

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1329]
# Description
As a user with an API token, I want to use the Avalon API to update captions on a media object. 

If a user has edit ability on an object, there should be an available call to the Avalon API to add or update a captions file to a masterfile.

# Done Criteria
- [ ] Captions can be updated using the Avalon API

**Comment by davidschober** [comment]
@joncameron will do some investigation into what is needed. We still need more background.

**Comment by joncameron** [comment]
Superseded by #5710.
