### ISSUE TITLE
Time Views in Media Player - Knowledge Spike

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1330]
### Needs Summary
Currently Avalon only displays time relative to the section. Faculty needs at the IU School of Music require a view on the player that shows time relative to the current track rather than to the section.

### Done Looks Like
-  [x] Meeting/swarm scheduled to discuss how mediaelement can accommodate our needs for 
- [x] Discussion and summary/document related to findings of the discussion are shared with the team

**Comment by davidschober** [comment]
@joncameron to schedule with @gfitzwat @carrickr @csyversen @cjcolvar.

**Comment by joncameron** [comment]
![20161122_111926 jpg](https://cloud.githubusercontent.com/assets/1406618/20566080/e54b16d6-b161-11e6-8700-2a167d4b0124.jpeg)
