### ISSUE TITLE
Video fails to upload and error message is displayed if name of file contains Special character " L with stroke".

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1335]
Environment:- https://spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**

1. Launch URL on browser.
2. Login with valid credentials.
3. Access any collection and create new item.
4. Upload audio "SHYWOŁVE - 09 Lost in Motion" where L is latin (L with stroke).

Observe error message on trying to upload video.

Note:- Video upload fails after conversion process on mallorn.

**Done looks like**

User should be able to ingest or upload video with special characters in name.

Please refer attached screenshot for details:-
![mallorn_error](https://cloud.githubusercontent.com/assets/15963595/19974062/9d42269e-a1bd-11e6-8b4f-b41cf065988a.jpg)

![spruce_error](https://cloud.githubusercontent.com/assets/15963595/19974056/91d908a4-a1bd-11e6-9dc8-640811311cd7.jpg)

**Comment by cjcolvar** [comment]
This probably applies to other unicode characters as well.  On mallorn the matterhorn workflow failed, but on spruce the mediainfo command fails presenting a 500 to the user instead.

**Comment by davidschober** [comment]
At least  make it not 500. Give an error. Jon to make a different story for enhancement.

**Comment by joncameron** [comment]
We'll dive into fixing this, but if not this bug will be punted to the next dot release.

**Comment by joncameron** [comment]
@carrickr Attempting to upload a file with the Ł character gave me the following error:
![screen shot 2016-12-07 at 9 47 43 am](https://cloud.githubusercontent.com/assets/1406618/20972321/858fb916-bc62-11e6-80d2-78fb01d6bd6a.png)
What's the intended behavior? __Done looks like__ has the ability to upload these files; is that the desired case?

**Comment by cjcolvar** [comment]
This works for me on spruce now.

**Comment by carrickr** [comment]
If desired POs should test this with a special character video and ensure message is to their satisfaction.
