### ISSUE TITLE
Update Wiki Documentation for R6

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1337]
To Update:
- [x] Config Files https://wiki.dlib.indiana.edu/display/VarVideo/Configuration+Files
- [x] Guide to monitoring - update to include that it's behind authentication https://wiki.dlib.indiana.edu/display/VarVideo/Guide+to+monitoring+Avalon
- [x] Master and derivatives  https://wiki.dlib.indiana.edu/display/VarVideo/Master+and+Derivative+File+Locations
- [x] remove 'in progress' from Avalon home page instructions https://wiki.dlib.indiana.edu/display/VarVideo/Customize+Avalon+Homepage
- [x] Add note to puppet install that it is deprecated for 6.0

**Comment by davidschober** [comment]
@joncameron 

- [ ] create a list of each specific item

**Comment by joncameron** [comment]
I assigned Phuong so he can change the Config files document.
