### ISSUE TITLE
As a developer I want better solr commit strategies on our reindex_all task 

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1343]
## So That

We use solr more efficiently and speed up our reindex all.  

## Done Looks Like

Rather than call update_index on every object, call to_solr on the objects and only commit to solr every one thousand objects or so.  This reduces the low on solr since it just needs to handle one large post every so often and then optimize itself, rather than update its indices every commit

**Comment by carrickr** [comment]
On 5.x releases I'm seeing issues with the rake task not worrying.  It reports items as existing in Solr but not Fedora.  Conversely when I come at it from the other end ( https://gist.github.com/carrickr/e1966649f30f0ce1f224b1e7e8940c5c ) I see no errors.  Solr can find everything it has in Fedora.  This may not be an issue in 6.x as Fedora 4 handles it differently, but we should verify this.  Also consider improving the 5.x reindex all.

**Comment by davidschober** [comment]
old and stale. abandoned.
