### ISSUE TITLE
Ensure external dependency gems are official releases and not git repositories

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1347]
We are currently using hydra-head master branch to get a bugfix.  Before we release we should be on a stable released version of hydra-head (and any other gems we don't manage) and have tested with it.

**Comment by mcwhitaker** [comment]
It looks like this should happen before we start our final regression testing for the release.

**Comment by davidschober** [comment]
@carrickr I'm closing this because it's a dupe of #1411. Please let me know if I'm wrong and yank it back to ready.
