### ISSUE TITLE
Improve Playlist Performance

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1354]
For playlists with large numbers of items, performance is extremely slow when
- loading the playlist view 
- moving from one item to the next within the playlist
The higher the number of playlist items becomes, the slower the performance is when loading the playlist and navigating between playlist items.

20 or 30 items seems to be the point where it becomes unacceptably slow (~10s per load).

See Maria's comment regarding what may be the underlying issue: https://github.com/avalonmediasystem/avalon/issues/1354#issuecomment-266495952

Original write-up by Maria:
Currently it takes several seconds for the player to go from the end of one playlist item to the beginning of the next. This hinders a bit the use case related to continuous streaming. For the educational use case, the delay makes it harder to compare one item against the next.

**Comment by carrickr** [comment]
@mcwhitaker Which server are you seeing this on as an issue?

**Comment by mcwhitaker** [comment]
@carrickr This was reported in our MCO instance.

**Comment by davidschober** [comment]
Note, these are not critical for 6.0. If we're able to work on these, we should not merge into 6.0.

**Comment by davidschober** [comment]
Adding 5.x tag as well as this will need to be fixed for IU production. 

@mcwhitaker , per your email do we know what a long playlist is? (e.g. > 20 items, > 40)

**Comment by mcwhitaker** [comment]
@davidschober Phil Ponella's list has over 100 items. I have not tried this with a list of 40 items. I was thinking of importing his playlist under my username and start trimming it down 10 items at a time to see what happens to performance.

**Comment by davidschober** [comment]
Sounds like a plan.

**Comment by mcwhitaker** [comment]
@cjcolvar said that this work is significant because we will need to solr'ize some fields and refer to solr instead of fedora throughout the code. Significant testing will be required.

**Comment by jwd** [comment]
@mcwhitaker Do you know yet at what size this becomes a problem? Is it related to number of playlist items, number of markers, or both?

**Comment by mcwhitaker** [comment]
@jwd I am working down the numbers. At this point, I am at 74 items (down from 114) and it takes 21 seconds to move from one item to another. At 114 items, it was taking 30 seconds. I will post results here.

**Comment by mcwhitaker** [comment]
Here are the results of my test, going down from 114 items to 4 items, removing 10 items at a time:
<pre><code>
# items	seconds
114	       30
104	       29
94	       26
84	       22
74	       21
64	      18
54	      14
44	      11
34	       9
24	       7
14	       4
  4	       2
</code></pre>

**Comment by joncameron** [comment]
@mcwhitaker These numbers are for MCO?

**Comment by mcwhitaker** [comment]
@joncameron Yes since that is where we are having the performance issues.

**Comment by joncameron** [comment]
Putting in the links I shared on avalon-core-l—test playlists on Mallorn, where we'll be testing:

https://mallorn.dlib.indiana.edu/playlists/2099
100 items
 
https://mallorn.dlib.indiana.edu/playlists/24
50 items
 
https://mallorn.dlib.indiana.edu/playlists/23
30 items

**Comment by joncameron** [comment]
I'm moving this to done since the work has been broken up into multiple issues.
