### ISSUE TITLE
thumbnails not appearing on listing page

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1355]
Thumbnails are not showing on listing page on spruce.

To recreate:
* got to a collection <https://spruce.dlib.indiana.edu/?f%5Bcollection_ssim%5D%5B%5D=Test_Collection&q=&search_field=all_fields>
* see no thumbnails. 
![screen shot 2016-11-08 at 4 41 27 pm](https://cloud.githubusercontent.com/assets/4803230/20120430/63072fce-a5d2-11e6-9908-772e4fdfc26f.png)

**Comment by anirudhpillai16** [comment]
Thumbnails are showing on listing page hence closing this issue as fixed.  Please refer attached screenshot for fix

![fixed](https://cloud.githubusercontent.com/assets/15963595/20277671/93741db0-aa6f-11e6-954e-fe27d56e594e.jpg)
