### ISSUE TITLE
MODS & RDF group work review

### ISSUE THREAD

**Issue by jenyoung** [avalonmediasystem/avalon#1356]
Working through mods recommendations. This is pre-work before a conversation with developers. 

- [ ] See if simple solutions determined by group can be used. 
- [ ] Write stories/tasks as needed

https://wiki.duraspace.org/display/hydra/MODS+and+RDF+Descriptive+Metadata+Subgroup

**Comment by jenyoung** [comment]
related #1533

**Comment by jlhardes** [comment]
Met with dev team and discussed mappings. Notes are available but not sure if they should be posted here. Outstanding things to figure out are identifiers (see https://docs.google.com/spreadsheets/d/16SCIPVLcIGgYJqRG25Pgwucp0hEgmaZCkbC2etwzfpA/edit?usp=sharing) for proposal. Also need to decide if mapping for Related Item and Related Item URL will work.

**Comment by mcwhitaker** [comment]
@jlhardes @jenyoung  Is this ready? Can we close it?
