### ISSUE TITLE
Investigate how to store structural metadata within a file

### ISSUE THREAD

**Issue by jenyoung** [avalonmediasystem/avalon#1360]
Investigate moving from our current structural metadata standard to IIIF AV when available. This issue is an investigative dive.

## DONE

Understand what a switch to IIIF AV would mean for structural metadata storage and display.

**Comment by davidschober** [comment]
Jen, can you fill this one in. The details are very sparse.

**Comment by jenyoung** [comment]
@davidschober we're talking about the structural metadata within a file.  does that make it clearer?

**Comment by davidschober** [comment]
K. I think I got it. I will rewrite the issue.

**Comment by mcwhitaker** [comment]
@jenyoung @jlhardes @davidschober  With the little detail provided, I may be wrong in my evaluation here, but I am not sure it is worth keeping this story on the board. IIIF/AV is very far from having standards; once the standards are published, we will need to make many more decisions about how to support them. This story will have to be part of and in coordination with a much larger effort.

**Comment by davidschober** [comment]
I think this is just an early knowledge spike for the metadata folks.

**Comment by joncameron** [comment]
This investigation has already started and work done for IIIF manifest generation in Avalon.
