### ISSUE TITLE
Investigate Ways to Restore Testing Server to a Clean State

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1363]
Identified during our testing meeting was the need for a way to clean out Fedora and Solr on Spruce and get back to a clean state. This could be achieved through scripting, but another option that may be available would be to use VM snapshotting. This needs to be investigated so we can go with the most efficient route to go down based on what is available.

### Done Looks Like
Questions are answered so we're ready to take the next step:
- Is snapshotting available on NU Test?
- Is snapshotting available on Spruce?
- Would it be better to write a script instead of using VM features?
- How would restoring handle updates to the core Rails app?
- How can Bamboo be used for this?

**Comment by davidschober** [comment]
write a script to clean everything then ingest a base set of content.

* blow away fedora, redis, derivatives, solr, database?
* ingest clean data via api

**Comment by joncameron** [comment]
It was decided in backlog refinement to use a script; David and I will clean this up. The 3 points are for writing that script.
