### ISSUE TITLE
Update List of Front End Testing Scenarios

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1364]
The spreadsheet with scenarios for users needs to be looked over, evaluated and updated as needed.

### Done Looks Like
- [ ] Missing new scenarios are identified and written 
- [ ] Current scenarios written out are updated or changed as needed
- [ ] The spreadsheet used for 5.x testing is updated and published for use—either as a spreadsheet or some other format
- [ ] Verify list of routes is covered in #1376

**Comment by davidschober** [comment]
@mcwhitaker and @joncameron I thin this should be pulled in to this sprint.

**Comment by davidschober** [comment]
@mcwhitaker  and @joncameron I went ahead and assigned Jon and I. Jon, do you want to crank through it Tuesday or Wednesday?
