### ISSUE TITLE
Sort By and Per Page dropdowns aren't working

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#1367]
dropdown_fields js is too liberal in applying it's onclick handler.

**Comment by anirudhpillai16** [comment]
Issue is verified and found fixed. User is able to sort by title, relevance, date and main contributor and able to limit results to 10,20,50 or 100 by selecting desired option.

Please refer screenshot for fix:
![fix](https://cloud.githubusercontent.com/assets/15963595/20279096/2b32032e-aa75-11e6-8a6f-0f63c43d5b58.jpg)
