### ISSUE TITLE
Finish Work on Migration Gem

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1369]
### List of Models to migrate

Order of migration by model or DB table

Before fedora-migrate:
- [ ] RoleMap (DB)

Fedora-migrate:
- [ ] Admin::Collection
- [ ] MediaObjects + relationships
- [ ] MasterFiles + relationships
- [ ] Derivatives + relationships
- [ ] Leases

Post fedora-migrate:
- [ ] Playlists, PlaylistItems, Markers (DB)
- [ ] SelectedItems (DB)
- [ ] IngestBatch (DB)
- [ ] User (DB)
- [ ] Courses (DB)
- [ ] Configuration

**Comment by davidschober** [comment]
@cjcolvar can you update this when you get back monday. I understand there's a blocker waiting for a hydra core merge. Can you put in the ref?

**Comment by carrickr** [comment]
@cjcolvar has a PR into the LDP gem to fix weak e-tags.  He has put in a PR ( https://github.com/projecthydra/ldp/pull/72 ) to LDP and it has been merged, so we can move forward on collections.
