### ISSUE TITLE
Ensure resque and resque scheduler restarts after cap deploy

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1372]
Capistrano 3 work is done. We need to do work with resque and resque scheduler.

## DONE 

- [x] update capistrano script to include a hook for restarting resque and resque scheduler
- [x] verify that it's working on redeploys.

**Comment by davidschober** [comment]
https://github.com/sshingler/capistrano-resque

**Comment by phuongdh** [comment]
@davidschober Resque restart hook was added a while ago in #1336 Not sure why it isn't working.

**Comment by csyversen** [comment]
I noticed we weren't specifying any workers, so i added that in here: https://github.com/avalonmediasystem/avalon/commit/cf9b6b2339abbe05ddb2a815f42c9177357bc041

we need to test it out though and i'm not sure about the best way to do that @phuongdh

**Comment by mbklein** [comment]
I'll take it.

**Comment by mbklein** [comment]
@csyversen This is working on NU Test deploys. PR it!
