### ISSUE TITLE
As a QA tester I want a list of all routes in Avalon and a strategy for testing them

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1376]
### Descriptive summary

With Avalon 6.0 we want to make sure that all routes, views, and Javascript in Avalon have been tested.  To this end, generate a list of all routes in Avalon and come up with a testing strategy to visit them (spreadsheet, browser stack, etc).

### Done Looks Like

Routes listed, any information required to access them documented (ex: special permissions, etc) , and a plan to test them.

**Comment by carrickr** [comment]
Prefix Verb     URI Pattern                                   Controller#Action
                       blacklight          /                                             Blacklight::Engine
                             root GET      /                                             catalog#index
                   search_catalog GET|POST /catalog(.:format)                            catalog#index
                    track_catalog POST     /catalog/:id/track(.:format)                  catalog#track
               opensearch_catalog GET      /catalog/opensearch(.:format)                 catalog#opensearch
                    facet_catalog GET      /catalog/facet/:id(.:format)                  catalog#facet
              email_solr_document GET|POST /catalog/:id/email(.:format)                  catalog#email
                sms_solr_document GET|POST /catalog/:id/sms(.:format)                    catalog#sms
           citation_solr_document GET      /catalog/:id/citation(.:format)               catalog#citation
             email_solr_documents GET|POST /catalog/email(.:format)                      catalog#email
               sms_solr_documents GET|POST /catalog/sms(.:format)                        catalog#sms
          citation_solr_documents GET      /catalog/citation(.:format)                   catalog#citation
                    solr_document GET      /catalog/:id(.:format)                        catalog#show
                   email_bookmark GET|POST /bookmarks/:id/email(.:format)                bookmarks#email
                     sms_bookmark GET|POST /bookmarks/:id/sms(.:format)                  bookmarks#sms
                citation_bookmark GET      /bookmarks/:id/citation(.:format)             bookmarks#citation
                  email_bookmarks GET|POST /bookmarks/email(.:format)                    bookmarks#email
                    sms_bookmarks GET|POST /bookmarks/sms(.:format)                      bookmarks#sms
               citation_bookmarks GET      /bookmarks/citation(.:format)                 bookmarks#citation
                  clear_bookmarks DELETE   /bookmarks/clear(.:format)                    bookmarks#clear
                 delete_bookmarks GET      /bookmarks/delete(.:format)                   bookmarks#delete
                                  POST     /bookmarks/delete(.:format)                   bookmarks#delete
                   move_bookmarks GET      /bookmarks/move(.:format)                     bookmarks#move
                                  POST     /bookmarks/move(.:format)                     bookmarks#move
  update_access_control_bookmarks GET      /bookmarks/update_access_control(.:format)    bookmarks#update_access_control
                                  POST     /bookmarks/update_access_control(.:format)    bookmarks#update_access_control
                publish_bookmarks POST     /bookmarks/publish(.:format)                  bookmarks#publish
              unpublish_bookmarks POST     /bookmarks/unpublish(.:format)                bookmarks#unpublish
        add_to_playlist_bookmarks GET      /bookmarks/add_to_playlist(.:format)          bookmarks#add_to_playlist
                                  POST     /bookmarks/add_to_playlist(.:format)          bookmarks#add_to_playlist
                        bookmarks GET      /bookmarks(.:format)                          bookmarks#index
                                  POST     /bookmarks(.:format)                          bookmarks#create
                     new_bookmark GET      /bookmarks/new(.:format)                      bookmarks#new
                    edit_bookmark GET      /bookmarks/:id/edit(.:format)                 bookmarks#edit
                         bookmark GET      /bookmarks/:id(.:format)                      bookmarks#show
                                  PATCH    /bookmarks/:id(.:format)                      bookmarks#update
                                  PUT      /bookmarks/:id(.:format)                      bookmarks#update
                                  DELETE   /bookmarks/:id(.:format)                      bookmarks#destroy
 user_identity_omniauth_authorize GET|POST /users/auth/identity                          users/omniauth_callbacks#passthru
  user_identity_omniauth_callback GET|POST /users/auth/identity/callback                 users/omniauth_callbacks#identity
                 new_user_session GET      /users/sign_in(.:format)                      users/sessions#new
             destroy_user_session GET      /users/sign_out(.:format)                     users/sessions#destroy
          user_omniauth_authorize GET|POST /users/auth/:provider(.:format)               users/omniauth_callbacks#passthru
           user_omniauth_callback GET|POST /users/auth/:action/callback(.:format)        users/omniauth_callbacks#:action
         browse_everything_engine          /browse                                       BrowseEverything::Engine
                        authorize GET|POST /authorize(.:format)                          derivatives#authorize
                                  GET|POST /authorize/:path(.:format)                    derivatives#authorize
     update_multiple_admin_groups PUT      /admin/groups/update_multiple(.:format)       admin/groups#update_multiple
         update_users_admin_group PUT      /admin/groups/:id/update_users(.:format)      admin/groups#update_users
                     admin_groups GET      /admin/groups(.:format)                       admin/groups#index
                                  POST     /admin/groups(.:format)                       admin/groups#create
                  new_admin_group GET      /admin/groups/new(.:format)                   admin/groups#new
                 edit_admin_group GET      /admin/groups/:id/edit(.:format)              admin/groups#edit
                      admin_group PATCH    /admin/groups/:id(.:format)                   admin/groups#update
                                  PUT      /admin/groups/:id(.:format)                   admin/groups#update
                                  DELETE   /admin/groups/:id(.:format)                   admin/groups#destroy
            edit_admin_collection GET      /admin/collections/:id/edit(.:format)         admin/collections#edit
          remove_admin_collection GET      /admin/collections/:id/remove(.:format)       admin/collections#remove
           items_admin_collection GET      /admin/collections/:id/items(.:format)        admin/collections#items
                admin_collections GET      /admin/collections(.:format)                  admin/collections#index
                                  POST     /admin/collections(.:format)                  admin/collections#create
             new_admin_collection GET      /admin/collections/new(.:format)              admin/collections#new
                                  GET      /admin/collections/:id/edit(.:format)         admin/collections#edit
                 admin_collection GET      /admin/collections/:id(.:format)              admin/collections#show
                                  PATCH    /admin/collections/:id(.:format)              admin/collections#update
                                  PUT      /admin/collections/:id(.:format)              admin/collections#update
                                  DELETE   /admin/collections/:id(.:format)              admin/collections#destroy
                 vocabulary_index GET      /vocabulary(.:format)                         vocabulary#index
                       vocabulary GET      /vocabulary/:id(.:format)                     vocabulary#show
                                  PATCH    /vocabulary/:id(.:format)                     vocabulary#update
                                  PUT      /vocabulary/:id(.:format)                     vocabulary#update
                     media_object PUT      /media_objects/:id(.:format)                  media_objects#update {:format=>"html"}
                                  PUT      /media_objects/:id(.:format)                  media_objects#json_update {:format=>"json"}
                                  PATCH    /media_objects/:id(.:format)                  media_objects#update {:format=>"html"}
       update_status_media_object PUT      /media_objects/:id/update_status(.:format)    media_objects#update_status
            progress_media_object GET      /media_objects/:id/progress(.:format)         media_objects#show_progress
             inspect_media_object GET      /media_objects/:id/content/:file(.:format)    media_objects#deliver_content
     indexed_section_media_object GET      /media_objects/:id/track/:part(.:format)      media_objects#show
          id_section_media_object GET      /media_objects/:id/section/:content(.:format) media_objects#show
                tree_media_object GET      /media_objects/:id/tree(.:format)             media_objects#tree
      confirm_remove_media_object GET      /media_objects/:id/confirm_remove(.:format)   media_objects#confirm_remove
                    media_objects POST     /media_objects(.:format)                      media_objects#create {:format=>"json"}
set_session_quality_media_objects POST     /media_objects/set_session_quality(.:format)  media_objects#set_session_quality
     confirm_remove_media_objects GET      /media_objects/confirm_remove(.:format)       media_objects#confirm_remove
      update_status_media_objects PUT      /media_objects/update_status(.:format)        media_objects#update_status
             remove_media_objects DELETE   /media_objects/remove(.:format)               media_objects#destroy
                                  GET      /media_objects(.:format)                      media_objects#index
                 new_media_object GET      /media_objects/new(.:format)                  media_objects#new
                edit_media_object GET      /media_objects/:id/edit(.:format)             media_objects#edit
                                  GET      /media_objects/:id(.:format)                  media_objects#show
                                  DELETE   /media_objects/:id(.:format)                  media_objects#destroy
            thumbnail_master_file GET      /master_files/:id/thumbnail(.:format)         master_files#get_frame {:type=>"thumbnail"}
               poster_master_file GET      /master_files/:id/poster(.:format)            master_files#get_frame {:type=>"poster"}
                                  POST     /master_files/:id/thumbnail(.:format)         master_files#set_frame {:type=>"thumbnail", :format=>"html"}
                                  POST     /master_files/:id/poster(.:format)            master_files#set_frame {:type=>"poster", :format=>"html"}
                still_master_file POST     /master_files/:id/still(.:format)             master_files#set_frame {:format=>"html"}
                embed_master_file GET      /master_files/:id/embed(.:format)             master_files#embed
     attach_structure_master_file POST     /master_files/:id/attach_structure(.:format)  master_files#attach_structure
      attach_captions_master_file POST     /master_files/:id/attach_captions(.:format)   master_files#attach_captions
             captions_master_file GET      /master_files/:id/captions(.:format)          master_files#captions
                     master_files POST     /master_files(.:format)                       master_files#create
                 edit_master_file GET      /master_files/:id/edit(.:format)              master_files#edit
                      master_file GET      /master_files/:id(.:format)                   master_files#show
                                  DELETE   /master_files/:id(.:format)                   master_files#destroy
                      derivatives POST     /derivatives(.:format)                        derivatives#create
                     autocomplete GET      /autocomplete(.:format)                       objects#autocomplete
                          objects GET      /objects/:id(.:format)                        objects#show
          playlist_playlist_items POST     /playlists/:playlist_id/items(.:format)       playlist_items#create
           playlist_playlist_item PATCH    /playlists/:playlist_id/items/:id(.:format)   playlist_items#update
                                  PUT      /playlists/:playlist_id/items/:id(.:format)   playlist_items#update
         update_multiple_playlist PATCH    /playlists/:id/update_multiple(.:format)      playlists#update_multiple
                                  DELETE   /playlists/:id/update_multiple(.:format)      playlists#update_multiple
                        playlists GET      /playlists(.:format)                          playlists#index
                                  POST     /playlists(.:format)                          playlists#create
                     new_playlist GET      /playlists/new(.:format)                      playlists#new
                    edit_playlist GET      /playlists/:id/edit(.:format)                 playlists#edit
                         playlist GET      /playlists/:id(.:format)                      playlists#show
                                  PATCH    /playlists/:id(.:format)                      playlists#update
                                  PUT      /playlists/:id(.:format)                      playlists#update
                                  DELETE   /playlists/:id(.:format)                      playlists#destroy
              avalon_marker_index POST     /avalon_marker(.:format)                      avalon_marker#create
                    avalon_marker GET      /avalon_marker/:id(.:format)                  avalon_marker#show
                                  PATCH    /avalon_marker/:id(.:format)                  avalon_marker#update
                                  PUT      /avalon_marker/:id(.:format)                  avalon_marker#update
                                  DELETE   /avalon_marker/:id(.:format)                  avalon_marker#destroy
                         comments GET      /comments(.:format)                           comments#index
                                  POST     /comments(.:format)                           comments#create
                    playlist_item PATCH    /playlist_items/:id(.:format)                 playlist_items#update {:format=>/(js|json)/}
                                  PUT      /playlist_items/:id(.:format)                 playlist_items#update {:format=>/(js|json)/}
        bulk_delete_dropbox_index DELETE   /dropbox/bulk_delete(.:format)                dropbox#bulk_delete
                           oembed GET      /oembed(.:format)                             master_files#oembed
                       about_page          /about(.:format)                              AboutPage::Engine
                                  GET      /about(.:format)                              redirect(301, /)
                                  GET      /about/health(.:format)                       redirect(301, /)
                    resque_server          /jobs                                         Resque::Server
                             jobs GET      /jobs(.:format)                               redirect(301, /)

Routes for Blacklight::Engine:
      search_history GET    /search_history(.:format)            search_history#index
clear_search_history DELETE /search_history/clear(.:format)      search_history#clear
clear_saved_searches DELETE /saved_searches/clear(.:format)      saved_searches#clear
      saved_searches GET    /saved_searches(.:format)            saved_searches#index
         save_search PUT    /saved_searches/save/:id(.:format)   saved_searches#save
       forget_search DELETE /saved_searches/forget/:id(.:format) saved_searches#forget
                     POST   /saved_searches/forget/:id(.:format) saved_searches#forget
track_search_context POST   /catalog/:id/track(.:format)         catalog#track
       suggest_index GET    /suggest(.:format)                   suggest#index {:format=>"json"}

Routes for BrowseEverything::Engine:
connector_response GET      /connect(.:format)           browse_everything#auth
          resolver GET|POST /resolve(.:format)           browse_everything#resolve
          contents GET|POST /:provider(/*path)(.:format) browse_everything#show
              root GET      /                            browse_everything#index

Routes for AboutPage::Engine:
   health GET  /health(.:format)  about_page/about#health
component GET  /:filter(.:format) about_page/about#index
     root GET  /                  about_page/about#index

**Comment by carrickr** [comment]
The above is raw, I'll clean it up and restrict to routes we care about (since SMSing the solr doc for example is not one of them)

**Comment by carrickr** [comment]
[routes.txt](https://github.com/avalonmediasystem/avalon/files/586652/routes.txt)

@joncameron @davidschober 

These are the 20 routes we care about from the user perspective (although note most of those routes support CRUD so they need to be tested multiple ways.  We can pass these to QA or write scripts based off them.

**Comment by davidschober** [comment]
@joncameron, let’s check these against our current testing script to see what kind of coverage we currently have for human testing. I think we should as part a 6.x release write basic automated (selenium) scripts for these routes.

**Comment by davidschober** [comment]
@carrickr and @joncameron, I added verifying these routes are covered to #1364. As a 6.x task we should investigate automating parts of the manual testing script. Closing.
