### ISSUE TITLE
Playlist Doesn't Display When Playlist Items Refer to Missing Objects

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1381]
### Description
If a playlist item refers to a media object or master file that does not exist, the user is unable to view or edit the playlist and instead receives a screen with error text. 

### Done Looks Like
Playlists which have items whose media objects or master files have been deleted are able to be viewed and edited. The items with missing content fail gracefully rather than preventing the user from accessing the playlist.

c.f. #1380. This is an issue for backporting this bugfix to 5.x if needed.

**Comment by davidschober** [comment]
same as #1100. Decided not to back port.
