### ISSUE TITLE
Fix collection default visibility

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1385]
Admin::Collection's default visibility is currently stored as an rdf property but instead it should be derived from the value of default_read_groups.  Likewise visibility= should manipulate the values in default_read_groups.

**Comment by cjcolvar** [comment]
Make sure to change the before_save callback too.

**Comment by cjcolvar** [comment]
I've done this work, I just need to create a PR to develop for this so it doesn't hold up regression testing.

**Comment by cjcolvar** [comment]
PR has been merged.  It could be tested now or during regression testing.

**Comment by joncameron** [comment]
This will be done during the full testing cycle.
