### ISSUE TITLE
implement second scrubber-- track-based

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1388]
## Done

Complete work based on designs in  issue #1387.

An end user should be able to tell time offset based on individual tracks (structural metadata) not only the full length of the master file. 

## Use case
An end user has marked up scores and shared (verbally, via syllabus, or using Avalon markers) key points in the Norton Anthology of Western Music. The offsets are based on track time not time of total CD/Recording. 

## Questions
Can markers refer to both time in total recording and time in structural metadata- based scrubber?

**Comment by carrickr** [comment]
We have to remember do this on all three (urgh) players in Avalon.  Media Object, Playlist, and Embed.

**Comment by davidschober** [comment]
duped by #1409. Closing.
