### ISSUE TITLE
Quality selector not showing

### ISSUE THREAD

**Issue by mbklein** [avalonmediasystem/avalon#1389]
On NU Test and Spruce.

After getting end to end ingest, the quality selector wasn't showing. And there's a javascript error that says a specific piece isn't getting loaded.

**Comment by joncameron** [comment]
Scope and size of this bug still needs to be determined.

**Comment by anirudhpillai16** [comment]
Tested today on spruce and didn't observe quality selector.

**Comment by anirudhpillai16** [comment]
Issue is verified and found fixed. Quality selector is showing under player tools hence closing this issue. Please refer screenshot for fix

![quality_selector_fixed](https://cloud.githubusercontent.com/assets/15963595/20770958/89ef985c-b715-11e6-9c1c-29ec458decda.jpg)
