### ISSUE TITLE
Deleting master file can cause a 500

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1392]
Steps to reproduce:
Create a new item
Add two files
Delete the files

Sometimes a 500 is thrown.
Rubyhorn::RestClient::Exceptions::ServerError in MasterFilesController#destroy
app/models/master_file.rb:709:in `stop_processing!'
app/controllers/master_files_controller.rb:242:in `destroy'

Probably a timing issue.  We need to catch this exception and handle it instead of causing master file destroy to fail.

**Comment by davidschober** [comment]
@joncameron can you try to reproduce and reopen if necessary. This feels very stale and I haven't heard any outside, real world use cases.

**Comment by joncameron** [comment]
This is fine to stay closed. This does happen (first identified in a production instance) but is heavily an edge case.
