### ISSUE TITLE
Error message thrown when user Enters a String Only Containing Space in Bibimport

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1393]
Environment:- https://spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**

1. Launch URL on browser.e.g:- Chrome.
2. Login with valid credentials.
3. Create new item under any collection.
4. Give space under catalog key field to enable import button.
5. Click Import.

Observe Error message is thrown on accessing import when space is used as input.

**Done looks like**

- [ ] Proper error message should be thrown when invalid input is used. e.g. "Please enter valid key"

Please refer attached screenshot for details:-
![space_biblographic_id](https://cloud.githubusercontent.com/assets/15963595/20402909/a03e89d6-accc-11e6-9d4f-1016e1c68f86.jpg)

**Comment by davidschober** [comment]
@carrickr said "should be sanitizing input"

**Comment by bkeese** [comment]
This might have been fixed to some extent by a recent change to bib_import that strips whitespace from the beginning and ending of submitted text.
https://github.com/avalonmediasystem/avalon/commit/e683b2f55b99ee46bf32a81be0b1f2bf8bf7e33d

**Comment by cjcolvar** [comment]
This is still present on spruce.

**Comment by cjcolvar** [comment]
@avalonmediasystem/product-owners I fixed this but the way I fixed it doesn't have any error message.  Is this okay or do we want a warning message?

**Comment by jlhardes** [comment]
I'm no product owner, but this seems reasonable to me. You get the appropriate errors messages about title and date being empty. If you already have a valid import in place and try to use just spaces for catalog key and click import, you don't lose the valid import - that's a good thing.

**Comment by cjcolvar** [comment]
Maybe we should catch this in the javascript though and not enable the import button?

**Comment by jlhardes** [comment]
If you can catch that and stop the action from happening in the first place, that works too. But this way doesn't hurt the record and gives the user information. It just also allows the import action to run and it doesn't need to run.

**Comment by bkeese** [comment]
Very simple javascript change to disable the button if only whitespace in the box.
