### ISSUE TITLE
[6.0 Specific]:- Using space after correct catalog key doesn't auto-fill fields.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1394]
Environment:- https://spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**

1. Launch URL on browser.e.g:- Chrome
2. Login with valid credentials.
3. Create item under any collection.
4. Enter valid catalog key. e.g:- for example 12355 followed by space.
5. Click Import.

Observe Field don't auto populate when space is used after valid catalog key. If user removes space then fields automatically fill in.

**Done looks like**

Fields should fill-in when correct catalog key is used with space or without space.

Please refer attached screenshot for details:-

![error_bb_id](https://cloud.githubusercontent.com/assets/15963595/20403230/0a22d77a-acce-11e6-8821-47fe2280862f.jpg)

**Comment by davidschober** [comment]
we will grab this on a .x release.

**Comment by cjcolvar** [comment]
Fixed with https://github.com/avalonmediasystem/avalon/commit/e683b2f55b99ee46bf32a81be0b1f2bf8bf7e33d.
