### ISSUE TITLE
open port 80 for streaming on mallorn and spruce

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1397]
## Done 

In order to facilitate better testing, move streaming to port 80 OR get port 1935 open on spruce and mallorn. Note, we are can only test off network using IUs VPN for FF and Chrome.

**Comment by davidschober** [comment]
@mcwhitaker, we solved this by granting my team VPN access correct?

**Comment by mcwhitaker** [comment]
@davidschober #1361 is the one you are thinking. This task is to actually work on the fix to the problem since there are limitations with the workaround. I believe you can't use browserstack currently.

**Comment by davidschober** [comment]
Sounds good.

**Comment by davidschober** [comment]
k. I can login now without needing to be on IUs vpn. Did this sort itself out?

**Comment by davidschober** [comment]
Tested this again. Streaming is working fine @joncameron you good to close?
