### ISSUE TITLE
We should probably update the Copyright statement

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1402]
Copyright 2011-2015, The Trustees of Indiana University and Northwestern

...given it is almost 2017!

**Comment by carrickr** [comment]
This should be small, Chris C says we have script for it somewhere.

**Comment by bkeese** [comment]
This is done.

**Comment by bkeese** [comment]
(it's in the code)

**Comment by davidschober** [comment]
Cool. That’s what I figured. 

Done and done..
