### ISSUE TITLE
Run Load Test in Fedora 4

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1407]
Run test created in #1405 in a Fedora 4 avalon with the same test dataset as used in #1406 in the same box to evaluate the impact of the upgrade on the performance of avalon. The evaluation will be made possible by comparing against the results of #1406.

**Comment by cjcolvar** [comment]
@mcwhitaker Can you give us an itemized list of things you need on mallorn for the test?

**Comment by mcwhitaker** [comment]
@cjcolvar  Here is a list of the IDs I used. A few of them refer to sections (marked with x).

avalon:225421	
avalon:225426	
avalon:226346	
avalon:226347	
avalon:7452	
avalon:7456	x
avalon:7478	
avalon:7513	
avalon:7514	x
avalon:7517	x
avalon:7675	
avalon:7676	x
avalon:7682	x
avalon:7685	
avalon:7686	x
avalon:7692	x
avalon:7695	x
avalon:7741	
avalon:7842	
avalon:7843	x
avalon:7846	x
avalon:7849	x
avalon:7871	
avalon:7872	x
avalon:7875	x
avalon:7878	x
avalon:7881	
avalon:8045	
avalon:8049	x
avalon:8061	x
avalon:8194	
avalon:8195	x
avalon:8198	x
avalon:8201	
avalon:8202	x
avalon:8205	
avalon:8208	
avalon:8209	x
avalon:8215	x
avalon:8233	
avalon:8364	
avalon:8371	x
avalon:8389	x
avalon:8395	x
avalon:8451

**Comment by mcwhitaker** [comment]
@cjcolvar if these items are not currently in mallorn, let's talk. It may not be worth the trouble to bring them over. In fact, the whole variations collection was in mallorn before and if we don't bring them all over for the pagination through the collection's search results to work as before, it won't work to use the same test. 

The variations items were good for editing (reordering sections) because several of them contained 5+ sections, which is not easy to find in other collections.

I do need an item with 100+ sections, though, to recreate a test similar to one of the tests I had before.
