### ISSUE TITLE
Retro Decisions

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1413]
- Stop working with assumption that "Done" is 100% complete. It's OK tweak the meaning of stories and kick off a new story if it's holding up the cycle.
- Push issues to close. Use POs
- Use mentions in issues a lot, comment more
- Break out issues better ]. 8 Point stories sit. if you can break a story into more than 3 or 4 dev tasks it should be broken. e.g #1369
- Be more conservative about what we can put in the sprint. 
- Create tasks for things that were worked on, including external things. Reference external PRs, etc in Hydra Core

**Comment by mcwhitaker** [comment]
This issue was moved to avalonmediasystem/avalon-planning#85

**Comment by mcwhitaker** [comment]
This issue was moved to avalonmediasystem/avalon-planning#86
