### ISSUE TITLE
Populate Mallorn with test data set

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1415]
depends on #1299

**Comment by mcwhitaker** [comment]
We do not need streamable data.

**Comment by mcwhitaker** [comment]
@joncameron @davidschober 

We had decided that for load testing we did not need to stream. I do not agree that we do not need to test streaming in mallorn at all as I believe streaming is part of Regression testing. 

I think this issue should be re-opened and worked on for at least a subset of the items so we can go through the test scenarios that call for streaming.

**Comment by mcwhitaker** [comment]
@joncameron @davidschober @bkeese I can't even navigate through the tracks to do load testing with the data the way it is.

**Comment by davidschober** [comment]
Yes, the not streaming was for load testing only.

**Comment by joncameron** [comment]
There is streamable data on Mallorn, just not the data from collections that were called out by Jen and Julie. Those we didn't need streaming for. I'm going to make a list or a new collection where streaming items will be available for load testing.
