### ISSUE TITLE
Write instructions for running migration

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1416]
These instructions should include:

- [x] How to prepare for migration
- [x] Migrate configuration
- [x] Migrate RoleMap database table
- [x] Run fedora-migrate migration of Fedora objects
- [x] Migrate other database tables
- [x] Warning in documentation about not ready for prime time

**Comment by davidschober** [comment]
This story is to document how to execute the migration completed in #1417. This is an outline of the documentation needed. https://github.com/avalonmediasystem/avalon/wiki/Migration-from-5.x-to-6.x

**Comment by cjcolvar** [comment]
We've been working on this here: https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+5+to+6+migration

**Comment by lealeelu** [comment]
Moved to here: https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+5+to+6+Database+Migration

**Comment by lealeelu** [comment]
Still some problems with rolemaps, maybe something with the rolemap cache needing to be cleared. Once that bug is figured out, we may need to update documentation.

**Comment by joncameron** [comment]
#1671 is the follow-up issue.
