### ISSUE TITLE
Complete migration tool for Fedora objects

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1417]
Finish overrides of fedora-migrate:

- [x] Admin::Collection
- [x] MediaObject
- [x] MasterFile
- [x] Derivative
- [x] Lease

**Comment by davidschober** [comment]
We are keeping this as a large issue because the work is linear.

**Comment by davidschober** [comment]
Need to find a mechanism to get ids before save.

**Comment by davidschober** [comment]
moving to in progress.
