### ISSUE TITLE
Database Migration - Playlists, PlaylistItems, Markers

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1420]
### Description
#1418 is the master issue for database migrations and contains the pattern or method to follow when creating each migration.
### Done Looks Like
Tools and/or instructions are written to migrate database tables for **Playlists, PlaylistItems, and Markers**. This may include migrating identifiers from old avalon:id pids to newly assigned noids.

- [x] add their migration status to the reporting tool

**Comment by davidschober** [comment]
We will need to map identifiers for this. 

Q: will the mapping be in a table or will we use a ruby task for it? @mcwhitaker

**Comment by cjcolvar** [comment]
Playlist - Dump and load
PlaylistItem - Dump and load
AvalonAnnotation (both clips and markers) - Dump, load, migrate #master_file to MasterFile with new noid
