### ISSUE TITLE
Database Migration - User

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1423]
### Description
#1418 is the master issue for database migrations and contains the pattern or method to follow when creating each migration.
### Done Looks Like
Tools and/or instructions are written to migrate database tables for **User**. This may include migrating identifiers from old avalon:id pids to newly assigned noids.

**Comment by davidschober** [comment]
@jenyoung when julie and I were looking at it we noticed that several users were no longer part of the university

@mbklein avalon does not have a validation on email address, so cleaning up users is more of a db maintenance task ... To be carded later.

**Comment by cjcolvar** [comment]
Probably a straight dump and load.
