### ISSUE TITLE
Figure About What To Do About About_Page

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1426]
### Descriptive summary

We currently have a fork of Stanford's About_Page that Avalon uses (and uses in the form of tracking a github repo).  The original plan was to probably push it back upstream and avoid living in our own little fork (aka repeating our erroneous ways that doomed our media element.js consumption), but the team ran out of time in the sprint to merge back in.  So we're still in our own fork.

We need to make a call if we try to get out of the work for R6 or not.

**Comment by carrickr** [comment]
We will tag this for R6 and release from our repo.  However I feel we should put getting back on main about_page pretty high up for 6.1 work (since there is no way we get it done for 6.0).

**Comment by joncameron** [comment]
We'll abandon this- not relevant in Hyrax.
