### ISSUE TITLE
Avalon Needs To Do A Better Job of Dealing With Non ASCII Characters in Filenames

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1431]
### Descriptive summary

Current state of affairs regarding non ASCII in a filename:

- User uploads of non ASCII characters fail
- Batch ingests containing non ASCII characters fail in matterhorn
- API ingests work if transcoding is skipped but fail in matterhorn in transcoding occurs

We need to determine:

- [ ] How strict is Matterhorn (it seems like can accept more than just ASCII since some transcodes with non ASCII haven't failed but we should look into this)
- [ ] Determine if we should just rename files for the user (and probably alert them to this) or flat out reject files via any method of ingest.

**Comment by phuongdh** [comment]
Just saw this today, ingest fails when filename contains square brackets. Example: 2804[kb]super-blues-guitar.aif.mp3

**Comment by joncameron** [comment]
Abandoning this since I don't think it's worth fixing or working around Matterhorn. Instead, documentation should be available regarding filename limitations in Avalon (@joncameron).
