### ISSUE TITLE
MARC to MODS Related Item URL Label not coming through correctly

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1433]
Currently a text label provided for 856 URLs on bib import is coming through as <relatedItem/url@displayLabel> but Avalon only shows that text as the link if it is <relatedItem@displayLabel>. We need to either change the XSL or change where Avalon is reading @displayLabel for Related Item URLs.

MCO has an example item showing a manually entered label for Related Item ("Testing") and the MODS contains the label brought in through bib import ("Program"): https://media.dlib.indiana.edu/media_objects/avalon:5844

This was reported by IU Music Library.

This issue is for Avalon 6.x. This same bug needs to be fixed for 5.x: #1398.

- [ ] Fix XSL per discussion on #1398.

**Comment by davidschober** [comment]
Michael say the fix is super, super easy. The issue is data already imported is in the wrong place. We have to decide how to make the reader work:
- tolerant
- move to the right place
- etc

We will put this in ready and time allowing, we can grab it.

**Comment by lealeelu** [comment]
The import for catalog key 15551486 is happening, but no label is being provided:
![image](https://cloud.githubusercontent.com/assets/5091130/25856675/bc77f5be-34a4-11e7-81a6-c6af059a6105.png)
When you save, no label is provided. There's probably more to the problem though.

**Comment by cjcolvar** [comment]
I think we should backport this so people can run the data migration prior to the 6.0 migration to avoid having to do an ugly rerun of a rails migration.

**Comment by bkeese** [comment]
We decided to implement this in a way (rake task) such that we don't need to run it prior to the migration. So there's no need to port this back to 5.x.

**Comment by jlhardes** [comment]
I tried this with the item mentioned above and another harp competition item and both import calls brought in the related item URL with the "Program" text as the link. Does this need to be tested via batch import as well?

**Comment by bkeese** [comment]
Batch uses the same xsl, so probably not necessary to test it.
