### ISSUE TITLE
figure out cross origin security issue for player api

### ISSUE THREAD

**Issue by csyversen** [avalonmediasystem/avalon#1440]
### Come up with requirements for the avalon embedded player

We've talked about other institutions being able to embed avalon videos in their sites similar to vimeo and youtube and allowing the client app to control the player, but are there any other details that we've missed?

Since the api to control the mediaelement player already exists, right now the major hurdle is overcoming the cross origin security issues of allowing other sites to control the application. It might be something simple but it's an area that i'm not familiar with and could have major security issues. 

refs #1312

**Comment by mcwhitaker** [comment]
@csyversen Chris, would the postMessage method resolve this issue? I have read that Javascript allows cross-document communication by use of this method. http://javascript.info/tutorial/cross-window-messaging-with-postmessage

**Comment by csyversen** [comment]
yeah that's one of the possible things we'd need to look into. We'd need to redesign and rethink the way that we're doing things right now, although it's definitely doable.

**Comment by joncameron** [comment]
CORS is a part of Player API work but also separate. This may be split into multiple issues.

**Comment by davidschober** [comment]
@joncameron I think we should dig into this soon. Chris S. noted that media element player has an existing API. It seems that we should leverage that and call it done. Does anyone have a feel for how much work it would be to retool the view?
