### ISSUE TITLE
Discuss migration to RDF if Mods xml is mapped

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1443]
- [ ] Would migration to RDF work better if MODS XML is mapped to RDF XML before migrating?
- [ ] break out tasks if necessary.

**Comment by davidschober** [comment]
relates to #1356

**Comment by jlhardes** [comment]
See white paper on Box for link to MODS to RDF spreadsheet mapping for Avalon.

[] - only mapping descriptive fields that are editable/manageable in Avalon (through Resource Description Form)
- established that default Avalon install uses extent for physical description (reviewed pawpaw)
- still need property for "other" identifier (within list of identifier types)
- need to figure out how to try mapping Geographic Subjects to TGN URIs and offering report from migration of geo subjects that didn't map
- think we decided that F3 pids could be URL or URN (made up but namespaced to show from F3)
- think we decided that Bibliographic ID could use loc:local but would not be a URL and that Other Identifier field would not offer loc:local as an option - display will need to change to include Bib ID as an identifier on item

**Comment by mcwhitaker** [comment]
@jlhardes My recollection regarding F3 pids matches yours. Sorry, my recollection about Bib ID is very fuzzy because we went around a couple of times. I think what you say is correct, but others will have to confirm.

**Comment by jenyoung** [comment]
[ ] Need to verify what MDPI is using for metadata field. Don't want to miss anything
[ ] Is there a difference between where physical description is being pulled from between the form and batch upload?
[ ] linking out to related item -- how is metadata provenance recorded?
[ ] Bibliographic ID - would one Other Identifier field work  and use owl:sameAs? 
[ ] Geographic subjects - might also need another tool for re-importing the data, or a rake task

**Comment by davidschober** [comment]
@jlhardes and @jenyoung this issue looks done, closing.
