### ISSUE TITLE
As a developer I want to profile Avalon's object creation 

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1453]
This is probably of somewhat highish priority to the IU side, since IU is looking at needing to ingest 15k+ objects per day once the digitization lab gets up to full speed.

Basically after tweaking our servers and giving Fedora and Solr resources, our bottleneck is a single massive ruby thread that limits us.  This thread is handing media object, master files, derivatives, and other tasks that could probably be backgrounded or else split out using the Parallel gem.  As a starting point we should have a conversation about reworking this and perhaps dedicate some time to using a profiling tool on Avalon.

**Comment by davidschober** [comment]
We have reworked / improved and agreed to performance standards. Stale.
