### ISSUE TITLE
Bring 5.x Playlist Improvements to 6.0

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1480]
All the work we do to improve playlists for 5.x should be included on 6.x.

I have all work for v.5.1.5 rebase onto 6's development branch here 8efd129895c815e0f0218fcd5d108877cc2b4d19.  However if we do addition 5.x work they should be brought over as well.

I have not pulled the changes in yet because I am waiting for POs to make a call if they want this is 6.0 or 6.x.

**Comment by carrickr** [comment]
@joncameron @davidschober 

For your consideration.  If we pull this into 6.0 we up our QA requirements, so I didn't put this in core develop yet, however if you want it, it can be done easily.

**Comment by bkeese** [comment]
This commit, which fixes javascript handlers for dynamically loaded playlist item markers, should be dried up by adding function to gem and reusing: https://github.com/avalonmediasystem/avalon/pull/1495/commits/5d3ac033a888218e6cbcae456b5c37ec7112ece4

**Comment by carrickr** [comment]
also need to grab 5.x toggle auto advance

**Comment by carrickr** [comment]
Also use the fix-marker branch, not the fix-playlist branch

**Comment by carrickr** [comment]
We need to figure out how to add stylesheets to the asset pipeline, specifically:

me-track-scrubber

**Comment by cjcolvar** [comment]
@joncameron @davidschober This should be in place on spruce ready for testing.
