### ISSUE TITLE
Port Phuong's Playlist Redirect Work From 5.x to 6.0

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1487]
Phuong made a change so that when someone goes to a playlist and is asked to log in, they are redirected to the playlist rather than the home page once they are authorized.  This needs to be ported from 5.x to 6.x.

Commit is 68677b38c95645429acd8c780d0b4f929cbc9975

Because Phuong's work hooks into the playlist speed improved we did, #1480 should be completed first (specifically there is no easy way to insert his adjustments to _playlist_item.html.erb into the current 6.0 code).

**Comment by carrickr** [comment]
A bunch of functions Phuong hooked into the 5.x Application Controller don't exist in 6 (store location, after_signin_path, and the entire Warden Block).  If the cherry-pick doesn't work we may find a way to do this in 6.x that differs from 5.x

**Comment by cjcolvar** [comment]
@joncameron @davidschober Is this critical for 6.0?  This has languished and could take some time for verifying it is working properly.

**Comment by davidschober** [comment]
@carrickr is this something you can reverify quickly? I'm OK pulling it out and pushing it in for the sprint immediately after release.

**Comment by cjcolvar** [comment]
@joncameron @davidschober This should be in place on spruce ready for testing.

**Comment by joncameron** [comment]
Tested on Spruce and works great in 6.0.
