### ISSUE TITLE
Write Documentation for AWS Work

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1489]
### Description
It would be beneficial to have documentation written for our Avalon setup in the Amazon cloud. How S3 works with Avalon, how Avalon uses elastic transcoder, etc. Anything that would be useful to have written down should be noted someplace in the Avalon wiki.

### Done Looks Like
- [ ] An appropriate area of the Avalon wiki is selected to put this content, including whether it should be public or private for the moment
- [ ] Overview of architecture CloudFormation creates
- [ ] Where can an installer find the code?
- [ ] How to spin up the code with CloudFormation
- [ ] Quickstart documentation in the README for Avalon-AWS Repo (not created yet) #1902

**Comment by davidschober** [comment]
Jon, what's this about?

**Comment by jlhardes** [comment]
NU and @phuongdh will grab this after NU has staging set up.

**Comment by phuongdh** [comment]
James Botino is taking notes and we'll use it for our doc
