### ISSUE TITLE
Attempting to Delete Marker Yields Error Message

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1497]
### Steps to Reproduce
1. Create a marker on a playlist item
1. Open the _Markers_ accordion and click the **Delete** button for any marker.
1. An error modal pops up (screen shot below)

### Expected Behavior
Clicking the Delete button for a marker should delete it and remove it from the list of markers for that playlist item.

![screen shot 2017-01-05 at 2 45 23 pm](https://cloud.githubusercontent.com/assets/1406618/21695007/e269a390-d355-11e6-8b4a-b6c659a508f2.png)

**Comment by bkeese** [comment]
{"message":"Marker was not updated: param is missing or the value is empty: marker"}
