### ISSUE TITLE
Selecting a Playlist Item Sometimes Skips Past the Desired Item

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1500]
### To Reproduce
1. Open a playlist (my example is https://mallorn.dlib.indiana.edu/playlists/2108)
1. Click on the third playlist item to navigate to that recording
1. Click on the first playlist item
1. The first playlist item appears to load briefly, then quickly skips down to the next playlist item

Repeated selecting of the first playlist item in the above case eventually loads up the first item for playback, but it took a couple of tries.

#### Environment
Mallorn running 5.x stable

**Comment by bkeese** [comment]
This PR is a reasonable fix. An argument can be made that we should do more work to improve playlist autoadvance. Specifically, I think we should write functions that can be used to enable and disable autoadvance and use them here to disable/enable autoadvance during stream switching. We have also discussed disabling autoadvance when scrubbing. I don't know if there is a story for this, but there should be.  I can also see adding a button to enable/disable autoadvance like Youtube's.
