### ISSUE TITLE
Write Documentation for old PID Migration

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1503]
### Description
The Avalon 6 migration tool stores the Fedora 3-style PIDs for posterity, but documentation has yet to be written to explain this process and where these PIDs are stored for administrators using the migration tool.

### Done Looks Like
Technical documentation is written about where Fedora 3 style PIDs are stored after migration.

Original issue: #836

### Tasks
- [x] Add documentation about new ids including configuring NOIDs and prov:wasDerivedFrom to https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+5.1.6+to+Avalon+6.0

### Related Issue
#2036 Documentation for Migration and Migration Report

**Comment by davidschober** [comment]
@mbklein and @cjcolvar this work was completed as part of our migration work, correct?

**Comment by cjcolvar** [comment]
We did the work, but I'm not sure if documentation was ever written for it.

**Comment by cjcolvar** [comment]
@davidschober @joncameron Is there a ticket for updating the Collection Managers Guide for 6.x? https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+Collections+Guide

**Comment by joncameron** [comment]
@cjcolvar @davidschober There isn't, but this would be a great task for Matthew to work on. He's already spent a lot of time cleaning this page up, so I'll just task him with changing references and updating as needed. I don't think I'll go as far as creating a ticket but if there are things you've noticed specifically please feel free to send him a Slack message.

**Comment by cjcolvar** [comment]
@joncameron The main thing I'm thinking of including that might need to new content instead of tweaking is the ids and anything pertaining to migration.

**Comment by cjcolvar** [comment]
@joncameron I've added something to the migration wiki page.  Do we also need something in the collection managers guide?

**Comment by joncameron** [comment]
@cjcolvar I think it would be good to have something on IDs in the guide. Are you interested in writing that section? If not Matthew or I can take it.

**Comment by cjcolvar** [comment]
I've never really edited the guide so I'd be happy if you or Matthew did it.  I could review if you'd like.

**Comment by cjcolvar** [comment]
Looking this over, it doesn't really seem to fit into the Collections Guide.  How about a What's New/Changes page for 6.x that is geared to collection managers.

**Comment by joncameron** [comment]
Information geared toward collection managers will be written up. Current draft here: https://wiki.dlib.indiana.edu/display/VarVideo/Changes+To+Be+Aware+of+After+Migration+to+Avalon+6.
