### ISSUE TITLE
Playlist autoadvance improvements

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#1504]
Write functions that can be used to enable and disable autoadvance and use them:
1. To disable/enable autoadvance during stream switching. 
2. To disable autoadvance when scrubbing.
3. For a new a button to enable/disable autoadvance like Youtube's.

**Comment by bkeese** [comment]
@davidschober @joncameron I'd like to start on this story this sprint. Would that be OK?

**Comment by joncameron** [comment]
New bug report filed: #1544
