### ISSUE TITLE
Construct URI for F3 PIDs and use prov:wasDerivedFrom to migrate as property to F4

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1526]
Based on Fedora 3 URL used for migration, construct a URI for any F3 PID that needs to come over to F4 (MediaObject, MasterFile, Derivative). Current custom predicate of avalon:migratedFrom can then become prov:wasDerivedFrom

Related to #836 (discussions recorded)

**Comment by jenyoung** [comment]
for migrations 

use predicate of prov:wasDerivedFrom for avalon:pid 

http://[fedora3URL.com]/avalon:pid as the object

**Comment by jlhardes** [comment]
This issue seems to be related to #1616 and might be a duplicate (but for a different milestone).

**Comment by mcwhitaker** [comment]
Whoever works on this needs to also look at #1616 and merge to this story what it does not mention.

**Comment by jlhardes** [comment]
Looks like there's a pull request for this so that review is needed but does this also need a metadata person review?
