### ISSUE TITLE
Investigate what Avalon default is for Physical Desc

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1533]
## Done
This ticket documents what goes into the physicalDescription element
- MODS element: relatedItem@type="original"/physicalDescription/extent
- RDF property: relatedItem@type="original"/physicalDescription/extent

NU and IU are using this differently.

IU using and mapping correctly.

NU displays the correct MODS element but the mapping in the MODS record is to physicalDescription/internetMediaType

**Comment by davidschober** [comment]
@jenyoung cant you add details.

**Comment by davidschober** [comment]
We need to quickly verify on paw paw.

**Comment by joncameron** [comment]
Double-checking on Pawpaw is what needs to be done to finish this issue.

**Comment by jenyoung** [comment]
related #1356

**Comment by jlhardes** [comment]
I created an item on Pawpaw and added physical description. It comes through as <extent> in MODS:

`<mods xsi:schemaLocation="http://www.loc.gov/mods/v3 http://www.loc.gov/standards/mods/v3/mods-3-4.xsd"><titleInfo usage="primary"><title>Test item</title></titleInfo><originInfo><dateIssued encoding="edtf">2017</dateIssued></originInfo><relatedItem type="original"><physicalDescription><extent>Test physical description</extent></physicalDescription></relatedItem><recordInfo><recordOrigin>Avalon Media System</recordOrigin><recordContentSource>IEN</recordContentSource><recordCreationDate>20170203</recordCreationDate><recordChangeDate>2017-02-03T10:38:12-05:00</recordChangeDate><languageOfCataloging><languageTerm authority="iso639-2b" type="code">eng</languageTerm></languageOfCataloging><recordIdentifier source="Fedora">avalon:9752</recordIdentifier></recordInfo></mods>`
