### ISSUE TITLE
UX Improvements for Playlist Markers

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1534]
### Descriptive summary
Playlist markers as they currently are have some elements that are confusing or problematic for users.

### Potential Issues to Resolve
- Markers are not clickable, but on a mouseover event, the cursor changes to the hand that indicates a clickable element
- The shape of the icon used makes it tough to determine the exact spot on the scrubber being referenced

### Potential Design Changes
- Changing the marker icon to a vertical stroke
- Making markers clickable

### Done Looks Like
A design meeting is scheduled to discuss these issues. Design documents (mockups, wireframes etc) are created and evaluated to create further issues to implement the proposed changes in code.

**Comment by davidschober** [comment]
@joncameron can we abandon this in favor of 7.x improvements?

**Comment by mcwhitaker** [comment]
@joncameron I think we can abandon it with respect to 5.x but not with respect to 6.x.

**Comment by joncameron** [comment]
I agree with Maria—I've dropped the 5.x tag. This discussion can apply to UI design we use for the player in Avalon in general, both for 6.x and beyond.

**Comment by gfitzwat** [comment]
Some ideas for the markers...
![1534artboard-1](https://user-images.githubusercontent.com/7095544/27453675-46684138-5765-11e7-9cd0-6eaf3a7c3fb0.png)
![1534artboard-2](https://user-images.githubusercontent.com/7095544/27453689-4e9b34f0-5765-11e7-8bd5-cadf1744c08e.png)

**Comment by joncameron** [comment]
We have design and recommendations for changes, so this issue can be considered closed. We'll take the discussion around this, make some decisions and create a new story to implement the changes desired.
