### ISSUE TITLE
Sort Playlists By Column Headings

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1535]
### Descriptive summary
As a user, I want to sort the table that contains my playlists (the playlist index) in order to more easily find the playlist I'm looking for.

The list of playlists available to a user is not currently able to be sorted, and is by default sorted by  creation date. Sorting is a standard operation on tables of information and would make it much easier to would make navigating through the list of playlists easier for users.

### Done Looks Like
Column headings on the playlist index (avalon_url/playlists) are clickable—clicking one will sort the table by the elements in that column. Sorting is done by standard lowest to highest by default (a to z, 0 to 9), with the ability to reverse that order if the heading is clicked again.

### Example of Functionality Desired
![jun-12-2017 13-33-17](https://user-images.githubusercontent.com/1406618/27046790-c2d4cfba-4f73-11e7-84b8-56dbfdbef293.gif)

**Comment by joncameron** [comment]
@bkeese Size isn't sorting correctly for me:
![jul-19-2017 16-27-38](https://user-images.githubusercontent.com/1406618/28388038-4d4bff86-6c9f-11e7-9aa5-44378e9c5094.gif)

**Comment by bkeese** [comment]
Your clicking the icon for the wrong column. The icons are right-justified, for some reason.

**Comment by joncameron** [comment]
@bkeese Yep, I realized that. Can we make the icons not right-justified? Maybe something like this where the icons are to the right of the text with a small amount of padding?

![screen shot 2017-07-19 at 4 36 22 pm](https://user-images.githubusercontent.com/1406618/28388507-f3cd7a78-6ca0-11e7-9843-ee5658f92beb.png)

**Comment by bkeese** [comment]
That would be an override to the datatables library we're using for this, which we can do. But, in the interest of keeping things maintainable, I think we should try to override as little as possible.

**Comment by mcwhitaker** [comment]
@joncameron Do we need the icons? Most of the tools I use do not show an icon; we just know that clicking on the column header sorts by that column.

Maybe @gfitzwat  could give us advice here... -- Matt, go to spruce.dlib.indiana.edu, login as archivist1@example.com, click playlists to see all the playlists owned by this user. The feature we are implementing is sorting by column.

**Comment by joncameron** [comment]
We're going to consider this done and move enhancements to new issues. I've tested and it works great!
