### ISSUE TITLE
As a User I Want to Make Copies of Playlists

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1536]
### Descriptive summary
As a user, I want to make a copy of a playlist so that I can easily create multiple versions of a playlist.

### Use Case
The ability to copy playlists means that a master playlist can be created, copied, and modified to meet different audiences and needs. This is especially the case for things like listening tests: you might circulate a longer playlist to students for studying, which you use to create the playlist for the exam in class.

### Done Looks Like
Users can create a copy of a playlist from the playlist index.
* A "Copy" button is available in the _Actions_ column of the playlist index, with the same styling as the Edit and Delete icons and with the clone icon from Font Awesome (http://fontawesome.io/icon/clone/).
* Clicking the copy button presents a modal to the user with elements:
  * Editable text field containing the string "#{source_playlist_name} Copy"
  * OK button
  * Cancel button
* After clicking the OK button in the modal
  * A copy of the playlist is created with the exact same items as the source playlist and with the name from the modal.
  * The new playlist appears in the playlist index

### Design Examples
![screen shot 2017-07-06 at 4 24 43 pm](https://user-images.githubusercontent.com/1406618/27931481-63732b0e-6268-11e7-80db-626b27e06c59.png)

![screen shot 2017-07-06 at 4 24 33 pm](https://user-images.githubusercontent.com/1406618/27931487-656b709c-6268-11e7-8b1c-f137baec6333.png)

### Tasks

**Comment by lealeelu** [comment]
I addressed the problem of there being two primary buttons. I turned one of them into default and put them both in a btn-group. How does this look?
![image](https://user-images.githubusercontent.com/5091130/28595283-3f958e72-7161-11e7-81bc-27759569c56c.png)

**Comment by bkeese** [comment]
Looks great!

**Comment by joncameron** [comment]
Same comment as Brian! I like the look of having them both in a btn-group.

**Comment by phuongdh** [comment]
Looks good.

**Comment by davidschober** [comment]
This looks good. Let's go with it.
