### ISSUE TITLE
Stand up clean Hyrax environment

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1540]
## DONE

- [ ] Figure out where we're going to put it (VM?)
- [ ] Stand up environment
- [ ] install clean/non-modified Hyrax
- [ ] try uploading a video and audio item and analyze the metadata aspects of hyrax
- [ ] break out tickets for investigation 

related to #1479

**Comment by joncameron** [comment]
This should be broken if necessary once the work starts.

**Comment by davidschober** [comment]
Great news!

**Comment by phuongdh** [comment]
http://ec2-54-200-29-241.us-west-2.compute.amazonaws.com:3000/

**Comment by davidschober** [comment]
Thanks!
