### ISSUE TITLE
Playlist Marker Icons Incorrectly Aligned to Offset

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1541]
### Steps to reproduce
See the following public playlist: https://media.dlib.indiana.edu/playlists/859
 
You can see that when the 1st marker, close to the beginning of the playlist item, is selected, the carat lines up well with the scrubber, but when the last marker, near the end, is selected, it does not line up.

### Done Looks Like
Playlist marker icons are properly aligned to the correct visual position on the rail.

### Example Images
![marker 1 selected](https://cloud.githubusercontent.com/assets/1406618/22151657/fa6b893e-deec-11e6-95ca-2851ff0b1193.png)

![marker 5 selected](https://cloud.githubusercontent.com/assets/1406618/22151658/fd217940-deec-11e6-94f3-3d2694c83a4d.png)

**Comment by joncameron** [comment]
This bug needs to be confirmed for 6 before adding the 6.x label.

**Comment by bkeese** [comment]
This seems to be dependent on screen size. On my laptop it looks right, but on my phone the scale used for marker placement is off one way when in portrait mode (too wide) and off the other way in landscape (too narrow). Weird.

**Comment by carrickr** [comment]
@joncameron Could one of you verify this occurs in 6.x?  If not, can we abandon given everyone is moving 6.x this summer?

**Comment by lealeelu** [comment]
It's happening in 6.x on spruce.
I noticed that the further into the track the bookmark is placed, the more it's off by. The track display is probably fine, it's the markers that are off. I added some images above.

**Comment by cjcolvar** [comment]
@joncameron @davidschober Do we need to backport this to 5.x?

**Comment by joncameron** [comment]
@cjcolvar @davidschober It doesn't, and I've removed the 5.x tag. I think that tag is a carry-over from when the issue was created.

**Comment by joncameron** [comment]
@cjcolvar @davidschober It doesn't, and I've removed the 5.x tag. I think that tag is a carry-over from when the issue was created.

**Comment by Karthikeya212** [comment]
The alignment of marker with scrubber is fine for a newly created marker, but if an existing marker is edited it is going out of phase with the scrubber and the page needs to be refreshed to get the marker in sync to the scrubber.

**Comment by bkeese** [comment]
Changes to the math here will be needed (reference commit: https://github.com/avalonmediasystem/media-element-add-to-playlist/commit/a2b6c8c6da1df45587171d02da758e0d7ce2629a) https://github.com/avalonmediasystem/avalon/blob/master/app/assets/javascripts/marker.js.coffee#L60

**Comment by lealeelu** [comment]
Found a problem with the markers. They don't update their position with screen resizing since they're not based off of percentage anymore. Can we update the pixel math on resize?
![image](https://cloud.githubusercontent.com/assets/5091130/26648298/059bf6d8-4610-11e7-8e7d-9aeb81f3dafd.png)
![image](https://cloud.githubusercontent.com/assets/5091130/26648327/1fb2995a-4610-11e7-9677-63bae48f95e9.png)
