### ISSUE TITLE
Test Batch Ingest for OVA

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1542]
### Description
Testing has been completed for the OVA on every measure except batch ingest. Phuong would like to use this as a special test to see if the average user trying Avalon out via the OVA can figure out where to put the files for ingest, and whether it works properly.

### Done Looks Like
Batch ingest is tested for the 6.0 OVA.
- [ ] ~~Batch ingest confirmed working (ingest sheets placed in the correct directory are automatically picked up and processed)~~
- [ ] ~~Instructions are written or updated for how to try out batch ingest via the OVA.~~

### Follow Up
#1623 is the bug report written out of this task, since this is more of a bug report now because of the testing that took place.

**Comment by phuongdh** [comment]
Drop your batch into /avalon-docker/masterfiles
