### ISSUE TITLE
Discuss Naming for Track Scrubber

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1551]
### Descriptive summary
A staff member at the IU Music Library has reported that users are confused by the naming and tooltip text for the track scrubber (lil' scrub, colloquially). I'd like to meet and discuss, possibly iterating over the current naming to get to something more intuitive for the average user.

### Done Looks Like
- [ ] Small team meeting to discuss naming for lil' scrub
- [ ] Decision made and documented about whether to change the name, what to change it to if so, and a timeline for effecting that

**Comment by davidschober** [comment]
is it the naming or can users not find the little guy?

**Comment by mcwhitaker** [comment]
@davidschober The comment made reference to the name. Apparently when you talk to them about scrubber in the documentation, or if the help desk refers to it as the scrubber, they don't know exactly what you are talking about.
