### ISSUE TITLE
Playlist Autoadvance Skips Items

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1552]
### Steps to Reproduce
1. Go to the following playlist page and click play: https://mallorn.dlib.indiana.edu/playlists/709
1. The third item in the playlist is skipped over

Complete #1861 prior to this

- [x] Create new playlist where this appears
- [ ] Investigate event timing when loading RTMP
- [ ] determine if a fix is possible with current player and the cost/potential tradeoffs
- [ ] rewrite autoplay (if possible) to better react to event timing

### Done Looks Like
Autoplay moves from item to item and plays through the full length of each playlist item

**Comment by carrickr** [comment]
Playlist 2108 has been removed from mallorn or made private ( @joncameron  ).  We'll need to make a new playlist

**Comment by carrickr** [comment]
Root cause is the way the player responds to the changing of its sources and the fact the player still has some events from the previous source, leading to a weird synchronization problem between previous events and new events .

**Comment by joncameron** [comment]
I've created a new playlist that exhibits the behavior in this bug.

**Comment by joncameron** [comment]
Closing as abandoned since this will be different/irrelevant with the mediaelement upgrade.
