### ISSUE TITLE
Playlist Item in Scrubber Shows Item Duration Instead of Section Duration

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1553]
### Summary

On a playlist view page, a playlist item is displayed to the user in the media player by a colored bar within the full range of the section from which the playlist item was created. This leads to  strange user experience:
- Markers can be created beyond the bounds of the item's time range
- Users are able to navigate before and after the range of the playlist item

### Use Cases
For many of the items to which this applies, structural metadata defines discrete sections within a file. Generally, the user intent will be to capture a pre-defined segment of the media object (defined as structural metadata) and not an arbitrary range withing a section. This makes the full view of the item unnecessary. 

### Done Looks Like
The media player should only show the duration of the playlist item in the media player, rather than the full section.

### Questions
- What happens to markers which are currently outside of the bounds of a playlist item? These display currently, but would not if the scrubber only showed the range of the

**Comment by mcwhitaker** [comment]
@joncameron This would be covered by work done on enhancement request #1849

**Comment by joncameron** [comment]
Closing in favor of #1849 to represent this work.
