### ISSUE TITLE
White Paper: Current state

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1557]
### Descriptive summary

Relates to #1479 

Brief description of current state of Avalon. Making it clear how Avalon is built.

**Comment by davidschober** [comment]
We realized there's actually two current states!

- [x] Current state overview
- [ ] 5.x current state @carrickr 
- [ ] 6.x current state @csyversen

**Comment by csyversen** [comment]
@davidschober done

**Comment by csyversen** [comment]
5.x current state is written up too

**Comment by davidschober** [comment]
Looks good. Closing.
