### ISSUE TITLE
White Paper: Overview of Hyrax

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1558]
Write an overview of Hyrax, what it does and what it means, generally for the Hydra community. 

relates to #1479

**Comment by joncameron** [comment]
We may want to have a conversation with Hyrax POs or other team members about their group, goals etc. 

- Read Material
- Talk to Hyrax team
- Write section

**Comment by jlhardes** [comment]
http://hyrax.projecthydra.org/about/managers/

**Comment by davidschober** [comment]
This section got wrapped into the the research of #1559 a bit. I'll grab it and write a draft.

**Comment by davidschober** [comment]
wrote a brief description and grabbed bullet points of features from hyrax. Should be enough for a general discussion.
