### ISSUE TITLE
White Paper: Avalon in the new Model

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1559]
Write a brief description about how Avalon fits into the new hyrax model. What a Hyrax driven avalon would look like. 

 - ActiveEncode—are we using it fully?
 - Hyrax...
  - Functionally
  - Parts of the code that matter or don't matter—identify and map what parts of Avalon will fit into the Hyrax model

#1479

**Comment by joncameron** [comment]
This could be a couple of swarms for discussion; this will be more of a group effort than other sections of the white paper.

**Comment by davidschober** [comment]
Completed with three scenarios. This is a draft, we will expect changes.
