### ISSUE TITLE
White Paper: Modularizing Avalon Features

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1560]
Write a brief descriptions about features that can be modularize and what features would need to remain monolithic. This is a position paper, so be opinionated. If there are disagreements, state them. 

 - Identify features that can be broken out
 - Identify features that cannot be broken out (what's part of the monolith/core?)
 - Make a note to follow intentions of the Hydra plug-in group and architecture best practices
 - Chris C is involved with the Hydra Plugins group and can help guide this

relates to #1479

**Comment by joncameron** [comment]
Timeboxed to 5 points.

**Comment by joncameron** [comment]
@mcwhitaker will attach a list of features.

**Comment by mcwhitaker** [comment]
[Avalon Features - HydraConnect 2016.docx](https://github.com/avalonmediasystem/avalon/files/735974/Avalon.Features.-.HydraConnect.2016.docx)

**Comment by davidschober** [comment]
@carrickr and @csyversen I think this is going to end up falling into our "three scenarios" a bit. Maybe we just take the features and bullet out low hanging fruit?

**Comment by davidschober** [comment]
These ended up being discussed in general as part of our "three scenarios" I added this list to the doc as an appendix.
