### ISSUE TITLE
Tried installation of Avalon 6 and got the Blacklight::Exceptions::InvalidRequest in CatalogController#index

### ISSUE THREAD

**Issue by taozhaolib** [avalonmediasystem/avalon#1569]
First time player. 
Followed the step-by-step instructions at https://wiki.dlib.indiana.edu/display/VarVideo/Manual+Installation+Instructions. 

Some info:
CentOS 7, Ruby 2.3.1, MariaDB 5.5.52, Solr 4.2.0, Tomcat 7.0.75, Java 8. 
Fedora 4 and Solr both deployed normally.

Details:
RSolr::Error::Http - 404 Not Found Error: 
HTTP Status 404 - The requested resource is not available.
<h3>Apache Tomcat/7.0.75</h3></body></html> URI: http://127.0.0.1:8983/solr/hydra-development/select?wt=ruby 
Request Headers: {"Content-Type"=>"application/x-www-form-urlencoded; charset=UTF-8"} Request Data: "qt=search&facet.field=avalon_resource_type_ssim&facet.field=creator_ssim&facet.field=date_sim&facet.field=genre_sim&facet.field=collection_ssim&facet.field=unit_ssim&facet.field=language_sim&facet.field=workflow_published_sim&facet.field=created_by_sim&facet.field=read_access_virtual_group_ssim&facet.field=date_digitized_sim&facet.field=date_ingested_sim&&&fq=%28%7B%21terms+f%3Dedit_access_group_ssim%7Dpublic%2C172.28.128.1%29+OR+%28%7B%21terms+f%3Ddiscover_access_group_ssim%7Dpublic%2C172.28.128.1%29+OR+%28%7B%21terms+f%3Dread_access_group_ssim%7Dpublic%2C172.28.128.1%29&fq=has_model_ssim%3A%22MediaObject%22&fq=workflow_published_sim%3A%22Published%22&fq=%28*%3A*+NOT+hidden_bsi%3Atrue%29&&rows=10&sort=score+desc%2C+title_ssort+asc%2C+date_ssi+desc" 
Backtrace: /home/avalon/.rvm/gems/ruby-2.2.5/gems/rsolr-1.1.2/lib/rsolr/client.rb:288:in `adapt_response' /home/avalon/.rvm/gems/ruby-2.2.5/gems/rsolr-1.1.2/lib/rsolr/client.rb:189:in `execute' /home/avalon/.rvm/gems/ruby-2.2.5/gems/rsolr-1.1.2/lib/rsolr/client.rb:175:in `send_and_receive' /home/avalon/.rvm/gems/ruby-2.2.5/gems/blacklight-6.7.2/lib/blacklight/solr/repository.rb:38:in `block in send_and_receive' /home/avalon/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.7.1/lib/active_support/benchmarkable.rb:41:in `block in benchmark' /home/avalon/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.7.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms' /home/avalon/.rvm/rubies/ruby-2.2.5/lib/ruby/2.2.0/benchmark.rb:303:in `realtime' /home/avalon/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.7.1/lib/active_support/core_ext/benchmark.rb:12:in `ms' /home/avalon/.rvm/gems/ruby-2.2.5/gems/activesupport-4.2.7.1/lib/active_support/benchmarkable.rb:41:in `benchmark' /home/avalon/.rvm/gems/ruby-2.2.5/gems/blacklight-6.7.2/lib/blacklight/solr/repository.rb:36:in `send_and_receive' /home/avalon/.rvm/gems/ruby-2.2.5/gems/blacklight-6.7.2/lib/blacklight/solr/repository.rb:22:in `search'

Thanks.

**Comment by taozhaolib** [comment]
![image](https://cloud.githubusercontent.com/assets/7934682/22571790/f8a39d38-e966-11e6-9fd0-ec8a84e77009.png)

**Comment by cjcolvar** [comment]
Seems like Avalon can't connect to your solr or fedora servers.  I would check those two services are up and that they are configured properly for Avalon in config/solr.yml and config/fedora.yml.

**Comment by taozhaolib** [comment]
solr.yml 
# This is a sample config file that points to a solr server for each environment
development:
  url: http://localhost:8983/solr/
test:
  url: http://localhost:8983/solr/
production:
  url: http://localhost:8983/solr/

fedora.yml
development:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fcrepo-webapp-4.7.0
  base_path: /dev
test:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fcrepo-webapp-4.7.0
  base_path: /test
production:
  user: fedoraAdmin
  password: fedoraAdmin
  url: http://127.0.0.1:8983/fcrepo-webapp-4.7.0/rest
  base_path: /prod

BTW,
http://127.0.0.1:8983/solr and http://127.0.0.1:8983/fcrepo-webapp-4.7.0/rest both display normally.

**Comment by phuongdh** [comment]
Your application wants to connect to "hydra-development" core on Solr. Did you name the “avalon” core this way, or this came from another Hydra-based application?

**Comment by phuongdh** [comment]
If I understand correctly, you're trying to install the develop branch of Avalon. If so hydra-development is indeed the name of the default Solr core for development. How did you create this core? Did you feed it the correct configs here https://github.com/avalonmediasystem/avalon/tree/master/solr_conf/conf ?

**Comment by taozhaolib** [comment]
Thank a lot for the replies. I tried again with Avalon 5 installation and got a seemly working instance which means the protocol does work for Avalon 5. Now I am repeating again with Avalon 6 with better understanding with the instructions. Will keep you guys posted.

**Comment by taozhaolib** [comment]
What does it mean "Also check in etc/load/org.opencastproject.organization-mh_default_org.cfg"?

Create a new file of etc/load/org.opencastproject.organization-mh_default_org.cfg and put in 

prop.avalon.stream_base=file:///var/avalon/rtmp_streams?

Also, it there missing a / before etc?

Thanks.

**Comment by taozhaolib** [comment]
I got the exact same error with the second trial of Avalon 6 installation. Even after I tried replacing the solr/config/schema.xml and the solr/config/solrconfig.xml with the ones from https://github.com/avalonmediasystem/avalon/tree/master/solr_conf/conf. 

I have no idea where the "hydra-development" solr core is from.

BTW, I used the newest branch of Avalon 6: 6.x-playlist-enhance. Should I try the 6.0.alpha?

I also wonder when you will post the official instruction for Avalon 6 install and wonder what is the difference between 5 and 6 install.

Thanks.

**Comment by bkeese** [comment]
Since version 6 has not been released, we don't recommend trying it yet. It will be released in the coming weeks and will include updated installation instructions.

**Comment by taozhaolib** [comment]
Thanks bkeese.

Right now I just want to set up a developer version instance. 

I also tried the easy installation posted at https://github.com/avalonmediasystem/avalon/tree/v6.0.0.alpha but also got an error with solr 6.2:

[root@test-box avalon]# bundle exec rake server:development
solr-6.2.0.zip: |====================================================================================| 100% (Time: 00:01:48 )
solr-6.2.0.zip.md5: |================================================================================| 100% (Time: 00:00:00 )
rake aborted!
NoMethodError: undefined method `include?' for nil:NilClass
/usr/local/rvm/gems/ruby-2.3.1/gems/solr_wrapper-0.18.0/lib/solr_wrapper/client.rb:24:in `collection?'
/usr/local/rvm/gems/ruby-2.3.1/gems/solr_wrapper-0.18.0/lib/solr_wrapper/client.rb:15:in `exists?'
/usr/local/rvm/gems/ruby-2.3.1/gems/solr_wrapper-0.18.0/lib/solr_wrapper/instance.rb:152:in `create'
/usr/local/rvm/gems/ruby-2.3.1/gems/solr_wrapper-0.18.0/lib/solr_wrapper/instance.rb:211:in `with_collection'
/usr/local/rvm/gems/ruby-2.3.1/gems/active-fedora-11.0.0/lib/active_fedora/rake_support.rb:26:in `block in with_server'
/usr/local/rvm/gems/ruby-2.3.1/gems/solr_wrapper-0.18.0/lib/solr_wrapper/instance.rb:64:in `wrap'
/usr/local/rvm/gems/ruby-2.3.1/gems/solr_wrapper-0.18.0/lib/solr_wrapper.rb:40:in `wrap'
/usr/local/rvm/gems/ruby-2.3.1/gems/active-fedora-11.0.0/lib/active_fedora/rake_support.rb:17:in `with_server'
/home/vagrant/avalon/Rakefile:38:in `run_server'
/home/vagrant/avalon/Rakefile:20:in `block (2 levels) in <top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => server:development
(Centos 7 box, Ruby 2.3.1)

I am not familiar with Ruby so could you please take a look?

**Comment by taozhaolib** [comment]
I think I just finished installing the Avalon 6 Dev version in a vagrant box after I tweaking a little stuff. Right now I can curl http://localhost:3000 to get the output of the web page. However, I still could not curl the internal and external IP addresses: curl http://internal.IP:3000 and curl http://external.IP:3000 and both got refused connections. Any configuration I need to do about this?

Thanks.

**Comment by cjcolvar** [comment]
We haven't finished the packaging and install/update documentation for Avalon 6 yet so I'm not sure how to help you since you're in uncharted territory.

@carrickr just finished writing some documentation on how to setup an Avalon 6 development environment with docker.  He is getting some people from NU to test today, but you could go ahead and try it out and give him feedback in our slack channel #avalon on https://project-hydra.slack.com/.

**Comment by taozhaolib** [comment]
Thank you very much cjcolvar. But I do need to show a dev instance to someone next week. Is there any configurations to be set on the WEBrick server?

**Comment by carrickr** [comment]
If you are on OS X, we have a tested install based on docker containers documented here:

https://github.com/avalonmediasystem/avalon/wiki/Configuring-an-OS-X-Development-Environment-With-Docker-Containers

This works with 6.0 on OS X.  It should work on Linux as well, although with Linux I'm not sure if the networking hack steps are needed or if they are different.

**Comment by taozhaolib** [comment]
Thank you carrickr. I'll try it this weekend.

**Comment by taozhaolib** [comment]
The Docker avalon installation was not working well but I did managed to install the dev version on my vagrant box. Right now I can see the Avalon 6 running but there seems to be a bug: Sometimes when the program hits the database, e.g. creating new user, user login, create new playlist, the server cannot send back a valid page, and sometimes it shows "Blacklight::Exceptions::InvalidRequest in CatalogController#index ".

Is there any setting wrong or something? Where do I check the log?

Thanks.

**Comment by taozhaolib** [comment]
For example, when I try to log in, the server prints out with empty page:

Started GET "/users/auth/identity?action=new&controller=users%2Fsessions" for 172.28.128.1 at 2017-02-13 21:46:19 +0000
(identity) Request phase initiated.


Started POST "/users/auth/identity/callback" for 172.28.128.1 at 2017-02-13 21:46:22 +0000
(identity) Callback phase initiated.
  Identity Load (0.0ms)  SELECT  "identities".* FROM "identities" WHERE "identities"."email" = ?  ORDER BY "identities"."id" ASC LIMIT 1  [["email", "tao.zhao.lib@gmail.com"]]
Processing by Users::OmniauthCallbacksController#identity as HTML

**Comment by carrickr** [comment]
Did you have the docker install fail for you on an OS X box or is your development host running Linux?

**Comment by taozhaolib** [comment]
I did not use docker, and instead I installed avalon in a vagrant box with the instructions in the README of the github repository. The docker installation was fine with solr, fedora, and something, until the step of avalon installation, where the matterhorn was installed, maybe due to the tomcat running in the host machine? Not sure about that. But I did the installation just using the vagrant box.

**Comment by carrickr** [comment]
The easiest path will probably be to wait till next sprint when we have the full R6 directions done.  As it is I'm not sure how you configured what you currently have, but if you were using R5 directions it is possible that you have an older version of Solr (specifically Solr 4) installed, etc.  Which might explain some of those issues you're seeing with Blacklight, but it also could be other issues.

**Comment by phuongdh** [comment]
@taozhaolib Instruction for 6.0 has been released, please give it a try and open a new ticket if you run into problems. Thanks https://wiki.dlib.indiana.edu/display/VarVideo/Manual+Installation+Instructions
