### ISSUE TITLE
Expose secured about_page to monitoring software

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#1579]
### Description
Nagios gets its information from about/health.yaml, which has recently required authentication. As a sysadmin, I need a way to expose this information or let Nagios authenticate somehow. This could be through a token or other means.

### Done Looks Like
- The means to authenticate or expose about page to monitoring software is determined and written into Avalon

### Tasks
- [ ] Make /about/health.yaml publicly accessible. /about can stay private.
- [ ] Make sure Nagios is getting the info needed

**Comment by cjcolvar** [comment]
@joncameron @davidschober do we need this for 6.0 or can it wait for 6.0.1?  As it is we can't monitor any Avalon 6 test machines using health.yaml.

**Comment by davidschober** [comment]
6.0.1
