### ISSUE TITLE
Facet Counts Wrap Incorrectly

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1586]
### Description
Facet counts break in the middle of long (3 digit and more) numbers, leading to unsightly spacing. This story will be timeboxed, and this issue will be worked on in a future point release if the scope is too broad.

### Example from Mallorn on 2/10/17, running Avalon 6.0
![screen shot 2017-02-10 at 10 38 55 am](https://cloud.githubusercontent.com/assets/1406618/22832743/40fa7fa4-ef7d-11e6-9d7c-b2d4a60b8cab.png)

### Done Looks Like
There are no line breaks in facet counts.

**Comment by mbklein** [comment]
Why not just add `whitespace: nowrap` to the `.facet-values .facet-count` CSS selector?

![avalon 2017-02-10 13-31-00](https://cloud.githubusercontent.com/assets/196872/22841033/82051032-ef95-11e6-87c9-049a11dd95a4.png)

**Comment by bkeese** [comment]
This isn't actually about the facet-count wrapping. It's about establishing its fixed width so that wrapping of the facet-label can happen correctly.

**Comment by mohideen** [comment]
The facet_load.js fix is not working if none of the facets have the `collapse: false` option configured.

**Comment by bkeese** [comment]
Blacklight now has the facet_load fix, and it is improved. We can get rid of our override.

**Comment by cjcolvar** [comment]
`facet_load.js` will be removed with #2527.
