### ISSUE TITLE
Release 6.0

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1588]
### Description
Officially releasing to the world.

- [x] Write a draft of release notes on Github
- [x] Publish release on Github <https://github.com/avalonmediasystem/avalon/releases>
- [x] Update wiki with release notes as needed
- [x] Publish blog post announcing the release
- [x] send out email to hydra/ slack

**Comment by davidschober** [comment]
@mcwhitaker I don't think I have access to the blog. Do you? Last thing then I'm closing this...

**Comment by mcwhitaker** [comment]
@davidschober No, the blog is in the drupal website and I don't have access to that. We need to ask @joncameron to grant us access to that so we can take care of things in his absence.

**Comment by mcwhitaker** [comment]
@davidschober Matthew has access to it. I can ask him to publish it. What is the text to be published, is it the announcement that Evviva sent out?
