### ISSUE TITLE
Migrated audio items showing video player

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1592]
Viewing a sound recording item on mallorn is showing the video player instead of the audio player.

migrated item: https://mallorn.dlib.indiana.edu/media_objects/q811kj631

MCO item: https://media.dlib.indiana.edu/media_objects/avalon:22180

**Comment by cjcolvar** [comment]
Looks like there might be a number of fields missing being migrated from the master file descMetadata datastream.  I'll look into this.

**Comment by cjcolvar** [comment]
Actually, it looks like file_format was the only field not coming over.  I have a PR for this.
