### ISSUE TITLE
[Mallorn] item time duration not showing on search results

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1599]
### Descriptive summary
item time duration not showing on search results

### Expected behavior
Time Duration of each item should be shown in parenthesis to the right of the item title.

### Actual behavior
item time duration not showing on search results

### Steps to reproduce the behavior

1. Login to mallorn
2. Click "browse"
3. Notice the durations missing

Example of item in 5.x:

![image](https://cloud.githubusercontent.com/assets/16720883/22904134/3d04b7aa-f209-11e6-97f6-186b34c75477.png)

Example of item in mallorn:
![image](https://cloud.githubusercontent.com/assets/16720883/22904152/50a1f05c-f209-11e6-98fa-47d1fe7cb0e1.png)

**Comment by cjcolvar** [comment]
This just requires a redeploy of latest develop branch to mallorn.  We can do this today.

**Comment by joncameron** [comment]
Closing as this is fixed.
