### ISSUE TITLE
R5 to R6 Metadata: Permalink predicate

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#1604]
Both MediaObject and MasterFile have permalink listed but property used is http://projecthydra.org/ns/relations#hasPermalink instead of dc:identifier as listed in #1068

## DONE

Decide if we 
* Fix it now
* Fix it later
* Don't Fix it

**Comment by joncameron** [comment]
We'll leave this here for doublechecking migration. #1627 is the one that will be worked on immediately for 6.0 release.

**Comment by cjcolvar** [comment]
We need to investigate if this is broken in the R5->R6 migration and if it is then it would be priority.

**Comment by cjcolvar** [comment]
This can wait until 6.0.1
