### ISSUE TITLE
R5 to R6 Metadata: Derivative height/width

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#1605]
Derivative - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/1c/59/de/b8/1c59deb8-42bf-4460-a1b9-192e264d605a
ebucore:encodingLevel, ebucore:hasMimeType, ebucore:hasCodec, ebucore:bitRate, avalonEncoding:audioCodec, and avalonEncoding:audioBitRate are here from Encoding class (#1055) but not ebucore:height, ebucore:width

**Comment by joncameron** [comment]
This also may be a problem still (possibly not), will need testing.

**Comment by jlhardes** [comment]
This item is a video derivative and is still missing ebucore:height and ebucore:width: http://mallorn.dlib.indiana.edu:8984/fedora4/rest/c5/44/a9/5a/c544a95a-613b-4efb-8c0f-125a96ddb2d1

**Comment by lealeelu** [comment]
Is this something that needs to be added to the migration script?

**Comment by cjcolvar** [comment]
Yes.

**Comment by bkeese** [comment]
I'm guessing the fix is to set width and height on target here: https://github.com/avalonmediasystem/avalon/blob/master/app/migration/fedora_migrate/derivative/encoding_datastream_mover.rb#L31
