### ISSUE TITLE
R5 to R6 Metadata: Collection Bibframe version

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#1606]
Collection (AHEYM) - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/rj/43/04/57/rj430457n
http://bibframe.org/vocab/heldBy is from BF1.0, not BF2.0 (http://id.loc.gov/ontologies/bibframe/heldBy)
using BF2.0, value needs to be URI
recommendation was to use BF2.0 term, but either way expected value is a URI, not text

## DONE

Decide if we

* Fix it now
* Fix it later
* Don't Fix it

**Comment by jlhardes** [comment]
Fix it later - leave it as string for now or coerce string into URI that is avalon namespaced thing that isn't real for anything. In future, make that field editable to be mappable to LOC-style vocab authority. 

Don't fix it - See what Hyrax does with admin_sets and if that can work for units in R7.

**Comment by cjcolvar** [comment]
I vote for leaving it as is for now and creating a ticket to explore how Hyrax handles this.  So don't fix in 6.x and deal with it in 7.0.

**Comment by jlhardes** [comment]
Avalon doesn't deal with units as it should. 

Proposed solution: For now, keep bf:heldBy and use it incorrectly with strings. Inquire with Hyrax about admin_sets to see if those are something that can work for Avalon units and how those are mapped. If Hyrax has a unit solution, wait until R7 and fix units to match that mapping. If Hyrax does not have a unit solution, fix in R6.x to make units managed as URIs with the bf:heldBy property.

**Comment by jenyoung** [comment]
Hyrax does not out-of-the box have a concept of "Unit" anywhere let alone in admin sets but is something we could customize locally.

**Comment by jenyoung** [comment]
Closing - issue to be fixed in #1763
