### ISSUE TITLE
R5 to R6 Migration: Collection manager/editor missing

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#1607]
### Description
Staff on a collection are not carried over in the migration.

Collection (AHEYM) - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/rj/43/04/57/rj430457n
I also noticed that one manager/editor didn't make it to the collection on mallorn.

### Done Looks Like
- [ ] A test migration is performed so we have data to evaluate if needed (the original mallorn example above doesn't look like it exists anymore)
- [ ] Migration updated so that all managers and/or editors on migrated collections carry over

**Comment by cjcolvar** [comment]
I just ran a migration on mallorn and wasn't able to reproduce this. I'll keep an eye out for this when we run our test migration of IU production.

**Comment by cjcolvar** [comment]
I spot checked about 15 collections after running the migration from MCO and didn't see this problem.  I'm closing this.
