### ISSUE TITLE
R5 to R6 Metadata: Collection default special access missing

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#1608]
## Description

Collection (JSoM Performance) - http://mallorn.dlib.indiana.edu:8984/fedora4/rest/25/14/nk/49/2514nk499
The default special access (list of users and groups) didn't appear to migrate.

## Done looks like

- [ ] special access migration is rechecked and outcome is recorded if the default special access does not migrate cleanly. 
- [ ] default special access migrates cleanly

**Comment by joncameron** [comment]
This may have fixed and should be verified.

**Comment by davidschober** [comment]
@bkeese was this fixed?

**Comment by bkeese** [comment]
We haven't checked yet.

**Comment by davidschober** [comment]
cool.

**Comment by cjcolvar** [comment]
I think this may have been fixed, but I'll verify when we test migrate IU's production content.

**Comment by cjcolvar** [comment]
I spot checked about 15 collections after running a migration from MCO and didn't see this problem so I'm closing this now.
