### ISSUE TITLE
R5 to R6 Migration: fix role_map migration

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#1610]
When migrating mallorn from R5 to R6, the role_map ended up with more than one managers and administrators groups. It seemed to merge the role_map imported from the R5 sql dump with the existing R6 role_map (from cache?).

### Done Looks Like
- [ ] Validation is performed

**Comment by joncameron** [comment]
This may be fixed. TBD.

**Comment by cjcolvar** [comment]
I didn't notice this being a problem the last time I tested the migration, but I'll check again the next time I run it and close if it isn't a problem.

**Comment by bkeese** [comment]
This can be closed. It was an artifact of my testing wherein I had a different authentication configurations for the R5 and R6 instances I was using. I made a note in the migration instruction wiki page addressing this possibility.

**Comment by cjcolvar** [comment]
I'm noticing that the role_map table will reload from the yaml if any requests are made after the wipeout script is run and before the DB dump is loaded.  We should put a note about this somewhere to warn people who are rerunning the migration script.
