### ISSUE TITLE
R6 - scrubber missing icons

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1611]
### Descriptive summary

Mallorn on R6 - scrubber is missing icons for quality level and volume.

### Expected behavior

Icons should be available

### Steps to reproduce the behavior

1. Login to mallorn
2. click Browse
3. click on second item in search results (10th USA International Harp Competition : final stage : Elizabeth Bass, Lenka Petrovic, Katherine Siochi, harp.)
4. For video, search for Boryslav and click on that item in search results.
5. Note that the scrubber is not showing the icons

Example scrubber in r5 (audio):
![image](https://cloud.githubusercontent.com/assets/16720883/23006814/29723544-f3d2-11e6-89a7-b8f1f8cdc4c6.png)

Example scrubber in r6 (audio):
![image](https://cloud.githubusercontent.com/assets/16720883/23006839/4d72e61e-f3d2-11e6-8676-4c9ccce8892a.png)

Example scrubber in r5 (video):
![image](https://cloud.githubusercontent.com/assets/16720883/23008296/9f45ca6a-f3dc-11e6-9ac1-29320f67d8bc.png)

Example scrubber in r6 (video) missing quality level gadget:
![image](https://cloud.githubusercontent.com/assets/16720883/23008335/dc795384-f3dc-11e6-8b8a-c015763b3580.png)

**Comment by carrickr** [comment]
Cannot reproduce on Spruce with current items, spot checking shows all the icons:

https://spruce.dlib.indiana.edu/media_objects/tm70mv16z

https://spruce.dlib.indiana.edu/media_objects/9k41zd48h

**Comment by bkeese** [comment]
I'm seeing volume but not quality selector icons on those items.

**Comment by mbklein** [comment]
I see volume but not quality selector. I've found the issue and am fixing it now.
