### ISSUE TITLE
R6 - styling of facets missing bold

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1612]
### Descriptive summary

On mallorn, r6, the styling of the facets navigation bar needs the facet names bolded.

### Expected behavior

The bolding helps distinguish the facet names from the facet values.

### Steps to reproduce the behavior

1. Login to mallorn
2. Look at the facet names

Example in r5:
![image](https://cloud.githubusercontent.com/assets/16720883/23006966/1f7e4360-f3d3-11e6-98e8-b002c45ef01d.png)

example in r6:
![image](https://cloud.githubusercontent.com/assets/16720883/23007002/46948900-f3d3-11e6-9667-d8c373b8c81b.png)

**Comment by joncameron** [comment]
@mcwhitaker I don't see this on Spruce... what browser did you see this in?

**Comment by mbklein** [comment]
I can't reproduce this, either. Facet names are showing up bold for me in Safari, Chrome, and Firefox, both on my local dev machine and on mallorn.

**Comment by davidschober** [comment]
Can we move to in review as "Can't reproduce"

**Comment by carrickr** [comment]
Same here on local, spruce and mallorn, can't reproduce
