### ISSUE TITLE
Cannot View Playlists on Mallorn and Spruce

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1613]
### Descriptive summary

When trying to view a playlist on Mallorn, an error is raised.  To reproduce, log in as archivist 1 and then visit: https://mallorn.dlib.indiana.edu/playlists/708

It will raise an error:
<img width="1436" alt="screen shot 2017-02-16 at 10 42 41 am" src="https://cloud.githubusercontent.com/assets/5350060/23028350/19571176-f435-11e6-8b87-c2ab3061ce07.png">

**Comment by carrickr** [comment]
This can be reproduced on Spruce, same behavior

**Comment by carrickr** [comment]
Alright who renamed the helper method from mediaobject to media_object?  fess up

**Comment by bkeese** [comment]
points at cjcolvar
