### ISSUE TITLE
Leases are applied to all items, regardless of user type or collection

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1614]
### Description
Leases created on a media object get copied to every media object in the Avalon instance, across collections and units. Also, newly created media objects immediately have pre-existing leases.

### Steps to Reproduce
1. Add a lease to a media object. Level of user and date range doesn't matter.
2. Look at any other item in the parent collection of the object to which the lease was added. Each item now has that exact lease.

### Done Looks Like
Leases only affect a single object from the standard access control edit page.

### Original Write-up from Julie
A lease created on https://mallorn.dlib.indiana.edu/media_objects/ng451h56v with a user who is a default manager is being applied to every item on mallorn in every collection. A lease created on https://mallorn.dlib.indiana.edu/media_objects/8g84mm35j with a user who does not have access to manage any collections is also being applied to all items on mallorn in every collection.

**Comment by bkeese** [comment]
I suspect lines like this one (where read_groups was changed to default_read_groups in order to fix tests:  https://github.com/avalonmediasystem/avalon/commit/99cb9e21d40b34b8601d79dc6725d212ee922fa0): https://github.com/avalonmediasystem/avalon/blob/develop/app/models/access_control_step.rb#L46
