### ISSUE TITLE
avalon:pid should be mapped to prov:wasDerivedFrom instead of loc:local

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1616]
### Description
Right now, avalon:pid is migrating through mapped to loc:local (http://mallorn.dlib.indiana.edu:8984/fedora4/rest/9g/54/xh/70/9g54xh70s). 

### Done Looks Like
- [ ] avalon:pid should be brought over as prov:wasDerivedFrom (http://www.w3.org/ns/prov#wasDerivedFrom).

### Notes
See https://docs.google.com/spreadsheets/d/16SCIPVLcIGgYJqRG25Pgwucp0hEgmaZCkbC2etwzfpA/edit?usp=sharing for identifier mappings for Avalon in Fedora 4.

loc:local is something we want to use for Bibliographic ID when an identifier is used to import descriptive metadata.

NOTE: This description is updated from the original issue so comments below reflect discussion that resulted in this task list.

**Comment by davidschober** [comment]
@jlhardes This sounds like one we need someone on right away, correct ?

**Comment by bkeese** [comment]
My recollection was that we were going to look into a provenance ontology before doing this.

**Comment by jlhardes** [comment]
These are the notes from that meeting: https://docs.google.com/document/d/1hktRY89dr1Y3Yqo132ohY5cQX1Hq6FDM6GgTIgwwzkM/edit

At the very end there's a series of questions about what to use for bib id but earlier the F3 to F4 pids were decided to be owl:sameAs. loc:local doesn't fit for the avalon:pid from the old system. If we want something to indicate the avalon:pid is a provenance identifier, we might be able to use https://www.w3.org/TR/2013/REC-prov-o-20130430/#wasDerivedFrom from PROV-O (http://www.w3.org/ns/prov#wasDerivedFrom). Would that work for the avalon:pid?

Also, what is the other identifier number appearing in loc:local on Fedora 4? I can't resolve that to any Fedora 4 object. It's mysterious.

**Comment by davidschober** [comment]
@jlhardes is this a blocker for release?

**Comment by jlhardes** [comment]
It might not be a blocker. loc:local is not a property that is showing up on any newly-created items on spruce so it looks like it's a property that is only being used for migrated items. We should discuss but it might work to push off straightening this out for later.

**Comment by davidschober** [comment]
@jlhardes can you remind @joncameron and I. Do you see this as a blocker for release? I'm ok with attacking it next sprint.

**Comment by jlhardes** [comment]
This issue is not a blocker for 6.0 release if migration is not being included until after the release. If we can straighten out all of these identifiers in the next sprint (fixing this for migration and lining up plans for permalink, identifier@type="other", and bib import id for later work) that works for me.

**Comment by davidschober** [comment]
Thanks.

**Comment by jlhardes** [comment]
After further review of all identifiers at play in R6 and for content migration to R6, the avalon:pid will be best brought over as prov:wasDerivedFrom (http://www.w3.org/ns/prov#wasDerivedFrom). 

See https://docs.google.com/spreadsheets/d/16SCIPVLcIGgYJqRG25Pgwucp0hEgmaZCkbC2etwzfpA/edit?usp=sharing for identifier mappings for Avalon in Fedora 4.
