### ISSUE TITLE
Submit fix to ActiveFedora for Lease where query

### ISSUE THREAD

**Issue by mbklein** [avalonmediasystem/avalon#1620]
### Description
Create an upstream fix and test case for the `HasAndBelongsToManyAssociation#where` failure we encountered in `MediaObject#leases`

### Done looks like
ActiveFedora upstream accepts the pull request.

### Tasks
- [ ] write test
- [ ] submit PR
- [ ] determine if we want a patch release of AF to release this / need to backport it at all
- [ ] New story for removing our workaround?

**Comment by mbklein** [comment]
See #1614 for details

**Comment by davidschober** [comment]
@mbklein This is after release correct?

**Comment by mbklein** [comment]
Probably.

**Comment by joncameron** [comment]
@mbklein Still worth doing, or should this be abandoned?

**Comment by davidschober** [comment]
Done in another PR.
