### ISSUE TITLE
OVA Missing Directory and Batch Ingest Cronjob Not Working

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1623]
### Description
There needs to be changes in the OVA for batch ingest to work properly.

### Bug Description
- Without the 'dropbox' directory in the 'masterfiles' directory, newly created collections do not get directories for them created, and so there isn't a place for batch ingest manifests to get picked up.
- The cronjob that runs the rake task for batch ingest did not appear to be working, but the reason is as yet unknown.

### Done Looks Like
- [x] /root/avalon-docker/masterfiles/dropbox directory created
- [x] Cronjob investigated or altered so it runs correctly

**Comment by phuongdh** [comment]
Needs to add sendmail to Avalon image
