### ISSUE TITLE
Scrubber section overlay extending outside player

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#1625]
Descriptive summary
In multi-section items, the section overlay on the scrubber is extending way beyond the player. 

Expected behavior
Section overlay is proportionate to the section duration

Steps to reproduce the behavior
Login to Spruce
Go to https://spruce.dlib.indiana.edu/media_objects/2r36tx526

Observation:

![image](https://cloud.githubusercontent.com/assets/1304657/23070798/43d94278-f4fa-11e6-9b5c-c231b72c4462.png)

**Comment by bkeese** [comment]
This is caused by the structural metadata not matching the actual media (which is only 1 second long).
