### ISSUE TITLE
Leases Should Accomodate Lack of Start or End Date

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1626]
### Description 
When creating a lease, the start or end date should be allowed to be unspecified. This is a requirement for feature parity with 5.x. 

### Done Looks Like
Leases can be created with:
- a start date and an end date
- a start date but no end date
- an end date but no start date

**Comment by carrickr** [comment]
To check behavior on this, bring up a dev environment without any leases in it (run `Leases.all each do |l| l.delete end` in console to clear them out).  Then do `Leases.all` and you should have [] returned.

Go an item and create a lease without any start or end date on it and save the item.  Then check `Leases.all` in console again and it will still be [].  So Leases without start/end dates are not being saved as leases for some reason.

**Comment by carrickr** [comment]
Also it looks like our Leases model current requires an end time:

```
[45] pry(main)> l = Lease.new
=> #<Lease id: nil, begin_time: nil, end_time: nil, lease_type: nil, default_permission_ids: [], default_embargo_id: nil>
[46] pry(main)> l.begin_time = Time.now
=> 2017-02-17 10:26:00 -0500
[47] pry(main)> l.save
ArgumentError: No end_time supplied
from /Users/clr5101/avalon/app/models/lease.rb:73:in `ensure_end_time_present'
```

**Comment by bkeese** [comment]
Special permissions without dates are allowed, but not created as Leases (https://github.com/avalonmediasystem/avalon/blob/develop/app/models/access_control_step.rb#L40).

**Comment by carrickr** [comment]
virtual_read_groups and virtual_ip_grounds, but solrization of them now fails, interesting.

**Comment by bkeese** [comment]
We were just trying to accommodate both types of special permissions (the original non-time based read_users and read_groups, and the new time-based leases) in the same GUI. I don't remember why, but it's pretty clear we wanted to disallow leases without end dates.
