### ISSUE TITLE
R5 to R6 Metadata: Examine How Permalinks Are Handled in Metadata

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1627]
### Description
The storage location for permalinks is not clear. These need to be handled gracefully in 6.0 and tested to make sure everything is stored properly.

### Done Looks Like
The location of permalink information in metadata is clarified to ensure that it's going in the correct place. Testing is done afterward to make sure 6.0 creates these links properly and the metadata checks out as well.

**Comment by bkeese** [comment]
In R5, permalinks are stored in MODS as:
'''<location>
<url access="object in context">http://purl.dlib.indiana.edu/iudl/media/6537033g48</url>
</location>'''
This remains the same in R6.

**Comment by bkeese** [comment]
At IU, we'll need to fix our permalink generator initializer (it refers to ids in the R5 way), but in general permalinks seem to work in R6.
