### ISSUE TITLE
R6 View PlayList returning "NoMethodError"

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1631]
### Descriptive summary

Server: spruce.dlib.indiana.edu
Testing: Regression
Browser: Checked on both Chrome and Firefox (Issue doesn't seem to be browser related)
Issue: The View Playlist option is navigating to an error page that shows "**NoMethodError**"

### Steps to reproduce the behavior

1. Login to the system with credentials (archivist1@example.com/archivist1).
2. Navigate to the "PlayList" tab.
3. Create a playlist if there isn't one, or use the existing playlist named "Playlistin".
4. Click on the playlist name.
    (or)
    Click on "Edit" button in the playlist table, and click on the "View Playlist" button.
5. An error page will be displayed with "NoMethodError" exception.

### Related work

Link to related tickets or prior related work here.
![error_viewplaylist](https://cloud.githubusercontent.com/assets/25850972/23078086/4638d4dc-f515-11e6-9cc5-9fc3185b197a.PNG)

**Comment by Karthikeya254** [comment]
Just to note:
1. This can be seen on clicking the "see here" link that comes below the player immediately after the video is added to playlist (this shouldn't be a surprise, as this might also be trying to access the same method as above).
2. This error is not seen if the play list is empty.

**Comment by bkeese** [comment]
@carrickr You missed one mediaobject. https://github.com/avalonmediasystem/avalon/blob/dc6343e393d1adf1ffa882855d670fe9ad0b50a0/app/views/playlists/_playlist_item.html.erb#L4

**Comment by cjcolvar** [comment]
This was fixes a while ago.
