### ISSUE TITLE
Video loading failure intermittently

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1633]
### Descriptive summary

Server: spruce.dlib.indiana.edu
Testing: Regression
OS: Windows
Browser: Checked on Chrome
Issue: The video loading is failing intermittently in the chrome browser in Windows systems, it is not observed in Mac. The page need a reload in order to play the video.

### Steps to reproduce the behavior
1. Login to the spruce system
2. Click on Browse option
3. Click on "ABC3" video that comes on the top of the list and check if the video is playing
4. As it is seen intermittently this process needs to be repeated multiple times to reproduce the issue

### Related work

Link to related tickets or prior related work here.

![video not loading properly](https://cloud.githubusercontent.com/assets/25850972/23135110/48adbcda-f765-11e6-9af8-6af707b3c0b7.PNG)

**Comment by Karthikeya212** [comment]
I am observing the same issue on hemlock(R5) as well

**Comment by carrickr** [comment]
Spruce is expected, it's been a Red5 issue forever on our infrastructure.  @phuongdh is Hemlock Red5 or AMS?

**Comment by mcwhitaker** [comment]
@carrickr Hemlock is currently wowza.

**Comment by davidschober** [comment]
no longer happening.
