### ISSUE TITLE
Item sections displaying in wrong order upon load

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1640]
### Descriptive summary

In Mallorn r 5.1.5, the sections are not always being displayed in the order they were set using the Structure page. 

### Expected behavior

The Structure page is the tool the collection manager has to organize the various sections of an item. The order in which sections are organized in this page should be the order in which they are displayed when the item is loaded for playback.

### Steps to reproduce the behavior

1. Login to mallorn R5 (mallorn.dlib.indiana.edu/8981)
2. Click on "Collections" facet
3. Click on "Load Testing Collection" 
4. Click on "100 section item"
    Note that some items are labeled 1,2,3,4,5,6,7,8,9. These should be displayed in this order. They are not.
5. Click on Edit
6. Click on Structure. Note that the item sections labeled 1,2,3,4,5,6,7,8,9 are displayed in this order as the first sections of the structure.

**Comment by carrickr** [comment]
This is to a degree a known bug with regard to how items are loaded into 5.1.5.  @cjcolvar and I had to fix it on palm after Variations were loaded.  It's not so much a bug in the Avalon code as an issue related to how the various master files were loaded in and it can be solved by reordering the media objects after import.

**Comment by cjcolvar** [comment]
Actually I think this is dealing with a race condition for items with lots of sections where the ordered sections and sections (stored differently in Avalon 5) were getting out of sync.

**Comment by mcwhitaker** [comment]
@carrick I don't think that is correct. We are supposed to be able to reorder the sections in the Structure page and this is what I have been trying to do with this item, but it keeps showing items in a different order.

**Comment by joncameron** [comment]
Closing since this is a 5.x bug and is not present in the Avalon 6.
