### ISSUE TITLE
"Open in New Tab" option for a playlist item is returning "Template is missing" error

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1641]
### Descriptive summary

Server: spruce.dlib.indiana.edu
Testing: Regression
Issue: Clicking on "Open in New Tab" option for a playlist item in the playlist page is returning "Template is missing" error

### Expected behavior
It should play the media in a new tab
### Steps to reproduce the behavior

1. Login to the spruce system
2. Open any playlist available
3. The items list will be present in the right side of the page
4. Right Click on one item and click on "Open in New Tab" button 
5. It will navigate to an error page displaying "Template is missing"

### Related work

Link to related tickets or prior related work here.
![playlist in new window](https://cloud.githubusercontent.com/assets/25850972/23235987/8e21a058-f925-11e6-8a02-8c3e8e993e39.png)
![playlist item in newtab](https://cloud.githubusercontent.com/assets/25850972/23235991/930e91a2-f925-11e6-82b6-d3ebd6577430.PNG)

**Comment by cjcolvar** [comment]
For this we either need to change the url being used or make the current route (e.g. https://spruce.dlib.indiana.edu/playlists/25/refresh_info?autostart=true&position=2) redirect to a decent place when the request isn't an AJAX request.

**Comment by cjcolvar** [comment]
@avalonmediasystem/product-owners This feels like edge case to me and low priority.

**Comment by mcwhitaker** [comment]
@joncameron @davidschober 

The comment by @cjcolvar compels me to say something that I have been looking for an opportunity to say; this is not at all aimed at his comment, which just served as a reminder for me.

I recently read a comment related to user experience that compared aiming at an application that works is like being a chef that aims at food that is edible; we should aim at delight.  I agree with this, especially when our users are very familiar with applications where the user experience is a delight.

Thus, I think we can't classify all little things related to user experience as edge case and low priority. There is a big number of those little things and the accumulation of them turns them into a problem. I notice often enough a lack of interest in them that I feel compelled to say all this.

If this particular UX ticket is especially thorny to fix, then maybe we can say it is one that we will leave for later; the point I am trying to convey is that I hope we don't leave all of the UX tickets for later and deliver an application that works but that feels unfriendly.

**Comment by joncameron** [comment]
@mcwhitaker I agree that we should shoot for delight and the spirit of your comment, but in the context of current ux issues and bugs I do feel that this particular issue is low priority. It's not necessarily a lack of interest but rather a focus on things that I'd like to have handled first, such as the bugs impacting ux that have been worked on in the current sprint. 

Post 6.1 release, something that would be great is to have a themed sprint where the goal is fixing up a lot of these little things so they don't kicked down the road forever and become an unmanageable pile.
