### ISSUE TITLE
In Firefox browser Play/Pause option is not working with SPACEBAR

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1644]
### Descriptive summary

Server: spruce.dlib.indiana.edu
Testing: Regression
Browser: Firefox
Issue: The Play/pause option is not working using SPACEBAR even though the video is highlighted using keyboard. It is seen only in Firefox, and is working fine in Chrome.

### Steps to reproduce the behavior

1. Open Mozilla Firefox browser
2. Log in to the spruce system
3. Browse through and click a video file
4. Click keyboard's TAB button until the video is highlighted
5. Click on SPACEBAR, the video should play and a re-click should pause the video. The first play/pause cycle works fine and if you try it play it again using SPACEBAR it doesn't work.

### Related work

Link to related tickets or prior related work here.

**Comment by bkeese** [comment]
I am seeing the same behavior in Chrome and Firefox:
a) when the big central play/pause button is selected via keyboard, the spacebar operates as described
b) when the small play/pause button in the control bar is selected via keyboard, the spacebar works as required.

**Comment by joncameron** [comment]
I'd like to close and mark this as a known issue based on Brian's comment, especially since this only affects the custom play button overlay/wide media player scope.

Sound good @davidschober ?
