### ISSUE TITLE
Manager is unable to delete a collection

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1646]
### Descriptive summary

Server: spruce.dlib.indiana.edu
Testing: Regression
Issue: A manager level user is unable to delete a collection from the system, it is redirecting to the home page with a message stating that user is unauthorized to perform the operation.

### Steps to reproduce the behavior

1. Login to spruce system, with a Manager credentials not an Administrator
2. Go to Manage Content page, which lists the collections that this user is a part of
3. Click on Delete button for any collection
![collection delete button](https://cloud.githubusercontent.com/assets/25850972/23316044/de356670-fa96-11e6-8dce-96b4b9e3dab7.PNG)
4. The user is navigated to the home page with a message ribbon saying that the user is not authorised to perform the operation.
![unauthorized manager to delete collection](https://cloud.githubusercontent.com/assets/25850972/23316124/24f49342-fa97-11e6-9326-4be66bf3f80d.PNG)

### Related work

Link to related tickets or prior related work here.

**Comment by carrickr** [comment]
Admin can delete, so permissions difference between admin and manager seems to the cause.

**Comment by carrickr** [comment]
Manager needs can :manage, Admin::Collection but scoped to just collections they can manage
