### ISSUE TITLE
Audio icon missing in player on Chrome browser

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1647]
### Descriptive summary

Server: spruce.dlib.indiana.edu
Testing: Regression
Browser: Chrome
Issue: The audio adjustment icon is missing in the players icon list. It is observed only on Chrome browser, and is fine in Firefox and Safari

### Steps to reproduce the behavior

1. Log in to the spruce system in Chrome browser.
2. Play any audio or video file and observe the player icons.

**Mozilla**
![player icons mozilla](https://cloud.githubusercontent.com/assets/25850972/23321387/54134fcc-faad-11e6-9a2a-62c0d0e3f6ac.PNG)

**Chrome**
![player icons chrome](https://cloud.githubusercontent.com/assets/25850972/23321398/5ff453fe-faad-11e6-911b-7713da752bf3.PNG)

### Related work

Link to related tickets or prior related work here.

### Tasks
- [ ] Inspect dev tools, figure out how icon is implemented
- [ ] Check against Browserstack, alternate platforms
- [ ] Recreate issue
- [ ] Fix

**Comment by carrickr** [comment]
@Karthikeya212,  I cannot replicate.  Using Chrome 56 on OS X.  I see the audio for both audio and video on spruce currently (both logged in as archivist1 and not logged in at all).

**Comment by cjcolvar** [comment]
I'm not seeing this on Chrome 56 on OS X as well.

**Comment by Karthikeya212** [comment]
@carrickr , Could you try the chrome browser on a Windows machine. I have checked it on a Mac and is working fine, but it nor displaying audio icon on a Windows machine for the same version of the browser

**Comment by bkeese** [comment]
I'm seeing the control on Windows, Chrome  56.0.2924.87 (64-bit)

**Comment by Karthikeya212** [comment]
Observed the issue on Windows, Chrome 56.0.2924.87 (64-bit). Seems like issue is present only in some systems with the same configuration.

**Comment by Karthikeya212** [comment]
I don't know how much it is useful, but I see a "Volume" http call that is not happening in my windows machine, but the request is there on a Mac

Calls in Chrome on Mac
![audio icon chrome mac](https://cloud.githubusercontent.com/assets/25850972/23370001/392ddb10-fce1-11e6-87d6-b196a0277a8c.png)

Calls in Chrome on Windows
![audio icon chrome windows](https://cloud.githubusercontent.com/assets/25850972/23370020/4c45918e-fce1-11e6-91c8-42a7537021eb.PNG)

**Comment by mcwhitaker** [comment]
I can reproduce this in Chrome Version 56.0.2924.87 (64-bit).

**Comment by carrickr** [comment]
@mcwhitaker @Karthikeya212 

Can you see Chrome in the Windows Volume Mixer (down in the right hand task bar)?  Or get sound out of other flash video sources in the web?

**Comment by Karthikeya212** [comment]
Yes, I have Chrome in the Volume Mixer

**Comment by joncameron** [comment]
@Karthikeya212 @mcwhitaker Can you report your OS version and Flash version (and everyone else as well)?

**Comment by cjcolvar** [comment]
@mcwhitaker are you available to show me the error since I can't reproduce it?

**Comment by mcwhitaker** [comment]
@cjcolvar Yes. But you need to get me on slack because I go through the github emails only once a day.

**Comment by joncameron** [comment]
This is a timebox issue that we've pegged to 2 points.

**Comment by davidschober** [comment]
Can't seem to replicate on chrome 60. It may have been a momentary chrome bug. @joncameron to confirm and close. We are moving toward ME 4
