### ISSUE TITLE
Full Screen option not working for an embedded video

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1648]
### Descriptive summary

Server: spruce.dlib.indiana.edu
Testing: Regression
Browser: not browser specific
Issue: For a video that is embedded on a different website the full screen option is not working.

### Steps to reproduce the behavior
To check already embedded video, visit below website and check the full screen option
(or)
To reproduce the issue end-to-end,check below procedure
1. Log in to spruce system.
2. Open any video and copy the embed link from share option.
3. Go to a different website where you can embed this link or use the below website.
https://www.w3schools.com/html/tryit.asp?filename=tryhtml_intro
4. Embed the video and check the full screen option.

### Related work

Link to related tickets or prior related work here.

**Comment by cjcolvar** [comment]
This is due to the w3schools site now embedding the html output of the tool in an iframe which doesn't have 'allowfullscreen'.  We need to find a new site which allows fullscreen to test with.

It might be interesting to detect the lack of allowfullscreen and disable the fullscreen button.

**Comment by joncameron** [comment]
Closing since this is an issue with the site in which the content is embedded rather than with Avalon itself.
