### ISSUE TITLE
Develop A LDCX Proposal

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1649]
Working with DCE, we should come up with a concrete goal to accomplish during LDCX and the ensuing Developers Congress.  Such as mapping Avalon metadata to PCDM, or sticking ActiveEncode into HydraDerivatives, or perhaps developing an ActiveStreaming gem.  

Generally speaking those who have concrete deliverables and a plan to hit those deliverables get the largest mindshare during the conference, so we need to show up with a goal and plan.

**Comment by jlhardes** [comment]
I'd be up for mapping Avalon metadata to PCDM as a concrete LDCX goal. I won't be at the Dev Congress but I'll be at LDCX.

**Comment by mcwhitaker** [comment]
I think this thread on the IIIF list is pertinent to us and LDCX: https://groups.google.com/forum/#!msg/iiif-discuss/O2EjAERTF7w/-0nH0VarDQAJ

**Comment by carrickr** [comment]
We'll do Hydra Derivatives at LDCX and also look to work on Hyku.
