### ISSUE TITLE
Typeahead dropdown renders under other textfields

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1653]
Steps to reproduce
- Go to the edit page for a collection
- Type 'ar' in the managers field

Observed behavior
Typeahead dropdown renders under the editor and depositors fields.

Expected behavior
Typeahead dropdown renders on top.

Seen in Chrome 56 on Mac OS X

**Comment by cjcolvar** [comment]
I also see this on the media object access control page.  Type 'ar' in the user field and the typeahead dropdown should render over group, under external group, and over ip address.  My assumption here is that other typeahead text fields are the only ones rendering over the typeahead dropdowns.

**Comment by bkeese** [comment]
z-index for the dropdown typeahead menu is hardcoded at 100 here: https://github.com/twitter/typeahead.js/blob/588440f66559714280628a4f9799f0c4eb880a4a/src/typeahead/www.js#L89

**Comment by bkeese** [comment]
Probably can override the hardcoded z-index in avalon.cscc with 
```css
.twitter-typeahead .tt-menu { z-index: 1010 !important; }
```
