### ISSUE TITLE
R6 Notes displayed for empty table of contents

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#1667]
## Description

Seen on spruce and mallorn, for some items without any defined notes or table of contents, the item view page displays a header for Notes/CONTENTS even when no value is present.

## Done looks like

The header should not be displayed if no notes or table of content is present.

- [ ] View partial is updated to handle empty list OR different solution is found

**Comment by bkeese** [comment]
![image](https://cloud.githubusercontent.com/assets/7440154/23516371/07ae72b4-ff3b-11e6-8a58-48befd3485b5.png)

**Comment by joncameron** [comment]
Possibly impacted by performance extremism.

**Comment by davidschober** [comment]
Did this get fixed?

**Comment by jlhardes** [comment]
I think this is still happening using bib import. I just created and imported 2 records on mallorn using that same catalog key and a different catalog key that has no Contents notes and both are showing an empty CONTENTS header (catalog keys: 5442674 and 1763862).

**Comment by bkeese** [comment]
In R6, calling mediaobject.table_of_contents on a mediaobject with no table of contents returns [""], which doesn't evaluate to empty or non-present.

**Comment by cjcolvar** [comment]
I was wondering this...do any of our other fields work this way?  Seems like we might need to make some tweaks in https://github.com/avalonmediasystem/avalon/blob/master/app/models/concerns/media_object_mods.rb#L331-L337.
