### ISSUE TITLE
Write Documentation for Docker Installation

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1672]
### Description 
Installation instructions for production servers. The audience is everybody. This replaces the now deprecated Puppet install. Some notes for this can be cribbed from the macOS instructions.

### Done Looks Like
https://wiki.dlib.indiana.edu/display/VarVideo/Installing+Avalon+on+a+server+using+Docker is updated to include comprehensive instructions on installing Avalon 6.0 with Docker.

**Comment by phuongdh** [comment]
Some instructions have been updated here https://github.com/avalonmediasystem/avalon-docker/tree/red5
