### ISSUE TITLE
Hyrax Code Dive (~30 points)

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1673]
### Description
Avalon developers need to start getting familiar with the Hyrax code before work starts in earnest on release 7. All developers on the team need to dive into the code.

### Done Looks Like
- [ ] Hyrax code discussion happens in a swarm for the current sprint
- [ ] Look at Hydra derivatives and become familiar with them
- [ ] Hydra presenters, actors, service classes

**Comment by joncameron** [comment]
We could possibly reach out to Jamie Little from DCE for this swarm session as well.

**Comment by cjcolvar** [comment]
We walked through simple customizations using the touring design patters slide deck:
http://projecthydra.github.io/training/touring_design_patterns
From this I made a sample git repo that followed that slide deck and incorporated a bit from Dive into Curation Concerns:
https://github.com/projecthydra-labs/hydra-vagrant/wiki/Dive-Into-Curation-Concerns
https://github.com/avalonmediasystem/hyrax-demo
More information could probably be learned from the Sufia wiki including their page about metadata customization:
https://github.com/projecthydra/sufia/wiki/Customizing-Metadata

**Comment by cjcolvar** [comment]
We haven't looked at hydra-derivatives yet.

**Comment by cjcolvar** [comment]
Best document for QA of hyrax is linked below and suggested edits/additions are welcome:
https://docs.google.com/document/d/1WUyYdbU4rCs6ZHRmhe2_SXvHSbv1fJ2M6Un32yck3s4/edit

**Comment by cjcolvar** [comment]
Here is another doc that might inform QA scenarios: a Sufia 7.2 end user document which could be helpful but maybe a bit out of date.
https://docs.google.com/document/d/1VrlcIEyFQ4BBVKVv96Svho_YS_AIwi2BdnkKGVyDfII/edit
