### ISSUE TITLE
Variations Playlist Import Returns 404

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1674]
### Descriptive summary
A faculty member in Music provided a Variations playlist that won't import correctly. When importing the file, a 404 page is returned and the playlist is not imported into an Avalon playlist.

### Expected behavior
The standard error page for Variations playlists that have problematic items appears and alerts the user to what might be the issue.

### Actual behavior
A 404 gets thrown.

### Done Looks Like
- [x] Troubleshooting is done to determine why importing this playlist returns a 404 instead of the usual error page. 
- [ ] Variations playlist import is fixed so that it fails gracefully and lands the user on the error page for Variations imports instead of returning 404.

**Comment by bkeese** [comment]
From the server log: 
Started POST "/playlists/import_variations_playlist" for 140.182.75.88 at 2017-03-03 13:48:08 -0500
Processing by PlaylistsController#import_variations_playlist as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"+DozjVX0h/jOXBDuP0etTEpcflVMZ5CCBOpono0Uoi4=", "Filedata"=>#<ActionDispatch::Http::UploadedFile:0x00000008447890 @tempfile=#<Tempfile:/tmp/RackMultipart20170303-18379-ur56y1>, @original_filename="M432-Sp2016_Unit_2 FRENCH.v2p", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"Filedata\"; filename=\"M432-Sp2016_Unit_2 FRENCH.v2p\"\r\nContent-Type: application/octet-stream\r\n">}
VariationsPlaylistImporter: Error finding MasterFile: MasterFile could not be found for Variations label ACN0284A
VariationsPlaylistImporter: Error finding MasterFile: MasterFile could not be found for Variations label ACN0284B
VariationsPlaylistImporter: Error finding MasterFile: MasterFile could not be found for Variations label ACN0284C

**Comment by cjcolvar** [comment]
I don't see those in MCO.  Someone should check the list of problem items, but probably easiest to just hand edit the playlist to remove the offending items then reimport.

**Comment by bkeese** [comment]
Also, the import is designed to fail more gracefully, but something isn't working. Probably should fix.

**Comment by bkeese** [comment]
Here are the variations mappings for those:
IU/MediaObject/222375: ACN0284A
IU/MediaObject/222374: ACN0284B
IU/MediaObject/222373: ACN0284C

**Comment by bkeese** [comment]
The professor should probably be told that these titles were not imported into MCO:
Debussy, Beau soir
Debussy, 4 Chansons de jeunesse, Pantomime
Debussy, 4 Chansons de jeunesse, Clair de lune, 1re version
Debussy, Mandoline
Debussy, Ariettes oubliees, C'est l'extase
Debussy, Ariettes oubliees, Il pleure dans mon coeur
Debussy, Ariettes oubliees, Paysages belges-Chevaux de bois
Debussy, Fetes galantes, 1re recueil, En sourdine
Debussy, Fetes galantes, 1re recueil, Clair de lune
Debussy, Fetes galantes, 1re recueil, Fantoches
Debussy, Noel des enfants qui n'ont plus de maison
Debussy, 3 Chansons de Bilitis, La Flute de Pan
Debussy, 3 Chansons de Bilitis, La Chevelure
Debussy, 3 Chansons de Bilitis, Le Tombeau des Naiades

**Comment by mcwhitaker** [comment]
@bkeese I will see if the items should have been imported into MCO by checking if they are playable in Variations. Hold on.

**Comment by mcwhitaker** [comment]
We have determined that the item has been on the list of problems.
