### ISSUE TITLE
Performance Testing

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1680]

**Comment by cjcolvar** [comment]
are we doing another pass of the performance testing or calling it good?

**Comment by mcwhitaker** [comment]
As discussed in standup today, we will do another pass once r6 is in Mallorn.

**Comment by mcwhitaker** [comment]
[f4r6speedy-Mar-21-13_20.pdf](https://github.com/avalonmediasystem/avalon/files/859409/f4r6speedy-Mar-21-13_20.pdf)

Performance without the speedy-af gem for the same set of steps ran for 12:08 minutes. With the speedy-af gem, it ran for 2:03 minutes.
