### ISSUE TITLE
Video is freezing or continuously loading on moving the scrub/timeline bar to the end

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1684]
### Descriptive summary

Server: spruce.dlib.indiana.edu
Testing: Regression
Browser: Chrome(56.0.2924.87 (64-bit))
Operating System: Windows10
Issue: On scrolling the timeline bar or the scrubber to the end of the video, the following observations are made
(i) The video is freezing at the end and displaying the time line correctly.
![video drag to end](https://cloud.githubusercontent.com/assets/25850972/23564348/1af016b0-0018-11e7-8767-e218bc49dd68.PNG)

(ii) The video is freezing at the end and displaying the wrong time in the video (some random large number).
![player scrbber drag issue](https://cloud.githubusercontent.com/assets/25850972/23564361/28ecc790-0018-11e7-86b1-b6d619a8d3b6.PNG)

(iii) A scroll back from that point is making the video going to continuous loading.
![video drag back from end](https://cloud.githubusercontent.com/assets/25850972/23564335/0dc66b4c-0018-11e7-99ba-0cfc5b1a4320.PNG)

### Steps to reproduce the behavior

1. Login to the spruce system
2. Open a video and drag the timeline bar to the end of the video, or just click at the end of the timeline bar.
3. For videos that are greater than 2min long, the timeline bar doesn't let you click smoothly at the end, so use the scrubber in this case.
4. After the video is stuck, drag the timeline bar back to check the video going into continuous loading.

### Related work

Link to related tickets or prior related work here.

**Comment by davidschober** [comment]
can't recreate

**Comment by cjcolvar** [comment]
@joncameron @davidschober Can we remove this from the Known Issues?

**Comment by joncameron** [comment]
Can't reproduce, willing remove from Known Issues.
