### ISSUE TITLE
Items not clearing from Playlist & Selected Items after the end of lease date

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1688]
### Descriptive summary

Server: spruce.dlib.indiana.edu
Testing: Regression
Browser: Chrome(56.0.2924.87 (64-bit))
Operating System: Windows10
Issue: After the end of the lease date of access for a user, the items are not getting removed from the selected items list and also from playlist.

### Steps to reproduce the behavior

1. Login to spruce system with at least manager level user.
2. Create a new item and set special access to an Avalon user who is not a member of this collection.
![lease list](https://cloud.githubusercontent.com/assets/25850972/23621912/8b10e57e-026a-11e7-8111-6bb8ca5d897d.PNG)

3. Login to spruce using the Avalon user details.
4. Search for the item that he has special access(lease) to.
5. Select the item and keep it like that (selection may include other items as well).
![secadm_selected_items](https://cloud.githubusercontent.com/assets/25850972/23621947/addf1efe-026a-11e7-8ec5-fae98978eced.PNG)

6. Click on manage Selected Items option an add the selected item to the playlist (playlist may include other items as well).
![secadm_playlist_view](https://cloud.githubusercontent.com/assets/25850972/23621954/b3379020-026a-11e7-8457-548173bff320.PNG)

7. Wait for the lease to be completed (based on the end date you provide).
8. After the lease is over, check the selected items list. The count still shows same(it is not updated), but the item is not present in the list.
![secadm_selected_items_after_lease](https://cloud.githubusercontent.com/assets/25850972/23622040/0b185b6c-026b-11e7-9c8c-173e201951b7.PNG)

9. Go to the playlists page, and click on the playlist that we have earlier added the item to. It will navigate to an error page.
![secadm_playlist_after_lease](https://cloud.githubusercontent.com/assets/25850972/23621882/68d698aa-026a-11e7-874b-98fa635b0fc1.PNG)

### Related work

Link to related tickets or prior related work here.

**Comment by joncameron** [comment]
Errors in the playlist page are the higher priority. We may not need to worry about the selected items one just yet.

**Comment by bkeese** [comment]
Playlist page should be fixed now. Needs QA on spruce when deployed.

**Comment by joncameron** [comment]
@Karthikeya212 As per Brian's comment, can you verify and move this issue to done afterward?

**Comment by Karthikeya212** [comment]
Playlist works fine, creating a new issue just for selected items
