### ISSUE TITLE
Video end time is reported as NaN on mobile device

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1689]
### Descriptive summary

Server: spruce.dlib.indiana.edu
Testing: Regression
Browser: Chrome(55.0.2883.91)
Device: Nexus 5
Operating System: Android 6.0.1
Issue: The video end time is displayed as NaN when we launch Avalon in the mobile device. Though it is displaying the correct time once we start playing the video.

### Steps to reproduce the behavior

1. Launch spruce system on a mobile device.
2. Browse the list and click on the video, check the end time of the video before playing it.
![endtime nan in mobile chrome](https://cloud.githubusercontent.com/assets/25850972/23623820/6ef2ae84-0271-11e7-9db3-03c21b42cd52.png)

### Related work

Link to related tickets or prior related work here.

**Comment by joncameron** [comment]
Stale and low priority bug. Reported under known issues. It looks like the current behavior has changed and the player reports 0:00 until the stream has loaded.
