### ISSUE TITLE
Video Captions not working on R6

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1691]
### Descriptive summary

Server: spruce.dlib.indiana.edu
Testing: Regression
Browser: Chrome(56.0.2924.87 (64-bit))
Operating System: Windows10
Issue: Captions are displaying while playing the video

### Steps to reproduce the behavior

1. Login to spruce system.
2. Create a new item and add the captions file while creating the item (or) can use item "A_LunchRoom" that I have created on spruce and also contains the captions file.
3. Play the video, and switch on the "cc" icon in the player.

### Related work

Link to related tickets or prior related work here.

**Comment by joncameron** [comment]
It was noted that the extreme-performance branch might fix this once it's merged into develop. Might be the first thing to test.
