### ISSUE TITLE
NU Standup Clean AWS Hyku/Hyrax

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1693]
## Done

NU has a clean AWS Hyku Dev environment in AWS in preparation of work with DCE.

This instance will be used to do production-level testing.

**Comment by joncameron** [comment]
@davidschober will ask Michael about the security feasibility of granting access to this environment for IU devs.

**Comment by mcwhitaker** [comment]
@joncameron   We don't need dev access to this. We will need one instance of hyku/hyrax to play with, and we are able to standup one on our end for the whole team, so if NU has a different purpose for the box on this ticket, it is not a problem at all. 

I only asked for more details about this task during our meeting to understand what the task was about. It sounds like it is more of a NU-specific task.

**Comment by davidschober** [comment]
I think we have same purpose. This one is a clean install for development on Avarax.
