### ISSUE TITLE
Parallelize the Extreme Performance ReIndex Task

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1695]
### Descriptive summary

It, like everything else that touches Fedora is slow.  This is a bit of a problem when updating large 
Avalon repos and needing to reindex all the data.  

Also ensure reindex everything calls this task.

### Done Looks Like

- [ ] Less Slow
- [ ] `reindex_everything` calls this task

**Comment by carrickr** [comment]
https://github.com/avalonmediasystem/avalon/blob/ddfe1331dec7db266290165dd2135856dcc5edae/lib/tasks/avalon.rake#L133-L145

index_for_speed is the task

**Comment by joncameron** [comment]
@cjcolvar also mentioned that reindexing would be good to revisit in general. This particular ticket may not be necessary.

**Comment by joncameron** [comment]
I'll bring this up in backlog buddies—it may be best to close this and create a new ticket for looking at reindexing in general as per my comment above.

**Comment by davidschober** [comment]
abandoning considering work on 7.
