### ISSUE TITLE
Items not clearing from the Selected Items list after the end of lease date

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1701]
### Descriptive summary

Server: spruce.dlib.indiana.edu
Testing: Regression
Browser: Chrome(56.0.2924.87 (64-bit))
Operating System: Windows10
Issue: After the end of the lease date of access for a user, the items are not getting removed from the selected items list.

### Steps to reproduce the behavior

1. Login to spruce system with at least manager level user.
2. Create a new item and set special access to an Avalon user who is not a member of this collection.
3. Login to spruce using the Avalon user details.
4. Search for the item that he has special access(lease) to.
5. Select the item and keep it like that (selection may include other items as well).
6. Wait for the lease to be completed (based on the end date you provide).
7. After the lease is over, check the selected items list. The count still shows same(it is not updated), but the item is not present in the list.

### Related work

Link to related tickets or prior related work here.

**Comment by Karthikeya212** [comment]
Linked to issue #1688

**Comment by lealeelu** [comment]
Looking at the problem, it looks like it would be best to make a rake task and add that task to a daily scheduled job in config/schedule.rb. The rake task would search for outdated bookmarks and then use a new class that would delete the bookmark. mo.remove_bookmark is on the MO and might not be best.

**Comment by davidschober** [comment]
edge case.
