### ISSUE TITLE
Developers get fully working R6 dev environment using Docker

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1704]
### As a Developer
I want an easy to install/update and robust, full-featured development environment. 

### So That
I can easily and confidently test code changes locally (especially player and streaming changes).

### Done looks like
All developers get fully working (including transcoding and streaming) development environments setup using Docker.

### Related Issues
#1761: Linux Instructions
#1751: Windows Instructions

**Comment by mcwhitaker** [comment]
@cjcolvar this is for r6, correct? We have a similar ticket for hyrax/r7 work #1714 .

**Comment by cjcolvar** [comment]
Yes, this is for R6 for continuing 6.x work.

**Comment by carrickr** [comment]
https://github.com/avalonmediasystem/avalon/wiki/Configuring-an-OS-X-Development-Environment-With-Docker-Containers

For OS X.

**Comment by lealeelu** [comment]
As part of the "All developers" goal, I've started a windows dev environment guide.
https://github.com/avalonmediasystem/avalon/wiki/Configuring-a-Windows-Development-Environment-with-Docker
Since the rest of us are using windows with linux vm's.

**Comment by mcwhitaker** [comment]
@lealeelu I suppose what you are doing is then related to ticket #1751 ?

**Comment by lealeelu** [comment]
@mcwhitaker Yup, looks like it.
I know this is probably a silly approach, but I want to see if it works.

**Comment by davidschober** [comment]
closing. This is done
