### ISSUE TITLE
investigate LDAP/ Authentication on AWS

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1722]
figure out how to move authentication configuration to the environment.

https://aws.amazon.com/blogs/aws/aws-identity-and-access-management-now-with-identity-federation/

**Comment by joncameron** [comment]
This could be complicated if we use this. Investigation into just using Shibboleth has been suggested as being easier.

**Comment by joncameron** [comment]
This is being closed and we will kick off further tickets as needed, especially if there's a need to actually implement some sort of ldap. Work for authorization will be represented on a separate ticket.

**Comment by davidschober** [comment]
We did the investigation. This can be used, but firewalls will depend up local environments. NU is digging into openID. The team will look into Shibboleth for SAAS pilot.
