### ISSUE TITLE
Document CloudFormation script for custom Avalon version support

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#1725]
## Description

As institutions (and vendors) begin to host Avalon instances in AWS, the cloud formation scripts should easily be able to support customized Avalon installs.  A devops person should be able to pin a cloud formation script to a specific repo easily.

## Done looks like

- [x] a user should be able to configure a cloud formation script to point to specific versions/repos for custom installs (previously done)
- [ ] how customization occurs is well-documented.

**Comment by davidschober** [comment]
@mbklein @phuongdh mentioned you had some ideas about this. I'm working on cleaning up the issues to be more verbose. Does the above capture?

**Comment by davidschober** [comment]
@phuongdh is this made redundant by #1489?

**Comment by phuongdh** [comment]
@davidschober this may be beyond the scope of #1489

**Comment by joncameron** [comment]
This ticket is old and we have enough documentation to suit out purposes for now to close it.
