### ISSUE TITLE
Support lyrasis preferred authentication methods

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#1726]
### Description

As we move toward a SAAS pilot, we will need to discuss with lyrasis what their preferred authentication method would be for a multi-tenant solution. Avalon should support the system that lyrasis is using, but lyrasis will have to configure.

### Done looks like 

- [ ] ask Lyrasis what they want to use
- [ ] Provide documentation if necessary

**Comment by joncameron** [comment]
We will probably need to work on Shibboleth, both for authentication and authorization. Checking external group membership at time of login.

**Comment by joncameron** [comment]
Where's the line drawn between Avalon AWS and Avalon SaaS? Is this something not necessary for AWS, but rather is something configured for an instance of Avalon running in a SaaS environment? It's unclear at the moment to me.

**Comment by davidschober** [comment]
@phuongdh or @mbklein can you rewrite the describe this a little more clearly. Is the goal to have shibboleth work with AWS?

**Comment by mcwhitaker** [comment]
During our meeting with Lyrasis on 6/1 we agreed to implement shibboleth support in the AWS install of Avalon. Lyrasis was going to find a pilot institution willing to help us by serving as our test case for validation of our work.

**Comment by davidschober** [comment]
we decided the basic login would be OK for our work.
