### ISSUE TITLE
User with lease to hidden item can discover it in search results

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1729]
## Steps to reproduce:

Create a hidden item with lease to the end user.  In incognito, login as the end user and click browse to see the item.

## Expected behavior:

Any non-collection member should not be able to discover hidden items.

This bug is also present in R5.

#1758 documents this as a known issue.

**Comment by davidschober** [comment]
This will be tinkering with SOLR discovery. It's pretty complex. It's an edge case, so we will make it lower priority.

**Comment by davidschober** [comment]
We are abandoning. We can't come up with a real world scenario.
