### ISSUE TITLE
Cannot reach player using TAB from keyboard in Chrome

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1733]
### Descriptive summary

Server: spruce.dlib.indiana.edu
Testing: Regression
Browser: Chrome(56.0.2924.87 (64-bit))
Flash version: 24.0.0.221
Operating System: Windows10
Issue: Cannot reach player control using the TAB option in keyboard. The control is stopped at the last element before the player ("Delete" button if the user is from collection staff ; "Search" box if it is normal avalon user). This issue is not seen in Firefox.

### Steps to reproduce the behavior

1. Login to spruce in Chrome browser
2. Open a video
3. Use TAB key to navigate to the player

### Related work

Link to related tickets or prior related work here.

**Comment by joncameron** [comment]
I could not reproduce this in Chrome 56 on macOS 10.11, but could reproduce it on Chrome 56 in Windows 10, Flash 24.0.0.221.

**Comment by phuongdh** [comment]
Not signed in, tabbing does take me to the controls. Signed in, I'm stuck at the Delete button. Now if I remove this button in Chrome inspector, then I can tab into the player!

**Comment by bkeese** [comment]
Our handing of this is pretty brittle.. It's here: https://github.com/avalonmediasystem/avalon/blob/develop/app/assets/javascripts/keyboard_access.js

**Comment by Karthikeya212** [comment]
Tested on Spruce with different user types. It looks good.
