### ISSUE TITLE
Allow user to update the thumbnail of an item using screenshot from any section of the item

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1738]
### Descriptive summary
The user should be able to update the thumbnail of an Item, by taking the screen capture from any of the sections that are present in that item.

### Actual behavior
At present user can update the thumbnail using the screen capture only from the top most section

**Comment by davidschober** [comment]
@Karthikeya212 is this occurring on both 6.x and  5.x?

**Comment by Karthikeya212** [comment]
Yes, it is is present on both versions.

**Comment by joncameron** [comment]
This is a wontfix for Avalon 6.x. We could look at this again when implementing this feature in Avalon 7.
