### ISSUE TITLE
Fix Failing Playlist Tests

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1752]
Faker issues probably

**Comment by bkeese** [comment]
The error condition was changed, so the text of the error message was changed to "This playlist currently has no playable items".

**Comment by cjcolvar** [comment]
Shoot, sorry about that.  I thought that wasn't actually getting testing.

**Comment by carrickr** [comment]
Should I flip this over to you?

**Comment by cjcolvar** [comment]
Sure, thanks!
