### ISSUE TITLE
Write issues for hydra-derivatives Avalon

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1757]
- [x] write and review issues for hydra-derivatives work
- [x] write up notes from ldcx/ showcase work
- [x] review notes from #1673

**Comment by davidschober** [comment]
when @cjcolvar gets back @val99erie and POs will verify that we're done with this, and break out any final issues.

**Comment by cjcolvar** [comment]
Added stories #1827, #1826, #1829.
