### ISSUE TITLE
Cannot re-order playlist items in Chrome with latest flash

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1768]
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Regression
Browser: Chrome(56.0.2924.87 (64-bit))
Flash version: 24.0.0.221
Operating System: Windows10
Issue: Cannot re-order play list items in the above mentioned chrome browser and flash versions. It is working fine on chrome with older flash versions

### Steps to reproduce the behavior
1. Login to spruce in Chrome browser.
2. Edit a playlist
3. Try to re-order the items

### Related work

Link to related tickets or prior related work here.

**Comment by lealeelu** [comment]
Server: spruce
Browser: Chrome 58.0.3029.110
Flash: n/a No flash is needed on the edit playlist page
OS: Windows 10

I wasn't able to reproduce this issue.

**Comment by cjcolvar** [comment]
@avalonmediasystem/product-owners can we close this?  I wasn't able to reproduce it now that we made fixes to it.

**Comment by Karthikeya212** [comment]
This problem still exists in my system. I am using the following versions
Chrome: 59.0.3071.86 (Official Build) (64-bit)
Flash: PPAPI 25.0.0.171

I still can't figure out why this doesn't work, I can't say that flash is not working, as I am able to play the videos without any complaint from Avalon.

**Comment by bkeese** [comment]
Maybe a hard refresh (Ctrl-F5) to force a reload of the javascript/css will fix it for you?

**Comment by Karthikeya212** [comment]
Tried it, still not working. Tried it in the incognito as well without any success.
