### ISSUE TITLE
Uploading a file that isn't an audio or video file throws error

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1769]
### Steps to reproduce
- Go to manage files page of an item.
- Select a text file and click upload.
- You will see an error.

### Expected behavior/Done Looks Like
The user will stay on the manage files page and a flash message will appear saying the file was not an audio and video file.
### Tasks
- [ ] Isolate and fix

**Comment by Karthikeya212** [comment]
Is the same expected behavior applies to Structure and Caption file uploads ? When I checked earlier they are also throwing errors like manage files
