### ISSUE TITLE
Update puppet scripts to point to 5.x-stable branch instead of master

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1770]
If someone tries using the puppet scripts to install Avalon it will probably fail now because it will pull 6.0 from master.  The puppet scripts were written for avalon 5.x and abandoned for 6.0.  If we update the puppet scripts to pull from 5.x-stable then there is still a path to install avalon 5.x and it isn't broken.
- [x] Fix script
- [x] Email Christian and list
- [x] Mention in README about puppet abandoned for Avalon 6.

**Comment by joncameron** [comment]
@phuongdh From mailing list traffic this seems to be completed. Can you confirm and move to In Progress or Done?
