### ISSUE TITLE
Define minimal metadata for Avalon style videos

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1772]
Looking at the manifest used in #1774 and determining from there what needs to be done metadata-wise. We can use a static manifest as something to look at too.

## Done looks like

- [x] Verify if out of box metadata is enough for baseline IIIF-AV endpoint 
- [x] Find any differences and note
- [x] investigate sufia 7.3 works type (deemed unnecessary)
- [x] Define first pass of metadata for avalon-style content type used for IIIF-AV endpoint

**Comment by davidschober** [comment]
If it it can play a video and have some structure. 

@jlhardes noted it will be easier to look at a static manifest. @bkeese or @mcwhitaker  can you send over examples?

**Comment by jlhardes** [comment]
We'll want to review the manifest produced for #1774 to do this work.

**Comment by mcwhitaker** [comment]
The draft examples from IIIF-av are here: https://github.com/IIIF/iiif-av/tree/master/source/api/av/examples

The IU example that has been worked on by the IIIF-AV work group is this: http://www.avalonmediasystem.org/downloads/iiif/lunchroom_manners/lunchroom_manners.json

**Comment by davidschober** [comment]
Thanks!

**Comment by little9** [comment]
After creating a basic implementation, I've noticed some things about the IIIF-AV manifest that I think
it would helpful for us to be specific about. 

For example, the `content` element in IIIF-AV is an array, which could have multiple sub-elements. In the lunchroom manners it has one sub-element, with the `AnnotationPage` type. It would be super helpful to know that Avalon will only generate one sub-element in content. 

Inside `content` there is `items` , which has a `body`, which also has `items`. It would be great to know if there will always be three items at that level. In the example that's the "Low","Medium", and "High" videos.

If we know that the elements will only be nested once it will be much easier to write code.

**Comment by bkeese** [comment]
I think we'll eventually be able to constrain these sorts of things. But at this point we can't be certain what the structure will ultimately be. About the qualities, I think we can safely say there will be AT MOST 3 qualities. Audio items only have 2 by default.

**Comment by jenyoung** [comment]
For `AnnotationPage` while Avalon doesn't have functionality to play multiple items simultaneously at this time, there is a use case for playing a video and an audio at the same time. We don't want to limit ourselves.

Default items: 
For the item array under `content`, we don't want to limit ourselves at the moment. An use case is playing audio and video at the same time.
For the item array under `body`, video will have 3 items (Low, Medium, High), audio will have two (High and Medium).  

Descriptive metadata minimum required:
Title = `label`
Date =`metadata` with a key value pair for date

Anything else also is mapped to `metadata` with key value pairs
Abstract is mapped to `description` - may be duplicative of `metadata`

**Comment by jlhardes** [comment]
See https://gist.github.com/jlhardes/1e3adada7410591f46b170e65dce20af for example and comments for descriptive metadata recommendation.

**Comment by jlhardes** [comment]
The checklist item for investigating sufia 7.3 works type doesn't seem to be helpful here to figure out what we need in the manifest file for an avalon-style video. Let us know if we're not understanding something that we still need to define.

**Comment by cjcolvar** [comment]
Looks good to me. :+1:
