### ISSUE TITLE
Derivatives are created when an avalon-style content type is ingested

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1776]
## Done looks like
When I ingest an avalon-ish video (TBD) appropriate derivatives to drive IIIF-AV endpoints are created.

This will be informed by technical issues created in #1757 

- [ ] Derivatives are created using hydra derivatives

**Comment by cjcolvar** [comment]
@davidschober Can we close this in favor of the stories written by #1757?

**Comment by davidschober** [comment]
Yup
