### ISSUE TITLE
Write List of Avalon Features

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1778]
### Description
Avalon release notes include detailed information and features for each release, but there is no comprehensive list of all Avalon features that potential adopters can look at to get an overview of all that the application provides.

### Done Looks Like
A feature list is written up that includes all Avalon-provided features. This could be a bulleted list, and would be something appropriate for declaring that Avalon 6.0 has full feature parity, and for publishing on the website or other document for interested parties.

### Tasks
- [ ] take the delta/feature spreadsheet and work from there to determine features
- [ ] Document in wiki or other document

**Comment by carrickr** [comment]
@joncameron @davidschober This needs tasking by the POs

**Comment by lealeelu** [comment]
@joncameron @davidschober Is this tasked enough for you two and is 2 points good?

**Comment by joncameron** [comment]
Thanks @lealeelu. David and I will talk to finish the task list and done criteria before we mark it fully tasked. In the future you can skip over anything assigned to me and @davidschober as we'll take care of writing and tasking it.
