### ISSUE TITLE
Control Access: editors end up as managers

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1779]
### As a 
Collection Manager

### I want
to be able to add an editor to my collection.

### So that 
I can get help with editor-level tasks.

### Current bug:
In 5.x and 6.x, when you add an editor, the name ends up showing as a manager.

### Steps to reproduce:
1. Login to Spruce as archivist1@example.com
2. Click on Manage Content
3. Click on collection Yonder Blue Mountain Ensemble
4. Add a new editor
5. See that the editor name ends up as a manager.

### Done Looks Like
Following the steps above adds the name to the list of editors.

**Comment by cjcolvar** [comment]
If the user is in the managers group, they will always show up as a manager when added to a collection as an editor.  This is baked in and may be difficult to change.  Users not in the managers group should be able to be added as an editor as expected.

**Comment by mcwhitaker** [comment]
Validated Chris's comment. Closing.
