### ISSUE TITLE
CloudSearch Solr in AWS

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1781]
### Description
Using AWS CloudSearch instead of spinning up our own Solr instance. Given the way we use Zookeeper now, and the way rsolr works, it's just not interface compatible with CloudSearch Solr and making it happen would be a huge undertaking.

### Done Looks Like 
Avalon in AWS uses CloudSearch Solr instead of our own Solr.

**Comment by davidschober** [comment]
stale and ambitious
