### ISSUE TITLE
Investigate flip/flop plugin architecture

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1783]
## Done looks like 

- [ ] developers dig into the proposed arch as needed. 
- [ ] notes are take on the flip flop architecture proposed in hyrax <https://github.com/voormedia/flipflop>

**Comment by val99erie** [comment]
## How the Flipflop gem is used in Hyrax

Hyrax uses flipflop to configure a set of features that can be easily enabled/disabled by flipping a single boolean value.

An example of one the flipflop-controlled features in hyrax is `:transfer_works`.  This features allows a user to transfer ownership of a work to another user.

Within hyrax, the ability to transfer works is granted to certain users via cancan-style abilities in the `ability.rb` file.  If the `:transfer_works` feature is enabled in flipflop, then some users will be granted the ability, but if the feature is disabled, then no users will be granted the ability.

In the Rails views, the cancan abilities are checked to determine if the user has the ability to transfer a work.  If yes, then the UI controls for transferring a work are displayed on the page.  So of course, if the feature is disabled in flipflop, the cancan query will always return false for every user, and that part of the UI will never be displayed.

In the case of the `:transfer_works` works feature, all the code for transfering a work already exists in hyrax, and the feature can truly be enabled/disabled with just one boolean.  This is true for all the features that are currently configured with flipflop in hyrax.

This is an important note for development of plugins that are intended to be used with hyrax:  If the goal is to control the feature with flipflop, then the code needs to be written in a way that the feature/behavior can easily be turned off with just one boolean.

**Comment by val99erie** [comment]
The important part of that comment is that there is just one boolean in just one part of the code that controls the entire feature.

**Comment by cjcolvar** [comment]
I agree that is important and will probably be the trickiest part for some of our plugins: keeping the places in the hyrax that know about our flip flop feature to a small number if not one point.

**Comment by val99erie** [comment]
Yeah, that's why I thought that writing the transfer_works feature basically as a cancan ability is an interesting approach -- because cancan already works on the concept of a single boolean.  Can this user do X?  And then the rest of the code just queries cancan to see if it should expose certain behavior.  It's a natural analog, since cancan and flipflop both have the concept of a boolean query to control the behavior.
