### ISSUE TITLE
Chrome Flash audio embeded player doesn't load flash automatically

### ISSUE THREAD

**Issue by lealeelu** [avalonmediasystem/avalon#1798]
Embeded audio that requires flash won't load automatically because Chrome blocks the plugin. It doesn't happen to embeded video.

Might be related to #1647, or maybe both can be fixed.

**Comment by lealeelu** [comment]
This wasn't really done. Found a bug. This should fix it though:  
https://github.com/avalonmediasystem/mediaelement_rails/commits/opacity-fix

I expanded the size of the swf player to 20x20px but it started showing up in the embed player. So I changed the opacity to 0, which fools google at least for now.

**Comment by lealeelu** [comment]
I'm going to have to pass on this one for a little while. 

Karthik did some testing and found that he couldn't get the embeded player to play. I looked further into it and found that chrome may be defaulting some components to html5 because of the option in chrome://flags called "Prefer HTML5 over flash". When I disable this option, the embed player works perfectly (I'm assuming because it's using all flash) when I set the option to default or disabled, it doesn't play. When you hit the play button, it switches to show the pause button, but no progress is shown, the bar isn't shown and no audio.

**Comment by mcwhitaker** [comment]
@lealeelu  "when I set the option to default or disabled, it doesn't play" - did you mean "default or enabled"? If so, and when the flag is set to disabled you can play, read on.

I think we can instruct users that they need certain settings for avalon content to play. So if we need to tell the users that they need to disable that flag (and the flag remains disabled across browser sessions), I am fine with that. 

The problem in production today is that there are no settings that make it work without user intervention each time they want to play embedded avalon content. Your solution seems to work with certain chrome settings, so to me that is good enough!

**Comment by lealeelu** [comment]
ya, I meant enabled. The problem with just disabling that is the flags area is a no-go zone for users. If you go to it, you'll see what I mean. Any wrong step and they can seriously mess up chrome beyond repair. It's really only for developers and advanced users. :(
