### ISSUE TITLE
Create Test Environments for Avalon 7 Work

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1800]
### Description
We need environments to deploy our test builds of Avalon stuff in Hyku.

### Done Looks Like
A VM is provisioned to create a development and staging environment for active work.

### Tasks
- [x] The VM (flourine) is setup and has Docker installed.
- [ ] Bamboo builds and deploy Avalon containers to flourine.

**Comment by phuongdh** [comment]
We'll need an Avalon 7 app before we can deploy it to the new server

**Comment by phuongdh** [comment]
The plan
![image](https://cloud.githubusercontent.com/assets/1304657/26370074/b3b0d97a-3fc4-11e7-9370-303917ca9e3c.png)
