### ISSUE TITLE
Move Sample Media Files to Location Accessible by IIIF/AV Board

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1801]
### Description
We have permission from the IU Libraries Moving Image Archives to share some of their media with the IIIF/AV community as sample files. The IIIF/AV community also needs a sample video that indicates time for synchronization purposes; Maria will pull a video of this type from Youtube or elsewhere. 

### Done Looks Like
These sample videos are put into a directory that is accessible to the IIIF/AV community.

**Comment by mcwhitaker** [comment]
All files are listed in the IIIF-AV document for the purpose: 
https://docs.google.com/document/d/1gInWfSIepIzerulJ4be75o7dyXvaS_B_WYuI5kg76R4/edit
