### ISSUE TITLE
rewrite hydra derivatives to work with actioncable

### ISSUE THREAD

**Issue by csyversen** [avalonmediasystem/avalon#1803]
it would be awesome to eventually write up hydra_derivatives to support rails 5's actioncable and do away with polling all together. This seems like a great use case for it.

**Comment by davidschober** [comment]
@csyversen you want this in the next sprint correct?

**Comment by davidschober** [comment]
This would allow us to get rid of polling . Per Chris S. It's cool, but not necessary.

**Comment by cjcolvar** [comment]
As far as I understand actioncable it is meant for only browser javascript <-> rails server interactions so doesn't really apply to these ruby code (on server) <-> transcoding server interactions.  We could try using concurrent-ruby (which actioncable uses) instead.  This might   look like using the TimerTask and an observer to handle the waiting for active-encode to finish with an optional timeout in a way that hydra-derivatives expects: http://ruby-concurrency.github.io/concurrent-ruby/Concurrent/TimerTask.html (look for the Observation example)

**Comment by csyversen** [comment]
yeah you're correct about actioncable. I was thinking that when the browser is displaying the status of an encoding job to a user that we could use actioncable there instead of polling (which is how it works now, i think)

**Comment by cjcolvar** [comment]
Got it.  That totally makes sense. :+1:

**Comment by cjcolvar** [comment]
@csyversen Maybe it would make sense to close this one and create a new one for any improvements to displaying the status of the encoding job within hyrax if any are needed.

**Comment by csyversen** [comment]
@cjcolvar yeah that's a good idea. Closing this!
