### ISSUE TITLE
Implement hyrax-style batch ingestion for Avalon work content

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1804]
## Description 

As we move Avalon into Hyrax we will have develop an analogous approach to batch ingestion of Avalon work types into a Hyrax- based application. The goal is to have something that works similar to current Avalon batch ingest via spreadsheet with a work and associated metadata created per line. 

## Community stuff

I believe  ?Ohio State? and possibly the AIC has done some work on spreadsheet-based ingestion into hyrax/Sufia. It might be a good time to reach out. 

## Done looks like 

- [ ] Develop Spreadsheet with RDF Properties 
- [ ] Using a spreadsheet an end user can ingest Avalon work types into Hyrax
- [ ] The spreadsheet is similar to the batch ingestion template currently used

**Comment by davidschober** [comment]
The hyku feature list shows bulk ingest via spreadsheet https://docs.google.com/spreadsheets/d/1Cd2FCYa_7O5ngQjvAdVa6S0kyk2M8SYjEj4abpjpCsY/edit#gid=0

We need to see if we can rip this functionality out of hyku and customize.

**Comment by cjcolvar** [comment]
Look into https://github.com/curationexperts/darlingtonia

**Comment by davidschober** [comment]
Note, NU has a working version of this. We should consider this low hanging fruit and add it as a MVP. @carrickr

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#106
