### ISSUE TITLE
Rough concepts/designs for Avalon in Hyrax completed

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1805]
## Description
As we move Avalon into Hyrax we will need to deal with several design issues particularly from the end user side. From an ingestion / workflow side we should attempt to stick to hyrax patterns as much as possible. From a front-end our goal is to show video, audio, current metadata  and a player similar to our current player. One complexity is the "markers and and playlists" as this is outside of the current scope of hyrax so it will all be custom. 

## Done looks like
- UX and designers from IU ux discuss Hyrax design patterns/ Compare to Avalon 6.x patterns
- Wireframes developed for Homepage/ Search Page/ Item-level Page
- Discussion about what a "skinned" Avalon powered by Hyrax might look like
- Issues written for customizations

**Comment by davidschober** [comment]
Note, this can/should be broken out necessary.

**Comment by davidschober** [comment]
@adamjarling and @joncameron does this look right sized? I'm thinking of sketches for a vanilla "Avalon in Hyrax". Hopefully we can work with Matt Fitzwater?

**Comment by adamjarling** [comment]
@davidschober @joncameron  Should this be tasked, or create tasks which reference this. EPIC issue?

A good starting point may be to generate wireframes for the 3 pages listed in Done Looks Like above (Home/Search/Item-Level), and then see how those pages are constructed in default Hyrax and I could try to give some insight on how customizable they are, whether they're straight Hyrax, or Blacklight, or where the UI seems to be coming from.

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#94
