### ISSUE TITLE
create UI for clips in IIIF-AV driven player

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1807]
## Description

As we move toward a complete Avalon in hyrax solution we will want to have clips within a hyrax context. Note this is dependent upon a plan for recreating the "playlist" functionality in hyrax possibly leveraging user collections? 

This is informed by work in #1811. 

## Done looks like

- A user can clip an arbitrary section of a song or movie within hyrax (This will likely need more work)
- a user can label the section of song or movie
- Kick off new issues as necessary (for bugs and backend work)

![screen shot 2017-04-05 at 3 51 49 pm](https://cloud.githubusercontent.com/assets/4803230/24726391/d3d17cc8-1a17-11e7-9339-49eafc59234d.png)

## Note

This is time boxed. We will evaluate at will.

**Comment by adamjarling** [comment]
Before I task this, I'll need to spend some time with someone to understand:
- How it currently works.
- What would be different about the functionality in a Hyrax context.
- How the front end processes a 'clip'
- Is the backend in Hyrax set up to receive the clip information?

**Comment by joncameron** [comment]
It would be great if playlists are done through IIIF and use generic tooling.
