### ISSUE TITLE
IIIF-AV: Decide when to generate manifest

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#1816]
Options include but are not limited to:
* upon request
* upon update
* upon publish

Things to consider are:
* eventually manifest might be required by player
* player needs to be functional before publish
* generation of manifest might be non-trivial
* might be different answers for metadata vs structure

**Comment by davidschober** [comment]
Note from #1775  We should use the existing pattern if possible.

Hyku's IIIF endpoint is here:
https://github.com/projecthydra-labs/hyku/blob/master/app/controllers/concerns/hyku/iiif_manifest.rb
which uses iiif-manifest to actually construct the manifest:
https://github.com/projecthydra-labs/iiif_manifest/
starting here in ManifestFactory:
https://github.com/projecthydra-labs/iiif_manifest/blob/master/lib/iiif_manifest/manifest_factory.rb

**Comment by davidschober** [comment]
This may be redundant

**Comment by davidschober** [comment]
abandoned.
