### ISSUE TITLE
IIIF-AV: Map structural and technical metadata to manifest

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#1817]
Refers to metadata story: #1772 #1808
this relates to #1775 (iiif endpoint)

* This can be static. It's a mapping of metadata to the 3.0 presentation spec in it's current state
* The spec will change. 
* This mapping full work type from avalon hyrax work type. 
Map all possibly desired manifest fields to avalon metadata sources.

**Comment by davidschober** [comment]
This is looking toward the avalon work type. 

(maria) We need to look to other types of metadata we would want to put into the manifest so that other client can consume the manifest.
