### ISSUE TITLE
Pagination is not working in R5 after increasing number of items to view per page

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1820]
### Descriptive summary
Server: media.dlib.indiana.edu
Testing: Exploratory
Browser: Chrome(56.0.2924.87 (64-bit)), checked on Firefox(50.0.2) as well
Flash version: 24.0.0.221
Operating System: Windows10
Issue: Pagination is not working in R5 after increasing the number of items to view per page and clicking on Browse button.

### Steps to reproduce the behavior
1. Login to MCO system
2. Click on "Browse" button
3. Modify the items per page dropdown value from 10 to anyother value, for example: 50
4. Click on "Browse" button again after modifying
5. Click on "Next>>" link to go to the next set of 50 items. Instead of showing 51-100 items in second page, it shows 11-60 items. The clicks on "Next>>" or "<<Previous" buttons don't work anymore.
![pagenation](https://cloud.githubusercontent.com/assets/25850972/24980336/ca2a4ad6-1fa5-11e7-858d-d74283093407.PNG)

### Related work

Link to related tickets or prior related work here.

**Comment by cjcolvar** [comment]
I think we may have a bug for this already somewhere in the backlog.  I'm aware of this and could give more details if necessary.

**Comment by Karthikeya212** [comment]
@cjcolvar could you please share that ticket number here

**Comment by mcwhitaker** [comment]
@cjcolvar I believe you were aware of a ticket that I had opened in the IU queue (https://bugs.dlib.indiana.edu/browse/VOV-5205)

**Comment by davidschober** [comment]
@Karthikeya212 can you verify this is not an issue on 6 and close?

**Comment by Karthikeya212** [comment]
@davidschober The behavior is slightly different in r6. After increasing the items per page to 50 in r5 and clicking on Browse after that will still save that setting and show 50 items per page, it is after this action we observe the issue. However, in r6 after increasing the count and clicking on Browse it resets the setting and goes back to showing 10 items per page, so there is no chance of observing this issue.

**Comment by cjcolvar** [comment]
Right so the bug was a result of our desire to have sticky per page and sort options which I implemented in 5.x or before.  I somewhat deliberately didn't migrate that to 6.x and let the default Blacklight behavior take effect again.  If we want the sticky behavior, we could make a ticket for it and suggest it upstream but I'm not sure if it will find traction and I'm not sure if it is something we really want to commit to maintaining.
