### ISSUE TITLE
Avalon Work Type in Hyrax - Show

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1822]
### Method from #1773

Ideally what we want to do is something along the lines of using the generic work type generator and templates currently in Hyrax and then using Thor to inject on top of them. So this involves updating the model, show, and forms within in Hyrax and then dropping in spec tests as well. We can do our own generator and templates, but it isn't particularly DRY to do it that way.

### Done
- [ ] Update the show
- [ ] Write spec tests

### Original Story
#1773

**Comment by carrickr** [comment]
This can probably be abandon. We're going to run with generic work type until it breaks for us. We've done enough investigation that we know how to make a work type in Hyrax if needed and we also know we don't want to do this unless we need to.

Right now though all we need is #1854 to power our player though.

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#100
