### ISSUE TITLE
Create Hyrax Plugin for Hydra Derivatives

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1826]
### Description
Making a plugin version of the code in #1827 so that Hyrax applications use ActiveEncode for audio and video derivative generation.

### Done
- A plugin is written that is minimally viable—it just needs to work, not have any extra features or conform to the hydra plugin spec.
- Enables ActiveEncode through Hydra derivatives
- Gives instructions on how to set it up with S3 and Elastic Transcoder
- Any additional helper code necessary to make it work (if this needs to be part of it or not can be determined)

Developer tasks
- [ ] Create skeleton engine/plugin
- [ ] Override [create_video_derivatives](https://github.com/projecthydra-labs/hyrax/blob/master/app/services/hyrax/file_set_derivatives_service.rb#L71) with new subclass.
- [ ] Inject subclass into derivative services
- [ ] Write  instructions on how to set it up with S3 and Elastic Transcoder

This then ties into another story for capturing the technical metadata about the created derivative files (#1863).

**Comment by joncameron** [comment]
Extra ticket to be created for:
- Gives instructions on how to set it up with S3 and Elastic Transcoder
- Further documentation

**Comment by carrickr** [comment]
This is tasked, but  as noted above, can be broken up.   We should probably repoint after that to try to get this under eight.

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#102
