### ISSUE TITLE
As a QA Analyst, I need a collection of A/V content to be used for perfomance testing

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1831]
## Collection Details:
**Server**: media.dlib.indiana.edu
**Collection name**: Performance Test Collection
**Items to be used from collection**: performance_item

## Sections in that item:
1.	Lunchroom Manners (09:32) – includes Structure and Captions
2.	Popeye for president (00:30) – includes only Captions
3.	ElectricBeat_1 (00:05) – includes only Captions
4.	ElectricBeat_2 (00:05)
5.	ElectricBeat_3 (00:05)

### We need to:
- build a 100-section item within the given collection
- Add the 100-section item X number of times to the collection (X needs to be determined)

This collection will be created via batch ingest and the files and spreadsheet will be reused whenever we need to recreate it in another Avalon test environment. 

### Some information about the initial 100-section item:
- The above media objects are already identified with different variables such as varying length, varying size, including structure and caption files only in some objects.
- It would be better to keep all these five varying sections, and repeat them to build a 100section item.
- As time and size of each item needs to be taken into consideration, a proposed distribution would be 
1. Section 1 – repeating 5 times
2. Section 2 – repeating 20 times
3. Sections 3, 4, 5 – repeating 25 times each

- Distributing these 100 sections randomly so that section transition could be verified easily for smaller length sections

**Comment by joncameron** [comment]
We may not need a script, since we don't know yet how batch ingest works in Hyrax.

**Comment by davidschober** [comment]
@mcwhitaker and @joncameron this looks pretty ready to go, right? If so, can we move to  ready for tasking?

**Comment by joncameron** [comment]
@davidschober I think it's ready for tasking—I'll pull it over to ready.  @mcwhitaker please feel free to pull it back if there's more that needs to be added.

**Comment by mcwhitaker** [comment]
@joncameron @davidschober This is in progress already. I will mark it as such after noting in the description that it is being done differently than originally proposed.

**Comment by davidschober** [comment]
Sounds good. Thanks!
