### ISSUE TITLE
As a QA Analyst, I need performance parameter values set

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1832]
## So that 
- We know what performance levels we are aiming at.
- We can verify if releases or specific pull requests have a negative impact on performance.
- We can determine if a performance test passes or fails based on expectations.

## Done looks like
- The performance parameters identified as part of [avalon-planning/#104](https://github.com/avalonmediasystem/avalon-planning/issues/104) have their performance indices defined.
- a base architecture is defined to determine performance indices

**Comment by mcwhitaker** [comment]
Attaching here the Performance Parameters document from the other issue for quicker reference:

[Performance testing plan for Avalon.docx](https://github.com/avalonmediasystem/avalon/files/922663/Performance.testing.plan.for.Avalon.docx)

**Comment by Karthikeya212** [comment]
please add any additional parameters or performance scenarios that you feel are important to consider.

**Comment by davidschober** [comment]
@joncameron are we pretty much done?

**Comment by joncameron** [comment]
@davidschober Yep, attached is the Word doc updated with the relevant values and a few things added. 
[performance_metrics-2017-05-25.docx](https://github.com/avalonmediasystem/avalon/files/1029064/performance_metrics-2017-05-25.docx)

**Comment by mcwhitaker** [comment]
@joncameron @davidschober Regarding your comment on "Maximum supported number of active users for mallorn" - "Depends on infrastructure?"

Yes, this depends on infrastructure, which is why we specify "mallorn". That is the infrastructure we are assuming for our testing (or the mallorn-equivalent for an avarax instance).

I believe 500 is too high based on my testing of our MCO instance. MCO is in much better infrastructure and it started returning error messages with 200 active users. _Note that a user who is streaming is not active_ (the avalon app is not doing anything). Active users are those who are clicking on something or entering data or doing an ingest.

**Comment by mcwhitaker** [comment]
@Karthikeya212 We need to update the last paragraph of this document. The strategy to recreate the testing collection has changed. Could you please do that before we can close this ticket? Thank you.

**Comment by mcwhitaker** [comment]
@davidschober @joncameron - Should @Karthikeya212 move this to the avalon wiki, internal documentation section? It is better then an attachment to a github issue, I am thinking.

**Comment by davidschober** [comment]
That sounds like a great plan. I’m also OK with lowering the active users. Jon and I kinda threw a dart at that one (I’d need access to analytics to make a hard call). Can we put a note in about the hardware we’re running?

**Comment by Karthikeya212** [comment]
updated strategy for creating test collection
[performance_metrics-2017-05-25.docx](https://github.com/avalonmediasystem/avalon/files/1029336/performance_metrics-2017-05-25.docx)
