### ISSUE TITLE
Render the "structure" Portion of a IIIF-AV Manifest

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1839]
### Description
The iiif-av player needs to render the structure portion of the iiif-av manifest.

### Done Looks Like 
TBD

**Comment by davidschober** [comment]
related to #1844

**Comment by davidschober** [comment]
@little9 and @adamjarling and @joncameron given what I've seen is this done already? I'm a bit confused.

**Comment by little9** [comment]
@davidschober I would say this is done now

**Comment by davidschober** [comment]
@joncameron closing. You can reopen if more needs doing.
