### ISSUE TITLE
Quality Can Be Chosen When Present In Manifest

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1843]
### Description
IIIF-AV player should have a quality selection interface when type: "Choice", choiceHint: "user" is present in the manifest

The functionality should mimic current functionality in Avalon.

[ UPDATE - May 11, 2017 ]
This story evolved to represent file quality selection in the URL via hash params.  When a manifest contains different quality file options, the player will play the specific quality file based on hash params.  The UI selector needs to be added next.

### Done looks like
- [ ] end use can choose video quality in an IIIF driven player

Related to #1878

**Comment by davidschober** [comment]
![screen shot 2017-04-26 at 5 10 23 pm](https://cloud.githubusercontent.com/assets/4803230/25459332/5356e0aa-2aa3-11e7-9013-ed321d04ac4e.png)

**Comment by davidschober** [comment]
This assumes the video tag has all the sources already. And the manifest has been parsed. 

(jamie) will the manifest be consistent or a minimum number.
(maria) currently that's the norm but it could change.

**Comment by adamjarling** [comment]
Related to and/or duplicated by #1878

@little9 is currently working on a quality selection strategy driven by URI hash params.  I'll try to find that ticket and link it, as there was some discussion on Jamie's idea.  Then we should further clarify how we represent quality selection in the UI.

**Comment by little9** [comment]
In my current branch you can link to a specific quality like this: `/#avalon/time/227,245/quality/Low`. To make a switcher work with the structure porition there would need to be a dropdown or links to change the links in the structure  section. So you click on High and then the links are changed to `/#avalon/time/227,245/quality/High`

**Comment by davidschober** [comment]
@adamjarling and @adamjarling it looks like work has been started on this. Do we need to task it out more or is it ready for the next sprint?

**Comment by adamjarling** [comment]
@davidschober Sounds like this part is done, representing the quality in the URI hash.  Carrying forward, sounds like next step is to create the selection action in the UI.

**Comment by davidschober** [comment]
OK. Can you point that issue in during BB tomorrow?

**Comment by adamjarling** [comment]
Yea, will do.
