### ISSUE TITLE
Navigate by Interacting With Structure

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1844]
## Done looks like
If structural metadata is present that contains time ranges, a user should be able to click links representing that structure to seek within the media in the player.  

### Notes
Per conversations, IIIF allows for a parent to represent the entirety of its children in deeply nested structures. The parent becomes is inclusive of extents in children.

**Comment by davidschober** [comment]
@little9 it looks like you already started some work on this. Feel free to add any refinement you want.

**Comment by davidschober** [comment]
Note depends upon #1839

**Comment by little9** [comment]
I have this partially completed, but need to figure out a way to do parent -> children extents. Navigation is done with hashes in the url so that portions can be linked to directly.
