### ISSUE TITLE
Player Renders on Page When IIIF-AV Manifest is Present

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1845]
### Description
The IIIF-AV-compliant player should render on a view in Hyrax when there is an element on the page with a data attribute pointing to the manifest URL.  <div data-iiif-av-endpoint=http://path/to/manifest.json />

### Done Looks Like
- [ ]

**Comment by mcwhitaker** [comment]
@joncameron My understanding from conversations with the devs last week is that in hyrax the manifests are generated dynamically, so there will not be a data attribute pointing to a manifest. Maybe we need to rephrase this?

**Comment by cjcolvar** [comment]
I think there can still be a data attribute pointing to the iiif manifest building endpoint.  @little9 mentioned in slack:
Right now it works by putting an element in the view like this: `<div id="demo-video-player" data-iiifav-source="https://path/to/manifest/demo/iiifav">`

**Comment by mcwhitaker** [comment]
@cjcolvar Sure. Then the wording needs to be: "pointing to the IIIF building endpoint" instead of "pointing to the manifest".
