### ISSUE TITLE
Investigate Display of Structural Metadata Within Hyrax Context

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1846]
### Description
This is an investigative ticket to discuss direction for the player UI and how to represent structural metadata.

### Questions
Do we want structural metadata to display within the media player, like can be done with Universal Viewer? Or should we keep structural metadata outside the player as it is in 6.x? What are pros and cons of each approach with respect to the user experience?

### Done looks like
- direction agreed up
- documentation written
- sketches drawn

**Comment by davidschober** [comment]
@joncameron this sounds pretty critical, can you write out a description?

**Comment by davidschober** [comment]
@joncameron can you rewrite this one? I"m not sure what it represents.

**Comment by davidschober** [comment]
Related to #1931

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#98
