### ISSUE TITLE
As an instructor, I want a way to share playlists with a group of people defined by me

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1848]
### So That

I can share a _listening exam playlist_ with AIs without making the list public (risking undesired access by students who will be taking the listening exam).

### Possible Options
- Users can create "unlisted" links for a playlist with a URL that is not easily accessed in the style of YouTube(like avalon.edu/playlist/2ks93k2js)
- Users can require that a playlist is only accessible via a password, requiring users to enter the password before gaining access to the playlist
- Users can add specific users for access

### Done looks like

There is a way for sharing playlists beyond the private/public binary option that will enable the playlist owner to control who has access to the list.

### Description
We’ve received the following feedback from a professor concerning the visibility of playlists:

> There are instances when the binary private / public isn’t sufficient—for instance in the case of playlists that will be used to administer listening exams.

> For exam playlists, AIs need access to the playlist yet making the playlist public seems risky, given that playlist URLs don’t provide much obscurity (a wily, motivated student could work their way through all public playlists in the hope of hitting the right one).

> Ideally, there’d be a way to grant access to playlists on a per-user basis—perhaps a way for the playlist creator to define a set of one or more co-owners.

**Comment by davidschober** [comment]
@joncameron can you help flesh out how immediate this need is? Is it something that can way for 7?

**Comment by joncameron** [comment]
This isn't an immediate need, but I'd like it to stay in the backlog. This was written from a user need at IU and is less pressing than other playlist-related refinements.

**Comment by carrickr** [comment]
We need a final call on sharing method before we can point and refine this.  I would vote for the unlisted URL personally as that is the easiest.

**Comment by cjcolvar** [comment]
I would vote for either the first or last option and vote against the middle (password access).  The first being simpler but the last being more robust/secure.  FWIW, google docs does both.  So if we only have time for one which one should we do first assuming we may want both eventually?

**Comment by lealeelu** [comment]
I vote for the unlisted url. It fits our use case with the music library and we already got the ok from them that it would work. Down the road we can add the user based sharing.

**Comment by mbklein** [comment]
Implementation notes for first method:
  * Add a `token` column to the `playlists` table
  * If `visibility` is `private` and `token` is `NULL`, the playlist behaves like a normal private playlist
  * If `visibility` is `private` and `token` is not `NULL`, the playlist can be accessed read-only at `/playlists/[token]`
  * `token` can be regenerated or `nil`ed to revoke access from the old token.

Implementation notes for third method:
  * Read access is controlled via a many-to-many table between `playlist_id` and `user_key` (NOT numeric user IDs)

I strongly discourage trying to create password-protected playlists. The token method serves the same purpose (with the token essentially serving as a password) and is easier both to code and to use.

**Comment by mcwhitaker** [comment]
@avalonmediasystem/product-owners - Both suggestions from @mbklein require some interface design so I suggest asking our UX analyst for input on the solution you decide.

**Comment by joncameron** [comment]
We'll implement the first method.

**Comment by joncameron** [comment]
This also feeds into the story of adding a share link for playlists, #XXXX

**Comment by joncameron** [comment]
Behavior and text for _Share_ functionality:

- The share widget will always be shown on the playlist view page.

Private Playlists display this text:
<img width="415" alt="screen shot 2017-08-25 at 2 37 49 pm" src="https://user-images.githubusercontent.com/1406618/29728201-01922de0-89a5-11e7-8b93-d69054bb9176.png">
_Edit Playlist_ above is a link to the playlist's edit page (same hyperlink as the "Edit Playlist" button above it).

**Comment by joncameron** [comment]
### Updated styling for confirmation pop-up when changing link token
<img width="359" alt="screen shot 2017-08-25 at 4 09 20 pm" src="https://user-images.githubusercontent.com/1406618/29731018-b526b9c4-89b0-11e7-8feb-a176a3227540.png">

**Comment by joncameron** [comment]
We also decided to use the same styling for the buttons as are used in the _Resource Description_ page of editing a media object. I'm not sure what CSS class difference it is but @lealeelu knows which I mean.
