### ISSUE TITLE
As a faculty member with audio content in Avalon, I want to be able to share just clips of audio files in playlists

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1849]
### Description
In the current playlist view, the entire masterfile is displayed in the media player, with the range of the playlist item displayed as a highlighted region within the context of the masterfile. 

### So that 
The playlist I share is limited to the clips of my work that I want to highlight.

### Done looks like 
User has a way to share only clips of the media file instead of full media file content.

### Description
A conducting faculty member wanted to provide examples of his work for his tenure dossier. We helped him by putting together a playlist of the recordings he wanted to include. He had provided specific time offsets for the parts of the specific recordings he wanted the reviewers to hear/see. Avalon allows for the playlists to go directly to the start time offset, but puts the marker in the context of the entire recording. The faculty member wanted just the clip, not the entire recording available to the reviewers as there are other places in the recordings that weren’t as stellar as the clips he intended for them to hear/see, and we made it too easy for them to scrub around to sample other parts.

So, the ability to make clips and create a playlist of them is what is being asked for here.

### Further Description

Issues with the current rendering in playlist view
- Marker offsets are relative to the length of the section, not to the playlist item
- Markers outside of the playlist item scope are undefined behavior

**Comment by mcwhitaker** [comment]
See also #1553.

**Comment by davidschober** [comment]
@mcwhitaker can you and I and @joncameron  talk through this one? I'd like to pick one way to do clips within playlists.. Either show it in the context of the track with lil'scrub or this way where **only** the clip is shown. I think offering too many ways to do something will be confusing to end users. I know when we decided to go the with the zoom scrubber it was because there were use cases wherein people wanted to see the highlight but also see the relation to the rest of the work. How critical is this for 6.3? I think this needs some design work.

**Comment by mcwhitaker** [comment]
@davidschober when we went with the lil scrubber, it was because we did not want to spend the time to do what this ticket is asking for. I don't know of the use case to keeping it the way it is today.

If someone wants to go to the source item, we provide a link to it on the section below the player.

We can talk about it if you want to come to a determination.

**Comment by joncameron** [comment]
It would be best to wait until after ME4 is finished being implemented.

**Comment by davidschober** [comment]
@mcwhitaker @joncameron to discuss with user what's more important... Context or isolation. These are competing use cases.

**Comment by davidschober** [comment]
this seems out of scope.It was based on a single use case .

**Comment by joncameron** [comment]
Re-evaluate for 7.

**Comment by mcwhitaker** [comment]
@joncameron What does it mean to re-evaluate for 7? If the ticket is closed, where will we keep track of it to come back and re-evaluate? I am interested to know what the process because apparently you think it is not stale, it just needs reevaluation.
