### ISSUE TITLE
Avalon installed and can't see the Options Such as Upload video and contents

### ISSUE THREAD

**Issue by blackyboy** [avalonmediasystem/avalon#185]
Hi , Installed Avalon media , but the front end have only the sign in and there is nothing Displayed how can i see the back-end even after log in using a Credential's there is no options to upload videos and other options, how to get it , Here in 1st image i'm showing my front-end and in 2nd image its back-end after log in , 

While Have a look at Site health using 

http://192.168.1.220:3000/about/health

It's showing as 

error solr
Numdocs must be greater than or equal to 1

In Image 3 Error message you can see , But while im navigating to 

http://192.168.1.220:8983/solr/#/

Its Working file as shown in image 4 

In image 5 

While choosing the coreadmin in left pane of Solr , there too numDocs : 0 

How can i get fixed and get my Full Front End .. 

Image 1

![selection_001](https://f.cloud.github.com/assets/4866182/1451974/2362aae6-42b7-11e3-810d-ad0c4fb47cde.png)

Image 2 

![selection_002](https://f.cloud.github.com/assets/4866182/1451976/3a4e2aa0-42b7-11e3-8ffd-c2de462becf8.png)

Image 3

![selection_003](https://f.cloud.github.com/assets/4866182/1451979/4a5d8756-42b7-11e3-8ebb-c502fcf211f5.png)

Image 4 

![selection_004](https://f.cloud.github.com/assets/4866182/1451981/51f51132-42b7-11e3-9317-a4b49c18442b.png)

Image 5 

![selection_005](https://f.cloud.github.com/assets/4866182/1451982/5a2cb58a-42b7-11e3-9f23-fc978f0a872d.png)

**Comment by jogiraju** [comment]
Hi, I have installed Avalon Media Systems Version 5.1 successfully on CentOS 6 using puppet installation option. I was able to upload audio files (tried mp3) without any error and could playback using the Avalon Web Interface. However, I was not able to upload Video files (mp4, flv, etc.). It is giving an internal server error (504). The same thing happened with Avalon VirtualBox appliance installation. 

Can any body help ?
