### ISSUE TITLE
Investigate FITS and Storing Additional Technical Metadata in Hyrax

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1850]
### Points of Investigation
- [x] determine why FITS doesn't provide proper metadata for .ogg video and consider PRing to fix it
- [x] determine if other video types have this issue
- [ ] ~look into having Hyrax store additional technical metadata fields for the generic work type.  See [this comment](https://github.com/avalonmediasystem/avalon/issues/1824#issuecomment-297069043) for locations to make the change~ Duplicate of task in #1854
- [x] Make sure fits provides the aspect ratio

Initial investigation was does in #1824 

### Done Looks Like
Decision on if we use GenericWork type with enhanced technical metadata or if we go with our work type and use either our implementation of FITS or just directly use MediaInfo

**Comment by lealeelu** [comment]
Got output for an .ogg video. https://gist.github.com/lealeelu/9d2ff2690049201c2613a433e72c7cf7

I got fits to look at the ogg with mediainfo by going into xml/fits.xml and adding .ogg to the list of mediainfo included extensions like so: 
```<tool class="edu.harvard.hul.ois.fits.tools.mediainfo.MediaInfo" include-exts="avi,mov,mpg,mpeg,mkv,mp4,mxf,ogv,ogg,mj2,divx,dv,m4v,m2v,ismv,m2ts,mpeg4" classpath-dirs="lib/mediainfo" />
```
and that also determines which order the tools run in and output preference.

**Comment by lealeelu** [comment]
Also, it runs a ton faster if you disable some of the tools listed in fits.xml. Are there any in there we might not need?

**Comment by lealeelu** [comment]
Verified it returns aspect ratio. Since it's being run through mediainfo, we should expect the same results for aspect ratio as we've been getting with our current avalon.
