### ISSUE TITLE
S3 Storage for Dropbox

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1855]
### Description

AWS storage for files needs to be discussed.
Decision point

### Decision Points
- [ ] What are we going to do?
- [ ] Create plan for moving forward and write new tickets as needed.

### Original Issue
Broken out from: https://github.com/avalonmediasystem/avalon-docker/issues/9

**Comment by davidschober** [comment]
@joncameron, @phuongdh and @mbklein... I think we've made these decisions correct? 

The cloud formation script currently drops off stuff in s3 buckets, handles batches from them, etc. Is there something more specific I'm missing?
