### ISSUE TITLE
Create current feature list documenting 6.0 media player

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#1860]
Create a feature list of the current Avalon media player, which will guide development tasks for the new Hyrax player.

### Done Looks Like:
- [x] The below list is filled-out

#### Player Icons
- Play/Pause
- Toggle track scrubbing
- Volume adjustment
- Video quality selector
- Create thumbnail
- Add to playlist
- Add Marker
- Full screen

#### UI
- Share dialog
  - Share this resource
  - Embed
  - LTI URL
- Sections
- Sidebar content

#### Player Icons
- Play/Pause
- Toggle track scrubbing
- Volume adjustment
- Video quality selector
- Add to playlist

#### UI
- Sections
- Sidebar content

![avalon-audio-player-example](https://cloud.githubusercontent.com/assets/3020266/25632679/2dbff07a-2f3a-11e7-841a-b5515a30dd5e.png)

![avalon-player-example](https://cloud.githubusercontent.com/assets/3020266/25632680/2dc10a5a-2f3a-11e7-9cb5-2aada20a0c96.png)

**Comment by adamjarling** [comment]
@davidschober @joncameron Does this list look complete enough to mark as 'Done'?

**Comment by joncameron** [comment]
@adamjarling Looks good to me, and I think it's ready to mark as Done. I added "Add Marker" to the player—that one only appears on the player in Playlist view.

**Comment by adamjarling** [comment]
@joncameron Great, thanks for adding that.  So maybe to mark this issue as done, where we don't need to reference it anymore, #1858 should be updated with subtasks to reflect everything in this initial list.   I'll continue updating the EPIC ticket with subtasks and add descriptions to flesh that out.

**Comment by davidschober** [comment]
This looks great. @joncameron do you want to add it to the wiki somewhere? or is it enough to have it represented in this issue.

**Comment by joncameron** [comment]
Yes, I'll add this to the wiki tomorrow so we don't lose track of it and close this issue.
