### ISSUE TITLE
Investigate Solutions To Why Playlist Items Are Skipped

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1861]
This is a swarm topic

- [ ] create playlist where the skipping occurs, using either lots of short clips or repeating the same clip
- [ ] investigate fixing this while maintaining seamlessly play through
- [ ] if seamless is not possible, investigate if inserting a pause between items solves the issue
- [ ] if the pause does not fix, discuss potential cost of fix vs potential cost of a new player
- [ ] present results to POs and discuss how this impacts #1552

### Related Issue
#1552 - Main story/bug report for fixing this problem

**Comment by joncameron** [comment]
This should be re-evaluated after the MEJS4 upgrade to see if it's still a concern.

**Comment by cjcolvar** [comment]
I was not able to reproduce this with a quick test of the MEJS4 player on spruce.

**Comment by joncameron** [comment]
I couldn't reproduce this either; going to do one more pass before closing this.
