### ISSUE TITLE
Add Fedora4 URI to MODS record as recordIdentifier

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1869]
## Description

Per discussion on slack, the recordIdentifier for the fedora 3 pid should be left in the MODS document and a new recordIdentifier should be added for the fedora 4 uri:
`<recordIdentifier source="Fedora4">[full object URI]</recordIdentifier>`

This is something we could rerun later to add to the mods record. 

## Done looks like

- [x] Fedora4 URI is added to MODs record as a recordIdentifier
- [x] If a  recordIdentifier is already there it is not replacing but adding along side

**Comment by lealeelu** [comment]
In the process of testing this out, I thought it would be a good idea to make a new task based off of avalon:migrate:repo called avalon:migrate:pids that takes a list of pids separated by commas and only migrates that instead of everything ever.
