### ISSUE TITLE
prov:wasDerivedFrom is not being indexed

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1877]
prov:wasDerivedFrom is not being indexed due to a bug in ActiveFedora/ActiveTriples where URI's aren't being indexed.  We either need to submit a PR to fix this, find a workaround, or give up and use a string instead of an RDF::URI.

**Comment by jlhardes** [comment]
Never give up! :) That property needs a URI as a value so I would vote for PR fix.

**Comment by jenyoung** [comment]
I agree. URI is needed.

**Comment by davidschober** [comment]
points assume we're doing the work around. @cjcolvar needs this in sprint 126.

**Comment by cjcolvar** [comment]
I think a workaround I suspected might work is.  I'm treating the property as multivalued even though we're only ever going to put a single value in it and the property getter/setter methods are only defined during the course of the migration.  This is hacky but an easy workaround.

**Comment by jlhardes** [comment]
Does this keep the value as a URI or is that working with the value as a literal?

**Comment by cjcolvar** [comment]
It is still a URI.
