### ISSUE TITLE
Media element 4 - CreateThumbnail

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#1880]
### Description
Re-create create thumbnail functionality from Avalon 6.x video player into Hyrax Mediaelement video player. 

### Done Looks Like
As a user, I want to press a button that triggers a modal pop-up that displays a static image. And saves said static image data to the proper place. 

### Tasks
- [x] Attempt to bring in existing mediaelement plugin.
- [x] If that doesn't work, create plugin from scratch.

**Comment by adamjarling** [comment]
Pointing at a 3, assuming we can bring in mediaelement plugin.  If we build from scratch, will be much more work.

**Comment by davidschober** [comment]
@adamjarling can you do this work without somewhere to store the thumbnail? Or are you just moving the visual part.

**Comment by adamjarling** [comment]
@davidschober I'm not sure.  The idea was to begin work on this by attempting to use the existing mediaelement plugin.  I'm guessing that would provide the UI, at least as a starting point?  Once it seems the plugin is pulled in correctly, then we'll need to evaluate the functionality within the Hyrax environment.  Until either Jamie or myself start work on this ticket, not entirely sure what we'll find.

**Comment by adamjarling** [comment]
@davidschober @joncameron Perhaps this is a good starting point to pull in a plugin into a MediaElement 4 player?   Sounds like @phuongdh has an existing Git repo of the codebase he worked up in Swarm from Tuesday, we could build on top of?   

And it'd be helpful for me to work on this ticket jointly with @bkeese so I can learn how previous plugins were applied to the Rails application, ask questions, get me generally up to speed before moving onto other plugins.   

Thoughts?

**Comment by davidschober** [comment]
That makes sense to me!

**Comment by joncameron** [comment]
Sounds good to me as well. I'll put something on the board later today for this.

**Comment by adamjarling** [comment]
Quick update... this feature follows the Mediaelement 4 plugin pattern, established in Adding Playlist, Add Markers to Playlist.

This should be merged AFTER the Add Markers to Playlist branch, as it builds from that work. (https://github.com/avalonmediasystem/avalon/pull/2329)
