### ISSUE TITLE
Hyrax Media Player - Sections

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#1887]
### Description
Hyrax player UI should display a 'Sections' area similar in look and functionality to Avalon 6.x UI.

### Done Looks Like
- [x] Sections data is represented in the manifest
- [x] Create sections UI container markup
- [x] Sections manifest data parsed, and completes UI markup
- [x] #1946 Update Hash handler with canvas index/id 
- [x] Links within section content cause the player to play desired range/area

![avalon-player-sections](https://cloud.githubusercontent.com/assets/3020266/25753807/8a8bb5ce-3182-11e7-8f3c-b80055f48dc0.png)

**Comment by lealeelu** [comment]
@adamjarling, It looks like this is in progress. Do you want to move it to in progress or is this on hold?

**Comment by adamjarling** [comment]
Yes, it's in progress.  Feel free to move into the appropriate column.  Thanks!

**Comment by mcwhitaker** [comment]
@adamjarling Do you think you will get to this during this sprint? I think the reason why it was not "in progress" was because we concluded you had other things to work on this cycle.

**Comment by adamjarling** [comment]
@mcwhitaker Actually this functionality is pretty much done, at least for the video player.  @little9 set up a recursive function to parse the manifest 'structures' which will display the links.  Once we split the audio and video players into their own 'pages' this functionality either will work immediately with the audio player, or just take a little bit of work to make functional.  I think we can get this done in this sprint.

**Comment by mcwhitaker** [comment]
@adamjarling The audio example we have with 2 sections is not working properly. Clicking the links related to section 2 still move the player cursor in section 1. See http://96665a02.ngrok.io/demo/audio/#avalon, which is the demo Jamie put together for me with audio and video on separate pages.

**Comment by adamjarling** [comment]
@mcwhitaker Yes, seems right that the audio player will take some work to make functional as I mentioned above.  I haven't seen the audio player split into it's own page yet, or pulled down the latest branch codebase.  Do you want me to work on this now?

**Comment by mcwhitaker** [comment]
@adamjarling Not necessary, thank you. I will mention while demoing that this is a work in progress.

**Comment by adamjarling** [comment]
Ok sounds good.  I'm close to wrapping up the NU Avalon UI, and aiming to hop back into this audio issue (and other Hyrax player work) tomorrow w/ Jamie.

**Comment by little9** [comment]
I'm going to need to spend some time thinking about the different possibilities that the manifest might have. 

- For video there is basically one file, which may have multiple quality derivatives. 
- For audio there can be multiple files (tracks) that each have multiple quality derivatives. 

Do video resources ever have something like the equivalent of tracks?

**Comment by mcwhitaker** [comment]
@adamjarling You can have multiple files for video as well. And we can have one audio and one video file (or multiple audio and video files) for an Avalon work -- see #1851.

And Video may have structural metadata also, which should be used for navigation as well. 

Basically, the only difference between audio and video is the media format.

**Comment by mcwhitaker** [comment]
@little9 Another difference is 3 derivatives for video (H,M,L) and 2 for audio (H,M).
