### ISSUE TITLE
Hyrax Media Player - Sidebar Metadata

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#1888]
### Description
Hyrax player UI should display sidebar metadata content similar to how Avalon 6.x UI displays content.

### Done Looks Like
- [ ] Manifest file contains necessary metadata content
- [ ] Sidebar UI container markup created
- [ ] Manifest file parsed and supplies markup with correct data

![avalon-player-sidebar](https://cloud.githubusercontent.com/assets/3020266/25754456/e00d7256-3184-11e7-90a5-f03862dffdc0.png)

**Comment by adamjarling** [comment]
@bkeese Is the sidebar metadata content usually not part of the manifest?  There'd be another source of this info?

**Comment by bkeese** [comment]
That's a good question. We have had discussions about adding arbitrary metadata to the manifest, and it seems possible that we could add everything that might be wanted in the player view. However, there are other sources for this info that could be loaded separately.

**Comment by adamjarling** [comment]
Ok, sounds good.  For now, I'll just put that on the back burner and assume it's coming from another source.

**Comment by jlhardes** [comment]
We defined minimum descriptive metadata to accompany an item in IIIF for Avalon - title and date - from #1772 and those are mapped to where they would go in the manifest. So the minimum metadata we require to describe an Avalon item is also the minimum metadata that should show in that sidebar.

**Comment by jenyoung** [comment]
Doesn't all the metadata associated with an item display now in the sidebar? Why would that be different in the player view? I don't know of another way to see more than the title and date  except for the sidebar.

**Comment by carrickr** [comment]
Per the conversation in swarm, show what we currently show in the sidebar, as shown in the original image.

**Comment by mcwhitaker** [comment]
@jenyoung @jlhardes We should add to the IIF-AV manifest anything that we think we would like other players (not avalon) show if they embed our content.

**Comment by carrickr** [comment]
The equivalent of our metadata sidebar, the area in red in the  will be provided by universal viewer.  Regarding the original question, the section in red highlighted above comes from a separate source currently (as per bkeese's comment).

No dev work has been done with universal viewer yet, so we're not entirely sure what the AV manifest will look like (and how well it will work for presentation to the average user).  In Hyrax we probably won't control the sidebar like we do in Avalon, we'll only control the player area.

Moving forward we should probably demo what the manifest viewer in Universal Player looks like and then do any design refinement needed.

**Comment by carrickr** [comment]
So Adam's initial question "Of what is in the IIIF vs the sidebar" was answered in that IIIF provides the data needed to drive the player.  

Regarding displaying data to the user, that's more of a round 2 issue when we start refining the views, at which point we'll make tickets to detail that work and determine how we get the metadata to that page.

Closing as the ticket was answered, future tickets will be made related to UI design.

**Comment by mcwhitaker** [comment]
@carrickr IIIF-AV has the means to provide the sidebar information also if we want to, which is why I asked @jenyoung and @jlhardes what they want other players to show if they get a IIIF-AV manifest from avalon for an avalon item. 

If they want other players to show more information that is available than just the minimal, we should add that to the IIIF-AV manifest that we generate for avalon items. This is all independent of how developers will code the sidebar.
