### ISSUE TITLE
Create Collection Modal - Add bottom margins to text inputs

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#1889]
### Description
Add default application spacing/padding/margins to form elements in 'Create Collection' modal window

### Done Looks Like
- Form text input elements are evenly spaced vertically, and do not look scrunched together.

### Tasks
- [ ] Update CSS to fix margins

**Comment by joncameron** [comment]
Current look:
![screen shot 2017-08-24 at 9 24 42 am](https://user-images.githubusercontent.com/1406618/29668424-24bb52da-88ae-11e7-8f77-44e58dcdef4b.png)

**Comment by adamjarling** [comment]
@joncameron This should be a pretty easy fix.  Same thing I noticed on the Add Playlist modal from Add To Playlist functionality.  Each form element label / input should be wrapped in a `form-group` bootstrap class to keep consistent... ideally in all forms across the application.

**Comment by davidschober** [comment]
done enough
