### ISSUE TITLE
Playlist empty list - call to action?

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#1891]
### Description
When creating a playlist, default message displays "This playlist currently has no playable items."  There is no call to action or path forward for user.   Provide an action link or button guiding user to creating a playable item?

### Done Looks Like
- Discuss UX issue, and patterns in the application for similar scenarios?
- Provide a call to action link or button which takes user to create playable item path.

### Tasks
- [ ] Discuss UX issue, and patterns in the application for similar scenarios?
- [ ] Provide a call to action link or button which takes user to create playable item path.

![playlist-empty-call-to-action](https://cloud.githubusercontent.com/assets/3020266/25812270/636001a2-33db-11e7-88e4-f35e5ae8c1ee.png)

**Comment by davidschober** [comment]
For this one an "Add items to playlist" which kicks off a search.

**Comment by davidschober** [comment]
av 6 styling won't fix
