### ISSUE TITLE
Clean up VPC's network interface when stack is deleted

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#1896]
Currently security groups stack can't be cleaned up because the DBclient group has an attached network interface.

We need to write a script to detect the network interface. When you bring a stack up and down you have to manually delete the network interface. This was because we created a lambda that uses something in the VPC. 

If it tries to delete the stack it gets stuck.

### Done looks like
Network interfaces detaches cleanly.

### Tasks
- [ ] Lambda written to detach and delete network interface OR, if not possible,
- [ ] Retain security groups so it doesn't prevent the stack from deleting cleanly

**Comment by joncameron** [comment]
"Lambdas all the way down" - Phuong

**Comment by davidschober** [comment]
closing as stale
