### ISSUE TITLE
Reference - Hyrax Embedded Video Player Possible Bug

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1899]
### Description
Reference ticket for work done on projecthydra-labs/hyrax#932

### Done Looks Like
- Verify config changes in the Hyrax issue resolve the problem
- Identify what needs to be done to fix the bug if not

**Comment by joncameron** [comment]
We'll turn this more into an investigative ticket. It's been confusing to people so far regarding getting ffmpeg working and ingesting video in hyrax.

**Comment by davidschober** [comment]
@cjcolvar did this get cleared out?

**Comment by davidschober** [comment]
abandoned. There was some confusion about configuration.
