### ISSUE TITLE
Create Thumbnail For Video Item

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1900]
### Description

Recreate current functionality that creates a thumbnail from a stream for display. 

### As a 
Collection Manager

### So That
I can set the thumbnail image for a video.

### Done Looks Like

- Thumbnail button is wired up to create and store thumbnail
- Thumbnail is shown on front end. 

#### Tasks
- [ ] UI Work #1880

**Comment by davidschober** [comment]
@adamjarling do you wan too pint this?

**Comment by davidschober** [comment]
scratch this. Abandoned in favor of #1880 (pointed.)
