### ISSUE TITLE
Create Repository for AWS Templates

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1902]
### Description
Avalon templates currently living in MBK's personal repo at https://github.com/mbklein/aws need to be moved to a central, Avalon-owned location.

### Done Looks Like
Relevant code from https://github.com/mbklein/aws is given a home under the avalonmediasystem Github organization.

Decide whether to fork and branch or split completely.

**Comment by davidschober** [comment]
Note #1489 should be created at the same time.
