### ISSUE TITLE
Start conversation with Hyku team about video  work type

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1906]
### Description
Whether we need to create a new work type for video or add to the existing generic work type is yet to be determined. A conversation with the Hyku team about their current plans will help us plan for what direction makes best sense for Avalon.

### Done Looks Like
- [ ] Figure out where video lies on road map
- [ ] what are their needs in Hyku
- [ ] start to answer question generic or video type

**Comment by cjcolvar** [comment]
@davidschober did Carrick give you a report that can be summarized here and we can move this to done?

**Comment by davidschober** [comment]
He got a bit held up yesterday and today he’s on vacation. We can close it. He discussed it a bit on tuesday with you all right?

**Comment by davidschober** [comment]
@carrickr can you post your findings here?

**Comment by joncameron** [comment]
@carrickr Is this still in the hopper? I remember you mentioning a work-in-progress document but I can't remember if that was in Box or on your local disk.

**Comment by carrickr** [comment]
Report on Hyrax is here: https://northwestern.box.com/s/a0voph3h2tt4azbm78lwp0kf7w7wb40e

On Hyku, it got a paragraph, it seems kind of like the forgotten stepchild at times based on current development priorities.
