### ISSUE TITLE
Discuss UX/UI issues

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1907]
## Description

Karthik has started a wiki page noting odd ui/ux behavior. Adam and Kathik will get together to discuss and how to solve them, generate issues etc.

## Tasks
- [x] meeting takes place (on or off)
- [x] issues generated

**Comment by mcwhitaker** [comment]
Link to the Usabillity/UX notes from @Karthikeya212 : https://wiki.dlib.indiana.edu/pages/viewpage.action?pageId=525145959

**Comment by adamjarling** [comment]
@davidschober @joncameron  Just had a great meeting with @Karthikeya212 and @mcwhitaker going over the QA Observation List.   All the items seem manageable, and could improve the UI/UX significantly.   

Next step may be to share @Karthikeya212 's document with you both, and get a game plan for how to implement.   I think sooner the better.  Ballpark guesstimate: all 19 items I could probably implement in 4-6 work days.   Plus QA time...

**Comment by davidschober** [comment]
Excellent. We’ll look through these and get them on the road map for next month possibly?

**Comment by adamjarling** [comment]
@davidschober Yes, we should aim for the next month.  They'll help clean up NU Avalon, and IU Avalon (I imagine) implementations as well.

**Comment by davidschober** [comment]
@Karthikeya212 to break out issues.
