### ISSUE TITLE
Unable to Import Dropbox Item in Collection With Name Containing '?' Character 

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1920]
### Description
If a collection name contains a question mark, attempting to import a file from the collection's dropbox fails and Rails throws an error.

### Environment
Mallorn, 6.0.1. Originally encountered on 5.1.6, and also affects 5.x.

### To Reproduce
- Give a collection a name containing the "?" character
- Put a media file into the dropbox for the new collection
- Attempt to use the "Import from dropbox" to ingest the media file
- A 500 is returned

### Done Looks Like
* Question marks are stripped from system directory name and dropbox works as expected

### Tasks
- [ ] Strip question-mark from collection name when creating and accessing dropbox directory.
- [ ] Write tests
- [ ] Document change

### Production.log Excerpt With rb_sysopen Error
> Started GET "/media_objects/avalon:16186" for 66.249.69.49 at 2017-05-15 09:48:46 -0400
> Processing by MediaObjectsController#show as HTML
>   Parameters: {"id"=>"avalon:16186"}
> Processing by MasterFilesController#create as HTML
>   Parameters: {"utf8"=>"✓", "authenticity_token"=>"3/D8MhBQnh4qfS1AmkBFFzHqo+3K1XrMf6lAFblsan0=", "workflow"=>"", "container_id"=>"avalon:241332", "selected_files"=>{"0"=>{"url"=>"file:///N/beryllium/avalon/dropbox/Marcel_Tabuteau__How_Do_You_Expect_to_Play_the_Oboe_If_You_Can't_Peel_a_Mushroom?/01+Prelude.mp3", "file_name"=>"01+Prelude.mp3"}}}
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_facet_limit.html.erb (2.4ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_facet_limit.html.erb (1.8ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_facet_limit.html.erb (7.8ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_facet_limit.html.erb (6.8ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_facet_limit.html.erb (1.9ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_facet_limit.html.erb (1.8ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_facet_limit.html.erb (2.7ms)
>   Rendered catalog/_facet_group.html.erb (29.0ms)
>   Rendered catalog/_facet_group.html.erb (8.2ms)
>   Rendered catalog/_facets.html.erb (37.7ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_search_sidebar.html.erb (37.9ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_opensearch_response_metadata.html.erb (0.2ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_did_you_mean.html.erb (0.1ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_constraints_element.html.erb (0.4ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_constraints_element.html.erb (0.5ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_constraints.html.erb (3.5ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_paginate_compact.html.erb (3.1ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_sort_widget.html.erb (5.2ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_per_page_widget.html.erb (7.5ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_view_type_group.html.erb (0.1ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_sort_and_per_page.html.erb (17.8ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_search_header.html.erb (22.0ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_document.html.erb (112.0ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/_results_pagination.html.erb (10.2ms)
>   Rendered catalog/_search_results.html.erb (148.0ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/catalog/index.html.erb within layouts/avalon (186.4ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/shared/_ajax_modal.html.erb (0.0ms)
>   Rendered modules/_user_management.html.erb (0.4ms)
>   Rendered modules/_header.html.erb (0.8ms)
>   Rendered modules/_avalon_search_form.html.erb (0.0ms)
>   Rendered _user_util_links.html.erb (1.2ms)
>   Rendered modules/_global_navigation.html.erb (2.3ms)
>   Rendered modules/_flash_messages.html.erb (0.1ms)
>   Rendered modules/_footer.html.erb (0.3ms)
> Completed 200 OK in 421ms (Views: 193.9ms | ActiveRecord: 16.2ms)
>   Rendered media_objects/_administrative_links.html.erb (62.4ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/bundler/gems/mediaelement-track-scrubber-66973deb0518/app/views/_track_scrubber.html.erb (0.1ms)
>   Rendered media_objects/_workflow_progress.html.erb (2.6ms)
>   Rendered media_objects/_share_resource.html.erb (0.1ms)
>   Rendered media_objects/_embed_resource.html.erb (0.1ms)
>   Rendered media_objects/_share_resource.html.erb (0.4ms)
>   Rendered media_objects/_embed_resource.html.erb (0.7ms)
>   Rendered media_objects/_share.html.erb (13.9ms)
>   Rendered media_objects/_sections.html.erb (11.2ms)
>   Rendered media_objects/_metadata_display.html.erb (19.8ms)
>   Rendered media_objects/_item_view.html.erb (69.2ms)
>   Rendered media_objects/show.html.erb within layouts/avalon (149.1ms)
>   Rendered /srv/avalon/avalon_r5/shared/gems/ruby/2.1.0/gems/blacklight-5.18.0/app/views/shared/_ajax_modal.html.erb (0.0ms)
>   Rendered modules/_user_management.html.erb (0.3ms)
>   Rendered modules/_header.html.erb (0.6ms)
>   Rendered modules/_avalon_search_form.html.erb (0.0ms)
>   Rendered _user_util_links.html.erb (0.7ms)
>   Rendered modules/_global_navigation.html.erb (1.4ms)
>   Rendered modules/_flash_messages.html.erb (0.1ms)
>   Rendered modules/_footer.html.erb (0.2ms)
> Completed 200 OK in 452ms (Views: 150.9ms | ActiveRecord: 54.3ms)
> Completed 500 Internal Server Error in 526ms
> 
> Errno::ENOENT (No such file or directory @ rb_sysopen - /N/beryllium/avalon/dropbox/Marcel_Tabuteau__How_Do_You_Expect_to_Play_the_Oboe_If_You_Can't_Peel_a_Mushroom):
>   app/controllers/master_files_controller.rb:223:in `initialize'
>   app/controllers/master_files_controller.rb:223:in `open'
>   app/controllers/master_files_controller.rb:223:in `block in create'
>   app/controllers/master_files_controller.rb:218:in `each_value'
>   app/controllers/master_files_controller.rb:218:in `create'
>   lib/avalon/stream_auth.rb:55:in `call'

**Comment by cjcolvar** [comment]
I think we just need to strip out the ? or replace it like we do for other special characters when we create the server side directory.  https://github.com/avalonmediasystem/avalon/blob/master/lib/avalon/sanitizer.rb#L17
