### ISSUE TITLE
Bulk actions are working only on first 10 items irrespective of number of items selected

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1927]
### Descriptive summary
Server: spruce.indiana.edu
Testing: Exploratory
Browser: Chrome(58.0.3029.110 (64-bit))
Flash version: 24.0.0.221
Operating System: Windows10
Issue: Bulk actions Delete/Move/UpdateAccessControls/AddToPlaylist are working only on first 10 items irrespective of number of items selected

### Steps to reproduce the behavior
1. Login to spruce
2. Select more than 10 items, and navigate to Managed Selected Objects page.
3. Initially only 10 items will be displayed in the page, change items per page to 100.
![selected items 100](https://cloud.githubusercontent.com/assets/25850972/26123434/e3d57128-3a48-11e7-8049-a19e118811a8.PNG)

4. Make sure that all the items in that page are selected.
5. Click on Delete button, which displays a pop-up with all the items to be deleted, confirm it.
![delete 100](https://cloud.githubusercontent.com/assets/25850972/26123480/0ca47e82-3a49-11e7-81c6-2fedcd05d199.PNG)

6. It reloads the page and shows only first 10 items again, also the operation is performed on those 10 items and not on all the selected items.
![delete 10](https://cloud.githubusercontent.com/assets/25850972/26123570/5be46584-3a49-11e7-8f0b-4b1838963407.PNG)

### Related work

Link to related tickets or prior related work here.

### Tasks
- [ ] track down where we need to reconfigure Blacklight/rsolr defaults
- [ ] reconfigure them
- [ ] write a test to prove that it is fixed

**Comment by Karthikeya212** [comment]
Publish/Unpublish are working fine with more than 10 items. It may be because these two actions are not triggering any requests for a pop-up or a new page like the other 4 options Delete/Move/UpdateAccessControls/AddToPlaylist.

This issue is not seen in R5

**Comment by cjcolvar** [comment]
This is probably a bug that comes up because Blacklight/rsolr default to 10 results.  We need to track down where we need to reconfigure it and write a test to prove that it is fixed.  Probably 3 points.

**Comment by mcwhitaker** [comment]
@cjcolvar I wonder if the configuration you are looking for is this:

https://github.com/avalonmediasystem/avalon/blob/dd9ea47de0fb4cc3bc2503b0b414e98fd2ea48ae/app/controllers/catalog_controller.rb#L38-L43
