### ISSUE TITLE
Error should be thrown if ActiveEncode job doesn't receive id

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1932]
The encoding creation job blindly tries to update the masterfile using the new encode job and spawns the progress update jobs but they don't do anything since they can't find the ActiveEncode job.  We should probably throw an error or handle it in a way that makes it visible to the user and administrators.

### Related Issue
#2060 Failure to create ActiveEncode job returns unrelated job's metadata

**Comment by cjcolvar** [comment]
This has been handled in #2060 except that the error message presented to the user is not helpful.
@avalonmediasystem/product-owners should we close this story or rewrite it to be focused on the providing a more helpful error message?

**Comment by joncameron** [comment]
@cjcolvar I think we should close and write a new one. What's the error message that the user currently receives—is it 'Error creating encoding job' as a Blacklight notification?

**Comment by cjcolvar** [comment]
No I believe it is `ERROR: NilClass`

**Comment by joncameron** [comment]
Question for backlog buddies: what are the circumstances in which this will pop up?

**Comment by joncameron** [comment]
This can be low priority- using the queue throttlers may alleviate this, and it hasn't been seen in production.

**Comment by davidschober** [comment]
We haven't seen this. Stale.
