### ISSUE TITLE
MODS contains a lot of extra empty elements

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1935]
MODS for items on spruce contain a lot (sometimes A LOT) of extra empty MODS elements. For some elements (physicalDescription), this is making the MODS not valid.

## Done looks like

- Mods should be valid
- There should not be empty elements
- when you create or edit items empty elements should not be created

## relates to
It might be related to:

#1837

### Tasks
- [ ] Isolate issue and fix
- [ ] Write tests
- [ ] Ensure is fixed for bib import as well as non-bib import items

**Comment by jlhardes** [comment]
These are all 3 items in the "Jules test" collection on spruce.
[descMetadata.zip](https://github.com/avalonmediasystem/avalon/files/1011066/descMetadata.zip)

**Comment by bkeese** [comment]
I wonder if this was caused by the empty string bug we fixed recently. https://github.com/avalonmediasystem/avalon/pull/1898/files

**Comment by jlhardes** [comment]
Is that fix on spruce? These are items I just created so if that fix helps with this then these new MODS records shouldn't haven't all of those extra fields, right?

**Comment by bkeese** [comment]
It is on spruce, so I guess something else is causing this. Boo.

**Comment by cjcolvar** [comment]
It looks like this is only related to bib import from what I can tell.

**Comment by cjcolvar** [comment]
@jlhardes Could you please verify that this isn't a problem with new objects on spruce that do NOT use bib import?

**Comment by jlhardes** [comment]
There's still a lot of empty <physicalDescription> even in this item that I just created and didn't use bib import.


![screen shot 2017-05-18 at 5 07 52 pm](https://cloud.githubusercontent.com/assets/3440166/26223558/a7f5d080-3bec-11e7-97aa-8d9dfaa4c0d6.png)

**Comment by bkeese** [comment]
titleInfo[@usage='primary'] also is repeated

**Comment by bkeese** [comment]
Every time the resource description page is saved, a new empty titleInfo element is added to MODS.

**Comment by davidschober** [comment]
This might be connected to #1837
