### ISSUE TITLE
Migrated items showing Fedora4 URL as Other Identifier

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1938]
Migrated items that don't have bib import as the source for descriptive metadata are showing a 127.0.0.1 Fedora4 URL for the item as an Other Identifier with no label. The MODS contains this info only as `<recordIdentifier>` so it shouldn't be coming through in the UI as Other Identifier.

**Comment by jlhardes** [comment]
Screenshot of UI attached:

![screen shot 2017-05-18 at 1 11 22 pm](https://cloud.githubusercontent.com/assets/3440166/26214874/00e4de3c-3bcc-11e7-9bd7-6c4a2c360026.png)

And screenshot of MODS XML:

![screen shot 2017-05-18 at 1 16 56 pm](https://cloud.githubusercontent.com/assets/3440166/26214949/57d017d4-3bcc-11e7-8263-1edc18845136.png)

**Comment by davidschober** [comment]
Thanks! @jlhardes I'll move this to the top of "needs refinement". Does someone want to take a crack at pointing it so we can get it quickly to ready? Developers feel free to discuss and point so we can move it to ready.

**Comment by bkeese** [comment]
@jlhardes The issue appears to be that we're using the MODS recordInfo/recordIdentifer to store both bibliographic_ids and now another recordIdentifier with source=Fedora4. 
The UI includes bibliographic_ids in the list of Other Identifiers.
We can exclude recordIdentifiers with source=Fedora4 from the bibliographic_id list. That would keep it from showing up in the UI as one of the other identifiers.
Will that work?

**Comment by jlhardes** [comment]
@bkeese that sounds great!
