### ISSUE TITLE
Shibboleth Support in Avalon AWS

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1942]
### Description
We'll need to be able to support shibboleth authentication for users running Avalon in the cloud. This is due to Avalon running on a different domain (lyrasis.net or something similar, for example) than what an institutions SSO would be using.

### Done Looks Like
- Avalon in AWS can use Shibboleth as a means of authentication
- Allow users to initialize a configuration for Shibboleth

child of https://github.com/avalonmediasystem/avalon/issues/3230

child of https://github.com/avalonmediasystem/avalon/issues/3230

#### Note
Michael said it could be done.

**Comment by phuongdh** [comment]
No longer relevant
