### ISSUE TITLE
As a user, I want to be able to add all tracks of a CD to a playlist at once

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1943]
### So that 
I don't have to add track by track.

### Items for Discussion
- Should this happen via some action on the Media Object page, like a helper button?
- Should this be per-section or per-media object?
- Should this also be available in _bulk actions_?

### Done looks like
-  A user has the ability to add all segments of a section to a playlist in one step. 
- The structural metadata is used to inform the clip sizes and names of playlist items.
- Per discussion: 07/27 The scope of this is **ONLY** for a top-level "add all" link. 
- The "add to" interface should be similar functionally to the current add to playlist.

**Comment by joncameron** [comment]
Chris suggests adding an element that's right-aligned and that captures each node.

**Comment by davidschober** [comment]
To simplify things we might want to add the entire item with a single link. 

Chris: We need to think about very large items (as an edge case)

**Comment by joncameron** [comment]
Please feel free to attach ideas and designs to this issue.

**Comment by davidschober** [comment]
Brian: One on entire item, one on each section.

**Comment by davidschober** [comment]
Everyone that has an interface idea, take a crack at it.

**Comment by phuongdh** [comment]
Second Brian's idea

**Comment by joncameron** [comment]
Defining titles which for playlist items pulled from structural metadata need to be defined further.
