### ISSUE TITLE
Investigate Player API Usable on iFrames with Redirect URLs

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1945]
### Description
As a developer, I want to use the Avalon Player API on embedded content where the iframe source is a redirect URL.

### So That
The embedded player can be controlled with the Avalon Player API. 

Configuring Avalon to assign a permanent URL (e.g. PURL or Handle) is a standard feature many implementers use to refer to objects so references aren't lost in namespace changes for PIDs—for example, in migrating from Avalon 5 (Fedora 3 PIDs) to Avalon 6 (Fedora 4 NOIDs). Because content embedding uses these permanent URLs by default if available, these URLs should be able to be used in iFrames for embedding purposes, and also need to be able to be controlled with the Player API. 

### Currently
This is the message I'm getting in the console for a PURL embed: "Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://purl.dlib.indiana.edu’) does not match the recipient window’s origin (‘https://media.dlib.indiana.edu’)."

### Done Looks Like
The Player API can control embedded content even if the iframe source is a redirect. Options are considered to make this happen best and the API is changed accordingly or a guide to enabling this for implementers is made available (for CORS or something similar if it fixes the issue).

**Comment by bkeese** [comment]
This already works. The API client just needs to send the correct (non-PURL) domain. The wiki document for the Player API has been updated to reflect this.
