### ISSUE TITLE
Update Known Issues Page for Avalon 6.1

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1947]
### Description
As a user, I want to know what bugs or unexpected behaviors are present in Avalon's latest release.

The Avalon [Known Issues](https://wiki.dlib.indiana.edu/display/VarVideo/Known+Issues) documentation lists issues within the application that users should be aware of. This page needs to be updated for each major or minor version release.

### Done Looks Like
- Relevant known issues for release 6.1 are listed (including those which have Github issues referring to them)
- Issues no longer applicable for the 6.1 release are removed

**Comment by davidschober** [comment]
Reviewed.
