### ISSUE TITLE
Update testing scratch pad

### ISSUE THREAD

**Issue by jenyoung** [avalonmediasystem/avalon#1949]
Changes to the testing scratch pad:

**Server Info Tab:**

Report bugs here:  https://bugs.dlib.indiana.edu/browse/VOV-4850 -- Should it be https://github.comn/avalonmediasystem/avalon/issues ?

**Full Script Tab**
Different test batches for NU & Indiana? - NU refers to old server on Server Info tab, Step 5 on Fulls script refers to Google Drive tar.gz file

**Comment by davidschober** [comment]
Let's try to keep everything as generic as possible, we can create diffs for NU/IU as part of each team's internal docs.

**Comment by bkeese** [comment]
This is no longer relevant, right?

**Comment by joncameron** [comment]
Yep, closing in favor of a new QA process which I'll email about soon.
