### ISSUE TITLE
Investigate what to do with Other Identifiers information

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1950]
This breaks out #1837 (What to do with bib import records)

We think we have to deal with "other identifiers differently. In order to keep moving, we broke this out to deal with it separately.

### Description
Other Identifiers should not be overwritten during a bib import action. Items added to Avalon (in batch or migration) sometimes will have local identifiers that are not part of a bibliographic record. When a bib record is then imported, those identifiers need to remain.

### Done Looks Like
- Bib import does not clear Other Identifiers
- Warning message on bib import should explain that saying, "Note: this will replace all metadata except for Other Identifiers."
- Other Identifiers list is de-duplicated so same identifier with same type is not listed multiple times.
- Bib ID used for bib import is added to Other Identifiers and replaces any Bib ID that is already listed in Other Identifiers (Bib ID list in Other Identifiers doesn't grow but is updated).

**Comment by davidschober** [comment]
@jlhardes and @jenyoung can you two take a look at this and describe it a bit more fully some time next week?

**Comment by jlhardes** [comment]
This issue is for trying to remember why we needed to not overwrite the Other Identifiers fields in the Resource Description Form when it is saved. We specifically made this change for a reason connected to the bib import functionality but we don't know if this feature is still necessary or not.

**Comment by mcwhitaker** [comment]
@jlhardes Is this a task for metadata experts or developers?

**Comment by jlhardes** [comment]
I added that comment so when @jenyoung and I come back to it we know what this is about. We'll task it next week.

**Comment by jlhardes** [comment]
I searched through all Github issues and the older VOV issues in Jira and cannot locate anything that explains why we decided the Other Identifiers field shouldn't be overwritten when a new bib import is run in the Resource Description Form.

There is https://bugs.dlib.indiana.edu/browse/VOV-4004 that resolved a bug where format was overwritten with a new bib import and messing with the moving image/audio thumbnail and format facet but that format information that Avalon stores was separated from the MODS XML so that isn't connected to the Other Identifier field.

**Comment by jlhardes** [comment]
After team discussion, determined reasons for not overwriting Other Identifiers: Variations and MDPI connection - identifiers (group id and MDPI barcode, Variations identifiers that are not in MARC record) that are added and then bib import is done, don't want to lose identifiers

Need to make sure bib import identifier is copied to Other Identifier

Need to deduplicate Other Identifiers

If different bib import identifier is used for new bib import, remove old bib import identifier from Other Identifiers list.

**Comment by jlhardes** [comment]
@joncameron @davidschober - We think this might be done, at least the work in the last comment? Is there more that needs to happen?

**Comment by joncameron** [comment]
This is done—the change has been implemented according to Julie's comment at the end. This would be good to have documentation for in the wiki.
