### ISSUE TITLE
Standardize User-facing System Messages

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1951]
### Description
As a user, I want to have the same message informing me of an error, warning or confirmation prompt.

### Done Looks Like
Create a mapping object that keeps track of standardized error message text.

### Images of Current Warning and Error Messages
![26893840-98e3b316-4b8a-11e7-86e9-199b20a0a625-2](https://user-images.githubusercontent.com/1406618/26992049-e73f81ba-4d2a-11e7-8626-f1b296624091.png)

### Reference
#2022

**Comment by cjcolvar** [comment]
We should take the opportunity to actually use i18n support in Rails through the locale file for this.  This locale file will be less daunting to edit by non-devs.  See http://guides.rubyonrails.org/i18n.html.

**Comment by joncameron** [comment]
We'll take a look at this in the future for Avalon 7.
