### ISSUE TITLE
Uploading A Caption File in Invalid Format Returns Error

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1952]
### Done looks like:
 * Flash message is displayed instead of an error page.
### Tasks:
- [x] Isolate and fix

**Comment by mcwhitaker** [comment]
@cjcolvar I think this needs more work. I am getting the flash message even when a provide a valid vtt file (the lunchroom vtt that @Karthikeya212 posted on slack yesterday for Jen).

I am not doing a batch ingest, so I am assuming that the name of the file does not matter as long as it has the .vtt extension and is in the correct format. But trying with a file that has the same name as the mp4 file with the added .vtt extension also did not work.

Another annoying thing is that the flash message is not getting cleared once I click on the + icon again to try again, so I end up not knowing if the flash message is for my new attempt or still refers to the prior attempt.

**Comment by cjcolvar** [comment]
@mcwhitaker This is ready for re-review on spruce.

**Comment by Karthikeya212** [comment]
The invalid file handling is working for me

**Comment by mcwhitaker** [comment]
@cjcolvar I was able to upload a good file; an invalid file was gracefully rejected. Looks good.
