### ISSUE TITLE
Write documentation about indexed/faceted metadata

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#1963]
### Description
No information is available in Avalon documentation about what fields are indexed for searching and browsing.

### Done Looks Like: 
Avalon Collections Guide includes information about:
- What gets indexed (all Resource Description Form fields, section titles, etc)
- What's available as facets from index
- What is keyword searchable from index

**Comment by jenyoung** [comment]
solr info https://github.com/avalonmediasystem/avalon/blob/master/app/models/mods_behaviors.rb#L21-L91

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#95
