### ISSUE TITLE
User cannot delete a 100 section item from preview page

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1965]
### Descriptive summary
Server: mallorn.dlib.indiana.edu
Testing: Performance
Browser: Chrome(58.0.3029.110 (64-bit))
Flash version: 24.0.0.221
Operating System: Windows10
Issue: When tried to delete a 100 section item using the delete button present on the item preview page, the page is loading for around 30sec and the user is navigated to an error page and the operation is terminated.

### Expected behavior
The item gets deleted from the Avalon system.

### Actual behavior
The item is not getting deleted.

### Steps to reproduce the behavior
1. Login to mallorn system.
2. Add a 100 section item.
3. After the item is added navigate to the preview page of the item.
4. Click on the Delete button on that page to delete the item.
5. The page loads for some time and is navigated to a error page.
![delete 100 sec item issue_1](https://cloud.githubusercontent.com/assets/25850972/26592789/d452e4be-452f-11e7-87fb-396ce21ec51b.PNG)
6. Open a new tab after some time and browse for the item, it is not deleted (the delete operation might have been terminated).

### Related work

Link to related tickets or prior related work here.

**Comment by Karthikeya212** [comment]
Similar issue is seen with deleting individual sections as well. The user is navigated to an error page when he tries to delete a single section out of the 100 sections in the Manage Files page.

**Comment by Karthikeya212** [comment]
I have tried the same on spruce, it loaded for 20 to 30min and then threw a "Site Unreachable" error, but eventually the process didn't terminate and the item is deleted.

**Comment by cjcolvar** [comment]
The site unreachable probably came from a deploy to spruce due to a PR being merged.

**Comment by phuongdh** [comment]
- [ ] Move delete job to background.
- [ ] Reduce number of callbacks that update relationships.
