### ISSUE TITLE
Migration is not setting ebucore:width and ebucore:height on derivatives

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#1992]
The migration is looking in the wrong place for width and height in the encoding datastream for derivatives.  Instead of trying to set width and height separatly it is possible to read the value of `//video/resolution` from the datastream and set it on the derivative using `.resolution`.

**Comment by jlhardes** [comment]
Is there an RDF property for that? I don't see anything in EBUCore for resolution which I think is why we went with separate width and height.

**Comment by cjcolvar** [comment]
Right, this is a bug for the migration of derivative objects.  We have a helper method called `resolution` which splits apart a string like '1024x768' into width and height and sets those two EBUCore properties.  The issue is that the derivative's `encoding` datastream template included elements for width and height `//video/resolution/width` but in reality those weren't used and a resolution string combining the two was put into `//video/resolution` instead.  The migration was looking in the split apart xml elements instead of the resolution node.  The migration should look in both places to be safe.  But either way only setting EBUCore width and height on the migrated object.

**Comment by cjcolvar** [comment]
Verified working with migration to neon.
