### ISSUE TITLE
Standalone Media Player - Clicking on current structure link doesn't play structure link

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#1993]
### Description
In the standalone player, when clicking on a link in the structures section which is the currently playing link, the hash handler does not update and nothing happens

This is an issue in event handling, when a new manifest url is supplied, extra event listeners are added which pile up and cause timing errors in console.  

Need to find a better way to handle event delegation when loading multiple players from different canvases.

### Done Looks Like
- Clicking any section link in the UI will play from beginning of that section link's start time.

### Tasks

**Comment by davidschober** [comment]
fixed a while ago
