### ISSUE TITLE
UX: Styling adjustments for "Sign in" link

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2009]
### Observations
1. The “>>” has no specific meaning.
2. The yellow box adds too much contrast; was it added because people did not see the “sign in” link? The IU sites don’t have that and users find it easily.

### Screenshots
![image](https://user-images.githubusercontent.com/25850972/26890896-2d9d2528-4b81-11e7-843c-302651aa5704.png)

**Comment by joncameron** [comment]
Also changed already.
