### ISSUE TITLE
UX: Search bar with no clickable buttons

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2010]
### Observations
1. Search bar has no clickable buttons to trigger the search, user has to rely only on ENTER button from keyboard.

### Screenshots
![image](https://user-images.githubusercontent.com/25850972/26891166-156ab6d6-4b82-11e7-88f2-119eab1ee373.png)

**Comment by joncameron** [comment]
This was done a while ago.
