### ISSUE TITLE
UX: Limit the text or eliminate description column from my collections table

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2015]
### Observations
1. My Collections table displays description for every collections, because of which some collections occupy very large row height in the table resulting in increased table length.
Instead the description field could be removed and let user to go to the collection and read it or the text displayed in the table could be limited and displayed in a tool-tip on hovering. 

### Screenshots
![image](https://user-images.githubusercontent.com/25850972/26892842-944c9ab4-4b87-11e7-9593-ed7bf8beabe0.png)

**Comment by Dananji** [comment]
Fixed in #3527
