### ISSUE TITLE
UX: Audio and StreamQuality strips overlap on their icons

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2018]
### Observations
1. The Audio and StreamQuality icons when clicked opens their respective action strips to perform the action, these strips are overlapping a bit on the icons.

### Screenshots
![image](https://user-images.githubusercontent.com/25850972/26893384-1eec424a-4b89-11e7-90ac-811e109437a3.png)

**Comment by joncameron** [comment]
Old ticket; this is also no longer an issue (no overlap of elements in our current MediaElement).
