### ISSUE TITLE
UX: Improving exception handling

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2021]
### Observations
1. In some areas, such as uploaded file type mismatch, if an error occurs that user will be navigated to an error page with no instruction on what to do next.
It would be better if the issue is pointed out at the same location, or at least instructions for the user when navigated to an error page on what is the next step of action.

### Screenshots
![image](https://user-images.githubusercontent.com/25850972/26893697-117950f2-4b8a-11e7-8ed7-eb8ec9541a6f.png)

### Done Looks Like
- Help text which is friendlier than the Rails stock page
- Provide link to help form, website etc. (configurable, maybe in avalon.yml?)

**Comment by cjcolvar** [comment]
When ever this appears, we should fix the underlying code issue for why this error appears.  We could create our own 500 error page but I don't think we'll be able to provide any more meaningful text than something went wrong and here's the place to contact for help.

**Comment by mcwhitaker** [comment]
@cjcolvar Agree with the need to fix the underlying error and other parts of the suggestion.

I believe that the UX issue is that from this page there is no possible action. If there were at least the option of going back to the home page, it would already be better than it is today.

**Comment by joncameron** [comment]
- Present the user a way to submit a help request
- Present options to the user, possibly a link back to the home page

**Comment by joncameron** [comment]
cjcolvar noted to me that https://github.com/avalonmediasystem/avalon/pull/2085/files is the general pattern that will be tweaked for implementation of the updated error page.

**Comment by davidschober** [comment]
We should make a default 500.

**Comment by Dananji** [comment]
Worked on #4800
