### ISSUE TITLE
UX: Inconsistent wording in confirmation messages in various parts of the application

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2022]
### Observations
1. It would be better to maintain a common styling format and common wording for all the similar types of operations performed over the application.

### Screenshots
![image](https://user-images.githubusercontent.com/25850972/26893840-98e3b316-4b8a-11e7-86e9-199b20a0a625.png)

**Comment by cjcolvar** [comment]
@avalonmediasystem/product-owners Same as of #1951?

**Comment by joncameron** [comment]
@cjcolvar Yep. I'll close this and move the examples over to #1951 to start fleshing it out.
