### ISSUE TITLE
UX: Date Validation

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2023]
### Observations
1. Date validation missing for Creation Date and Publication date (except the string validation).

### Screenshots
![image](https://user-images.githubusercontent.com/25850972/26893880-bbbceed4-4b8a-11e7-9b78-c690f4c74a0d.png)

**Comment by joncameron** [comment]
We'll have @metadataists join the conversation for work on this issue.

**Comment by jlhardes** [comment]
I'm not sure what semantically vs syntactically means here. Are we thinking of validation to decide if the publication date is actually the publication date or if the creation date is actually the creation date?

**Comment by mcwhitaker** [comment]
@jlhardes Say the year is 0000. This is syntactically correct, but does not make sense. Say the publication date is 2300; this, too, is syntactically correct, but semantically incorrect. These are some examples.

**Comment by jlhardes** [comment]
OK, thanks. My head wasn't going there with "semantic." I'm not sure it's a good idea to put limits on the date ranges we think are acceptable. Even for future dates there could be a reason to populate a date with a future date that hasn't occurred yet. If dates are really wrong, collections managers can use the facets to easily see those dates. If a whole set of items got the wrong dates on them then we need a batch update mechanism to help correct those. As long as it is syntactically a correct date, I recommend that is all the validating that we do. I don't know if we should consider 0000 a syntactically correct date, though.

**Comment by mcwhitaker** [comment]
@jlhardes What should be the syntax for the year in your opinion, if not 4 digits?

**Comment by jlhardes** [comment]
Dates should follow EDTF (http://www.loc.gov/standards/datetime/pre-submission.html) - we already have that set. What I am not sure about is if the literal year 0000 is an accurate date to use or not. EDTF doesn't get into that in the spec.

**Comment by mcwhitaker** [comment]
@jlhardes It shows that in the first example of the table in section 7:

![image](https://user-images.githubusercontent.com/16720883/27450799-ecc01674-575a-11e7-990d-2c9e33f6d796.png)

So it even accepts negative years...

**Comment by jlhardes** [comment]
Awesome, I missed that! So 0000 is a valid year! OK, so as long as the syntax matches a good date according to EDTF, I don't think we should restrict the date ranges for validation.

**Comment by joncameron** [comment]
Closing this since per Julie's comment, there's no need to do additional checks on date values beyond what should be bound by the spec.
