### ISSUE TITLE
Actions performed using player controls (thumbnail/scrubber/add-to-playlist) are not visible in full-screen mode

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2024]
### Observations
We should:
 1.) Hide the player controllers that bring up modal pages (playlist, thumbnail) when in full screen mode; or 
2.) Exit full screen mode when user clicks on them (the operations initiated by these controls hidden from the user in full screen mode). 
3.) A third option, which seems harder, would be to unhide the modal pages even when in full screen mode.

### Done Looks Like
- When a user clicks on a player controller in full screen mode, full screen mode exits.

### Tasks
- [ ] In the new MediaElement4 player, set up a click event handler for specified controls when in full screen mode. 
- [ ] Handle the event either by simply exiting full screen mode, or continuing to execute the clicked control.

**Comment by joncameron** [comment]
The second option is what the general consensus is on the best choice.

**Comment by adamjarling** [comment]
@joncameron Do we want to execute the clicked control mentioned in Tasks above after exiting full scree mode, or just simply exit full screen mode and be done?

**Comment by mcwhitaker** [comment]
@adamjarling  would it be too difficult to exit full screen and move on to execute the clicked control? From the user perspective, this is better because they tell the system one single time what they want instead of having to tell it twice.

**Comment by adamjarling** [comment]
@mcwhitaker I'm pretty sure we can make this happen.  The tricky part may be getting the timing right, depending if there's some type of callback function we could hook into exiting full screen mode.  We'll aim for that behavior in this ticket when pointing.

**Comment by joncameron** [comment]
@adamjarling I'll echo what Maria said above. If for some reason we can't make it happen or it's too much of a time sink to implement correctly, I'm fine with simply exiting full screen mode and having the user click again on the control.

**Comment by bkeese** [comment]
In each relevant button click handler, start with something like:
```if (player.isFullScreen) { player.exitFullScreen(); }```
Then proceed with the rest of the button click handler.
