### ISSUE TITLE
UX: Hyperlinking Collections and Items where their names appear to ease out navigation

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2025]
### Observations
1.“Collection >> Item” – Making the relationship terms links to the element they represent would reduce navigation effort.

### Screenshots
![image](https://user-images.githubusercontent.com/25850972/26894062-4bed697a-4b8b-11e7-84b3-f839b3ca2a75.png)

**Comment by joncameron** [comment]
Things that are able to be faceted (collections, units) could be hyperlinked, not only on the manage selected item page but also within the descriptive metadata on media objects.

**Comment by joncameron** [comment]
Breadcrumbs on pages for collection staff would lead to the admin pages for collections etc.
