### ISSUE TITLE
Accessing a deleted item shows unhelpful error

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2027]
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Exploratory
Browser: Chrome(56.0.2924.87 (64-bit)), checked on Firefox(50.0.2) as well
Flash version: 24.0.0.221
Operating System: Windows10

### Steps to reproduce the behavior
1. Login to spruce system
2. Add an item
3. Delete the item
4. Go back to the item

### Expected behavior
Page shows "Item invalid" or "This item doesn't exist or has been deleted"

### Actual behavior
When you go a deleted item, it shows "We're sorry, but something went wrong. If you are the application owner check the logs for more information."

### Example
https://mallorn.dlib.indiana.edu/media_objects/tb09j565c

### Tasks
- [ ] Handle Ldp:Gone response nicely
- [ ] Deploy and test

**Comment by joncameron** [comment]
I like "This item does not exist or has been deleted." as the error text.  This should ideally be displayed in the usual object view where the player and metadata would normally appear.
