### ISSUE TITLE
Embed Logins Don't Redirect Correctly

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2034]
### Description
Embedded players with content that is restricted don't gracefully handle the user clicking the 'sign in' button and passing that back to the player.

As a user, after authenticating I expect to go back to the location where I expect my content to be.

### Current Behavior Example
![jun-09-2017 09-34-04](https://user-images.githubusercontent.com/1406618/26977737-f1967b98-4cf6-11e7-84a2-bc34b28fac08.gif)

### Done Looks Like
- After the user authenticates in the pop-up browser window, the window closes and the content the user was trying to view appears

**Comment by cjcolvar** [comment]
I tested this using sodiuim and it appears fixed.

**Comment by Karthikeya212** [comment]
tested on sodium and spruce and is working fine
