### ISSUE TITLE
Documentation for Migration and Migration Report

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2036]
### Description
As a sysadmin migrating an Avalon instance to release 6, I want documentation about running the migration and regarding the migration report.

### Done Looks Like
- A wiki page is noted in this ticket (or created if necessary) to contain this information
- Documentation is written

### Notes
Especially as NU and IU have finished migration of r6 into production, documentation should be compiled and made available to other adopters.

**Comment by cjcolvar** [comment]
This documentation has been started here but may need some additions:
https://wiki.dlib.indiana.edu/display/VarVideo/Migration+Report+and+Results
It may need to be linked elsewhere besides this page: https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+5.1.6+to+Avalon+6.0

**Comment by joncameron** [comment]
We should provide a little collection manager info regarding the migration report. More work also needs to be done on the IU and NU migrations.

**Comment by jlhardes** [comment]
Also need to link this from the Avalon Collections Guide somehow so collection managers can find out it exists.

**Comment by cjcolvar** [comment]
Migration tool documentation written here: https://wiki.dlib.indiana.edu/display/VarVideo/Migration+Tool

**Comment by joncameron** [comment]
I'm working on a separate document for collection managers. We'll also have to note up front that this stuff is for Administrators and that interested Manager-level users will have to be elevation to check in on the Migration Report.
