### ISSUE TITLE
Remove bibimport overwrite warning when creating a new item

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#2039]
## Description

When creating a new item, using bibimport to populate the Resource Description is showing the recently created warning (#1837) about bibimport replacing data in all fields except Other Identifiers.

We do not want the warning in this situation.

### Note

Should we check if there are fields populated at all before issuing the warning? That would be a broader solution.

**Comment by joncameron** [comment]
Brian's current idea for a fix he may implement: "Checking for a blank title should be good enough, now that I think about it. Only records that are here for the first time won't have one."

**Comment by jlhardes** [comment]
On spruce: That fix seems to be in place and working that way. I created an item, used a valid catalog key for bib import, and didn't receive any warning message. I have also tried other bib imports after that initial bib import and receive the warning message.

If you remove the title and save, you have a record with an error message but it does save. Then using a new catalog key for import, you don't get any warning, it just replaces all fields and you end up with 2 catalog keys in Other Identifiers again. But you're making a bad record before the second bib import, so I think the total replacement and no warning and extra Other Identifiers is OK.

**Comment by mcwhitaker** [comment]
@joncameron @jlhardes Do you think we should save a record with no title (and an error message)? I would think we would fail to save when a required field is missing.

**Comment by cjcolvar** [comment]
@mcwhitaker I agree but that is a different issue that this one.  
Our workflow is such that we have to save objects missing required fields prior to getting to the resource description page.  But at that point we should require required fields prior to saving so this is a separate bug.

**Comment by jlhardes** [comment]
That seems like it might be a separate bug from this but those were the steps that I took and it seemed to save the record with no title and then gave me the error message about a missing title after it saved.

I just removed the title and saved on one of my records on spruce. You can see it in the Jules test collection (the title is now the F4 identifier, I think - 0v838057g).

**Comment by joncameron** [comment]
I've created https://github.com/avalonmediasystem/avalon/issues/2045 for this bug; this ticket can be closed out.

**Comment by mcwhitaker** [comment]
@cjcolvar I agree it is a separate bug. My point was to clarify the specs since @jlhardes comment seemed to imply that it was all right to save without a title.

**Comment by joncameron** [comment]
@avalonmediasystem/product-owners  Just testing to make sure I'm getting these @ messages...

**Comment by davidschober** [comment]
I got one
