### ISSUE TITLE
Media Objects Can Be Saved Without Required Fields (Title & Date)

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2045]
### Descriptive summary
Server: spruce.dlib.indiana.edu
Browser: Firefox 53
Operating System: macOS 10.11.6

### Issue
Media objects can be saved without a title or date, which are required fields—objects should not save if these are absent.

### Expected behavior
Save operations are not allowed if there is no value in the Title or Date fields of the Resource Description form.

### Actual behavior
![jun-09-2017 10-36-47](https://user-images.githubusercontent.com/1406618/26980255-97025978-4cff-11e7-9c63-334cce5b9a96.gif)
The record saves and the Fedora 4 ID becomes the Title.

### Steps to reproduce the behavior
1. Login to spruce.
2. Go to the resource description for a record, delete the Title or Date fields, and click Save
3. Warnings appear to the user (bark but no bite)
4. Go to the Preview/Object View and see that the Title and Date values are set

### Related work
Originally reported in #2039

**Comment by cjcolvar** [comment]
Issue seems to be here: https://github.com/avalonmediasystem/avalon-workflow/blob/master/lib/avalon/workflow/workflow_controller_behavior.rb#L66

This will be a little tricky since we need to make sure that saves on the manage files tab skip validation if the workflow hasn't progressed to resource description yet.

**Comment by mcwhitaker** [comment]
@Karthikeya212 - in the PR that @cjcolvar submitted, he said that his fix could affect ingest badly. Please make sure to test ingest as well as the data entry/save issue when this ticket is ready for QA.
