### ISSUE TITLE
Investigative dive into User Management for IMLS Grant

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2066]
### Description
The Lyrasis team needs an investigative dive into building/ finding an existing user management / authentication system for use with Avalon 6.x. The goal is to have a built in system that can:

+ Add Users
+ Deactivate/ Delete users
+ Modify Users
+ Stores basic information about the users (email, first name, last name, affiliation) 
+ Allows for 5- 20 users per institution ( scoped to Administrators/ Collection Managers)
+ Need a report before July 10 for a call with Lyrasis. The report can be a go/no go or scope of work

### Possible ideas

Use AWS directory services:
https://aws.amazon.com/directoryservice/?nc2=h_m1

Investigate Grouper:
https://github.com/samvera-labs/hydra-grouper 

### Done Looks Like
* Recommendations made about user management system to implement
* Draft of report started if possible within timebox

### Tasks
- [ ] Try AWS MS ActiveDirectory
- [ ] Try devise integration with MS AD

**Comment by davidschober** [comment]
@joncameron and @mcwhitaker We have to make this a priority for the next sprint cycle. I'll be out next week, can you make sure it gets into the sprint. This will have to be time boxed.

**Comment by mcwhitaker** [comment]
@davidschober Yes, Jon D spoke with me about it. We will add to the next sprint.

**Comment by davidschober** [comment]
Good news is,  it looks like there’s an AWS active directory, so we might be able to just have phoung/mbk verify that it works as expected with Avalon.

**Comment by phuongdh** [comment]
AWS Simple AD may work: http://docs.aws.amazon.com/directoryservice/latest/admin-guide/directory_simple_ad.html

**Comment by davidschober** [comment]
I wonder if we can set up a test instance as a show and tell.

**Comment by cjcolvar** [comment]
@avalonmediasystem/product-owners I think it would be helpful to talk over this story based upon the research @phuongdh and I did on Monday.  Could we do that early tomorrow?

@phuongdh did you have any more success with Simple AD?  Last we left it on Monday I thought we couldn't get ldap to work with it.  Maybe kerberos would work better? Or maybe MS AD?

**Comment by joncameron** [comment]
@cjcolvar Definitely, let's work it into backlog buddies tomorrow.

**Comment by davidschober** [comment]
agreed.

**Comment by phuongdh** [comment]
AWS AD requires a Windows instance to manage user/groups by using MS AD manager.  AWS Cognito would probably be overkill/too much work. We're leaning toward openLDAP options. @cjcolvar had some success with OpenLDAP and phpLDAPAdmin.

**Comment by phuongdh** [comment]
OpenLDAP bundle on AWS Marketplace for 1c/h https://aws.amazon.com/marketplace/pp/B00YQE6UGO

**Comment by davidschober** [comment]
Option 1: 

* Use OmniAuth Identity Gem as is. Users would self register.
* Users could be added to Avalon Groups for "affiliation"
* Users can not update password, etc
* Might be OK for a short pilot

Option 2: LDAP Server 

* Bring up ec2 instance with LDAP. 
* They configure whatever schema what they want (whatever fields). There's a PHP LDAP Admin  that you can add people with whatever fields. 
* AWS Marketplace has a EC2 instances with services preinstalled. <LINK NEEDED> which might be the easiest way to set this up. 
* They could nest, so only a single LDAP server is needed for all institutions. 
* Avalon's wiki page has an LDAP Example <LINK> We could write a how to. 
* There are lots of clients for LDAP 
* This solution would allow Lyrasis to authenticate against the same LDAP server for Hyrax/Hyku
* There is no robust way for user changing password, etc. 
* The Team favors this, because it's well-established, flexible and is known to work. It also is minimal work for our team, and the Lyrasis would find support from the Avalon User community. 

Option 3: Custom Work

* Minimum 2 - 4 Sprints @ 3 people (design, ops, dev)
* We would write a replacement for or team ommniauth identity to: 
  - create users
  - delete users
  - manage users
  - Change password/forget password

* We might look at devise, but that would require rolling back omniauth and losing LTI which would mean considerably more work. 
* If Devise worked fine with OmniAuth, it might be OK. 
* This seems like a considerable amount of work to undertake. The team is not confident in this approach. 


Option 4: AWS Cognito (https://aws.amazon.com/cognito/faqs/)

* Might be free (up to 50k monthly users)
* We would have to write custom stuff to work with it.
* If we could hit the service in the way we wanted to, it could be as low as 1 sprint-2 sprints 
* This seems interesting, because it seems low cost, and may be fairly easy to develop on
* We don't know how to manage users, but there's an interface. 
* We may still have to write the update password, etc, with calls to AWS.

**Comment by cjcolvar** [comment]
@davidschober I think we should bump option 4 up to 2-4 sprints similar to the option 3 given we might need to do some of the same custom work just wrapping Cognito.
