### ISSUE TITLE
Change "Create New Playlist" Link Color

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2068]
### Description
The current color is difficult to read—it's a dark blue against gray, which is not good for readability.

### Example Image
![screen shot 2017-06-29 at 9 14 25 am](https://user-images.githubusercontent.com/1406618/27689206-7e5648c4-5cab-11e7-876a-682e591027ce.png)

### Done Looks Like
A color with better contrast against the background is decided and CSS updated for the 'Create new playlist' link.

### Tasks
- [x] Update the CSS to target general links within this dropdown element.
- [x] Lighten up the link color.

**Comment by adamjarling** [comment]
This should be fixed now when rendering the MEJS4 player.  @davidschober  @joncameron Can you verify it's working on your end?

**Comment by joncameron** [comment]
@adamjarling @davidschober Yep, verified! I'm going to close this issue.
