### ISSUE TITLE
Our player is mediocre at buffering (6.01)

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2074]
This is a bit hard to replicate on university networks and perhaps as we do IIIF 3 and a new play this may not as relevant.  But try pulling down a really high quality stream and jumping around it.  I'm seeing a behavior where:

1.  I jump somewhere and get the spinning circle
1.  It starts playing, plays 3 to 5 seconds but then the buffer runs empty
1.  Rather than getting the spinning circle again to show buffering the screen goes black and the play icon comes up, which makes it seem kind of like an error rather than a buffer issue

**Comment by carrickr** [comment]
@davidschober This behavior what Nicole referenced in her June 26th email

**Comment by joncameron** [comment]
I'm closing this since we've made the decision to move to MediaElement 4.  @carrickr if this still comes up after the 6.3/ME Update release please go ahead and write a new ticket with the behavior.
