### ISSUE TITLE
Can't share unpublished embed code

### ISSUE THREAD

**Issue by lealeelu** [avalonmediasystem/avalon#2078]
We've found users trying to use embed code from before an item is published and without a purl. We should be encouraging them to publish and then use the purl embed in case we change the system in a later upgrade and the old urls don't work.

**Comment by cjcolvar** [comment]
How about we hide the share icon and link until the item is published?  That way the user can't even see the share urls until they are finalized upon publish.

**Comment by joncameron** [comment]
@cjcolvar I like that idea, and I think that would help make the distinction between published and unpublished. @davidschober what do you think?

**Comment by davidschober** [comment]
I like the idea of hiding the embed code.
