### ISSUE TITLE
Use S3-split-job for skip-transcoding in AWS

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2082]
### Description
Getting _skip transcoding_ to work in an AWS environment.

### Tasks
- [ ] Integrate S3-split-job with skip transcoding
- [ ] Consider adding queues/workers

**Comment by davidschober** [comment]
@phuongdh @mbklein is this issue abandoned? I remember a short discussion but can't remember how it turned out.

**Comment by davidschober** [comment]
@phuongdh and @mbklein  is this abandoned? If so, unpoint and close.
