### ISSUE TITLE
Editor is unable to edit collection information

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2083]
### Descriptive summary

Server: mco-staging.dlib.indiana.edu
Testing: Regression
Browser: Chrome(56.0.2924.87 (64-bit))
Operating System: Windows10
Issue: Editor is unable to edit the collection information.

### Steps to reproduce the behavior

1. Login to the sodium system with Manager credentials.
2. Create a collection and add an avalon user as editor to it.
![added editor](https://user-images.githubusercontent.com/25850972/27386607-5aff8716-5664-11e7-929f-d68defe81a9c.PNG)

3. Login to sodium system with Editor credentials.
4. Go to Manage Content and click on the collection.
5. Click on "Edit Collection Info" button, which opens a pop-up to edit the details. Modify some details and click on Update Collection button.
6. The system throws an "Unknown Item" error and the details are not updated in the collection.
![editor cannot edit collection](https://user-images.githubusercontent.com/25850972/27386758-c732ca4c-5664-11e7-829a-c7a049a7fbfc.PNG)

### Related work

Link to related tickets or prior related work here.

### Tasks
- [ ] Fix ability for admin collections to allow editors to edit.
- [ ] Write/update tests for this changed ability

**Comment by cjcolvar** [comment]
Verified and this is what the log says:
I, [2017-06-21T11:21:33.260477 #12090]  INFO -- : method=PATCH path=/admin/collections/m326m172d.json format=json controller=Admin::CollectionsController action=update status=500 error='ArgumentError: User xxx@xxx.xxx does not belong to the manager group.' duration=167.12 view=0.00 db=1.57 time=2017-06-21 11:21:33 -0400
F, [2017-06-21T11:21:33.261263 #12090] FATAL -- : 
ArgumentError (User xxx@xxx.xxx does not belong to the manager group.):
  app/models/admin/collection.rb:78:in `add_manager'
  app/models/admin/collection.rb:73:in `block in managers='
  app/models/admin/collection.rb:73:in `each'
  app/models/admin/collection.rb:73:in `managers='
  app/controllers/admin/collections_controller.rb:167:in `update'
  app/controllers/application_controller.rb:63:in `handle_api_request'

**Comment by joncameron** [comment]
My inclination is to just change the permissions matrix to indicate that an Editor cannot edit collection info. I don't see much of a use case for this to begin with.

**Comment by joncameron** [comment]
Closing as a stale, very minor bug.

**Comment by cjcolvar** [comment]
@joncameron Was the matrix ever updated for this change?  Can we remove it from the Known Issues as well since it has come to be expected behavior?

**Comment by joncameron** [comment]
I agree that it's become expected behavior and there has been no user feedback relative to this issue. I've updated the matrix and will remove this from the known issues list.
