### ISSUE TITLE
Depositor is unable to navigate to Preview page using Save and Continue button in Access Controls page

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2084]
### Descriptive summary

Server: mco-staging.dlib.indiana.edu
Testing: Regression
Browser: Chrome(56.0.2924.87 (64-bit))
Operating System: Windows10
Issue: Depositor is unable to navigate to Preview page using "Save and continue" button in Access Controls page

### Expected behavior
Though the Depositor do not have rights to modify anything on Access Control page, he wouldn't want to be restrict the navigation on that page when the "Save and continue" button is enabled

### Steps to reproduce the behavior

1. Login to the sodium system with Depositor credentials.
2. Create an item.
3. After reaching the Access Controls page Depositor cannot navigate to Preview page by clicking on Save and Continue button.
4. The only way to go to Preview page is by clicking the "Preview" link on the left side panel

### Related work

Link to related tickets or prior related work here.

**Comment by cjcolvar** [comment]
Verified as reproducible.  The Save and Save and Continue buttons never submit the form.  They do nothing so I think this is a UI issue.

**Comment by bkeese** [comment]
Fixed by https://github.com/avalonmediasystem/avalon/commit/acdd8be13ef6c16e514a4686fcf3c35cbb93c1e8#diff-ce186c576027b868f1791b932daa2be9
