### ISSUE TITLE
Thumbnail offset is set to 0 and are not generated For the video files in Batch Ingest Package in wiki

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2087]
### Descriptive summary

Server: mco-staging.dlib.indiana.edu
Testing: Regression
Browser: Chrome(56.0.2924.87 (64-bit))
Operating System: Windows10
Issue: Thumbnail offset is set to 0 and are not generated For the video files in Batch Ingest Package in wiki

### Expected behavior
Though the Depositor do not have rights to modify anything on Access Control page, he wouldn't want to be restrict the navigation on that page when the "Save and continue" button is enabled

### Steps to reproduce the behavior

1. Login to the sodium system.
2. Create an item and upload a video file from Batch Ingest package in wiki,
3. The thumbnail offset is set to 0.
4. After the video is trans-coded, go to preview and try to update the thumbnail, you can see that the icon is not working.

### Related work

Link to related tickets or prior related work here.

**Comment by cjcolvar** [comment]
I'm seeing this for other files as well when attached via upload or dropbox.
