### ISSUE TITLE
Display Loading Icon when RTMP Stream is Buffering

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2090]
Noticed on the NU AWS Instance:

The page will load and when profiled via wireshark the media itself will load within a tenth of a second.  However the duration on the player will remain 0:00 and the user will be unable to play the media for 6 to 15 seconds.  If the user gets frustrated and reloads the page, the entire cycle repeats including the delay.  Although if the user reloads after the stream is loaded they do not encounter this bug.

Regarding replication what is interesting is that:

- Carrick: Safari is instant load, Chrome and Firefox are slow
- Michael: Safari is the slowest
- Adam: Sees no significant lag in any browser

## First Pass Solution

Display a loading icon that remains on the player under the `done preloading` event fires.  The `received metadata` event fires twice which makes it trickier to use.

<img width="575" alt="screen shot 2017-06-21 at 11 06 29 am" src="https://user-images.githubusercontent.com/5350060/27438596-cab5e2c4-5733-11e7-9ab3-1a13734c8df8.png">

<img width="553" alt="screen shot 2017-06-21 at 11 08 12 am" src="https://user-images.githubusercontent.com/5350060/27438546-a2a2c8ce-5733-11e7-8e9e-18656c32a342.png">

## Long Term Solution

Ensure this doesn't crop up when we put the new player into Avalon (the IIIF 3.0 one).

**Comment by joncameron** [comment]
Low effort solution: just put splash text at the top of the screen telling users to be patient.

**Comment by davidschober** [comment]
@adamjarling did your loader get pushed upstream?

**Comment by adamjarling** [comment]
@davidschober Not yet. We just pushed the latest fix up yesterday.  What's the timing on pushing something like this upstream?   I'll need to do a little work to it to prepare for upstream.  Currently there are a few NU specific js behaviors built into the namespaced object which I should separate out.  We wanted to see how this fix held up yesterday, and I think so far so good.

**Comment by adamjarling** [comment]
@joncameron @davidschober To follow up on the discussion 6/30/2017 about potentially pulling this loader into core, it's my opinion that this loading spinner, although working for Northwestern's purpose, is not an ideal solution.  It does not hook into MediaElement events in the typical way.  

When initially putting together the loader, for some reason (without digging too far into Avalon's Mediaelement customizations), the typical 'buffer' or 'loaded' events which should fire when a video is ready were not able to be captured.   So we just went for a quick, lightweight, roundabout solution.  

When Mediaelement gets upgraded in Avalon and we re-write the Javascript integration, we could incorporate this custom loader (the UI work here), in a more standard, robust fashion.

**Comment by joncameron** [comment]
@davidschober I'm with Adam in that I'd prefer to wait and implement a better solution when mediaelement gets upgraded instead of spending time currently pushing it upstream.

**Comment by mcwhitaker** [comment]
@joncameron @davidschober That was actually the general consensus during our standup today.

**Comment by joncameron** [comment]
Closing this ticket—we'll create a new one when needed, as per the discussion above.
