### ISSUE TITLE
Fix Thumbnail Tool's Reliance on Posters

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2093]
### Description
Creating a thumbnail currently throws an error if a poster doesn't exist for an object. It should be more resilient when a poster doesn't exist, whether by informing the user or generating the poster if one is not already present.

### Done Looks Like
When a user clicks the 'create thumbnail' icon, the modal should pop up in the normal fashion even when a poster doesn't exist.

**Comment by davidschober** [comment]
This should be fixed when we add the thumbnail button ... adds the thumbnail button in ME 4 #1880

**Comment by joncameron** [comment]
Closing another stale, edge case bug.
