### ISSUE TITLE
Import Button Doesn't Trigger Event in Microsoft Browsers

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2094]
### Description
Clicking the "Import" button in the pop-up that occurs when performing bibimport on records with existing metadata doesn't trigger perform any action. See example gif below.

### Platforms
Microsoft IE 11 and Edge on media.dlib.indiana.edu, Avalon 6.1rcx

### Initial user report
I’m trying to import the finished bib record for vad8467 (IU Philharmonic Orchestra /  Strauss’s Alpine Symphony), and I get no response when I click "import."

### Secondary User Report
When you are editing the resource description for an item, if you click to import, in the bibliographic id area, nothing happens.  In the gui, the button appears to be pressed but it does not appear that anything is trying to load.
we have tried on a few different computer.  we have tried with a few different id types, we have tired different users and different audio only items.

### Example
![jun-22-2017 14-38-55](https://user-images.githubusercontent.com/1406618/27450163-bbe8833a-5758-11e7-92c6-695d4aac4549.gif)

**Comment by mcwhitaker** [comment]
I was able to reproduce this in spruce. Also, the "No, Cancel" button works.

**Comment by cjcolvar** [comment]
This has been tested on sodium, but should be retested on spruce.
