### ISSUE TITLE
Embed title should link to master file instead of media object using permalink if available

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2096]
### Description/Current Behavior
The embedded player displays a video title in the upper left of the player.  The title is the section's title, but it links to the media object instead of the section.  The link should be the permalink if available.  The link is currently hard to see on spruce because its color is about the same as the background.

### Done Looks Like
Section title hyperlink in the embedded player is set to a PURL for the section that is embedded, or set to the standard non-PURL URL if a PURL is not available.

### Tasks
- [ ]  Edit link generating code to use the correct URL.

**Comment by cjcolvar** [comment]
This story is bigger now because it will also encompass making this plugin work with the MEJS4 player.  I hope to finish it in a 3 and have adjusted the size accordingly.

**Comment by joncameron** [comment]
The embedded player link is now directing to the section rather than object; looks good! I haven't tested the permalink portion but if tests are passing I feel comfortable closing this out and opening another as needed.
