### ISSUE TITLE
Ensure google Analytics is wired up

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2097]
https://analytics.google.com/analytics/web/#report/visitors-overview/a797260w88118607p91492725/

Google analytics needs to be wired up. 

Use the same AVR account for now.

**Comment by joncameron** [comment]
@davidschober @carrickr Is this an NU issue that fell into the core board?

**Comment by davidschober** [comment]
looks like it. odd. sorry.
