### ISSUE TITLE
Unneccessary Forward Slash in Batch Ingest Report Email

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2100]
### Description
Every report email sent by Avalon to the user specified by email address in a batch ingest manifest shows a forward slash followed by a newline.

### Environment
Spruce on 6.x, Media.dlib.indiana.edu on 6.1rcx
Firefox 54 on macOS 10.11.6

### Example Screenshots
---
![screen shot 2017-06-26 at 11 53 18 am](https://user-images.githubusercontent.com/1406618/27548219-4f2276f0-5a66-11e7-876e-85ec8be833ff.png)

---
![screen shot 2017-06-26 at 11 53 07 am](https://user-images.githubusercontent.com/1406618/27548223-52478442-5a66-11e7-9cfe-a19ac928300c.png)

---
![screen shot 2017-06-26 at 11 53 26 am](https://user-images.githubusercontent.com/1406618/27548217-4c91434e-5a66-11e7-8e60-c67664a17c22.png)

### Expected Behavior/Done Looks Like
There is no weirdo "\/\n"  text at the top of the email from Avalon for batch ingest.

**Comment by davidschober** [comment]
related to #2145
