### ISSUE TITLE
Batch Ingest Status Email Contains Raw CSS Text

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2101]
### Description
The batch ingest status email that contains information upon a successful ingest doesn't look right—it has CSS code littered at the bottom. 

### Environment
Spruce, 6.x
Outlook 2016 on macOS 10.11.6

### Expected Behavior
The CSS styling in the email should be valid and applied to the HTML, as well as not visible to the user as text.

### Example Screenshot
![screen shot 2017-06-26 at 12 06 53 pm](https://user-images.githubusercontent.com/1406618/27548915-6df2cef2-5a68-11e7-9228-20ccd352ab05.png)

**Comment by davidschober** [comment]
related to #2145
