### ISSUE TITLE
User is not navigated to home page in case of invalid credentials

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2102]
### Descriptive summary

Server: mallorn.dlib.indiana.edu
Testing: Regression
Browser: Chrome(56.0.2924.87 (64-bit))
Operating System: Windows10
Issue: User is not navigated to home page in case of invalid credentials

### Expected behavior
User should be navigated to the home page with error message saying about the invalid credentials

### Actual behavior
User is navigated to a blank page with a message saying "Not found. Authentication passthru."

### Steps to reproduce the behavior

1. Open mallorn home page.
2. Try to login with invalid credentials.
3. User is navigated to a blank page with a message saying "Not found. Authentication passthru."
![image](https://user-images.githubusercontent.com/25850972/27550729-c9f10e48-5a6e-11e7-8871-f5d066f94074.png)

4. Click on browser back button, now it will display the error message.
![image](https://user-images.githubusercontent.com/25850972/27550763-e710eb4c-5a6e-11e7-84ba-bec7c52184ca.png)

### Related work

Link to related tickets or prior related work here.

### Tasks
- [ ] Check authentication configuration on mallorn, since it is using default Devise auth, and fix it.

**Comment by davidschober** [comment]
This is related to the fix for embed.  #2034, #2059, #2108

It may have broken this.

**Comment by davidschober** [comment]
This should redirect to the login

**Comment by bkeese** [comment]
There is an error happening here:
https://github.com/avalonmediasystem/avalon/blob/develop/app/controllers/users/omniauth_callbacks_controller.rb#L22

 ActionView::MissingTemplate: Missing template modules/identity_auth_form

I can't find where this template is supposed to be found.

**Comment by cjcolvar** [comment]
@bkeese Is that rescue on line 23 not happening or does `super` not do the right thing?

**Comment by bkeese** [comment]
Rescue happens. Apparently super doesn't do the right thing.



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by Karthikeya212** [comment]
Tested with Spruce on browsers Chrome (63), Firefox (57), Edge (40), IE (11), Safari (9.1) on Windows-10 and Mac Sierra.
