### ISSUE TITLE
Batch Ingest Fails On Valid MARC XML with "Language Not Recognized" Error

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2116]
### Description
Batch ingest manifest manifest fails items at the bibimport stage with the message seen in the screen shot attached when a valid MARC value is present. See Julie's original comment below for more information.

#### Error Email Received 
![image](https://user-images.githubusercontent.com/1406618/27742463-b8aa38f6-5d86-11e7-833f-06efb88067cb.png)

#### Manifest File Triggering the Error
[IULMIA_VSS_Migration_Manifest.xlsx](https://github.com/avalonmediasystem/avalon/files/1115713/IULMIA_VSS_Migration_Manifest.xlsx)

### Original Comment from Julie
Checking out what we have happening in the XSL for bib import, we are looking first at the value in position 35-37 of the 008 field for what is returned in the MARCXML. In both of these examples, there are 3 pipes (|||) in that position. After that check in the XSL, we're looking in 041 which doesn't exist in either of these records.

There does appear to be a case to use 3 pipes (|||) for language in the 008 when there is no attempt to code the language. Both the concise information and the full information on the MARC site for 008 specify this for language info in position 35-37 (concise: https://www.loc.gov/marc/bibliographic/concise/bd008a.html and full: https://www.loc.gov/marc/bibliographic/bd008a.html).

So it looks like we need a catch in the XSL to drop language if 3 pipes is the value in 008/35-37 or allow that value in MCO as a "no information provided" scenario (equivalent to '###') so it translates to "there is no language info."

Do we want this check added to the XSL or handled elsewhere? 

### Related 
Original Issue on IU's Production Board: https://bugs.dlib.indiana.edu/browse/VOV-5491
PR: https://github.com/avalonmediasystem/avalon/pull/2117

**Comment by joncameron** [comment]
MARC XML from an item that triggers this error:
`
<?xml version="1.0"?>
<zs:searchRetrieveResponse xmlns:zs="http://www.loc.gov/zing/srw/"><zs:version>1.1</zs:version><zs:numberOfRecords>1</zs:numberOfRecords><zs:records><zs:record><zs:recordSchema>info:srw/schema/1/marcxml-v1.1</zs:recordSchema><zs:recordPacking>xml</zs:recordPacking><zs:recordData><record xmlns="http://www.loc.gov/MARC21/slim">
  <leader>01272ngm a2200301Ka 4500</leader>
  <controlfield tag="007">mr|maaadu||r</controlfield>
  <controlfield tag="008">040608s1969||||xx 111 g          ml||| d</controlfield>
  <datafield tag="099" ind1=" " ind2=" ">
    <subfield code="a">BR1217</subfield>
  </datafield>
  <datafield tag="245" ind1="0" ind2="0">
    <subfield code="a">If..</subfield>
    <subfield code="h">[motion picture] /</subfield>
    <subfield code="c">Memorial Enterprises.</subfield>
  </datafield>
  <datafield tag="260" ind1=" " ind2=" ">
    <subfield code="a">[S.l. :</subfield>
    <subfield code="b">s.n.],</subfield>
    <subfield code="c">1969.</subfield>
  </datafield>
  <datafield tag="300" ind1=" " ind2=" ">
    <subfield code="a">3 film reels (111 min.) :</subfield>
    <subfield code="b">sd., col./b&amp;w ;</subfield>
    <subfield code="c">16mm.</subfield>
    <subfield code="3">ref. print</subfield>
  </datafield>
  <datafield tag="508" ind1=" " ind2=" ">
    <subfield code="a">Michael Medwin (producer); Lindsay Anderson (producer); Lindsay Anderson (director); Miroslav Ondricek (photographer).</subfield>
  </datafield>
  <datafield tag="511" ind1="1" ind2=" ">
    <subfield code="a">Malcolm McDowell, David Wood, Richard Warwick, Christine Noonan.</subfield>
  </datafield>
  <datafield tag="590" ind1=" " ind2=" ">
    <subfield code="a">Gift to the Lilly Library from the David Bradley film collection.</subfield>
  </datafield>
  <datafield tag="590" ind1=" " ind2=" ">
    <subfield code="a">Vinegar syndrome poor; shrinkage .1-.5%; faded.</subfield>
  </datafield>
  <datafield tag="591" ind1=" " ind2=" ">
    <subfield code="a">B-ALF: Bradley Estate May 2002</subfield>
  </datafield>
  <datafield tag="700" ind1="1" ind2=" ">
    <subfield code="a">Bradley, David,</subfield>
    <subfield code="d">1920-1997,</subfield>
    <subfield code="e">former owner.</subfield>
    <subfield code="5">InU</subfield>
  </datafield>
  <datafield tag="700" ind1="1" ind2=" ">
    <subfield code="a">Medwin, Michael,</subfield>
    <subfield code="d">1923-</subfield>
  </datafield>
  <datafield tag="700" ind1="1" ind2=" ">
    <subfield code="a">Anderson, Lindsay,</subfield>
    <subfield code="d">1923-1994</subfield>
  </datafield>
  <datafield tag="700" ind1="1" ind2=" ">
    <subfield code="a">McDowell, Malcolm,</subfield>
    <subfield code="d">1943-</subfield>
  </datafield>
  <datafield tag="700" ind1="1" ind2=" ">
    <subfield code="a">Wood, David.</subfield>
  </datafield>
  <datafield tag="700" ind1="1" ind2=" ">
    <subfield code="a">Warwick, Richard,</subfield>
    <subfield code="d">1945-1997</subfield>
  </datafield>
  <datafield tag="700" ind1="1" ind2=" ">
    <subfield code="a">Noonan, Christine.</subfield>
  </datafield>
  <datafield tag="710" ind1="2" ind2=" ">
    <subfield code="a">Memorial Enterprises.</subfield>
  </datafield>
  <datafield tag="596" ind1=" " ind2=" ">
    <subfield code="a">5</subfield>
  </datafield>
  <datafield tag="926" ind1=" " ind2=" ">
    <subfield code="a">B-ALF</subfield>
    <subfield code="b">_ALFBRAD</subfield>
    <subfield code="c">BR1217 Reel 1 of 3</subfield>
    <subfield code="d">NONCIRC</subfield>
    <subfield code="f">1</subfield>
  </datafield>
  <datafield tag="926" ind1=" " ind2=" ">
    <subfield code="a">B-ALF</subfield>
    <subfield code="b">_ALFBRAD</subfield>
    <subfield code="c">BR1217 Reel 2 of 3</subfield>
    <subfield code="d">NONCIRC</subfield>
    <subfield code="f">1</subfield>
  </datafield>
  <datafield tag="926" ind1=" " ind2=" ">
    <subfield code="a">B-ALF</subfield>
    <subfield code="b">MESSAGE</subfield>
    <subfield code="c">BR1217 Reel 3 of 3</subfield>
    <subfield code="d">NONCIRC</subfield>
    <subfield code="e">NEVER</subfield>
    <subfield code="f">1</subfield>
  </datafield>
</record></zs:recordData><zs:recordPosition>1</zs:recordPosition></zs:record></zs:records></zs:searchRetrieveResponse>
`

**Comment by jlhardes** [comment]
There is a variable created for the language code that replaces | and # with nothing and then that variable is checked to see if it has a value before the language code from the 008 is used in the MODS element. I made a change to that variable previously to try and also prevent 'N/A' from coming through (an old cataloging practice). That change didn't remove that string but was a check that the variable value didn't equal that string when creating the variable. So that turned the variable into a true/false value and didn't work to make the variable an empty string when it was supposed to be empty. I switched out that 'N/A' check to be a replace() function so now that variable is empty if the language code is '|||', '###', or 'N/A'.

**Comment by cjcolvar** [comment]
This appears to be fixed on spruce since I can import 5799342 which is the record above which was failing before.

**Comment by jlhardes** [comment]
Just to complete what was actually changed. The replace() function didn't work because the XSL version has to 1.0 and the replace() function is only available in 2.0. So the variable is constructed now to translate | and # to an empty string (as before) and each time the language code is needed there is a check to make sure the variable is not 'N/A' and that it is also not an empty string before it is called up.
