### ISSUE TITLE
Getting permalink dns error on published items when the item contains sections of different sections

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2120]
### Descriptive summary

Server: mallorn.dlib.indiana.edu
Testing: Regression
Browser: Chrome(56.0.2924.87 (64-bit))
Operating System: Windows10
Issue: Getting permalink dns errors on published items when the item contains sections of different sections

### Steps to reproduce the behavior

1. Create an item with an audio and a video section.
2. Assign lease for an avalon user for that item and publish the item.
3. Try to access that item from Avalon users accout, first sections plays well.
4. For the next section it is giving an "un-resolvable dns" error.
![image](https://user-images.githubusercontent.com/25850972/27764891-96e8e64e-5e72-11e7-9782-82ae731cf2b7.png)

5. But the collection staff can access without any problem.
6. Unpublish the item, now this is error is seen even for the collections staff, and is mostly coming for the section that contains video file.

### Related work

Link to related tickets or prior related work here.

**Comment by cjcolvar** [comment]
Once an item is published and assigned a permalink, that permalink is used in various places in the interface.  The problem here is that mallorn isn't configured with a good permalink generator.  This shouldn't be a problem on IU production systems that have working permalinks.

**Comment by joncameron** [comment]
As mentioned, permalinkresolver.example.edu isn't from a valid configuration and comes from the example in our documentation: https://wiki.dlib.indiana.edu/display/VarVideo/Permalinks.
