### ISSUE TITLE
Cannot move items between playlists using browsers IE11 and Edge

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2121]
### Descriptive summary

Server: mallorn.dlib.indiana.edu
Testing: Regression
Browsers: IE11, EDGE
Operating System: Windows10
Issue: Cannot move items between playlists with IE11 and Edge browsers

### Steps to reproduce the behavior

1. Create two playlists and add some items to the first playlist.
2. Go to Edit playlist page of first playlist.
3. using the check-boxes select the items to move.
4. Click on 'Move To' dropdown and select the second playlist to move the items to.
5. The page reloads but you can see that the items are still present in first playlist and the second playlist is still empty.

### Related Issues
#2094 Import Button Doesn't Trigger Event in Microsoft Browsers

**Comment by cjcolvar** [comment]
This probably just needs the fix that was used for bib import confirmation reapplied here.

**Comment by joncameron** [comment]
I added a reference to the issue Chris mentioned above, #2094.

**Comment by joncameron** [comment]
Abandoning as stale.
