### ISSUE TITLE
Audio strip is trimmed on both ends in EDGE browser

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2122]
### Descriptive summary

Server: mallorn.dlib.indiana.edu
Testing: Regression
Browsers: EDGE
Operating System: Windows10
Issue: Audio strip is trimmed on both ends in EDGE browser

### Steps to reproduce the behavior

1. Open an avalon item using EDGE broswer.
2. Hover over the audio icon of the player, you can see that the white strip to adjust audio is trimmed on the top and bottom of the strip.
![image](https://user-images.githubusercontent.com/25850972/27765009-72690da0-5e75-11e7-9eed-cd1d2097525c.png)

3. Perform the same in IE11 or any other browse r(chrome/firefox). The difference is observable between the two.
![image](https://user-images.githubusercontent.com/25850972/27765018-a0688b90-5e75-11e7-8fcd-11bcb95b7e5b.png)

### Related work

Link to related tickets or prior related work here.

**Comment by joncameron** [comment]
Stale.
