### ISSUE TITLE
Media Element 4 allow for audio and video on the same page

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2132]
## Description

Avalon media objects can have both Audio and Video. Ensure media element 4 can create and destroy both Audio and Video players without reloading the page.

## Done looks like
- an avalon media page with both audio and video can have different players rendered based on media type

**Comment by adamjarling** [comment]
Update: currently the general functionality of playing audio and video on the same page, through different MediaElement players, works.  To play audio files locally, I had to include the rtmp flash for the <source>.  @mbklein mentioned there may be a way to play audio files on a desktop server without flash?

To test this on a server, we'll want to disable the flash to prove we don't need it?
