### ISSUE TITLE
Test Mediaelement 4 with Cloudfront

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2137]
### Tasks:
- [ ] Deploy mediaelement 4 branch to AWS staging
- [ ] Ingest and test playback on Cloudfront

**Comment by adamjarling** [comment]
@davidschober @mbklein In Avalon core, the MEJS4 branch is: https://github.com/avalonmediasystem/avalon/tree/mejs4

Once the application is loaded, if you visit a MediaElement player page, put the following query param at the end, re-load and it will load up a MediaElement 4 player.   `?mejs4=true`

**Comment by davidschober** [comment]
@mbklein do you want to deploy this temporarily to staging tomorrow so we can do a smoke test?

**Comment by mbklein** [comment]
Yep. I'll have to create a new branch that combines the AWS stuff with the ME4 stuff, but that shouldn't be a problem.
