### ISSUE TITLE
Test Mediaelement 4 with Wowza

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2138]
### Description
Testing MediaElement 4 with Wowza to make sure that it works properly.

### Tasks
- [x] Install local Wowza
- [x] Config MediaElement 4 branch with Wowza
- [x] Test

**Comment by phuongdh** [comment]
Player goes transparent when switched from audio to video, turns back to normal when click play.
![7dKSDit.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57597b1a54d4111300a7df58/125516c66e82c728ace21e0d46bf90b110a68abdcda5fd53b652fa912a5265296b51f47f76d4b12be64678570d5e4cac46585b41adaf8e2ba0a42062c80d55b98e30063e937f03a6aa811eb500bf2089468cb1bf8e4ec7ea3a37aa.png)

**Comment by phuongdh** [comment]
Public test item: http://fluorine.dlib.indiana.edu/media_objects/qz20ss48r?mejs4=true

**Comment by joncameron** [comment]
A test against another streaming protocol/service is needed to compare to this before we close.
