### ISSUE TITLE
Create parallel and/or new javascript file for Mediaelement 4

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2140]
### Description
Need to re-factor current Avalon media element coffee script file to handle player interactions.

### Done Looks Like
- Start a new JavaScript file to handle player instantiations and removals.
- Use ES2015 JavaScript
- Add Babel support to the rails app

### Tasks
- [x] Create a new JavaScript file which instantiates a new Mediaelement 4 player.
- [x] Include `sprockets-es6` gem to support ES2015 and handle transpiling.

**Comment by adamjarling** [comment]
For the time-being, we'll work from `app/assets/javascripts/avalon_player_new.es6` as the replacement to `.../avalon_player_js.coffee`.  This file can be a wrapper which handles interacting with the new MediaElement.

**Comment by cjcolvar** [comment]
@adamjarling Is this work currently happening in the mejs-new branch?  Should we make a clean branch with just these changes or just worry about cleaning up some of that early testing later?

**Comment by adamjarling** [comment]
@cjcolvar Yes, that's the correct branch.  I built on top of the early testing, but changed almost all of the implementation, so we could probably create a clean branch off master, then rebase the mejs-new changes on top of it?

**Comment by cjcolvar** [comment]
@adamjarling Sounds good.  You should cut a clean branch off of develop instead of master since it is where feature branches get merged.
  
What do you think about making it so we could toggle the new player through a query param (or some other mechanism)?  This could get it merged into develop earlier and be demoable on spruce but still leave the old player in place.  This way we could merge incremental changes and not create a mega branch.

**Comment by adamjarling** [comment]
@cjcolvar Got it, and will cut the clean branch on Monday when I get back.   Also, great idea on toggling the ME4 player via a query param.  This will make it much more practical to move on and test.  I'll begin setting that up on Monday as well.

**Comment by joncameron** [comment]
Leaving this open until Sprint 132 as per the discussion above.

**Comment by davidschober** [comment]
The work above (creating a query param) will be kicked off in a new issue.
