### ISSUE TITLE
OVA for Release 6.1

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2144]
### Description
Our OVA file is updated for each new Avalon release so interested users can download and run the full Avalon stack in a preconfigured VM environment.

### Done Looks Like
- The OVA runs with Avalon 6.1
- The new OVA is available at http://www.avalonmediasystem.org/downloads/avalon-vm.ova

### Tasks
- [x] Build OVA
- [x] Test
- [x] Push to server

**Comment by joncameron** [comment]
Everything looks good testing wise! 

@phuongdh Can you update the OVA name to be "Avalon Media System 6.1.0" and then push to the server?

**Comment by phuongdh** [comment]
Done
