### ISSUE TITLE
Fix Failing Batch Ingest/ Media objects not attaching

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2145]
### Description
Determine and fix the source of the failing batch ingests now that they are failing instead of picking up the wrong metadata. This is occurring both at Indiana  and NU on production systems. IU saw failures at ~100 items (sometimes less), NU saw failures at > 250. 

## Done looks like

- strategy is determined for re-arch if necessary
- A new method of ingest is implemented (indy, jobs etc)
- a simple aggregate report is generated for user on success and failure and emailed. 

### Related

#2060 Failure to create ActiveEncode job returns unrelated job's metadata
#2055 (closed as DUPE)

**Comment by joncameron** [comment]
Suspicions are that this is a Fedora problem... observed by both IU and NU in production use.

**Comment by davidschober** [comment]
@mbklein and @carrickr this sounds like the situation we were seeing on AWS. Can you add in any thoughts?

**Comment by davidschober** [comment]
@carrickr : There's different types of "fix". We could break up the spreadsheet using rue and do behind the scenes throttling. Or we could create nice background jobs and create an aggregate report. 

In the short term we could do something where a big spreadsheet comes in and then waits then does some checking. If two users upload two spreadsheets, that wouldn't help, we have no mechanism to stop the second spreadsheet.

**Comment by carrickr** [comment]
My thoughts for my preferred fix:

- When spreadsheet is dropped off, open it up with roo and load it into SQL
- Iterate over the rows, when every row has a status of failed or succeed (aka nothing in pending), send the user an email report along the lines of what we currently do
- each row is handled via an activejob that ingests that row
- we can tune these jobs depending on what fedora can handle
- a second task can check the database every so often for competition and kick off the emails

**Comment by davidschober** [comment]
Is there a single status email sent? It would be great if we could generate and attach a CSV of the failures so the user could edit and re-upload.

Something like


``` 

131 Media objects and 200 files were imported successfully. 13 Media objects could not be imported. Details in attached CSV file. Please fix the errors and re-upload to complete the batch.


Attachments:

failed_objects.csv

```

**Comment by carrickr** [comment]
Get test coverage for app/mailers/batch_registries_mailer.rb from 50% to 100%
Get test coverage on all views in app/views/batch_registries_mailer/ up to 100%
Write tests for app/jobs/ingest_batch_status_email_jobs.rb
Have a chron job queue the tasks in app/jobs/ingest_batch_status_email_jobs.rb (so via whenever)
Fix on breaking test regarding mocking of the bibimport function
