### ISSUE TITLE
Investigate property changes for technical metadata

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#2157]
### Description
@jenyoung and I have an Avalon property mapping change we're thinking needs to happen. We want to use nfo:codec for audio codec instead of the avalon-specific property that is currently in place. 

http://oscaf.sourceforge.net/nfo.html#nfo:codec

That sets the audio codec property to an ontology that already exists and it can be shared and used elsewhere. Phydo, the preservation repo project with IU and WGBH, also needs an audio codec property so we need to set these up to use the same property and it can’t be the avalon-specific one since that’s only useful internally to Avalon. Both projects use ebucore:hasCodec for the video codec already and Avalon already uses nfo for checksum in Avalon so it's not a new namespace. That's also the same with Phydo.

There are other technical metadata properties that also need to be updated so we need to investigate and list them out. Below are notes about which properties need to change, when it will be best to release these changes, and what Done Looks Like for these changes to be in place.

### Value

- It may be easier to get technical metadata in place before the changes in 7.0
- It aligns IU with phydo, but phydo won't be ready until ~7.0

### NOTE

before we execute we need bitrate (Encoding class on derivatives), held by (Collection class), in addition switching media element to default to hls may make us rethink our avalon-specific derivative class predicates (whether they're all still needed).

### Done Looks Like

- @jlhardes and @jenyoung verify that there's nothing else we can move (schema:bitrate, bf:heldBy)
- property is changed
- all objects are run through and migration occurs to move to new property (on all derivatives)
- Release as a full minor release; if list is significant, is it better to hold until 7.0?

### Tasks

- [x] Schedule meeting to discuss questions and changes needed
- [ ] Write story/stories for work needed to implement changes based on meeting

**Comment by davidschober** [comment]
@jenyoung and @jlhardes can we rewrite this issue to be the investigative work? Done being write issue ? That way we can account for the research work.

**Comment by jlhardes** [comment]
I changed the name of the issue and updated the Description. Does that work?

**Comment by jlhardes** [comment]
Properties to update:

- http://avalonmediasystem.org/rdf/vocab/encoding#audioCodec to http://oscaf.sourceforge.net/nfo.html#nfo:codec
- http://avalonmediasystem.org/rdf/vocab/encoding#audioBitrate to http://schema.org/bitrate
- http://bibframe.org/vocab/heldBy to http://id.loc.gov/ontologies/bibframe/heldBy

**Comment by jenyoung** [comment]
Would like to know from the devs if 'hlsURL' & 'hlsTrackID' will still be needed with the new player?

**Comment by jlhardes** [comment]
bf:heldBy change already described in #1763

**Comment by jenyoung** [comment]
technical properties for ebucore are inn #2634
