### ISSUE TITLE
Add Avalon Metadata Profile to documentation

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#2158]
### Description
https://wiki.dlib.indiana.edu/display/~jlhardes/Avalon+Metadata+Profile

Need a spot for that somewhere in Avalon's documentation on the wiki: https://wiki.dlib.indiana.edu/display/VarVideo/Documentation

### Done Looks Like
- An appropriate area of the Avalon documentation wiki is decided upon to store metadata reference information, including the document referenced above

**Comment by jlhardes** [comment]
This profile is not located on the Avalon wiki: https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+Metadata+Profile

**Comment by mcwhitaker** [comment]
@jlhardes Did you mean "is now" instead of "is not"? That is what it looks like.

**Comment by jlhardes** [comment]
I did mean that the profile is located on the Avalon wiki - sorry for the typo! I edited that comment and the link should go to that documentation.
