### ISSUE TITLE
Streaming stops after 20 minutes

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#2162]
### Description
When streaming RTMP audio (on MCO for example) playback stops after about 20 minutes and can't be resumed without refreshing the page.

### Resolution

- [ ] IU will bump up streaming on their instances
- [ ] Document how to turn up timeouts
- [ ] revisit after HLS only upgrade if needed

**Comment by davidschober** [comment]
This might be a windows issue. It is a token renewal .

@mbklein said we could update the token renewal to 30 minutes to see if it changes behavior. 

We set token to 90 minutes then revisit after ME 4

Put in "known problems"

**Comment by cjcolvar** [comment]
I think it would be good to reproduce this in a testing environment so we know under what conditions it happens and that it isn't just an IU or @bkeese issue.
