### ISSUE TITLE
Documentation to upgrade from 6.0 to 6.1

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2163]
### Description
Enhancing the current documentation for upgrading Avalon instances to 6.1.

### Done Looks Like
- Wiki documents include more detailed information on upgrading Avalon.

### Tasks
- [x] Instruction for upgrading a manual install
- [x] Instruction for upgrading a Docker install

**Comment by phuongdh** [comment]
https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+6.0+to+Avalon+6.1

**Comment by cjcolvar** [comment]
@joncameron would you call this done?

**Comment by joncameron** [comment]
@cjcolvar Yes, I think it's ready to get called done. I'm going to close— @davidschober or @mbklein can you also do a quick check to make sure it looks good on your ends too?
