### ISSUE TITLE
Hyrax Collection Extensions Discussion

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2165]
### Description
The Samvera community will be holding a community sprint for the development of Collection Extensions.  (https://wiki.duraspace.org/display/samvera/Collection+Extensions+Development+Sprints). The Avalon team needs to meet and discuss how it fits with our current work, and how the Collection Extensions requirements will fit in the scope of Avalon 7. 

### Done Looks Like
A meeting is scheduled so the Avalon team can discuss the collection extensions work in the context of Avalon.

**Comment by mcwhitaker** [comment]
@joncameron I would like to be part of this discussion, so please schedule it for next week.

**Comment by joncameron** [comment]
@mcwhitaker We'll put this in sprint 132 and schedule for next week.

**Comment by joncameron** [comment]
This discussion was postponed—it made more sense to happen after the community sprint.

**Comment by joncameron** [comment]
We've long moved past this.
