### ISSUE TITLE
Update Avalon Testing Script

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2166]
### Description
After reviewing the testing script in #2139, there are some changes I'd like to make based on Chris' suggestions.

### Done Looks Like
- The test script is lightly updated to include suggestions.
- Wiki documents referring to the testing script are updated to point to its new location on Box.

### Related
#2139 Review Test Script for Testing Streaming

**Comment by jenyoung** [comment]
actually during NU's  migration to 6.0 we came up with a list of changes. how can we get them included? we have an issue on our board https://github.com/nulib/avalon/issues/86

**Comment by davidschober** [comment]
testing scripts were massively changed
