### ISSUE TITLE
Clicking Playlist Marker Icon Moves Playhead to Marker Offset

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2167]
### Description
As a user, I want the action of clicking a playlist marker icon to move the player position to the time offset property of that marker.

Current mouseover behavior for a marker icon:
- Cursor changes to hand icon
- The same events happen as though the cursor were over the rail (tooltip showing timepoint on the rail under the cursor,

### Done Looks Like
- Mousing over a marker icon changes the cursor to indicate clickability (the current behavior)
- If the mouse is over the marker icon, a tooltip (in the same style as appears above the rail to indicate time) displays the marker name and offset value
- Clicking the marker moves the playhead to that time offset

### Other Enhancements
This issue is meant to be a first pass—eventually working on enhancements as in the design work in #1534.

### Tasks
 - [ ] Have a discussion with Matt and PO's about the design.
 - [ ] Implement Design

**Comment by bkeese** [comment]
@joncameron Is this work meant to be on the  MEJS 4 player, or the current player?

**Comment by joncameron** [comment]
@bkeese This one is meant for the current player.

**Comment by cjcolvar** [comment]
I tested this code on mallorn which streams via AMS instead of Red5 as spruce/fluorine do.  I was unable to reproduce the bug with Firefox not loading playlist items fully.  Since we plan on dropping RTMP and thus Red5 with the ME.js 4 player, I move to not fix this bug since it has already been such a time sink.
@avalonmediasystem/product-owners thoughts?

**Comment by joncameron** [comment]
@cjcolvar  Makes sense to me. @davidschober Closing this one out since everything looks good besides the Red5 wonkiness.
