### ISSUE TITLE
Change Appearance of Playlist Index Column

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2168]
### Done looks like
The icons appear in the correct place or are hidden (REFINE ME)

### Tasks
- [ ]  Apply css styling as necessary
- [ ] Design what the column looks like.

**Comment by joncameron** [comment]
We have options- one would be to remove the icons, another would be to align them closer to the text.

**Comment by cjcolvar** [comment]
@avalonmediasystem/product-owners This needs more refinement and design.  Should it be moved back into Needs Refinement for now?

**Comment by bkeese** [comment]
I vote for moving the icons instead of removing them. I find myself looking at them to see which column is the current sort.

**Comment by bkeese** [comment]
I think we need a call on this from @davidschober  or @joncameron  before completing.

**Comment by davidschober** [comment]
@joncameron I voted to move them. in your absence, we're moving with that.

**Comment by joncameron** [comment]
Looks great to me! Much nicer. Thanks @bkeese
