### ISSUE TITLE
Refactor Documentation for Upgrading Avalon

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2171]
### Description
Most users upgrading Avalon will be moving from a version of Avalon 5 to the latest Avalon 6 release. There is no single document currently for performing this. Current instructions on the 6.0 to 6.1 page have a reference to go back to the 5.6 to 6.0 documentation and run through those before following the instructions on the 6.0 to 6.1 page.

### Questions for Discussion
- Should there be a single page for upgrading from 5.x to 6.x? What are the advantages of disadvantages?
- If so, what would that look like and how would it be updated?
- Is there a better way to structure the upgrade documentation we currently have?

**Comment by davidschober** [comment]
@joncameron what did you have in mind here?

**Comment by joncameron** [comment]
5.x to 6.0 is one step, and from there 6.0 to 6.x is the steps that we can take.

**Comment by davidschober** [comment]
very old and stale.
