### ISSUE TITLE
Documentation for Override of PID namespace on the Migration Rake Task

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2172]
### Description
Documentation for override of PID namespace on a migration rake task.

### Done Looks Like
- Code change in #2164 is documented on the wiki under the Migration Tool page
### Related Issue
#2164

**Comment by cjcolvar** [comment]
Done under `Command Options` https://wiki.dlib.indiana.edu/display/VarVideo/Migration+Tool.
