### ISSUE TITLE
Add Open Graph Protocol Info to Media Object Pages

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2175]
### Description
[The Open Graph protocol](http://ogp.me/) allows for rich presentation in embedded contexts. Copy and pasted links can be rendered with thumbnail previews, summaries, and other information that provides more description and useful context for a link. Having Avalon provide this same functionality would provide for richer media sharing. 

### Done Looks Like
- The appropriate meta elements from OGP are written into the header for item pages and collection landing pages
- Metadata included are the four required properties of OGP (title, type, image, URL) and others added as desired

### Questions
- Are we wanting to target a specific sharing site (no, generic as possible)
- What is this getting us, and is it aligning with what we're wanting?
- What are the caveats per site that make use of OGP? Having places in mind will help us—different places might make use of the information differently.

**Comment by joncameron** [comment]
What are the options for this in Hyrax? That should be followed up on.

**Comment by Dananji** [comment]
@joncameron The gem I mentioned: https://github.com/kpumuk/meta-tags

**Comment by joncameron** [comment]
This looks great; follow-on work in #4357. In particular:
- are there non-OGP things that need to be added?
- can we add embeds?
- Title string changes as needed
- Default image (aka no poster on the item) should be easily replaceable
