### ISSUE TITLE
Improve SEO

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2176]
### Description
Search Engine Optimization is important for many institutions, and providing it out of the box in Avalon is a valuable feature. What Avalon is currently doing needs to be discussed, and ideal practices for implementing SEO should be discussed by the team.

### Done Looks Like
- Current SEO practices in Avalon is evaluated
- Recommendations are made on what to implement for strong SEO for Avalon instances and media object pages

**Comment by davidschober** [comment]
@joncameron I agree with this. I think this should fall into our Hyrax move. They've already done some work including : 

* Adding Google Scholar, Facebook, and Twitter metadata to works pages
* Using resource sync (based on google site maps) for sharing data. 

I would argue we dig into what they've done and expand on it. But I don't think we should slate this work for 6.x

**Comment by joncameron** [comment]
https://developers.google.com/search/docs/guides/intro-structured-data#structured-data-guidelines

**Comment by davidschober** [comment]
@joncameron I think this issue is quite stale. I move to write an actionable issue, say, add json-ld with schema.org mappings for all content(media) pages. It could probably be taken on at the same time as adding a data-layer #3039
