### ISSUE TITLE
Custom Thumbnails for Audio Items

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2182]
### Description
As a collection manager, I want the ability to set custom thumbnails for audio items in my collections so that I can provide context or branding to audio-only items.

### Done Looks Like
TBD

**Comment by cjcolvar** [comment]
Do we need this in Avalon 6.x?  I'm pretty sure this is solved in Hyrax by the notion of representative image for a work.

**Comment by joncameron** [comment]
Not relevant, as per Chris's comment.
