### ISSUE TITLE
Move / re-factor media object 'Sections' JS to a .js file instead of in-lining

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2185]
### Description
Move and re-factor the custom javascript for controlling opening and closing of section panels, to a separate javascript file, instead of having it inline.

### Done Looks Like
- Inline JS removed
- Functionality works as normal

### Tasks
- [ ] Remove inline JS from `app/views/media_objects/_sections.html.erb`
- [ ] Move this code to a "Sections" custom Avalon Mediaelement plugin created in #2161.

**Comment by adamjarling** [comment]
Relates to #2161

**Comment by adamjarling** [comment]
This is pretty old, so I'll take a second look and update the issue after Playlist Items.

**Comment by adamjarling** [comment]
I think we combine with with the "Sections" MEJS plugin creation work.  In the future as it may take a few days to get it right and tested.

**Comment by davidschober** [comment]
This should be part of the initial work we do.

**Comment by cjcolvar** [comment]
@davidschober @joncameron I'm confused.  Is this a 6.x or 7-0.1 issue?  To me it reads as a 6.x issue.

**Comment by adamjarling** [comment]
@cjcolvar This should transfer over into a 7.x issue.  Your call on whether it's worth implementing in 6.3.x?

**Comment by adamjarling** [comment]
@cjcolvar  I think we close this as stale, and re-evaluate how it'll work in 7.
