### ISSUE TITLE
Clicking on marker beyond end of playlist clip doesn't work

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2186]
### Timeline
This issue will be re-evaluated after Avalon moves to MediaElement 4 as its media player (slated for Avalon release 6.3) as per comments below.

### Expected behavior
Player seeks to marker location and autoplay is turned off

### Actual behavior
Play seeks to beginning of playlist item

This also suggests that all marker clicks should cause autoplay to toggle to off.

**Comment by davidschober** [comment]
@joncameron do you think this is something we can grab as part of ME4? I'm hoping we can put as much effort as possible toward getting that out the door, and I'm sure we'll have to debug.

**Comment by joncameron** [comment]
@davidschober Yes, this isn't high priority—we can wait on this one until after the MediaElement upgrade.

**Comment by cjcolvar** [comment]
Can't reproduce on mallorn.
