### ISSUE TITLE
Document lists to send release announcements to

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2191]
## Description
We are currently keeping the list of lists we send announcements out to in our heads. Let's write procedures on the wiki and get the list standardized so **anyone** can do it if necessary. 

### Done looks like:
* wiki page is created
* stuff's documented

**Comment by joncameron** [comment]
https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+Announcements

Current question: do messages to avalon-l also forward to members of avalon-discuss-l? I can't remember and need to doublecheck before closing this one out.
