### ISSUE TITLE
Extend Active Encode to allow use of FFMPEG for local development 

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2199]
## Descrption

As a Developer, I don't want to have to standup a complicated transcoding box to work on Avalon. We should extend Active Encode to allow for transcoding via ffmpeg. 

## Done looks like

- A developer can use Active encode with ffmpeg

**Comment by joncameron** [comment]
Is this needed for 0.1, or can the basic ffmpeg derivative generation done through Hyrax currently suffice?

**Comment by cjcolvar** [comment]
I think basic hydra-derivatives will be fine for 0.1.

**Comment by cjcolvar** [comment]
@avalonmediasystem/product-owners Should this be moved to a different milestone since we agreed that stock hydra-derivatives would be okay for 0.1?

**Comment by joncameron** [comment]
Definitely, I've moved it to the _Avalon 7 Backlog_ milestone for now.

**Comment by davidschober** [comment]
I am abandoning this as dupe.
