### ISSUE TITLE
Add Media File to a Work in Hyrax

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2200]
### Description
As a user, I want to add audio and video files to a work in Hyrax so that my content is available in the repository in a way that shields me from having to worry about the technical details of transcoding.

We're sticking with out of the box hydra_derivatives for this early work. This should be the most standard, default way to accomplish this task, with all of the needed configuration figured out and set.

Attaching a media file to a standard, generic work is the scope of this story.

### Done Looks Like
- Configuration changes are made to allow for media files to be added to a generic work #2845 
- Dev environments/Docker are set up to make this work #2846
   - derivative generation happens
   - ensuring ffmpeg is installed
  
 - As a user I can create a new work, upload a media file, and the file will be represented in the generic work in the default way (using whatever the ffmpeg defaults are for hydra_derivatives) #2847
 - Video plays within the work view in the media player #2847

### Notes
- In Hyrax there's a configuration flag (ffmpeg enabled). What else needs to be configured to get the wheels turning as expected.
- HTML5 video tag/native browser playback is set in Hyrax for A/V files.
- hydra_derivatives can do the basic transcoding as part of its standard behavior

**Comment by mcwhitaker** [comment]
Created #2873 for the queue installation. Adam will revert IIIF work to show streaming.
