### ISSUE TITLE
Extend iiif_manifest gem to represent IIIF 3.0 style manifests

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2201]
## Description

The Samvera iiif_manifest gem is currently generating presentation manifests for images and book-like objects; we need to extend it to represent A/V material using the current spec. 

## Done looks like
- Create branch in iiif_manifest gem for this work #2848 
- Make requests configurable—return specific versions of the Presentation manifests (2.0 vs 3.0, etc.) #2849
- Take a pass at implementing the iiif_manifest gem for the current draft of IIIF Presentation 3.0 (post AV meeting in London) #2850
   - stick with that until May (when IIIF conference is) and do clean-up at that point'
- Check in with community—maybe not an organized sprint, but possibly get 1-2 people from interested parties to help with efforts on the iiif_manifest development #2851

**Comment by joncameron** [comment]
Current caveats: 3.0 has not been released, and the spec is not yet complete.

**Comment by mcwhitaker** [comment]
As of today, this EPIC is waiting on #2849.
