### ISSUE TITLE
Avalon Player Consumes IIIF Manifest

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2202]
### Description
The Avalon player should consume a IIIF manifest upon creation. The IIIF manifest will contain all the information necessary for the player (extras such as ranges for structure within representation etc. are out of scope) and be mapped to the proper creation parameters for MediaElement.

Manifests may come out differently from the iiif_manifest gem than the examples that we've created in the past. The Avalon player should accommodate the possibilities of how manifests are modeled. 

### Notes
- Once player parsing is set, we're good. There won't be much variation in manifest layout for simple sets of information at this level.
- The player consuming non-Hyrax-generated manifests is a nice to have, but is out of scope of 0.1 and speculative for now. We'll assume that the player will only consume and need to consume iiif_manifest gem generated manifests for the time being.

Informed by #2201

### Done looks like
- Ensure that the Avalon player can consume a presentation 3.0 manifest from iiif_manifest gem
- The media plays back successfully (no structural metadata yet)

### Tasks
- See #2854

**Comment by joncameron** [comment]
It would be good to have samples of different ways to model our IIIF manifests.
It might be good to have a ticket indicating where the spec is at now and taking a look at our example manifests and what the differences between them are.
We could also have an issue ahead of this to figure out what our target model is for generating iiif manifests in the iiif_manifest gem.

**Comment by adamjarling** [comment]
Related to #2854
