### ISSUE TITLE
Avalon Player Can Stream From a Media Server

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2203]
### Description
The IIIF manifest that the Avalon player consumes will contain URLs referencing media on a streaming server or servers. The Avalon player should be able to use this to actually present the video or audio content within the player. We will focus on configuration and setup through infrastructure. 

### Done looks like 

- The player can stream from wowza _or_ cloudfront
- We can store or map it via infrastructure.

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#90
