### ISSUE TITLE
Dropbox Import Throws Error on Filenames With Spaces

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2209]
### Bad Behavior
Rails returns a 500 when a user attempts to import a file from an Avalon dropbox that contains one or more spaces in the name. 
![aug-09-2017 14-59-12](https://user-images.githubusercontent.com/1406618/29139037-82964906-7d13-11e7-871c-ebaaa4d67aef.gif)

#### Environment
Encountered on Neon (IU Prod) (6.1), Pawpaw (6.1), Spruce in Firefox 55 on macOS.

### Expected Behavior
After clicking "Open Dropbox", selecting a file with spaces in the name and clicking the "Submit" button, the file should show up per normal as imported and attached to the media object.

### Rails Debug Page
![screen shot 2017-08-09 at 2 54 30 pm](https://user-images.githubusercontent.com/1406618/29138784-b3ec72d8-7d12-11e7-8419-f045cdd06f8d.png)

**Comment by davidschober** [comment]
This is possibly a browse everything error but it could possibly be compensated for in the master file controller. We can encode spaces before trying to parse.
