### ISSUE TITLE
Create Architecture Drawing

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2214]
the TIB requested an architecture diagram for Avalon. @phuongdh do you have one handy? If not, let's get this in the next sprint cycle and get it done early. The goal is to show how the various pieces (workers, avalon, fedora, solr, etc) work together. We could possibly reuse a cleaned up AWS diagram.

**Comment by davidschober** [comment]
![img_20170816_162623](https://user-images.githubusercontent.com/4803230/29385480-7ed607fe-829d-11e7-88c6-9fad188bef8d.jpg)


We need to find the originals of these drawings...

**Comment by davidschober** [comment]
We need a diagram of Avalon 7 not 6.x @cjcolvar do you want to work with me to cleanup the work down in our wihitepaper?

**Comment by davidschober** [comment]
I pulled together our recent discussions and simplified the drawing from the face to face (so there weren't too many components represented). 

![structurizr--1-_1-2](https://user-images.githubusercontent.com/4803230/29435051-13448578-836b-11e7-9ac6-6f8e022a300e.png)

 I created this in structurizr.com if someone  wants to tweak, the code is here:

https://gist.github.com/davidschober/88e8a873137403e87f9a84544635dc42

**Comment by davidschober** [comment]
Updated with @cjcolvar 
![structurizr--1-_1-4](https://user-images.githubusercontent.com/4803230/29471399-8029d440-8415-11e7-8917-45d8447a5471.png)

**Comment by cjcolvar** [comment]
:+1: Looks good to me.

**Comment by davidschober** [comment]
@jwd and @joncameron I realized this got stuck when I left for vacation. @jwd do you want to take a quick look and send it on to the TIB. @joncameron where do you want to put it in the wiki?

**Comment by joncameron** [comment]
@davidschober I'd like to put it in a section for Avalon 7, possibly on or as a side page to the roadmap.

**Comment by davidschober** [comment]
@joncameron Have at it! I think someone needs to send it to the TIB. @cjcolvar can you get thumbs up from JD to send over to the TIB folks

**Comment by davidschober** [comment]
https://gist.github.com/davidschober/88e8a873137403e87f9a84544635dc42

UPDATED with @jwd edits

![avalon_7](https://user-images.githubusercontent.com/4803230/30118392-8855d934-92e8-11e7-8721-78c8eaa41ceb.png)

**Comment by cjcolvar** [comment]
@davidschober One small suggestion: I think the Avalon Front End should be Component: Hyrax Application instead of Hyrax Plugin.  The Avalon Front End will be the wrapping up of all of the Hyrax plugins that Avalon cares about with UI tweaks.  Unless you were thinking the dashed line box is the application.  Hmm...I'm torn since everything in the Avalon Front End could be plugins but the bundling and any UI tweaks would be the application.

**Comment by joncameron** [comment]
It could be something like this:
![img](https://user-images.githubusercontent.com/1406618/30120018-a3284ef6-92f5-11e7-84e4-8f89f5e66f2e.png)
Or _Avalon_ could go on top of the dashed box to indicate that everything encapsulated in it is "Avalon"

**Comment by davidschober** [comment]
Someone else has to do it if we're redrawing it. I don't have time today.

**Comment by joncameron** [comment]
@davidschober I think it looks good. I'll put this version up and we can always change as desired.

**Comment by davidschober** [comment]
@jwd did you want to send it over to the TIB?

**Comment by mcwhitaker** [comment]
@davidschober @joncameron There is a typo in this diagram. The _Transcoding Server_ box, in the list of containers, has _Elastic Trancoder_ instead of _Elastic Transcoder_,

**Comment by davidschober** [comment]
Thanks! Changing now

**Comment by davidschober** [comment]
![avalon_7](https://user-images.githubusercontent.com/4803230/30129722-824548b2-930c-11e7-99d8-37d95ebd7025.png)

**Comment by cjcolvar** [comment]
@davidschober I don't see any difference.

**Comment by jwd** [comment]
Fedora Repository should say "Fedora 4.x Repository". I agree with Chris that Avalon Front End should be labeled as Hyrax Application. It's confusing to say the Avalon Front End is a Hyrax plugin and then in the description say that it include Hyrax plugins. And should Hyrax itself really be described as a Hyrax plugin?

**Comment by davidschober** [comment]
k. Here's a new version that gets us out of the hairiness (I think). When @cjcolvar and I were brainstorming originally we used "hyrax" as shorthand for the backend. The entire dotted line is the solution bundle _based_ on hyrax. There's a backend, ingestion, models, etc/ and a FE (IIIF-driven player etc). 

https://northwestern.app.box.com/files/0/f/37421864978/Architecture_drawings

I put it in here for easier updating.

**Comment by joncameron** [comment]
Minor updates:
![avalon7arch](https://user-images.githubusercontent.com/1406618/30214127-4cb1022c-9479-11e7-84c2-ea0b285be8a7.png)


@jwd Does this meet the changes you were thinking about in your comment yesterday, or are there other things that need to be changed or updated before sending it out?

https://gist.github.com/joncameron/75a0686a8250c10ffd8d251fab23961c

**Comment by mcwhitaker** [comment]
@davidschober - Jon D signed off on this. I will be sending it out now.

**Comment by davidschober** [comment]
cool Thanks!

**Comment by davidschober** [comment]
@mcwhitaker I added a sprint label for this, feel free to remove if this shouldn't be recorded as such.
