### ISSUE TITLE
Player doesn't resize when something on the page causes a scroll bar to appear

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#2215]
When a page starts without a scroll bar and then something happens (i.e. the 'share' button is clicked) which causes a scrollbar to appear. The player doesn't resize. This shows up sometimes as the last player control on the right being wrapped down and appearing outside the player.
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57597e546b48630e00666b0c/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f47f76d4b12be64678570d5e4cac46585b41adaf8e2ba0a42062c80d55b98e30063e937f03a6aa831eb808b0218e4f87bfbc8f4dc2e13c21e299c2.PNG)

**Comment by bkeese** [comment]
This thread proposes an interesting solution: 
https://stackoverflow.com/questions/2175992/detect-when-window-vertical-scrollbar-appears

**Comment by davidschober** [comment]
@bkeese is this happening a lot? I'm thinking we might want to punt until 7

**Comment by davidschober** [comment]
@adamjarling @bkeese is this happening in ME4? If not, let's abandon...

**Comment by bkeese** [comment]
I'm curious if this is an issue in ME4 also. It happens consistently in ME3 in the described scenario. But, that might only be with certain objects on certain screen sizes, and it isn't really all that noticeable. I'd say if ME4 doesn't have the problem, then we punt. If not, we might want to solve it soon for both versions.

**Comment by adamjarling** [comment]
@bkeese I can't seem to re-create this for the original ME player.   But currently I'm on a small laptop where the scroll bar is always present.  Also, it might not yet be a good time to know if it's an issue in ME4, since all the player controls aren't yet in.  I'll keep an eye out for this though.

**Comment by cjcolvar** [comment]
I can't reproduce this on mallorn.
