### ISSUE TITLE
Talk to Hyrax devs about implementing Avalon RDF mapping as base Hyrax descriptive fields

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#2223]
Avalon has a mapping for Avalon MODS to RDF: https://docs.google.com/spreadsheets/d/1TY5G_9Jl6QI-Aq6c3cCs54BH5E5sRu3Omhnz6GMub0U/edit?usp=sharing

Tasks
- [ ] Start discussions with Hyrax devs/Samvera community about changing base Hyrax descriptive fields to update / expand fields to more closely match this mapping
- [x] Will include the Samvera Metadata IG

Avalon to Hyrax mapping https://docs.google.com/spreadsheets/d/1iKpx_jw5QY6-R5FH_2-HCcqdqIuJkDdP93xZyiY4tIU/edit?usp=drive_web

Done Looks Like
Talk with Samvera Metadata IG about plan and possible WG.
Report and Generate new tickets as necessary.

**Comment by jlhardes** [comment]
Strategy from #2856 meeting:

* Hyrax fields that Jen and Julie see as missing or needing changes:
    * no genre field
    * confusion with geographic subject including place of publication
    * no temporal subject
    * no notes fields
    * no label for related item URL
    * changing keyword to schema:keywords from dc:relation (issue in backlog for that)
*  Talk to SMIG about changes and gauge interest
    * If interest, start Hyrax Base Metadata Working Group 
        * define use cases for Hyrax (types of content)
        * find common base set of fields (example for changes/additions above but there might be others)
        * make plan for how to implement and offer migration path
        * take this to Hyrax Roadmap
    * Do design work with WG first then schedule sprints to implement code changes

**Comment by jlhardes** [comment]
SMIG discussions for reviewing Hyrax metadata fields, creating documentation, and gathering feedback are scheduled for April 23 and May 4 (https://groups.google.com/forum/#!topic/samvera-metadata/KlsSHwEg5pM). These sessions are after this current sprint so this story will likely continue for 2 more sprints at least to encompass both of the meetings and time to process the results.

**Comment by davidschober** [comment]
@jlhardes I'm ok with calling this complete as the goal was to start discussions, correct? Maybe we can add a separate issue in the next cycle to document outcomes?
