### ISSUE TITLE
Verify mappings for descriptive metadata to show in IIIF manifest are still good

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#2225]
#1772 outlined minimal descriptive metadata to show in IIIF manifest. This needs to be reviewed and decisions made about how much description should show in IIIF manifest.

c.f. 
https://gist.github.com/jlhardes/1e3adada7410591f46b170e65dce20af

### Done Looks Like
- [ ] mappings reviewed

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#92
