### ISSUE TITLE
Verify mappings for descriptive metadata to show full metadata outside of IIIF manifest are still good

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#2226]
Avalon has a mapping for Avalon MODS to RDF: https://docs.google.com/spreadsheets/d/1TY5G_9Jl6QI-Aq6c3cCs54BH5E5sRu3Omhnz6GMub0U/edit?usp=sharing

This needs to be reviewed and updated if necessary.

**Comment by jenyoung** [comment]
duplicate to #1808
