### ISSUE TITLE
Update Avalon 7 Roadmap

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2228]
### Description
A lot of discussions have happened regarding Avalon 7 that might not be reflected in the roadmap. We'll need to go through and update anything as necessary. 

### Done Looks Like
POs review the roadmap and make updates as needed.

**Comment by davidschober** [comment]
@joncameron we did this right?

**Comment by joncameron** [comment]
@davidschober I think so, but this ticket also reminds me that the previous document in Box should be checked in case anyone had added things there and they weren't reflected in the roadmap in the wiki. I'll do that and close this issue.
