### ISSUE TITLE
Design for Media Object-level Embedded Player

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2240]
### Description
The embedded Avalon player only deals with single sections at once. As a user, I want to embed a media object, including all of it's sections, into another page so that I have access to all of the content within an item.

### Questions
- How much structure within should be represented?
- What's a good design pattern used by similar platforms?
- How will we represent this link vs the current behavior for embed code visible to users?
- Can we use an existing MEJS4 plugin that will fit this need?

### Done Looks Like
- Design is discussed and initial mock-up/wireframing done for an embedded player that also plays through sections (and possibly structure).

**Comment by davidschober** [comment]
Should we use ME4s playlist plugin for this? It seems like it would be a good idea to have this hideable/ throw out from the side rather than dropping text on a page.

**Comment by joncameron** [comment]
Multi-disc CD interface might be something analogous.

**Comment by joncameron** [comment]
I've changed this to just be a design story.

**Comment by davidschober** [comment]
@joncameron do we have do design on it or can we pick up on ME4js built in slide out?

**Comment by davidschober** [comment]
@joncameron check above ^^^ I'd rather not customize ME4 if possible. If there's an existing plugin, we should use it.

**Comment by joncameron** [comment]
@davidschober Definitely, if there's one that meets our needs that would be great. Part of this story should be evaluating what's out there in terms of grab and go plugins.

**Comment by joncameron** [comment]
Another option is to use the IIIF player instead of the current player and embed that, using our manifest. Probably the right way to do it.
