### ISSUE TITLE
MediaElement4 Add Structural Metadata Title(s) to default title

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2247]
### Description
Incorporate Brian's work on recursively applying structural metadata titles to default title for Add to Playlist functionality in MEJS4.

### Done Looks Like
Mimic functionality added in #982 for the MEJS4 player.

### Tasks
- [ ] #982 functionality added to MEJS4 player.

**Comment by adamjarling** [comment]
@davidschober @joncameron FYI I pulled this into the sprint as it was related work to Add To Playlists.

**Comment by joncameron** [comment]
@adamjarling Throwing a curveball in... I've updated this with a story that updates/refines the logic for determining the default value for a playlist item.

**Comment by adamjarling** [comment]
@joncameron No problem.  I think some clarification/standardization is a good thing here.
