### ISSUE TITLE
Refinement for Playlist Item Title Generation

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2249]
### Description
This is a further refinement to the way titles for playlist items are prepopulated.

### Updates
- Filename will not be included as part of the prepopulated title field
- The segment or track which is currently selected should not carry over the numbering which Avalon generates (skipping the "1.", "2." etc and that doesn't appear in the XML file

### Desired Behavior for Population of Title Field For New Playlist Items
- If there is only a single section and no structural metadata XML exists, use MediaObject_Title
- If no structural metadata XML exists or it exists but no structural segment is active, use "MediaObject_Title - Section_Label"
  - 'File name' will be used if no 'Section label' value exists
- If structural metadata XML exists and a segment is currently highlighted, use "#{MediaObject_Title} - #{Section_Label} - #{Label value of parent node if one exists} - #{Label of span which is currently active}"
  - 'File name' will be used if no 'Section label' value exists
  - If there are multiple parent Divs to the span in the XML, each should be listed, starting with the top node on down.
  - Example — this item will contain "Johann Sebastian Pizza - Pizza Pie in G Major - Pizza A" as part of the full prepopulated value
    - <img width="180" alt="screen shot 2017-08-29 at 1 59 49 pm" src="https://user-images.githubusercontent.com/1406618/29836221-8b446100-8cc2-11e7-9b48-c7f09c058108.png">

### Done Looks Like
- Updates made to the logic that fills in the default title for a playlist for both the current MediaElement _Add to playlist_ functionality as well as for the MediaElement4 player in Avalon, as defined in the Updates section above

### Reference
#982 Titles for Newly Created Playlist Items Only Include Media Object Title

**Comment by adamjarling** [comment]
@joncameron Assigning myself for the MEJS4 side of this (not sure if it applies to both MEJS2 and 4).

**Comment by joncameron** [comment]
@adamjarling Sounds good, especially since #1881 is closed now. I've updated the done criteria to reflect the work on both.

**Comment by bkeese** [comment]
I'll work on the MEJS2 part.

**Comment by cjcolvar** [comment]
@adamjarling The MEJS2 part is done in (#2272).  You should probably look at it since it might vary from the above description a little.
