### ISSUE TITLE
Text for Related Items Doesn't Wrap In Playlist View

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2252]
### Description
On a playlist's view page there is not adequate space between items in the Related items list. If an item listed in the Related items area has text that exceeds the width of the accordion and wraps onto the next line, it renders on top of the next item in the list.

### Example Item URL
https://mco-staging.dlib.indiana.edu/playlists/1389?token=7FO6DUOIQjJHf6Z9nzMn5w

### Example:
<img width="809" alt="screen shot 2017-08-25 at 4 30 43 pm" src="https://user-images.githubusercontent.com/1406618/29731617-00ef6250-89b3-11e7-828c-743e21533dca.png">

**Comment by bkeese** [comment]
I have a PR in that does this: 
![image](https://user-images.githubusercontent.com/7440154/29732290-f922d1a8-89b5-11e7-930b-e012086773df.png)
