### ISSUE TITLE
Media Player Should Span Width of Section Accordion

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2266]
### Description
The MediaElement version and configuration currently used caps the width of media player so that is doesn't span the width of the accordion section immediately below it. This may have been due to a previous limitation, but MediaElement4 allows for dynamic width resizing in a way that's reasonable to implement. The current look is lopsided—there's unnecessary white space between the video and the metadata container column.

### Done Looks Like
The Avalon media player's width extends to the width of the accordion section.

### Current Look
![screen shot 2017-08-29 at 9 05 46 am](https://user-images.githubusercontent.com/1406618/29822860-ee86c0f0-8c9a-11e7-9bc3-0655d1b2474c.png)

![screen shot 2017-08-29 at 9 04 59 am](https://user-images.githubusercontent.com/1406618/29822865-f12e4bc0-8c9a-11e7-9ec6-d1a9d688a05e.png)

### Desired Look
(these were quick mockups done in photoshop; the player looks more stretched than it would be in implementation)
![audio_long](https://user-images.githubusercontent.com/1406618/29822856-ebc8fc70-8c9a-11e7-8fc6-73ccc1e6172c.png)

![span_to_accordion](https://user-images.githubusercontent.com/1406618/29822852-e7d57e5e-8c9a-11e7-9b43-f636031d1aec.png)

**Comment by adamjarling** [comment]
@joncameron Is this for MEJS4, or MEJS2?   Or both?

**Comment by joncameron** [comment]
@adamjarling MEJS4, added the label to make it explicit.

**Comment by cjcolvar** [comment]
Is this still a problem?  I'm not seeing this on spruce.

**Comment by phuongdh** [comment]
@cjcolvar Still is, if your screen is wide enough. 

@davidschober I have the fix for this but my concern is if we let player width grow, the height will also grow accordingly and push other content out of the viewport. IMO we need to rethink responsive layout so it works better with larger screens.

![image](https://user-images.githubusercontent.com/1304657/33784515-2bdc5b98-dc2f-11e7-82e0-692711b5c467.png)

**Comment by davidschober** [comment]
Can you show this Monday?

**Comment by phuongdh** [comment]
@davidschober @joncameron If we were to limit player and section width, a ton of white space is inserted on the right, it gets worse on higher res screen.

![image](https://user-images.githubusercontent.com/1304657/33839645-d0df9a78-de60-11e7-92e5-a6288d0c4c89.png)

Center content and limit width, à la Hyrax/Youtube

![image](https://user-images.githubusercontent.com/1304657/33839904-6c971fa4-de61-11e7-9445-50b28235723a.png)

**Comment by cjcolvar** [comment]
Instead of playing with this too much, how about we just replicate the behavior of the MEJS2 player under Avalon 6.2?

**Comment by joncameron** [comment]
@phuongdh Please go ahead and close this one when things are back to parity with 6.2 styling (if they're not already!)

**Comment by phuongdh** [comment]
Instead of closing and then forget about this, should I remove 6.3 label and move it back to Backlog/Needs Refinement?

**Comment by joncameron** [comment]
No longer relevant
