### ISSUE TITLE
Section Accordion Appears on Single Section Items

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2267]
### Encountered Behavior
The section accordion below the media player displays on items that only have a single section.
<img width="1045" alt="screen shot 2017-08-29 at 2 20 07 pm" src="https://user-images.githubusercontent.com/1406618/29837293-bce40e1a-8cc5-11e7-835b-ab6bddd395be.png">

### Expected Behavior
A media object with only one section will not display the section accordion.
<img width="893" alt="screen shot 2017-08-29 at 2 25 47 pm" src="https://user-images.githubusercontent.com/1406618/29837399-07295ec6-8cc6-11e7-94c3-0de83c8469e9.png">

### Environment
Sodium, mco-staging.dlib.indiana.edu

**Comment by cjcolvar** [comment]
I think this is still working as expected where the sections show up for collection staff while there is processing happening.  When processing completes successfully, it won't be shown anymore.  For example, https://mco-staging.dlib.indiana.edu/media_objects/qj72p820d.
