### ISSUE TITLE
Add Item to Playlist Modal Lacks Indication of Default Scope

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2275]
### Description
When adding an entire item or section to a playlist, the modal that appears does not have either of the two radio buttons under _Playlist Item Scope_ selected. One of these should be selected to indicate the default, and which option will carry if the action is completed by clicking the _Add to Playlist_ button.

### Environment
Seen on Spruce and MCO Staging, Firefox 55 on macOS 10.11.6

### Currently Looks Like
<img width="586" alt="screen shot 2017-08-31 at 10 32 10 am" src="https://user-images.githubusercontent.com/1406618/29934879-cd1d5abc-8e4a-11e7-80f0-d2a1f6a02db2.png">

### Done Looks Like
One of the radio buttons is selected to indicate the default value for scope in the _Add Item to Playlist_ modal.

**Comment by lealeelu** [comment]
I think the single item for each section should be the default because if you mess up and use that option when you meant the other, it's less to clean up.

**Comment by lealeelu** [comment]
Can we get some professor/AI/User to try this out and get their feedback?

**Comment by davidschober** [comment]
I think single item should be default for the same reasons as @lealeelu. As a general rule, I think defaults should do as _little_ as possible. @joncameron you good with this?

**Comment by joncameron** [comment]
I think that's fine too. We can always change based on user feedback if needed.
