### ISSUE TITLE
Validate embed works with ME4js

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2276]
## Description

Verify that embed works with the ME4js player.

## done looks like
- player is embedded
- all controls work as expected
- stream is smooth

**Comment by Karthikeya212** [comment]
Verified the use cases and are working fine except #2456 . Also I couldn't see the captions icon in the ME4 player, I presume that it is not supported yet.

**Comment by cjcolvar** [comment]
Yes, I looked and I don't think we have captions enabled there yet.
