### ISSUE TITLE
Test MediaElement 4 with RTMP Streaming

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2277]
### Description
Since some institutions using Avalon will be using RTMP streaming, it needs to be tested as working appropriately with Avalon 6's MediaElement 4 player.

### Done Looks Like
- Testing is done so that RTMP support can be verified as working
- On a single server: AMS

**Comment by joncameron** [comment]
This could inform us as to what the base status of out-of-the-box RTMP support is. We can check in with stakeholders and others, but this may not be necessary.

**Comment by davidschober** [comment]
@joncameron did we decide to abandon?

**Comment by davidschober** [comment]
Abandoning per discussions
