### ISSUE TITLE
Start Using New Travis Infrastructure

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2285]
### Description
The new Travis infrastructure has made breaking changes, and we're currently running on their legacy infrastructure. We need to begin using their new infrastructure to keep current and for the quality of life improvements the new Travis stuff brings.

### Considerations
Figure out if we can upgrade to the new infrastructure using sudo, or make Avalon work without sudo.

### Done Looks Like

**Comment by joncameron** [comment]
Not high priority until it's high priority.

**Comment by cjcolvar** [comment]
I worked on this while fixing the travis build that suddenly failed this morning.
