### ISSUE TITLE
Testing for Rewritten Batch Ingest Functionality

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2287]
### Description
Extensive testing will need to be done on the batch ingest feature.

### Done Looks Like
- Test script is written (human testing)
- Tests are done according to the criteria specified in the script (drawing from this issue)

### Testing Points
- Make sure it works
- Make sure it works with a large set of items (~1000)
- Make sure replays work

**Comment by davidschober** [comment]
@carrickr and @Karthikeya212 are you two done with this? I think @Karthikeya212 is actively testing correct?

**Comment by Karthikeya212** [comment]
@davidschober I faced a couple of issue while testing, and am waiting for this bug #2410  to be fixed to proceed with testing as the ingest process itself is not starting.

**Comment by davidschober** [comment]
Thanks for the update! @Karthikeya212
