### ISSUE TITLE
IIIF Endpoint Extra Credit

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2297]
- Structure Within
- Descriptive Metadata

**Comment by adamjarling** [comment]
@cjcolvar Here's some differences I'm noticing between manifests:

**lunchroom_manners** : https://dlib.indiana.edu/iiif_av/lunchroom_manners/lunchroom_manners_v2.json

**spruce_manifest**:
https://spruce.dlib.indiana.edu/media_objects/vq27zn45k/manifest

_lunchroom_manners:_
`"id": "http://dlib.indiana.edu/iiif_av/lunchroom_manners/canvas/1#t=0,157",`
_spruce_manifest:_
`"id": "https://spruce.dlib.indiana.edu/master_files/sx61dm32g/canvas#t=0,1:00",`

_lunchroom_manners:_
this never happens (missing ending time in range `t` value)
_spruce_manifest:_
`"id": "https://spruce.dlib.indiana.edu/master_files/sx61dm32g/canvas#t=5:00,",`

**Comment by cjcolvar** [comment]
I fixed the first.  I thought the second might still be a valid mediafragment, but it doesn't look like it.  I'll update that to have the duration as the end time of that range.

**Comment by cjcolvar** [comment]
2nd issue fixed on mallorn.
