### ISSUE TITLE
Testing: Is MasterFile moved in the middle of a batch ingest for new batch process?

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2310]
### Description
When `master_file_strategy` is `move`, sometimes during the middle of a long batch ingest, a master file would get moved, thus failing the batch.

I assume the same problem might happen when `master_file_strategy` is `delete`.

### Done Looks Like
Batch ingest validation will fail if single file referenced in multiple rows.

### Tasks
- [ ] Manifest validation is updated to include error cases with a single file reference being present in multiple object rows

**Comment by joncameron** [comment]
This isn't  a case that would often be encountered in real life.

**Comment by davidschober** [comment]
@carrickr @cjcolvar  can you dig into this? Is this case still true with the rewrite? If not, feel free to abandon.

**Comment by cjcolvar** [comment]
@davidschober This scenario is still a possibility with the rewrite.  Is it still important to provide validation feedback to the user when the same file is used multiple times in a batch manifest?

**Comment by bkeese** [comment]
@carrickr Have you dealt with this in your recent batch work?

**Comment by phuongdh** [comment]
Discussion at standup today: find a real use case or won't fix. This is an edge case that may require major rewrite. Brian: this could be a problem when rerunning batches. Carrick: doc says you have to reupload when rerunning so we won't have this problem. Tabling this for now so we can make the deadline.

**Comment by davidschober** [comment]
this is a won't fix. We've never had this problem in the wild.
