### ISSUE TITLE
IIIF Fall 2017 Group Meeting Preparations

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2314]
### Description
Here are some highlighted notes from IIIF emails on where Avalon can prepare, and/or be informed of upcoming IIIF group meeting desired outcomes.   Maybe this helps as a reference item for the next 2 months?

#### LA Getty Meeting - September 25-27, 2017

> To prepare for the meeting, please think up your toughest use cases and bring them with you so that we can uncover any remaining problems and solve them if we can, and get the best use of face-to-face and pen-to-whiteboard time. Bring edge cases to model - they should be in scope, and complex enough to test the model we have so far. We’re hoping to use the time in LA to come up with a set of proposals that could be put to vote, and assemble a tight and productive agenda for the IIIF A/V Technical Specification Group meeting at the Toronto working session in October.

 
> To prepare for the discussions in LA, please review the following:
Overview of IIIF A/V scenario and considerations: https://docs.google.com/document/d/1X7b7zQGDsiEvAfvb1WboDXe360mz7Zmm0o0LT43nozk/edit#heading=h.j34yxgyeivy5
Draft of IIIF Presentation API v. 3: http://prezi3.iiif.io/api/presentation/3.0/
Avalon Media System experiments:
Code: https://github.com/avalonmediasystem/avalon-iiif-player
Demo: https://avalonmediasystem.github.io/avalon-iiif-player/build/
British Library tests:
Code: https://github.com/digirati-co-uk/iiif-av-bl
Demo: https://dev.filmicweb.org/clients/digirati/iiif-av-bl/
Experiments by Masahide Kanzaki: http://www.kanzaki.com/works/2016/pub/image-annotator?u=/works/2017/test/iiifav-bl-fixture-collection.json

> Thanks!
Sheila

@davidschober @joncameron @cjcolvar @mcwhitaker 

Related to #2294

**Comment by davidschober** [comment]
Thanks Adam!

**Comment by adamjarling** [comment]
Do we want our IIIF player/parser to handle sample manifests located at the British Library's testing ground?

https://dev.filmicweb.org/clients/digirati/iiif-av-bl/

Currently our parser is not set up to process their structure.  Assuming their structure is valid for IIIF A/V?

**Comment by cjcolvar** [comment]
I would wait and talk it over with them during the meeting.

**Comment by adamjarling** [comment]
Got it.

**Comment by mcwhitaker** [comment]
@adamjarling Those manifests are valid, but some of them are not use cases for Avalon, such as when you have multiple items are the same time. That is part of the discussion I was starting this morning: how far do we want to go with our player? We need to have that conversation at some point.

**Comment by adamjarling** [comment]
Yea, sounds good.  There are some standardizations which should probably be defined (and maybe they are but I just don't know about it), for example will `structures` or `sequences` or certain manifest fields always be an array, or can they sometimes be a single element object?  Basic patterns which if not clear in the upcoming spec, will probably frustrate client-side parsing applications.

**Comment by cjcolvar** [comment]
@joncameron @davidschober Mark as done because we're at the meeting now?

**Comment by joncameron** [comment]
@cjcolvar @davidschober 👍
