### ISSUE TITLE
MediaElement 4 - create SVG files for control buttons

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2317]
### Description
Need to create .svg files to represent MEJS4 control icons.  They're used as background images.

### Done Looks Like
MEJS4 player new plugin icons are sharp & crisp looking, and are .svg files.

### Tasks
- [ ] Create the .svg files for each icon
- [ ] Figure out how to get the files to display as background images in the Rails application (I tried this for half a day and could not get them to render).

**Comment by jlhardes** [comment]
@lealeelu - this looks like something you could take on!

**Comment by lealeelu** [comment]
@adamjarling, I'm pretty sure we set the svg's as background images through css, not rails.  Do you have a style in mind for new style of icons? I was just going to go to font awesome.

**Comment by adamjarling** [comment]
@lealeelu Yea, correct they are being used as CSS background images, which is fine.  I've been re-creating the current control icons (in MEJS2) for MEJS4 as .png files.   They're just a bit fuzzy.  I think MEJS needs an actual file for the icons when using as a control plugins.  So this might make using font-awesome css not the best approach, for hooking into how MEJS renders plugins.  I could be wrong, but just following the pattern of other MEJS4 community plugins... the control image file would be self-contained and not need a font-awesome dependency.

What would be great would be to simply create .svg graphics from the .png files located in this directory:
app/assets/stylesheets/mejs4/

Probably easiest is to just re-use the same icons as before, just create individual vector files for each?   White layer for the controls.   

If we wanted to consolidate and make a sprite single .svg file for all that's fine, or just individually creating them is probably fine for now as well.

Does this make sense?

**Comment by lealeelu** [comment]
Yup! I was wanting to make a single svg file and use an offset to line it up properly. Having it as a single svg would be nice because I can line them up and size them how I need. One of the biggest problems we had with the old player is that they were all kind of made in different ways and different sizes. It took a lot of finagling to get them to look right.

**Comment by adamjarling** [comment]
@lealeelu That sounds perfect!  Glad you're familiar with this approach's benefits.

**Comment by lealeelu** [comment]
Found the original svgs here: https://github.com/avalonmediasystem/mediaelement-skin-avalon/tree/master/app/assets/images/mediaelement-skin-avalon

**Comment by mcwhitaker** [comment]
@adamjarling @davidschober Player controls look good to me, but I don't remember seeing the problem before, so I may not be the best person to sign off on this.

**Comment by adamjarling** [comment]
@mcwhitaker I checked the source, and it's pulling the new .svg file.  So as long as visually it looks ok, I'd say we close this.
