### ISSUE TITLE
LTI doesn't login user in certain cases

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2319]
Reported bug:
A user who has never visited the Avalon instance tries to access Avalon via LTI within Canvas (iframe not new window) and ends up at the normal facet query but without any results because the user wasn't logged in.

This was reported on Chrome and reproduced on Safari on Mac (@jwd's machine and browserstack).

Steps to reproduce:
1) Clear cookies and cache
2) Go to canvas
3) Click on an embedded course

The underlying issue here is that Safari (and some versions of other browsers) will not accept cookies from iframes for sites that have never been visited before.  (One explanation of this here: http://labs.fundbox.com/third-party-cookies-with-ie-at-2am/)

Workaround right now it to visit Avalon before trying to load embed (including Canvas).

To solve this we'll either need to:
1) do some sorcery to get the user to view Avalon directly and then reload the embed context
2) make it so Avalon embeds don't need cookies

@pdinh has been working on approach #1.  I'm not sure if approach #2 is even feasible but if it is it might be larger/riskier than #1.

**Comment by phuongdh** [comment]
One possible workaround: if we detect cookie not being set, show flash message telling user to click a link, this link opens Avalon in a popup, the popup will auto-close immediately, then we tell user to hit F5. This is potentially a little jarring on mobile since the popup will be more noticeable.

Another workaround: have instruction for user to open Avalon in a separate window, then come back to Canvas and refresh.

**Comment by cjcolvar** [comment]
After exploring this today, I feel like the easiest and most robust solutions are:
1) Make sure all LTI links open in a new tab instead of iframe.
2) Have avalon determine when this secenario happens and display instructions like:
```
We couldn't log you in because you've never visited https://media.dlib.indiana.edu before.  Please click the link then come back and refresh the page.
```

Solution 1 will work in all cases but could be hard to ensure that all professors click the new tab checkbox when adding modules.  Solution 2 would always work but would be annoying/confusing to users.  It could be possible for solution 2 to be a safety net for solution 1.  I would advocate for this approach baring any new discoveries.

**Comment by cjcolvar** [comment]
@avalonmediasystem/product-owners What are your thoughts?  I would be happy to talk through this if things aren't clear from the comments above.

**Comment by joncameron** [comment]
I'm most interested in case 2 that Chris mentioned;  I like having a clear message to the user about what they need to do and why the content isn't showing up.  I think case 1 could be covered in documentation for teachers in Canvas that will eventually be written. Looking forward to 7.0 I think it would be ideal to solve this completely without workarounds, but I  don't think it's something that needs to be tackled in 6, especially with a stopgap measure that will work for now.

**Comment by Karthikeya212** [comment]
Tested with Chrome and Safari on Windows/Mac, didn't see any issue.

**Comment by Karthikeya212** [comment]
need to re-verify the warning message once

**Comment by Karthikeya212** [comment]
The warning message and the actions required are working on MCO-Staging, verified it on canvas-test.iu.edu

But there is no warning message seen on fluorine when checked with Spruce, and also there is no issue with login, it is logging in properly and the user is able to access the item.

**Comment by cjcolvar** [comment]
I'm seeing the same behavior.  Maybe the difference is that fluorine's canvas is HTTP only so maybe the Safari block only happens when the parent page is HTTPS attempting to embed an iframe of HTTPS.
@phuongdh how hard would it be to set fluorine up as HTTPS?
