### ISSUE TITLE
Make permalinks on mallorn resolvable

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2320]
### Description
The permalink configuration on mallorn is a dummy config and creates permalinks that aren't resolvable.  This has led to confusion and brokenness when testing.

### Done Looks Like
Mallorn changed to not create permalinks at all.

**Comment by joncameron** [comment]
Permalinks can be entered manually via the UI for testing. Since permalink generation is a local implementation issue, this could be tested on a staging environment for a production instance.

**Comment by cjcolvar** [comment]
Permalinks can be manually created on mallorn by appending the item or section id to `https://purl.dlib.indiana.edu/iudl/media/mallorn/`
For example:
`https://mallorn.dlib.indiana.edu/media_objects/pv63g038s/section/hh63sw02g`

**Comment by davidschober** [comment]
Permalink's were removed from Mallorn per @joncameron

**Comment by joncameron** [comment]
Someone updated the permalink resolver, so the structure that Chris commented with is being used at least for the media object.
