### ISSUE TITLE
I want to run Avalon feature tests on a Selenium grid in Docker

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2324]
So that we move away from PhantomJS and test javascript effectively.

### Tasks
- [ ] Add a Selenium grid to test.yml docker-compose file
- [ ] Enable remote testing on Avalon (spec helper)

**Comment by phuongdh** [comment]
Tabled for now. We'll keep using PhantomJS until maybe Avalon 7

**Comment by joncameron** [comment]
Still relevant?
