### ISSUE TITLE
MediaElement 4 - Refinement for Playlist Item Title Generation

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2326]
### Description
Implement work in #2249, into MEJS4.

### Done Looks Like
- Add to Playlist title input field is dynamically created, and follows the criteria outlined in #2249.

### Tasks
- Recreate functionality and naming scheme detailed in #2249 into MEJS4.

**Comment by joncameron** [comment]
Anyone can jump in on this ticket.

**Comment by Karthikeya212** [comment]
The ticket #2249 says that 
1. If there is only section in the item and if it doesn't have section label, when added to a playlist it should contain only the Media_object title without anything else appended (not even file name)  to it
2. But if there is a multi-section item and one of its sections doesn't have any structural metadata or a section label, so when it is added to the playlist it should have Media_object title + filename appended to it

But the current behavior is in contrast to the above intended behavior. In case "1", filename is appended to title and in case "2" only title is used if there is no section label

Look at the below screenshot. Object-5 here is from an item with only one section and no section label. Object-4 is from a multi-section item where this particular section has no label.
![image](https://user-images.githubusercontent.com/25850972/33725495-49e1eda0-db40-11e7-9792-2eb18cd809e6.png)

**Comment by Karthikeya212** [comment]
Note that the above mentioned behavior for case "2" is only seen if the unlabeled section is an audio file. For a video file it is appending the filename properly to the object title

**Comment by bkeese** [comment]
I have a new PR in for this (2516). It removes the filename for items with a single title-less, structure-less section. The problem with the audio item above isn't related to it being an audio item. In this context, audio and video items are treated the same. There is probably something else going on with that particular object, (maybe a label of " ", or a missing filename).
