### ISSUE TITLE
6.2 - Write upgrade documentation

### ISSUE THREAD

**Issue by lealeelu** [avalonmediasystem/avalon#2327]
### Description
Write instructions for upgrading from 6.1 to 6.2

### Done Looks Like
- Wiki contains a page (https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+6.1+to+Avalon+6.2)  on upgrading from 6.1. to 6.2, with steps

**Comment by cjcolvar** [comment]
There is a link at the top to [What's New in Avalon 6.2](https://wiki.dlib.indiana.edu/display/VarVideo/What%27s+New+in+Avalon+6.2) but it leads to a 404.

**Comment by phuongdh** [comment]
I created that placeholder so @avalonmediasystem/owners can create the page and fill in the details.
