### ISSUE TITLE
IIIF Player - Add support for thumbnail

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2342]
### Description
Add support in the IIIF player / parser for `thumbnail` property.  Example manifest created by @mcwhitaker here: http://dlib.indiana.edu/iiif_av/lunchroom_manners/lunchroom_manners_v4.json

### Tasks
- [x] Parser should extract a `thumbnail` value if it exists from a manifest canvas object.
- [x] If a value exists, this image should be used as the poster still for a video file.

@davidschober @joncameron FYI adding this to the sprint.

**Comment by cjcolvar** [comment]
@mcwhitaker Should the type be "Image" instead of "dcTypes:Image"?  That's what I'm seeing in the 3.0 docs: http://prezi3.iiif.io/api/presentation/3.0/#thumbnail.

**Comment by mcwhitaker** [comment]
@cjcolvar I don't know the answer to your question and I can't get to the prezi 3 documentation right now (site must be having problems). 

I see many manifests with dcTypes, but they are prezi 2. We have not explicitly talked about that change in the A/V meetings, but there have been other community calls where prezi 3 has been discussed, so you may be right. But without having access to the documentation, I can't tell.

**Comment by adamjarling** [comment]
@mcwhitaker @cjcolvar Are you both able to open this link?  ( http://prezi3.iiif.io/api/presentation/3.0/#thumbnail )   For past 2 days I cannot open it for some reason.
```
This site can’t be reached

prezi3.iiif.io’s server DNS address could not be found.
Search Google for prezi 3 iiif io api presentation
ERR_NAME_NOT_RESOLVED
```

**Comment by adamjarling** [comment]
@mcwhitaker Quick question on: http://dlib.indiana.edu/iiif_av/lunchroom_manners/lunchroom_manners_v4.json

Here `structures` is not at the root of the Manifest, but nested in a `canvases` array element.  Is this valid?   I'm trying to follow the Object model here (http://iiif.io/api/presentation/2.1/#b-summary-of-metadata-requirements), to see what's legal where, in order to keep the parser logic from ballooning.  Not sure if those tables at the bottom are just for Presentation API 2.0, or if they carry over to 3.0..., or quite possibly I'm just reading them wrong:)

**Comment by cjcolvar** [comment]
@adamjarling From what I can tell from the prezi 3 spec that manifest is invalid.  `canvases` should be `items` and `structures` should be at the root.

**Comment by mcwhitaker** [comment]
@adamjarling good catch! I have fixed it. It was a problem when adding ] and }...

**Comment by adamjarling** [comment]
@mcwhitaker @davidschober @joncameron @cjcolvar 

Note this currently only works for the specific instance of thumbnails present in:  http://dlib.indiana.edu/iiif_av/lunchroom_manners/lunchroom_manners_v4.json 

@cjcolvar has added the manifest option to mallorn, and I'm working now on updating the parsing to handle those manifests (ie. https://mallorn.dlib.indiana.edu/media_objects/0c483j54d/manifest).  There will be pretty big (and better) changes for the parser if the Mallorn manifests are more in line with what Avalon will provide looking forward.   Perhaps we'll have a better idea after the next few days out here.

**Comment by mcwhitaker** [comment]
@adamjarling I have changed http to https on the v4 manifest.
