### ISSUE TITLE
Testing the New Batch

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2350]
Batch format directions [here](https://wiki.dlib.indiana.edu/display/VarVideo/Batch+Ingest+Package+Format).

**Bad Sheet Errors**

Submit a sheet without a valid user.  This could be:
- User does not exist in the system
- User is blank
- User does not have permission to edit this collection

For the first two, the administrators of the Avalon instance should get an error email.  In the last case the user and the administrators should get an error email.

**Bad Rows on a Sheet**
- Row lacks minimum metadata (bibid or title and date issued)
- Row lacks an actual file (the audio/video file referenced in the sheet does not exist on disk)

User should get an email indicating which rows failed and which rows succeeded 

**Other Errors**
- A corrupted file (fails in transcode)

User should get an email indicating which rows failed and which rows succeeded 

**Stalled Testing**
TBD

**Comment by joncameron** [comment]
Very stale!
