### ISSUE TITLE
Fix Test Coverage on AWS Pull Request

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2353]
Deal with missing test coverage in the AWS PR (2348).

**Comment by carrickr** [comment]
Initial meeting schedule

**Comment by cjcolvar** [comment]
Seems like we might want to write tests for these classes:
- [ ] SecurityHelper
- [ ] FileLocator
- [ ] Course.unlink_all and corresponding job?
- [ ] MasterFileBuilder?
- [ ] UploadFormHelper
- [ ] SolrCollection classes?

**Comment by cjcolvar** [comment]
Other possible things to test:
- [ ] ApplicationController changes
- [ ] BatchIngestJob
- [ ] DeleteOldSearchesJob
- [ ] MFManagementJobs
- [ ] S3SplitJob
- [ ] SolrBackupJob?
- [ ] Admin::Collection.create_dropbox*
- [ ] MigrationTarget
- [ ] ElasticTranscoderJob?
- [ ] SolrCollectionAdmin, SolrCollectionCreator, SolrConfigUploader
- [ ] BetterActiveElasticJobAdapter

**Comment by cjcolvar** [comment]
Maybe we should skip the ActiveJob and ActiveEncode classes?
