### ISSUE TITLE
Setup AWS instance of Avalon for testing

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2358]
### Description
Post merge of #2348, setup an Avalon instance for regression testing (#2357)

### Done Looks Like
- Setting up on Spruce
- Setting up on AWS

**Comment by phuongdh** [comment]
Now on AWS: http://avalonappz.avaloninfr.avaloncloud.party/

**Comment by joncameron** [comment]
Login bug needs review on this before closing.
