### ISSUE TITLE
Different player design underlying the original Avalon player

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2362]
### Observations
There is an underlying player control which opens a player with different design. It gets activated by clicking on certain area of the original player. Though not very evident, but it might be seen at times when user is trying to play/pause an item by clicking on the player rather than button.

## Steps
1. Open an item in Avalon and start playing.
2. While the item is playing hover the mouse on the player, at some area in the center of the player the mouse cursor turns into a hand symbol, click when this happens.
3. The player goes into a full screen mode, and it has only audio and full screen icons, that too not similar to the original player (see the player control bar in below image).

![image](https://user-images.githubusercontent.com/25850972/31031163-eeece756-a525-11e7-975a-0afea07ff1ce.png)

**Comment by joncameron** [comment]
No longer relevant.
