### ISSUE TITLE
MediaInfo Git History Has Been Written, May Cause Issues for Current Users

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2367]
Situation is that we install MediaInfo by directly calling its git repo:

```
gem 'mediainfo', git: "https://github.com/avalonmediasystem/mediainfo.git", branch: 'remote_files'
```

This results in the Gemfile.lock ending up with a specific git commit, such as:
```
GIT
  remote: https://github.com/avalonmediasystem/mediainfo.git
  revision: aaa6464976764857c2a9d178b12c70542b11a9b3
  branch: remote_files
  specs:
    mediainfo (0.7.1)
```

This week, MediaInfo's git history got rewritten slightly, and some commits went away.  Developers saw this on Tuesday when we had issues running tests on the new AWS Branch, due to the `Gemfile.lock` referencing a commit, `f6d7a14c5035effc9eb9986ff56621b020ebc27f` that can't be parsed.  When NU autodeployed Avalon last night the same bit us:

```
  + bundle install
  Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
  installing your bundle as root will break this application for all non-root
  users on this machine.
  Warning: the running version of Bundler (1.15.0) is older than the version that created the lockfile (1.15.1). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
  Fetching gem metadata from https://rubygems.org/.......
  Fetching version metadata from https://rubygems.org/..
  Fetching dependency metadata from https://rubygems.org/.
  Fetching https://github.com/avalonmediasystem/avalon-workflow.git
  Fetching http://github.com/projecthydra-labs/active-encode.git
  Fetching https://github.com/avalonmediasystem/mediainfo.git
  fatal: Could not parse object 'f6d7a14c5035effc9eb9986ff56621b020ebc27f'.
```

The good news is the revision we shipped 6.1 with still appears to work, I ran the following after checking out the 6.1 release commit:
```
CROGERS-MAC:avalon clr5101$ bundle exec gem pristine mediainfo
Restoring gems to pristine condition...
Cached gem for mediainfo-0.7.1 not found, attempting to fetch...
Fetching: mediainfo-0.7.1.gem (100%)
Restored mediainfo-0.7.1
```

However anyone who has `bundle updated`or otherwise messed with their gemfile may have picked up one of the commits who has been rewritten out of history.

The fix is to edit their `Gemfile.lock` so that the revision for mediainfo is:
```
revision: 5e28f2b58cefb20b6e06f022256ea1d13b761b1f
```

Note this would not immediately break in production, it would just break future deploys if they have a bad revision in their `Gemfile.lock`.

Also while we control MediaInfo, we're merely forking someone else's MediaInfo, so we can't cut releases at will.  However we could potentially be more careful/have stricter practices about having a `master` branch that is referenced in releases and its history is untouchable.  Right now even on release we're pointing to a specific feature branch of our fork, which is all well and good until we forget production systems reference this branch.

**Comment by cjcolvar** [comment]
The version of mediainfo shipped with 6.1 was the tag 'avalon-r6.1' from the avalonmediasystem fork.  Avalon 6.2 shipped this same version of the gem.  The 'remote_files' branch was merged yesterday into the 'avalon_fixes' branch as part of the AWS PR (#2348).  So the changes in 'remote_files' now live in 'avalon_fixes' and will until a new tag is cut for Avalon 6.3.

**Comment by carrickr** [comment]
Did we ever tell anyone to switch over to remote_fixes though to get bugs?  If we didn'tthen this can close

**Comment by cjcolvar** [comment]
I don't think anyone but NU used this branch so I'm :+1: to closing it.

**Comment by joncameron** [comment]
Closing as per discussion above.

**Comment by mbklein** [comment]
Confirming that no one but NU used the `remote_files` branch.
