### ISSUE TITLE
Cannot access audio files while using the playlists shared with its sharewith or LTI link

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2376]
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Testing fix for bug #2333 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10
Issue: Cannot access audio files while using the playlists shared with its sharewith or LTI link. Note that an Admin user is able to perform the same operation without any issue.

### Steps to reproduce
1. Create a shared playlist and add video and audio files to it.
2. Share the playlist using share with or LTI link with the avalon users who has valid access to the files.
3. Login with the avalon user and access this playlist.
4. Click on the audio items present in the list or wait for the auto-play to reach that audio file. The control is navigated to the homepage saying that the user is unauthorized.
5. Whereas the user can play the same item if he has created his own playlist with the same items.

**Comment by cjcolvar** [comment]
I think this may have been fixed with #2405.  Can you retest?

**Comment by Karthikeya212** [comment]
Tested it on spruce and is working fine
