### ISSUE TITLE
Sorting on Tags column in playlist table is not happening as expected

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2378]
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Testing the ticket #1538 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10
Issue: Sorting on Tags column in playlist table is not happening as expected.

### Steps to reproduce
1. Create a set of playlists, some with tags and some without tags.
2. Go to the playlist table and click on Tags column to sort the table with respect to Tags.
3. We can see that the rows with tags are placed in the middle of the rows with no tags which is not a correct sorting order.
![image](https://user-images.githubusercontent.com/25850972/31512731-fccb3178-af59-11e7-8811-730c9039d704.png)

**Comment by bkeese** [comment]
I have not been able to duplicate this problem on Spruce or locally.

**Comment by Karthikeya212** [comment]
I think it is the effect of having older playlists that were created before this change is deployed to the server, because those are the ones that are not sorted correctly.

![tag_sort.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58a747faca210c2000ae4f77/125516c66e82c728ace21e0d46fc959d1c918cbb9babf301b44fff9e2c4533317346f67c2483b27abc1b7f02590d4fae415f5f40f9a8df2ca6b02e6c981e5ab38532022d8c6853beb2901eb60bbb258b488cb6ba8c4bc4eb342df5c6.PNG)

**Comment by Karthikeya212** [comment]
Is this an issue that is to be taken care of?
If not please close this.

**Comment by bkeese** [comment]
This makes sense. Default tag values for existing playlists weren't set to a serialized empty array. Older playlists should behave correctly once tags are added to them.

**Comment by cjcolvar** [comment]
Sounds like we need a migration then to initialize any existing playlists.  This should be pretty easy.

**Comment by joncameron** [comment]
Abandoned - new issue is #2411
