### ISSUE TITLE
As a user I want to be redirected to new pid or see better error message when I visit a Fedora 3 style link

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2381]
Currently if I go to an old pid link, eg https://media.dlib.indiana.edu/media_objects/avalon:123456, I get a 500.

Ideally, I should be redirected to the correct item if possible (can be done using information from the migration table), if not, I should get an 410 Gone/404 Not Found, or a more explanatory error message.

**Comment by cjcolvar** [comment]
@mbklein added something to handle this, but it seems like it needs a little more to make it more fault tolerant as ids that don't exist throw an exception.(https://github.com/avalonmediasystem/avalon/blob/develop/app/controllers/application_controller.rb#L38-L43)
This could also be DRY'd up with the code in ObjectsController unless we want object type validation.

**Comment by cjcolvar** [comment]
This is causing errors in our fedora log due to treeifying the fedora 3 pid (`/av/al/on/:1/avalon:123456`) and having a bad path segment (`:1`) leading to the following error:
```
ERROR 08:00:11.154 (FedoraInvalidNamespaceExceptionMapper) NamespaceExceptionMapper caught an exception: Empty namespace in :1
```

**Comment by joncameron** [comment]
Timeboxed to 2 points; if we can do it the ideal way, we can return a 404 as per Chris' mention rather than a 500.

**Comment by joncameron** [comment]
We should probably support embeds for the same as well.

**Comment by cjcolvar** [comment]
Tasks:
- [ ] Write a test
- [ ] Implement fix

**Comment by cjcolvar** [comment]
Happens for MediaObjectsController, MasterFilesController, Admin::CollectionsController

**Comment by phuongdh** [comment]
https://spruce.dlib.indiana.edu/media_objects/avalon:2017 is redirecting correctly to https://spruce.dlib.indiana.edu/media_objects/xw42n7934
