### ISSUE TITLE
CSS issues in Manage Files page

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2386]
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Regression 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10
Issue: CSS issues in Manage Files page

### Steps to reproduce
1. Go to Manage Files page
2. try to upload a file, you can see that the upload text is not visible on that button.
![upload_button](https://user-images.githubusercontent.com/25850972/31557146-ab946588-b015-11e7-8581-de51f3d98f7f.PNG)
3. After uplaoding files we can see that the files list is misaligned.
![misaligned_fileupload](https://user-images.githubusercontent.com/25850972/31557169-b9a6f6b8-b015-11e7-8672-d6a93c9d6d61.PNG)

**Comment by bkeese** [comment]
I think this happened here: https://github.com/avalonmediasystem/avalon/commit/b3cf0e2104b0eadfba5fbf5f576d3b9decbdb06a#diff-2feec9d9c794c2e06944abc8bf5b1211

**Comment by cjcolvar** [comment]
AWS merge cleanup.

**Comment by cjcolvar** [comment]
Looks like the table of associated files missing is introduced here: https://github.com/avalonmediasystem/avalon/commit/87fee337fd36488083416f450d25d8e2ae8c754a#diff-2feec9d9c794c2e06944abc8bf5b1211L36
@mbklein maybe there is some CSS that is missing that handles this move from a table to hierarchy of divs?

**Comment by cjcolvar** [comment]
I wonder if the upload button being different is due to jquery.fileupload.js being included: https://github.com/avalonmediasystem/avalon/pull/2348/files#diff-32d082be9e44d95fd236b839a7b110f5
@mbklein Is that plugin for browse everything or the normal file upload?

**Comment by cjcolvar** [comment]
Nevermind that last comment...it looks like the change is in the file_upload partial due to bad merging.

**Comment by adamjarling** [comment]
Just made a push to this branch to fix the styling issues for "Associated Files"

**Comment by Karthikeya212** [comment]
This looks good on spruce
