### ISSUE TITLE
Hidden items are appearing in Search results

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2388]
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Regression 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10
Issue: Hidden items are appearing in Search results, both for collection staff and also for the users with special access.

### Steps to reproduce
1. Edit an item and add special access to an avalon user.
2. Select the check box "Hide this item from search results" and click on Save.
![image](https://user-images.githubusercontent.com/25850972/31563183-0733484e-b02c-11e7-8b5c-55b7b2b004de.png)

3. Make sure the item is published.
![image](https://user-images.githubusercontent.com/25850972/31563233-2f8d74b8-b02c-11e7-82a8-8d41c878f4e3.png)

4. Login with a collection staff or the avalon user with special access and search for the item.
![image](https://user-images.githubusercontent.com/25850972/31563290-66291c52-b02c-11e7-83d8-9b5e3da5b7b1.png)

**Comment by cjcolvar** [comment]
Bug previously discussed in #1758.

**Comment by joncameron** [comment]
Not a use case valuable enough to put time towards fixing this, in addition to technical complexity that Chris could elaborate on.
