### ISSUE TITLE
Batch ingest going into a loop and ingesting the same items multiple times

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2390]
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Regression 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10
Issue: Batch ingest going into a loop and ingesting the same items multiple times

### Steps to reproduce
1. Create a manifest file and start the batch ingest using it.
2. Keep checking the e-mail notifications and the ingest process in avalon.
3. Multiple mails will be coming saying that batch process is successful, and can observe the same item ingesting multiple times in the collection.

**Comment by Karthikeya212** [comment]
Tested this on Spruce, the manifest file is being deleted abruptly and the batch is terminating.

1. Tried to ingest a manifest containing 5 items --> Received a "successfully registered" mail -->  It ingested one item and the process terminated --> checked that the manifest file is no longer present in the dropbox folder.

2. Tried to ingest a manifest containing 5 sections in a single item ->  Received a "successfully registered" mail -->  Item ingest didn't start --> checked that the manifest file is no longer present in the dropbox folder.

**Comment by carrickr** [comment]
Opened #2410 to handle the new bugs and avoid a zombie issue
