### ISSUE TITLE
Captions are misaligned in full screen mode after auto switching in playlist

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2393]
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Regression 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10
Issue: Captions are misaligned in full screen mode after auto switching in playlist

### Steps to reproduce
1. Add multiple items that have captions to a playlist.
2. Start playing an item, turn on captions and click the full screen icon.
3. After the item completes playing it switches to the next item and start playing it. The player will still be in full screen mode after switching but the captions icon will be turned off by default.
4. Turn on the captions icon still being in full screen mode, we can see that the captions will be displayed to the left of the screen.
![image](https://user-images.githubusercontent.com/25850972/31624122-99b1686e-b26f-11e7-9b25-47dfd63dbad5.png)

**Comment by davidschober** [comment]
@Karthikeya212 this is ME2 correct? if so, let's close  and we'll fix in me4

**Comment by Karthikeya212** [comment]
Yeah this is ME2, I will close it then.
