### ISSUE TITLE
Ingest Issues With Batch, Does not Start for multiple items

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2410]
_Reported via @Karthikeya212 in #2390, moving over here to avoid zombie issues:_

Tested this on Spruce, the manifest file is being deleted abruptly and the batch is terminating.

Tried to ingest a manifest containing 5 items --> Received a "successfully registered" mail --> It ingested one item and the process terminated --> checked that the manifest file is no longer present in the dropbox folder.

Tried to ingest a manifest containing 5 sections in a single item -> Received a "successfully registered" mail --> Item ingest didn't start --> checked that the manifest file is no longer present in the dropbox folder.

**Comment by cjcolvar** [comment]
I just ran a batch with one item with 3 sections and all 3 started processing and another batch with a single section and it worked as expected.  I didn't test multiple items in a single batch. 
 @Karthikeya212 could you test this again?  Maybe I could be with you when you do it so I can watch the server while the batch is processing.

**Comment by Karthikeya212** [comment]
@cjcolvar The batch ingest is working properly now, I don't know what could be the issue on Friday, if you want to check any logs from Friday check for the collections "Batch test" (5_item_batch.csv) and "Batch retest" (5_section_batch.csv)
