### ISSUE TITLE
Avalon Website: project page missing infographic

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#2412]
On this page of the Avalon website: http://www.avalonmediasystem.org/project

There is a mention of an infographic, but the infographic is missing:

![image](https://user-images.githubusercontent.com/16720883/31905663-e76bf3a2-b7fc-11e7-8bec-6cf82f3713a7.png)

**Comment by mschnaars** [comment]
I'm unsure what the original infographic was; the image is not displaying on previous versions of the page. Was it either of these?
![AvalonArchitectureUpdated.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58e6579415c1c60020714827/125516c66e82c728ace21e0d46c9829b2f8d8d889deab74ab058f3803c5422463900a23f7581a164fd52690e050a1de853524d41fbfddf2aa4e53524d95a59ecd36d5874c23840fabf8219ad1da862da11d1e9e1d30695aa2f2ff58a88453f1b051081f95e37a8914cc851e406.png)
![LifecycleInfographic.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58e6579415c1c60020714827/125516c66e82c728ace21e0d46c49d9c26819aaa83ec964da252f78628562f7a2a46ef696097ec22ba416f43554d4bab450e5e46aff0dd78a0e43d728a5b0be9d43c0973c63b03b0aac04ee155e57dd205d0f4ae805ec1ef3724e28b8747381d071081f95c36b2d4.jpg)

**Comment by mcwhitaker** [comment]
@mschnaars I think it was the Lifecycle infographic.
