### ISSUE TITLE
Batch ingest failing to read/register properly the manifest file with 1000 items

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2423]
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Batch Ingest 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10

Issue: 
Batch ingest failing to read/register properly the manifest file with 1000 items.
It is throwing an error “To successfully ingest, either title and date issued must be set or a bibliographic id must be provided” in the logs.
Even though I received a successful registration mail it seems like all the fields are not read properly.
![image](https://user-images.githubusercontent.com/25850972/32056249-32679136-ba32-11e7-8e65-5339470072e6.png)

Note: The same file with less number of items is working fine, and the items are ingested properly.

**Comment by joncameron** [comment]
Chris reviewed the spreadsheet and didn't find an issue with the manifest, but @Karthikeya212 will be attaching it to this issue in case someone else finds anything off in it that might cause this error.

**Comment by Karthikeya212** [comment]
manifest file with 1000 items
[mirrorbatch_1000_items.zip](https://github.com/avalonmediasystem/avalon/files/1418872/mirrorbatch_1000_items.zip)

**Comment by davidschober** [comment]
We will timebox investigation/fix at three. If we can't get it solved. Pause, and write what we know in new issues.

**Comment by cjcolvar** [comment]
I tried this on spruce with a new spreadsheet that had only `Title` and `Date issued` (and file validation and ingestion disabled during the test) and everything worked fine with the exception of DB errors related to spruce using sqlite and which were resolved when I reran the failed jobs via resque's UI (https://spruce.dlib.indiana.edu/jobs).
