### ISSUE TITLE
MEJS4 - Dynamically add source type to video (and audio?) HTML tags

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2425]
### Description
Currently the Javascript code which renders an a HTML `<video>` or `<audio>` element hardcodes the `type` attribute.

```
currentStreamInfo.stream_hls.map((source) => {
        markup += `<source src="${source.url}" type="application/x-mpegURL" data-quality="${source.quality}"/>`
      })
```

If that data is supplied in the media object data coming from the server, we should use the value passed in instead of hardcoding.  

### Tasks
- [x] Check if the media source type is being passed into the Rails view / front-end (ie. application/x-mpegURL)
- [ ] If so, use the value passed in

**Comment by adamjarling** [comment]
Related to #2346

**Comment by adamjarling** [comment]
@cjcolvar @bkeese Currently we're setting the `<video type=` the following way:
```
<source src="<%= hls[:url] %>" type="application/x-mpegURL" data-quality="<%= hls[:quality] %>"/>
```

Do we want to leave this hardcoded, or base it off the hls `mimetype`?  For a media object, here's what the hls object looks like:
```
hls
{:quality=>"high", :mimetype=>"video/mp4", :format=>"video", :url=>"http://streaming:8880/avalon/04b77e85-1bf2-4232-b1d0-2b472c4791e0/f4ba5c28-7129-4689-a8ad-db243222bf4a/big_buck_bunny.mp4/index.m3u8?token=88e6fa1cd793c2972302e60a39de58aa03953aeb"}
```

I was thinking for this story we'd want to use the value from the media object (which I thought might be `video/mp4` from an unrelated IIIF video issue), but maybe that's not how we want to handle here?

**Comment by cjcolvar** [comment]
I think we need it to be `application/x-mpegURL` for MEJS to work for HLS but our metadata might be wrong.  We should probably have a data migration that fixes all of these but I'm a little hesitant because I'm not sure if we're assuming the `video/mp4` value elsewhere in the code.

I'm not understanding the problem that is trying to be solved here.  Could you give me some more context?

**Comment by adamjarling** [comment]
@cjcolvar Ok that makes sense and I'll leave as-is for now.  I created this ticket, due to some odd behavior between MEJS4 and the IIIF Avalon player, dynamically populating the `type` when destroying/creating instances of the player in same browser window.  My concern was we weren't seeing this in the Avalon player, because those `type` attributes were hard-coded in.

I'll just close this ticket.  As long as our Avalon MEJS 4  player is playing HLS correctly, no need to rock the boat.

**Comment by cjcolvar** [comment]
I think that sounds good and we can work on addressing this in Avalon 7 and the IIIF player if necessary.
