### ISSUE TITLE
MEJS4 - Investigate best way to break down JS player wrapper into smaller modules

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2426]
### Description
The primary MEJS4 player javascript wrapper file is getting too large.  app/assets/javascripts/media_player_wrapper/avalon_player_new.es6  

This is due to tight coupling between "Sections" transition behavior and the player.  Should Sections code be it's own file/module?  Ideally yes, but...

### Tasks
- [ ] Investigate ways to use standard `require` functionality with the sprockets-es6 gem.  I've tried but can't seem to get it to work and it may be due to the version of Rails we're running?
- [ ] Test out creating a separate JS file which houses pure functions which won't mutate state.  Pull this file into the app via global namespace, and extract non-state related functions to this file.  

Both of these options above will make the main JS wrapper file (who's job is to tie MediaElement4 to our app) more lightweight and easier to navigate around.

**Comment by davidschober** [comment]
@adamjarling did this refactor already happen? Or can we wait until after 6.3 ?

**Comment by adamjarling** [comment]
I think this should happen asap.  In order for this to happen in an efficient way, I'd like to pull in Brian, Chris or Phuong and help me see if there's an alternate gem we can use for ES6 JS in our version of Rails.  The current gem doesn't seem to allow local imports, or requires, or I haven't been able to get it working.

**Comment by davidschober** [comment]
Cool. I'll move it to the top.
