### ISSUE TITLE
Import button is missing in Resource Description page

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2432]
### Descriptive summary
Server: http://avalonappz.avaloninfr.avaloncloud.party
Testing: Regression on AWS 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10
Issue: Import button is missing in Resource Description page.

### Steps to reproduce
1. Start creating an Item.
2. After uploading files in Manage Files page, go to Resource Description page, you can see that there is no import button to import the metadata for the item.
![image](https://user-images.githubusercontent.com/25850972/32339252-97227564-bfcd-11e7-97dc-1351104d2fbb.png)

**Comment by davidschober** [comment]
Specific to AWS.

**Comment by bkeese** [comment]
Bib import must not be configured on this AWS app. We should configure it first, then test it.
