### ISSUE TITLE
Unable to remove a captions file once it is uploaded

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2433]
### Descriptive summary
Server: http://avalonappz.avaloninfr.avaloncloud.party
Testing: Regression on AWS 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10
Issue: Unable to remove a captions file once it is uploaded.

### Steps to reproduce
1. Create an Item and upload a captions file in the Structure page.
2. Go to the preview and verify if the captions are displayed.
3. Go again to the Structure page and try to remove the captions file, it is navigating to an error page.

**Comment by bkeese** [comment]
I replicated the error, but don't know how to check the logs for the AWS app.
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57597e546b48630e00666b0c/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f47f76d4b12be64678570d5e4cac46585b41adaf8e2ba0a42062c80d55b98e30063e937f03a6aa8317b500bf21884d83b0bf8d48c8e83a37aa.PNG)
