### ISSUE TITLE
Batch ingest is not working in AWS

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2435]
### Descriptive summary
Server: http://avalonappz.avaloninfr.avaloncloud.party
Testing: Regression on AWS 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10
Issue: Batch ingest is not working in AWS

### Steps to reproduce
1. Go to the S3 bucket of the collection.
2. Upload the media files and after they are done uploading, then upload the manifest file.
3. After a while refresh the page, you can see manifest.error file generated.
4. Following error is observed in logs 
[2017-11-02T20:08:51.013336 #24276] ERROR -- : NoMethodError: undefined method `ingest_package' for #<Avalon::Batch::Ingest:0x00007f92cce7e6e8>

**Comment by davidschober** [comment]
@phuongdh do you have it wired up the same way as NU @mbklein or @carrickr can you assist?

**Comment by davidschober** [comment]
is this a documentation issue?

**Comment by davidschober** [comment]
This seems like it's an odd issue with not launching latest code. It might be pointing to the wrong place, or it's screwy.

**Comment by davidschober** [comment]
@phuongdh can you verify that this is still valid? Batch works fine at NU?

**Comment by davidschober** [comment]
@carrickr to pull new batch job back to core.

**Comment by joncameron** [comment]
PR #2775 is still in needs review.

**Comment by davidschober** [comment]
stale
