### ISSUE TITLE
Item information icon is not visible in the embedded player of AWS

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2436]
### Descriptive summary
Server: http://avalonappz.avaloninfr.avaloncloud.party
Testing: Regression on AWS 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10
Issue: Item information icon is not visible in the embedded player of AWS

### Steps to reproduce
1. Embed an avalon item in any page.
2. Make sure you login to the avalon and the media item is playable on that page.
3. We can see that the item information icon is not visible on the player.
![image](https://user-images.githubusercontent.com/25850972/32383575-be672d42-c08e-11e7-88c7-11ed109182dd.png)

**Comment by davidschober** [comment]
@Karthikeya212 was this true in ME4?

**Comment by davidschober** [comment]
in ME4 we don't have the feature turned on yet. In MEjs2 we think that it's post. If that's getting used the icon is not in that packet. It seems to be an asset problem. We should change this into make ME4 use logo plugin.

**Comment by cjcolvar** [comment]
I believe this was fixed with #2493.
