### ISSUE TITLE
Item selection in Managed Selected Objects page clearing after performing a Move operation.

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2437]
### Descriptive summary
Server: http://avalonappz.avaloninfr.avaloncloud.party
Testing: Regression on AWS 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10
Issue: Item selection in Managed Selected Objects page clearing after moving them to a new collection.

### Steps to reproduce
1. Select some items and go to Managed Selected Objects page.
2. Move the selected items to a different collection or even same collection.
3. Click on any other action button (preferably Update Access Controls button as it creates a pop up), we can see that the pop-up displays that there were no items selected.
4. The items will be removed from that page if you refresh it.

**Comment by Karthikeya212** [comment]
Note: This behavior is not seen for Admin users, but can be observed for all remaining roles

**Comment by davidschober** [comment]
is this a blacklight core bug?

**Comment by joncameron** [comment]
Unable to reproduce.
