### ISSUE TITLE
Manager is unable to add markers for playlist items

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2439]
### Descriptive summary
Server: http://avalonappz.avaloninfr.avaloncloud.party
Testing: Regression on AWS 
Browser: Chrome 62
Operating System: Windows10
Issue: Manager is unable to add markers for playlist items. All the remaining levels users are able to perform this action.

### Steps to reproduce
1. Login to avalon with a manager level user.
2. Create a playlist and add items to it.
3. Go to the playlist, start playing the items and try to add markers.
4. It is returning an unauthorized user exception.

**Comment by cjcolvar** [comment]
This might be fixed and should be retested when the AMS testing site is update with latest from develop (#2562).

**Comment by joncameron** [comment]
@davidschober will test on NU staging and close when they're verified as fixed.
