### ISSUE TITLE
IIIF Player not rendering the player

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#2440]
### Description 
Looking at the Sample Page (https://github.com/avalonmediasystem/avalon-iiif-player/wiki/IIIF-AV-Sample-Manifests), the video samples have been updated to the current state of the IIIF Prezi 3 spec. Those manifests are not working fully in the IIIF Player; more specifically, the player is not being rendered.  

I also tested the lunchroom manners v4, which used to render and play correctly, and it is no longer rendering correctly.

### Done looks like
- [x] we either determine that the manifests are wrong or we fix the player such that they successfully render and play
- [x] Remove the sample manifests which are now in the "old" IIIF structure

**Comment by adamjarling** [comment]
@mcwhitaker @davidschober @joncameron I made some updates to the parsing to reflect the latest manifest version, but there are some issues with MediaElement playing the file types across Chrome/Safari/Firefox/Edge.    We should create another ticket to investigate what's going on.  Whether it's the way MEJS4 is instantiating somehow, or whether there is a file type / HLS issue I need to know more about.

**Comment by mcwhitaker** [comment]
@adamjarling I am fine with closing this one if you want to create the ticket to solve the problem. The work today has helped understand that the manifests are not the problem. Thank you for your help.
