### ISSUE TITLE
Observations for Avalon testing on iPad

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2442]
### Observations

1. Options on   homepage not visible in normal mode, but are visible in portrait mode.
![image 1](https://user-images.githubusercontent.com/25850972/32673413-1f30f5e8-c61d-11e7-8028-be428321f807.png)
![image 2](https://user-images.githubusercontent.com/25850972/32673417-23286096-c61d-11e7-839a-37c875dbe264.png)

2. In full-screen mode player options are overridden with default player options of safari. The captions are not working even if there is a captions icon for safari. And the Quality/Scrubber/Thumbnail icons cannot be accessed.
![img_20171109_112135](https://user-images.githubusercontent.com/25850972/32673517-8e03ff74-c61d-11e7-89ff-8db84db77ef7.jpg)

3. Browse and Search options are misaligned sometimes in normal mode.
![image 5](https://user-images.githubusercontent.com/25850972/32673606-d7a0d3dc-c61d-11e7-86e3-db720986e5d9.png)

4. Player control panel not auto-hiding when the item is playing.

5. Audio icon not visible in the player (similar to flash issue in chrome)

6. Default playlist displayed is the add to playlist option, which doesn't allow to add
![image 7](https://user-images.githubusercontent.com/25850972/32673721-35476e60-c61e-11e7-900d-650e61b589da.png)

7. Embed player icon panel is misaligned. There is a blank space left below the assigned window size.
![image 8](https://user-images.githubusercontent.com/25850972/32673777-554d9982-c61e-11e7-921d-d3596afeb589.png)

8. Playlist options are misaligned in normal mode.
![image 9](https://user-images.githubusercontent.com/25850972/32673824-82143160-c61e-11e7-99ed-0f9199a473e1.png)

**Comment by davidschober** [comment]
This looks like a bigger styling issue.
