### ISSUE TITLE
IIIF Avalon Player - investigate playback issues

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2448]
### Description
There are some inconsistencies in playback of most recent manifest structure for the IIIF Avalon player.  This issue is due to either how we're creating an instance of MEJS4, or something in the file type being declared in the `<video>` source.

### Tasks
- [ ] Investigate using a default instance of MEJS, minus any customizations, directly including media file and file types in the source.
- [ ] ...more

**Comment by davidschober** [comment]
I'm going to abandon this. We can come back at it later.
