### ISSUE TITLE
Username shows up as a number instead of email

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2449]
After the recent AWS branch merge, new user shows up as the row id, e.g. "41", instead of the email, e.g. "archivist1@example.com". 

I believe this is a user_key setting in Devise and it should default to email..

**Comment by cjcolvar** [comment]
I have a fix for this and will create a PR today.

**Comment by davidschober** [comment]
This bug was introduced when we added AWS. If new stuff was created between the merges, they have to go back and fix.
