### ISSUE TITLE
Migrate Pawpaw Content to Demo box

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2453]
### Description
Moving the existing content in Pawpaw that should be retained (demos, teaching materials etc.) to our demo instance in the cloud. Right now there's a mix of Avalon project content and some sandbox-y stuff (200 GB worth of streams) in the instance.

### Done Looks Like
- Put up banner to let user know about their content going away.
- Put in redirects for content
- Clean up all items that aren't Avalon
- Reingest a few items that may be missing
- Work with @joncameron  to ensure we know what needs to be retained so that no content is broken
- Jon will email users to give them a heads-up

**Comment by phuongdh** [comment]
CAS login config is currently tied to IU and has sensitive info, probably best to not deploy/bundle it with Turnkey. 

We could switch demo to identity auth, use Persona to send out invites to current users, delete them. When they sign up they'll have their content back.

**Comment by joncameron** [comment]
???

**Comment by phuongdh** [comment]
New content is still coming in to pawpaw recently. If not losing content is important, do we need to lock it down before migration?

**Comment by joncameron** [comment]
As long as we have a banner up and users are notified, losing this content shouldn't be an issue since this is an evaluation site. And the current users will be emailed.

**Comment by phuongdh** [comment]
Objects seem to keep their ids so we'll just have to domain forward pawpaw to demo and be done.

**Comment by phuongdh** [comment]
Waiting to hear back from existing users to clean up non-Avalon content.

**Comment by phuongdh** [comment]
Also need to decide which collections will be featured on the home page

**Comment by cjcolvar** [comment]
Blocked by #3945

**Comment by phuongdh** [comment]
Waiting for pawpaw redirect
