### ISSUE TITLE
Provision AWS Services for Pawpaw Cloud Instance

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2454]
## Description
In order to show how well our new turnkey works, we will cut over pawpaw to aws. The goal is to have a proved and battle-tested solution. 

## Done looks like
- [x] Run turnkey Terraform script
- [x] ~~migrate data~~
- [x] cut over dns/ and / or rename 
- [ ] ~~burn down pawpaw~~

**Comment by davidschober** [comment]
child of https://github.com/avalonmediasystem/avalon/issues/3230

**Comment by phuongdh** [comment]
Updated Terraform script to deal with DNS wrangling a bit better. Fixed bug in cert validation.

Live now with basic functionalities working: https://demo.avalonmediasystem.org

**Comment by phuongdh** [comment]
Migrated most data over. Need to configure CAS.

**Comment by phuongdh** [comment]
pgloader script:

```
LOAD DATABASE 
	FROM 	mysql://root:******@mysql/avalon
	INTO 	postgres://dbavalon:******@avalon.something.rds.amazonaws.com/avalon
WITH prefetch rows = 10000
alter schema 'avalon' rename to 'public';
```
