### ISSUE TITLE
Quality icon panel is not enabling for embedded mejs4 audio player

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2456]
### Descriptive summary
Server: Spruce
Testing: Mejs4 Embed player
Browser: Chrome 62.0.3202.94, Firefox 56.0.2
Operating System: Windows10
Issue: Quality icon panel is not enabling for embedded mejs4 audio player.

### Steps to reproduce
1. Embed a mejs4 audio player in a website.

2. Make sure that the audio file has both High and Medium derivatives.

3. Check that the mejs4 player in spruce is able to display the quality strip when hovered on quality icon
![mejs_audio_qual_icon](https://user-images.githubusercontent.com/25850972/32902728-26c918aa-cac1-11e7-8a49-c18efeda9aa5.PNG)

4. But the same is not seen for the embedded player, the quality icon is not showing the panel when hovered on.
![mejs_audio_qual_icon_embed](https://user-images.githubusercontent.com/25850972/32902764-47bf65aa-cac1-11e7-99c9-14be69c166e2.PNG)

**Comment by cjcolvar** [comment]
@joncameron @davidschober I believe the decision was to remove the option to change quality in the audio embedded player and rely on the adaptive stream (the auto quality).  This is what is currently in the code.  I propose we close this and remove it from the Known Issues.

**Comment by joncameron** [comment]
Chris's comment is accurate and what we ended up doing—closing this issue.
