### ISSUE TITLE
Markers Do Not Display For Tokenized Playlist URLs

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2459]
### Description
When a playlist with markers is shared via the _share by link_ option, the markers do not appear for standard users when accessing the playlist via that link. The markers do not appear in the media player or the _Markers_ accordion below.

#### Environment
- media.dlib.indiana.edu, Firefox 56
#### To Reproduce
- Create a playlist with at least one item
- Add markers to the playlist item
- Set the playlist to _share by link_
- Use the tokenized link to access the playlist with a standard, non-admin and non-collection staff user account
- The markers do not display

### Done Looks Like
- Any markers on a playlist item display on the MEjs rail and the Markers accordion for all users accessing the palylist through its tokenized share link

**Comment by cjcolvar** [comment]
@davidschober @joncameron Should this be fixed for 6.3?  I think so.

**Comment by joncameron** [comment]
@cjcolvar Yes, definitely. I've put the tag on it.

**Comment by Karthikeya212** [comment]
Tested on Spruce with Firefox56
