### ISSUE TITLE
Documentation for Behavior In Issue 2387

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2460]
### Description
Documentation needs to be available for edge case behavior that occurs when trying to attach a masterfile with no metadata in the record.

See #2387 for reference.

### Done Looks Like
- Behavior in #2387 is documented in the Avalon wiki under Known Issues (https://wiki.dlib.indiana.edu/display/VarVideo/Known+Issues).

**Comment by mschnaars** [comment]
Added to Avalon Wiki under Known Issues

**Comment by joncameron** [comment]
Closing as per Matthew's comment.
