### ISSUE TITLE
Investigate hydra-role-management gem

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#2464]
### Description
We would like to see if we can use this gem to provide the user/group management features that will enable smaller institutions without IT support to manage access to their Avalon installation.

https://github.com/samvera/hydra-role-management

### Done Looks Like
- [ ] we can make a decision about using or not using this gem for our purpose.

**Comment by joncameron** [comment]
Abandoning due to current contract with Notch8 to implement local user management.
