### ISSUE TITLE
Feature List for Avalon 7

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2470]
### Description
A full list of features is available that describes the meat of what Avalon does in a user context.

### Done Looks Like
- A list of features is compiled
- The list is reviewed by team members
- The list is revised as needed

**Comment by joncameron** [comment]
@Karthikeya212 will you be around this month? I and @davidschober and @mcwhitaker  can work on this or get it more ready for review if not.

**Comment by Karthikeya212** [comment]
@joncameron Yeah, I will be around this month. I am working on this and will post a final version of the draft next week so that people can review.

**Comment by mcwhitaker** [comment]
@joncameron I think we said the deadline for this (reviewed and all) is Jan 17th (our face-to-face meeting). So I think @Karthikeya212 may give all his attention to 6.3 testing/regression testing without having to worry about this as there will be time in January to complete the work. Agreed?

**Comment by joncameron** [comment]
@mcwhitaker Definitely! Thanks for the reminder on the deadline, it can certainly wait. I'm going to move it out of _in progress_ for the time being until @Karthikeya212 jumps back on it after 6.3 testing. I think I jumped the gun when working through the many issues we have open.

**Comment by mcwhitaker** [comment]
@Karthikeya212  has submitted his document for review: https://iu.app.box.com/file/250830372129

Next steps are to identify which of these features are present in hyrax so we can figure out the work ahead.

**Comment by davidschober** [comment]
I vote to move this to "in review/completed" @Karthikeya212 you did a great job! Let's create a new "Create a delta document" issue.
