### ISSUE TITLE
Error clicking "Add to Playlist" when not logged in

### ISSUE THREAD

**Issue by mbklein** [avalonmediasystem/avalon#2473]
### Description
1) Go to https://mallorn.dlib.indiana.edu/media_objects/cz30ps74m
2) Make sure you are *not* logged in
3) Click one of the `Add to Playlist` buttons in the section list.

### Done Looks Like
- The _Add to Playlist_ button does not appear for users who are not logged in.

**Comment by mbklein** [comment]
@davidschober and @joncameron: 
Please decide expected behavior for anonymous (not logged in) users:
1. The `Add to Playlist` button doesn't show up.
2. The `Add to Playlist` button redirects to a login page.

**Comment by mcwhitaker** [comment]
@mbklein A user should not be able to "add to playlist" if he is not logged in because then we don't know who will own the playlist. 

I think the issue should be rephrased to not show the buttons.

**Comment by mbklein** [comment]
@mcwhitaker That's why I added a comment asking the POs for clarification on expected behavior. :smile:

**Comment by mcwhitaker** [comment]
@mbklein Your post and mine were crossed...

**Comment by davidschober** [comment]
@mbklein let's hide it.

**Comment by joncameron** [comment]
At standup today we agreed that the button should just be hidden.
