### ISSUE TITLE
Handle master_file=nil in active_code_job.rb

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2487]
Honeybadger report https://app.honeybadger.io/projects/54117/faults/35657458

[PROJECT_ROOT]/app/jobs/active_encode_job.rb:21 :in `error`
19     def error(master_file, exception)
20       # add message here to update master file
21       master_file.status_code = 'FAILED'
22       master_file.error = exception.message
23       master_file.save

**Comment by joncameron** [comment]
Stale.
