### ISSUE TITLE
Getting error when using "uuuu" for date

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#2488]
### Descriptive Summary
At IU, honeybadger has reported an error when user entered "uuuu" as date.

### Steps to reproduce

1. Login to spruce
2. Pull up an item that you have rights to edit.
3. Click _Edit_
4. Click _Resource Description_
5. Enter "uuuu" for _Creation Date_
6. Click _Save_

You will see the error:
![image](https://user-images.githubusercontent.com/16720883/33504262-d68b2ea0-d6b4-11e7-8eed-31d86ec5f6c2.png)

### Expected Behavior
Gracefully tell user that the date format is not valid.

**Comment by bkeese** [comment]
Entering '1uuu' is also not permitted by the spec, but the error message is handled gracefully.

**Comment by cjcolvar** [comment]
No, I think we should present a nice error to the user for either '1uuu' or 'uuuu' saying they aren't valid.

**Comment by Karthikeya212** [comment]
Tested on Spruce
