### ISSUE TITLE
MEJS4 - Playlists page Autoplay button

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2499]
### Description
Wire up the functionality of Playlist Items page Autoplay button to work with the new JS wrapper file.

### Tasks
- [x] Create a boolean property on either the player wrapper file itself for Autoplay, or on the Playlist Items plugin scope if the functionality is specific to Playlist Items.
- [x] Make expected autoplay behavior work with code.

**Comment by adamjarling** [comment]
Fixed as part of #2308 Playlist Items page work

**Comment by cjcolvar** [comment]
Can this be closed with remaining work happening in #2533?

**Comment by adamjarling** [comment]
@cjcolvar Yes, closing now.
