### ISSUE TITLE
Markers should show on scrubber

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2506]
## Description

Markers are not showing up in scrubber.

Referenced in #2504

**Comment by cjcolvar** [comment]
@davidschober @joncameron Is this priority or could it be taken out of 6.3?  My vote would be take it out since it is labelled `enhancement`.

**Comment by davidschober** [comment]
This is core functionality. It can't be taken out. Markers need to be there. Mis labeled.

**Comment by cjcolvar** [comment]
@davidschober I understand that markers on main scrubber are core.  What I meant was can we skip adding markers showing on lil' scrub?  That seems to be included in this ticket and was not a part of prior versions.

**Comment by joncameron** [comment]
@cjcolvar Yep, I've edited the description to clarify that it's just the main rail/scrubber and that lil' scrub isn't part of this or getting markers added.

**Comment by davidschober** [comment]
I'm seeing markers as working in chrome on spruce. Is this just a safari issue? Can someone point>

**Comment by cjcolvar** [comment]
@davidschober There is some discussion happening here about how to make them more on par with how they worked in MEJS2:
https://github.com/avalonmediasystem/avalon/pull/2307

**Comment by cjcolvar** [comment]
@davidschober @joncameron Markers are showing on the scrubber now.  It would be nice to get PO's thoughts on if they sufficiently replicate the mejs2 player or if any new tickets should be created for additional work.
