### ISSUE TITLE
Switching between playlist items doesn't change video source

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2507]
## Description

When clicking between playlists items on ME4, the video source is not changing. 

## Done looks like

- when a user clicks a playlist item it should play the proper source. 

#2504

**Comment by yingfeng-iu** [comment]
closed by mistake, moving it back

**Comment by davidschober** [comment]
I'm seeing this in spruce can someone point this and move it to the top of ready?

**Comment by cjcolvar** [comment]
@davidschober I believe this will be taken care of with the PR that @adamjarling is about to make.  We plan on merging that and then running through it and writing new bugs tomorrow during swarm.

**Comment by adamjarling** [comment]
Yea, this will get handled by the forthcoming PR.

**Comment by davidschober** [comment]
Sounds great ! Thanks you two.

**Comment by davidschober** [comment]
@joncameron I tested this in Spruce on Safari and Chrome, closing as good with last PR. Feel free to sanity check.
