### ISSUE TITLE
add quality control tooltip

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2508]
## Description

Ensure the quality control tooltip exists on me4js.

## done

- you hover and the quality control tool tip pops 

#2504

**Comment by Karthikeya212** [comment]
The default quality is set as "high", and the sticky quality functionality is not working. To reproduce, change the quality of a video/audio object and reload the page, it sets back to high quality.

**Comment by bkeese** [comment]
This story is about the tool tip text being correct (It should be "Stream Quality".)
Please create another story about default/sticky quality functionality.

**Comment by Karthikeya212** [comment]
Oh sorry, I thought it is the functionality of the quality control.
