### ISSUE TITLE
Playthrough on item view page not working

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2509]
## Description

when on a page with multiple sections, the player should play the next section when it reaches the end of a section. 

## done looks like
- me4 functions similar to me2 when the end of a section is reached. Example https://pawpaw.dlib.indiana.edu/media_objects/2j62s484w?me4js=true

#2504

**Comment by adamjarling** [comment]
Duplicated by #2534.  Closing.
