### ISSUE TITLE
Playlist Items Page: Make track scrubber work

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2530]
### Description
Get the track scrubber (lil scrub) working on Playlist items page.

### Tasks
- [ ] Move scrubber specific functions to either the track scrubber plugin itself, or a helper class which can store shared functions needed to update and initialize the scrubber.
- [ ] Update `app/assets/javascripts/media_player_wrapper/avalon_player_new.es6` to de-couple scrubber.

@davidschober @joncameron

**Comment by davidschober** [comment]
This looks good. Pull in at will.
