### ISSUE TITLE
MEJS4 Autostart sections

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2534]
### Description
A player with sections should also follow the default Autostart behavior.  Which means that moving from one section to another automatically should happen by default (for now).

Eventually (past 6.3 release) this setting should be configurable by the user on the page, mimicking functionality (forthcoming) on Playlist Items page with it's "Autoplay" toggle button.

### Done Looks Like
- Items in the "Sections" panel content autoplay from one section item to the next by default.
- This behavior is not adjustable by user.

### Tasks
- [x] Handle end of player event, determine if there's another section to play into.
- [x] If a following section exists, load that file and autoplay.

@davidschober @joncameron

**Comment by davidschober** [comment]
@adamjarling can we squash autoplay (and autostart) or is that considerably more work? e.g. a single User interface following playlists (cribbed from Youtube). cc: @joncameron

**Comment by adamjarling** [comment]
@davidschober We can, but we should do with when we have more time.

**Comment by davidschober** [comment]
Sounds good. Stick with your original plan. We can grab that for 6.x

**Comment by adamjarling** [comment]
@cjcolvar @bkeese Can one of you look at why this value is not pulling through?  I need to grab all the "sections" on a page to see if any are left when handling the 'ended' event.  And this seems the best (for now) way to grab that information.

Ideally it'd be nice if we could make an array variable available from Rails, when calling the MEJS player, which indicates how many "sections" (and their ids) will be displayed on this view.  Then pass that thin array into the JS instead of having to crawl the DOM for this info (way slower).

![masterfile-id-error.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46e59589378791af86e5ba0ead59bd913b5428616b48e13b628ae92dbc56395b4d5a49a817595d17f5adda2df4b73e708d5c0fe8803b5874c02f0dbefad341eb5ee779c11ac7a4b6984dc6e23c20e6888e463817031d89fd5a27ed.png)

**Comment by adamjarling** [comment]
Actually I think I found where this is happening and working on a fix I need. 

 I can't figure out why that value is not being written in that string though...  and guessing it's causing a bug?

**Comment by bkeese** [comment]
app/helpers/media_objects_helper.rb, line 134 isn't being interpolated. Quotes need to change to something like this: ```
       playlist_btn = current_ability.can?(:create, Playlist) ? "<button type=\"button\" title=\"Add section to playlist\" aria-label=\"Add section to playlist\" class=\"structure_add_to_playlist outline_on btn btn-primary\" data-scope=\"master_file\" data-masterfile-id=\"#{section.id}\"></button>" : ''
```

**Comment by adamjarling** [comment]
@bkeese Ok, I'll play with that while I'm in the file.

**Comment by adamjarling** [comment]
@bkeese I made the update to `app/helpers/media_objects_helper.rb` and looks like it works.  Thanks for the code.  It's in this commit.
