### ISSUE TITLE
Playlist Items Page: represent playlist position in URL

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2536]
### Description
(from Pull Request notes)
Do we want to represent playlist item sections in the url (ie. http://localhost:3000/playlists/1?position=2)? It looks like copying the url for each item and pasting in the browser resolves to a route which displays the appropriate playlist item. (Low priority)

To be done post 6.3.

**Comment by cjcolvar** [comment]
This should apply to links in the playlist item list on the right side as well as the related item links.

**Comment by bkeese** [comment]
Clicking related items actually just finds and clicks the appropriate item on the right side, so handling it just on the right side should cover both.

**Comment by joncameron** [comment]
No longer applicable.
