### ISSUE TITLE
Mediaelement4 - Move sections code to it's own plugin

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2537]
### Description
In the player view with clickable sections, this JS code should be abstracted to it's own plugin and not be tightly coupled with the main player JS wrapper file.

**Comment by davidschober** [comment]
@adamjarling is this still valid?

**Comment by adamjarling** [comment]
Yes, and it's pretty important to do sooner than later.

**Comment by joncameron** [comment]
Stale.
