### ISSUE TITLE
Avalon Should Handle MediaInfo Changes Better

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2543]
As revealed by #2520 (and we've had this happen before)

When MediaInfo changes its output format, which happens with some regularity, our characterization breaks.  Which in turn means that no workflow is set on a masterfile.  Avalon however chugs along with a workflow of `nil` right up it comes time to stick it in Fedora and then everything blows up.

We need better characterization or some kind of fallback where Avalon alerts to the issue prior to throwing a generic error to the user.  This is something we're going to have to deal with since on AWS, Amazon just goes ahead and updates MediaInfo and there is no graceful way to roll back to the old one.  When the container is updated to use 17.10, you get it and its changed outputs.

**Comment by carrickr** [comment]
@cjcolvar Thoughts on this by the way, I put this in as kind of a placeholder, we should develop a specific plan of attack.

**Comment by cjcolvar** [comment]
@carrickr I'm not quite sure how we can be future proof.  I think our best course of action is, as you suggested, gracefully handling the error that occurs when mediainfo explodes.

**Comment by carrickr** [comment]
Yeah I'm torn between gracefully handling it or doing a bit of cheating where if MediaInfo kicks back a nil, assume mediainfo changed (as opposed to someone putting in a .png) and passing it through as avalon workflow.  Although that would mess up audio.  It's annoying because we could probably guess off file extension and be right 99% of the time, so no reason to blow up just because the gem got updated.

**Comment by joncameron** [comment]
FITS as used in Avalon 7/Hyrax also has issues with MediaInfo. MediaInfo remains an unslain dragon, hiding on a golden pile of technical metadata.
