### ISSUE TITLE
Refresh token console error

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2549]
### Description
I keep seeing this console error, developing locally.  Anyone else?

![refresh-token-error2](https://user-images.githubusercontent.com/3020266/33952028-338c8a46-dff6-11e7-8146-8912831d42a9.png)

![refresh-token-error](https://user-images.githubusercontent.com/3020266/33951925-e8420246-dff5-11e7-9182-9f9d48e04777.png)

**Comment by bkeese** [comment]
Yes. I do too.

**Comment by adamjarling** [comment]
Ok.  I'll check it out and see what's up.

**Comment by adamjarling** [comment]
@bkeese @cjcolvar @yingfeng-iu Is this file in place to handle embed stuff?  Or is this a holdover from MEJS2?

**Comment by cjcolvar** [comment]
@adamjarling The refresh_token code should be independent of MEJS versions.  It deals with keeping the streaming token current and valid.
