### ISSUE TITLE
Playlist Items Page Endpoint Error

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2557]
### Description
This bug crept in through some commit... When auto-advancing from one playlist item to another, the `GET http://localhost:3000/playlists/1/items/2/metadata` endpoint is not found.  See screenshot.

![playlist-items-page-endpoint-error.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46f8989b3a8e8aba9ba4b657a150e3d9394720766401ad2f608aea26ab0f7e131d000cbe5d4a1f06a3a3dc78e2a436628f5b0fbbd06f0c7d926e17feb9801fb801be25da1982b6ba9850d2aa6c7bb3d4d216744b470a83ed5c33aa984ec95bf44ae74a55a0133f66f43b.png)

**Comment by bkeese** [comment]
This will be fixed when my PR #2555 is merged.

**Comment by adamjarling** [comment]
Sweet.   Easy fix!

**Comment by phuongdh** [comment]
Added reference to this bug from @bkeese PR so it gets moved and checked

**Comment by adamjarling** [comment]
I'm still seeing this error on `/develop`.  Anyone else?

**Comment by bkeese** [comment]
I am too. Must have missed something.
