### ISSUE TITLE
Deploys to Spruce Seem to Kill Off Background Jobs

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2560]
## Description 

Namely the ones checking Matterhorn, but also potentially more (and we just haven't noticed yet).  That's kind of a problem with regard to testing things like Batch, since basically everytime someone merges into develop it triggers a deploy.  

We should determine how to avoid killing jobs during Bamboo deploys.

## Done looks like

- investigation takes place into cause
- Spruce is set up so background jobs

**Comment by joncameron** [comment]
@phuongdh Is this still relevant, or can it be closed?
