### ISSUE TITLE
Don't Show Actions Column When User Cannot Take Action on Markers

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2561]
### Description
Users who are viewing a playlist are shown the column for actions to be taken in the markers accordion, but no button shows up as they do not have permissions to take action on the set of markers for the playlist. 

### Done Looks Like
- The action column does not appear to users who do not have permissions to edit the markers on the playlist being viewed.

**Comment by cjcolvar** [comment]
Since #2561 got merged marker actions don't show for any user including the playlist owner.

**Comment by yingfeng-iu** [comment]
was working locally when i tested, will check again

**Comment by joncameron** [comment]
I tested this as well—looks good!
