### ISSUE TITLE
Firefox console warnings

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2564]
### Description
In the latest Firefox version (57.01.1) getting the following console warnings.  See screenshot.

![firefox-console-warnings.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46ee9d8826848cb1c2eab04db752fc9164512661270dad2c63c7af6aaf50740b0a0c0abe4b4a5a43f8af8829f5bf68238c0e0aefd16a5f70c36c47abb8840da313f871d51bdaebe5c01982fa3737e683854e3b1f061a8ff75b3ca5994bcf4abb.png)

**Comment by cjcolvar** [comment]
@adamjarling does it still end up playing?

**Comment by adamjarling** [comment]
Yea, the video still plays just throws a stack of warnings, not errors.

**Comment by phuongdh** [comment]
Seems low priority. 6.x/never? FF always tends to throw a bunch of warnings at me.

**Comment by adamjarling** [comment]
@cjcolvar Should we abandon this?  I didn't know FF was a complainer previously.

**Comment by cjcolvar** [comment]
How about we leave it for now but put it at 6.x?  I'll make that change and we can continue the discussion on this ticket if we think it should be prioritized differently.

**Comment by davidschober** [comment]
abandoned. Firefox is a  complainer.
