### ISSUE TITLE
Playlist Items - item link same player start time not updating

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2567]
### Description
In the playlist items page, playlist items sidebar, when clicking on an item which is the same media source (same player), the start time is not updating.

Related to #2533

**Comment by bkeese** [comment]
FWIW, I'm not seeing this problem locally.

**Comment by adamjarling** [comment]
@bkeese Here's a screen cast what I'm seeing locally:  https://screencast.com/t/WAUXA0nNlB

**Comment by bkeese** [comment]
You might try again after my latest PR is merged. Travis should be done soon.

**Comment by adamjarling** [comment]
I found an area which I think needs to be updated.  I'll put in a PR and tag you and @phuongdh

**Comment by adamjarling** [comment]
@bkeese @phuongdh @cjcolvar This got merged yesterday.  Is someone having another look at this, or did I forget to move it into the Needs Review/Done column?

**Comment by bkeese** [comment]
Which PR was it?

**Comment by adamjarling** [comment]
https://github.com/avalonmediasystem/avalon/pull/2568/

**Comment by cjcolvar** [comment]
I'm not able to reproduce.  Closing.
