### ISSUE TITLE
"Double" start of player when loading new player in page

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2569]
### Description
On the playlist items page, when loading a new player, about half the time I'm getting a jumpy, double re-start of the player.  Like it starts playing for a fraction of a second, then it re-starts or re-paints to the screen or something.

Going to look into it and and see if it's different from Sections page, and if so, why.

**Comment by cjcolvar** [comment]
@adamjarling can this be closed?

**Comment by adamjarling** [comment]
Yes, I'll close now.
