### ISSUE TITLE
General JS clean-up

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2573]
### Description
Light pass through the JS, enforcing more consistent patterns, best practices, making code more consistent in appearance.

**Comment by joncameron** [comment]
@adamjarling Is this something you wanted to do before code freeze? I'm inclined to close at this point or label it 6.x if there's still more you'd like do do on the code.

**Comment by adamjarling** [comment]
The OCD part of me would just like to be consistent in certain code patterns, however all things considered I think the risk in working on this ticket now outweighs the reward.  Let's put til 6.x?

**Comment by davidschober** [comment]
Abandoned. This is too general. As we're working on 7 we will clean up as we go.
