### ISSUE TITLE
Playlist Items page - player adds twice find alternative to boolean flag

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2575]
### Description
Currently the way to prevent double firing of the 'timeupdate' event is handled through setting a boolean flag in the playlist items plugin.  Find an alternative way to handle this, not using the boolean flag.

**Comment by adamjarling** [comment]
I have a fix for this in place, that I can push up a PR for once #2592 is merged.

**Comment by cjcolvar** [comment]
@adamjarling this got merged and is closable, right?

**Comment by adamjarling** [comment]
Correct.
