### ISSUE TITLE
Markers not working in Safari

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2578]
_From @davidschober on December 15, 2017 16:17_

To Recreate:

- Go to a playlist <https://spruce.dlib.indiana.edu/playlists/100> using safari
- click on a marker
- see that the playhead is not moved forward to proper position

_Copied from original issue: avalonmediasystem/avalon-planning#221_

**Comment by cjcolvar** [comment]
Might be fixed by #2586

**Comment by cjcolvar** [comment]
I wasn't able to reproduce with the latest on spruce.

**Comment by joncameron** [comment]
Couldn't reproduce this, but I filed another Safari marker bug: #2620
