### ISSUE TITLE
Add popovers to markers

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2579]
_From @davidschober on December 15, 2017 16:19_

## Description

To create better parity with markers, add popover/ hover with the title of the marker on the scrubber.

## Notes

Pointed at 3 per discussion.

_Copied from original issue: avalonmediasystem/avalon-planning#222_

**Comment by bkeese** [comment]
If we were shooting for 6.3 feature freeze today, I don't think we can get this in for 6.3.

**Comment by davidschober** [comment]
Can we sneak it in Monday, or is it too big

**Comment by bkeese** [comment]
We can try.

**Comment by bkeese** [comment]
I have this working, but had to fall back to the MEJS2 style of marker (below the time rail). Is it ok?
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57597e546b48630e00666b0c/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f47f76d4b12be64678570d5e4cac46585b41adaf8e2ba0a42062c80d55b98e30063e937f03a6aa8318b500bf21884986b4ba8d45c3e83437aa.PNG)

**Comment by davidschober** [comment]
I’m OK with that. Jon?

**Comment by cjcolvar** [comment]
I think this is good because I'm seeing the markers within the scrubber not showing up on the mobile devices I'm testing.

**Comment by joncameron** [comment]
Yep, this is perfect. I think the fallback to the previous style of marker makes sense. Thanks @bkeese!
