### ISSUE TITLE
Playhead Returns to Playlist Item Start After Playback 

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2582]
### Description
When a playlist item finishes playing and autoplay isn't on, it should return to the beginning of the playlist item, similar to the way playback stops and the playhead returns to the beginning of a section after playback.

To keep in line with 6.2 behavior, users should also be able to click on the rail past the end time of the playlist item to move the playhead to a later timepoint. The current MEJS4 behavior is to allow users to click before the beginning of the playlist item but not past the end.

### Done Looks Like
- If a playlist contains a single playlist item and Autoplay is On or Off, OR if a playlist contains multiple items and Autoplay is Off:
  - when the playlist item is finished playing (the end is reached), playback stops and the playhead moves back to the beginning of the playlist item 
- If a users clicks on the rail to move the playhead past the end time of the playlist item, the playhead should move to that time.

### Timebox
This is a timeboxed item.

**Comment by adamjarling** [comment]
@joncameron Consider this scenario:  Playlist item range in a 60 second file is say 15 - 25 seconds.   If user clicks in the time rail between 26 - 60 seconds, where should the playhead go?

Currently the code blocks the user from playing any portion of the overall clip past the specified playlist item end time.  This seems kind of restrictive...

**Comment by joncameron** [comment]
@adamjarling The playhead should go where clicked, and move to timepoint past the end time of the playlist item. So it's the case right now that the playhead will move to a time before the playlist item, but not after?

**Comment by adamjarling** [comment]
Correct.  In it's current state you can't play anything past the playlist item endpoint time.

**Comment by joncameron** [comment]
Got it. If possible I'd like it to have the same behavior both before and after. Would it be easier for me to open a new ticket, or attach that to this one?

**Comment by adamjarling** [comment]
Ok, got it.  I'd say just update the description of this ticket to capture the evolved scope of what this ticket is doing now.

**Comment by joncameron** [comment]
Updated 👍

**Comment by joncameron** [comment]
The return to the beginning of the playlist item is working great. Clicking the rail past the end of the playlist item works in some cases and sometimes not, and I'll write that up in a new issue.
