### ISSUE TITLE
Related items table gets a border for small screen sizes only

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2587]

**Comment by cjcolvar** [comment]
It looks like there is a difference of CSS classes between the related items and markers: `table-responsive` vs. `table-condensed`.  Maybe we should choose one or the other.

**Comment by yingfeng-iu** [comment]
The .table-responsive class creates a responsive table. The table will then scroll horizontally on small devices (under 768px). When viewing on anything larger than 768px wide, there is no difference. 

If scrolling is useful on mobile device, I wonder if we shall keep it.
