### ISSUE TITLE
m3u8 files should not be downloadable without a token/cookie

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2593]
In 6.3, m3u8 and ts files can be downloaded without any token or cookie (incognito mode). 

Example: `https://spruce.dlib.indiana.edu/streams/600d02de-fc86-4a58-8934-2ecea8b9ae3d/c037e409-e14a-4a88-b22f-24a185d3c2ee/Arkansas_Blues.mp4.m3u8`

**Comment by cjcolvar** [comment]
It looks like the authorization endpoint isn't being called on spruce for HLS stream requests.

**Comment by davidschober** [comment]
Is this a code or config problem?

**Comment by cjcolvar** [comment]
I'm thinking config problem right now because the `20-avalon.conf` isn't being used on spruce right now.

**Comment by phuongdh** [comment]
That's because we use Rails server instead of Apache on Spruce. I think this can be a wontfix issue, if data on Spruce isn't too important.

**Comment by joncameron** [comment]
@phuongdh Can you label _wontfix_ and close if this is just a config issue? I don't think content security is important on Spruce.

**Comment by phuongdh** [comment]
@joncameron I'd like to check this  on Mallorn when it gets 6.3 to make sure it's a config issue first.
