### ISSUE TITLE
Handle clicking a marker past playlist item end time

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2596]
### Description
See attached video link for a reference:

https://screencast.com/t/jr9zHSlMuqP

Question on the following scenarios:
- What happens when a user creates a marker outside of the playlist item range?  This is allowed?
  - _(Agreed 2017-12-18 that this is still currently allowed for 6.3 as it was the previous behavior)_.
- What happens when a user clicks on a marker past the playlist item end point?   Should it play from that time, similar to clicking on the time rail past the playlist item end point?  
  - _(Agreed 2017-12-18 that this will let user play the current clip past playlist item end time, similar to clicking in the time rail past end time)_

### Done Looks Like
- User is allowed to add markers beyond the playlist item end time.
- When clicking on a marker time past playlist item end time, allow playing to continue from the marker time.

### Tasks
- [x] Handle marker title click event, determine if marker time is past playlist item end time.
- [x] If so, hook into same functionality as clicking in time rail past playlist item end time.

**Comment by davidschober** [comment]
No it shouldn't be allowed. A marker needs to be within the context of the playlist item . 

It's a bit hierarchal (Media Object>>playlist item>>marker)

**Comment by adamjarling** [comment]
Got it.  I'll re-word this ticket to reflect the work needed.  Thanks.

**Comment by joncameron** [comment]
So the rub here is that it's currently allowed (6.x). Users can set markers before or after the playlist item range, and markers display even if they're out of playlist item context. So—keep allowing, or change behavior? And what to do with user-created markers that fall outside of the bounds? What do you think @davidschober ? I'm not sure if anyone is realistically doing that, so if we change change the behavior I'd be in favor of that, but it's a slight unknown.

**Comment by adamjarling** [comment]
This fix has been merged.  I forgot to check off the checkboxes.  Just did.  Is there anything else which needs to be done for it?
