### ISSUE TITLE
Audio embed quality switching popover hidden

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2604]
In the MEJS2 player a plugin was used that made an "HD" button in the control bar which would toggle between medium and high qualities.  In the MEJS4 player, the stock quality switcher with popover with list of available qualities is used.  The problem is that audio embed players have a fixed height that doesn't allow for the popover to show.  We either need to bring back that plugin or figure out a different way that works within the vertical space.

**Comment by adamjarling** [comment]
@cjcolvar Do you have a screen shot of this?  On what platform is the popover not displaying properly for audio files?

**Comment by cjcolvar** [comment]
Any platform.  The issue is with embedded players being in an iframe with a set height of 50 so there isn't any space for popovers vertically.  See the second embed here: https://wiki.dlib.indiana.edu/display/VarVideo/Embed+Test+Page

**Comment by adamjarling** [comment]
Ah, for embedded players.  I get it now.

**Comment by bkeese** [comment]
One option is to make the pop-up selector arranged horizontally instead of vertically. This would likely be a simple css change.

**Comment by adamjarling** [comment]
@bkeese If you have a CSS idea maybe give it a shot?  I'm having trouble seeing how we can make this work w/ MEJS4's quality selector plugin.

Does the player know when it's being embedded?

**Comment by bkeese** [comment]
I think @phuongdh is on the right track with using a fork of our own HD toggle that someone has written to work with MEJS4.

**Comment by phuongdh** [comment]
@avalonmediasystem/product-owners Possible future solution: audio player only has one quality = high. 
My reasoning: even low quality video (~4.5M/min) requires far more bandwidth than high quality audio (~2.5M/min).

**Comment by adamjarling** [comment]
That's a quick, less risky fix if it's acceptable.

**Comment by joncameron** [comment]
@phuongdh I don't see that happening—one significant use case is anyone with a slow internet connection, accessing overseas, etc. Avalon really needs to provide multiple derivatives, even for audio.
