### ISSUE TITLE
Thumbnail grabber control showing for all users

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2605]
### Description
The thumbnail grabbing tool should only show for privileged users.  Currently it is showing for all users even users who aren't logged in.

### Done Looks Like
- The thumbnail grabbing button only shows for users who are logged in and 
  - are an administrator or
  - are on a media object page contained in a collection in which they are in a _collection staff_ role

**Comment by yingfeng-iu** [comment]
The thumbnail button is added in buidlcreateThubmnail in mejs4_plugin_create_thumbnail.es6, but no permission checking there. I can add permission checking there, or before adding the feature to mejs4ConfigFeatures in _mejs4_player_js.html.erb. I think the latter might be better. 

Also I was wondering if any other features need permission checking, and Brian mentioned that addToPlaylist should only be allowed for login user. I checked the code and don't see permission checking for that one either. If we want to add permission checking for addToPlaylist then I guess doing these checkings before adding to the feature list is better?

**Comment by bkeese** [comment]
👍

**Comment by cjcolvar** [comment]
:+1:  Sounds good to me!
