### ISSUE TITLE
Structure link clicks cause reload of page

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2606]
All structure link clicks including those within the same section are causing the whole page to reload.  When the page finishes loading the player's current time is 0 instead of the start time of the structure link clicked.

Expected behavior is page does not reload (even when switching between sections) and player advances to the start time of the structure node.

**Comment by adamjarling** [comment]
I think some playlist items section click listeners got added to the main js wrapper file instead of the playlist items plugin js...

**Comment by adamjarling** [comment]
I think this caused the error: https://github.com/avalonmediasystem/avalon/commit/b9928ea240b85777c6d41f06ec1f25ee05b69b5c

**Comment by joncameron** [comment]
I couldn't reproduce—going to close and reopen a new issue if it reoccurs.

**Comment by adamjarling** [comment]
Yea, I put a fix in for it yesterday.
