### ISSUE TITLE
Autoplay on playlists doesn't start new item (iPad)

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2611]
## Description

On iOS, Autoplay on playlists advances correctly but does not start playback for playlist items that have new sources

To Recreate
- go to https://spruce.dlib.indiana.edu/playlists/117
- see that as the first playlist item runs out the second does not start 

Master issue: #2609

**Comment by bkeese** [comment]
Interesting. So, label it "won't fix" or try to work around it?

**Comment by cjcolvar** [comment]
I'd vote for "won't fix" for now although I tested on MCO and it is playing through fine on playlists.

**Comment by davidschober** [comment]
I'm going to "won't fix" this and close it.
