### ISSUE TITLE
 IPAD/iOS: Lil' scrub appears but is missing duration and doesn't get updated while playing 

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2612]
## Description 

 Lil' scrub appears but is missing duration and doesn't get updated while playing .

To recreate,

- Go to a playlist https://spruce.dlib.indiana.edu/playlists/117
- expose lil'scrub
- see that it's not updating time. 

Master issue #2609

**Comment by adamjarling** [comment]
This could be a tricky one to address.  

As some background, most of lil' scrub's code I just cut out of the previous plugin and created a new plugin file (following our new plugin pattern), converted from CoffeeScript to JavaScript.  I didn't really dig into how things were working, or optimization.  Not that that's the issue, but there's some code that could maybe be updated to MEJS4's context.

I'll open in BrowserStack and see if it's possible to monitor any obvious console errors for starters.

**Comment by cjcolvar** [comment]
After some more testing, I think this is a timing issue because if you switch to a new playlist item with the same source lil' scrub works fine.  You can even switch back to the original playlist item and it works, but if you switch to a playlist item with a new source then it is back to not working.

**Comment by adamjarling** [comment]
Ok, going to test on Browserstack now too and try a few things.

**Comment by cjcolvar** [comment]
I'm seeing this same behavior in Safari on Mac 10.11.6 as well.

**Comment by adamjarling** [comment]
Will need to test this being served from Spruce.  Browserstack for me throws errors on es6 Javascript in the console.   It's fixed now for Safari.

**Comment by joncameron** [comment]
Working in Browserstack, tested on mobile safari in iOS 11.
