### ISSUE TITLE
IPad : Markers are not showing in the scrubber

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2614]
## Description

Markers are not showing up in the scrubber 
This seems to only be on the iPad. Tested fine in IOS 11/ iPhone.

**Comment by cjcolvar** [comment]
This needs to be retested now that #2618 has been merged.

**Comment by cjcolvar** [comment]
Markers show fine for me given the changes made in #2618 with the exception of the bug noted in #2620.
@davidschober Is it okay to close this issue?

**Comment by davidschober** [comment]
I don't have a physical device here. I'll close with your review.
