### ISSUE TITLE
IOS: Volume control does not appear

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2616]
## Description 
On IOS Volume control does not appear

To recreate:

- go to video or audio piece
- see that there's no volume.

**Comment by cjcolvar** [comment]
I'm not sure if this is really a problem.  I think it might be deliberate because it might be that the volume of the native player is directly linked to the device volume making an independent volume for the MEJS player be irrelevant or broken.

**Comment by joncameron** [comment]
Agree, I think the standard behavior for mobile apps is that volume controls mirror device/OS volume level anyway. I'm going to close this one.
