### ISSUE TITLE
Markers Do Not Display In Correct Location in Safari

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2620]
### Description
All markers in Safari are showing up on the rail at 0 seconds. If a different playlist item is selected and then the playlist item with the bad marker positions is selected again, the markers display normally.

This affects both mobile and desktop safari.

### Environments
- Safari 11.0.2 on macOS 10.11.6
- Safari 11.0.2 on macOS 10.13
- Safari on iPad running iOS 10

### Example screenshot
<img width="782" alt="screen shot 2017-12-19 at 10 46 12 am" src="https://user-images.githubusercontent.com/1406618/34165724-0e4f7126-e4ab-11e7-92a3-5f128e93996f.png">

### Done Looks Like
- Markers appear at the appropriate points on the rail relative to their position in the masterfile, and does so on the initial load of the playlist item.

**Comment by joncameron** [comment]
Marker element code in the inspector:
<span class="fa fa-chevron-up scrubber-marker" style="left: NaN%" data-marker="644"></span>

**Comment by bkeese** [comment]
duration must me zero at this point: https://github.com/avalonmediasystem/avalon/blob/develop/app/assets/javascripts/media_player_wrapper/mejs4_helper_markers.es6#L387
We should find a different way of getting our hands on the duration that doesn't depend on the player having it.

**Comment by adamjarling** [comment]
There are some console errors firing in Safari that may have something to do with it also... logging some stuff out to see where it's failing.

**Comment by adamjarling** [comment]
`player.duration` isn't calculated and made available yet for some reason in this environment.  That's why the markers aren't getting spread.

**Comment by bkeese** [comment]
Perhaps a simpler approach would be to grab the duration out of the DOM somehow.
