### ISSUE TITLE
Android: Quality switching has no effect

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2625]
### Description
Attempting to switch qualities on an android device closes the popover menu but nothing happens.  If you reopen the qualities popover the original quality is still selected.

**Comment by bkeese** [comment]
I'm testing on my galaxy s-7 and I'm not seeing this problem. I see the quality selection change, a request for the new quality in the network tab of dev tools, and the video starts over (presumably with the new quality). The new quality is selected in the popover when clicked again.

There are some other things I see though, which may or may not be problems:
1) The popover doesn't disappear when clicking a quality. It only goes away when a click somewhere else happens.
2) The scrubber bar is never there.
3) The play always starts at the beginning again when a new quality is clicked.

**Comment by mcwhitaker** [comment]
At one point I remember being told that @bkeese's #3 above is a consequence of red5. Do we still use red5 in the test servers?

**Comment by cjcolvar** [comment]
@mcwhitaker I believe that was true before for desktop browsers (except Safari).  The divide between mobile and safari on the one hand and everything else on the other is still present as the former uses native browser support to playback HLS whereas the later uses hls.js.  For the browser/platforms with native support for HLS, their behavior will probably vary since it is specific to the environment.

**Comment by mcwhitaker** [comment]
@joncameron will create the new tickets.
