### ISSUE TITLE
Android: Duration not displayed until playback starts

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2626]
### Description
The time values reported on the media player show as "0:00" until playback is started. 

### Environment
Android 6 through 9. This is a longstanding issue in Android, since Avalon was using MediaElement 2.

#### Before playback is started, the values will remain 0 indefinitely:
![Screen Shot 2019-06-24 at 4 50 22 PM](https://user-images.githubusercontent.com/1406618/60051176-6da56380-96a0-11e9-9717-c7d30a24f926.png)

#### ...and after the play button is clicked, there is a pause before the stream begins playing, and the time values fill out:
![Screen Shot 2019-06-24 at 4 50 37 PM](https://user-images.githubusercontent.com/1406618/60051188-7433db00-96a0-11e9-9b7c-715c0bf5cc28.png)

**Comment by joncameron** [comment]
@cjcolvar is this the same as #1689? That was the one that popped in my mind when I saw this issue.

**Comment by cjcolvar** [comment]
I think it is the same but the duration is reported as 0 for the android 6 device I tested.  I believe this is fixed on iOS.

**Comment by joncameron** [comment]
OK, I think I'm going to file this under 'low priority' like the previous one and get it on our _known issues_ page.

**Comment by joncameron** [comment]
@SumithBaddam noted: Tested and is still persistent
