### ISSUE TITLE
User has to change the quality twice to actually see it updated, a single click on quality panel is not updating the quality of the object

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2629]
### Descriptive summary
Server: https://spruce.dlib.indiana.edu
Testing: Player Testing
Browser: Chrome 62.0.3202.94
Operating System: Windows10
Issue: A single click on quality panel is not updating the quality of the object, user has to do the same operation twice to actually update the quality.

### Steps to reproduce
1. Start playing an item, and update the quality.
2. Hover over the quality icon and see if it actually updated (it is not).
3. Perform the same operation again, and now you can see that the quality is updated.

**Comment by cjcolvar** [comment]
I remember running into this and I think part of the issue here is that only the text is clickable instead of the whole area around the quality in the popover.  But I remember it being flaky and being sort of erratic in behavior.

**Comment by Karthikeya212** [comment]
I tried it by clicking exactly on the text, but getting same issue.

**Comment by adamjarling** [comment]
Looks like this plugin has been updated since we originally pulled it in.  I'm going to pull down the latest and see if it changes anything.

**Comment by adamjarling** [comment]
It seems better, but still some odd behavior in the click handling.  And still does nothing on the first click most of the time. 

@cjcolvar The real solution is probably to fork this plugin, adjust and fix it, and implement ours.  That might take some time... I'll time box it at an hour and see how it sits from there?

**Comment by cjcolvar** [comment]
Sounds fine to me.  Any objections @avalonmediasystem/product-owners?

**Comment by joncameron** [comment]
Sounds good to me too 👍

**Comment by joncameron** [comment]
Moving to QA- it seems from testing that the quality does switch as long as the user clicks the text (high med low). There seem to be dead zones within the bounds of the gray overlay for each quality, but at this point I don't think it's worth the extra time to nail that since functionality is working as it should be.

**Comment by Karthikeya212** [comment]
Tested on Spruce
