### ISSUE TITLE
Video player controls bar is blinking when user clicks on the timeline bar to play forward/backward

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2631]
### Descriptive summary
Server: https://spruce.dlib.indiana.edu
Testing: Player Testing
Browser: Chrome 62.0.3202.94
Operating System: Windows10
Issue: Video player controls bar is blinking when user clicks on the timeline bar to play forward/backward. This is not observed for audio player or when used scrubber to do the same in video player.

**Comment by Karthikeya212** [comment]
This can be seen even when clicking on play icon.

**Comment by joncameron** [comment]
I think this is either not showing now or is a dupe of https://github.com/avalonmediasystem/avalon/issues/2750.
