### ISSUE TITLE
Embedded Player Zooms Infinitely on iPad

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2632]
### Description
Viewing an embedded player on mobile Safari results in a slow, constant expansion of the media player's size. Must be seen to be believed.

### Environment
iPad 4 running latest mobile Safari on Browserstack

### Example
![bbb2](https://user-images.githubusercontent.com/1406618/34176615-8d1c3110-e4ce-11e7-83e4-54f07fa41c92.gif)

**Comment by cjcolvar** [comment]
I'm wondering if we need to reimplement this change: https://github.com/avalonmediasystem/mediaelement/commit/882db358b11aa057b43d10cb52367c3ae1daa3a9
@adamjarling is there an easy way to override the same callback in mejs4?
https://github.com/mediaelement/mediaelement/blob/26ec30053d3fd59c973fec0164989bda984bee21/src/js/player.js#L923-L931

**Comment by cjcolvar** [comment]
I manually reapplied that change (directly to mediaelement's vendored JS file) and retested in browserstack and it grows slightly with each quality switch (and possibly other resize causing events).  This adds up over time but is much more subtle than the example above.

**Comment by adamjarling** [comment]
ha, that is kind of creepy in the bunny example.  I wonder why the resize event is being continuously emitted?  That's the event callback causing this?

@cjcolvar Is your latest fix acceptable?   Could we move the code you applied to the vendored file, to our `avalon_player_new` file?

**Comment by cjcolvar** [comment]
@adamjarling do you know of any good way to override that callback from `avalon_player_new`?  We'd want to make sure that if we bind a different handler that we unbind it in `remove()`.

**Comment by cjcolvar** [comment]
Since we haven't really had any luck finding an independent solution, I move that we put the fix directly in the vendor JS file and make a ticket to find a better solution.

**Comment by adamjarling** [comment]
Did @phuongdh 's approach work with the plugin or no?

**Comment by cjcolvar** [comment]
@adamjarling No, I think the problem was timing.  You can read my comments on the PR here: https://github.com/avalonmediasystem/avalon/pull/2656#issuecomment-353242587

**Comment by adamjarling** [comment]
Ah, got it.

**Comment by cjcolvar** [comment]
@joncameron A fix is now deployed on spruce.  Each quality switch will still bump up the size of the player a pixel or two so if you switch qualities enough the player will get big but it should be much better than before.

**Comment by joncameron** [comment]
Works as advertised.
