### ISSUE TITLE
Unable to add the audio file to playlist using Add to Playlist icon present in player

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2633]
### Descriptive summary
Server: https://spruce.dlib.indiana.edu
Testing: Player Testing
Browser: Chrome 62.0.3202.94
Operating System: Windows10
Issue: Unable to add the audio file to playlist using Add to Playlist icon present in player. Whereas, these items can be added to playlist with out any issue using the Add to Playlist icon present on each section label bar.

**Comment by bkeese** [comment]
There are 2 issues here:
1) The error message displayed in the flash does not present the user with the specific error that is contained in the response to the ajax request. ```{"message":["End time must be between start time and end of section"]}```
2) In this specific test case, the duration of the tested audio file is rounded up in the player view to ```04:04```. The actual duration of the masterfile is slightly shorter.  We could set some sort of threshold on the end-time validation that can accommodate this rounding error.

**Comment by cjcolvar** [comment]
Sounds good to me!

**Comment by davidschober** [comment]
I'm good with your solution to #2. Just put a floor on it?

**Comment by joncameron** [comment]
Seconded!

**Comment by joncameron** [comment]
Is there an item in Spruce this can be tested against, or way to trigger the behavior that was fixed?

**Comment by bkeese** [comment]
https://spruce.dlib.indiana.edu/media_objects/j098zb18x
https://spruce.dlib.indiana.edu/media_objects/4q77fr355/section/2514nk51b
@joncameron
