### ISSUE TITLE
Embed Code Does Not Change When Section Is Switched

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2639]
### Description
For a media object, regardless of the section currently selected, the embed code shows the URL for the first masterfile in the media object and does not change.

### Environment
Spruce, Firefox 57, macOS 10.11.3

### Example
![dec-20-2017 09-25-10](https://user-images.githubusercontent.com/1406618/34211646-c13536f6-e567-11e7-8b6c-9bbe226f7569.gif)

### Done Looks Like
- When a section is selected (either by user action or playthrough), the embed code in the Share div changes to reflect the embed URL for that masterfile

**Comment by cjcolvar** [comment]
Same for Share and LTI links.

**Comment by cjcolvar** [comment]
Embed code is updating correctly now as well as section share link, but the item share link is getting set to the section share link and the lti links are incorrect as well.
