### ISSUE TITLE
Batch Ingest Emails: Hyperlinks for Media Object IDs

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2640]
### Description
In batch ingest emails where an object has been successfully processed, the object ID should be  a hyperlink to that object in the repository. In the image below, each successful item is listed by ID, but it would be nice if a user could click one to go directly to the media object page.

![all_success](https://user-images.githubusercontent.com/25850972/34173171-9cb2be7a-e4c2-11e7-8850-5af6e438dbee.PNG)

### Done Looks Like
- IDs in the _Media Object ID_ row in the batch ingest success email are hyperlinked to the media object page. For example, n009w2411 would be a hyperlink to https://spruce.dlib.indiana.edu/media_objects/n009w2411

**Comment by Karthikeya212** [comment]
No links are shown and also no details about the object is shown.
![image](https://user-images.githubusercontent.com/25850972/34301579-2b380710-e6fb-11e7-8293-33267c0491e4.png)

**Comment by cjcolvar** [comment]
@Karthikeya212 ready for testing on spruce.

**Comment by Karthikeya212** [comment]
Tested on spruce, working fine
