### ISSUE TITLE
Batch Ingest Success Email: Use Collection Name In Subject Line

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2641]
### Description
Currently, the batch ingest success email uses the collection ID in the subject line instead of the name of the collection. This isn't very useful to collection managers who will want to quickly identify the collection that the message is referring to, and don't think in terms of Fedora IDs.

### Example
![all_success](https://user-images.githubusercontent.com/25850972/34173171-9cb2be7a-e4c2-11e7-8850-5af6e438dbee.PNG)
Instead of _bn999679s_, the collection name should be used.

### Done Looks Like
- Subject line for batch ingest success emails uses the name of the collection instead of the collection NOID

**Comment by Karthikeya212** [comment]
Tested on Spruce, working fine.
