### ISSUE TITLE
IPAD: Playlist info panels and accordion title don't update until after playback starts

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2643]
Go to a playlist and expand the info panels and see that nothing shows in them.
Click play and see that they load.
Pause.
Click to a new playlist item and see that the panels and accordion title still show the info from the previous playlist item.
Click play and see that they update.

**Comment by adamjarling** [comment]
Not sure I can work on this via Browserstack and localhost...  Same on iPhone?

**Comment by adamjarling** [comment]
I can try to debug this on iPhone...looks like it's doing the same thing.

**Comment by adamjarling** [comment]
I'm not having much luck connecting to the Rails server from my iPhone... might not be able to work on this one.

**Comment by cjcolvar** [comment]
I created a WIP PR to capture my work on this but it is not workable yet.
https://github.com/avalonmediasystem/avalon/pull/2659

**Comment by adamjarling** [comment]
Which version of iPad do we support down to?  iPad 4?

**Comment by adamjarling** [comment]
And what controls should be in the player for phone / tablet?  Track scrubber, add marker or playlist item, thumbnail, and fullscreen?

**Comment by cjcolvar** [comment]
This looks good now on an ipad 4.  We need to retest on android.

**Comment by Karthikeya212** [comment]
This looks good on Android as well
