### ISSUE TITLE
Refinement to Playlist MEJS4 Behavior

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2651]
### Description
- On load, a user cannot click past the end of the playlist item range to move the playhead to that point, but:
  - if a users clicks a marker link in the markers accordion, the playhead moves to that point and the user can click freely at any point after the playlist item range
  - if a user double (sometimes triple) clicks the rail past the end of the playlist item range, the playhead moves to that point and the user can click to move the playhead freely past that point
Users should be able to click around on the rail at a point past the playlist item without having the playhead snap back to the beginning of the playlist item, in the same way that a user can click to move the playhead in the time range before the beginning of the playlist item. 

### Environment
Spruce, Firefox 57, macOS 10.11.3
Spruce, Safari 11, macOS 10.11.3

### Done Looks Like
- Users can single-click a point past the end of a playlist item to move the playhead to that point, without the playhead snapping back to the beginning of the playlist item

### Examples
![dec-20-2017 15-58-38](https://user-images.githubusercontent.com/1406618/34228449-b315f830-e59e-11e7-89fc-c22edb700ea1.gif)

![dec-20-2017 16-00-16](https://user-images.githubusercontent.com/1406618/34228507-e7c0b4da-e59e-11e7-84f8-969501adcceb.gif)

**Comment by phuongdh** [comment]
Is this Safari? Can't replicate in Chrome.

**Comment by cjcolvar** [comment]
@joncameron a fix is in place on spruce, can you retest?

**Comment by joncameron** [comment]
@cjcolvar Still seeing the same behavior in Firefox and Safari. Couldn't replicate in Chrome, same as @phuongdh.

**Comment by cjcolvar** [comment]
Ok now that you showed me and digging through the code my guess is that there is a timing bug where the time rail click event is getting crossed with a time update event.  This is why it could be erratically happening.  Code in question is https://github.com/avalonmediasystem/avalon/blob/develop/app/assets/javascripts/media_player_wrapper/mejs4_plugin_playlist_items.es6#L313-L358

**Comment by joncameron** [comment]
This is a minor bug that only affects certain browsers, so I'm going to drop it for 6.x and pull it for now.

**Comment by joncameron** [comment]
Closing; if this behavior is seen again we'll create a new ticket.
