### ISSUE TITLE
Multiple issues on Safari

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2652]
Playlist player on Safari (Mac and iOS) aren't working very well and throwing lots of errors in the console.

Done Looks Like
All serious console errors for loading, playing, and switching items with the playlist player are fixed.

**Comment by adamjarling** [comment]
I don't know why we're just seeing these now.  Everything was fine in Safari before when committed.  Some regression happened, and these updates might regress something else... hopefully this is not a circle.  Wonder what the best approach is here...

**Comment by adamjarling** [comment]
Fixed by removing a previous 'resize' event commit.
