### ISSUE TITLE
Add to playlist form defaults aren't updating with section changes

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2660]
Go to an item with multiple sections
Click the Add to Playlist button
Go to a different section without closing the add to playlist form
Click the Add to Playlist button and notice that the default title and end time are based on the last time the form was open
Close the form and open it again and notice that the defaults are correct now

**Comment by bkeese** [comment]
Another detail: The form values change to the correct values as it is closing upon switching sections. A timing issue.

**Comment by bkeese** [comment]
Need to set ```addToPlayListObj.active``` to false when closing the modal when switching to new section.
