### ISSUE TITLE
Unable to play items on Internet Explorer 11

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2661]
### Descriptive summary
Server: https://spruce.dlib.indiana.edu
Testing: Regression Testing
Browser: Internet Explorer 11
Operating System: Windows10
Issue: Unable to play items on Internet Explorer 11. The timeline is showing both start and end times as 00:00.

![image](https://user-images.githubusercontent.com/25850972/34260997-a1fda9fc-e635-11e7-848e-0c4cb79d3e87.png)

**Comment by cjcolvar** [comment]
From my testing, it appears that the issue is only with initial load.  I'm able to navigate to another section and start playing immediately.  I'm also able to switch back to the first section and playback works as normal then.

**Comment by phuongdh** [comment]
Clicking on structures is also failing and throwing StateInvalid error in IE console.

**Comment by joncameron** [comment]
Testing in browserstack, Chris found that mediaelement is there but there's no duration—the stream isn't loading. But clicking on a different section loaded the stream into the player, and then selecting the first section again loaded it properly. Sounds like a first load problem.

**Comment by bkeese** [comment]
Looks like in IE, the src tag for native hls is not correct. In Chrome, it's the full 

![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57597e546b48630e00666b0c/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f47f76d4b12be64678570d5e4cac46585b41adaf8e2ba0a42062c80d55b98e30063e937f03a6aa801eb500bf218c4786bfba894ac8ef3837aa.PNG)

**Comment by bkeese** [comment]
![Capture.PNG](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/57597e546b48630e00666b0c/125516c66e82c728ace21e0d46cb958a379791accda5fd53b652fa912a5265296b51f47f76d4b12be64678570d5e4cac46585b41adaf8e2ba0a42062c80d55b98e30063e937f03a6aa8318b500bf218c4786bfb48c4fc6ea3b37aa.PNG)

**Comment by bkeese** [comment]
Maybe this: https://github.com/streamroot/videojs5-hlsjs-source-handler/issues/10

**Comment by bkeese** [comment]
hls.js is emitting an error that is caught while the mejs player is being instantiated. So, the instantiation of the player never completes and it never calls handleSuccess. Unfortunately, the hlsjs error itself contains no information useful for debugging. And the log isn't much help: ```[log] > media source closed``` with no indication why.

**Comment by bkeese** [comment]
The <video> has has a MediaElement.error on it with ```MEDIA_ERR_SRC_NOT_SUPPORTED```. I'm going to check this on spruce though, since it's behavior it a bit different that on my local box.

**Comment by bkeese** [comment]
On spruce there are 2 ```<video>``` elements on the show page. One has id ```mejs-avalon-video_native_hls```, the other ```mejs-avalon-video_from_mejs```. 
On both IE11 and Chrome, the mejs one has an error code 4.  On Chrome, the message is "DEMUXER_ERROR_COULD_NOT_OPEN: FFmpegDemuxer: open context failed". IE11 doesn't support the message field. 
On IE11, the native_hls one also has an error code 4. On Chrome it doesn't.

**Comment by adamjarling** [comment]
Yea, I'm not really sure what this could be caused by, but I'd investigate these errors in IE 11's console:

[error] > error while initializing DemuxerWorker, fallback on DemuxerInline
MEDIA12899: AUDIO/VIDEO: Unknown MIME type.

Seems something isn't being interpreted right between MEJS lib / file type / IE 11 .

**Comment by bkeese** [comment]
I found that removing the 'quality' feature resolves this problem. We are now using the mejs quality plugin instead of our own, so a fix would involve finding and pushing a fix upstream. I propose we just remove this feature for IE11 clients. The effect will be that IE11 users will use the configured default quality (or the first that is available if default isn't). Is this OK @joncameron @davidschober?

**Comment by davidschober** [comment]
I'm OK with that . Can we issue a backlog ticket? It might be worth shoving something upstream, or at least noting the bug for them.

**Comment by mcwhitaker** [comment]
@davidschober @joncameron -- If POs accept Brian's suggestion, I think we need to make sure that documentation is updated to reflect this limitation for IE11 users.

**Comment by joncameron** [comment]
This limitation will go in our 'Known Issues' page per usual for the next release.
