### ISSUE TITLE
Scale captions font size according to screen size

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2669]
The captions font size is reducing if the screen size is increasing. As a result, the full screen mode of the player has smaller font for captions. Please check the below picture of four screen shots at different screen sizes, the left 2 are with normal mode and right 2 are with full screen mode of the player.

![image](https://user-images.githubusercontent.com/25850972/34271632-203da388-e65b-11e7-9c0b-cf8bd2b90dc8.png)

**Comment by joncameron** [comment]
This should get enhanced in the Avalon MediaElement fork in Avalon 7.
