### ISSUE TITLE
Playlist is not displaying rest of the items if the first item has restricted access for the user

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2675]
### Descriptive summary
Server: https://spruce.dlib.indiana.edu
Testing: Regression Testing
Browser: Chrome 62.0.3202.94
Operating System: Windows10
Issue: Playlist is not displaying and not letting you play rest of the items if the first item has restricted access for the user, and rest all the items have access.

### Steps to Reproduce
1. Create a public or shared playlist
2. Add items to the list and make sure that the avalon user doesn't have access to the first item in the list.
3. Share this playlist to the avalon user, and open it using avalon user credentials. The items below the restricted item would not be playable.
![image](https://user-images.githubusercontent.com/25850972/34275255-81131864-e66a-11e7-85c3-c8372a7c38e8.png)

**Comment by Karthikeya212** [comment]
Note: If the restricted item is at any other position except the starting position, the playlist is behaving as expected.

![image](https://user-images.githubusercontent.com/25850972/34275444-54814e96-e66b-11e7-94a7-c79b742f7c46.png)

![image](https://user-images.githubusercontent.com/25850972/34275382-11f328ec-e66b-11e7-8bca-ab3efb009469.png)

**Comment by Karthikeya212** [comment]
Though the items are showing up, user is unable to play the items below the restricted items if it is on the top, but the items are playable when I switch the position of this restricted item.

**Comment by bkeese** [comment]
Does the page switch to the unplayable item? Or does it do something else (or nothing)?

**Comment by Karthikeya212** [comment]
It just navigates to home page saying that user is unauthorized to play

**Comment by cjcolvar** [comment]
I'm seeing different behavior on a different playlist.  The playlist @Karthikeya212 shared with me in slack is share with token.  I'm guessing that that might be the cause of the issue.

**Comment by Karthikeya212** [comment]
Yeah I think @cjcolvar  is correct, I don't see this behavior for a public playlist

**Comment by cjcolvar** [comment]
At this point I think the playlist items on the right (and anywhere else the links are like related items) need to have the token query param included.

**Comment by phuongdh** [comment]
Updated issue to reflect current state

**Comment by bkeese** [comment]
About related items, clicking those effectively just clicks the relevant playlist it on the right. So adding the token there will be adequate.

**Comment by phuongdh** [comment]
Confirms busted on MCO as well https://media.dlib.indiana.edu/playlists/1954?token=2TnNqUhEMNi3dJ5Sht3hEQ

**Comment by cjcolvar** [comment]
@Karthikeya212 this has been merged and it looks good to me on spruce.

**Comment by Karthikeya212** [comment]
Yeah looks good to me
