### ISSUE TITLE
Unable to change quality using keyboard

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2678]
### Descriptive summary
Server: https://spruce.dlib.indiana.edu
Testing: Regression Testing
Browser: Chrome 62.0.3202.94, EDGE 40
Operating System: Windows10
Issue: Unable to change quality using keyboard. User can navigate to the quality icon using TAB, once quality icon is reached it opens up the panel with high/med/low options, but the user cannot navigate/select any of those option in the panel. The next TAB click is an empty operation and user cannot see where the control is, and one more TAB takes control to the next available icon in the player. Moreover, the quality panel never closes after that unless user hovers over the quality icon.

Note: There is also an empty TAB operation before control moves to the quality icon, i.e. user cannot see where the control is before reaching quality icon.

**Comment by cjcolvar** [comment]
I don't remember it being this bad when I tested earlier this week.  I wonder if adding the closed captions toggle made things worse.

**Comment by Karthikeya212** [comment]
I checked it again and I observed that after highlighting quality icon a TAB after that is actually going into the quality panel and using the down arrow we can select the relevant quality, but the user has no way to find this out as no visible sign that the quality panel is highlighted. However the panel closing issue still resides, i.e. the panel doesn't collapse automatically.

**Comment by cjcolvar** [comment]
I was able to open the panel and up the arrow keys to change qualities by hitting enter when the quality icon was highlighted, but had the same issue of not being able to close the quality panel.
