### ISSUE TITLE
Source item details link should link to master file

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#2680]
### Description
Playlist item's source item details link is to its parent media object instead of the master file that the playlist item comes from.  This could be confusing when the playlist item comes from something other than the first section of a media object.

### Done Looks Like
- For a playlist item, the "Source Item Details" accordion links to the masterfile route, rather than the media object for a given playlist item (playlist items are always at the masterfile level, not the object level)

**Comment by Dananji** [comment]
@joncameron When the accordion link is changed to the MasterFile route with the text as MasterFile's title/id instead of the MediaObject's title/id, do you think we need to still show the MediaObject's title/id in there?
