### ISSUE TITLE
Issues with Related Items section in playlists

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2682]
### Descriptive summary
Server: https://spruce.dlib.indiana.edu
Testing: Regression Testing
Browser: Chrome 62.0.3202.94, EDGE 40
Operating System: Windows10
Issue: Issues with Related Items section in playlists

1. If there are other items already present in the playlist that are unrelated, now if new items that are related the playlist is not creating the "Related Items" section for these items.
![image](https://user-images.githubusercontent.com/25850972/34305402-fdba918e-e70b-11e7-9b77-44015a801349.png)

2. If I add the related items to an empty playlist, then the "Related Items" section is created properly in the playlist, but then if I add any unrelated items to the playlist the Related Items section doesn't load any content for the previous items.
![image](https://user-images.githubusercontent.com/25850972/34305522-78642a80-e70c-11e7-9093-6ac128788d2c.png)

Note: In case-2, if I refresh the page and only play the related items, then the Related section is showing content properly, but once I play the unrelated item and go back to the related items the Related section is no longer showing content.

**Comment by cjcolvar** [comment]
This is happening when navigating to a playlist item that has no related items and then navigating to one that does.  At that point the related info panel appears but is empty and will never reload until page reload.

**Comment by Karthikeya212** [comment]
Tested on Spruce
