### ISSUE TITLE
Fix streaming on AWS

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2701]
MEJS4 with hls.js now makes XHRequest to m3u8 and ts files, so having CORS header has become a requirement for streaming servers.

I've read that when using signed CloudFront urls with cookie, `allow *` is considered too permissive and hence not allowed. Need to allow only the specific domain for Avalon web. This means the S3 derivative bucket policy in CloudFormation script needs updating as well.

**Comment by phuongdh** [comment]
@mbklein please take a look at this issue. I mucked around too much and ruined my stack, gonna try to rebuild everything from CloudFormation now.

**Comment by phuongdh** [comment]
Fixes are now in `aws-fix` branch

**Comment by davidschober** [comment]
@mbklein or @carrickr is this on our staging branch? If so we want @phuongdh to move to closed.

**Comment by davidschober** [comment]
@mbklein @phuongdh @carrickr can you verify where we're at with this?

**Comment by phuongdh** [comment]
I cherry-picked these from nustaging after confirming with mbk so they should work.
