### ISSUE TITLE
Exit full screen mode when user wants to add markers

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2705]
According to the changes made to the player, when user clicks on any of the Scrubber/Thumbnail/AddToPlaylist icons on the player when it is in full-screen mode, the player automatically comes out of the full-screen mode and allows the user to continue his work.

This functionality is missing when user clicks on Add Markers icon on the playlist player. However, clicking scrubber icon is exiting the full-screen mode in playlist player.

**Comment by joncameron** [comment]
This may already be fixed.

**Comment by joncameron** [comment]
This behavior is no longer present.
