### ISSUE TITLE
Keyboard Navigation on Safari Not Working Properly

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2707]
### Description
When using tab and shift+tab to navigate, Safari doesn't navigate through the elements in the proper way that Chrome and Firefox exhibit—that is, navigation doesn't go from element to element across the buttons and navigational elements in the player.

### Environment
Spruce, Avalon 6.3, Safari

### Done Looks Like
Keyboard navigation in Safari is the same as the behavior in Firefox and Chrome.

**Comment by joncameron** [comment]
General question for UXO—what are the most common browsers for assistive browsing? We could ask experts and assign priority from there. This appears to be a mediaelement.js issue, and we could also file a bug with them directly.

**Comment by cjcolvar** [comment]
@joncameron Can you retest this?  I can't reproduce it.

**Comment by joncameron** [comment]
I reproduced this in Safari 12.1.1, macOS 10.14.5. When tabbing in Safari, the focus never goes to:
* Buttons on the media player beside the rail and the centered "play" icon
* The structure below the media player

**Comment by cjcolvar** [comment]
Weird.  I'm running Safari 12.1 on macOS 10.14.4 and it all looks normal to me.  
@davidschober are you able to reproduce this?

**Comment by joncameron** [comment]
@bkeese mentions that for our previously used Mediaelement version there was a tab-order structure which may have been abandoned when we upgrade. Investigate?

**Comment by Dananji** [comment]
I tested this on a Safari browser (Version 12.0 and macOS 10.14) and I was able to reproduce this.

When I searched for this in the internet, found that after macOS 10.7 the new default behavior of Safari was limited when it comes to navigating with tab key.
To enable this; Preferences -> Advanced -> Accessibility -> Check `Press Tab to highlight each item on webpage` 

When this is enabled the tab navigation works as expected (similar to Chrome)

**Comment by phuongdh** [comment]
@Dananji still sees this behavior in latest Safari

**Comment by SumithBaddam** [comment]
This issue is specific to the latest version of Safari browser. By default, they have disabled the tab press for highlighting. To enable this, user needs to check for press tab to highlight in the accessibility options.

Safari Browser -> Preferences -> Advanced -> Accessibility -> Check Press Tab to highlight each item on webpage.

**Comment by mcwhitaker** [comment]
Jon will see how he wants this taken care of.

**Comment by joncameron** [comment]
Safari documentation for keyboard shortcuts and gestures:
https://support.apple.com/guide/safari/keyboard-and-other-shortcuts-cpsh003/mac

Safari's behavior has changed so that links to not receive focus from tabbing. This functionality is available by using option+tab instead.

Based on reading through some more documentation, this is a Safari feature and not a bug, and overriding via JS or some other means would be also mucking with MacOS accessibility setups that a user may have. It seems to be a slightly gray area but this also appears to be a platform-specific convention and doesn't necessarily go against WCAG (https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=214%2C211#keyboard).
