### ISSUE TITLE
rework avalon 7 vision paper for f2f

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2709]
## Description

Now that we have some space since our original draft of the Avalon on Hyrax White paper, we should revisit it and rewrite it. This document should serve as our vision document. 

## Done looks like:

* Section on "components"
* Section on "Avalon as a Solution Bundle"
* Section on milestones w/links to GH milestones

**Comment by davidschober** [comment]
@joncameron can you take a last look at this, the close?

**Comment by joncameron** [comment]
Looks good! We'll be discussing tomorrow.
