### ISSUE TITLE
Create Needs Assessment Document/ Hyrax Deltas

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2710]
# Description

Using the user stories from #2470 we will create an analysis document outlining what features are in Hyrax or how we can configure/customize hyrax. We should also note what we need to build greenfield and what could be a separate component. Some of this work has been done (in our previous milestone work) and some is in our heads. The goal is to get it onto a single document prior to the F2F

## Done looks like

The spreadsheet in #2470 is update with In Hyrax column and notes about implementation for each user story.

**Comment by davidschober** [comment]
I added this to the vision doc.

**Comment by davidschober** [comment]
@joncameron can you take a peak?

**Comment by joncameron** [comment]
@davidschober I've read through this again and it looks good. The next step is to start breaking each thing out, figuring out when in our timeline we're going to investigate points that are needed; all of that good stuff.
