### ISSUE TITLE
Create Delta For Hyrax/Avalon Features

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2711]
### Description
We need a list of features in Hyrax 2.x to figure out the features that will map to Avalon 7, and which do not exist or do not exist to our needs in Hyrax.

### Done Looks Like
A document is written that details how current Hyrax features correspond to the existing Avalon features

**Comment by cjcolvar** [comment]
@joncameron is this a duplicate of #2710?

**Comment by joncameron** [comment]
@cjcolvar It is. Closing it out.
