### ISSUE TITLE
Remove Red5 references from docs

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2712]
# Description 

Now that we are all HLS all the time, we need to update our manual install docs and upgrade docs to reference shutting down Red5/ RTMP services. (woohoo)

## Done looks like
- docs are reviewed and updated with shutdown/move to pure HLS streaming.
- Decide on what we're shipping our shipped package (nginx)

**Comment by davidschober** [comment]
With manual install we are pre-chunking HLS so for development you don't need to run a streaming server. If you want one for dev you can use NGINX. 

For Production we recommend using Wowsa, Cloudfront or other robust streaming server. Some folks have used NGINX.

**Comment by joncameron** [comment]
Someone should test the manual installation instructions to make sure everything's A-OK.
