### ISSUE TITLE
HLS Pause/Seek Timing Issues 

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2723]
### Description
HLS pause/seek related timing issues are caused various issues in the player.

### Environment
Spruce, Firefox 57, macOS 10.11.6

### To Reproduce the Zoom Scrubber Issue
- Go to https://spruce.dlib.indiana.edu/media_objects/g732d898n
- Click Track 5
- Play, and then pause
- Click Track 2
- Click in the zoom scrubber rail and click play
- Track 2 is still selected, but Track 5 is highlighted and playing

**Comment by bkeese** [comment]
I have confirmed this is a bug in MEJS's use of the hls shim. The demo player on the hls.js page works as expeced (http://streambox.fr/mse/hls.js-0.7.10/demo/). The demo player on mediaelementjs homepage doesn't exhibit's the same bug (when choosing an HLS source): http://www.mediaelementjs.com/

**Comment by bkeese** [comment]
Correction. It was a problem in how avalon was configuring mejs with the 'preload' option. We were setting the value to 'true', which is not a valid value. Setting it to 'auto' appears to fix the problem.
