### ISSUE TITLE
Work Out Throttling for Batch Ingest (It's Too Powerful for AWS)

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2724]
Our specific issue is that currently after we load a spreadsheet we [immediately queue](https://github.com/avalonmediasystem/avalon/blob/71a1adb02130a05ca0316086128f9f73847d07d6/lib/avalon/batch/ingest.rb#L63) all the media objects for processing.  This is also going to kick off a transcoding task for every media object.

Elastic Transcoder can handle a large queue, but only always you to queue 2 jobs per second, with support for short bursts of hundreds ([doc](https://docs.aws.amazon.com/elastictranscoder/latest/developerguide/limits.html))

```
Maximum rate at which you can submit job requests:

Create Job: You can submit two Create Job requests per second per AWS account at a sustained rate; brief bursts of 100 requests per second are allowed.

Read Job: You can submit four Read Job requests per second per AWS account at a sustained rate; brief bursts of 100 requests per second are allowed.
```

So reading in a thousand line spreadsheet and then throwing all 1000 at the transcoder in a second or two results in:

![image](https://user-images.githubusercontent.com/5350060/34676280-50d292da-f45a-11e7-9b10-c836e4011c76.png)

My proposal is to break out the ingest.rb line referenced above and allow throttling params to be passed in.  For folks running matterhorn or such where we haven't seen this problem, they can just not throttle.  For AWS we have a specific ingest job and I would propose we have it throttle to 2 items per second.

This is somewhat imperfect for AWS.  With AWS we're reacting to the deposit of manifest files and then firing off a job for that specific file, which then in turn kicks off jobs for each media object in the file.  So if four users all drop spreadsheets at the same time, then we'd have four jobs all spawning jobs.  This would still be under the burst limit, but theoretically if this went on for a long time we could end up over the burst limit.

The other area of imperfection is that for people who aren't doing lots of massive batches back to batch you probably don't need this.  I specifically blew up Elastic Transcoder after doing multiple submissions and replays of objects right before a demo and probably shoved us past the burst limit.  So in theory you could fix this via making sure your power users who use batch know to space their stuff slightly on AWS and not throw in anything too huge.

**Comment by davidschober** [comment]
@carrickr is this abandoned.

**Comment by davidschober** [comment]
Dealt with this in docs.
