### ISSUE TITLE
Observations on Android OS

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2748]
Server: spruce.dlib.indiana.edu
OS: Android 6.0.1
Browser: Chrome 63.0.3239.111

1. Timeline scrubber disappears in the player when user changes quality
![whatsapp image 2018-01-19 at 1 22 59 pm](https://user-images.githubusercontent.com/25850972/35165506-8971bcb8-fd1c-11e7-8416-f4cbe0036e25.jpeg)

2. Playlist items are not showing the timeline scrubber while playing the file (similar to above screenshot)

3. Cannot do play-forward/play-backward using mini scrubber in the playlist item (unresponsive)

**Comment by joncameron** [comment]
The bugs listed here could not be reproduced.
