### ISSUE TITLE
Rail is Highlighted in Yellow When Clicked

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2750]
### Description
A highlighted section around the timeline appears when the user clicks on the rail to seek.

### Environment
Firefox 67 on macOS 10.14.5.

### Example
![jan-22-2018 11-39-31](https://user-images.githubusercontent.com/1406618/35238587-e14eef3a-ff7b-11e7-8209-564bd33b886b.gif)

### Questions
This appears when clicking some element in the media player at some times and not on others. What's the behavior? I think this is an accessibility thing, but what is it accomplishing and how can we normalize the behavior?

### Done Looks Like
Clicking on the scrubber does not make visible the yellow highlighted area around the rail.

**Comment by joncameron** [comment]
What browsers is this occurring in?

**Comment by davidschober** [comment]
part of #2786

**Comment by joncameron** [comment]
This is a Firefox issue.

**Comment by joncameron** [comment]
This seems to be appearing intermittently in Firefox now. This can be very low priority since it appears much less intrusive now.
