### ISSUE TITLE
Set Up local Dev Environment (possibly with Docker)

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2751]
### Description

- Documentation for setting up development environment
- Docker setup
- Decisions on initial pass at transcoding and streaming (ngnx, ffmpeg)
- Decision on path to side load fixtures so you can work without transcoding -- scope of this is to talk about it.

### Done Looks Like
- [x] Getting Started instructions written for developers

**Comment by phuongdh** [comment]
We need those decisions made

**Comment by cjcolvar** [comment]
Is this done for now given that more will come with #2200?
