### ISSUE TITLE
Create New Repo for Avalon 7 Solution Bundle App

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2753]
### Description
We will need a home for our new App! 

### Done Looks Like
- [x] Create the repo
- [x] Discuss app vs. engine
- [x] Generate a Hyrax app or engine into repo
- [x] If engine, generate another repo to hold the canonical app for deploying to test server

**Comment by joncameron** [comment]
I'm going to suggest 'avalon7' as the name for this repo right now. Thoughts @davidschober ?

**Comment by joncameron** [comment]
avalon-777? avalon-s? avalon-rebirth? avarax? hyravalon? samveravalon? ava7on?

**Comment by bkeese** [comment]
avalonagain? hyracylon? samalonvera?
