### ISSUE TITLE
Explore web pack within a rails app

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2756]
## Description 

- Upgrade rails to 5.2 (if necessary)
- figure out how web pack works in a hyrax app
- Generate new issues at will.

## Done looks like
- Verify we can do it
- write some docs up for the community. 

https://github.com/rails/webpacker

**Comment by cjcolvar** [comment]
We found that rails 5.1 has support for webpacker built in and it works as advertised within a new hyrax app.  There isn't really any instructions other than follow the instructions in the README on https://github.com/rails/webpacker
