### ISSUE TITLE
Webpacker and modern JS practices swarm

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2758]
### Description

Get up to speed on best practices, make some issues around JS.

- Webpack
- State management?  Redux, Rxjs
- Frameworks or no?  (ReactJS, Vue, etc)

**Comment by davidschober** [comment]
Talk about general JS topics.

**Comment by cjcolvar** [comment]
We decided that we could use a knowledge spike to investigate state management and/or framework further.

**Comment by cjcolvar** [comment]
Issue created: https://github.com/avalonmediasystem/avalon/issues/2786
