### ISSUE TITLE
Inject Avalon Player in Hyrax Generic Work View

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2766]
### Description
Adding our IIIF standalone player to the view for a generic Hyrax work. The player should try to pull in a manifest, whether successful or not.

### Done Looks Like
- The IIIF Player is instantiated on page load for items that have audio or video content #2853 
- The IIIF Player is instantiated with the manifest generated from the work #2854

**Comment by mcwhitaker** [comment]
As of today, this EPIC is waiting on #2854.
