### ISSUE TITLE
Update IIIF Gem to Include Presentation 3.0 Manifest Generation

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2768]
### Description
The IIIF gem used in Hyrax does not yet support the IIIF Presentation 3.0. 

### Done Looks Like
- IIIF Presentation 3.0 manifests can be generated from a Hyrax Generic Work type containing an Avalon video

**Comment by cjcolvar** [comment]
This would be good to do as a small community sprint/effort.
