### ISSUE TITLE
Performance Issues When Loading MediaObjects With Large Number of Sections

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2769]
### Description
Loading a media object with large numbers of sections takes a very long time, and performance reduces exponentially as the number of sections increases. Performance needs to be improved when returning a media object page, possibly by reducing calls to Fedora.

### Done Looks Like
- Loading a media object page with large numbers of sections is a faster operation than current, ideally fitting in with the time guidelines previous established (https://wiki.dlib.indiana.edu/display/VarVideo/Performance+Metrics).

**Comment by joncameron** [comment]
MBK identified a high-cost call and replaced it with something equivalent but cheaper regarding performance, seen in the PR referenced in the issue.

**Comment by cjcolvar** [comment]
Fixed with #2783, #2781, and #2776.
