### ISSUE TITLE
Scope Structural Metadata editor

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2771]
## Description

per face to face, we promised a scope document with estimates to key stakeholders for a structural metadata editor that will:

* Allow time point to be visually edited
* Investigate use of waveform for visually highlighting time points
* Allow visual editor to kick out and store our current structural doc
* Allow for editing existing structural metadata 
* Structural will be shown in waveform or scrubber.
* Time  points can be deleted
* Generate Stories.

### Ideas Document
https://iu.app.box.com/notes/276449280505

**Comment by davidschober** [comment]
Ideally we are writing code that can be reused. Waveforms should be a general on table or off.

**Comment by mcwhitaker** [comment]
@adamjarling , @cjcolvar , @bkeese , @joncameron , @davidschober  and me will meet.  I will schedule the meeting.

**Comment by mcwhitaker** [comment]
Doodle poll: https://doodle.com/poll/xqintnv9n5nnzqwx
