### ISSUE TITLE
Add GH Hooks to avalon-bundle

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2774]
## Descriptions 

Building on work from #2753, add GH hooks as necessary and document out setup. 

- [x] Github hooks setup
  - [x] Linters
  - [x] CI (Circle CI?)
  - [x] codeclimate
    - [x] es lint
    - [x] rubocop
- [ ] Watching other repos for builds
    - [ ] hydra_derivatives?
    - [ ] hyrax?

**Comment by joncameron** [comment]
After avalon-bundle is moved to samvera-labs, this story can get worked on.

**Comment by joncameron** [comment]
@adamjarling has set up es-lint as part of the webpack compilation process.

**Comment by carrickr** [comment]
Rubocop is running, but needs numerous excludes: https://circleci.com/gh/samvera-labs/avalon-bundle/9

**Comment by carrickr** [comment]
ESLint is also running, but reports 25 errors: https://circleci.com/gh/samvera-labs/avalon-bundle/10

**Comment by carrickr** [comment]
Code Climate is 504ing, I added the code to the the yml file but can't log into code climate to do the other half

**Comment by cjcolvar** [comment]
TODO
@carrickr  will take linting and rubocop out of circleci build. 
@cjcovar and @phuongdh will hook up codeclimate and ensure that it is using bixby and the eslint profiles.

**Comment by cjcolvar** [comment]
@joncameron @davidschober I'm now questioning watching other repos to kick off builds so I think it should probably come out as a separate ticket if the need arises.
