### ISSUE TITLE
Masterfile Management Can't Handle Filenames with Spaces

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2778]
### Description
When a file is ingested, has spaces in the filename, and is due to be moved to another directory after processing with masterfile management, the file never actually moves and an error is thrown.

### Done Looks Like
Users can safely ingest filenames with spaces and have them be moved as the system is intended to do.

### Likely Culprit
https://github.com/avalonmediasystem/avalon/blob/dc80e4390ff46e71bb210a1a0591582e4f2a429d/app/jobs/master_file_management_jobs.rb#L46

### Backtrace from IU Production Honeybadger
![screen shot 2018-01-26 at 11 23 12 am](https://user-images.githubusercontent.com/1406618/35449670-ad35c634-028b-11e8-9cb6-999a2276c8e9.png)

**Comment by Karthikeya212** [comment]
Tested on spruce
