### ISSUE TITLE
Large Batch Ingest Overloads Fedora and Doesn't Process Properly

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2798]
### Description
Attempting to ingest a batch containing a single media object with 195 sections failed in process, and only a subset of them ingested. 

The Batch::Entry#process! method should be refactored so it doesn't write to fedora so much. See potential approach here: https://gist.github.com/cjcolvar/5f25c70ca0252c8463f34942635346a0

### Environment
- IU Production, Avalon 6.3.2

**Comment by davidschober** [comment]
I think @carrickr documented this.

**Comment by davidschober** [comment]
redundant with #2770
