### ISSUE TITLE
Streaming quality selection is not sticky.

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#2802]
How to reproduce:
When in a new session, load a video object and change the streaming quality from 'auto' to 'high'. Then, select a different video and observe the selected quality.
Expected behavior:
The previously selected quality ('high') should be selected by default.
Actual behavior:
'auto' is the selected quality.

**Comment by Karthikeya212** [comment]
Tested on Spruce: The streaming quality is set to 'medium' by default and even though the quality is changed it is reverting back to 'medium' after a reload or on opening a new item in a separate tab

**Comment by bkeese** [comment]
Ah. The quality is now pulled out of the session as it should, but code for setting the session quality was never added when moving to mejs4.
