### ISSUE TITLE
Investigation of Issues with Upload of Large Item Sets from GUI

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2811]
### Description
Investigation needs to be done regarding bug #2801 before issues can be created to deal with the work needed to resolve.

### Done Looks Like
- Timeboxed investigation is performed to seek out probably causes and work needed to for  #2801

### Reference Issue
research for #2801

**Comment by carrickr** [comment]
Easy fix is stick in a spinnie wheel that spins until all the master file creates have happened.  Then refresh the page.  

This does have the problem that you're still doing one big request that needs to create numerous Fedora calls.  So if the request is too big for Fedora, it breaks.  Solving this involves moving all master file creates to job based calls that can be throttled.  But user behavior becomes more complicated.  Do you tell the user "Hey thanks for the files, come back in an hour after I'll run your requests through a low rate", get into more complicated refreshes, etc?

@cjcolvar and I recommend for doing the spinnie wheel and documenting if you try to make too large of an object via GUI it's gonna blow up at some point.  For reference NU was able to do a 60 part object via GUI with the only issue being the page loading (which the spinnie wheel fixes), the object itself was created with its parts.
