### ISSUE TITLE
Plan for Executing iiif_manifest Gem Work

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2815]
### Description
Developing a plan for carryout out work to implement necessary IIIF 3.0 support 

### Done Looks Like
- Figure out ways to break down #2201 and #2850
- Plan of attack on how to do the work
- Initial ping of community

**Comment by cjcolvar** [comment]
I've reviewed the iiif_manifest gem some and now think that it might not be that much work to implement the changes.  My plan right now is to try doing it ourselves and ping community members for review and feedback instead of trying to coordinate work with others.
