### ISSUE TITLE
MEJS Quality Plugin needs work

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#2820]
The MEJS quality plug-in will not display the quality choice modal if a derivative with the default quality does not exist. That is, unless the default is 'auto', in which case it will look for a derivative with the quality 'auto' or find the first available derivative if 'auto' isn't available.

We need to change the plug-in so that it will find the first available derivative when the default it not there, no matter what the default is.

This change should probably be pushed upstream.

**Comment by cjcolvar** [comment]
@bkeese should this be tagged quality-assurance or is it waiting on a PR to upstream?

**Comment by bkeese** [comment]
It's already been QA'd. 
Push upstream? Maybe?
