### ISSUE TITLE
Playlist sorting fails if there is a deleted item in the list

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#2824]
### Description
If there's a deleted item in a playlist, a user loses the ability to sort the items in the playlist.

### Done Looks Like
Users can sort playlists which contain deleted items.

**Comment by bkeese** [comment]
I just tried this on Spruce with Chrome and Firefox and was unable to reproduce.

**Comment by cjcolvar** [comment]
I tried in Chrome and wasn't able to reproduce this either.
