### ISSUE TITLE
Paused Seeking

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#2826]
A general paused-seeking problem for media_objects and playlist items. Specifically, it is a problem when seeking before playing. And it is only for certain media objects, and only when seeking to certain time points. In most cases, this behavior doesn't surface.

After seeking, the poster and spinner remain until play is clicked. The video then begins playback at the correct seek point.

https://spruce.dlib.indiana.edu/media_objects/pn89d657h/section/pv63g024f?t=300.0,400.0

Refs #2822

**Comment by joncameron** [comment]
This may be related to thumbnail sheets.

**Comment by joncameron** [comment]
Dananji can look at this again and see if it's still an issue. Or go back and think about what's possible with paused seeking, or what the right behavior is.

**Comment by joncameron** [comment]
I'm closing this since we're doing a MediaElement upgrade and this behavior hasn't been seen in a while. A lot has changed in the player since this issue was created.
