### ISSUE TITLE
IE11: Section navigation issues

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2827]
Issue 1: Autoswitch/Autoplay not working in a multi-section item.

Issue 2: Autoswitch/Autoplay not working in a playlist with multiple items.

Issue 3: Cannot navigate to other items in the playlist by clicking on the item. So, cannot play any other item in the playlist except the first.

**Comment by bkeese** [comment]
https://babeljs.io/docs/usage/caveats/

**Comment by adamjarling** [comment]
Hmmm. Interesting.  So Babel is being brought into the application through the 'sprockets-es6' gem, or whatever it's named.    Can a gem be configured?  In this case, like to include a polyfill?  Or could we install the polyfill code directly into the application, before our application code is rendered?  

https://babeljs.io/docs/usage/polyfill

**Comment by adamjarling** [comment]
As a test, if you chucked this into the app, does it seem to fix whatever is breaking?

`<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-polyfill/6.26.0/polyfill.min.js"></script>`

**Comment by bkeese** [comment]
Yes. It does solve the problem.

**Comment by cjcolvar** [comment]
@bkeese @joncameron @davidschober Did this ever get fixed?

**Comment by bkeese** [comment]
Looks like babel-polyfill is coming in with sme package.

**Comment by joncameron** [comment]
We'll need to retest this The package is there, and so it might be fine now.
