### ISSUE TITLE
Add Standard Files to avalon-bundle Repository

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2832]
### Description
We need templates and boilerplate for the new avalon-bundle repository.

### Questions
- Do we need the "Copyright IU/NU Regents" stuff in our headers?

### Done Looks Like
- Figure out what we need for copyright/license notices (we'll be using the standard Apache 2 license file) (the license file is supposed to not contain the copyright notice)
- Add PR template 
- Code of conduct file (Use Samvera generic)
- Contributing file
- Bug report template

**Comment by joncameron** [comment]
Jon notes that part of Apache2 is including the copyright header—we may need to look at other examples.

**Comment by davidschober** [comment]
@joncameron to verify with @jwd about copyright.
