### ISSUE TITLE
Safari: Player API Doesn't Respond Initially

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2833]
### Description
The player API does not work on the embedded player in Safari on page load. If a user clicks play in the player, the Player API starts to work (for example, sending a seek command).

#### Environment
IU Production

### Done Looks Like
- The iframe containing the Avalon embedded player responds to the Player API

**Comment by cjcolvar** [comment]
I vote for won't fix and I already put a note on the player api wiki page:
https://wiki.dlib.indiana.edu/display/VarVideo/Player+API

This is based upon this posting and local testing:
https://webkit.org/blog/7734/auto-play-policy-changes-for-macos/
