### ISSUE TITLE
Player js issues in audio/embed context.

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#2837]
### Description
In mejs4_helper_utility.es6 line 89, an error is occurring in an embed context:
cannot read property 'querySelectorAll' of undefined.

There is another error in this context that shows up in Firefox: player.qualitiesButton is undefined (same file, line 33)

### Tasks
- [x] Put checks that element exists in the JS, now that an element is potentially not present in embed scenarios.

**Comment by bkeese** [comment]
Here is a page where these errors are showing up:
https://staging.culanth.org/articles/2-sounds-of-democracy-performance-protest-and

**Comment by adamjarling** [comment]
What branch should I do the work on?

**Comment by bkeese** [comment]
I guess develop.

**Comment by adamjarling** [comment]
I see the qualitiesButton error on `app/assets/javascripts/media_player_wrapper/mejs4_helper_quality.es6` in the embed url above, but not the error on mejs4_helper_utility.es6 line 89.   

I'll push up a fix and let's see if it works.

**Comment by adamjarling** [comment]
@bkeese I'll let you evaluate whether this commit fixes the embed error issue.

**Comment by bkeese** [comment]
LGTM. Thanks.
