### ISSUE TITLE
Bibimports in Batch Remove the Rights Statement

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2838]
If you have a bib id and import, any rights statement you had in the spreadsheet gets overwritten.

**Comment by joncameron** [comment]
This is the case for all metadata fields if there's a bib import. We currently don't have a way to do both bib import and additional metadata (for example, local "other identifier" information that would be relevant in addition to the bib import metadata pull). This is the normal behavior of Avalon.
