### ISSUE TITLE
Text In Embedded Audio Player Cycles Between Weights [Safari]

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2844]
### Description
When an audio item is embedded on a page, the weight of the text changes in unexpected ways. In the worst case, it cases the entire player to wiggle around as the elements move slightly due to the frequent changes between bold and not bold text, or at least that what the case appears to be (example 1). In other less drastic cases, click events to navigate appear to change the text weight for a split second (example 2). I've observed this only in Safari so far—Safari is the browser to most noticeably exhibit this in terms of weird side effects, at least.

#### Embed on External Site - IU Production (https://staging.culanth.org/articles/2-sounds-of-democracy-performance-protest-and)
![feb-27-2018 11-43-53](https://user-images.githubusercontent.com/1406618/36756930-6d089b56-1bde-11e8-8eaf-b391b9b5fb74.gif)
####  Test Embed on Internal Wiki - IU Production
![feb-27-2018 16-52-39](https://user-images.githubusercontent.com/1406618/36757094-ad40a074-1bde-11e8-927d-dc0716255805.gif)

**Comment by Dananji** [comment]
@joncameron Is this still an issue? The example in the ticket no longer exists.
So I embedded the player in a blog post. And it doesn't wiggle when interacting (play/pause) in Safari. Although the tooltip showing the time on the time rail gets cut off.
Here's the blog post link: https://dananjiliyanage.blogspot.com/2019/12/planet-earth-planet-earth.html

**Comment by joncameron** [comment]
@Dananji I can reproduce it at the current URL for this Culanth blog post: https://journal.culanth.org/index.php/ca/article/view/ca33.1.01/43

![Dec-10-2019 12-17-39](https://user-images.githubusercontent.com/1406618/70552325-2116ed00-1b47-11ea-8f50-9634419e2ef7.gif)

**Comment by Dananji** [comment]
I will check it out :+1: Thanks!

**Comment by Dananji** [comment]
@joncameron Yes I can see this in Safari 11.1. But not in the newer versions. This seems to be fixed after Safari 12.1. It would still be a problem for users who are using older versions, so I will try to fix it.

**Comment by joncameron** [comment]
@Dananji To make this more complicated (😫) I reproduced this bug and made the gif using Safari 13.0.3 on macOS 10.15.1.

**Comment by Dananji** [comment]
Oh! :|

**Comment by cjcolvar** [comment]
I tested with the same environment as Jon and I see the broken behavior on Cultural Anthropology but not MCO.  Spruce looks fine to me as well.
