### ISSUE TITLE
Necessary Middleware and Services are Installed and Running on Docker/Dev Environments

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2846]
### Description
In our Avalon 7 development environments, we'll need necessary services for transcoding and background jobs. Everything should be set up so that Hyrax can do the out of the box ingestion and transcoding.

### Done Looks Like
- FFmpeg is installed properly
- Derivative generation happens
- new issues spawned for future work

### Parent Issue
#2200

**Comment by davidschober** [comment]
playback does not need streaming at this phase.
