### ISSUE TITLE
Organize Community Involvement with iiif_manifest Work

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2851]
### Description
We'll want to check in with the community about our work with iiif_manifest gem, since others have expressed interest in helping out. 

### Done Looks Like
- Chris and Ryan check in with the community and see when and who is interested in helping with this development work.

### Parent Issue
#2201

**Comment by davidschober** [comment]
relates to #2850

**Comment by joncameron** [comment]
From Chris in #2851: "I've reviewed the iiif_manifest gem some and now think that it might not be that much work to implement the changes. I'm still a little unsure about how to break down the work in order to distribute it and not have work overlapping. My plan right now is to try doing it ourselves and ping community members for review and feedback instead of trying to coordinate work with others. We could still ping those who might be interested for review and testing."
