### ISSUE TITLE
Strategize for Avalon RDF in base hyrax

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2856]
## Description 

#2223 is big. We need a discussion to figure out our strategy, etc

## Done looks like

- [x] meeting is held with Jen, Julie, Chris
- [x] Strategy is documented on #2223

**Comment by jlhardes** [comment]
@jenyoung and @cjcolvar - Take a look at the documented strategy and make sure that is correct.

**Comment by cjcolvar** [comment]
Write up in #2223 looks good to me!

**Comment by jenyoung** [comment]
@jlhardes this looks good to me! thanks for writing it up!
