### ISSUE TITLE
Sections missing when performed a large batch ingest on mco-staging

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2859]
### Description
When performed a 100-section item ingest using batch manifest, the final ingested item only had 93 sections ingested and 7 sections were missing. There were no errors for ingested sections, all the 93 sections were properly ingested.

Item: https://mco-staging.dlib.indiana.edu/media_objects/3j3336052

Manifest used:
[manifest_python_100_sec_item_small.zip](https://github.com/avalonmediasystem/avalon/files/1790661/manifest_python_100_sec_item_small.zip)

Screenshot of ingested item:
![image](https://user-images.githubusercontent.com/25850972/37114648-e46c8be2-2216-11e8-960a-baf0510ebd6e.png)

**Comment by joncameron** [comment]
This should be retested. I haven't seen this at all in production.

**Comment by davidschober** [comment]
@joncameron this feels stale. Is this happening on a production instance/is it reproducible ?

**Comment by joncameron** [comment]
Super stale; closing.
