### ISSUE TITLE
[Android] Quality Selector Popup Not Disappearing Upon Selection

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2874]
### Description
The popover doesn't disappear when clicking a quality. It only goes away when a click somewhere else happens.

**Comment by davidschober** [comment]
Need to retest. This is old @SumithBaddam can you retest? If it's no longer an issue, let us know and we'll close.

**Comment by bkeese** [comment]
NB: There is on open PR that addresses this.

**Comment by davidschober** [comment]
Great! Do you know which one? Can we attach it to this issue and move the issue to Review?
