### ISSUE TITLE
Inconsistencies in search results on Spruce/Mallorn

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2881]
### Steps to reproduce
1. Login with Admin/Manager and open My collections page
2. Click on a collection to open its homepage, make sure that it has some items
3. Click on List all Items button
4. The result page only contains unpublished items from the collection, and if there are no unpublished items it shows no items in the result.

**Comment by cjcolvar** [comment]
On spruce, it looks like solr was out of sync with fedora so I'm reindexing everything which I think should clear it up.  I'll do the same on mallorn if the symptoms look the same.

**Comment by Karthikeya212** [comment]
Looks good on spruce
