### ISSUE TITLE
Unable to update thumbnail on items pushed to Spruce through intercom

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2882]
### Description
When a video item is pushed to Spruce through intercom from Mallorn, thumbnail is not successfully transferred, and also user cannot update the thumbnail on this item in Spruce.

eg: https://spruce.dlib.indiana.edu/media_objects/hh63sw016

**Comment by bkeese** [comment]
The thumbnail plugin for the player needs to be updated to allow the creation of new poster. 
app/assets/javascripts/media_player_wrapper/mejs4_create_thumbnail.es6, line 151:
`createThumbnailObj.baseUrl = "/master_files/"+createThumbnailObj.player.avalonWrapper.currentStreamInfo.id`

**Comment by bkeese** [comment]
A number of things have been done to address this bug. Both the ingest API and Intercom have been tweaked to allow the transfer (recreation, actually) of thumbnails and posters. Plus, the thumbnail plugin has been tweaked to allow selection of thumbnails even when item has no thumbnail to begin with. 

This is ready for final (hopefully) QA.

**Comment by Karthikeya212** [comment]
Tested and working fine
