### ISSUE TITLE
Pushing item through intercom is going to continuous loading on Edge browser

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2883]
### Description
Browser: Edge(40.15063.0.0) 
OS: Windows 10
Issue: Click on Push to Spruce button on an item in Mallorn, and click Push button in the pop-up. The button goes into continuous loading.

![image](https://user-images.githubusercontent.com/25850972/37679213-a9b2251c-2c56-11e8-805f-64395836d0b7.png)

**Comment by bkeese** [comment]
So the push never succeeds?

**Comment by Karthikeya212** [comment]
No, it just stays like that

**Comment by cjcolvar** [comment]
I'm seeing this in Edge 15 but not Edge 16 on browserstack.  I don't see any indication why it is hanging in the javascript console.  It appears that it never makes any requests either.

**Comment by Karthikeya254** [comment]
Yeah Edge 16 is fine, checked it on windows10

**Comment by cjcolvar** [comment]
@davidschober @joncameron is this worth working on given that it works in Edge 16 (latest stable)?

**Comment by joncameron** [comment]
@davidschober @cjcolvar I'm going to say no and make this a 'wontfix' issue.

**Comment by cjcolvar** [comment]
Current version plus two back for edge is 16-18.  I'm closing this issue and removing it from the known issues since it only affects edge 15 and below.
