### ISSUE TITLE
Embed URL is missing for video items pushed through intercom

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2884]
### Description
The video items that are pushed from Mallorn to Spruce doesn't have embed urls, whereas audio files have them and can be embedded. If a multi-section item is pushed then only the video sections are missing embed urls.

https://spruce.dlib.indiana.edu/media_objects/8g84mm40d
![image](https://user-images.githubusercontent.com/25850972/37679716-26261454-2c58-11e8-8e58-efd44921da29.png)

**Comment by cjcolvar** [comment]
Looks like the master file that got pushed is missing `width`, `height`, `display_aspect_ratio`, and `original_frame_size`.

**Comment by bkeese** [comment]
This should be fixed by PR #2885

**Comment by Karthikeya212** [comment]
Tested
