### ISSUE TITLE
Trim Whitespace In MODS values

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2888]
### Description
If the value for a related item url contains whitespace characters, it renders out badly. We should be trimming whitespace on these values.

### Example
'Related Item' URLs
A value like "https://purl.dlib.indiana.edu/iudl/variations/program/vad4578" that includes a LF character at the end will get rendered out as  "https://purl.dlib.indiana.edu/iudl/variations/program/vad4578%0A", which breaks the link that is intended.

### Done Looks Like
- When a MODS value contains whitespace control characters, the whitespace is trimmed so the control characters are not encoded into the value rendered out.

**Comment by cjcolvar** [comment]
@Karthikeya212 
I tested and found this working on spruce by adding a related item with a long title and long url and then checking the link on the preview page.  The url element using multiple lines appears to have been the cause of this problem in IU production and the code was updated to handle this scenario:
```
<relatedItem displayLabel="Test IIIF presentation 2 manifest from nurax showing me at the prime meridian in Greenwich, UK">
<location>
<url>
https://nurax.curationexperts.com/concern/images/mw22v549p/manifest?manifest=/concern/images/mw22v549p/manifest
</url>
</location>
</relatedItem>
```
