### ISSUE TITLE
Properly Sizing the Player From Technical Metadata

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2914]
### Description
We have technical metadata containing height, width and aspect ratio information. The question now is how to use this to properly display video in MediaElement, in terms of player bounds, letterboxing/pillarboxing, stretching based on aspect ratio for non-square pixels, etc.

### Done Looks Like
- Evaluate how to represent, in the IIIF manifest and n MediaElement, video such that it is properly displayed.

**Comment by davidschober** [comment]
this will be driven by the IIIF manifest. We need to come to a shared understanding of what the  problem is.

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#88
