### ISSUE TITLE
Pawpaw: Infinite Ingest

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2916]
### Description
I uploaded our sample ingest manifest and assets to the _Sample Videos_ dropbox on Pawpaw. But the job is not finishing, and is instead running over and over, ingesting the assets hundreds of times.

### Done Looks Like
- Some troubleshooting is done to figure out what's going on.

**Comment by cjcolvar** [comment]
A fix has been deployed to spruce.
