### ISSUE TITLE
100 item batch ingest failing

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2922]
### Description
Servers: mco-staging, pawpaw

When the user uploads a manifest file containing 100 items, it fails with a title field error and doesn't start the  ingest process. Where as the same file with less number of items ingest successfully.

**Comment by cjcolvar** [comment]
@Karthikeya212 are you able to give a link or point me to where the failing batch is?

**Comment by Karthikeya254** [comment]
@cjcolvar It fails to start the ingest process itself, this link (https://iu.app.box.com/folder/31130013694) has a zip file with manifest files and assets folder containing the items. Use onr of the 100 item manifest files to check the failure.

**Comment by cjcolvar** [comment]
@joncameron @davidschober Is this still an issue that needs investigation or can it be closed (and removed from the Known Issues)?

**Comment by joncameron** [comment]
I'll test this and close if possible. Most likely this is now resolved.

**Comment by joncameron** [comment]
Couldn't reproduce; the 100-item manifest came through without a problem. Closing and removing from Known Issues.
