### ISSUE TITLE
Avalon 7 - 0.2 Master Issue

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2936]
Further refine the IIIF Player, auto-generate IIIF manifests based on an Avalonish -work type metadata. Structural metadata will be ported over as is for use in a IIIF manifest. We will also investigate and create a MVP of a structural metadata editor for 6.5. Bonus points: Begin discussion and sketches for a branded hyrax-based Avalon solution bundle

- Structural Metadata Editor (Avalon 6.5)
    + parent of #1931 (structural metadata editor UI discussion)

- Create a work type in Hyrax for AV #1773 
    + Keep track of work in community started in #2223 
    + parent of #2941 Determine scope of initial work type metadata. It should be defined by #1808 
    + parent of #1821 (Avalon Work Type model)
    + parent of #1822 (Avalon work type Show)

- IIIF Manifest Generated from AV Work Type #2934
    + parent of #2937 (Structural Metadata Store XML)
    + parent of #2938 (structural metadata xml crosswalked to IIIF Manifest)
    + parent of #2225 Necessary Avalon work type metadata is represented in IIIF manifest  
    + Bonus! Xml file can be uploaded as part of the work. 
           * parent of #1953 (uploading a structure file in invalid format returns an error)

- The Media Player Consumes the Generated IIIF Manifest #2865
    + parent of #2914 (properly sizing player from tech md)
    + parent of #2203 (solution bundle player can stream from media server, ingestion out of scope)
    + parent of #1846 (investigate display of structural metadata)
    + parent of #2204 (solution bundle player can be navigated via structural metadata)
   
- OUT OF SCOPE : Investigate Management Needs for Derivative Generation (Matterhorn Replacement) #2935
    + parent of #1826 (create hyrdra derivatives plugin)
    + parent of #2935 (matterhorn investigation)

- Metadata
    + parent of #1808 (refine metadata needs for Avalon work)

- BONUS: Look and Feel
    ~+ parent of #1811 (decide how playlists are are dealt with in hyrax)~
    + parent of #1809 (discuss use of admin sets/collections)

**Comment by davidschober** [comment]
Issue migrated to samvera-labs/avalon-bundle#85
