### ISSUE TITLE
Write Spec Doc For Time Based Media Work Type

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2941]
### Description
Using the metadata requirements from #1808 produce a spec doc for a Hyrax work type.  Doc should meet the mvp need.  This is so we have a firm spec for the model. This should be in the Avalon Bundle wiki.

### As A

As a PO/ Tester I want to know what version of the metadata spec we are pinned to so we can check diffs/ make priorities, etc. 

Also a developer I want to be able to have issues that say "update model to metadata model version "cute mouse"  the Diffs are no drop down for notes, etc"

### Done Looks Like

- [x] Decide on how  to Version Doc in Google Spreadsheet @jenyoung to train 
- [x] Meet to discuss doc
- [x] Update spreadsheet to reflect the code
- [x] Spec doc written/ Version pinned for .2
- [x] Published in [avalon-bundle wiki](https://github.com/samvera-labs/avalon-bundle/wiki)

### Avalon MODS to RDF Spreadsheet
https://docs.google.com/spreadsheets/d/1TY5G_9Jl6QI-Aq6c3cCs54BH5E5sRu3Omhnz6GMub0U/edit#gid=0

### Relevant Code
https://github.com/samvera-labs/avalon-bundle/blob/master/app/models/audiovisual_work.rb

### Discussion in PR
https://github.com/samvera-labs/avalon-bundle/pull/115

**Comment by jenyoung** [comment]
workflow:

- Make changes to document in Google Docs
- When a version is cut, name a version in Google Docs
- Save an xlsx version _from_ google docs with same name as named version
- upload xlsx to wiki and link with reference to version of avalon bundle we are mapping to
- Developers can get diffs by going to Google Docs, showing versions, showing named versions and clicking on versions to compare.

**Comment by jenyoung** [comment]
Please let me know of any changes, etc.

https://github.com/samvera-labs/avalon-bundle/wiki/Avalon-Audiovisual-Work-Model

**Comment by mcwhitaker** [comment]
@joncameron I think @jlhardes was thinking of that more like a provenance field.

**Comment by jenyoung** [comment]
Is this field meant to be displayed as part of the descriptive metadata?

**Comment by jenyoung** [comment]
I added `ebucore:comment` under the  Technical metadata for now. We do want this to display with the descriptive metadata. From an email in March

> We don’t really want them to be editable or part of the MODS descriptive metadata so we’re thinking of bringing them in as more of a technical-style metadata property on either the MasterFile or the MediaObject, depending on where the comment applies. Wherever the comments are stored, they would show along with the item-level MODS descriptive metadata for the end user but they would not be available for editing (similar to the tech md properties we’re storing now)
