### ISSUE TITLE
MasterFile management moving should verify file before it deletes

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2946]
### Description
NU ultimately implemented the primary fix that Carrick suggested, without the additional work of creating an ideal robust handling of potential failures in the S3 move operation defined in the function in question. We should add Carrick's fix put in place for NU into core as well.

### Done Looks Like
- Cherry-pick https://github.com/nulib/avalon/pull/381 into core

From `master_files_management_jobs.rb`

```
  def s3_to_s3(source, dest)
      source_object = FileLocator::S3File.new(source.source).object
      dest_object = FileLocator::S3File.new(dest.source).object
      if dest_object.copy_from(source_object, multipart_copy: source_object.size > 15.megabytes)
        source_object.delete
      end
    end
```

We should probably change it to `source_object.delete if FileLocator.new(dest_object).exists?` and have some kind error handling (requeue it if fails and if it fails multiple times email someone).

On NU we've seen the s3_to_s3 copy fail silently on large files at least once.  We probably need to change the other move jobs (s3 to file, file to file) as well.

**Comment by carrickr** [comment]
For refinement I think we need @joncameron and @davidschober to decide a strategy for notifying of a copy failure

my proposal is to retry three times with a delay between each and then email the admin of the avalon instance about the issue

the second thing we need to handle is that currently the code works as follows when doing a move strategy

1. update the master file location in Fedora (so `a_master_file.file_location = new_location`)
1. kick off an active job to do the actual move of the file to the new location and delete from the old location

So this causes two problems, the first is that we have data loss right now, file fails to copy to new location and the user supplied one is deleted.  The second is that the file location points to a place there never was a file.  I think we definitely want to avoid the delete.  As for the file location, we could add in another step in the recovery process to change the file location back to the user supplied location at the expense of this ticket getting bigger in point size.  Or we could document it as a known issue of "If you get emails about file copies failing, you need to fix the problem and then copy all the files that failed so they're where Avalon thinks they should be (or stick the files somewhere else and update the master file pointers)."  PO call there.

**Comment by davidschober** [comment]
I think this proposal makes sense.

**Comment by joncameron** [comment]
@phuongdh Still valid?

**Comment by joncameron** [comment]
Cherry-pick https://github.com/nulib/avalon/pull/381, which puts in the if statement Carrick proposes in the description of this ticket. It's not the full solution, but solves the issue without being the true ideal.
