### ISSUE TITLE
meet with Archivematica to define spec

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2948]
child of #2792
### Description
We'll be meeting with another Archivematica/Avalon user, and thinking about implementing a bag export during the Avalon ingest process.

## Done looks like 

- spec is written for bag 
- discussion how to serialize.

**Comment by davidschober** [comment]
@joncameron @mcwhitaker we met with Archivematica, but we've since pivoted a bit away from this. Should we move this out of the sprint at the end of the cycle?

**Comment by davidschober** [comment]
K. Let's pull it out of the current sprint tomorrow and put it back to ready.

**Comment by davidschober** [comment]
@mcwhitaker @joncameron should we call this "in progress" or done given the current back and forth with Archivematica? I'd like to as we will generate more work and issues after the latest round of discussions

**Comment by mcwhitaker** [comment]
@davidschober I think we can abandon this one as we don't think we will be writing any bag at this point.
