### ISSUE TITLE
Avalon Could Do Better With Commas and Such

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2953]
So lets say I upload a file called:

`I make poor file,name choices.mp4`

Avalon is cool with that, but when it stores the file name in solr it will be `I make poor file%2Cname choices.mp4` but still has the comma in on disk (or for a real life example: `file_location_ssi"=>"s3://avalon-masterfiles-cfx3wj9/dropbox/Chicago_Chamber_Musicians_Archive%2C_1989-2010/avr/01_Dvorak;_Three_Slavonic_Dances_Gottlieb_Hall.wav`)

So this sets up the following issue of:

`FileLocator.new(master_file.file_location).exists?` is false
`FileLocator.new(master_file.file_location.gsub('%2C', ',').exists?` is true

We should be more proactive in stripping characters so the location you get from solr works without needing to handle those charaters

**Comment by joncameron** [comment]
I don't like character stripping, but I agree with past Carrick—things shouldn't break if a non-alphanumeric character is present in the filename. We'll need to see how current ActiveFedora/Hyrax is doing this; it may not be an issue there.
