### ISSUE TITLE
Demo ingest package is not available in Confluence

### ISSUE THREAD

**Issue by ross-spencer** [avalonmediasystem/avalon#2958]
The demo of the 'Batch ingest format' is no longer available on confluence here: http://www.avalonmediasystem.org/downloads/DemoFixturesBatch.tar.gz

Linked to from this page here: https://wiki.dlib.indiana.edu/display/VarVideo/Batch+Ingest+Package+Format

**Comment by joncameron** [comment]
@ross-spencer I have a link to the package here so you can download it before this is resolved: https://northwestern.box.com/s/tmbtgyjvexpgogwj0vrfgoisyooyg3en.

**Comment by joncameron** [comment]
The link has been fixed and is now available as it should be from the links on the Avalon website and wiki.
