### ISSUE TITLE
Thumbnail button not working in Safari

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2959]
JS error in console:

TypeError: undefined is not an object (evaluating 'this.player.avalonWrapper.currentStreamInfo')
updateTrackScrubberProgressBar — mejs4_player-3087ac774a8e74d64246d432025ce79e9c6914d84e12f6726297a7c3ff97adc4.js:6:11494
handleTimeUpdate — mejs4_player-3087ac774a8e74d64246d432025ce79e9c6914d84e12f6726297a7c3ff97adc4.js:6:8671
(anonymous function) — mejs4_player-3087ac774a8e74d64246d432025ce79e9c6914d84e12f6726297a7c3ff97adc4.js:6:8531
dispatchEvent — mejs4_player-3087ac774a8e74d64246d432025ce79e9c6914d84e12f6726297a7c3ff97adc4.js:1:20168
(anonymous function) — mejs4_player-3087ac774a8e74d64246d432025ce79e9c6914d84e12f6726297a7c3ff97adc4.js:4:28933
9e — application-7e1d87d91c9abc9ccf030bfec081106d060b5fdc61021e91930b44ec7ab1a791.js:36:5692

**Comment by cjcolvar** [comment]
This is working on mallorn.
