### ISSUE TITLE
Requesting Non-existing Object Returns 500

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2962]
### Description
The request for an id of an object which doesn't exist or no longer exists (via GET or HEAD reuqests) returns a 500 instead of a 404.

### Done Looks Like
* Change rewrite_v4_ids method so that responses are 404 rather than 500.

https://app.honeybadger.io/projects/54117/faults/36121837

**Comment by cjcolvar** [comment]
Can we also broaden the guard for this method so that it also applies to HEAD requests?  I'm seeing a few errors in honeybadger because of this.

https://app.honeybadger.io/projects/54117/faults/37684203

**Comment by SumithBaddam** [comment]
I am unable to reproduce this. Tested it on spruce with random media object ID. It is throwing a 404 error. 
https://spruce.dlib.indiana.edu/media_objects/f7623c8sdasdas

**Comment by phuongdh** [comment]
I also see 404 for both GET and HEAD.
