### ISSUE TITLE
Should not always require aws/rails/mailer when server is EC2

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2973]
This initializer requires aws mailer whenever it detects the server is an EC2 instance
https://github.com/avalonmediasystem/avalon/blob/master/config/initializers/mailer.rb

However when running Avalon on a cloud service somewhere else that might use EC2 (Dockerhub) it still triggers and fails.

**Comment by mbklein** [comment]
The easiest option would be to add a `:mailer` setting to the `railsconfig` chain, and require `aws-sdk-rails` if the setting is `:aws_sdk`.

**Comment by phuongdh** [comment]
Verified on a plain EC2 instance
