### ISSUE TITLE
Player loses fullscreen when advancing to another section or item

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2979]
Steps:

In item view with multi sections:
- Play first section
- Make it fullscreen
- Wait till it reaches the 2nd section

In playlist view with multi items:
- Play first item
- Make it fullscreen
- Wait till it reaches another item

Observed:
Player is taken out of fullscreen and advances to next section/item

Expected:
Player stays in fullscreen while advancing

Environment:
OSX, Chrome

**Comment by Dananji** [comment]
NOTE: Could not figure out a way to enforce full-screen on the new section conditionally based on the previous player settings. I managed to preserve the `isFullScreen` flag in the previous section and carry that onto the next section. Maybe this was a wrong approach.
