### ISSUE TITLE
Finish setting up new Bamboo on sulfur

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2980]
child of https://github.com/samvera-labs/avalon-bundle/issues/179

- [x] Change Docker config location
- [x] Move domain/certs
- [ ] Move users/roles 
- [x] Check Bamboo configs

**Comment by davidschober** [comment]
child of https://github.com/samvera-labs/avalon-bundle/issues/179

**Comment by phuongdh** [comment]
Users will be added when the needs come up because everyone has to enter their own passwords
