### ISSUE TITLE
Use Collection Information in a Suitable Area for Analytics

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2988]
### Description
There is not currently a way to easily compile collection-specific statistics through tools such as Google Analytics. One proposal is to add this identifying information to something that is easily able to be filtered in an analytics suite; for example, printing the collection number of the current item in the page title.

### Done Looks Like
- A way to add identifying information which can be searching and filtered in an analytics suite is discussed and agreed upon
- Code changes are made to implement the above

### Notes
#4408 is the following ticket. It looks like we'll only need to send a small amount of values through Tag Manager and there are existing libraries to make this feasible.

**Comment by davidschober** [comment]
@joncameron I think the most straight forward way to handle this is to add structured data containing that information (and other critical information) to each page. This is a current google best practice for SEO as well as complex analytics using tag manager https://developers.google.com/search/docs/guides/intro-structured-data

Here is an example of NU's structured data on dc.

I'd like to refine this and possibly get it done for AV 7. It seems low hanging.

**Comment by joncameron** [comment]
@davidschober That sounds great—I'm 100% on board with adding this in for 7.

**Comment by davidschober** [comment]
This could be a two stepper. 1) add a data layer 2) add support for google tag manager. That's a little bit of a shift. Our current GA support is very basic. A shift to GTM would require administrators to create a GTM account and set it up.

**Comment by davidschober** [comment]
https://github.com/rcs/google-tag-manager-rails

Maybe we make it configurable, but always drop the dataLayer. At any rate, let's point it and get it moving. Do you want to identify what metadata makes sense? @joncameron

**Comment by joncameron** [comment]
This is possibly superseded by another issue (put reference here). We could put a slugified collection name in the title. 

David notes that this is redundant; we can close in favor of the other, moving the datalayer example over if needed. David's research indicates that Matomo/GA use the same syntax for this information within the page.

**Comment by mcwhitaker** [comment]
Issue that supersedes this is #3616
