### ISSUE TITLE
Player API Not Working in Safari

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2993]
### Description
Commands to the player given with the Player API on Safari is not functional. The console displays an error: 
```
TypeError: undefined is not an object (evaluating 'currentPlayer.media')
```

### Environment 
Safari 11.1.2 on macOS 10.13.6

### Test page
https://www.music.indiana.edu/iumusiclive/debug.shtml

### Expected behavior
Firing an API call will cause the desired behavior in the player, such as starting playback on the example site above.

**Comment by cjcolvar** [comment]
I tested the fix for this on spruce with the embed api on the wiki and it worked.
