### ISSUE TITLE
Playlist manual sorting problem

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#2998]
### Description

The handles used to move playlist items up and down when manually sorting are not working.

Server: mallorn and pawpaw
Browser: Google Chrome Version 67.0.3396.99 (Official Build) (64-bit)
Browser: Firefox Quantum - 61.0.1 (64-bit)
Operating System: Windows 10 Enterprise

![image](https://user-images.githubusercontent.com/16720883/42970450-4eb47e46-8b77-11e8-9022-a743dc708993.png)

**Comment by cjcolvar** [comment]
FWIW I'm not able to reproduce this problem on either server with Chrome Version 67.0.3396.99 (Official Build) (64-bit) on MacOS 10.13.6.

**Comment by joncameron** [comment]
@mschnaars tested this today and could not reproduce, although he mentioned that he thought he encountered this issue a few weeks back. I'm going to close for now and we can reopen if it pops back up.

**Comment by mcwhitaker** [comment]
For the records, this still happens to me. So it is not the case that it cannot be reproduced at all, it just cannot be reproduced by someone else. I am not against closing, I just want the records to be complete.
