### ISSUE TITLE
Clean up old batch ingest code

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3001]
From @cwant https://samvera.slack.com/archives/C1C3C4F5L/p1531839754000267

* Does the model IngestBatch matter any more? (and if not, why is it still in the code repository?)
* Why do the two new models BatchEntries an BatchRegistries have plural names?
* Now that a manifest is deleted on ingest, does this code have value anymore https://github.com/avalonmediasystem/avalon/blob/master/lib/avalon/batch/file_manifest.rb#L24-L30

There might be other stuff as well

**Comment by joncameron** [comment]
Unlikely to happen given our focus on Hyrax batch ingest.
