### ISSUE TITLE
Script for backfilling waveform data

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3008]
### Description

After #3005 all new master files will get waveform data generated.  We'll want a way to generate waveform data for all preexisting master files.  This could take the form of a rake task or ruby script.

### Tasks
- [ ] Write script or rake task that iterates over all master files without waveform data and enqueues job (from #3005).
- [ ] Add option for throttling to avoid Fedora issues
- [ ] Write tests
- [ ] Write documentation

child of https://github.com/samvera-labs/avalon-bundle/issues/231

**Comment by davidschober** [comment]
@cjcolvar you already started working on this correct?

**Comment by yingfeng-iu** [comment]
I did not add throttle at this point as I feel it may not be necessary. Once we can test this in staging we can decide if it's needed.

**Comment by cjcolvar** [comment]
Closed by #3166.
