### ISSUE TITLE
(SME) - Define rules for UI nesting behavior

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3017]
### Description
Need clarification on the nesting rules for the structual metadata editor in UI.  

* What happens when adding a new heading, child of rules, etc.  Legal entry points?
* What happens when adding a new time span, child of rules, etc.  Legal entry points?
* When editing, choosing a new parent/child... what's legal or allowed?
* Should a group of time spans all be moved if the parent header is moved?
* When adding a new time span, how does auto-sort by time work?  
* Validation on front-end, what exactly does it validate?   Overlapping allowed or no?
* How does the current advanced XML editor come into play here?   Still needed?

### Done Looks Like
- Rules document generated and stored/saved at: https://github.com/avalonmediasystem/structured-metadata-editor-sandbox

**Comment by davidschober** [comment]
see #3022
