### ISSUE TITLE
Interaction and Behavior Document for SME

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3021]
### Description
Creating a document that describes the interaction between the user and the visual structural editor.

### Done Looks Like
A shared document in Box is created:
- Each desired interaction with the editor defined (zooming, navigation, setting segments, etc.)
- Visual information like wireframes and mockups are stored within the document or at the same directory level within Box

**Comment by joncameron** [comment]
Decisions document: https://iu.app.box.com/notes/311970117366
Box folder for design (SME): https://iu.app.box.com/folder/46591982960

**Comment by davidschober** [comment]
I added the images from Phoung. Closing
