### ISSUE TITLE
Document interaction decisions for Structural Metadata Editor

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3022]
## Description

After going back and forth on design, we need to lock down the interaction decisions.

Decisions:

- a timespan does not allow overlap
- an timepan can not be out of order
- an timespan can not be demoted from a parent unless it is the last item in the relationship (last child), as it would create an out of order item. 
- Timespans can only be moved ONE parent- level up or down.
- Use an arrow and handle click.
- Only first and last time-spans can be moved. Middle Children are stuck
- Headings are ordered by the children they have
- If when creating a timespan, you butt against the start or end of another timespan, you have to change the other timepan first. 
- Labels can be edited at will

## Done looks like

 - issue  is updated with the current decisions 

child of #177

**Comment by adamjarling** [comment]
Moving timespans, 
* They can only be moved ONE level up or down.
* Use an arrow and handle click.

**Comment by davidschober** [comment]
@phuongdh can you attach your drag and drop mockup?

**Comment by phuongdh** [comment]
Only shows user the valid places they can drop an element to.

![image](https://user-images.githubusercontent.com/1304657/43791464-c1000a26-9a43-11e8-8b22-79ff9da3160a.png)
-----------------
![image](https://user-images.githubusercontent.com/1304657/43791545-fd935ff6-9a43-11e8-8165-4e4bafee089e.png)
-----------------
![image](https://user-images.githubusercontent.com/1304657/43791501-d86664d0-9a43-11e8-9969-19cf6d95b57a.png)

**Comment by davidschober** [comment]
@adamjarling what do you think about the above mockup?

**Comment by joncameron** [comment]
Decisions in the body of the issue; closing.

**Comment by joncameron** [comment]
https://northwestern.box.com/s/h0hehpbsjq634ke9tju3hui634ijxf3y
