### ISSUE TITLE
pawpaw needs a captcha

### ISSUE THREAD

**Issue by jwd** [avalonmediasystem/avalon#3034]
### Description
The Contact Us form on pawpaw does not use a captcha, and as a result, multiple spam messages per day are coming through. Need to add reCAPTCHA, similar to IU production instances, in order to stop this spam.

### Done Looks Like
- reCAPTCHA added to the Contact Us form in Pawpaw

**Comment by bkeese** [comment]
We will need a new key for the recaptcha api. Or could we just use the same one we use for MCO? @jwd?

**Comment by cjcolvar** [comment]
This should be setup on pawpaw after we release 6.4.4 and add the recaptcha key.

**Comment by jwd** [comment]
@bkeese Sorry, for some reason I missed the notification on this. Yes, please use the same one we're using on MCO, which is registered for use with any site under dlib.indiana.edu.

**Comment by cjcolvar** [comment]
@jwd captcha is now in place.  Can you verify that the test comment I submitted came through?

**Comment by joncameron** [comment]
I confirmed that that the captcha on Pawpaw is working.  Hurrah!
