### ISSUE TITLE
Document working_file_path

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3037]
### Description
Document working_file_path and everything around it. 

### Done Looks Like
- Documentation added to the Avalon wiki on working file path

#### Working File Path PR
https://github.com/avalonmediasystem/avalon/pull/3051

**Comment by cjcolvar** [comment]
@joncameron will you please look over this and make sure that it makes sense?
https://wiki.dlib.indiana.edu/display/VarVideo/Working+File+Path
I linked to it from the "Configuring Avalon" section on this page:
https://wiki.dlib.indiana.edu/display/VarVideo/For+System+Administrators
Maybe there is a better place to link it or more places that should link to it?

**Comment by joncameron** [comment]
![giphy](https://user-images.githubusercontent.com/1406618/50013696-e314d680-ff8f-11e8-98c3-a598c6a9a6fc.gif)

**Comment by joncameron** [comment]
Made minor edits and moved to the _For System Administrators_ section.
