### ISSUE TITLE
Adding a manager as an editor to a collection grants manager-level access

### ISSUE THREAD

**Issue by mschnaars** [avalonmediasystem/avalon#3041]
### Description

When an Avalon user who is a member of the manager group is added as an editor to a collection, they are granted manager level access instead. This behavior has only been identified when attempting to add as an editor; adding as a depositor works as expected.

### Environment
Spruce, Avalon 6.4.3, Chrome

### Expected Behavior

Adding a manager as an editor to a collection grants them editor-level access.

### Screenshots

Adding a manager as an editor
![bug1](https://user-images.githubusercontent.com/25825877/44413266-f7444c00-a538-11e8-887b-511f61677f3b.png)

Defaults to manager-level access
![bug2](https://user-images.githubusercontent.com/25825877/44413272-fa3f3c80-a538-11e8-86e7-9553e47bee2b.png)

**Comment by cjcolvar** [comment]
This is a known issue when the user belongs to the `manager` group.  If the user is not in the `manager` group then they should be added as an editor.  This is inherent in the design so I move to close as won't fix so long as it is verified that non-`manager` users are added as editors.

**Comment by mschnaars** [comment]
@cjcolvar Noted. I saw this exception get mentioned later in the test script; I'll update the script so future testers don't get waylaid and keep writing up the same issue.
