### ISSUE TITLE
Attempting to View a Playlist Throws an Error

### ISSUE THREAD

**Issue by mschnaars** [avalonmediasystem/avalon#3042]
### Description
Trying to view a playlist redirects to an error screen with message:  
`ActionView::MissingTemplate in Playlists#show`

### Environment
Spruce, Avalon 6.4.3, Chrome

### Screenshots
The error screen:
![playlist_error](https://user-images.githubusercontent.com/25825877/44476960-583a5580-a607-11e8-9fae-e48ed66c656a.png)

**Comment by cjcolvar** [comment]
I thought I fixed that one.  Oh, it looks like the build failed and it didn't deploy to spruce.  I'm rerunning the build and will let you know when it gets deployed.  The redeploy shouldn't affect you much other than right after it happens the first request will take longer to load.

**Comment by cjcolvar** [comment]
Ok deployed now.  So this should be fixed and working.

**Comment by joncameron** [comment]
@mschnaars Can you verify that it's working and then close this issue?

**Comment by mschnaars** [comment]
Verified, don't encounter any issues loading playlists on Spruce.
