### ISSUE TITLE
Clicking "Select All" Throws an Error

### ISSUE THREAD

**Issue by mschnaars** [avalonmediasystem/avalon#3043]
### Description
When viewing multiple items, clicking the "Select All" checkbox checks one item at a time, and throws an error in a pop-up for every other item.

### Environment
Spruce, Avalon 6.4.3, Chrome

### Screenshots
The error message:
![selectall_error](https://user-images.githubusercontent.com/25825877/44478116-ad2b9b00-a60a-11e8-8ac4-000340ccabf5.png)

**Comment by bkeese** [comment]
This is a problem caused by sqlite's lack of capacity for multiple synchronous updates. Errors are caused by locked database. This is only a problem on spruce because it is configured to use sqlite.

**Comment by bkeese** [comment]
Addressing #3138 will fix this bug.
