### ISSUE TITLE
"View Raw Metadata" Button Throws a Missing Template Error

### ISSUE THREAD

**Issue by mschnaars** [avalonmediasystem/avalon#3048]
### Description
Clicking the "View Raw Metadata" button on any item page throws an error for a missing template

### Environment
Spruce, Avalon 6.4.3, Chrome

### Screenshots
![raw_metadata_error](https://user-images.githubusercontent.com/25825877/44550242-9c098980-a6f1-11e8-9e6b-a81f6255a7a5.png)

**Comment by joncameron** [comment]
Still present; probably a Spruce data issue?

**Comment by cjcolvar** [comment]
Actually I think this might be a rails 5.1+ issue and needs a return statement to avoid continuing process the action.

**Comment by joncameron** [comment]
No longer relevant or reproducible.
