### ISSUE TITLE
Selecting "Update access control" as a bulk action causes an error

### ISSUE THREAD

**Issue by mschnaars** [avalonmediasystem/avalon#3058]
### Description

After selecting multiple items, selecting the "Update access control" button on the "Manage Selected Content" page opens a modal window displaying a MissingTranslationData error.

### Environment

Spruce, Avalon 6.4.3, Chrome

### Screenshots

The modal window displaying the error:
![update_access_control_error](https://user-images.githubusercontent.com/25825877/44867283-6ca8ce80-ac55-11e8-835f-b8de352d4e56.png)

**Comment by joncameron** [comment]
Couldn't reproduce; most likely a Spruce issue that was resolved.
