### ISSUE TITLE
Share Button Disappears When Browser Uses Adblock Plus

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3062]
### Description
When a browser is using Adblock Plus with default lists and filtering, Avalon's share button does not appear. This is ultimately due to Fanboy's Social Blocking List.

More information is available at easylist.to about these lists. Here is Fanboy's Social List itself: https://easylist.to/easylist/fanboy-social.txt. 

### Done Looks Like
- Avalon's Share button is named in a way that it is not blocked by name filtering from Fanboy's Social List

**Comment by Dananji** [comment]
@joncameron I can't seem to reproduce this in Google Chrome. Any help on this is appreciated. Thanks!

**Comment by joncameron** [comment]
@Dananji If you can't reproduce I'm assuming that this isn't an issue anymore. Closing!
