### ISSUE TITLE
Captions not displayed for audio only content

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3076]
There is no space nor controls presented to allow for the rendering of captions within our audio player.  This could be an accessibility issue.

**Comment by davidschober** [comment]
@joncameron to verify whether this is an accessibility issue.

**Comment by joncameron** [comment]
Closing this older issue. I don't think this is an accessibility issue. The broader issue is having text materials along with audio—I think this would take more a form along the lines of the OHMS embedded viewer, where a player + text elements share a div.
