### ISSUE TITLE
Lil scrub unreachable by keyboard navigation

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3079]
What value is there to navigating to lil scrub or the main scrubber since right/left arrow keys are already bound to seek forward/back 10 sec?

**Comment by davidschober** [comment]
@joncameron I'm not sure this one makes much sense. Can you confirm and close?

**Comment by joncameron** [comment]
I'm going to close this. An accessibility review might bring this up again. I could see different values for forward/back depending on whether the scrubber or lil scrub is used, but I think evaluating the sequence of player elements with keyboard navigation in a wider sense would be the best to start.
