### ISSUE TITLE
Move Pawpaw to AWS

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3088]
### Description
Pawpaw can be deployed in AWS using out new turnkey solution, eating our own dogfood, etc.

### Done Look Like
- We deploy an instance to AWS
- Migrate data from current Pawpaw to the new instance
- Decide on domain name
- Get a new domain if desired (do we let AWS manage the domain or not?) (spoiler: yes)
- Update contact form with new Captcha or redirect contact form page to the contact page on the website

### Notes
- Pawpaw will now be demo.avalonmediasystem.org
- All DNS for avalonmediasystem.org needs to move to Route 53.
   - JD will work with Phuong on moving DNS

Check notes in #3036

child of https://github.com/avalonmediasystem/avalon/issues/3230

**Comment by davidschober** [comment]
This issue was made redundant.
