### ISSUE TITLE
Load time of the playlist that has a 100 section item

### ISSUE THREAD

**Issue by srsridh** [avalonmediasystem/avalon#3092]
### Performance Testing ###

**Steps**

1. Add a   100-section item to a playlist.
2. Go to   the playlist tab and click on the playlist that contains 100-section item.
3. Note   down the time taken from the point of clicking on playlist till the playlist   page loads completely with the player on left and all the items displayed on   right.

The benchmark time recorded is 14.2s and I observed 29.23s

### Done Looks Like
- These steps are taken again so they can be recorded by Skylight
- Investigate how to improve performance issues related to this ticket
- Create new issues as needed

**Comment by cjcolvar** [comment]
Related to #2784.
