### ISSUE TITLE
Batch ingest 100 items and 100 section item

### ISSUE THREAD

**Issue by srsridh** [avalonmediasystem/avalon#3095]
### Performance Testing ###

Batch ingest of 100 section item - Benchmark time ( 1hr 50 mins) , observed time (>2hr 20mins)
Batch ingest of 100 items - Benchmark time ( 2hr 40 mins) , observed time (>3hr 30mins)

### Done Looks Like
- These steps are taken again so they can be recorded by Skylight
- Investigate how to improve performance issues related to this ticket
- Create new issues as needed

**Comment by davidschober** [comment]
@joncameron can this be closed? I'm not sure I'm following these skylight bugs from last november?

**Comment by joncameron** [comment]
We haven't used Skylight in a while and this issue is stale—if it's valuable we can run through this again if needed and take action on the results.
