### ISSUE TITLE
Review open PRs with POs Pronto!

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3099]
## Description

Review open PRs with POs and take action on them 

Parent of #3074
Parent of #3075
Parent of #3061

**Comment by cjcolvar** [comment]
@joncameron @mcwhitaker #3104 was merged but needs manual QA testing now

**Comment by mcwhitaker** [comment]
@cjcolvar Thank you. 
@joncameron - Krishna is out most of the week next week, but could potentially look into this the week after. If you prefer to test it yourself before then, that is fine. Otherwise let me know and I can sit with Krishna to talk about testing.

**Comment by cjcolvar** [comment]
2 PRs have been merged and 1 has been responded to so I wonder if we can close this issue?

**Comment by joncameron** [comment]
Closing. I'll review #3104 this week.
