### ISSUE TITLE
Endpoint for Structural Metadata JSON

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3110]
### Description
Creating a CRUD endpoint that delivers and returns structural metadata XML from masterfiles as JSON. This is for Avalon 6.

### Notes
This is for use with the structural metadata editor.
The shape of the JSON is defined in the structural metadata editor code.

child of https://github.com/samvera-labs/avalon-bundle/issues/231

**Comment by bkeese** [comment]
[
  {
    "type": "div",
    "label":
      "Faculty/Student Recital",
    "items": [
      {
        "type": "span",
        "label": "[ambience]",
        "begin": "00:00:10.00",
        "end": "00:00:23.60"
      },
      {
        "type": "div",
        "label": "Richard Wagner, Der fliegende Holl&#xE4;nder (excerpts)",
        "items": [
          {
            "type": "div",
            "label": "Sub-heading Label",
            "items": [
              {
                "type": "span",
                "label": "&quot;Die Frist ist um&quot;",
                "begin": "00:03:02.11",
                "end": "00:13:48.00"
              }
            ]
          }
        ]
      },
      {
        "type": "div",
        "label": "Giuseppe Verdi",
        "items": [
          {
            "type": "span",
            "label": "I vespri siciliani: &quot;Merc&#xE8;, dilette amiche&quot;",
            "begin": "00:33:10.94",
            "end": "00:37:31.09"
          }
        ]
      },
      {
        "type": "div",
        "label": "Richard Strauss, Ariadne auf Naxos (excerpts)",
        "items": [
          {
            "type": "span",
            "label": "&quot;Lieben, Hassen, Hoffen, Zagen&quot;",
            "begin": "00:37:31.09",
            "end": "00:39:35.59"
          },
          {
            "type": "span",
            "label": "&quot;Es gibt ein Reich&quot;",
            "begin": "00:39:35.59",
            "end": "00:46:40.59"
          }
        ]
      },
      {
        "type": "span",
        "label": "Gaetano Donizetti, Lucia di Lammermoor: &quot;Tombe degli avi miei&quot;",
        "begin": "00:46:40.59",
        "end": "00:52:37.25"
      }
    ]
  }
]
