### ISSUE TITLE
Missing translation on bulk update access controls

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3123]
```
<span class="translation_missing" title="translation missing: en.blacklight.update_access_control.confirm">Confirm</span>
```
Or this will cause a 500 if you have this set (usually only in test/development modes):
```
config.action_view.raise_on_missing_translations = true
```

**Comment by phuongdh** [comment]
I couldn't find any usage of `update_access_control.confirm` in the code and no `translation_missing` in the rendered UI. Abandoning due to being irreplicable
