### ISSUE TITLE
wire up json endpoint to SME

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3133]
## Description

The SME should be able to consume and post to the JSON data. 

## Done looks like 
- JSON object for structural metaedata editor is wired for consumption
- Post updated structure to endpoint works

child of https://github.com/samvera-labs/avalon-bundle/issues/231

**Comment by bkeese** [comment]
Endpoints are:
Get:  https://host/master_files/{id}/structure.json
Post: https://host/master_files/{id}/structure.json (post param 'json' with json data)
