### ISSUE TITLE
Change database on spruce to mysql or postgres

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#3138]
Spruce is currently configured to use sqlite database. This causes database locking issues when multiple updates are issued simultaneously (or nearly simultaneously). Moving to mysql or postgres will fix these issues.

**Comment by phuongdh** [comment]
We should consider moving spruce Avalon to fluorine and give it a proper domain name, like: dev6.avalonmediasystem.org or dev6.avalon.dlib.indiana.edu

**Comment by joncameron** [comment]
Closing in favor of #1376
