### ISSUE TITLE
investigate IIIF auth and IU centric implementation

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3147]
## Description 
Gain an understanding of the IIIF spec and how it can be implemented with wowza in a IU-ish environment. 

## Done looks like 
- spike on IIIF
- write up implementation spec focused on IU
- report out to team (share knowledge)
- write issues

child of https://github.com/samvera-labs/avalon-bundle/issues/252

**Comment by cjcolvar** [comment]
Implementation draft: https://gist.github.com/cjcolvar/f9d9fc80e0934048d29cbb675d43475d

**Comment by cjcolvar** [comment]
Once we implement something let's try testing with this:
https://digirati-co-uk.github.io/iiif-auth-client/?sources=https://iiifauth.digtest.co.uk/index.json

**Comment by cjcolvar** [comment]
I think we've done this except for the report out which we plan to do during swarm next week.
