### ISSUE TITLE
(SME) - Use front-end generated unique ids as unique identifiers for headers and timespans, instead of labels

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3153]
### Description
Currently the Structural Metadata Editor uses the `label` field as a unique identifier.  This is not a valid use case.  Need to use a front-end generated id system.

### Done Looks Like
- Each `div` and `span` item in the data structure has a unique id associated with it.
- Headers or timespans of the same label text are allowed to be created.  (Although this might get tricky when selecting a header parent from a dropdown list, when creating a new timespan).

### To Do
- [x] Add a unique id library helper to React project. (https://www.npmjs.com/package/uuid)
- [x] When the JSON data is retrieved from the server, it should run through a function which adds a unique id to each `div` and `span` object.
- [ ] Current code which uses `label` as a unique identifier, is re-factored to use the newly created object `id`.  (this could be it's own issue?)
- [x] When a new timespan or heading is created, an `id` field is added to the new object.

### Notes
- @joncameron Should heading labels be unique?
- When submitting the final SME data structure object back to server, it's ok to leave the `id` properties on each object.  Back end will just ignore them.

blocks #3154 #3155

**Comment by joncameron** [comment]
There should be the expectation that heading labels may not be unique. Something like "Side 1" may appear in multiple headings for a many-sectioned item.

**Comment by adamjarling** [comment]
@joncameron @davidschober @mcwhitaker Pulling this into the sprint.  After a discussion we had today, this needs to get into the code asap.
