### ISSUE TITLE
Review Current Structural Metadata Editor

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3157]
### Description
Defining the MVP for structural metadata editor. What does the shippable product look like?

### Done Looks Like
- POs review, document and deliver this information to stakeholders

child of https://github.com/samvera-labs/avalon-bundle/issues/231

**Comment by davidschober** [comment]
blocked by #3223

**Comment by joncameron** [comment]
I'm going to close this ticket in favor of moving #3223 into "needs review" and having POs take a look, creating new tickets from there as needed. I think that satisfies the original intention of this issue, to evaluate the current status of the tool.
