### ISSUE TITLE
Document Waveform Backfill Script

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3169]
### Description
The waveform backfill script (#3008) needs to be documented on the Avalon wiki so that implementers know that it exists and how to run it.

### Done Looks Like
- A wiki page is created in the Avalon wiki that describes the waveform backfill script and how to use it

**Comment by yingfeng-iu** [comment]
https://wiki.dlib.indiana.edu/display/VarVideo/Waveform+Backfill+Script
