### ISSUE TITLE
Adopt mbklein's Redrate for throttling ingest jobs

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3177]
### Description
Supposedly works better than current throttling mechanism we have.

### Done Looks Like
- @phuongdh will investigate and implement if everything looks good
- Retire the old rate limiting mechanism
- Write documentation

Michael Klein [1:54 PM]
AWS Elastic Transcoder has limits `CreateJob` calls to 2 per second (with some bursting possible), and will fail hard if you exceed it. And while it’s great to handle failures and put them back into the queue or whatever, it doesn’t prevent a batch job or a single MediaObject with a lot of MasterFiles from spamming the API.

Phuong Dinh [1:56 PM]
hmm did the throttling not help?

Michael Klein [1:56 PM]
Nope
So I found a Ruby method rate limiter with a nice interface, written by Shopify, which would work great on its own for a single worker instance. But we need the rate limit to work across multiple worker instances, so I replaced its internal state with state persisted in Redis and created https://github.com/nulib/redrate

Anyway, with redrate, all that’s required is https://github.com/nulib/avalon/commit/c4e258f6e9c7c137688c70591cbebd6459a20f4f

Phuong Dinh [2:00 PM]
I assume it works the same with non-AWS Avalon

Michael Klein [2:01 PM]
Yes. You can call `limit_method :method, rate: X, interval: Y` on any method in any class and it’ll automatically throttle it to `X` calls per `Y` seconds.

**Comment by joncameron** [comment]
NU stopped using redrate. Should we still try to use it? Is the current Avalon throttling strategy not working as well as it should? 

The issue IU ended up having is with overwhelming Matterhorn, which is on its way out. 

We can wait on this until it becomes an actual issue. I'll close this issue and we'll reopen a new one if and when it's needed.
