### ISSUE TITLE
IIIF Manifest - Link Back to Repository

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3191]
### Description
In a IIIF manifest we need a reference back to the repository object.

### Done Looks Like
- Attribute used to hold this information is identified
- Added to implementations(s)

**Comment by cjcolvar** [comment]
PR for support in `iiif_manifest`: https://github.com/samvera-labs/iiif_manifest/pull/31
Next need to implement this in Avalon 6.

**Comment by cjcolvar** [comment]
Avalon 6 work just needs a test written: https://github.com/avalonmediasystem/avalon/compare/develop...iiif_link_back?expand=1
