### ISSUE TITLE
Work on stories for AMI

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#3192]
- [x] Build new nginx image that supports streaming with S3
- [ ] Create standalone AMI with docker-compose
- [ ] Create CloudFormation template for said AMI with S3 buckets & Transcoder
- [ ] Do we need S3 bucket for Fedora?

**Comment by mcwhitaker** [comment]
Stories will be created as part of #3187. We will work on some of that in this sprint.

**Comment by phuongdh** [comment]
Time boxed. 

Demo (subject to change) for nginx with S3: 
- Use this stream http://ec2-34-227-176-99.compute-1.amazonaws.com:8880/hls/path/boiledwater720.mp4/index.m3u8
- In this player: http://demo.jwplayer.com/developer-tools/http-stream-tester/
