### ISSUE TITLE
Elements Not Vertically Centered in Embedded Audio Player

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3197]
### Description
Player elements are not vertically centered in the embedded audio player (see example in #3196). Since Avalon has been issuing a value of 50px, these elements should be vertically centered so that things don't look off in existing embeds.

### Done Looks Like
- Player (all elements) are vertically centered.

**Comment by cjcolvar** [comment]
@joncameron Is this still an issue?

**Comment by joncameron** [comment]
@cjcolvar Yes, examples in the wild are embeds on this page: https://journal.culanth.org/index.php/ca/article/view/ca33.1.01/43
