### ISSUE TITLE
Bump the limit for web upload and make it configurable

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3200]
### Description
Web uploads are currently capped at 250 MB. This was a decision made years ago targeting local development, and comments to indicate that ideally this would be set in a config file somewhere (and that was the initial goal).

### Done Looks Like
- Web upload file size limit is set in a configuration file
- Default upload file size limit is 2 GB

### Comments and References
```
Q: The file upload was limited to 250 MB.  What will be the expected file size capacity in production?

The file size is production will depend on your installation.  250MB is an arbitrary limit we chose for local development purposes - we intend to support very large files.
```
https://wiki.dlib.indiana.edu/display/VarVideo/FAQ+for+Avalon+website+-+DRAFT

https://github.com/avalonmediasystem/avalon/blob/82cfe0c38320f9e9dc3fe8d7a47f322da31fee0b/app/models/master_file.rb#L151-L156

**Comment by joncameron** [comment]
Merge this with #3201 and close the other story.

**Comment by joncameron** [comment]
Note: in Avalon 7, this will no longer be an issue. Hyrax includes tooling for chunked HTTP file transfers out of the box.
