### ISSUE TITLE
Become AWS Marketplace seller

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3209]
## Description

We want to create a marketplace seller account so that we turn the knobs and see what it does. 

Related to #3187

## Done looks like

- Get approval for becoming a seller (IU)
- Click the link to become one
- Turn some knobs.

**Comment by davidschober** [comment]
cc: @phuongdh

**Comment by joncameron** [comment]
Does it make sense to keep trying toward this turnkey solution, or should we wait and see if it can go under the Duraspace umbrella?  Leaning toward waiting on this discussion.

**Comment by davidschober** [comment]
closing. We decided to go another direction.
