### ISSUE TITLE
Create test cases for Timeline feature

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#3210]
### Description
Create the manual testing scripts for the new timeline feature.

### Done looks like
 Scripts are created and placed in the Quality Assurance box folder

**Comment by cjcolvar** [comment]
@mcwhitaker @joncameron Where does this issue stand?  Was it completed?  If not, who does it make sense to have pick it up?

**Comment by mcwhitaker** [comment]
I have emailed Krishna asking for the test cases. I know he has created them.
