### ISSUE TITLE
Timeliner Testing

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3216]
### Description
As Digirati nears completion of their work on the Timeliner tool, we need to make sure that the communication points and information transfer between it and Avalon work correctly.

### Done Looks Like
Interaction between Avalon and the Timeliner application is tested, primarily including:
- Avalon-generated IIIF manifests work correctly when sent to the Timeliner
- Postback for saving is working with Timeliner

**Comment by bkeese** [comment]
```
---
IU/Container/178953:
- :id: afj2476a
  :duration: 4441827
  :offset: 0
- :id: afj2476b
  :duration: 3003160
  :offset: 4441827
IU/Container/214369:
- :id: vaa0690a
  :duration: 357162
  :offset: 0
```

**Comment by cjcolvar** [comment]
This is ready for more testing on mallorn.
I successfully imported the joplin Variations timeline by changing it to "IU/Container/1" which I added to the map file on mallorn.

**Comment by bkeese** [comment]
Things I've noticed:
The options for loop and stop at end of section don't appear to be working. I wonder if this is related to our decision to unselect bubbles when playing.
