### ISSUE TITLE
Document path forward for turnkey solution

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3217]
## Description

It will take some time to get the AWS marketplace sorted out. With that in mind we should write a short  decision doc. Marketplace and setting up a simpler "one box with docker that can run on AWS " installer and script. 

This document should include:

- description of marketplace
- description of simplified setup (one box, docker, aws for transcoding, rds for db) + cloudformation
- path forward that allows for agile response to decision in marketplace (what we can do _now_ what we can wait for, what it means)

## Done  looks like

- document written
- document shared with management.

**Comment by davidschober** [comment]
## Notes





## Meeting notes


GOAL:


Small to Medium sized collection hundreds to ~25k
Minimal / no support
Few moving parts (e.g. a single ec2 with a bunch of docker containers and some services)
I click "install Avalon" and add some credentials. 




- Expertise. I've spun up some ec2 instances. Maybe I played with docker locally. I mean I know what it is
- The Marketplace solution will hopefully be able to create a set of resources
- No Elastic Beanstalk. For simplicity's sake everything should be boot on a single box. A single box with a bunch of ec2 containers
- Cloudwatch to manage all logs. And docs saying "All logs are available here"
- ElasticTranscoder
- Cloudfront or nginx streaming? cloudfront takes manually configuration but we could do a straight from s3
- Out of Scope: Failover / load balancer, we have instructions on how to do it. This will not do scaling or monitoring. We will note this. 
- Bundle in all the gems for various auth strategies. Ask for the right variables. Write docs for Setup. 
- s3 hosted static assets (e.g. logo and css) 
- AMI will pull the default docker image, but you could pass in a new docker image as a 
- IDEA! PawPaw should be this turnkey solution (eat our own dogfood). 


TODO:


- Learn about the marketplace/ setting up an ami/set of resources/ NOTE Marketplace is one option, this might not be the right solution. There are other options e.g. jungleworks, terraform? https://aws.amazon.com/marketplace/management/tour/
- Figure out how to add configurable assets. It could be told to use s3 assets and seed from it's default assets. 
- Move PawPaw to this!

**Comment by phuongdh** [comment]
https://iu.app.box.com/notes/402368185776

## Description

The goal of this project is to create an AMI (Amazon Machine Image) that contains necessary components and dependencies to run Avalon Media System in the cloud for small to medium-sized collections. The AMI will be simple enough to install and run by someone with familiarity with AWS concepts, but the installer shouldn't need to be an expert. AWS services will be used for processing-intensive or commodified parts of the stack and will require configuration by the installer (e.g. RDS, S3, Elastic Transcoder). In the future, one of the partners or a third party may setup Avalon as a AWS Marketplace solution, but a marketplace ready solution is not a requirement of success. 

## Key Assumptions

- User will have a basic understanding of AWS/ Cloud environments
- User will have a basic understanding of Docker/ containers
- Small to medium sized collections ~100-->~25k
- Straight-forward deployment with minimal / no support
- This solution will only be scalable vertically (larger EC2)
- Lean on existing CloudFormation templates or Terraform scripts
- Logs should be streamed to AWS Cloudwatch if possible
- PawPaw will be moved to this install to "eat our own dog food"

## What this System will do

- All core Avalon features
- Production-ready environment
- Stream videos securely using NGINX
- Stand up easily so users can learn the system and extend as necessary (e.g. decide on scaling strategy)
- Include all Authentication strategies (via omniauth gems) but will not be configured
- Notch8-built authentication strategy will be configured by default when available and be configurable for "superuser"

## What this system won't do

- Scale horizontally 
- High availability
- CI/CD (users can set it up themselves)
- Auto backup (DIY)
- Be launched from the Marketplace (future work)

## The Plan

- Create a Docker-based AMI with Avalon, Fedora, Solr, Nginx.
- Create Terraform script to generate AWS resources: EC2, S3 buckets, RDS databases, ElasticTranscoder pipeline.
- Host static assets in S3 (?)
- Figure out an upgrade strategy
- Test in AWS with realistic ingestion
- Stand up an instance and migrate Pawpaw there

## Future Work / Out of Scope

- Decide if we want to work with a vendor on a Marketplace version. This should not stop work on an easily installable AMI.
- Keep in mind Marketplace only supports single EC2 or CloudFormation, ie Terraform will be awkward.
