### ISSUE TITLE
Rails 5.2 Support

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3218]
### Description
Rails 6 will come out soon, at RailsConf. Versions prior to 5.2 will be deprecated and only get severe security updates.

### Done Looks Like
The version of Rails Avalon uses is upgraded to 5.2.

**Comment by cjcolvar** [comment]
Gems that need releases
- [x] ActiveFedora
- [x] SpeedyAF
- [ ] active_fedora-datastreams
- [ ] blacklight-access_controls
- [ ] hydra-head

Avalon PR: https://github.com/avalonmediasystem/avalon/pull/3219
