### ISSUE TITLE
Impose a limit on the maximum number of history and tokens in session

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3226]
### Description
Session table can overflow if a bot (or someone) opens hundreds of pages quickly. Handle this gracefully, instead of throwing 500s.

### Done looks like
- [ ] ???

**Comment by cjcolvar** [comment]
We hit this in production and the bad bot logged 12k+ exceptions over a couple days.

**Comment by joncameron** [comment]
On potential solution: put a cap on session history/tokens that is reasonable for a user but not for a bot which is creating massive amounts.

**Comment by joncameron** [comment]
We'll close this and open a new issue if it reappears. This may be resolved already.
