### ISSUE TITLE
Avalon 6.4.5 Bugfix Release

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3233]
### Description
A bugfix release is required due to some severe security issues in Rails:
- https://groups.google.com/forum/#!topic/rubyonrails-security/GN7w9fFAQeI
- https://groups.google.com/forum/#!topic/rubyonrails-security/pFRKI96Sm8Q

### Done Looks Like
- Gemfile updated
- Merge into master
- 6.4.5 released on Github

**Comment by cjcolvar** [comment]
PR to master. #3246
