### ISSUE TITLE
Investigate whether nbw is still best way to turn a create-react-app project into a npm package (create issue).

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3241]
### Description
Previously we packaged up the React IIIF Media Player with the `nwb`tool, but now we should re-evaluate whether this is the best approach still.  Ideally it'd be best to not break out of the `create-react-app` application.

### Done Looks Like
- A decision is made on what tooling/environment to use to package up the current application so it can be exported/imported.

### To Do

child of #3223

**Comment by adamjarling** [comment]
The `create-react-app` official documentation still recommends the NWB tool for creating npm packages:   https://github.com/insin/nwb#react-components-and-libraries

**Comment by adamjarling** [comment]
@cjcolvar @Dananji  So even this might be the best tool to use for packaging "NWB", I'd prefer to keep core development in our current `create-react-app` environment, because it's so good, strong community support, and heads and tails above everything else out there.  And it's currently a smooth developer experience which would be nice to maintain.

I'm thinking about something along the lines of this.  We create a separate NWB project, which is just the "packager" repository.  We don't care about tests, or even running the local demos in NWB, we use it for the packaging script alone.

When we're ready to make a release, we manually copy the `/src` contents from `structured-metadata-editor-react`repo into the appropriate directory in the "packager repo", and push this up to Github.

Then we can either pull the SME top level component into Avalon 6/7, through a Git branch, or publish to NPM if we wish as well.

**Comment by Dananji** [comment]
Sounds good :+1:

**Comment by adamjarling** [comment]
Moving forward with above direction.
