### ISSUE TITLE
Profile MediaObject.show, MasterFile adaptive m3u8 and improve performance

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3244]
### Description
Currently very slow
https://www.skylight.io/app/applications/lsyCrP8LCmuf/recent/6h/endpoints/MasterFilesController%23hls_adaptive_manifest?responseType=m3u8

Skylight is running on Pawpaw, which is using Wowza.

We need to go deeper into the profiling to learn more about what could be done to improve performance.

### Done Looks Like
- Profiling done on MediaObject.show and adaptive m3u8 generation
- Notes written on what avenues are available to improve performance

**Comment by joncameron** [comment]
No quick solution to this.

**Comment by joncameron** [comment]
See #4874
