### ISSUE TITLE
FFmpeg Encoding Profiles

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3248]
### Description
This issue is for @pdinh to report his experiments with FFmpeg encoding parameters.

**Comment by phuongdh** [comment]
1080p action and static scenes compared using different bit rates in avalon encoding profile:

2M, max 2M, buffer 2M
![image](https://user-images.githubusercontent.com/1304657/54625798-583bf000-4a46-11e9-8d18-d247ccb1f176.png)

2M, max 6M, buffer 6M
![image](https://user-images.githubusercontent.com/1304657/54625940-99340480-4a46-11e9-854e-5513a5a23160.png)

9M (original)
![image](https://user-images.githubusercontent.com/1304657/54625968-a5b85d00-4a46-11e9-9aec-c1ad0de6f778.png)

======================

2M, max 2M, buffer 2M
![image](https://user-images.githubusercontent.com/1304657/54626012-b963c380-4a46-11e9-94e3-df49d6d448f3.png)

2M, max 6M, buffer 6M
![image](https://user-images.githubusercontent.com/1304657/54626026-bff23b00-4a46-11e9-99cf-ae7cbb933665.png)

9M (original)
![image](https://user-images.githubusercontent.com/1304657/54626087-de583680-4a46-11e9-8931-6442eed7eb78.png)

======================

2M, max 2M, buffer 2M
![image](https://user-images.githubusercontent.com/1304657/54626101-e7e19e80-4a46-11e9-8078-e6e85508e122.png)

2M, max 6M, buffer 6M
![image](https://user-images.githubusercontent.com/1304657/54626111-eb752580-4a46-11e9-9e8c-0ec557c808b7.png)

9M (original)
![image](https://user-images.githubusercontent.com/1304657/54626116-ef08ac80-4a46-11e9-9a53-8a1369f10893.png)

======================

2M, max 2M, buffer 2M
![image](https://user-images.githubusercontent.com/1304657/54626133-f92aab00-4a46-11e9-8e37-f412cc450cd0.png)

2M, max 6M, buffer 6M
![image](https://user-images.githubusercontent.com/1304657/54626143-fdef5f00-4a46-11e9-9a03-7ff2b1dc0b43.png)

9M (original)
![image](https://user-images.githubusercontent.com/1304657/54626158-047dd680-4a47-11e9-853f-83ebcafa196c.png)

**Comment by phuongdh** [comment]
File size:
2M, max 2M, buffer 2M = 7.9MB
2M, max 6M, buffer 6M = 8MB
3M, max 6M, buffer 6M = 12MB
9M = 34MB

Conlusion:
Upping the max bit rate improves image quality in fast-moving scenes without noticeably increasing file size.

**Comment by joncameron** [comment]
Closing. We'll come back to encoding profiles in the future with the goal of doing more frequent evaluation and iteration on size and quality.
