### ISSUE TITLE
Mediaelement's utility method rounds time to whole seconds

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#3260]
Playlist items (and probably markers) cannot be created with time offsets more precise than whole seconds. MediaElement.js's time formatting utility functions round to seconds and  will need to be monkey patched, and/or we'll need to write our own.

https://github.com/mediaelement/mediaelement/blob/6d665634da067ac075cd49631e646c7b16f25510/src/js/utils/time.js#L74

Also, in this method the pattern matching is broken and seconds are coerced to integers: https://github.com/mediaelement/mediaelement/blob/6d665634da067ac075cd49631e646c7b16f25510/src/js/utils/time.js#L118

**Comment by cjcolvar** [comment]
Testing this on spruce, I think the following still needs to be cleaned up:
1.  Add to Playlist form start doesn't default to having subseconds when start time is 0
2.  Add to Playlist form start and end display three precision places but value only has seconds precision (00:00:10.010 -> 00:00:10.000)
3.  Scrubber marker mouseover popup has the same problem as #2
4.  SME only has two precision places and forces that level of precision
