### ISSUE TITLE
Regression Testing for 6.5

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#3265]
### Testing Scripts

- [x] Create Collection (1 scenario)
- [x] View Collection List (3 scenarios)
- [x] Delete Collection (3 scenarios)
- [x] Assign Roles (3 scenarios)
- [x] Add Item (1 scenario)
- [x] Edit Item (1 scenario)
- [x] Delete Item (1 scenario)
- [x] Publish/Unpublish item (2 scenarios)
- [x] Batch Ingest (1 scenario)
- [ ] Structural Metadata (2 scenarios)
- [x] Video Captions (1 scenario)
- [x] Playlist (14 scenarios)
- [x] Player features (8 scenarios)
- [x] Item Access Control (3 scenarios)
- [x] Assign Special Access (7 scenarios)
- [x] Bulk Actions (5 scenarios)
- [x] Accessibility (3 scenarios)
- [ ] Import Variations Playlist (2 scenarios)
- [x] Share Resources (9 scenarios)
- [ ] Timeliner (? scenarios)
- [ ] Structural Metadata Editor (? scenarios)

**Comment by cjcolvar** [comment]
The `Delete Collection` step for managers is misleading because a limitation of avalon is that managers added as editors are elevated to managers automatically so scenario 2 step 3 should say "depositor" only and not "editor/depositor".

**Comment by cjcolvar** [comment]
Regressions:
- Playlist copy button on index page doesn't open modal

**Comment by cjcolvar** [comment]
I did not test LTI in the share resources script.
