### ISSUE TITLE
Performance Testing for 6.5

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#3266]
### Description

Run the performance tests and validate performance against our benchmarks as described in our Performance Test Plan (https://iu.app.box.com/folder/31130013694)

**Comment by bkeese** [comment]
Results 
S3 7.8s (was 12.7s)
S4 negligible (was 300ms)
S5 22s (was 21.5s)
S6 36s (was 42s)
S7 33s (was 43s)
S8 29s (was 21s)
S9 59s (was 80s)
S10 15s (was 23s)
S11 12s (was 23s)
S12 16s (was 30s)
S13 25s (was 40s)
S14 8s (was 14s)
S15 negligible (was 300ms)
S16
S17
S18 negligible (was 600ms)
S19 ...
