### ISSUE TITLE
Update Avalon Timeliner Fork

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3286]
### Description
Upstream work needs to be added back into the Timeliner code that we're using for functionality within Avalon.

### Done Looks Like
- Our fork is updated
- Testing is done

**Comment by cjcolvar** [comment]
First step is getting our changes merged upstream.
https://github.com/digirati-co-uk/timeliner/pull/295

**Comment by cjcolvar** [comment]
Changes have been merged upstream and current build is in place on spruce, but we're still waiting on the final changes from upstream.
