### ISSUE TITLE
Link Subject Field in Descriptive Metadata to Blacklight Search For Field Value

### ISSUE THREAD

**Issue by jlhardes** [avalonmediasystem/avalon#3288]
# Description
Users have requested that the subject field for an item be hyperlinked to a catalog search result for matches on that subject value. This would allow users to be able to see all of the items under that subject heading in a list of search results. This doesn't have to be a standalone facet that is added to the standard facet listing, but instead can be a link that leads to a standard search page populated by querying on that particular value and subject field.

## Example
- https://media.dlib.indiana.edu/media_objects/jw827k39c contains a list of values under **Subjects**
- Each value under **Subjects**, _Sonatas (Guitar)_ for example, would be a hyperlink 
- Hyperlinks would be in the form of `https://avalon.site/catalog?f[subject_ssim][]=Sonatas (Guitar)&q=&search_field=all_fields`
- (the above link would be escaped as appropriate, with the correct filter and query parameters (may be inaccurate in the example)

# Done Looks Like 
- [x] Subject field in the descriptive metadata listing is hyperlinked to search for that subject term in the Subject field
- [x] Searching should be phrase matching. For example, if you click on a term 'Sound' in one record, should not get a match for a record that has the phrase 'Sound effects'

## Examples from Cook Music Library
This is an example of the Latin American Music Collection in the 690
https://iucat.iu.edu/catalog/536732

And an example of a donor's collection subject heading in the 690
https://iucat.iu.edu/catalog/19648080

### Previous Questions
- Can/should this be added as a facet? Music Library are interested in adding this field as a sub-collection type facetable value
- Ex: black music collection, latin american music collection, specific donor collection
- Series field in Media Collections Online populated from a different field in IUCAT
- 690 used differently by different collections; music uses $7a for their collection so might be able to use that to identify their records

**Comment by elynema** [comment]
@joncameron Does this need further consultation with Julie? I'm wondering if it should be scoped into 7.8 or wait for next release.

**Comment by elynema** [comment]
@joncameron @jlhardes My take-away from the conversation in MCO working group was that they were asking if we could bring in 690 values for the Series field to link these collections. Then these values would populate the Series facet. I don't think we need to introduce a new topical subject facet?

**Comment by joncameron** [comment]
Done looks like needs to be changed. What other things from 690 need to be accounted for?

**Comment by elynema** [comment]
We should follow up with Laikin to get an example record in IUCAT and clarify whether they have a preference for these collections being represented as series or topical subjects in MCO.

**Comment by joncameron** [comment]
Can be discussed with the MCOWG: will these be something applicable to everyone?

**Comment by joncameron** [comment]
Example:
https://iucat.iu.edu/catalog/19648080
https://media.dlib.indiana.edu/media_objects/37721159n

**Comment by joncameron** [comment]
We'll take this back to the MCOWG before continuing investigation/progress on implementing this.

**Comment by joncameron** [comment]
IUCAT does searches on the subject field itself. In Avalon's current index, we don't have a separate field for subject, and that's what we'll need to add in to be able to do this search.

**Comment by elynema** [comment]
Per the MCO working group, this does not need to be a facet (and is preferred not to be a facet b/c they don't want to expose uncontrolled vocabulary in a facet). They would like the values in the Subject field to be hyperlinked to a search for items with that term in the Subject field specifically.

**Comment by elynema** [comment]
@joncameron @cjcolvar I did find examples of subject headings that have the '/' character. These do not work well with this tool.

Example record: https://avalon-dev.dlib.indiana.edu/media_objects/9w0323021.

If you click on the heading 'HISTORY / Military / Nuclear Warfare History' you end up at a search results page with no matching items, which is not correct since this record should be matching: https://avalon-dev.dlib.indiana.edu/catalog?f%5Bsubject_ssim%5D%5B%5D=HISTORY+%5C%2F+Military+%5C%2F+Nuclear+Warfare. I'm guessing this has something to do with the slashes? Other multi-term searches without slashes work fine.

Jon, we probably should not actually be importing these subject headings into MCO as they do not display in IUCAT (they are not LCSH), but we may not want to pursue that at this point.

**Comment by elynema** [comment]
Verified that phrase matching is working. If I click on the heading "Forest" in one record, it does not bring up records with the heading "Forest fires"

**Comment by cjcolvar** [comment]
@elynema This should be ready for testing again with a fix for the slashes.

**Comment by elynema** [comment]
Working now. Closing this issue.
