### ISSUE TITLE
Waveform.json not created when ingesting new files

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#3314]
### Description

When ingesting new media files the waveform is not getting created for most files (tried with .mp3 and .mp4 file)

**Comment by cjcolvar** [comment]
Two parts of this:
1) Determine why waveforms are being created and fix it.
2) Add a hook to the SME show controller action that kicks off the waveform generating job when it encounters the waveform missing.  Change the SME error message to tell the user that the waveform is being generated and to check back later.
