### ISSUE TITLE
Create a starter repository for React, redux, webpack, npm packaging project

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3320]
### Description
Create a boilerplate repository for creating a React application/component which can be imported into another application (ie. Avalon).

### Done Looks Like
- Repo created and forked into `avalonmediasystem`.
- Documentation added.

**Comment by adamjarling** [comment]
Updated and created at:

https://github.com/avalonmediasystem/starter-react-webpack-npm_packaging-project

**Comment by Dananji** [comment]
I forked the repository and created a sample component following the instructions in the README, which are very clear about starting out with this project. And integrated the sample React component in Avalon, and it works!
@adamjarling Great work!!
