### ISSUE TITLE
Waveform Not Displaying Regions On Load

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3327]
### Description
When launching the structural metadata editor, the timespans are occasionally not showing on the waveform visualizations as color regions. If the modal is closed and reopened, the waveform displays properly. 

@Dananji noted that this is most likely a timing issue.

### Done Looks Like
- When launched, time regions are colored appropriately in the waveforms.

**Comment by Dananji** [comment]
The segments in Peaks are created from the timespans in the `structure.json`.  Sometimes the structure is empty at the time of the Peaks initialization. This leads to the empty waveform in UI.

Implementing a way to update the UI after the asynchronous API call for the `structure.json` is finished before initializing Peaks will fix this issue.

NOTE: Using asynchronous actions in Redux store will be one way to fix this.
