### ISSUE TITLE
Precompiling assets shouldn't need Fedora/Solr

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3332]
I don't want to (can't always) stand up Fedora/Solr just to precompile assets. This is necessary to build a production-ready Docker image, so we don't have to compile assets every time we bring a container up.

- [ ] Remove dependency on Fedora/Solr for `rake assets:precompile`
- [ ] Update Dockerfile

**Comment by joncameron** [comment]
Timeboxed to a 2.
