### ISSUE TITLE
Warn User If Derivative is Missing and Update Current Error Messages

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3333]
### Description
Users need to be informed when there is an error upon trying to load resources used in the editor.

### Current Behavior
Currently, the React app looks for the waveform and shows a warning instead of the waveform in the UI. If the structure is not already created and there is no waveform, we create a single element from the section label and show that.

### Done Looks Like
- A simple error message displays when a stream request gives a bad response.
- Messages below updated (to be written as part of this issue)

### Note 
What is the current error message displayed for missing waveforms?
- "Requested masterfile not found." (for when the status is 404 on the structure or the waveform)
- "Error initializing the peaks.js waveform"

**Comment by Dananji** [comment]
@joncameron Following are the error/warning messages the SME gives for the given scenarios;

Error fetching/posting data from/to server:
    Status code 401 -> **Unauthorized to access the masterfile**
    Status code 404 -> **Requested masterfile not found**

Error fetching structure and waveform with a status code other than 401/404:
    Structure.json ->  **There was an error fetching the Structured Metadata from server**
    Waveform.json ->  **There was an error initializing the PeakJS waveform**

Saving to masterfile successfully -> **Successfully saved to masterfile**

When there's no space to create more timespans -> **Time ahead has timespans reaching the end of media file, there is no available time to insert a new timespan**

Generic error message -> **Network error, please try again**

If you could update the message as necessary I can change them in the code.

And what would be the specific error message for the missing derivative?

Thanks!

**Comment by joncameron** [comment]
Thanks @Dananji! I'll update the messages in the issue this afternoon and ping you once they're ready.

**Comment by Dananji** [comment]
Errors comes as Hls events and then the error needs to be separated.
This error needs to passed into the application's error handling mechanism to create an alert visible in the UI.

**Comment by Dananji** [comment]
When there is an error in fetching the derivative, the Peaks's `player` instance becomes empty. 

Therefore the duration of the file becomes `NaN` (Not-a-number), which displays the warning `Time ahead has timespans reaching the end of media file, there is no available time to insert a new timespan` every time a user tries to add a timespan even when there is space available ahead.

For that reason, along with the warning the `Add a Timespan` button is disabled.

**Comment by joncameron** [comment]
Error fetching/posting data from/to server:
    Status code 401 -> **You're not authorized to access this resource.**
    Status code 404 -> **Requested data not available.**

Error fetching structure and waveform with a status code other than 401/404:
    Structure.json ->  **There was an error retrieving the structure information.**
    Waveform.json ->  **There was an error initializing the waveform.**

Saving to masterfile successfully -> **Saved successfully.**

When there's no space to create more timespans -> **There is no space available to insert a new timespan.**

Generic error message -> **Network error. Please try again.**

@Dananji

**Comment by Dananji** [comment]
@joncameron What would be the error message for missing derivative, when the status code is not 401/404 (Similar to '**There was an error retrieving the structure information.**' for Structure.json) ?

**Comment by joncameron** [comment]
@Dananji Let's go with "There was an error retrieving the media stream."
