### ISSUE TITLE
Structural Metadata Editor Testing and scenario generation

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3334]
## Description

We need to generate scenarios and run through them form the SME in advance of 6.5

## Done looks like
- [x] scenarios documented
- [x] scenarios run through

#### Waveform generation
- [x] Waveform generation needs to be checked - we may have a situation where waveforms are a different length than the media stream

#### Modal and informational fixes
- [x] When closing the SME modal, give the user a warning about unsaved changes
- [x] Remove the “Close” button at the bottom of the modal along with the unnecessary space that comes with it 
- [x] Put a informational message to the user on the Structure edit page to let users know that the page must be refreshed to show structure changes in the XML editor if changes have been made in the SME (advanced edit XML is cached when the page is loaded) 

#### Time value handling
- [x] SME should handle time values like "MM:SS", "SS", that Avalon is able to handle in the structure. These are not valid currently in SME; it's expecting HH:MM:SS.ms and doesn't handle other formatted times. 
- [x] In the structure XML, spans can have begin attributes with no end attribute (this is specified in the mediafragment spec). This isn’t currently handled in the SME. SME should be able to handle  these.
- [x] The end time value and beginning time value of two adjoining spans should be able to be the same (right now there’s a required 1ms gap in SME). For example, One span could be from 10:00.00 to 12:02.00, and the next span should be able to be from 12:02.00 to 13:00.00.

**Comment by joncameron** [comment]
#### Further enhancements and fixes 
These are not blockers for release and can be fleshed out for a future iteration of the SME
- The "Child of" drop-down box should be pre-filled with a default value. Even in cases where there is only one option, users still need to select a value from the list.
- Better contrast for the default gray coloring of the waveform. The current gray doesn't as much contrast as would be ideal.
- When editing a timespan, zooming out causes the gray color to overlap what should be the orange of a selected timespan. This may be an edge case and is not highly reproducible. 
- There should be a button to play from the beginning of the currently selected timespan.
- The default HTML5 player should be removed and a standalone play/pause button and volume toggle should be introduced instead. This removes the redundant rail that comes with the HTML5 player and introduces consistency (different browsers render the default player differently)
- Only one editing mode should be available to be used at one time. The two modes are rearranging (dra and drop) and editing. If one is active, the other should be disabled.
- 2 drop targets for the same space value sometimes appear when in drag and drop mode. 
- No drop target at the bottom-most heading
- Icon for drag and drop - the circle isn’t very instructive. This should be changed to a more meaningful icon.
- Drop target for span in the first sub-heading can’t be promoted up to the level of its heading
- Add confirmation on “Remove” button for structure (and captions) on the Structure edit page. Currently there is no warning or confirmation when clicked.
- The “Child Of” drop-down doesn’t show all of the expected values. For example, it sometimes doesn’t show the top-most heading , or the last heading, even when the timespan is valid to be placed there.

**Comment by Dananji** [comment]
@joncameron Can I start working on the issues in this comment?

**Comment by joncameron** [comment]
@Dananji I'd prefer to have these written out as issues first, unless there's one you feel clear on and would like to jump on now. I did create one ticket from this that should be small: https://github.com/avalonmediasystem/avalon/issues/3377

**Comment by Dananji** [comment]
Yeah. I will work on that. Thanks!
And any issue that I feel clear I will work on them and mark them here.

**Comment by Dananji** [comment]
@joncameron, These are the fixes that I need more clear explanations. If you were going to write these as separate issues, please do so for the following. The rest have been fixed and I'm currently working on:

`The default HTML5 player should be removed and a standalone play/pause button and volume toggle should be introduced instead. This removes the redundant rail that comes with the HTML5 player and introduces consistency (different browsers render the default player differently)`

1. The "Child of" drop-down box should be pre-filled with a default value. Even in cases where there is only one option, users still need to select a value from the list.
2. When editing a timespan, zooming out causes the gray color to overlap what should be the orange of a selected timespan. This may be an edge case and is not highly reproducible.
3. There should be a button to play from the beginning of the currently selected timespan.
4. Icon for drag and drop - the circle isn’t very instructive. This should be changed to a more meaningful icon.
5. Add confirmation on “Remove” button for structure (and captions) on the Structure edit page. Currently there is no warning or confirmation when clicked.

Thanks!
