### ISSUE TITLE
Video Player Does Not Some Browsers

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3335]
### Description
In Safari 12.1, MediaElement displays an audio player for audio items, but does not display the player for videos.

The same holds true for the latest Chrome for Android, tested on a Galaxy S9 in Browserstack.

And for Internet Explorer 11 on Windows 7 in Browserstack.

### Done Looks Like
- The video player appears on the view page for all browsers.

**Comment by cjcolvar** [comment]
#3337 allows the player to load and play on Safari on OS X and iOS as well as Chrome on Android and IE11. 
But the captions button is not sticky on Safari on OSX (this might also be the case for iOS and Android).  @davidschober @joncameron Is this an issue that needs to be fixed?  It appears that this is currently broken in MCO.

**Comment by davidschober** [comment]
Can we do a small dive to see what it takes to fix it?

**Comment by cjcolvar** [comment]
I already did a dive on this and it wasn't obvious how to resolve the issue which appears to be inside ME.js: `player.tracks` wasn't initialized as expected here (https://github.com/avalonmediasystem/avalon/blob/develop/app/assets/javascripts/media_player_wrapper/avalon_player_new.es6#L338).
I think it would probably take more time than it is worth it to fix this right now and the impact to the user is minimal.  The worst is that the user needs to click the captions button to re-enable captions when a new section starts playing.

**Comment by mcwhitaker** [comment]
@joncameron @davidschober  I would be fine with closing this, but I think we need to include it in our _known issues_ page with the workaround documented.

**Comment by joncameron** [comment]
I've updated the Known Issues page and will close this issue.
