### ISSUE TITLE
Update Installation Methods and Documentation for 6.5

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3372]
### Done Looks Like 
- [x] Update manual install instruction for: new ffmpeg, disable HLS module
- [x] Update Docker install
- [x] Create Docker install for 6.5 (to replace VM Image)
- [x] Write instructions for non-dev Docker use

**Comment by joncameron** [comment]
@phuongdh Up to date instructions are at the README for https://github.com/avalonmediasystem/avalon-docker?

**Comment by joncameron** [comment]
Still need to alter language on the wiki and website regarding Docker containers for tagged releases.
