### ISSUE TITLE
Unable to Play Items in Internet Explorer 11

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3376]
### Description
Media streams do not play in Internet Explorer 11. Tested on Browserstack: Win7, IE 11.

Console screenshot from IE 11:
<img width="482" alt="Screen Shot 2019-05-23 at 2 05 52 PM" src="https://user-images.githubusercontent.com/1406618/58275961-3ae81280-7d64-11e9-8066-f4d090bb716f.png">

Most likely a regression, originally reported and resolved in #2661.

**Comment by bkeese** [comment]
This was originally resolved by removing the Quality feature of the player for IE11. That change remains in place, but is no longer working.

**Comment by joncameron** [comment]
Tested today and could not reproduce. Maybe a streaming server hiccup when hitting it from the Browserstack network?
