### ISSUE TITLE
Timeliner — Browser Displays Unnecessary Warning

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3388]
### Description
Navigating away from the Timeliner view within Avalon after changes are made, even if a save action is done directly before navigation away from the page, results in the "are you sure?" dialog:
![Screen Shot 2019-05-30 at 9 27 08 AM](https://user-images.githubusercontent.com/1406618/58636171-adee0d80-82bd-11e9-8b34-a9b35b8941aa.png)

If a user has saved the current state of the Timeline, they shouldn't be presented with this warning.

**Comment by bkeese** [comment]
This message is triggered by there being contents in the Undo Queue. We no longer empty the queue when saving.

**Comment by cjcolvar** [comment]
I did some initial work on this but didn't have a good place to test it.  Now that 6.5 is out we could maybe test it out on spruce.  Here is the timeliner branch I was working on: https://github.com/IUBLibTech/timeliner/tree/unsaved_changes
