### ISSUE TITLE
Streaming to Android from Wowza only works on 'auto' quality setting

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#3394]
### Description
When using Wowza, streaming on Android only works on the 'auto' quality setting. The option to change the stream quality level should be hidden from the user to avoid this complication.

### Done Looks Like
- On Android browsers, the quality selection button does not appear on the media player, disallowing users to explicitly change quality levels.

### Original ticket
When testing the release of Avalon 6.5 on Android, several things were noticed:
- When streaming from pawpaw and MCO (wowza), only 'auto' quality setting works.
- When streaming from mallorn (nginx), streaming works as expected.
- Quality selection is not sticky.

Testing on Android 9, Chrome 74

Related to #3393

**Comment by cjcolvar** [comment]
I wonder if this is due to how the HLS manifest is being generated since the auto manifest Avalon creates wrapping the underlying streaming server manifests.  Maybe we could use the new HLS routes per quality (high.m3u8, medium.m3u8, low.m3u8) that we made for the IIIF Auth implementation since they wrap the underlying manifests just like auto.m3u8.  Unfortunately I found #3393 which blocks testing out this theory.

**Comment by cjcolvar** [comment]
I tested on spruce and while the quality selector was no longer there I couldn't get streaming to work on any of the Android devices I tested (Galaxy S8,9,10+) in browserstack.  Maybe this is just a spruce issue?  I was able to stream this same video (https://spruce.dlib.indiana.edu/media_objects/qf85nb40f) in Chrome on my laptop but wasn't able to on the latest iphone in browserstack.

**Comment by cjcolvar** [comment]
Brian tested on his galaxy S8 running android 9 with chrome 78 and streaming worked fine.  I tried the same configuration on browserstack and it failed.  I wonder if there is a firewall issue?  I didn't think there was.  Maybe this is a browserstack issue then?

**Comment by phuongdh** [comment]
Worked on Galaxy S10e, Android 9, Chrome 78.
