### ISSUE TITLE
README has stale URL for Mediainfo CLI

### ISSUE THREAD

**Issue by dmolesUC** [avalonmediasystem/avalon#3416]
Under “[Setting Up an Avalon Media System Development Environment](https://github.com/avalonmediasystem/avalon#setting-up-an-avalon-media-system-development-environment)”, the README gives http://mediainfo.sourceforge.net; the current URL appears to be https://mediaarea.net/en/MediaInfo/Download/Mac_OS.

**Comment by cjcolvar** [comment]
Fixed by #3418.
