### ISSUE TITLE
Create "an intro to metadata in avalon"

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3442]
## Description 
As a new adopter, I want a section on the wiki that introduces Avalon's metadata in an easy to understand way. Ideally this would be written using "real world" examples so end users can link the theoretical to a real world implementation. 

## Done looks like
- Discussion takes place to map out what we want to communicate, using past experiences in consulting with new and existing Avalon users about their metadata needs
- A TOC is written
- MODS and how it's used by Avalon is organized and easily findable/accessible
- Examples are laid out
- the section is written and put on the wiki

**Comment by jenyoung** [comment]
We don't have any documents written up yet but we have this plan:

Construct a new wiki page for Supported Field Names list: https://wiki.dlib.indiana.edu/display/VarVideo/Batch+Ingest+Package+Format#BatchIngestPackageFormat-SupportedFieldNames

Create new Metadata wiki page and add as a section in Avalon Collections Guide (maybe between "Players and Controls" and "Creating Units"?) - https://wiki.dlib.indiana.edu/display/VarVideo/Avalon+Collections+Guide

On new Metadata wiki page - Include general intro to current metadata status (descriptive metadata still MODS XML and everything else is RDF properties from various ontologies). Then link to Avalon Metadata Profile for RDF properties and new Supported Field Names wiki page for descriptive metadata fields.

Additional paragraph on main Metadata page can include future plans for descriptive metadata as RDF and link over to Avalon Audiovisual Work Model: https://github.com/samvera-labs/avalon-bundle/wiki/Avalon-Audiovisual-Work-Model

**Comment by jenyoung** [comment]
draft: https://wiki.dlib.indiana.edu/pages/resumedraft.action?draftId=549127428&draftShareId=e24e22d2-b703-4baf-8b83-519815042187&

**Comment by jlhardes** [comment]
Further edit made to @jenyoung's draft - needs review.

Suggested new page for Supported Field Names: https://wiki.dlib.indiana.edu/pages/resumedraft.action?draftId=549127622&draftShareId=bfd72f48-8038-4230-abdb-6bee5ac545c6& 

Supported Field Names section of Batch Ingest Package Format would be removed and linked to this.
