### ISSUE TITLE
Prep UI options presentation for Avalon 7

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3448]
### Description
Prepare a presentation for the Face 2 Face meeting, outlining options and recommendations for developing the UI in Avalon Bundle.

### Done Looks Like
- Presentation given

### Tasks
- [ ] prep presentation

**Comment by adamjarling** [comment]
Based off of: https://docs.google.com/document/d/1z5pggNcam-sTp4OVrbJP8tiTaHZDdrtUL0qEwpW7Ntg/edit?usp=sharing

**Comment by Dananji** [comment]
@adamjarling I can't access the Google doc in the link in the comment.
I already created a Google doc and shared with you the same day after our discussion (on 27th June). The email I used was adam.arling@u.northwestern.edu. Maybe you didn't get the invitation..
Anyway, I will add the things I wrote in my document to this one.

**Comment by adamjarling** [comment]
Oh, sorry about that.  I rarely check my u.northwestern.edu account for emails...just more for access.  Whichever doc you want to use is fine by me.

**Comment by Dananji** [comment]
We can use this one. This is thorough than what I have :)
