### ISSUE TITLE
Investigate "hide from results"

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3457]
We would like to deprecate this feature. NU no long needs it, IU has ~ 400  uses of it. We would like to do a dive into how this is being used (if at all still) and whether or not it's ok to kill it off.

### Done looks like:

- get list of uses
- do a quick review with collection managers who used the feature on the 400 items to see if they need the feature

**Comment by cjcolvar** [comment]
Gist created and passed to @joncameron in slack.

**Comment by joncameron** [comment]
Use Case:
- I have streaming media in Avalon, but the main reference and record for the content is within another repository or service. This could include things like an IR or a repository supplemental materials to print books. I don't want the item discoverable except within these services; Avalon contains my media but is not the repository I want people to be using for search and discovery.

Some of the list that was produced from IU production on items that were set to "hide from search" are from items that didn't need to be set to 'hide from search'. The others are mostly fitting the use case above. 
- Items in the IR, but the media is in Avalon
- The media is only meant to be embedded in another site, like an article in a scholarly publication, and search and discovery from within Avalon as a search and discovery tool, or items in Avalon which are indexed in a search engine, is undesirable. 

I think that "hide from search" is a valid use case given the examples above and should be retained. Other applications offer this as well, usually under the term 'unlisted'.
