### ISSUE TITLE
Bib Import

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3460]
For Avalon 7 we need to have Bib import working in a Hyrax context. 

## Done looks like
- Investigation into current bib import trends, new mark fields
- investigation into local customization to see if we can elevate any local work
- Execute bib important and transformtion
- document transformation and to customize

**Comment by joncameron** [comment]
Would have to be on us for now, but could be interesting to throw out to the community as common work we could do together. Implementation: ? Lots of different approaches possible.

**Comment by joncameron** [comment]
Will create a new ticket for this when we're working on avalon-bundle and ready to implement or investigate this.
