### ISSUE TITLE
Investigate Ordering descriptive fields 

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3461]
## Description 

As part of our core requirements for AV 7 we need to order descriptive fields

## Done looks like
- tap metadataists for examples of this in the community/wild (in a Hyrax install)
- take a look at other implementations of ordering in Hyrax
- Make recommendations for how to order descriptive metadata
- write issues as necessary.

**Comment by joncameron** [comment]
It would be best to have metadataists provide examples before launching into investigation.

**Comment by jlhardes** [comment]
Here is the final report from the Hyrax Metadata Ordering Working Group: https://wiki.duraspace.org/download/attachments/90977535/Hyrax_Metadata_Ordering_Report.pdf

**Comment by jlhardes** [comment]
The examples from various institutions that the WG reviewed are available in this google group thread: https://groups.google.com/forum/#!topic/samvera-tech/g1oa5B2B0Wk

**Comment by cjcolvar** [comment]
Julie and I looked through the Audiovisual work type form and thought these fields need to be ordered: `title`, any names (`Main Contributors`, `Contributors`)

**Comment by cjcolvar** [comment]
Using a JSON blob like we're currently doing for the multi-part fields could work for preserving ordering as well at least to start with.  Possible blockers for this approach are if we want to order any RDF triples that have URIs instead of literals or splitting them back up into multiple triples when sharing the RDF out.

**Comment by jlhardes** [comment]
Hyrax 3 is making a change for the Title field: https://github.com/samvera/hyrax/issues/3299

Behind the scenes multiple titles are still there but the form is only going to allow one, so Avalon could limit to just one title and we don’t need to order that field. That would leave Main Contributors and Contributors as the only fields requiring order to get started.
