### ISSUE TITLE
Embedded Media Player

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3462]
### Description
Avalon features an embedded player—a route that returns only the player, with some specific changes for the context change of being embedded in another page as an iframe. This needs to be implemented in Avalon on Hyrax.

### Notes
- Is feature parity with Avalon 6.x+ the wrong thing to target? There are many issues with the current version of Avalon's embedded player:
   - no structure available for navigation
   - can't embed all sections (restricted to one section per embed)
   - no quality selection for audio
   - limited metadata options
- Player API needs to be implemented.

It's important to retain discrete quality selection. Part of re-implementing the embedded media player could be looking at this and the other problems outlined above to see if these can be reasonably added while this work is done.

**Comment by davidschober** [comment]
@joncameron I'm not sure I understand what this issue is.

**Comment by joncameron** [comment]
@davidschober Epic for the embedded Avalon player (avalon.tld/master_file/ID/embed) for Avalon on Hyrax. I added some text to make that more explicit.
