### ISSUE TITLE
Investigate Ingestion API

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3464]
## Description
As we move toward feature parity, we need an ingestion API in Avalon 7 that can be used for MDPI, switchyard, etc. The ingestion API allows the creation of metadata with side-loaded content. 

## Done looks like
- dig into existing Hyrax API  implementations
- discuss with POs pros cons of different path's forward
- write issues to execute.

**Comment by cjcolvar** [comment]
@davidschober @joncameron Should this ticket be moved to avalon-bundle?

**Comment by joncameron** [comment]
@cjcolvar Definitely! Moved to https://github.com/samvera-labs/avalon-bundle/issues/355
