### ISSUE TITLE
persona punchlist

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3484]
@orangewolf I moved this to a new issue for easier tracking for the team. 

The Avalon team got together, and I realized there were a few parts I didn't understand about how persona was working under the hood. Hopefully this is a punchlist we can work from:

- [x] The identity provider should be listed in the "manage users" table. There's a column for it, but it is not being updated.
- [x] Change / Edit should be greyed out, not visible if the user is not a local user (devise). We discussed this as a solution to managers trying to edit passwords/reset passwords when they can't.
- [x]  Remove admin from the footer. My notes had us settling on documentation for those setting up Avalon. 
- [x] @cjcolvar was investigating whether there's an existing screen to use instead of the screen that comes up when you click "admin". At a minimum LTI needs to be removed. 
- [x] LTI Should be removed from screen as it's not a login method. 
- [x] Add some spacing around the "forgot password" and "sign up"
- [x] Failed login for email/password goes back to /users/sign_in with the provider choice buttons revealed and the login form hidden.
- [x] Add Hard Deletes!

**Comment by davidschober** [comment]
relates to #3451

**Comment by cjcolvar** [comment]
Things I'm seeing now on spruce:
1. Failed login for email/password goes back to /users/sign_in with the provider choice buttons revealed and the login form hidden.
2. Back to Admin button doesn't work and presents the error: "You are not authorized to manage users"
3. I'm still a bit confused by soft deletes and wonder if we should use hard deletes for now to avoid errors and confusion.  I also can't seem to delete a user even when using `#really_destroy!` in the rails console.

**Comment by orangewolf** [comment]
2. sounds like a bug, I'll look at it.

3. is.a bug
 https://cl.ly/e5a73db50431/Screen%20Shot%202019-08-14%20at%208.57.15%20AM.png
`really_delete` works as it should and `destroy_without_paranoia`  works, but something is conflicting on `really_destroy!`

**Comment by cjcolvar** [comment]
@orangewolf Thanks for fixing `really_destroy!`.  I still would like to talk through soft deletes with the POs since I think it is confusing from an end user perspective without more functionality that isn't currently there yet.

**Comment by cjcolvar** [comment]
@orangewolf So I did a little exploration and #2 is due to the `auth` `before_action` causing the post to `stop_impersonating` throw a `AccessDenied` error.  Skipping that `before_action` in a monkey patch initializer makes things work as expected.
```
Samvera::Persona::UsersController.class_eval do
  skip_before_action :auth, only: [:stop_impersonating]
end
```
I'll make a quick PR to persona now.

**Comment by orangewolf** [comment]
great, pushed up 0.1.5 w/ your change merged in.

for (1) I think we could use an anchor tag to reopen the email section. Can you let me know if you consider that in scope? 

I'm happy to continue answering questions after the fact and I want to get the work to a place everyone is happy with it, but I also know from experience that we have get to a clear "done" on the contract. Can you let me know what your thoughts are on that?

**Comment by joncameron** [comment]
Hi @orangewolf,

For (1) using a tag to reopen the section sounds great. That's in scope for us.

For (3) we want to go with a strategy of hard deletes. Implementing soft deletes can be done at a later time if we come up with some stronger use cases, but right now hard deletes will meet our needs and seems quicker to finish off.

These two hopefully small things are all that's left, and once they're completed we're ready to call it done!

**Comment by orangewolf** [comment]
thanks Jon, I appreciate the clarity.

**Comment by orangewolf** [comment]
The last PR #3558 turns of soft delete.  The one before it fixes an issue with getting invites to work.  If fixed it so I could get some users to delete and figured I'd push it up while I was at it.

**Comment by orangewolf** [comment]
@joncameron punchlist has how been punched 🤛

**Comment by davidschober** [comment]
Thanks @orangewolf. I'm out of town tomorrow. @joncameron let's you and I schedule time to test / sign off on this next week. @cjcolvar can you let  us know when it's staged/ready for testing.

**Comment by cjcolvar** [comment]
@davidschober Everything should be on spruce ready for testing.  We should might want to try turning off omniauth-identity on spruce for a round of testing with only persona.

**Comment by davidschober** [comment]
@orangewolf This looks great. Feel free to send to close it out!
