### ISSUE TITLE
Link to Source Item from Timeline

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3497]
### Description
As a user, I want to go to the source item page from a timeline so that I can see more information about the item such as descriptive and structural metadata.

### Done Looks Like
- A link to the item section is available in the "Timeline Information" area of the Timeliner
- The link is a PURL, if available
- The link is absolute

**Comment by bkeese** [comment]
PR #3498 bug: The Source Object link redirects to the media object show page, but it does so within the timeliner's iframe, not at the host page's level.

**Comment by cjcolvar** [comment]
:+1: That totally makes sense.  That will have to be a timeliner change.
