### ISSUE TITLE
Auto quality not visible for audio items on mobile

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3503]
The quality selection popup renders above the audio player but it goes past the top of the page and thus isn't visible.  If you expand the first hamburger menu then there is enough space to show all of the available qualities. (This isn't present when you're signed in or on IU production because we have a larger header.)
<img width="165" alt="Screen Shot 2019-08-14 at 11 31 40 AM" src="https://user-images.githubusercontent.com/1053603/63034370-37f24f00-be87-11e9-9fc3-ef466318b251.png">
<img width="165" alt="Screen Shot 2019-08-14 at 11 32 14 AM" src="https://user-images.githubusercontent.com/1053603/63034369-37f24f00-be87-11e9-95a2-e8a8a8d93f76.png">

**Comment by joncameron** [comment]
@SumithBaddam noted: Tested and is still persistent
