### ISSUE TITLE
Move a Section to Another Item

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3514]
### Description
As a collection manager, I want to move a section to another item so that I can correct items in which a section is in the wrong item

### Done Looks Like
- On an item's "Manage file(s) page, each masterfile displays a "Move" button in addition to a "Delete" button
- Clicking the "Move" button displays a modal 
- The modal has a field where users can enter in the NOID of the media object to move the section to
- This modal includes a bit of AJAX-y magic to display information on the requested ID (like title) and indicate whether the move action will be successful (red coloring for media objects that a user cannot move the section to, for example, and green coloring for those they can)
- The modal has a submit button that triggers the move
- If the user submitting this action does not have permission to add a masterfile to the target object, they receive an error message

#### ❇️ Specifics based on further prototyping
- The modal contains:
  - "Target Item Identifer:" text field.
  - Text area for metadata/messages to user
  - "Move" button
  - "Cancel" button
- By default, the text area has text that reads "Please enter a valid item identifier."
- When a valid ID is entered, the modal displays metadata from target media object:
  - Title
  - Collection
  - Main contributor
  - Publication Date
  - Published status

- When "Move" is clicked, the page reloads with a flash message.
  - The Flash message read "Section successfully moved to Item #{Media Object NOID}". Item #{Media Object NOID}" text is a hyperlink to that media object.
- When "Cancel" is clicked, the modal closes.

### Mock up
![move](https://user-images.githubusercontent.com/1406618/63100315-d1cc0180-bf44-11e9-832c-8dec1a3857b9.png)

**Comment by cjcolvar** [comment]
I think the modal will want to make GET requests to a new endpoint (let's call it `/media_objects/:id/move_preview.json` for now) which will return basic information about the target media object in JSON if it is a valid target and a 403 when it is not a valid target (user doesn't have edit privileges on it).
The modal should submit it's form to `/master_files/:id/move?target_id=:target_id`.
