### ISSUE TITLE
Add Rights Statement Metadata for Items

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3516]
### Description
Implementing rights statements using the frameworks/resources from rightstatements.org 

### Done Looks Like
- A rights statement is able to be included in the descriptive metadata for an item
- This value, out of a controlled vocabulary, comes from rightsstatements.org
- This information is presented along with other descriptive metadata on an item's view page, and the text for the rights statement is hyperlinked to the appropriate page at rightsstatement.org

### Notes
- "rightsstatements.org", both words plural

**Comment by cjcolvar** [comment]
Should we gracefully handle the case when rights statements aren't in the controlled vocabulary?  Also the target _blank didn't render so that needs to be fixed.
