### ISSUE TITLE
Collection Description Text Should Retain Line Breaks

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3534]
### Description
Line breaks should be able to be entered and honored when the Collection Description text is rendered out on the page. They are saved within the field—I can enter line breaks for the description on the "Edit Collection" modal, save, re-open the modal for editing and see the line breaks in the text field—but these line breaks do not appear in any current display of this text (currently only "Manage Content" and the Collection's Admin page, but soon in a publicly viewable index of collections.

### Done Looks Like
- When rendered on a page, collection descriptions include line breaks

#### Text in the edit modal
<img width="893" alt="Screen Shot 2019-08-26 at 1 52 51 PM" src="https://user-images.githubusercontent.com/1406618/63711404-59e5bd00-c809-11e9-9559-74ecc4c44018.png">

#### Text display on the collection's page
<img width="642" alt="Screen Shot 2019-08-26 at 1 53 01 PM" src="https://user-images.githubusercontent.com/1406618/63711423-65d17f00-c809-11e9-80fc-2907924db518.png">

**Comment by cjcolvar** [comment]
This is fixed in the new collection index/landing pages and the admin edit collection but not the admin collection index page.  I can address that in #3527.
