### ISSUE TITLE
Update avalon-docker and Instructions

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3541]
### Description
As a user, I want to have accurate documentation that walks me through the steps of running Avalon under Docker, even if I'm not familiar with Docker or Avalon.

Follows from #3434.

### Done Looks Like
- [x] README is updated to include current OS X instructions (current instructions point to deprecated software and terminal commands)
- [x] Docker version release schedule is decided. Right now there are two releases for the avalon-docker repo: https://github.com/avalonmediasystem/avalon-docker/releases. Should this happen every Avalon release? Is it enough to point users to Master for the latest version of Avalon?
- [x] The step _Copy dotenv.example to .env and fill in the passwords and Rails secret key base._ is handled automatically and doesn't require manual entry of these values.
- [x] 413 error when uploading is fixed (see details in #3434)
- [x] auto.m3u8 not loading issue is fixed (see details in #3434)

**Comment by phuongdh** [comment]
Even though I don't expect the Docker script to change much if at all between minor Avalon versions, we could try tying Docker release to Avalon point release if that helps with clarity.

**Comment by joncameron** [comment]
Following the instructions, I encountered errors on Fedora 30. The output from Docker is here (formatting got mangled a bit):
[docker_fedora_output.txt](https://github.com/avalonmediasystem/avalon/files/3659340/docker_fedora_output.txt)
The database wasn't starting, it seems like.

**Comment by joncameron** [comment]
On macOS 10.13, I got the following when attempting to bring up the stack:

```
mallow:avalon jon$ docker-compose up avalon
Creating network "avalon_internal" with the default driver
Creating network "avalon_external" with the default driver
Creating volume "avalon_streaming" with default driver
Creating volume "avalon_database" with default driver
Creating volume "avalon_fedora" with default driver
Creating volume "avalon_work" with default driver
Creating volume "avalon_solr" with default driver
Creating volume "avalon_gems" with default driver
Creating volume "avalon_npms" with default driver
Creating avalon_db_1    ... done
Creating avalon_solr_1  ... done
Creating avalon_redis_1 ... done
Creating avalon_fedora_1 ... done
Creating avalon_avalon_1 ... error

ERROR: for avalon_avalon_1  Cannot start service avalon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/rails_init-dev.sh\": stat /rails_init-dev.sh: no such file or directory": unknown

ERROR: for avalon  Cannot start service avalon: OCI runtime create failed: container_linux.go:345: starting container process caused "exec: \"/rails_init-dev.sh\": stat /rails_init-dev.sh: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
```

**Comment by phuongdh** [comment]
@joncameron has confirmed everything works now.
