### ISSUE TITLE
Performance improvements for Avalon 7

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3548]
### Description
We need to profile and improve performance in general and specifically around MediaObject/Masterfile write operations. This is a timeboxed issue for investigation and work as encountered.

- [ ] Eliminate unnecessary saves
- [ ] Cache more often
- [ ] Make as few calls to Fedora as possible
- [ ] Lazy load when possible
- [ ] Load javascript more selectively
- [ ] To be continued

Current benchmark: https://wiki.dlib.indiana.edu/display/VarVideo/Performance+Metrics

### Notes
- Timebox? Work on it for 2 or 3 days and go from there.
- What places to we want to target in the application?
  - Playlists, item view, updating media objects, deletion of large objects, adaptive m3u8 generation
- Using Ruby profiler and Flamegraph

**Comment by davidschober** [comment]
@cjcolvar This should move into the next sprint. Do you and/phoung want to take a crack at pointing it?

**Comment by davidschober** [comment]
@phuongdh this feels like it might be an epic. Let's talk about this during a refinement session.

**Comment by joncameron** [comment]
See #4874
