### ISSUE TITLE
Some media not playable on mobile

### ISSUE THREAD

**Issue by ConnorSheremeta** [avalonmediasystem/avalon#3562]
Some media is not playable on mobile. Changing the quality sometimes resolves the issue. Occurs on spruce with Samsung S8 on Android 8 using either Chrome or stock browser. Also occurring on our Avalon 6 HLS instance using the same device.

Example items where this problem always occurs:
https://spruce.dlib.indiana.edu/media_objects/c6598f95-5082-4bed-a024-9337f6e68b66
https://spruce.dlib.indiana.edu/media_objects/sj1392079

Example item where this problem never occurs:
https://spruce.dlib.indiana.edu/media_objects/9593tv280

**Comment by ConnorSheremeta** [comment]
Also able to reproduce with Android 10, Chrome 76.0.3809.132 with audio (not video)

**Comment by joncameron** [comment]
@SumithBaddam noted: Tested this and some media is not playable on Nexus 7 Android 6 but it is playable on Samsung galaxy S8 with android 7.

**Comment by ConnorSheremeta** [comment]
Why was this closed?

**Comment by Dananji** [comment]
Hi @ConnorSheremeta, this was fixed with [this PR](https://github.com/avalonmediasystem/avalon/pull/4186), which enables `native_hls` renderers in mediaelement.js player for Android devices.
