### ISSUE TITLE
Edit Group success flash message color fix

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3564]
### Description
The "success" flash message when editing a group is blue, and should be green to be consistent UX.

![image](https://user-images.githubusercontent.com/3020266/64375649-df2c5700-cfeb-11e9-8a96-2f54a9bd412d.png)

### Done Looks Like
- When editing a group, successful flash message is green.

### Tasks
- [ ] Figure out where this flash message type is getting sent from in the Edit Groups controller?

**Comment by bkeese** [comment]
https://github.com/avalonmediasystem/avalon/blob/develop/app/controllers/admin/groups_controller.rb#L108
