### ISSUE TITLE
Links to Non-existent Fedora 3 Identifiers Return 500 

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3566]
### Description
Requests for media objects with Fedora 4 identifiers returns a not found message if not found, but Fedora 3 identifiers, if there is no map to a Fedora 4 ID in Avalon, will return a 500. Fedora 3 identifiers are in the format "avalon:#value"

### Examples
https://media.dlib.indiana.edu/media_objects/avalon:293820
https://spruce.dlib.indiana.edu/media_objects/avalon:2938

### Done Looks Like
- Requests with Fedora 3-style IDs for the media object route (as in example URLs) above redirect to the Avalon homepage with an "Item not found" message to the user

**Comment by SumithBaddam** [comment]
@joncameron can you provide a media object with this issue? It will help in understanding it better.

**Comment by joncameron** [comment]
@SumithBaddam Definitely, I've updated the issue with some examples and a more clear description.
