### ISSUE TITLE
Create Strategy for Cleaning Up After Local FFmpeg Encodes

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3576]
### Description
Transcoding using local FFmpeg will generate files during the process that need to be cleaned from the filesystem. The strategy for doing so, as well as the files needing to be cleaned up, need to be identified.

### Done Looks Like
- [ ] Write rake test to clean up metadata file artifacts from encoding

### Notes
- Within Docker, this may be mostly a non-issue
- Small files left behind will be progress info, technical metadata, etc.
- Work may need to be done in the adapter, in the context of other stories, to make sure derivatives go off to the correct place

**Comment by elynema** [comment]
Set default value of time before cleaning up files to 2 weeks.

**Comment by masaball** [comment]
Active Encode PR: https://github.com/samvera-labs/active_encode/pull/124

**Comment by elynema** [comment]
See pull request #5190 to bring in new version of Active Encode and create rake task in Avalon
