### ISSUE TITLE
Local FFmpeg Can Be Run Externally

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3578]
### Done Looks Like
- Avalon displays progress information from the active_encode database
- Avalon only persists transcoding information to Fedora when a job is completed/terminated (success or failure)
- Avalon uses watched_encode as the default encode class

### Notes
- To allow for horizontal scaling, and not just having one separate machine or container, and to stay 12 factor, we should have a worker container be only pushed to (create a new job, do work), and then it will write its output incrementally (poll the active_encode adapter) and write the snapshot to a database. The database is what is shared with Avalon. Avalon doesn't need to pull information directly from a storage volume on an external box/container.

The dashboard will be pulled from the database as well. Fedora will probably only get updated when processing terminates (regardless of exit status), rather than on each update. The masterfile will only get information when it's failed or completed. Right now Fedora is getting taxed by doing masterfile updates for each poll.

There should be a separate story for Docker, to use the code changes done in this issue.

**Comment by cjcolvar** [comment]
All of the done criteria were satisfied in #3651.  

One point worth discussing is that all of the encoding status information is only in the database now.  This means that if encoding has succeeded or failed is in the database.  Stored in fedora is the id of the encode (and its database record) and derivatives (if successful) or no derivatives (if cancelled or failed).

Can testing externally be a part of #3580?
