### ISSUE TITLE
Create a living Avalon Style Guide document

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3582]
### Description
Create a common resource for design decisions in the Avalon application, a living Style Guide which represents basic UI building blocks of the Avalon application (color hex values, fonts, page layouts, modals, etc.).  

The documented UI pieces can mostly be derived from Bootstrap.  The Style Guide can also be a point of reference to inform Bootstrap customization options in the application (`app/assets/stylesheets/branding.scss`).

This tool looks like it might be worth investigating?
Fabricator:  http://fbrctr.github.io

Or at the very least we come up with a .PDF file or .HTML page which acts as the actual style guide.

### Done Looks Like
- Basic style guide created
- Possibly committed alongside application code?
- Visually something like this:

![image.png](https://images.zenhubusercontent.com/5cc1c6928b624e26c373501c/fdea7eda-367a-44fa-a3ee-a0f3511f0051)

**Comment by joncameron** [comment]
Here's a nice one from Princeton: https://pulibrary.github.io/lux/docs

**Comment by adamjarling** [comment]
Here's a Ruby gem which might help for a living style guide?

https://github.com/trulia/hologram

**Comment by elynema** [comment]
Target user would be Avalon developers. Style guide for core Avalon styles, not IU styling / branding. Make sure to cover things like styling on error / warning messages and modals.
