### ISSUE TITLE
Use Neoload to load test the new demo box on AWS

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#3584]
### Descriptive summary

It would be good to determine the load limits of the new demo box (pawpaw on AWS). This can be done using IU's neoload load testing tool.

1. Concurrent users
2. Concurrent streaming sessions

**Comment by phuongdh** [comment]
Demo box
![image.png](https://images.zenhubusercontent.com/5cc1c79d0ce5f07dcc92eebd/7751b9ab-0ea8-4340-8b27-a0eb006d9b2f)

Pawpaw
![image.png](https://images.zenhubusercontent.com/5cc1c79d0ce5f07dcc92eebd/dadf6193-29af-4bb1-91f0-dfa201d835ee)

**Comment by phuongdh** [comment]
Demo box: t2.xlarge
Pawpaw: 16GB 4 cores

For 55 users browsing/playing, demo box managed to keep response time under 10s while pawpaw steadily climbed to 60s. Throughput is 20 times as much. 

We're requesting Neoload premium to test with even more users but the result looks very convincing.

**Comment by mcwhitaker** [comment]
[report-Oct-11-10_01.docx](https://github.com/avalonmediasystem/avalon/files/3719029/report-Oct-11-10_01.docx)

[errors.xlsx](https://github.com/avalonmediasystem/avalon/files/3719031/errors.xlsx)
