### ISSUE TITLE
Test FFmpeg, Pass through, and Elastic Transcode Adapters 

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3588]
### Description
Testing for the encoders in Avalon. Coordination will be required to make sure that testing is done separately for each adapter, i.e. Spruce is tested for FFmpeg and pass through adapters and Demo is used for Elastic Transcode.

### Done Looks Like
- Enumerate testing tasks listed below
- Run Avalon doing ingest, deletion, batch ingest, pre-transcoded derivatives in both UI and batch
- Looks at encode dashboard for both adapters to ensure proper information is returned/displayed
- Test with valid and invalid (broken) files
- Test with good and unusual (non-Western Unicode characters)
- Verify generated derivatives to make sure they're conforming to configured encode parameters

**Comment by cjcolvar** [comment]
Testing for FFmpeg and Skip Transcoding can be done on spruce or mallorn.
Testing for Elastic Transcoder can be done on demo.avalonmediasystem.org

**Comment by phuongdh** [comment]
Demo box test:
- Skip-transcoding doesn't work: known issue.
- File name with character `#` returns exception `Aws::S3::Errors::NotFound ()`. Works on Mallorn.
- File name with characters `+-` cannot stream. Works on Mallorn.
- File name with Vietnamese/Chinese chars returns error message: `The file you have uploaded has non-ASCII characters in its name.` Same on Mallorn
- Non-media file returns error message `The file was not recognized as audio or video - sample.zip (application/zip)`. Same on Mallorn.
- "Bad" media file ingested, can play audio but no video. Mallorn returns error `Too many packets buffered for output stream 0:1.` This is down to the difference between transcoders.

**Comment by cjcolvar** [comment]
@joncameron Do you think we could make a couple stories from @phuongdh 's testing and close this story?
1. Document what characters are not allowed in file names with elastic transcoder and ffmpeg.
2. Allow unicode characters in filenames
