### ISSUE TITLE
Collections Index

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3591]
### Description
Completing the bones of the collections index page.

### Done Looks Like
- Getting the collection poster images in
- Provide views for switching between "by unit" view and "a-z" view
- Create json endpoint for collections index

### MVP Punchlist - Remaining Work Discussed in Swarm
-  [x] Remove “Unit:” from the unit name
-  [ ] Normalize the poster image so it fits into a specific size
    - Current poster images are 700 w/l max (anything below is not upscaled)
    - anything below that won’t get upscaled
-  [x] Create and add placeholder image for collections with no poster image
-  [x] Applying Adam’s styling changes (merge into develop)
-  [x] Listing Filter box should be wider
-  [x] Higher contrast for toggle button

**Comment by joncameron** [comment]
### Description
Completing the collections index page.

### Done Looks Like
- Getting the collection poster images in
- Provide views for switching between "by unit" view and "a-z" view
- Create json endpoint for collections index

**Comment by cjcolvar** [comment]
I think we should make the poster standardization it's own story as Brian is working on it now. 
 A follow up bug that we should fix with Brian's work is that if you delete a poster, the collection json endpoint still thinks it has a poster and thus the collection index shows a broken image.

**Comment by joncameron** [comment]
Poster standardization broken out into #3627.
