### ISSUE TITLE
Discuss Policies for the Avalon Demo Instance

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3592]
### Description
How long will we retain content and user accounts? This question and other related to the administration of the new Pawpaw need to be answered to manage the instance smoothly.

### Done Looks Like
- Discussion is held in person or over email to clarify or establish policy
- This information is documented on the Avalon wiki

### Questions
- How long do we retain user accounts?
- How long do we retain content from users testing the system?
- How should authentication be done? Continue using CAS, or local accounts via Persona?

## Post-discussion Proposals
- Retain user accounts indefinitely
- Delete media objects 1 year after creation (except Avalon team content)
- Use Persona for auth
- Create a branch/fork for Demo so that explanatory/help text can be added to the site
- Wait until Avalon 7 release to publicly announce Demo and switch from Pawpaw/retire

**Comment by phuongdh** [comment]
https://github.com/avalonmediasystem/avalon/issues/2453#issuecomment-532848506

**Comment by joncameron** [comment]
### Notes
#### How long do we retain user accounts?
- Indefinitely. No need to flush user accounts according to a schedule.
#### How long do we retain content?
- Phuong doesn't care and notes that S3 is pretty cheap. May be a call made based on cost. Right now Pawpaw is at 200 GB. I propose retaining media objects for 1 year before deletion (except for Avalon team produced content)
#### When do we switch over to using Demo?
Pawpaw has been updated with each new tagged master release. We want Persona in Turnkey, as well as other tweaks, but these are still in the develop branch. I propose waiting until the release of Avalon 7 to retire Pawpaw and switch things over. This feels good from a marketing perspective too.
#### How will we do authentication?
Proposal: switch over to using Persona rather than IU CAS authentication. Since the usernames for guest accounts are email addresses, the transition for existing accounts should be fairly easy and could come with communication about the site change.
#### Demo site customization
I'd like to propose a new branch or fork of Avalon for the demo site. The addition of text on the homepage, sign in pages etc. that explain to new users about our demo site and how to use it will make it more inviting to users testing Avalon out.

**Comment by joncameron** [comment]
I'll bring this up for stakeholder review at the Avalon project management meeting on October 16th.
