### ISSUE TITLE
Expand on UI cleanup to allow for simple skinning/theming

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3603]
## Description

Now that we've cleaned up our UI, we should take another look at the CSS (and html) with an eye toward skinning/theming. Key areas of focus should be a well thought out set of SASS variables followin best practices and documentation for adopters

## Done looks like 
- [x] another pass at the CSS for cleanup and organization with new adopters in mind
- [x] some documentation written 

CC: @adamjarling

**Comment by cjcolvar** [comment]
@adamjarling Can this be moved to done or is there still more to do that isn't captured in other tickets?

**Comment by adamjarling** [comment]
Yea, this is done enough for now.
