### ISSUE TITLE
Contact Information on Collections Page

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3604]
### Description
As a collection manager, I want the  ability to provide contact information for a collection on the collections page so that users can find contact information or other

### Done Looks Like
New fields added to a Collection: 
  - Contact Email address
  - Website
These fields are optional (like description, not required). These are fields able to be edited in the same modal where name, description etc. is changed on the collection's admin page.

This information is rendered on the collection's landing page. We'll move the "Show more" text to the end of the cut-off text and put the email/url info where that is now.

#### Collection Edit Details Form
![Screen Shot 2020-04-21 at 10 31 10 AM](https://user-images.githubusercontent.com/1406618/79878717-bfe80b80-83bb-11ea-9ab9-12ebf755e5fe.png)

**Comment by joncameron** [comment]
Currently this information is stored in a Fedora object, so metadataists would probably want to weigh in for what predicates to use for them.

**Comment by cjcolvar** [comment]
We added the email and website fields to the collection model, but after discussion we decided that a label field should be added for the website url.  After this is added, we still need to display the contact info on the collection landing page.
Work branch is here: https://github.com/avalonmediasystem/avalon/tree/collection_contact

**Comment by Dananji** [comment]
Added code to display contact info in the collection landing page (Commit: https://github.com/avalonmediasystem/avalon/commit/fb839e3d217d9d826622946e9df2cd5bd9d0abfa)

**Comment by cjcolvar** [comment]
I tested and this is working as expected on spruce, but I'm going to leave this in QA until @jlhardes weighs in on the RDF predicates we're using to store the information.

**Comment by cjcolvar** [comment]
I talked with @joncameron and @jlhardes and I think the approach we'll take for now is to keep the website label but make it optional.  If it isn't supplied then the url (without protocol) will be displayed.  The label property will continue to have a custom rdf predicate but email and url will be switched to use schema.org's predicates.
