### ISSUE TITLE
Improve Analytics and SEO

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3616]
## Description
Avalon has had basic analytics integration for sometime. As an administrator I would like Avalon to have support for Google Tag Manager as well as have metadata in a dataLayer that can be piped into GTM.

## Done looks like
- GTM is configurable for Avalon (on all pages)
- A dataLayer is added to every page that has:
  * Title
  * Contributor
  * Collection
  * Unit
  * Subjects (array)
  * IsLoggedIn 
- A jsonLD blob is dropped in the page with schema.org mappings for 
  * Search
  * Title
  * Contributor
  * Description
  * Collection
  * Subjects (array)
- Avalon has a sitemap endpoint

**Comment by joncameron** [comment]
Are the approaches above platform agnostic? It appears so, but we could do a little more research to make sure it is. It looks like Matomo is very similar if not the same in approach.

**Comment by davidschober** [comment]
Matomo supports either ga style `dataLayer` or matamo-style `_mtm`  https://matomo.org/docs/tag-manager/#data-layer <https://matomo.org/docs/tag-manager/#data-layer>
