### ISSUE TITLE
UI enhancements - mobile/responsive

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3634]
### Description
Build on recent UI work in Avalon application to verify mobile/responsive layouts look correct and are readable on different viewport sizes.  Also cleanup mobile nav and header bar.

### Done Looks Like
- [ ] Entire site inspected and any issues fixed in layout.
- [ ] Fix mobile header display
- [ ] Update mobile nav to make sure it's clean and resembles same color scheme as primary navigation.

**Comment by adamjarling** [comment]
@joncameron @davidschober I think this could be ready once the Collections Landing page branch gets pushed to `develop`.

**Comment by davidschober** [comment]
Great! Should we pull it in to in progress? 

Related to #3736

**Comment by adamjarling** [comment]
How about "Current Sprint", then I'll grab it once the #3736 is merged.
