### ISSUE TITLE
XML Strings Lose Information

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3643]
### Description
Avalon strips certain non-alphanumeric characters from XML strings that should be retained. In particular, this results in text containing line breaks being mushed into long strings that don't look nice and are unexpected given the metadata input during record creation. This mainly affects the MODS XML document for descriptive metadata.

### Done Looks Like
- Line feeds, carriage returns, and tab characters are retained for string values in XML on the view page.

**Comment by davidschober** [comment]
@joncameron do you want to make this a high-priority bug?

**Comment by joncameron** [comment]
@davidschober Yeah, it would be very nice to have this in AV7 and it should be a small change.
