### ISSUE TITLE
Admin is unable to assign staff roles to any collection

### ISSUE THREAD

**Issue by SumithBaddam** [avalonmediasystem/avalon#3652]
**Summary:**
Server: demo.avalonmediasystem.org
Testing: Regression
Browsers: Chrome
Operating System: Windows10
Issue: Admin is not bale to assign any staff role to any of the collections.
ERROR: Unit is not included in the list

**Steps to reproduce the behavior:**
1. Login to Avalon system with admin level user credentials.
2. Click on “Manage Content” option.
3. Click on any collection from the table, it navigates to the collection details page.
4. Assign a Manager level user(user_mng)to the Manager/Editor/Depositor role.The system updates the collection details with this user.Note that if the Manager level user is added to an Editor role, he will automatically promoted to the Manager role.
5. Assign a collection staff user (user_a) to a Manager role, the system rejects as he is not in Manager group
6. Assign a collection staff user (user_b) to an Editor/Depositor role. The system updates the collection details with this user.

**Error:**
Unit is not included in the list is displaying on top after the trying to assigning roles.

**Comment by joncameron** [comment]
I wasn't able to reproduce this as 'archivist1'. Based on the error 'Unit is not included in the list' my guess is that controlled_vocabulary.yml was missing or the Unit value in question from the file when attempting to add the user.

**Comment by SumithBaddam** [comment]
@joncameron  This issue is only with the admin user. 'archivist1' is not an admin, he is a manager. When I try to add any user to any of the roles, manager, editor or depositor it is giving this error message. 
Users other than admin are able to add other users to those roles without any problem.

**Comment by joncameron** [comment]
@SumithBaddam Thanks for the correction, I completely missed that! I'm too used to 'archivist1' being an admin account.

**Comment by phuongdh** [comment]
Needed to mount `controlled_vocabulary.yml` because the one that comes with Docker image is overwritten often.
