### ISSUE TITLE
Setting Bibliographic ID to ‘3671440’ not importing data

### ISSUE THREAD

**Issue by SumithBaddam** [avalonmediasystem/avalon#3653]
**Summary:**
Server: demo.avalonmediasystem.org
Testing: Regression
Browsers: Chrome
Operating System: Windows10
Issue: While adding an item to a collection, setting the Bibliographic ID to ‘3671440’ is not importing data and auto populating it.

**Steps to reproduce this behavior:**
1. Login to Avalon system with collection staffuser credentials.
2. Click on “Manage Content” option.
3. Click on a collection (C1), it navigates to the collection’s home page.
4. Click on “Create Item” button. It open the “Manage file(s)” page.
5. Click on “Select file” button and upload a media object. Repeat this step for adding multiple media objects.
6. After uploading files click “Save and Continue”. It navigates to Resource description page.7Enter details manually in Resource Description page or SetBibliographic ID to ‘3671440’ and click import.

**Error:**
![image](https://user-images.githubusercontent.com/6374927/66411606-fe8b1b00-e9c1-11e9-9e13-ffd94481f785.png)

**Comment by joncameron** [comment]
Going to close this issue, as we'll purposefully not hook up a service to our demo instance to do bibimport.
