### ISSUE TITLE
After the end date has surpassed for special access assigned to a avalon user he is still able to access content

### ISSUE THREAD

**Issue by SumithBaddam** [avalonmediasystem/avalon#3654]
**Summary:**
Server: demo.avalonmediasystem.org
Testing: Regression
Browsers: Chrome
Operating System: Windows10
Issue: After the end date of special access assigned to a avalon user he is still able to access it.

**Steps to reproduce this behavior:**
1. Open two browser instances
         Browser-1:login to Avalon system with a user that has edit rights for an item.
         Browser-2:login to Avalon system with a normal avalon user.
2. In Browser-1, browse for a published item, and click on the item.
3. Click Edit button.
4. Enter avalon user in the “Avalon User” text area under “Assign special access”.
5. Enter the Begin Date and End Date to give access to the user with in these dates. (Give dates from the past. ex: end date - 10-04-2019)
6. Click on “Add” button at the end of that row to add this access entry to the system.
7. When tested, the user still has the access to the collection.

**Error:**
The user still has access to content even after the End Date has surpassed.

**Comment by joncameron** [comment]
Warrants investigation—hopefully a non-issue.

**Comment by cjcolvar** [comment]
I wasn't able to reproduce this on mallorn.  The initial report is for demobox so I can retest there once it has been updated to 7.0.

**Comment by Dananji** [comment]
I was able to reproduce this when the tested item's `Access Restrictions` says `This item is accessible by: collection staff, specific users`.
When the tested item is accessible by `logged in users and public`, the read-only user was able to see the item even though the lease has expired (in this case the user is part of the 2 categories).

I'm guessing this is the intended behavior for leases.
