### ISSUE TITLE
Share an item via LTI not available

### ISSUE THREAD

**Issue by SumithBaddam** [avalonmediasystem/avalon#3655]
**Summary**:
Server: demo.avalonmediasystem.org
Testing: Regression
Browsers: Chrome
Operating System: Windows10
Issue: Unable to see share an item via LTI option in the share resource tab.

**Steps to reproduce this behavior:**
1. Login to avalon
2. Browse for an item
3. Click on Share tab
4. Unable to notice share via LTI option

**Comment by joncameron** [comment]
I assume this is due to LTI not being configured for this instance.
