### ISSUE TITLE
Visual Structure Editor Writes Some Characters as HTML Entities

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3663]
### Description
When editing labels and spans in the structural metadata editor, certain usual suspects (&, >, etc.) are saved as their HTML entitity representation. This leads to an ampersand in the structural metadata editor showing up in the item view and XML editor as something like "Things `&amp;` Things", not "Things & Things".

### Environment
Spruce, Avalon 6.5 in IU Production, Firefox on macOS 10.15

### Steps to Reproduce
- In the Visual Structural Metadata editor, add an ampersand to a label or span
- Save the structure
- Go to the item view page or advanced XML editor
- The ampersand will display as &amp;

**Comment by Dananji** [comment]
I was able to fix this HTML character escaping in the visual editor, but this still shows up in the XML editor. I tried using a JavaScript fix (replacing the text area value), which did not work. Maybe there's a way to do this with a non-JS approach?

**Comment by Dananji** [comment]
XML editor cannot show the HTML entities as their respective characters, because it makes the XML invalid. Therefore, even if we save the text as HTML characters, they will be shown as HTML entities in the editor.

**Comment by joncameron** [comment]
@Dananji I'm still seeing this on Spruce: https://spruce.dlib.indiana.edu/media_objects/sj1392079/edit?step=structure 

The edit page shows me "&" in the preview, but on the item page it's displaying as "&amp;"
