### ISSUE TITLE
FfmpegAdapter does not handle filenames with spaces

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3670]
### Description
The ActiveEncode FFmpeg adapter does not currently work successfully when handling filenames containing spaces.

### Done Looks Like
- FfmpegAdapter handles filenames containing whitespace characters without error.

**Comment by joncameron** [comment]
@phuongdh Still present on Spruce: https://spruce.dlib.indiana.edu/encode_records/15

```Error Message: file:///tmp/Ben%20Savage%20-%20Eat%20Breakfast%20PSA.mp4: No such file or directory ```

I got the same result running develop locally.

**Comment by cjcolvar** [comment]
2nd PR to ActiveEncode was created (https://github.com/samvera-labs/active_encode/pull/64).  Once that is merged then we can create a PR to update avalon and retest on spruce.

**Comment by joncameron** [comment]
Looks fixed in ActiveEncode but there need to be Avalon changes to accommodate the same situation.

**Comment by cjcolvar** [comment]
Looks like issue now is that the outputs are missing a label:
```
[ActiveJob] [ActiveEncode::PollingJob] [f4ac7a3c-1b41-40ef-96a5-594776b6e717] Error performing ActiveEncode::PollingJob (Job ID: f4ac7a3c-1b41-40ef-96a5-594776b6e717) from Resque(default) in 311.12ms: NoMethodError (undefined method `sub' for nil:NilClass):
/srv/avalon/avalon_r6/releases/20191108151458/app/models/derivative.rb:103:in `from_output'
/srv/avalon/avalon_r6/releases/20191108151458/app/models/master_file.rb:329:in `block in update_derivatives'
/srv/avalon/avalon_r6/releases/20191108151458/app/models/master_file.rb:326:in `each'
/srv/avalon/avalon_r6/releases/20191108151458/app/models/master_file.rb:326:in `update_derivatives'
/srv/avalon/avalon_r6/releases/20191108151458/app/models/master_file.rb:321:in `update_progress_on_success!'
/srv/avalon/avalon_r6/releases/20191108151458/app/models/watched_encode.rb:32:in `block in <class:WatchedEncode>'
```
Not quite sure if this should be fixed in ActiveEncode or avalon.  I'll have to look at it more.
