### ISSUE TITLE
Failure during FfmpegAdapter#create isn't bubbling up

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3671]
### Description
Failures during the create method aren't being surfaced properly. 

### Done Looks Like
- Failures during FfmpegAdapter#create bubble up correctly

### Notes
Currently, not returning failure with a status message on the encode object. The encode object is passed back, but it doesn't have this information.

**Comment by cjcolvar** [comment]
I haven't been able to cause a failure during create on spruce, but good files and corrupt files are handled correctly on spruce.  I'm moving this to done then.
