### ISSUE TITLE
Waveform  generation causes a zombie process

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3672]
### Description
The cancel method isn't fully killing the ffmpeg process that has been started, and/or leaves a zombie process. This is (naturally!) not ideal.

### Done Looks Like
- FfmpegAdapter#cancel fully kills the ffmpeg process without leaving any lingering processes

**Comment by phuongdh** [comment]
Couldn't reproduce on Spruce: 
- Ingested a file
- Wait till processing is half way through
- Find running ffmpeg process: there is one
- Delete master file from item
- Find running ffmpeg process: there is none

**Comment by cjcolvar** [comment]
I tested again locally under docker and couldn't replicate this behavior either.

**Comment by cjcolvar** [comment]
Now that we moved the encode job create into a background job we have noticed that this has started happening again.

**Comment by cjcolvar** [comment]
Looks like the zombie is present on spruce. :(

**Comment by cjcolvar** [comment]
If we can't fix this right away then we can provide a workaround of restarting sidekiq often which would clean up the zombies.  Really really not good, but an option.
