### ISSUE TITLE
Overall progress not displaying on preview page, Progress not autoupdating on preview page

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3673]
### Description
Progress information is expected to be displayed on an item page, and to be automatically updated as the steps of the transcoding process move along. These are not currently happening.

### Done Looks Like
- Overall progress status displays on the item view page
- Progress information is automatically updated with the current status of the encode job

### Notes
Purely javascript on the page to retrieve and display this information.

**Comment by mcwhitaker** [comment]
@Dananji - wasn't this your question this morning?

**Comment by Dananji** [comment]
Yes, a part of this. Thanks!
