### ISSUE TITLE
Collections Landing Page - Continued Styling

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3674]
### Description
Styling changes according to notes taken in #3629

### Changes
- Temporarily get rid of faceting and evaluate looks
- Add a link "Filter this collection", and take right to the blacklight page
- Make the Unit name be bigger, and one headline size under page headline (so it looks more important).
-  Update the top UI to look kind of like this:
- @joncameron Possibly make the Collection image a square ratio, instead of 16:9? See below example...
- Make collection title to use page-title class instead of it's current h3.
- Make description copy Bootstrap "lead" copy.
- Lead copy description, cut off the text at 100 or so words, and give a "read more" link to show rest of text in accordion.

**Comment by adamjarling** [comment]
This work was completed in another issue(s)
