### ISSUE TITLE
Finish work on IIIF Prezi 3 Cookbook Recipes

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#3685]
## Description

We now have the Opera which we have permission to use in the cookbook recipes, so we should finish the work on the IIIF Prezi 3 cookbook recipes.

## Done looks like 
- [x] file is in S3 (make it available to Jon D and ask him to put it there)
- [x] Issues in IIIF github are updated

**Comment by cjcolvar** [comment]
Draft PR created: https://github.com/IIIF/cookbook-recipes/pull/110
