### ISSUE TITLE
Transcoding Dashboard UI

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3688]
### Description
Styling for the transcoding dashboard. The dashboard is now ported from Hyrax but has carried over the default styling. This should be refined so that it fits with our current styling for the application.

### Done Looks Like
- List of styling changes for the transcoding dashboard enumerated

**Comment by joncameron** [comment]
### Notes from Discussion
####  Styling Changes
- alternating row color or gridlines for table
- changing the sort icons (I like the DataTables website triangles, instead of our current up/down arrows)
- links to the encode job page should be easier to understand as hyperlinks (color scheme currently makes it difficult to see)
- show 25 records by default (make this 20 if possible), reverse sorted by default so newest jobs show first
- dynamic progress should be shown
- change the progress bar color? red when failed, etc.

#### Notes
- "job started" string represents the searchable database value, which is why it looks odd

**Comment by bkeese** [comment]
Here is the datatables event that can be used to help setup dynamic updates for progress bars:
https://datatables.net/reference/event/draw

**Comment by bkeese** [comment]
NOTE: Changes to default sorting and per page options will not be immediately visible. This is because we cache previously chosen options. To see the defaults, one needs to open an incognito window or to clear their cache.

**Comment by joncameron** [comment]
This looks amazing! I'm super happy with how this has turned out. My thoughts:

- Possibly change the title of the page to "Encoding Dashboard"—this might be more familiar to users and is the language used in the nav bar. 
- TBD

**Comment by cjcolvar** [comment]
Things are looking better after #3757 but I'm seeing a few things on spruce that could be cleaned up:
- Failed encodes are showing as green instead of red
- In progress show blue but don't turn to green when they move to complete dynamically before a page refresh
- The stripes should probably be removed for completed encodes
