### ISSUE TITLE
Avalon 7 Release

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3691]
### Description
Releasing Avalon 7.0.

#### Application Testing
- [x] Performance testing
- [x] Standard regression testing

#### Code Changes
- [x] Update version in code
- [x] Update license headers in files
- [x] Tag dependency repos
- [x] Update gemfile to point to those tags
- [x] Merge staging into master
- [x] Hit the release button in Github
- [x] Create tag for v7.0 (should already happen with hitting release button)
- [x] Recreate staging and develop branches by force pushing master to them

#### Documentation
- [x] Upgrade Instructions on Wiki
- [x] Update Known Issues
- - [x] Add newly reported (post 6.5 release) issues to Known Issues page
- [x] Update version numbers on Wiki to refer to 7.0 

#### Marketing and Outreach
- [x] Write a draft of release notes on Github (some items currently in a draft)
- [x] Publish release on Github https://github.com/avalonmediasystem/avalon/releases
- [x] Update wiki with release notes
- [x] Inform interested parties of code release before full public release
- [x] Publish blog post announcing the release
- [x] Update homepage with blog post for release announcement
- [x] Update website with demo box changes
- [x]  with announcement and any other website pages with references to 6.5
- [x] Put announcement on Twitter
- [x] Put announcement on Facebook
- [x] Send out email to Samvera community mailing list
- [x] Publicize in appropriate Slack channels

**Comment by cjcolvar** [comment]
@phuongdh Do we need to rebuild and tag our docker container in dockerhub as 7.0?
