### ISSUE TITLE
IIIF presentation homepage property should be an array

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3695]
When testing our manifest with the presentation 3.0 validator I discovered that the homepage property should be an array when we have it as a single object.  We should update this in Avalon (and avalon-bundle).  We should make sure that anything that uses homepage is updated as well (maybe timeliner).

**Comment by joncameron** [comment]
Covered by #4705?

**Comment by cjcolvar** [comment]
@masaball I forget was your fix just for timelines or did it cover all IIIF manifest generation?

**Comment by masaball** [comment]
My fix was just for timeliner, but you had already fixed it for the main app with PR #4536 so I think we are good on this issue unless there are more places you're aware of that we need to check.
