### ISSUE TITLE
Implement Collection Landing Page work

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3702]
### Description
Implement work started a month ago in issue... #3630 

### Done Looks Like / Tasks

- Temporarily get rid of faceting
- Add a link "Filter this collection", and take right to the blacklight page
- Make the Unit name be bigger, and one headline size under page headline (so it looks more important).
- Update the top UI to look kind of like this:
- @joncameron Possibly make the Collection image a square ratio, instead of 16:9? See below example...
- Make collection title to use page-title class instead of it's current h3.
- Make description copy Bootstrap "lead" copy.
- Lead copy description, cut off the text at 100 or so words, and give a "read more" link to show rest of text in accordion.

![image](https://user-images.githubusercontent.com/3020266/68314433-c5ef6780-007b-11ea-8acf-a79905e9f27b.png)

@joncameron

**Comment by Dananji** [comment]
@joncameron I have a quick question: was the decision to remove the filters in landing page made, because they move after we open the filters list? If so, I have a fix for that. 

If not and we need to get rid of facets in this page for now, let's make the changes requested in this ticket.

**Comment by joncameron** [comment]
@Dananji That was about their usefulness and not the weird opening thing that was happening. After some consideration it didn't seem like they would be useful enough to retain on this particular page. Thanks for checking in!

**Comment by cjcolvar** [comment]
Looks good overall!
I see a few things that might need fixing when testing on spruce:
- Sometimes card contents overflow their cards
- Maybe 9 or 12 cards per page would be more natural than 10
- Turn off field drop-down autocomplete on search field
- Maybe we could put a slight delay on the search so it isn't so quick changing
- Maybe add a spinning wheel to indicate when it is searching?

**Comment by adamjarling** [comment]
@cjcolvar @davidschober @joncameron  Agreed on all.  I'll create a clean-up issue to address the bullet points above.

**Comment by cjcolvar** [comment]
I'm moving this to done now that #3755 exists.
