### ISSUE TITLE
Search Bar missing on Android/Chrome

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#3715]
Search bar is missing on Android/Chrome.

Seen on spruce.

Galaxy S8
Android 9
Chrome 78

**Comment by cjcolvar** [comment]
Looks like for any small screen size and not just mobile.  The search bar used to be beneath sign in/sign out in the global navigation hamburger drop-down, but now doesn't appear on the page anywhere for small screen sizes.
