### ISSUE TITLE
Try ECS Instead of docker-compose

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3723]
### Description
For scalability purposes, Phuong would like to try using ECS. This might deliver a way that's more scalable but not too costly.

### Done Looks Like
- Instead of EC2, try using ECS (for horizontal scalability)
- Compare costs and performance
- Update documentation if this turns out to be the desired direction

**Comment by phuongdh** [comment]
Solution: use a Dns Resolver as Faraday middleware. Thanks @cjcolvar for the help
