### ISSUE TITLE
Investigate Handling of Pre-transcoded Derivatives

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3724]
### Description
Pre-transcoded derivatives have not yet been looked at/implemented in the UI or batch processes for the new transcoding work. 

### Done Looks Like
- Figure out a plan for this work
- Decide strategy for handling this (in ActiveEncode, or Avalon?)

**Comment by cjcolvar** [comment]
In order for skip-transcoded files to flow through the system in the same way as normally processed files including appearing in the encode dashboard, we decided to create a pass-through adapter.  It will echo what was passed to it back as outputs with technical metadata added.  It may also move the files to where the streaming server expects them.

New story created: https://github.com/avalonmediasystem/avalon/issues/3746
