### ISSUE TITLE
Avalon Docker Stack - Minio Support and Deployment/Smoke Testing

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3737]
### Description
Minio has been decided to be the filesystem used in the Avalon Docker stack. This work needs to be completed, and the full container-based stack tested before release.

### Done Looks Like
- A Minio-based container is used 
- The avalon-docker stack is deployed to the IU Enterprise Docker sandbox
- Smoke-testing completed for the running stack in the Docker sandbox

we need a story for the above, to deploy and smoke test. This could be a 5, and include finishing minio work. All that these stacks need is a smoke test.

**Comment by phuongdh** [comment]
I deployed a distributed Minio using 4 Swarm nodes (on https://labs.play-with-docker.com/). It seems to provide redundancy: all files remain accessible after taking down 3 nodes. Only caveat is the workers have their own volume that's not interchangeable so each needs to always stick to a specific node.

**Comment by phuongdh** [comment]
Fedora does not seem to work with Minio even though Modeshape does have support for non-AWS endpoint: https://github.com/ModeShape/modeshape/blob/5.4.x/modeshape-jcr/src/main/java/org/modeshape/jcr/value/binary/S3BinaryStore.java#L99-L100

I set endpoint in Fedora to http://minio:9000. Upon creating a collection, Avalon returns Ldp::HttpError (STATUS: 405 ...). No error found in Fedora log.

**Comment by cjcolvar** [comment]
@phuongdh With these findings can this story be closed?

**Comment by phuongdh** [comment]
> @phuongdh With these findings can this story be closed?

I want to dig a little deeper before concluding. Btw, the "Done looks like" may need revisiting or fleshing out a bit more.

**Comment by cjcolvar** [comment]
@joncameron Can we close this ticket?
