### ISSUE TITLE
Build Docker image with new tag in CircleCI

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3743]
When Avalon needs to install a system gem, the Docker image needs to be rebuilt because it (intentionally) lacks the tools to build system gem on init. Whenever this happens, we need to use a new tag for our dev image and let CircleCI build/push it.

**Comment by joncameron** [comment]
This is only for development purposes; a nice to have.

**Comment by joncameron** [comment]
Closing; will reopen or recreate if we need this.
