### ISSUE TITLE
Avalon 7 Release - Documentation

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3745]
### Description
This is a catch-all ticket for documentation that needs to be written for the Avalon 7.0 release.

### Done Looks Like
- All pages that need to be updated or added are compiled in a list of key changes

#### Includes
- Upgrade instruction
- Manual install for CentOS 7 (?) (Louisville had problem with Tomcat version)
- API Key changes
- Transcoding changes
- UI Changes (how to customize, how to keep old homepage, etc.)
etc
- Note that latest Wowza release does not work with Avalon (known issues)

**Comment by cjcolvar** [comment]
Adding to the list:
- Sidekiq
- Docker
- Minio (for docker)

**Comment by phuongdh** [comment]
https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+6.5+to+Avalon+7.0

**Comment by cjcolvar** [comment]
Pages to could use warnings or cleanup:
https://wiki.dlib.indiana.edu/display/VarVideo/Installing+Avalon+on+a+Server+Using+Docker
https://wiki.dlib.indiana.edu/display/VarVideo/Manual+Installation+of+Avalon+Using+Puppet
https://wiki.dlib.indiana.edu/display/VarVideo/Vagrant+Virtual+Machine+-+Upgrading+Avalon+1.0+to+Avalon+2.0
https://wiki.dlib.indiana.edu/pages/viewpage.action?pageId=515277053
https://wiki.dlib.indiana.edu/display/VarVideo/Install+Sample+Content+Via+Command+Line
Maybe https://wiki.dlib.indiana.edu/display/VarVideo/Manual+Installation+of+Avalon+Using+Puppet

**Comment by cjcolvar** [comment]
- [ ] Write narrative of transcoding changes.
- [ ] Go through Known Issues and verify/remove/add.

**Comment by phuongdh** [comment]
Transcoding narrative:
- We finally transitioned from Matterhorn to a self-managed transcoding process. Using the latest version of `active-encode` and the ffmpeg adapter, this allows for a faster, leaner and more flexible pipeline. The new transcoding dashboard lets administrators manage transcoding jobs from inside Avalon. The performant and feature-rich Sidekiq replaces Resque as our default worker. It is now possible to use [minio object store](https:/min.io) to decouple Avalon, Worker and Streaming service from each other.

**Comment by cjcolvar** [comment]
How about:
>With this release of Avalon, the transition from Matterhorn to a self-managed transcoding process has been completed. Using the latest version of active-encode and the ffmpeg adapter, this allows for a faster, leaner, and more flexible pipeline. The new transcoding dashboard lets administrators manage transcoding jobs from inside Avalon. Amazon's elastic transcoder is still supported but Matterhorn is no longer supported.
>
>The performant, feature-rich, and better maintained Sidekiq replaces Resque as our default background job engine. This aligns with Hyrax and most Samvera applications which made the switch before.
>
>It is now possible to use minio object store to avoid a shared storage requirement and decouple Avalon, Worker, and Streaming services from each other in alignment with 12 factor best practices.

**Comment by phuongdh** [comment]
Sounds good.
