### ISSUE TITLE
Inconsistent Click Behavior on Access Control Area

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3748]
### Description
On the item access control page (and for collection access control), clicking the text beside the checkbox registers as a click for that element, while clicking the text besides a radio button element below does not.

#### Environment
Avalon 6.5 in IU prod, Spruce

### Example
![Oct-04-2019 09-42-09](https://user-images.githubusercontent.com/1406618/69186014-c6f5af80-0ae5-11ea-8819-af6e9e7939e1.gif)

### Done Looks Like
- Clicking text beside a radio button selects that radio button in the Item Access area.

**Comment by joncameron** [comment]
PR for collection access control makes clear what can be done to fix this.

**Comment by SumithBaddam** [comment]
Tested this issue and it has been fixed. So closing it.
