### ISSUE TITLE
Move Search Field to Main Background Image on Homepage

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3754]
### Description
On the new Avalon homepage, move the search bar down into the central image as shown in the mockup, instead of the header where it currently lives. This will only affect the homepage; the search bar will be centered in the header on all other pages.

Note: The audio/video search toggle icons as seen in the mockup will not be implemented; the search bar will be visually and functionally identical to how it is currently.

### Done Looks Like
- Search bar on homepage moved to the center of the image on the homepage, as per the mockup below

![avalon-homepage-draft-1](https://user-images.githubusercontent.com/3020266/65781857-0de0ad80-e112-11e9-8033-c25d686779cd.png)

**Comment by adamjarling** [comment]
@cjcolvar So with the new `app/views/catalog/index.html.erb` file, search is broken.  It tries to re-load the new homepage.  What's the easiest way to handle this?
