### ISSUE TITLE
Collections landing page tighten up

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#3755]
### Description
Based on the work implementing #3702 , there's some additional tightening up needed & noticed when testing on Spruce.  

From @cjcolvar 
- Sometimes card contents overflow their cards
- Maybe 9 or 12 cards per page would be more natural than 10
- Turn off field drop-down autocomplete on search field
- Maybe we could put a slight delay on the search so it isn't so quick changing
- Maybe add a spinning wheel to indicate when it is searching?

### Done Looks Like
- Ensure no card content overflows their cards
- Make total card display flow naturally with Bootstrap grid conventions (9 or 12 instead of 10)
- Turn off field drop-down autocomplete on search field
- Add a `debounce` delay to search text user input
- Add a progress indicator for search results to indicate an active search

### Tasks
(see above)
- [ ] All complete

**Comment by adamjarling** [comment]
The Collection "cards" are constructed with the assumption all collection featured images will be the same size.  Noticed this on Spruce:

![image](https://user-images.githubusercontent.com/3020266/69344344-db948d80-0c34-11ea-964b-cb5987c9c394.png)

@joncameron @cjcolvar  Should we code around the possibility these images might have different dimensions, or will this be addressed for the 7 release?

**Comment by mcwhitaker** [comment]
@adamjarling The images with the different ratio were added before the ideal ratio was chosen. They will all be the same ratio.

**Comment by joncameron** [comment]
@adamjarling This will change to a specific, final size. The dimensions that get fed into cropperjs have changed a couple of times, so as posters got made on spruce they ended up in different dimensions. Changing the size was a decision that I overlooked adding to a ticket, but I'll make sure to get that in. As Maria just noted, in a real instance they should all be the same.

^^ @mcwhitaker beat me to it!

**Comment by joncameron** [comment]
@adamjarling Let's go with 12 as the final number for the total card display flow instead of 9 or 10.

**Comment by cjcolvar** [comment]
I tested on spruce and things look better and I'm not sure if the browser-supplied search field dropdown is really something we should deal with.  I'm seeing a few things that could still be cleaned up:
- Collection description text is a larger font size now
- Maybe the Next and Previous links shouldn't be subject to the 1s debounce wait? Or maybe a shorter wait?
- ~Card contents don't overflow anymore but are truncated instead.  We probably need to figure out how to ensure the contents stay within the card without being truncated.~ Maybe this is just an issue with a mis-sized thumbnail which will get fixed when we fix #3756

**Comment by adamjarling** [comment]
@cjcolvar 

> I tested on spruce and things look better and I'm not sure if the browser-supplied search field dropdown is really something we should deal with. I'm seeing a few things that could still be cleaned up:

Agreed, I don't think it's worth messing with browser-supplied things (like search dropdown), at least at the moment.

> 
> Collection description text is a larger font size now

Is this referring to this description text?  If so, it's the same size as before, but I can take it down if you want.

![image](https://user-images.githubusercontent.com/3020266/69434217-cd14a780-0d02-11ea-84d7-1365867e313a.png)


> Maybe the Next and Previous links shouldn't be subject to the 1s debounce wait? Or maybe a shorter wait?

Good catch, they shouldn't.  I'll fix this.

> Card contents don't overflow anymore but are truncated instead. We probably need to figure out how to ensure the contents stay within the card without being truncated. Maybe this is just an issue with a mis-sized thumbnail which will get fixed when we fix #3756 

Ah, I put an `overflow: hidden` on the `Card` component in Collection Listing, but it didn't carry over to the Collection landing page cards.  I'll cap this as well.
