### ISSUE TITLE
Horizontal Scroll Always Present on Homepage

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3787]
### Description
Regardless of the viewport size, there is always a horizontal scroll bar present for the homepage. It seems like there's some extra padding or other weirdness causing a little bit of scrollability when there shouldn't be.

### Example
![Dec-05-2019 09-01-36](https://user-images.githubusercontent.com/1406618/70241928-e6bfe100-173d-11ea-8ba9-5a644cf0d979.gif)

### Done Looks Like 
- No horizontal scroll appears on the Avalon homepage

**Comment by Dananji** [comment]
The horizontal scroll bar is introduced by the featured collection section of the page. This might get automatically fixed by #3812.

**Comment by Dananji** [comment]
Fixed by #3812
