### ISSUE TITLE
Import from Dropbox Shows All Collections

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3788]
### Description
After clicking the 'Open Dropbox' button while creating an item, the file picker windows shows the Avalon's dropbox root path listing all collections, rather than the collection that the user is currently creating an item in.

### Example
![Dec-05-2019 09-06-29](https://user-images.githubusercontent.com/1406618/70242415-cc3a3780-173e-11ea-94f7-c3e2423e19aa.gif)

### Done Looks Like
Opening the dropbox file picker only shows the directory for the collection an item is being created within.

**Comment by cjcolvar** [comment]
This looks like the initializer that monkey patches browse_everything with this avalon specific functionality just isn't running for some reason.

**Comment by cjcolvar** [comment]
This appears to be working fine on mallorn.  I'll check spruce's configuration again to see if that might be the issue.

**Comment by cjcolvar** [comment]
I don't see any difference in configs.  My local docker setup is having this issue as well.  I'll debug it locally.
