### ISSUE TITLE
Avalon 7 Regression Testing

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3789]
### Description
Full regression testing, using our testing scripts, for functionality checking and bug finding before release.  

### Done Looks Like
- [x] Regression testing on Spruce on current develop (mostly done; things yet to be done listed below)

#### Outstanding Regression Tests
- [ ] LTI

**Comment by phuongdh** [comment]
Edit Structure UI problem when window size is smaller (than medium?)
![image](https://user-images.githubusercontent.com/1304657/70822424-8408be00-1dab-11ea-83c4-72b97f9ecbce.png)

**Comment by SumithBaddam** [comment]
I think this is re-sizing issue because it works fine when I open it on monitor (larger screen) and shows up like this when I open it on my laptop.

> Edit Structure UI problem when window size is smaller (than medium?)
> ![image](https://user-images.githubusercontent.com/1304657/70822424-8408be00-1dab-11ea-83c4-72b97f9ecbce.png)
