### ISSUE TITLE
Fix wowza-avalon module for Wowza 4.7.8

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3799]
Problem is described here https://github.com/avalonmediasystem/avalon/issues/3708#issuecomment-562308079

The fix shouldn't break 4.7.5

**Comment by joncameron** [comment]
Not sure if this is a thing still or not; we should check to see what our current Wowza is in production.

**Comment by cjcolvar** [comment]
This is still relevant.  At IU we're still using wowza 4.7.5 and the latest version is 4.8.20.

**Comment by elynema** [comment]
Current latest release of Wowza is 4.8.28. We saw some performance issues this past week with the m3u8 coming out of Wowza; Chris suggested that we might want to come back to doing this work for the 8.0 release.

**Comment by joncameron** [comment]
Created new issue #6058 to upgrade Wowza, instead of the specific issue captured here in this very old ticket.
