### ISSUE TITLE
Manage Users Page Returns Error

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3811]
### Description
The Manage Users page is inaccessible; attempts to hit the route return the following error:
![Screen Shot 2019-12-06 at 12.02.15 PM.png](https://images.zenhubusercontent.com/5cc1c0106d0be2229caf2d9e/fd2a52de-200d-4280-8c45-9fe157a4f233)

### Done Looks Like
- Code error resolved so Manage Users returns and renders as normal.

**Comment by bkeese** [comment]
Redundant. Same as #3791
