### ISSUE TITLE
Restrict Width of Featured Collection Div

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3812]
### Description
The featured collection section of the homepage is full width, which ends up looking poorly aligned on larger viewports:

![Screen Shot 2019-12-06 at 12 08 38 PM](https://user-images.githubusercontent.com/1406618/70341570-3cb98500-1821-11ea-8858-c272b07e6051.png)

### Done Looks Like
- Set the 'featured collection section to centered fixed width column; leave the rest as is.

**Comment by adamjarling** [comment]
@joncameron @davidschober  Just confirming this is the way the page will look with the change suggested in this issue.  Better than current?

![image](https://user-images.githubusercontent.com/3020266/70344271-e9463780-181e-11ea-81b3-a02d7de6b080.png)

**Comment by mcwhitaker** [comment]
Will the carousel also be centered fixed width? Should everything be centered fixed width? I am not sure what that would do for responsiveness...

**Comment by adamjarling** [comment]
We could make the carousel be "contained" as well.  It might add some balance to the page leaving it full-width though?    Part of me thinks constraining the Featured Collection within a container is not any better than what it currently is?   I can make it however people think though... a quick fix either way, on both sections.

**Comment by mcwhitaker** [comment]
I agree that containing the Featured Collection does not make it better. I don't know what solution there might be...

**Comment by joncameron** [comment]
I emailed Matt to see if he has guidance on how to implement this. I'll update the ticket when he responds.

**Comment by joncameron** [comment]
Image from Matt:
![left](https://user-images.githubusercontent.com/1406618/70574623-87fdcb80-1b72-11ea-94a2-8b52d41bdd88.png)
Let's go with this for now.

**Comment by adamjarling** [comment]
Ok, I think I get it.  So the text content just stays with the image?  I'll fix it up.
