### ISSUE TITLE
Login Redirects to JSON Response

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3825]
### Description
Somtimes after a user logs in, they're redirected to a JSON response rather than to their intended landing location in the app.

### To Reproduce
- ?

**Comment by joncameron** [comment]
Duplicate of #3826

**Comment by cjcolvar** [comment]
I think these are two different issues so I'm reopening this issue.

**Comment by cjcolvar** [comment]
It would be nice if we could find repeatable steps to reproduce this.

**Comment by cjcolvar** [comment]
This was maybe fixed by the change to send no-cache headers on xhr requests.  I'm going to close it and if we see it again then we can recreate or reopen this issue.

**Comment by cjcolvar** [comment]
I am seeing this pretty consistently when logging in from the home page using persona email auth instead of omiauth-identity.
