### ISSUE TITLE
Demo box bugs with Avalon 7.0

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3842]
- [x] No player is shown after ingestion completes
- [x] Items shown in search even though user doesn't have access (gated discovery) - known issue, fix later
- [x] Skip-transcoding doesn't work (it never did on AWS) - fix later

**Comment by cjcolvar** [comment]
I did more testing and the gated discovery issue is the same as a long-standing known issue (which I'm having problems finding): unpublished items that are accessible to a manager of a totally different collection can still be discovered before publishing.

**Comment by cjcolvar** [comment]
Per discussion on slack we're tabling skip transcoding on turnkey/cloud since it has never worked.

**Comment by mcwhitaker** [comment]
@joncameron Could we maybe have tickets for these two known issues that we are deciding to fix later?

**Comment by joncameron** [comment]
#3890 and #3882 are the issues created for these two.
