### ISSUE TITLE
CSS issues in production mode

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3845]
I'm guessing there are other places this is happening but here is one example:

Production:
![Screen Shot 2019-12-12 at 3.31.49 PM.png](https://images.zenhubusercontent.com/5cc1d44fd0d0bb24e5be43b4/2bc7d584-2d7d-439a-8d87-9ada977e71e6)

Development:
![Screen Shot 2019-12-12 at 3.32.21 PM.png](https://images.zenhubusercontent.com/5cc1d44fd0d0bb24e5be43b4/8c5bb96b-7c0c-40a7-82b0-67f95acd62fc)

**Comment by phuongdh** [comment]
More squished UI

![image.png](https://images.zenhubusercontent.com/5cc1c79d0ce5f07dcc92eebd/cbc4a0f0-362d-4cca-9076-36ec9d413654)

**Comment by adamjarling** [comment]
On Mallorn, for example the `panel-heading` style gets an extra style definition from somewhere...

![image](https://user-images.githubusercontent.com/3020266/70749646-662b5280-1cf2-11ea-9872-de56a50e1e28.png)

Not on Spruce...

![image](https://user-images.githubusercontent.com/3020266/70749736-9246d380-1cf2-11ea-9a59-1d8da672241e.png)

It's maybe either coming straight in from Bootstrap, or Blacklight?   Nothing else would be introducing Bootstrap.

@cjcolvar Are the compilation settings different in a Rails app for dev vs. production?

**Comment by adamjarling** [comment]
The culprit is `/app/javascript/components/collections/Collection.scss`.

**Comment by bkeese** [comment]
I don't know how the packaging works. Maybe the css load order is not deterministic?

**Comment by adamjarling** [comment]
Typically `webpack` will keep local scope on variable names in CSS/Sass files it compiles, I think.  But doesn't seem to be the case when compiling for production.  I'm going to push up a quick fix and see if it helps?
