### ISSUE TITLE
SME crashes if invalid timespan exists

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3852]
Steps to reproduce:
1. Open https://mallorn.dlib.indiana.edu/media_objects/s7526c524/edit?step=structure and open SME
2. Click pencil edit button on final segment

@Dananji analyzed:
>Because the start/end times are not valid for Wash Hands (00:02:00.000 - 00:02:00.000)timespan the segments don't get added to Peaks at the time of first load. So when we edit any timespan, Peaks breaks because it has no segments to update. This results in SME crashing. This is what I think is happening.

**Comment by joncameron** [comment]
One possible quick fix: putting in an error boundary to prevent hard crashes (except for network problems).
