### ISSUE TITLE
EDTF link taking to "Page not found"

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#3861]
The link on the Resource Description page for the help with dates is taking use to a "page not found":

![image.png](https://images.zenhubusercontent.com/5cc0b4aeef180a2079276838/1b100712-9a2a-4a53-b05d-f7c3e8028129)

A valid link is this one: https://www.loc.gov/standards/datetime/

This version is recent (Feb 4th, 2019), so I am not sure if the spec has changed since our implementation and if we need to review. @joncameron

**Comment by joncameron** [comment]
Related: #3861
