### ISSUE TITLE
Valid EDTF Level 1 Dates Are Not Allowed

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3867]
### Description
The help text for dates on the resource description form notes that Avalon accepts values according to the EDTF Level 1 spec. This currently isn't the case; valid values used as examples in the spec throw an error when attempting to save the form.

### Example
<img width="1014" alt="Screen Shot 2019-12-16 at 1 37 32 PM" src="https://user-images.githubusercontent.com/1406618/70933258-9f710480-2009-11ea-815a-7072f354d12b.png">

### Environment
Current development (Spruce).

### Notes
- Which forms of EDTF should we be accepting? (Full Level 1.0, current finalized spec)
- What should we do about EDTF values already put in that are in the format from the draft spec? (20uu vs. 20XX)
- Talk to Julie about the above, and how to handle these values
- We currently use edtf-ruby to validate the EDTF values

**Comment by cjcolvar** [comment]
Here's what we're testing for right now: https://github.com/avalonmediasystem/avalon/blob/master/spec/models/media_object_spec.rb#L54-L107

Here's the gem that we use: https://github.com/inukshuk/edtf-ruby

**Comment by joncameron** [comment]
If the gem is updated, we can use the final spec rather than the draft spec. But existing values using the draft spec DON'T require migration.

**Comment by joncameron** [comment]
Duke has a gem that adds a transformation to the EDTF value to make it human-readable that could also be worth exploring.

**Comment by masaball** [comment]
The potential update can be found here: https://github.com/masaball/edtf-ruby/tree/edtf-spec-compliance

**Comment by masaball** [comment]
Updated a couple things and I think this is now ready for proper review. New diff: https://github.com/inukshuk/edtf-ruby/compare/master...masaball:edtf-ruby:edtf-spec-compliance

**Comment by masaball** [comment]
The changes were accepted and the gem has been updated.
