### ISSUE TITLE
Playlists, Timelines, Encode Dashboard horizontal scrolling in mobile view

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#3871]
### Description

On mobile view, Playlists, Timelines, and Encode Dashboard tables are scrollable horizontally. This applies to the entire page not just the table, and it looks as follows;

![Screenshot from 2019-12-17 09-56-58.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/a7ff0f39-5fa7-4f5f-a3d5-89d1dcbcaac4)

### Done Looks Like

Only the table is scrollable, so that the external content on the page like the `Search` field and `Create New Playlist` button always stay on screen.

**Comment by joncameron** [comment]
A worthwhile task would be to look at tables across the application and make sure styling etc. is consistent. But that's a bigger approach!

**Comment by Dananji** [comment]
Playlists in MCO,

![IMG_5796.PNG](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/aa6f6168-f3d2-4509-9538-81a5d841b5af)
