### ISSUE TITLE
Accessible unpublished items are discoverable by any manager

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3882]
### Description
If an item is visible (by way of item access controls, for example set to public access) by a non-owning manager but unpublished they can discover it in search results, but are not able to view it.  This is an issue with our solr search query and is a longstanding issue.

### Done Looks Like
Non-owning managers should not be able to see the item in the search results.

**Comment by mcwhitaker** [comment]
@joncameron  - does this affect the secret collection?

**Comment by masaball** [comment]
Is this still an issue? I have not been able to replicate the described behavior on my local instance.

**Comment by cjcolvar** [comment]
I wasn't able to reproduce this either on avalon-dev so I'm going to close it.
