### ISSUE TITLE
Skip Transcoding Not Working in Turnkey/Cloud 

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3890]
### Description
Skip transcoding does not work in our turnkey/cloud deployment solution for Avalon. This is a long-standing issue and should be resolved so our turnkey solution can have full functional parity.

### Done Looks Like
- Skip transcoding is functional in Avalon Turnkey

**Comment by phuongdh** [comment]
Not working, `Tempfile` is being removed before we have a chance to inspect it
