### ISSUE TITLE
Submit Stack Level Too Deep Fix to ActiveFedora

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3894]
### Description
ActiveFedora was monkey-patched in Avalon to resolve a 'stack level too deep' error. This fix should be pushed back upstream.

### Done Looks Like
- Upstream PR submitted for ActiveFedora fix.

**Comment by cjcolvar** [comment]
I'm abandoning this since AF's upgrade to support rails 6 dropped the approach we took. (https://github.com/samvera/active_fedora/pull/1403/commits/60ad34d1fb8814d9ed9219e489428fe80b9b7b76)  We'll need to reevaluate our workaround when we move to upgrade to rails 6.
