### ISSUE TITLE
Avalon 7 LTI Testing

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3896]
### Description
LTI testing needs to be done for Avalon 7 as part of regression testing. This is a separate issue due to the extra steps needed to fully test for us right now.

### Done Looks Like
- Avalon 7 code is deployed to a test instance that is configured with LTI
- Testing is done with sampling of Avalon's supported browsers and platforms
- Testing is done with Safari specifically, as there have been idiosyncratic issues with it and LTI in the past

**Comment by cjcolvar** [comment]
I'm leaving this in QA right now because I'd like to test on the latest safari to see if the behavior is different from MCO.
