### ISSUE TITLE
File upload throws an error when selected file is cleared/removed

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#3899]
### Description

On demo.avalonmediasystem.org, when ingesting a new file;

When the user clears the selected file while it is being uploaded an error (500: Internal Server Error) is thrown after the upload is finished.

Steps to recreate:
1. Go to file upload step of editing an item process / Create a new item
2. Select a file (medium - large in size, so it takes sometime to upload) from file explorer
3. Click on `Upload` button and observe the progress bar moving
4. Click on the selected file name, which will  open up the file explorer again
5. Click `Cancel` or press `Esc` button
6. Observe the file upload field is cleared and the progress bar still filling up
![Screenshot from 2019-12-20 16-18-32.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/100368ea-bbb4-4a3b-bae2-26df50102aba)
7. After upload is finished an error is shown, `Something went wrong....`

- [ ] Same thing happens when a file is removed while it is being uploaded. While the `Remove` button clears the file from the file upload UI, the progress bar keeps showing the file upload. When it is finished the same error is thrown.

### Done Looks Like

- [ ] Block file selection in the UI after upload has started, so that clicking on the file name will not open the file explorer.
- [ ] Clicking on the `Remove` button stops the file upload process

**Comment by joncameron** [comment]
This could be broken in two tickets. Notes:
- Removing all of the button options (change, remove, upload) while a file is actively uploading would be better and remove some of the issue seen in this ticket. Hiding these and displaying a single 'cancel' button that would set the upload widget back to its original state might be a good solution. 
- We could look at the widget being used and see if it could be modified (or if it has been by us in the past)
- This does not appear on Mallorn. For non-AWS Avalon a spinner shows up that blocks UI interaction until the upload is complete.
