### ISSUE TITLE
Upgrade bootstrap-sass

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3922]
### Description
Newer versions of bootstrap-sass add additional security checks and requirements for some UI elements that we use.  We need to review those and figure out how to comply with the newer restrictions or refactor the UI to avoid the issue.

### Done Looks Like
- Review new changes and requirements in bootstrap-sass
- Compile changes needed, if any, regarding UI or otherwise when upgrading bootstrap-sass

### Notes
- New bootstrap-sass was restrictive into what attributes can be passed in (or something along these lines), and they removed attributes that we're using. We'll need to figure out how to deal with this, and it's no necessarily straightforward.
- We may need to some larger markup changes to deal with changes in bootstrap-sass

**Comment by joncameron** [comment]
We did this!
