### ISSUE TITLE
Media Object in response from /media_objects.json API are duplicated

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3928]
### Description
The ingest API provides an endpoint (`/media_objects.json`) for retrieving paged lists of media objects.  The number of media objects per page can be set with a query param (`per_page`).  When setting this param to `1`, only one media object is in the returned json but it is there twice.  This holds true when setting `per_page=2` then two media objects are returned by they are both repeated for a total of 4 entries in the response array.  I assume this happens for all values of `per_page` or even when the param isn't present.

### Done Looks Like
- Media objects one display once in the json response from the API as per above

**Comment by cjcolvar** [comment]
I'm able to reproduce this on MCO, but not avalon-dev.  So maybe we could go ahead and close this ticket as fixed in the rails 6 upgrade work?

**Comment by masaball** [comment]
Yeah, guess something in the upgrade took care of it. I think we are good to close.
