### ISSUE TITLE
Replace spruce and mallorn servers

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3929]
### Description
Spruce and Mallorn are RHEL6 boxes, whose end of life is Nov 2020. We should replace them with RHEL/CentOS 8 if possible. 

Should also decide if we want to do container deployment and/or consolidate into 1 box. AWS is another interesting option, could keep cost down by deploying all containers to 1 EC2 box (no S3, ElasticTranscoder, etc), advantage: deploy new branch to its own box.

### Done Looks Like
- Make decision on when/how to replace, or whether to use container-based deployment and server management

**Comment by joncameron** [comment]
Already completed in early 2022.
