### ISSUE TITLE
Mallorn - Video Not Playing on Android devices 6-9 on any browser

### ISSUE THREAD

**Issue by SumithBaddam** [avalonmediasystem/avalon#3931]
### Descriptiong
Server: mallorn.dlib.indiana.edu
Testing: Regression
Browsers: Chrome, Firefox
Operating System: Android 6-9
Issue: Video not playable on Android devices 6-9 on any browser.

**Steps to reproduce this behavior:**
1. Open browser instance on Browserstack
2. Login to Avalon system with a valid user credentials.
3. Browse for a video or audio file and click on the play icon.

**Error:**
The media file loads and then displays blank screen at 00:00.
![image](https://user-images.githubusercontent.com/6374927/72164765-4b510a00-3394-11ea-833d-fa7d19236792.png)

**Comment by joncameron** [comment]
This is not an issue on IU staging. Most likely an issue with the streaming setup on Mallorn.
