### ISSUE TITLE
Persona datatables takes a long time to load when there are many users

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3942]
### Description
The persona datatables implementation isn't using an endpoint to do filtering and pagination so it has to load all of the users into the DOM and then initialize the table view.  On MCO we have just shy of 5000 user accounts so this takes ~25s for the full page load and initialization of datatables.

This is an upstream change we should probably make to Persona--improving the datatables.

### Done Looks Like
- Use an endpoint to do filtering and pagination for Persona

**Comment by cjcolvar** [comment]
WIP started here: https://github.com/avalonmediasystem/avalon/tree/persona_perf

**Comment by joncameron** [comment]
Resolved with #4713.
