### ISSUE TITLE
Demo Box - Password Reset Throws 500

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3944]
### Description
Password resets are returning the Rails 500 page for existing user accounts (doesn't happen for email addresses not tied to an account).

### To Reproduce
At https://spruce.dlib.indiana.edu/users/password, enter archivist1@example.com as the user and click the "send me password reset instructions" button.

**Comment by phuongdh** [comment]
Likely Persona doesn't use the Mailer setting (which is :aws_sdk)

**Comment by joncameron** [comment]
Fixed via #3946
