### ISSUE TITLE
Demo Box - Update Vocabs and Styling

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3945]
### Description
Making our demo site and the content within look nice and make sense for navigation, so that users evaluating Avalon can quickly see what Avalon is like and how it might be set up.

### Done Looks Like
- [x] Add featured collections
  - home_page:
    -  featured_collections: ['8910jt56k', '3197xm04j']
    -  carousel_collections: ['8910jt56k', '3197xm04j', '0v8380680', 'dj52w479s'] 
- [x] Set these to be the Units in controlled_vocabulary.yml:
  -  Test Content From Evaluators
  -  Avalon Media System
  -  Samvera Community
  -  Sample Content
- [x] Remove "The" from "The Avalon Media System" (https://github.com/avalonmediasystem/avalon/pull/3950)
- [x] Update https://www.avalonmediasystem.org/try-out-avalon page after Demo is updated

**Comment by phuongdh** [comment]
Given than we want to pull in a few commits from `develop`, I wonder if it makes sense to 
- cut a new `demo` branch from `master` and cherry-pick the commits
- or make a new release?

**Comment by phuongdh** [comment]
Collections Carousel not working:
```
Error: URL contains XSS injection attempt
    at a (https://demo.avalonmediasystem.org/packs/js/application-174e572ab1eaef31ba71.js:1:554329)
    at https://demo.avalonmediasystem.org/packs/js/application-174e572ab1eaef31ba71.js:1:554769
    at https://demo.avalonmediasystem.org/packs/js/application-174e572ab1eaef31ba71.js:1:358122
    at new Promise (<anonymous>)
    at e.exports (https://demo.avalonmediasystem.org/packs/js/application-174e572ab1eaef31ba71.js:1:357089)
    at e.exports (https://demo.avalonmediasystem.org/packs/js/application-174e572ab1eaef31ba71.js:1:552172)
```

**Comment by phuongdh** [comment]
Turns out it's an Axios bug that rejects query strings starting with "on" like our carousel endpoint here https://demo.avalonmediasystem.org/collections.json?limit=10&only=carousel

https://github.com/axios/axios/issues/2646
