### ISSUE TITLE
Auto Quality in Safari Not Loading Stream

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3957]
### Description
- It's not loading with the auto quality
- On iOS the quality setting isn't sticky--it's flipping back to auto when moving from track to track, which is an issue

**Comment by cjcolvar** [comment]
The first issue was due to a local issue and the second issue appears to be fixed in 7.0.

**Comment by joncameron** [comment]
Closing per Chris' comment.
