### ISSUE TITLE
Bulk intercom push errors can lead to 500

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#3958]
NoMethodError: undefined method `[]=' for #<ActiveModel::Errors:0x...> Did you mean? []
bulk_action_jobs.rb  179 block in perform(...)
[PROJECT_ROOT]/app/jobs/bulk_action_jobs.rb:179:in `block in perform'
177         elsif result[:status].present?
178           error = "There was an error pushing the item. (#{result[:status]}: #{result[:message]})"
179           media_object.errors[:base] += [error]
180           errors += [media_object]
181         else

https://app.honeybadger.io/projects/54285/faults/60038117

**Comment by joncameron** [comment]
Closing—this can be reopened if it reoccurs. It's been long enough that the Honeybadger info has expired.
