### ISSUE TITLE
Demo Site Improvements

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#3964]
### Description
Making changes to improve the appearance and presentation of the Avalon Demo site.

### Done Looks Like
- [x] Remove justification on collection description on the landing page
- [ ] ~Rework homepage design, which doesn't look good especially in very wide viewports~
- [x] Reduce the header height
- [ ] ~Remove the button before sign-in (unnecessary)~ (_ticket created on core board for general fix for this_) (#3991)
- [ ] ~Update our wiki page with demo server credentials~ (_handled by ticket on IU board_) (https://bugs.dlib.indiana.edu/browse/VOV-6101)
- [x] On Demo, there's 10 pixels of margin for 'section' elements, but not on Spruce. Why is this?

**Comment by Dananji** [comment]
I think this `margin-bottom: 10px` is introduced in SME (https://github.com/avalonmediasystem/react-structural-metadata-editor/blob/master/src/App.css#L8) and it's leaking into homepage. I don't know why it is affecting the homepage in demo not in spruce.

**Comment by Dananji** [comment]
@joncameron Can you please clarify what is the button before `Sign-in` that needs to be removed? Thanks.

**Comment by joncameron** [comment]
@Dananji It's the button with label "Email/Password" under "Select Sign In Method". This is redundant since there's only a single sign in method configured.
