### ISSUE TITLE
DRY up master_file_behavior and speedy_af proxy's display_title

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#3978]
### Done Looks Like
Complete the work started on this PR: https://github.com/avalonmediasystem/avalon/pull/3975/files

**Comment by phuongdh** [comment]
@cjcolvar opened this PR https://github.com/avalonmediasystem/avalon/pull/4128, we should follow up on it

**Comment by joncameron** [comment]
No longer needed.
