### ISSUE TITLE
Fix flappy test (PlaylistItemsController PATCH #update with valid params updates Playlist Item)

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#4002]
# Description
Flaky tests are causing issues in builds.
  1) PlaylistItemsController PATCH #update with valid params updates Playlist Item
     Failure/Error:
       expect do
         patch :update, params: { playlist_id: playlist.id, id: playlist_item.id, playlist_item: { title: Faker::Lorem.word, start_time:'00:20', end_time:'1:20' } }, session: valid_session
       end.to change{ playlist_item.reload.title }
     
       expected `playlist_item.reload.title` to have changed, but is still "debitis"
      ./spec/controllers/playlist_items_controller_spec.rb:162:in `block (4 levels) in <top (required)>'
      /usr/local/bundle/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:123:in `block in run'
      /usr/local/bundle/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `loop'
      /usr/local/bundle/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:110:in `run'
      /usr/local/bundle/gems/rspec-retry-0.6.1/lib/rspec_ext/rspec_ext.rb:12:in `run_with_retry'
      /usr/local/bundle/gems/rspec-retry-0.6.1/lib/rspec/retry.rb:37:in `block (2 levels) in setup'

rspec ./spec/controllers/playlist_items_controller_spec.rb:161 # PlaylistItemsController PATCH #update with valid params updates Playlist Item

**Comment by joncameron** [comment]
We'll close this for now; we could open up a broader issue of "Fix Flaky Tests" or similar if they come up.
