### ISSUE TITLE
Create Comparison of Avalon's MediaElement and the React IIIF Player

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4011]
### Description
Our long-term goal is to update the IIIF player. We need a comparison of what the player in Avalon currently provides (MediaElement + our extra stuff) vs. where the IIIF player is at now.

### Done Looks Like
- Document written that discusses what the IIIF player needs to be at parity with our current player

**Comment by Dananji** [comment]
1. Add quality selector 
2. Add lil' scrub
3. Add captions support
4. Add marker support in playlists
5. Support multiple sections
6. Identify the media type from manifest and create audio/video element from that
7. Parse section/structure labels properly
