### ISSUE TITLE
Missing RightsStatement Info in Controlled Vocabulary Throws 500

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4040]
### Description
If the rightsstatement portion of Avalon's controlled_vocabulary.yml file is not present, attempting to render the resource description portion of a media object's edit page will result in a 500.

**Comment by cjcolvar** [comment]
This probably also applies to the other controlled vocabularies we use on the description page (identifier_types and note_types) as well as the collection create/edit modal (unit).

**Comment by joncameron** [comment]
Check with Julie to see if an empty string value is acceptable for missing values in a controlled vocabulary. Will this be bad data going into records if it's the default behavior (instead of a 500)?

**Comment by joncameron** [comment]
Closing for catchall ticket #4800
