### ISSUE TITLE
Add Supplemental File to Masterfile in UI

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4042]
### Description
As a collection staff-level user, I want to add a supplemental file to my item and associate it with a masterfile so it can viewed or downloaded by end-users.

### Done Looks Like
- A new column, named "Files" for now, appears in the structure step of the edit view alonside "captions" and "structure" and has similar UI interactions to those existing categories
- Users can select the +/- toggle to see the files listing
- Selecting the upload button opens up a file picker
- Users can add any number of files to a masterfile
- Each file is listed in an ordered list 
- Users can remove a file by selecting the "Remove" button in the same row as the file they'd like to remove

### Mockup
![structure_edit_mockup](https://user-images.githubusercontent.com/1406618/77649840-dfb51c80-6f40-11ea-8fa7-f9538d64b8c7.png)

### Notes
Requiring that a supplemental file be associated at the masterfile level instead of the media object level is a strategy used by other applications such as Aviary. It would be nice to have support for attaching a supplemental file at the media object level: sets that contain a number of videos in one package which may have supplemental material associated with the whole package (liner notes for a DVD box set, collection-level records in an Avalon instance that have supplemental documents that discuss the collection in full), but for now I'd like to scope it to the masterfile level.

These extra files are often referred to as "Supplemental Materials", "Related Documents", "Supplemental Files"—is there a particular term that would be best to use? 

### Security
These files should be protected similar to Derivatives: only authorized users can download. Users who can read MediaObject can read the files.

**Comment by phuongdh** [comment]
We're going to try not storing the files in Fedora. Store them on disk and serve them from a web server.
