### ISSUE TITLE
Timeliner and links to it still visible for administrators when timeliner isn't configured

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#4048]
### Description
The restriction to the timeliner is currently depending on the ability which doesn't add abilities if the timeliner isn't configured.  This breaks down because administrators are given all abilities.  We should always grant abilities regardless of if the timeliner is turned on or not. 

### Done Looks Like
- Move the check for Timeliner being configured out of ability and into the controller, views, etc. where the timeliner ability checks are happening.

**Comment by Dananji** [comment]
Closing in favor of #4300
