### ISSUE TITLE
Timeliner should be configured by default

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#4049]
Instead of requiring users to configure the timeliner to turn it on, we should configure it by default and document how to turn it off.

**Comment by Dananji** [comment]
I think the first part of this is achieved via [this PR](https://github.com/avalonmediasystem/avalon/pull/4316), where we removed `timeliner_url` setting in config.

**Comment by joncameron** [comment]
Chris can take a look and see where this is at in the code; we could make it easier for implementers to have this enabled by default and have them turn it on than vice versa.

**Comment by joncameron** [comment]
Chris will close if this is actually already done.

**Comment by joncameron** [comment]
This is already the case.
