### ISSUE TITLE
Timeliner not working as expected

### ISSUE THREAD

**Issue by SumithBaddam** [avalonmediasystem/avalon#4055]
![timelines.PNG](https://images.zenhubusercontent.com/5d67e1cbb530512d88c8f52c/7fd5dfe7-6a3c-4b9a-ade4-fa278e633658)Timeline UI is inappropriate. This is causing the play, create bubble, group bubbles and other options un-clickable.

**Comment by Dananji** [comment]
This is fixed, and is in mco-staging now.
