### ISSUE TITLE
Unable to access item when access is granted via IP Address 

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#4057]
### Description
An Avalon implementer reported that, when setting access to items in a collection to _logged-in users only_ and granting special access to those users connecting from a specific IP address, a non-authenticated user with that IP address is not able to access the item.

### Expected Behavior
A non-authenticated user with that IP address should have access to the item based on their special access.

### Testing performed
I tested this in IU's MCO (7.0) and MCO-staging (7.1.0) and was able to reproduce the behavior. 
I tested in spruce (7.1.0) and I was not able to reproduce the behavior. 

I am not sure what would make spruce different from mco-staging with respect to how access control works.

**Comment by cjcolvar** [comment]
I was not able to reproduce this issue on spruce, mallorn, MCO-staging, or MCO.  If the item is not published then it will not be available to non-collection staff which might be the reason for this issue.

**Comment by joncameron** [comment]
Based on the reproducibility of the this issue, we may also need to create a bug report for forced authentication for collection landing pages even when not appropriate.

**Comment by cjcolvar** [comment]
I've had a few emails with Doug and I think the issue is that collections that have only hidden items a user has access to are hidden from that user on the collection listing and the collection landing page requires login.  I believe this is the expected behavior but am open to rethinking it if there are compelling use cases.

**Comment by mcwhitaker** [comment]
@cjcolvar I was able to reproduce this without hiding items -- I assume you are talking about hiding from search results -- I never touched that option and was able to reproduce so I will try again.

**Comment by mcwhitaker** [comment]
@cjcolvar  

1. In MCO staging, I set item "Belly Up" with "logged in users only", and added the special access for an IP address that corresponds to my current ip address.
2. I log out. 
3. I click on "view collections" and I can't see the "Test Collection" where the item is. (I believe I should because the item is not hidden and is to be available to anyone with that IP address.)
4. I log in.
5. I can see the item (for many reasons).

I am not deep-linking to anything. The use case here is the very simple one we have: if you are at the Music Library, your IP should be in a range that grants permissions. The user should have access to the Music Library collections. This user does not need to have an IU login.

**Comment by mcwhitaker** [comment]
By the way, I am not on the VPN either.

**Comment by mcwhitaker** [comment]
@cjcolvar  Sorry, Chris! User error. The item was not published! So it was _hidden_ in a way.
