### ISSUE TITLE
Users Can View and Download Supplemental Files

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4066]
### User Story
As a user, I want to see supplemental files associated with the item on the item view page so I can download and view them.

### Description
If present, supplemental files that have been uploaded by collection staff should appear on an item's view page. To accommodate the display of these files, we'll change our current panel that displays metadata into a tabbed panel that displays the metadata, but also a new "Files" tab.

### Done Looks Like
- The current panel for metadata is tabbed
- "Metadata" is changed to "Details" for the new tab-based interface
- If there are no supplemental files on the item, the "Files" tab does not display
- Users can switch between the descriptive metadata listing and the file listing by selecting the appropriate tab
- The files tab provides a listing that shows the label for each masterfile which has a supplemental file
- Beneath each masterfile label is a list of hyperlinks, one for each supplemental file associated with the masterfile
- The text of the hyperlink is the name of the file
- If there is only a single masterfile for the item, the supplemental files are listed and linked in the "Files" tab but the section label is not displayed, unless the label is present in the structural metadata (same rules as for showing the label in an item view)

### Mockup for Tabs
![Screen Shot 2020-03-26 at 9 23 11 AM](https://user-images.githubusercontent.com/1406618/77651630-7387e800-6f43-11ea-8508-d0adea435640.png)

![Screen Shot 2020-03-26 at 9 28 32 AM](https://user-images.githubusercontent.com/1406618/77652160-36702580-6f44-11ea-9208-b1737e6421a5.png)

### Inspiration
![Screen Shot 2020-03-26 at 9 11 56 AM](https://user-images.githubusercontent.com/1406618/77651689-8995a880-6f43-11ea-8002-20ac8a74ba76.png)

![Screen Shot 2020-03-26 at 9 16 02 AM](https://user-images.githubusercontent.com/1406618/77651639-77b40580-6f43-11ea-9e6d-5e2530c18b20.png)

### Notes
- Keep Fedora Objects in its own panel for the time being
- A tricky part could be making sure these are working with SpeedyAF, where items with many sections need to load a lot of section info before displaying files. This should probably be handled in the sibling story.

**Comment by cjcolvar** [comment]
TODO: Section titles shouldn't appear in files tab if they don't have any supplemental files attached to them.
