### ISSUE TITLE
Add Supplemental File Support in Models and Controllers

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4068]
### Description
- Adding supplemental file scaffolding into the application.

### Done Looks Like
- Model(s) and controller(s) updated to support supplemental files associated with masterfiles

**Comment by cjcolvar** [comment]
Model and controller code added.
TODO: add a real storage mechanism maybe with valkyrie/shrine/activestorage/carrierwave

**Comment by phuongdh** [comment]
We decided on using ActiveStorage for now.

**Comment by cjcolvar** [comment]
We also need to make sure this works with speedy_af so we don't have to load fedora objects in order to show media objects that have master files with supplemental files.
