### ISSUE TITLE
Playlist titles cannot have emojis when using MySql

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#4076]
Might affect other objects stored in the database (timeline, bookmarks, etc.).  I tested this and unicode is supported but when I added the emoji it caused a 500.  This could be because we need to adjust the character encoding on the database to be a different form of utf8.
Worked: 桜 Didn't work: 桜😇

Found in production: https://app.honeybadger.io/projects/54117/faults/62765815

Looks like we may need to switch from utf8 to utf8mb4:
https://mathiasbynens.be/notes/mysql-utf8mb4

### Done Looks Like
- Fix and then write instructions on how to fix, updating install instructions likewise as needed

**Comment by joncameron** [comment]
Closing as this isn't configured in our db schema; can provide this as guidance for future implementers if necessary.
