### ISSUE TITLE
Use Arrow Keys to Seek in Small Amounts

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4078]
### Description
Many media players offer this, and Avalon should as well for music students and others who need to do a lot of navigation.

### Done Looks Like
- Left arrow moves playhead 5s previous
- Right arrow moves playhead 5s in the future

**Comment by cjcolvar** [comment]
Youtube does 5 seconds: https://support.google.com/youtube/answer/7631406?hl=en

**Comment by joncameron** [comment]
Currently, focus need to be on MEjs to use keyboard shortcuts (space bar to play/pause, for example). MediaElement probably offers easy key-binding for other things like seek as in this issue, but there is a question of 

Buttons for seeking is also something that is worth considering; more complicated but is nice for user experience.
