### ISSUE TITLE
Flash Message for Save Structure Should Disappear Upon Edit

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4079]
### Done Looks Like
When the user takes an action in SME, the 'Save Structure' flash message should disappear (if currently visible).

**Comment by mcwhitaker** [comment]
@joncameron  - isn't this the same as https://github.com/avalonmediasystem/react-structural-metadata-editor/issues/85 ?

**Comment by joncameron** [comment]
It is! Duplicate of avalonmediasystem/react-structural-metadata-editor#85, closing.
