### ISSUE TITLE
Public Items Don't Show on Collection Landing Page

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4084]
### Description
Ampersands are not being encoded correctly for Blacklight JSON requests. This results in the collection landing page not displaying any results because the name of the requested collection in the URL does not match the name of the collection as Blacklight expects it.

### Example
Here's a public item: https://spruce.dlib.indiana.edu/media_objects/5138jd945

Here's the landing page for that item's collection, with no results, even for admins: https://spruce.dlib.indiana.edu/collections/6m311p430

The collection landing page is making a request to 
https://spruce.dlib.indiana.edu//catalog.json?per_page=12&q=&page=1&f[collection_ssim][]=Ampersands%20**&**%20More!, which returns a blank set of results.

Replace '&' with '%26', and the JSON response contains the expected item:
https://spruce.dlib.indiana.edu//catalog.json?per_page=12&q=&page=1&f[collection_ssim][]=Ampersands%20**%26**%20More!

**Comment by cjcolvar** [comment]
This probably just needs escaping in the search builder via `RSolr.escape` or something like that.

**Comment by cjcolvar** [comment]
Thinking about this again, I think we may just need to escape the request parameters in the Search react component.  This might be fixed if we pass the parameters into the axios request instead of manually appending them to the url string like:
```
axios.get('https://site.com/', {
  params: {
    name: 'Flavio'
  }
})
```
