### ISSUE TITLE
Test Avalon with Wowza 4.8.0

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#4089]
4.8.0 comes with some HLS fixes and updates, hopefully it will fix #3799. Randall Embry wants to move the test server, and would like to test out latest Wowza.

### Done Looks Like
- Make sure Avalon security module is working correctly with Wowza 4.8.0
- Fix error or write new issues as needed to resolve issues (first found in Wowza 4.7.x)
- Sample media is checked with 4.8.0

**Comment by joncameron** [comment]
This has probably already been long done; no need to test.
