### ISSUE TITLE
Check SpeedyAF Support for Supplemental Files

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4093]
### Description
Need to make sure that loading from Fedora isn't causing slowdown when loading media objects that contain or have masterfiles that contain supplemental files.

**Comment by cjcolvar** [comment]
The change needed so far was so small that I just included it in the open PR: #4104

**Comment by cjcolvar** [comment]
Looks like reifying is still happening:
`Reifying MasterFile because supplemental_files_json called from /srv/avalon/avalon_r6/releases/20200507195919/app/presenters/speedy_af/proxy/master_file.rb:42:in `supplemental_files'`
