### ISSUE TITLE
Supplemental File should not be persisted if the file failed to store 

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#4103]
Scenario: 
- Upload supplemental file without the files bucket
- Avalon throws an error about missing bucket
Observe:
- Supplemental file is still shown in Structure tab.

Expect:
- Supplemental file is not shown in Structure tab. 
- Record in DB should not be created

**Comment by joncameron** [comment]
Merge with existing issue #4113

**Comment by cjcolvar** [comment]
Fixed by #4125

**Comment by joncameron** [comment]
See above - duplicate
