### ISSUE TITLE
Errors when creating or editing collection are not displayed

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#4111]
### Steps to Reproduce:
1. Go to Manage Content
1. Click Create Collection button
1. Click Create Collection without adding a Name

OR

1. Go to a collection's edit page
1. Click Edit Collection Info
1. Remove the Name
1. Click Update Collection

### Current Behavior
Form modal closes and no message displayed and no visible effect.

### Expected Behavior
Form fields failing validation or with errors after submission will be highlighted with help message.

**Comment by joncameron** [comment]
Timeboxed to a 3. We'll try to preserve the modal.
