### ISSUE TITLE
Supplemental File records still created when ActiveStorage misconfigured

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#4113]
### Steps to Reproduce
Change the ActiveStorage configuration to be something that isn't configured correctly then try uploading a file to a section on the structure step.

### Expected Behavior
If the attaching of the file to the supplemental file fails then the supplemental file record should be deleted.

### Actual Behavior
500 page displayed but going back to the structure step the supplemental file is displayed as if the upload succeeded.

**Comment by cjcolvar** [comment]
I retested this on Spruce and it was still broken.

**Comment by phuongdh** [comment]
Confirmed `SupplementalFile.count` did not change when uploading to a misconfigured Spruce
