### ISSUE TITLE
Allow choosing activestorage configuration from settings.yml

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#4114]
Currently the activestorage adapter is hard coded in the matching environment file (e.g. config/environments/development.yml).  This leads to problems when deploying to spruce since it isn't setup to use minio which is the default so developers can use docker.

### Done Looks Like
- Config file is decided
- Application updated to use config

**Comment by joncameron** [comment]
On Spruce we can do development.local as an override.

**Comment by phuongdh** [comment]
Tested working on Spruce
