### ISSUE TITLE
Supplemental Files Can Be Attached to the Media Object in GUI

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4116]
### Description
Supplemental file support has been added for masterfiles, but they should also be able to be attached at the media object level. This covers use cases where supplemental files don't refer to a single file, but rather to the item as a whole (music album artwork, programs etc.).

### Done Looks Like
- A new section is added to the Structure edit step for a media object where users can upload a file to the media object level. 
- In the "Files" tab on the media object view page, supplemental files are listed (above the current listing of file by masterfile label)

**Comment by joncameron** [comment]
Copy the pattern on masterfiles to media objects.

**Comment by Dananji** [comment]
@joncameron For the GUI, do we have a mockup of how it would look like? It's not very clear from the description in the ticket. It would be helpful if you can explain how this would look like a little bit more even without a mockup. Thanks in advance!

**Comment by joncameron** [comment]
We'll schedule another meeting for Sprint 209 to discuss UI.
