### ISSUE TITLE
Update Date (EDTF) Help Text in Resource Description

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4118]
### Description
Our current text in the Resource Description form for valid date values doesn't point to the draft spec for EDTF, which we currently don't support. This should be updated.

### Done Looks Like
- Help text updated with link to draft spec, if available.

**Comment by jlhardes** [comment]
Internet Archive has several captures of the draft EDTF spec. Not ideal but it might be the only way to point to it now. Here's an example: https://web.archive.org/web/20190223123942/http://www.loc.gov/standards/datetime/pre-submission.html

**Comment by joncameron** [comment]
Superceded by #3867.
