### ISSUE TITLE
IIIF manifest generation reads from Fedora

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#4123]
When requesting the manifest, I'm seeing a speedy AF warning of reification:
```
Reifying MasterFile because stream_details called from /srv/avalon/avalon_r6/releases/20200507163803/app/controllers/media_objects_controller.rb:467:in `block in manifest'
```
This will be discussed during the knowledge share for SpeedyAF.

# Done
- [ ] Investigate what will resolve the unnecessary reification
- [ ] Assess the impact of having to reify master file. Huge performance concerns, or minimal?

**Comment by elynema** [comment]
Chris had some suggestions, so he and Mason will partner to look at them.
