### ISSUE TITLE
Create pull request to UV for V4 pre-release regressions

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#4130]
Two possible code changes were found when testing Avalon manifests with the latest pre-release version of UV.  These should be turned into pull request(s).

>The error happening with regards to auth services failing, Chris found that the issue might be with the changes in the way manifold handles the responses in the version used in UV previously to the latest one in master. Here JSON.parse(xhr.responseText) fails when responseText is empty.
Action item: make a PR to manifold to handle this gracefully
Possible diff:
 // if it's a resource without an info.json 
 // todo: if resource doesn't have a @profile 
 if (!xhr.responseText) { 
   that.status = HTTPStatusCode.OK; 
   resolve(that); 
 } else { 
   const data = JSON.parse(xhr.responseText); 
   let uri: string = unescape(data["@id"]); 

>Another issue that we found yesterday was that in the latest UV "Sound" canvases were trying to be matched with video "format"s and failing on "audio/mp4" but successfully loads with "video/mp4".

**Comment by cjcolvar** [comment]
The second issue was reproduced by @glenrobson and reported in https://github.com/UniversalViewer/universalviewer/issues/730

**Comment by Dananji** [comment]
For the first issue PR made: https://github.com/IIIF-Commons/manifold/pull/6
