### ISSUE TITLE
Download S3 derivatives for waveform processing

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#4141]
Running ffmpeg directly against S3 files has been very slow. We should consider downloading them before processing and retest. Brian agrees:

> The S3 protocol is HTTP and HTTP is chatty and slow when you do multiple small requests. The MP4 format metadata is spread throughout the file in different atoms, so to even get something as simple as the duration of the file it's going to take at least 4 HTTP transactions: get the length of the resource, read the last few bytes of the file which point to the MOOV atom, read the MOOV atom somewhere in the file to find the atom which describes the duration, and then read the duration atom.
> 
> When reading the file for transcoding, FFMPEG is going to read chunks of the file as separate requests which is going to reduce your bandwidth further because of the HTTP overhead and the latency on the S3 end.
> 
> S3 servers (as a general rule) are tuned to send the object as a whole and tend to be ill-suited for a bulk of byte-range requests.
> 
> I did a quick test which pulled that file via the perl S3 module and it took 2.469 seconds to get 46M -- which is 18.6MB/s. Not great, but far better than what you're seeing.
> 
> As a side note of your test: you measured all of the traffic in/out of the machine to VLAN 541 -- which would have included your terminal, anything that Kara's group was doing, and maybe some nagios checks. Your actual bandwidth was lower.
> 
> Another potential gotcha of trying to do it in place is that the ticket only lasts for 15 minutes. If you're doing a heavy transcode that takes longer than that, the processing will die when the ticket expires....which would be a pain to debug.
> 
> So, it's best to grab the entire file prior to the ffmpeg, process it, and then destroy the downloaded file. That will also allow you to take advantage of any multithreading that ffmpeg wants to do. If you have multiple operations to do on that single file, you can also batch them so it only has to hit S3 once.
> 
> Brian
>

**Comment by cjcolvar** [comment]
How about we add a flag to cache locally so the existing behavior can stay in case anyone doesn't want to cache locally?

**Comment by phuongdh** [comment]
Confirmed on AWS. Needs to confirm on MCO-staging.

**Comment by phuongdh** [comment]
It's not part of 7.1.1 so can't verify on MCO-staging but I've verified multiple times on demo.
