### ISSUE TITLE
Link to Jobs dashboard from the UI

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#4155]
Jobs dashboard is currently hidden unless you know the `/jobs` link. I've seen users struggling to remember how to get to it. I think we should put it on the menu, possibly under Manage > Manage Background Jobs

![image.png](https://images.zenhubusercontent.com/5cc1c79d0ce5f07dcc92eebd/cec9dbc4-178d-4aea-9f63-1b34cb6a2f75)

### Done Looks Like
- _Manage Background Jobs_ link is added to the nav menu
- Instead of 'Manage Background Jobs" it's something that could be last alphabetically
- "Manage Zobs?"

### QA
- [ ] Create test scenario to ensure that only administrators see this

**Comment by mcwhitaker** [comment]
@phuongdh I love the suggestion!
