### ISSUE TITLE
Deleting Collection doesn't delete its dropbox dir

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#4170]
### Description
@joncameron said we don't want user to accidentally delete their assets. But some users expect the dir to be deleted.

I think possible solutions are:
- Inform users that assets will be left behind in the deletion confirmation.
- Inform users that we'll delete the assets and actually delete them.

### Done Looks Like
- Deleting a collection deletes the associated dropbox directory and all contents
- A warning message displays to the user indicating that all contents within the directory will be deleted, giving them the option to cancel before the dropbox is deleted and do any file management needed
  - "There are X files in this collection's dropbox that will be deleted when this collection is deleted. Continue?"

**Comment by mcwhitaker** [comment]
@phuongdh @joncameron  - Given that we don't want the dropboxes to be used as permanent storage, I think we should warn the user that the assets will be deleted and let them cancel and go take care of that before coming back to delete the collection.
