### ISSUE TITLE
Error Starting Avalon with Docker

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4190]
Sebastian Bisciglia of the University of Toronto reported an error while attempting to run Avalon with our docker setup:

> attached is a screenshot of the error I encountered while using docker to set up a local instance of Avalon. I believe this error was thrown while getting the /avalon repo version up and running (not avalon-docker).
> 
> The OS is Centos 7 ("everything") running on my Mac in VirtualBox.
> 
> Also, whether running Avalon locally from the avalon and avalon-docker repo, archivist1@example.com is not recognized as an admin user.
> 

<img width="1180" alt="Screen Shot 2020-06-08 at 5 01 49 PM" src="https://user-images.githubusercontent.com/1406618/84659242-203f8900-aee5-11ea-8f2c-db75885db151.png">

**Comment by phuongdh** [comment]
My email to him:

> That error seems like a timing issue where Minio hasn't come up yet and the mc client is trying to hit it. Looks like it retried immediately and the buckets were created so things should be fine.
> 
> As for the user, did you sign up with username archivist1 or archivist1@example.com? Only one of them is an admin I think. You can always create another admin user following this guide here https://wiki.dlib.indiana.edu/display/VarVideo/Manual+Installation+Instructions#ManualInstallationInstructions-UsingtheSystem
>
