### ISSUE TITLE
Smoke testing Mallorn on 7.1.1

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#4191]
### Descriptive summary

Smoke test - When mallorn is upgraded to 7.1.1, we need to perform a smoke test before upgrading MCO.

**Comment by SumithBaddam** [comment]
Tasks for Smoke Test:
1. Can we stream?
2. Does the collection index page look right?
3. Does the collection home page look right?
4. Can I pull a playlist and stream it?
5. Can I pull a timeline and stream it?
6. Does Search work in all pages? (including collection filtering)
7. Do the facets work? (edited)
