### ISSUE TITLE
Send Users to Intermediate Page for Restricted Content

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4206]
### Description
When a user attempts to access restricted content, Avalon will send the user to the homepage and provide a "not authorized" flash message (if authenticated) or to the login screen (if not authenticated). This is confusing for users, especially external users who may be confronted with a sign-in page after clicking a link to an item in the repository.

### Done Looks Like
- When a user is authenticated and requests a page for a restricted item, the item page does not display the usual layout, instead providing a message to the user that the item is restricted and is inaccessible to them.
 - When a user is not authenticated and requests a page for a restricted item, the item page does not display the usual layout but instead a message to the user that the item is restricted and prompts them to log in.

### Notes
- We can look into changing the MediaObject controller to reroute to an intermediate page prompting the user to log in
- Change the controller to not display content until authentication

### Text for this page
"You're not authorized... etc"

**Comment by SumithBaddam** [comment]
For this, me and Dananji are working on 2 mocks and then take the input on which one to go forward with. Here is my mock to blur the media elements.
![blur_media_object.PNG](https://images.zenhubusercontent.com/5d67e1cbb530512d88c8f52c/6c9f1381-eaf9-4a37-9487-8a0bff2a5701)

**Comment by Dananji** [comment]
This mockup is for the new route, where the user is redirected to a new route where `restricted` is added to the end of the item page url (`/media_object/:id/restricted`). The screenshot shows the scenario where the user is logged in. When the user is not logged in, a link to the login page is added to the end of the message.

![Screenshot from 2020-07-07 11-36-29.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/486f2521-03c4-4d89-a73b-041fcd5674d0)

@joncameron Let us know which solution we should go ahead with. And please feel free to make changes :) Thanks!

**Comment by joncameron** [comment]
Let's go with @Dananji's mockup. I like the idea of the blurred page elements but I don't think it's necessary and the simple message to the user gets the point across very clearly. 

Let's also do a call to action for signing in, if the user is unauthenticated. 

If the user is unauthenticated, let's change the text below "Restricted Content" to be:
"You're not signed in. You may be able to view this item after signing in." and then provide a "sign in" button.
