### ISSUE TITLE
Try sidekiq-cron

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#4209]
### Description
Attractive option to get rid of crons and whenever. Need to check if it can behave like our locking_runner: avoids enqueuing a new job when old one is still running. One possible downside—if Sidekiq's not running, cron jobs won't run.

### Done Looks Like
- Try out [sidekiq-cron](https://github.com/ondrejbartas/sidekiq-cron) and see if it can be a viable replacement for crons/whenever
- Write new issues as needed if it's decided to move to sidekiq-cron

**Comment by phuongdh** [comment]
Looks like it doesn't prevent a new job from running if old one hasn't finished
![image.png](https://images.zenhubusercontent.com/5cc1c79d0ce5f07dcc92eebd/2ce57804-3956-4c54-b4e3-7f75c77c35ac)

**Comment by phuongdh** [comment]
This may help https://github.com/mhenrixon/sidekiq-unique-jobs

**Comment by mcwhitaker** [comment]
@SumithBaddam  - to test this, please run a batch ingest. It can be a small one.

**Comment by SumithBaddam** [comment]
@mcwhitaker Batch ingestion ran successfully on spruce.
