### ISSUE TITLE
Using Environment variables to configure authentication fails (patch proposal)

### ISSUE THREAD

**Issue by mcritchlow** [avalonmediasystem/avalon#4214]
Hello,

We're trying to configure an Avalon application using the support in the Config gem for environment variables.

We're using the `omniauth-google-oath2` gem: https://github.com/zquestz/omniauth-google-oauth2

And setting up environment variables like so:
```
# SETTINGS__AUTH__CONFIGURATION__NAME=UC San Diego
# SETTINGS__AUTH__CONFIGURATION__PROVIDER=google_oauth2
# SETTINGS__AUTH__CONFIGURATION__PARAMS__CLIENT_ID=client_id_value
# SETTINGS__AUTH__CONFIGURATION__PARAMS__CLIENT_SECRET=client_secret_value
```

When we run the app we get a stacktrace which maps to `Can't convert Symbol to Integer` [when setting up `Providers` ](https://github.com/avalonmediasystem/avalon/blob/master/lib/avalon/authentication.rb#L38)

I realized the difference between this, and setting up a YAML config file like so:

```
auth:
  configuration:
    - :name: UC San Diego
      :provider: google_oauth2
      :params:
        :client_id: client_id_value
        :client_secret: client_secret_value
```

Is that in the case of the config file, `configuration` is an Array, whereas the Env Vars option for the config gem explicitly does not allow using arrays, as our usage of the env vars naming convention shows.

So, instead of hitting the [`elseif` block (as we do for the config file)](https://github.com/avalonmediasystem/avalon/blob/master/lib/avalon/authentication.rb#L26-L28) when using [env vars we hit the `else` statement](https://github.com/avalonmediasystem/avalon/blob/master/lib/avalon/authentication.rb#L28-L30) and get the noted error.

What we observe is that the call to `.values` strips off all the keys, which causes the resulting array to throw that error.

A "fix", which we have working locally, is to change the `else` block to instead do `[config.to_hash]` which then causes the env vars to successfully process into `Providers` and allows our auth to work.

Would this be an acceptable patch to submit as a PR? Are there other use cases for this `else` block we're just not considering?

Thanks in advance.

**Comment by phuongdh** [comment]
Hi Matt,

Looking at the code, my guess is this is a workaround for the `Config` gem not supporting arrays, since we do need multiple providers. I bet this works without patching the code:

```
# SETTINGS__AUTH__CONFIGURATION__UCSD__NAME=UC San Diego
# SETTINGS__AUTH__CONFIGURATION__UCSD__PROVIDER=google_oauth2
# SETTINGS__AUTH__CONFIGURATION__UCSD__PARAMS__CLIENT_ID=client_id_value
# SETTINGS__AUTH__CONFIGURATION__UCSD__PARAMS__CLIENT_SECRET=client_secret_value
```

**Comment by mcritchlow** [comment]
Hi @phuongdh , thank you! We'll try that today. That would be great and I suspect you're right now that I look at it. Will follow up and close this out if it works.

**Comment by mcritchlow** [comment]
@phuongdh - Your recommendation worked out great, thanks again! Closing this out.
