### ISSUE TITLE
Display Access Restrictions on Item Page for Authorized Users

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4220]
### Description
When a user can access an item, they should be able to see what permissions are granted to give them access. For example, that they're able to view an item by virtue of being in a specific group, or specific access group (logged in users, public users etc.)

### Done Looks Like 
- Users see text on the item page indicating the access level for the item (public, logged in users, restricted, IP address etc.)
- (Public) - This is a publicly available item
- (Restricted) - This item is only available to (restricted group label—IU students faculty and staff, for example. This is not the exact group name in LDAP or otherwise, rather a human-readable text)
- (Collection staff only) - This item is restricted and only accessible to specific authorized users and collection staff
- (IP Range) - This item is accessible due to your network address.

**Comment by phuongdh** [comment]
@joncameron let me know if you have any feedbacks otherwise I'll finish the PR
