### ISSUE TITLE
IIIF Player

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4221]
What needs to yet be added?
What does not need to be carried over to the IIIF player.

@Dananji will list functionality here, and we'll review it to see what should or shouldn't be carried over from the current MediaElement player.

**Comment by Dananji** [comment]
Player in general:
- Highlight time rail when a section is selected
- Add lil' scrubber
- Add keyboard support

In item page:
- Add to playlist support**
- Create thumbnail support**

In playlists:
- Marker creation**

** These functionality would probably live outside the player, but still implemented within the React component with the ability to turn on/off through props as desired. For an example: `<IIIFPlayer markers {...other_props} />` will enable markers support.
