### ISSUE TITLE
Dropbox directory not created when collection is created

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#4224]
### Description

When Avalon is setup to use file system to host the dropbox directory, creation of the first collection should create the dropbox directory at the given path (in docker-compose.yml). The dropbox directory is not created as expected.

### Done Looks Like

Dropbox folder is created at the file system's given path when the first collection is created

**Comment by joncameron** [comment]
Creating a new collection on Spruce named "Create This Collection Please" created spruce:/srv/avalon/dropbox/Create_This_Dropbox_Please
