### ISSUE TITLE
Merge Multiple Items into One

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4226]
### Description
As a collection manager, I want to combine two or more media objects to create a single media object that contains all of the sections of each so that I have a quick way to create a single record from many separate items.

Merging will be destructive—each of the items in the set will be Original items should not be retained. 

### Done Looks Like
- On the _Selected Items_ page, provide a Merge button
- Clicking the Merge button launches a modal 
- Modal contains radio button list containing each media object, and a message to inform the user that the must pick one item whose descriptive metadata will be used for the merged object
- The modal contains radio buttons, one for each media object 
- The radio button selected is the media object that will provide the full metadata record for the single created object
- "Merge" and "Cancel" buttons are displayed in the modal
- After the user clicks the "Merge" button, a new item is created with the descriptive metadata of the selected item, and the masterfiles from each item are added (copied) to this new item.
- If some items or files were unable to be merged, proceed with the operation but display a flash message to the user that displays information on what failed0

**Comment by joncameron** [comment]
Note: we don't have a safeguard for multiple items pointing to the same derivatives. If an item is deleted, the corresponding derivatives are deleted, which isn't ideal if more than one item is referencing.

Merging should be non-destructive. Original items should be retained. Deleting the original items shouldn't make any changes to the new merged item.

**Comment by phuongdh** [comment]
Update: merge is destructive.

@joncameron what should happen when merging multiple items and one of them failed, should we stop or keep merging the rest? I guess if the items need to be in a specific order then we should stop, but this story doesn't mention ordering.

**Comment by joncameron** [comment]
Let's keep going and merge the rest, but display a flash message to the user indicating which item/file(s) were not successfully merged or failed.

**Comment by SumithBaddam** [comment]
If I merge an already merged media object into a non-playable item, none of the items are playable. But if I do the other way, merge non-playable item into a already merged playable one all the items are playable except the non-playable one. Is this expected?

**Comment by phuongdh** [comment]
@SumithBaddam @Dananji and I couldn't recreate this behavior on Spruce: after merging an already merged media object into a non-playable item, all the playable sections remain so.
