### ISSUE TITLE
Increase Default Fedora Timeout

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4242]
### Description
Should the default Fedora timeout value be increased? It led to an issue where a user was unable to add new sections to an item with many existing sections. If we can increase this default value without harm we should.

### Context
From a user in the avalon-discuss mailing list:

> We have noticed a trend where adding more than 75-80 files to a single record causes ingest failure.
>  
> As an example, I tried to ingest a 5-disc box set on a single record. I was able to ingest and transcode 80 of the 100 files. After 80, I have been unable to ingest more files, whether uploading in a batch, or even a single file.
>  
> As another example, I tried to ingest a single CD with more than 100 tracks (small, vocal exercises). I was able to ingest 80 files, but again, once I reached the 81st file, I was unable to ingest any further files.
>  
> My question(s): Is it possible to add more than 75-80 files to a single record? Is there a file-number limit per record? Is there a size limit for the total amount of files per record?

Phuong's Reply:
> Looking at the worker log, you may find that Avalon's connection to Fedora is timing out due to the massive amount of sections (tracks) that item has. Every time the item is updated, the changes will propagate to all of its children. 

> I think by default the timeout setting is 60 seconds but you can extend it by modifying <rails_root>/config/fedora.yml:
>   production:
>     user: fedoraAdmin
>     password: fedoraAdmin
>     url: ...
>     base_path: ...
>     request: { timeout: 600, open_timeout: 60}
> 
> Allocating more resources to Fedora/Tomcat may potentially speed it up too. 

### Done Looks Like
- Current production implementations are checked for timeout value
- Default timeout value changed or retained based on that
- Wiki documentation written if not changed, so that implementers have a reference for increasing the capability of their Fedora instance

**Comment by joncameron** [comment]
We can look up the IU production config for a reasonable value to change the defaults to.

**Comment by phuongdh** [comment]
IU production timeout is 2000, likely too big for average use case.
