### ISSUE TITLE
Prep for Avalon 7.2 Release

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4265]
### Description
Planning and preparation for the next Avalon release

### Done Looks Like
- List of features to be included is compiled
- PRs to be included are listed
- Develop merged to staging (if things are ready by end of sprint)

**Comment by phuongdh** [comment]
This needs to be fixed if we're including sidekiq-cron https://app.zenhub.com/workspaces/avalon-5bff96674b5806bc2bf90276/issues/avalonmediasystem/avalon/4307

**Comment by mcwhitaker** [comment]
Moving  _Develop merged to staging (if things are ready by end of sprint)_ to other ticket.
