### ISSUE TITLE
IIIF Media Player Planning

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4267]
### Description 
Ahead of a possible community sprint, planning 

### Done Looks Like
- List of requirements and features written for reference (what does the player do and not do in terms of functionality?)
- Refactor IIIF player component from class-based to functional components (avalonmediasystem/react-iiif-media-player#60)
- All the tests in IIIF player component are passing (avalonmediasystem/react-iiif-media-player#61)
- Avalon API endpoints are ready (this is not required as we can use mock endpoints, but it is good to have them ready) (#4285)
- Upgrade yarn dependencies in IIIF player component (avalonmediasystem/react-iiif-media-player#56)

**Comment by Dananji** [comment]
Prep work, avalonmediasystem/react-iiif-media-player#56
