### ISSUE TITLE
Investigate Using Latest Browse-Everything

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4268]
### Description
It would be advantageous to be able to use cloud-based file storage and sharing platforms (specifically Google Drive). Updating Browse Everything to be able to use this w

### Questions
- With Google Drive, what are the permissions a user will need to grant to Avalon?
- Testing needs to be done with a "Shared Drive" in Google

### Done Looks Like
- Investigate current Browse Everything. How much effort would it be to upgrade our existing versions?
- Create new issues for implementing this work or for further investigation

**Comment by phuongdh** [comment]
Trying v0.13 as used by Avalon. It does support Google Drive. After setting up browse-everything with an API key and authorizing my user with Google, I can browse the shared folders in my Drive. Can select a file and import it. But it's not sending Avalon an URL required for MasterFileBuilder

```
<ActionController::Parameters {"utf8"=>"✓", "authenticity_token"=>"********", "workflow"=>"", "container_id"=>"ft848q60n", "selected_files"=><ActionController::Parameters {"0"=><ActionController::Parameters {"url"=>"", "auth_header"=><ActionController::Parameters {"Authorization"=>"********"} permitted: false>, "expires"=>"2020-09-14T20:30:44.734Z", "file_name"=>"ivy_basketball.mp4", "file_size"=>"0"} permitted: false>} permitted: false>, "controller"=>"master_files", "action"=>"create"} permitted: false>
```

**Comment by phuongdh** [comment]
Couldn't authorize with my IU account
```
Authorization Error
Error 400: admin_policy_enforced
Access to your account data is restricted by policies within your organization. Please contact googladm@iu.edu to request that this app be trusted by Google@IU. Please include the name and ClientID of the app with your request.
Request Details
access_type=offline
response_type=code
redirect_uri=http://localhost:3000/browse/connect
state=google_drive
client_id=****************.apps.googleusercontent.com
scope=https://www.googleapis.com/auth/drive
```

**Comment by phuongdh** [comment]
Auth token is stored in the browser (cookie or localstorage)

**Comment by phuongdh** [comment]
Since Google Drive doesn't have a "presigned URL" equivalent, we can't just pass the file's URL to mediainfo, we'd have to download the entire file then run mediainfo on it. This is highly inefficient.

**Comment by phuongdh** [comment]
The auth header should be passed to the worker somehow, and active-encode needs to handle it.

**Comment by phuongdh** [comment]
It's working with this PR https://github.com/samvera-labs/active_encode/pull/75

**Comment by phuongdh** [comment]
@SumithBaddam can you QA this on Spruce and locally using docker-compose? We need to test ingestion/batch normally (without Google Drive enabled) to see if this causes any regression bug.

**Comment by SumithBaddam** [comment]
I tested it and it works fine as expected.
