### ISSUE TITLE
Error publishing item without title and date

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#4288]
Steps:
1. Create a new item
2. Go to Resource Description
3. Go to Preview
4. Click Publish

Error:
```
F, [2020-09-17T19:49:07.687758 #26] FATAL -- : ActiveFedora::RecordInvalid (Validation failed: Title field is required., Date issued field is required.):
```

### Done Looks Like
- Users receive an "Unable to Publish item" message in the interface rather than a 500 when attempting to take this action

**Comment by joncameron** [comment]
Worked great under collection manager permissions: 
![Screen Shot 2021-01-27 at 9 52 20 AM](https://user-images.githubusercontent.com/1406618/106008595-74b70380-6085-11eb-89c5-1f30f105f8ea.png)
