### ISSUE TITLE
Long Track Titles Cause 500 During Timeline Save

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4291]
### Description
Creating a timeline from an item or section with a very long value of a segment title will return a 500 error. The column for this value doesn't appear to be large enough.

### Backtrace
ActiveRecord::ValueTooLong: Mysql2::Error: Data too long for column 'title' at row 1: INSERT INTO `timelines` (`title`, `user_id`, `visibility`, `tags`, `source`, `created_at`, `updated_at`) VALUES ('Track 5. Motet: Ad veniam, Perveniam -- Clausula -- Tant grate chievre, que maugist -- Clausula -- Clausula -- Hoquetus -- Clausula -- Motet: Tamquam suscipit, vellus pluviam -- Motet: Qui voudroit femme esprover/Tanquam agnus ductus/Tanquam suscipit, vellus pluviam', 6051, 'private', '--- []\n', 'https://media.dlib.indiana.edu/master_files/8w32r746h?t=945,1392', '2020-09-21 21:36:06', '2020-09-21 21:36:06')

### Done Looks Like
- Provide a DB migration script to increase the column size for title

**Comment by Dananji** [comment]
I was not able to reproduce this in Spruce.
