### ISSUE TITLE
Avalon 7.2 - Release

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4308]
### Description

We'll need a slightly different process than usual, since we won't be merging develop to staging as is the usual way.

### PRs to Exclude
- https://github.com/avalonmediasystem/avalon/pull/4289
   - Google Drive/Browse Everything work is in-progress and this PR will not be part of this release

#### Features
- https://github.com/avalonmediasystem/avalon/pull/4239
- https://github.com/avalonmediasystem/avalon/pull/4246
- https://github.com/avalonmediasystem/avalon/pull/4248
- https://github.com/avalonmediasystem/avalon/pull/4260
- https://github.com/avalonmediasystem/avalon/pull/4271
- #4124
- #4085
- #4080
- https://github.com/avalonmediasystem/avalon/pull/4104
- https://github.com/avalonmediasystem/avalon/pull/4293
- https://github.com/avalonmediasystem/avalon/pull/4309

#### Dependencies
- https://github.com/avalonmediasystem/avalon/pull/4245
- https://github.com/avalonmediasystem/avalon/pull/4253
- https://github.com/avalonmediasystem/avalon/pull/4254
- https://github.com/avalonmediasystem/avalon/pull/4281
- https://github.com/avalonmediasystem/avalon/pull/4282
- https://github.com/avalonmediasystem/avalon/pull/4294
- https://github.com/avalonmediasystem/avalon/pull/4302
- https://github.com/avalonmediasystem/avalon/pull/4202
- https://github.com/avalonmediasystem/avalon/pull/4203

### Other Updates
- https://github.com/avalonmediasystem/avalon/pull/4216
- https://github.com/avalonmediasystem/avalon/pull/4241
- https://github.com/avalonmediasystem/avalon/pull/4250
- https://github.com/avalonmediasystem/avalon/pull/4258
- https://github.com/avalonmediasystem/avalon/pull/4261
- https://github.com/avalonmediasystem/avalon/pull/4262
- https://github.com/avalonmediasystem/avalon/pull/4290
- https://github.com/avalonmediasystem/avalon/pull/4231
- https://github.com/avalonmediasystem/avalon/pull/4237
- #4152
- #4168
- #4176
- https://github.com/avalonmediasystem/avalon/pull/4188
- https://github.com/avalonmediasystem/avalon/pull/4154
- https://github.com/avalonmediasystem/avalon/pull/4175

#### Fixes
- #4136
- #4125
- #4165
- #4169
- #4177
- #4181
- #4184
- #4186
- #4132
- https://github.com/avalonmediasystem/avalon/pull/4213
- https://github.com/avalonmediasystem/avalon/pull/4218
- https://github.com/avalonmediasystem/avalon/pull/4240
- https://github.com/avalonmediasystem/avalon/pull/4244
- https://github.com/avalonmediasystem/avalon/pull/4283
- https://github.com/avalonmediasystem/avalon/pull/4286
- https://github.com/avalonmediasystem/avalon/pull/4296
- https://github.com/avalonmediasystem/avalon/pull/4299
- https://github.com/avalonmediasystem/avalon/pull/4301
- https://github.com/avalonmediasystem/avalon/pull/4303
- https://github.com/avalonmediasystem/avalon/pull/4223
- https://github.com/avalonmediasystem/avalon/pull/4230
- https://github.com/avalonmediasystem/avalon/pull/4187
- https://github.com/avalonmediasystem/avalon/pull/4200
- https://github.com/avalonmediasystem/avalon/pull/4201

#### Pre-release check
- [x] Go through the current changelog since 7.1.1 and double-check changes to the code to make sure we're getting only things that should be in the release

#### Code Changes
- [x] Update version in code
- [x] Update license headers in files if needed
- [x] Tag dependency repos
- [x] Update gemfile to point to those tags
- [x] Merge staging into master

#### Application Testing
- [x] Smoke-testing 

#### Documentation
- [x] Update Known Issues
- [x] Update version numbers on Wiki to refer to latest release as 7.2

#### Marketing and Outreach
- [x] Write a draft of release notes on Github
- [x] Publish release button in Github
- [x] Create tag for v7.2 (should already happen when pressing release button in above step)
- [x] Publish release on Github https://github.com/avalonmediasystem/avalon/releases
- [x] Update wiki with release notes
- [x] Publish blog post announcing the release
- [x] Update homepage with blog post for release announcement
- [x] Update homepage with the updated version and documentation links
- [x] Update website with demo box changes
- [x] Put announcement on Twitter
- [x] Put announcement on Facebook
- [x] Send out email to Samvera community mailing list
- [ ] Publicize in appropriate Slack channels

**Comment by Dananji** [comment]
@joncameron The PRs I talked about were the following;

1. Streaming fix in Android browsers: #4186
2. Keyboard shortcuts for player: #4188 (there's a slight issue with this one, we enabled keyboard shortcuts in another [PR](https://github.com/avalonmediasystem/avalon/pull/4151) with skip forward and backward feature, which was not intended to be released and PR #4188 is related to keyboard shortcuts)
3. Fix skip transcoding in AWS: #4184
4. Bug fix for firing a derivative check infinitely: #4181
5. Fix for filtering collections with special characters: #4177
6. Add `Manage Jobs` link to `Manage` dropdown: #4176
7. Show error messages when creating/updating collection info: #4169
8. Use << instead of += since []= isn't defined for ActiveModel::Errors: #4168
9. Fix route reference when using become sessions: #4165

Some of these may have been excluded intentionally. I wanted to mention them in any case you missed these while compiling this list.

And also what about the list of PRs excluded in 7.1.1 release, do we want to include them in this version?
https://github.com/avalonmediasystem/avalon/pull/4152
https://github.com/avalonmediasystem/avalon/pull/4136
https://github.com/avalonmediasystem/avalon/pull/4125
https://github.com/avalonmediasystem/avalon/pull/4124
https://github.com/avalonmediasystem/avalon/pull/4085
https://github.com/avalonmediasystem/avalon/pull/4080

**Comment by Dananji** [comment]
Found these PRs we have not included in the ticket while I was rebasing;
1. https://github.com/avalonmediasystem/avalon/pull/4104 - Display supplemental files in item view page
2. https://github.com/avalonmediasystem/avalon/pull/4154 - Cache s3 object locally for faster waveform job
3. https://github.com/avalonmediasystem/avalon/pull/4187 - Fix rake:aws:create_presets not working
4. https://github.com/avalonmediasystem/avalon/pull/4200 - Fix S3 localizer
5. https://github.com/avalonmediasystem/avalon/pull/4201 - Fix skip transcoding with real S3
6. https://github.com/avalonmediasystem/avalon/pull/4202 - Update rack to 2.2.3
7. https://github.com/avalonmediasystem/avalon/pull/4203 - Update jquery-rails to 4.4.0 
8. https://github.com/avalonmediasystem/avalon/pull/4293 - Run cron jobs on Sidekiq
9. https://github.com/avalonmediasystem/avalon/pull/4309 - Check for Redis before creating cron jobs

I think the first one we have missed while compiling the list. It shows supplemental files in the item page, which is one of the main features in 7.2. The same goes with the last 2 PRs that Phuong worked on.
@joncameron What do you think about the other PRs here (couple of bug fixes and upgrades)?

**Comment by joncameron** [comment]
@Dananji Yes, that first one is definitely in. It looks like all of these PRs can be included to me.

@phuongdh  - Can you confirm that these all look good for 7.2, or if any should be excluded?
