### ISSUE TITLE
Update Avalonmediasystem.org site

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#4313]
Pages such as these need to be revised:

- [ ] https://www.avalonmediasystem.org/project (change language)
- [ ] https://www.avalonmediasystem.org/partners (check in with institutions as needed)
- [x] https://www.avalonmediasystem.org/avalon-advisory-board
- [x] https://www.avalonmediasystem.org/avalon-office-hours (time to remove?)
- [x] https://www.avalonmediasystem.org/avalon-team (move Chris to former list)
- [x] https://www.avalonmediasystem.org/job-openings (we forget to post our jobs here! Anyway, remove wording about NU)
- [ ] Project history needs to be updated
- [ ] Links to public institutions
- [ ] Update Avalon architecture diagram (broken out in #4099)
- [x] We no longer have an advisory board? Effectively no, could remove.
- [ ] Add Dananji and Michael to the list of staff

### Following Issue
Things not yet completed or needing more review have been moved to https://github.com/avalonmediasystem/avalon/issues/4442

**Comment by joncameron** [comment]
Note: we'll get Maria access to our Drupal site so she is able to edit.

**Comment by mcwhitaker** [comment]
@joncameron  - may I leave it to you to update the list of institutions implementing Avalon? You were going to ask some of those whether we could add them to our page and a link to their installation.

**Comment by mcwhitaker** [comment]
Questions:
1. Not sure about the dates on the grants. It seems that there was overlap?
2. Nothing in the project text speaks of moving to hyrax. Do we add this? 
3. What other suggestions for the project history?

**Comment by joncameron** [comment]
I've moved the remaining tasks to a new ticket: #4442. I've also put the project text into a Google doc for editing and review by the team before changing on the site.
