### ISSUE TITLE
7.2 Regression Testing (Mallorn)

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4318]
### Description
The 7.2 release should have a full regression testing.

### Done Looks Like
- Regression testing done using existing test scripts
- Testing for features listed in the release notes for 7.2 (https://github.com/avalonmediasystem/avalon/releases/edit/untagged-7b43971a6f8a41eba4b1)

**Comment by SumithBaddam** [comment]
I tested merge multiple items and it didn't work. When we select multiple items and click on merge and select an item, a flash message provides the link to the merged item. When I clicked on it, it wasn't merged.

**Comment by SumithBaddam** [comment]
Merging works fine now. Worker needed to be restarted.
