### ISSUE TITLE
Last item in Playlist continues playing beyond the limit

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#4325]
Steps:
- Add 2 or more partial items to playlist
- Autoplay the whole playlist or play the last item.

Observed:
- Player continues beyond the highlighted section of last item.
![image.png](https://images.zenhubusercontent.com/5cc1c79d0ce5f07dcc92eebd/84e3a26b-fd19-4c9b-ac68-2932b51e5b12)

Expected:
- Player stops at the end of the highlight

**Comment by joncameron** [comment]
Confirmed that the last playlist item stopped at the end of the highlight as it should (https://spruce.dlib.indiana.edu/playlists/268).
