### ISSUE TITLE
Browse-Everything and Google Drive

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4332]
What remains to be done? Create a checklist and finalize.

**Comment by joncameron** [comment]
Two issues right now:
- When the user token has expired and browse-everything doesn't recognize this (#4305)
- When the application restarts: browse-everything loses tokens and can't access Drive
- When there are multiple instances of Avalon, and only one knows about the token (there should be a way to share a token among Avalon instances; this happens in Docker)

**Comment by phuongdh** [comment]
- Store user credentials in Redis or DB (note security concerns)
- Make it work with Google Shared Drive

**Comment by joncameron** [comment]
Duplicate of #4339
