### ISSUE TITLE
Attach Transcripts to Item Sections

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4343]
### Description
As a collection manager, I want to upload a transcript file that corresponds to a section.

### Done Looks Like
- An entry for "Transcripts" appears below the "Captions" and above the "Section Supplemental Files" areas the Manage Files section of the Edit page (see mock below, which shows the Transcript section but is not in the order described here)
- Users can click the "Upload" button to open a file picker dialog, the selection of which is uploaded to Avalon
- Multiple transcript files can be attached
- Transcripts follow the UI for supplemental files to account for multiple file uploads, with ability to rename label

### Mockup
![transcript_mockup](https://user-images.githubusercontent.com/1406618/102258239-b7f55280-3edb-11eb-8c60-84a021d2bdaf.png)

**Comment by Dananji** [comment]
@joncameron Transcript file behavior explained in this ticket is different from the behavior explained in the back-end ticket. Here it says each masterfile will have multiple transcript files like the supplemental files and in the [other ticket for the back-end ](https://app.zenhub.com/workspaces/avalon-5bff96674b5806bc2bf90276/issues/avalonmediasystem/avalon/4344) it says there will be only one transcript file for each masterfile similar to captions.

**Comment by joncameron** [comment]
@Dananji This ticket is correct—we'll allow for multiple transcripts files—and I corrected the back end ticket.
