### ISSUE TITLE
Convert Transcript Files to IIIF Annotation Format (Plain Text)

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4345]
### Descriptions
Users can upload a set number of supported formats (that we determine) for transcripts. Once uploaded, the information in these files should be transformed into a IIIF Annotation file. 

If a user uploads a transcript which is not in supported format, then no transformation occurs and the information is not expected to be shown to the user on the item view page. Both the original transcript file and the transformed file are stored on the masterfile.

### Reference
https://textav.gitbook.io/textav-event-2018/unconference-projects/iiif-parliamentary-debates

### Done Looks Like
- Helpers are written to transform transcripts in plain text to IIIF Annotation format
- The IIIF Annotation file is then saved as a bitstream on the masterfile

**Comment by mcwhitaker** [comment]
An example: https://gist.github.com/mcwhitaker/57241245878b1282da0b65a59b8cbdb4

**Comment by joncameron** [comment]
This isn't the strategy any longer; closing.
