### ISSUE TITLE
Convert Transcript Files to IIIF Annotation Format (SRT)

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4351]
### Descriptions
SRTs, when attached to a masterfile, are transformed to a IIIF annotation format

### Reference
https://textav.gitbook.io/textav-event-2018/unconference-projects/iiif-parliamentary-debates

### Done Looks Like
- Helpers are written to transform transcript files in SRT format to IIIF Annotation format

**Comment by joncameron** [comment]
### Descriptions
SRTs, when attached to a masterfile, are transformed to a IIIF annotation format

### Reference
https://textav.gitbook.io/textav-event-2018/unconference-projects/iiif-parliamentary-debates

### Done Looks Like
- Helpers are written to transform transcript files in SRT format to IIIF Annotation format

**Comment by mcwhitaker** [comment]
I think one could adapt [Tom Crane's python code](https://github.com/tomcrane/bbctextav/blob/master/converter/make_iiif.py) for WebVTT  to work for SRT.
