### ISSUE TITLE
Investigate Transcript Transformations to IIIF Annotation Format

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4352]
### Description
We'll need to investigate best practices for modeling transcript information in IIIF Annotation Format. Annotation recipes are upcoming in the IIIF cookbook, so we'll have good examples to draw from soon.

### IIIF Transcript References (put more here as discovered)
- https://textav.gitbook.io/textav-event-2018/unconference-projects/iiif-parliamentary-debates

### Questions
- How will this be handled with transcripts that have no time information?
- How will we process the transformations from transcript to annotation?

### Done Looks Like
- Investigation done and team meeting held
- Findings captured in this ticket or another summary document
- Decision made about whether to create a gem just for this purpose, or where otherwise to put it in the code

**Comment by phuongdh** [comment]
Are we transforming on the fly (with cache) or storing the annotation in the DB?

**Comment by joncameron** [comment]
Maria notes that there are two types of manifest: those with timecodes and those without. 
- No timecodes: just text file. Reference to file in the manifest. (rendering link)
- Timecode present: transformed to IIIF Annotation format.

**Comment by mcwhitaker** [comment]
Here is a gist showing the rendering link: https://gist.github.com/mcwhitaker/b7fe171cb3d279764d4019591a259d11#file-transcript-file-in-rendering-link-L39-L50

I picked a manifest from spruce and just added the rendering code to it.
