### ISSUE TITLE
"My Drive" and "Shared Drives" as Root Folders in Browse-Everything

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4372]
### User Story
As a user, I want to view files in the filesystem-type structure they appear in Google Drive when selecting them for upload via the browse-everything UI. 

### Done Looks Like
- When Google Drive is selected a source using Browse-Everything, the root display is  shows two folders, "My Drive" and "Shared Drives"
- It would be nice to have "Shared with Me" as the third entry below "My Drive" and "Shared Drives", but not necessary if that increases the scope of this ticket
- Essentially mimics this basic layout from the Drive UI, but without the other nav sections, which are filtered views on the files within:
![Screen Shot 2021-01-28 at 9 19 57 AM](https://user-images.githubusercontent.com/1406618/106152938-00936300-614c-11eb-993a-494b6b8f7fd2.png)

**Comment by phuongdh** [comment]
My Drive is now present. Slight problem: browse-everything sorts alphabetically so `My Drive` is not always on top 

![image.png](https://images.zenhubusercontent.com/5cc1c79d0ce5f07dcc92eebd/6b2097de-9546-4bfc-ae60-ef4dc5e3d81d)
