### ISSUE TITLE
Media Player Captures All Keyboard Input on Item View

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4378]
## Description
Attempting to enter characters that are bound by the player (e.g. 'm' for mute) into a text field on an item page doesn't work—the event goes solely to the player, disallowing users from searching for text with 'm' and any others hooked up to the player.

## To Reproduce
Spruce, Avalon 7.2: On any media object view, click the global search field in the top nav bar of Avalon, then press 'm'. The player will toggle mute status, but the character 'm' doesn't get entered into the search field.

## Done Criteria
When focus is not on the player, for example, on a search field elsewhere on the page, page-wide key events should be directed there and not globally captured by the player.

**Comment by Dananji** [comment]
List of keyboard shortcuts for the player:

1. Space bar: play/pause
2. Left/right arrows: jump 5 seconds forward/backward
3. Up/down arrows: increase/decrease volume
4. `f`: enter/exit full-screen mode (this is shown in the label when hovered over the icon)
5. `m`: mute/unmute (this is shown in the label when hovered over the icon)
![Screenshot from 2021-02-08 10-51-50.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/4b5987a5-276d-4b0e-8f28-b9b66afe8a97)
