### ISSUE TITLE
Performance Issues for Items with Many Sections

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4394]
### Description
Attempting to create items with many sections often fails.

### Merging
Merging items with many sections results. Merging two items, each with 50+ sections, resulted in the merge job taking hours and not finishing the merge—
### Super slow saves for media objects

**Comment by phuongdh** [comment]
Code that add a section to a MediaObject, can it be faster? https://github.com/avalonmediasystem/avalon/blob/master/app/models/master_file.rb#L231-L244

**Comment by phuongdh** [comment]
- Deleting a MF triggers MO.save which does a lot of redundant stuff through callbacks. We need to figure out how to skip those callbacks. 
- Don't need to set_duration, just subtract the MF's duration from total time.

https://github.com/avalonmediasystem/avalon/blob/abb538dee577b3c2705472a69a4ffd46c69af84c/app/models/master_file.rb#L741-L750

**Comment by phuongdh** [comment]
Ruby-prof result of `update_parent!`
[prof.zip](https://github.com/avalonmediasystem/avalon/files/6070365/prof.zip)
