### ISSUE TITLE
Update LTI Documentation

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4397]
### Description
We've learned a lot about using LTI with Avalon in the past years, but our existing documentation is out of date.

### Done Looks Like
The page for LTI in Avalon's documentation wiki is updated.

**Comment by phuongdh** [comment]
Updated, I'll ask Oberlin for new screenshots since I don't have admin access to their Blackboard.

Also took the chance to add [Okta notes ](https://wiki.dlib.indiana.edu/display/VarVideo/Okta+implementation+notes)
