### ISSUE TITLE
Google Tag Manager Support

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4408]
### Description
As an administrator, I want more contextual information about pages so analytics can be more easily filtered by collection. Extra scripts should be able to be added so that Google Tag Manager can use additional elements to provide contextual information to Google Analytics. Matomo also uses these, in a slightly different format, so it should be easy to switch from one to the other. 

We can use existing Avalon accounts for Google Analytics to do testing with this.

### Done Looks Like
- ~New ID from Google needed for GTM generated using existing Avalon account ( @joncameron )~
   - Completed, container ID values for Mallorn and Spruce are on our private wiki area (https://wiki.dlib.indiana.edu/x/8AH-IQ)
- Google Tag Manager is configured for Avalon using https://github.com/rcs/google-tag-manager-rails or another library for this purpose.
- On item pages, a GTM DataLayer provides these variables from the record:
  - Item Title
  - Collection Name
  - Unit Name
- A new configuration key is present in settings.yml, google_tag_manager_id, under the existing google_analytics_id key (value will be a string in format of _GTM-XXXX_ )

### GTM Docs
https://developers.google.com/tag-manager

**Comment by joncameron** [comment]
At sprint planning we identified the need for this to be on Spruce. We can deploy to Spruce and test there for easy feedback on connecting GTM in the app to the GTM dashboard.

**Comment by Dananji** [comment]
@joncameron I've put this on spruce, you should be able to see this in Google tag manager dashboard if it's working :) If not, please let me know I will take a look at it again.

**Comment by joncameron** [comment]
I finally worked through the Tag Manager interface and tested things out and it works great! I did create a new issue, #4495, since we don't have analytics on Spruce and it would be nice to get the full amount of data via the Analytics dashboard, as users would generally see and use the data there.

![Screen Shot 2021-07-14 at 8 30 19 AM](https://user-images.githubusercontent.com/1406618/125628075-48a4e444-8921-4fde-9d92-57ae58f9f17d.png)
