### ISSUE TITLE
Issues with spaces in ingested filenames

### ISSUE THREAD

**Issue by apertome** [avalonmediasystem/avalon#4414]
### Description
In some cases, spaces in filenames cause issues. Specifically, the files are ingested and encode properly, but when attempting to view these items, the player does not show up on the page.

@phuongdh suggests that this might be specific to the MinIO - is this in dev environments only ?

### Done Looks Like
Ingesting files with spaces should work in all environments, and the player should appear normally on the page.

**Comment by apertome** [comment]
![broken player.png](https://images.zenhubusercontent.com/588a4d5451aa2c305772e62f/c4e1afe5-8418-46bb-9541-9811e84d13fa)

**Comment by apertome** [comment]
I triggered this by uploading an .ogg file with a space in the filename. May apply to other file types as well.

**Comment by joncameron** [comment]
Merged with broader issue #3926
