### ISSUE TITLE
Add Instance Information in Comments Mailer

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4424]
### Description
The 'contact us' form at /comments doesn't add anything to the email beyond the contents of the form. This should contain instance information so that emails coming in from potentially multiple instances. 

### Done Looks Like
- Instance name ("name" value in settings.yml) is added to the emails generated by the contact form
- "Site: #{name}" is added as the third line of the email, after the "Submitted by user:" line

**Comment by apertome** [comment]
Also make these details configurable?

Ideally, I'd like to see some sort of instance identifier in the subject lines of the e-mails.

**Comment by joncameron** [comment]
Another option: separate sender emails from each instance.
