### ISSUE TITLE
Update docker base images and ruby/node versions

### ISSUE THREAD

**Issue by apertome** [avalonmediasystem/avalon#4440]
For `avalon-bundle`, we upgraded to newer versions of the base docker images, and newer nodejs and ruby versions. We have not seen any issues after doing that.

We need to do the same thing for the `avalon` project. Maybe `avalon-docker` as well? Anything else?

**Comment by bjoernmartin** [comment]
I just created https://github.com/avalonmediasystem/avalon-docker/issues/58 since the Docker setup does not (seem to) work anymore. Maybe because this task needs doing?

**Comment by apertome** [comment]
These are not really the same issue, but both are changes to the docker build, so might as well tackle them at the same time.

**Comment by mcwhitaker** [comment]
@srongala  Could you please smoke test spruce and report issues here if you find any? Thank you.

**Comment by mcwhitaker** [comment]
@Dananji  will test this since it is not spruce and it is not smoke testing that we need. We need to test if the docker install works.
