### ISSUE TITLE
No User Feedback When Using Remove Button for Captions on Masterfile 

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4446]
### Description
Clicking the "Remove" button appears to clear the subtitle file, but only after a refresh of the page. There's no feedback to the user that the caption has been removed, and the filename is still populated to the left of the button.

### Done Looks Like
- Notification message to user appears letting them know the caption has been removed
- Caption filename in UI disappears when the caption is removed

**Comment by Dananji** [comment]
Cannot reproduce this on spruce, hence closing.
