### ISSUE TITLE
Investigate FLO Docker Deployment

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4456]
### Description
FLO is currently experiencing issues with their Docker deployment. The Avalon team will try to assist in resolving these with an eye to fixing any problems coming out of our specific Docker deployment info. 

### Done Looks Like
- Investigation and assistance for Avalon Docker

**Comment by mcwhitaker** [comment]
Abandoning for the moment because we have asked Phuong to help FLO directly. We will see if they come back with more questions.
