### ISSUE TITLE
update Avalon Repo Readme 

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#4478]
### Description
https://github.com/avalonmediasystem/avalon/tree/v7.2.1 - the Readme has links to installation docs from 2016. We need to have this updated.

### Done Looks Like
- Link in README updated to https://wiki.dlib.indiana.edu/display/VarVideo/Manual+Installation+Instructions
- Linux/macOS specific instructions removed in favor of generic manual installation instructions

**Comment by joncameron** [comment]
@joncameron  will redirect the pull. This should be merged right into main.
