### ISSUE TITLE
Docker image mediainfo issues

### ISSUE THREAD

**Issue by apertome** [avalonmediasystem/avalon#4486]
Docker images are broken and currently won't build due to errors trying to install mediainfo. It appears that their debian package repo has changed and now some of the files aren't found.

Need to fix this, and hopefully find a way of installing medainfo that's less fragile.

**Comment by mcwhitaker** [comment]
Put this on hold, waiting for the DevOps Engineer to create a staging docker environment.

**Comment by joncameron** [comment]
Already merged something that handles this; closing.
