### ISSUE TITLE
Supplemental File Support for API

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4520]
# Description
The API currently does not provide the ability to add supplemental files to objects or files. Objects are frequently created and edited via the API and the ability to add or remove supplemental files would be convenient to have available. One example is creating an item that has a caption file.

Should consider whether this could also work for bringing in supplemental files from AMP.

# Done Criteria
- [ ] Investigation and notes document compiled to decide on how to implement this feature

# Q
- What are the uses cases?
- This could live multiple places within the interface
- Write the spec, then attempt implementation

**Comment by elynema** [comment]
This work is already completed as part of #5801.
