### ISSUE TITLE
Updating manifest generation to use IIIF 3.0 Presentation

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#4532]
### Description

Avalon generates IIIF manifest for each media object. This is performed on the fly when you visit `media_object_url/manifest`. And this manifest generation seems to be partially using the presentation API 2 ([v 3.0 changelog](https://iiif.io/api/presentation/3.0/change-log/)).
We also have the timeliner in avalon currently using a IIIF manifest for rendering of the component, but this might be different from what is mentioned above. As per the notes below there are 2 code segments in `media_objects_controller` and `timelines_controller` for handling manifests.

IIIF manifests in avalon needs to be fully updated to use Presentation 3.0.
Validator for Prezi 3 compliance: https://iiif.io/api/presentation/validator/service/

#### Notes
- Code for manifest handling for media object: https://github.com/avalonmediasystem/avalon/blob/develop/app/controllers/media_objects_controller.rb#L465-L484
- Code for manifest handling in timeliner: https://github.com/avalonmediasystem/avalon/blob/develop/app/controllers/timelines_controller.rb#L196-L203
- A sample manifest in Avalon: https://spruce.dlib.indiana.edu/media_objects/474299231/manifest
- Maria's thoughts;
> I looked at the rest of one of the manifests and think that the "service" is probably the problem for validators to accept our manifests. If you have a way to try one of MCO's manifests excluding the service elements and the @ from @none, we may actually find that this is all...

**Comment by Dananji** [comment]
I used a IIIF manifest from MCO in the IIIF validator without `service` and `@` from `@none` tags. And found the following issues that needs to be fixed;
1. `Annotation` requires an `id` property
2. Cannot have `null` values for properties. Ones that I came across when testing are, `label`, `value` in metadata, `height`, `width`. Instead of null values use `{ "none": [] }`.
3. `homepage` property accepts an array

Manifest tested: https://gist.github.com/Dananji/ecd53e3a3d802e62b07c8c1c794a2210, to test this in the validator, I put this on maple [here](https://dlib.indiana.edu/iiif_av/iiif-player-samples/transcripts/mco-manifest.json).
Changes from above made to make it valid: https://gist.github.com/Dananji/ecd53e3a3d802e62b07c8c1c794a2210/revisions?diff=unified

**Comment by cjcolvar** [comment]
Fix for #2 with `height` and `width` submitted to `iiif_manifest`: https://github.com/samvera/iiif_manifest/pull/59
Fix for #3: https://github.com/avalonmediasystem/avalon/pull/4536

**Comment by joncameron** [comment]
@joncameron will break any remaining items here into separate issues.

**Comment by joncameron** [comment]
#4596 and #4597 are broken from this ticket as the remaining pieces of work identified.
