### ISSUE TITLE
Testing that tools are in place and function correctly

### ISSUE THREAD

**Issue by apertome** [avalonmediasystem/avalon#4550]
We need a way to test that ffmpeg, mediainfo, yarn, and and probably other, similar tools are in place, running correct versions, and they work correctly.

There seem to be some extra plugins for ffmpeg that we need and certain versions of these tools that we require, but it's not clear exactly which those are.

The idea here is to make sure that these tools are in place in all the places they need to be. For instance, the `worker` container needs ffmpeg at the very least. Right now the only way to notice it's missing is by manually checking inside the container, or trying to encode something and then figuring out why it failed, which is not straightforward.

### Possibilities
- Use rspec to test for binaries/versions
- Make sure binaries are runnable (correct arch etc.)
- Docker script on build or in container (maybe)
- Rake task on config change

### Done Looks Like
- Testing planned and implemented as per above

**Comment by apertome** [comment]
Per prior discussions, implementing this as a rake task.

**Comment by apertome** [comment]
Tools to check:

- [ ] ffmpeg
- [ ] mediainfo
- [ ] yarn

**Comment by joncameron** [comment]
What we have that Michael had merged and existing tests are good enough for now; can be re-evaluated as needed.
