### ISSUE TITLE
Troubleshoot/fix error in streaming server check on About page

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4555]
#  Description
Streaming server check is not responding properly in some environments even though streaming is still working correctly. The check, in theory, should work.

# Done Looks Like
- Issues with streaming server check improperly reporting is investigated

**Comment by joncameron** [comment]
Chris and Michael will check on this and figure out issues with Bamboo.

**Comment by cjcolvar** [comment]
I tested out the about page on our running instances that have different environments (ESS hosted, locally hosted, etc.) and all I tested appeared to be working okay except for ijccr-staging and archivo-staging which appear to have bad configurations.  I'll fix those and retest.

**Comment by cjcolvar** [comment]
Looking again I think these configurations may be correct but the wowza servers aren't responding so the errors are in fact correct.

**Comment by cjcolvar** [comment]
I think this is working as expected everywhere I've looked.  @apertome are you still running into this problem or can we close this ticket?

**Comment by apertome** [comment]
@cjcolvar I am still seeing this in my dev environment, but it's entirely possible that there is something messed up with my local configuration. I guess we might want to leave this open until we do a little more testing with the `staging` branch to make sure it's not showing up in other environments? Or open a new ticket for further testing.

**Comment by apertome** [comment]
![streaming_error2](https://user-images.githubusercontent.com/6306575/149574956-07605bef-ed64-4495-843f-b51f6efe29af.png)

**Comment by joncameron** [comment]
Closing since this may be only a dev environment issue.
