### ISSUE TITLE
Files From Web Upload Are Not Managed Correctly

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4568]
# Description
[Masterfile management](https://wiki.dlib.indiana.edu/display/VarVideo/Managing+Master+Files) is not being run on media processed through web upload. The Management setting configured by the Avalon admin should be respected for files that come in through either web upload or dropbox.

# Done Looks Like
- [ ] Files uploaded via web upload are have masterfile management applied as configured

**Comment by joncameron** [comment]
Double-check that this a fix for this is in the current code and that it's working correctly.

**Comment by cjcolvar** [comment]
This is resolved in Avalon 7.3, right?

**Comment by joncameron** [comment]
Resolved in an existing release, as Chris mentioned.
