### ISSUE TITLE
Remove fedora 3→4 migration code

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#4591]
# Description
Removing the fedora 3-> 4 code will help clean up the code base and avoid issues in the future where we are locked on old versions of dependencies in order to support this migration code.

We have a gem that was used for extending our migration tooling that is out of date and could create issues in the future if there are issues with the age of our dependencies. We can just drop this code instead of keeping it current. Some of the infrastructure there could still be maintained.

# Done Criteria
- Code for migration tooling identified and removed as needed

**Comment by joncameron** [comment]
Some work on this has been done as part of the Rails 6 upgrade. The fedora-migrate gem has been removed.

**Comment by joncameron** [comment]
Closing as the central part of this work is completed.
