### ISSUE TITLE
IIIF Manifest Generation - Add id Property to Annotation

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4597]
# Description
Avalon's IIIF manifests need a missing id property under the Annotation to be parsed properly by other viewers.

# Done Looks Like
- [ ] Avalon manifests have the id property to the Annotation.

# See Also
#4532

**Comment by masaball** [comment]
Fix submitted to `iiif_manifest`: https://github.com/samvera/iiif_manifest/pull/66
