### ISSUE TITLE
Rails 6 Migration

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4601]
# Description
- It is a priority to migrate Avalon to Rails 6 as 5.2 will be end of lifed very soon
- Blacklight and Bootstrap are necessary dependencies that also need to be upgraded

# Done Criteria
- Investigation into what needs to be done for migrating the current codebase to Rails 6
- Meeting or swarm time set aside for investigating
- Issues created for work needed for migration

**Comment by cjcolvar** [comment]
I'm working through dependencies right now and have open PRs for `active-annotations` and `speedy-af`.
https://github.com/avalonmediasystem/active_annotations/pull/3
https://github.com/samvera-labs/speedy_af/pull/8
Next on my list is `active-fedora_datastreams`: https://github.com/samvera-labs/active_fedora-datastreams/pull/8

Once the dependencies aren't blocking avalon then we should be able to update and test with Rails 6.0 and see what breaks both in CI and in the UI.

**Comment by cjcolvar** [comment]
The rails6 branch was merged but avalon-dev is refusing to start due to issues with autoloading/zeitwerk:
>DEPRECATION WARNING: Initialization autoloaded the constants Permalink, FrameSize, Identifier, MigrationTarget, MasterFileBehavior, MasterFileIntercom, SupplementalFileBehavior, Avalon::RDFVocab, MasterFile, WatchedEncode, FfmpegEncode, ApplicationHelper, Blacklight::LocalBlacklightHelper, Blacklight::ConfigurationHelperBehavior, Blacklight::ComponentHelperBehavior, Blacklight::Facet, Blacklight::FacetsHelperBehavior, Blacklight::RenderConstraintsHelperBehavior, Blacklight::RenderPartialsHelperBehavior, Blacklight::SearchHistoryConstraintsHelperBehavior, Blacklight::SuggestHelperBehavior, Blacklight::CatalogHelperBehavior, CatalogHelper, ConditionalPartialsHelper, DeviseHelper, MediaObjectsHelper, PlayerHelper, PlaylistsHelper, SecurityHelper, TimelinesHelper, UploadFormHelper, BrowseEverythingHelper, AboutPage::AboutHelper, Blacklight::UrlHelperBehavior, Blacklight::HashAsHiddenFieldsHelperBehavior, Blacklight::LayoutHelperBehavior, Blacklight::IconHelperBehavior, Blacklight::BlacklightHelperBehavior, Hydra::BlacklightHelperBehavior, BlacklightHelper, PreviewHelper, FontAwesome::Rails::IconHelper, Blacklight::Controller, Blacklight::SearchFields, Blacklight::SearchService, Hydra::Controller, Hydra::Controller::ControllerBehavior, Samvera::Persona::BecomesBehavior, ApplicationController, Admin, ACL, Hydra::ACL, UniquenessValidator, Admin::Collection, Lease, SpeedyAF::Proxy::MasterFile, DerivativeBehavior, DerivativeIntercom, Derivative, StructuralMetadata, SpeedyAF::Proxy::StructuralMetadata, FileUploadStep, ResourceDescriptionStep, StructureStep, AccessControlStep, and ActionText::ContentHelper.
>
>Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.
>
>Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload Permalink, for example,
the expected changes won't be reflected in that stale Module object.
>
>These autoloaded constants have been unloaded.
>
>Please, check the "Autoloading and Reloading Constants" guide for solutions.
 (called from <main> at /home/app/avalon/config/environment.rb:5)

We may want to consider using the old autoload approach instead of zeitwerk for now if possible.
