### ISSUE TITLE
No Collections Appear on Collections Index Page

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4616]
# Description
As an admin user, no collections are appearing on the collections index ("/collections"). There are collections in the system and Blacklight is showing them, but they're not appearing on this page like the should be. They do seem to be working and showing up on avalon-dev.

# Environment
https://avalon-staging.dlib.indiana.edu/collections

**Comment by joncameron** [comment]
<img width="1416" alt="Screen Shot 2022-02-24 at 12 43 53 PM" src="https://user-images.githubusercontent.com/1406618/155578563-e8ec3d23-1bb6-4599-b308-b10aa9e12097.png">
Seems like some of the packaged js/css might be missing.

**Comment by joncameron** [comment]
Might have to do with Rails environment; staging running in prod vs dev in dev. Asset compilation issue probably.

**Comment by cjcolvar** [comment]
I set the RAILS_SERVE_STATIC_FILES environment variable and restarted the service and it is working now.  I'm not exactly sure why nginx wasn't serving the static files itself, but letting rails serve them is fine for now.
