### ISSUE TITLE
Email Invite to New User Returns 500

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4617]
# Description
As an admin user, when I enter an email address on the Manage Users page and click the "Invite User" button, I get a 500 error message. This is happening on staging but I wasn't getting a 500 on dev.

# Environment
Staging, https://avalon-staging.dlib.indiana.edu/persona/users

**Comment by cjcolvar** [comment]
This is because the staging server wasn't configured to send email.  I did this and restarted the service and now it send email to iu.edu addresses.  I'm not sure why dev wasn't doing this but it could be because email doesn't actually get sent in the rails dev environment.
