### ISSUE TITLE
Update and Configure the Avalon Demo Site

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4626]
# Description
As a devops engineer, I want to know how to push new code to demo.avalonmediasystem.org and update configuration files.

# Done Looks Like
- Investigation and documentation into AWS deploy for demo.avalonmediasystem.org
- Demo site updated to 7.3
- Units added to the instance:
  - Avalon Media System
  - Samvera Community
  - Evaluator Collections

**Comment by cjcolvar** [comment]
I was able to successfully deploy 7.3 to the demo site, but I still need to investigate the units not loading correctly.

**Comment by cjcolvar** [comment]
The issue with the controlled vocabulary was that it was being overwritten by the example file in the Docker build.  I commented out this line in the demo branch and now the units are loading correctly.
