### ISSUE TITLE
"Checkouts" Page

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4637]
# Description
Top-level page "Checkouts" (/checkouts) page which displays the current user's checkouts in a tabular way with each , with buttons to take actions of returning a single item or all items. The checkouts list for a user queries the database for this information and renders it on the page.

# Done Criteria

 - The /checkouts page contains a list of the user's current checkouts
- Columns in the list:
 Title of the media object, which is hyperlinked to the media object route
 - Remaining time left on checkout (text)
 - Button with label "Return", which returns the item and removes it from this listing
 - The Checkouts page has a "Return All" button which returns all of the user's currently checked out items
- Admin users see all checkouts from all users
 - Only active checkouts should display by default
- A checkbox will enable the display of historical checkouts

**Comment by joncameron** [comment]
Columns for the Checkouts table for the database: checkout start time, when it will end, media object ID, user ID.
After this is created, decide on the best way to query it, from whichever page (media object, checkout listing)
The checkouts list for a user queries the database for this information and renders it on the page.

**Comment by joncameron** [comment]
2 issues:
- making the page
- adding it to the nav bar

**Comment by masaball** [comment]
With the merging of the display returned items PR, all functionality laid out in this has been implemented.
