### ISSUE TITLE
Smoke test avalon-dev

### ISSUE THREAD

**Issue by apertome** [avalonmediasystem/avalon#4653]
@cjcolvar and I smoke-tested avalon-dev this morning. Results below.

**Comment by apertome** [comment]
Global
- Many modals not working
- sidebar nav layout width uneven
- Most backend stuff is working. biggest exception is **Collection detail page/search** (see bold below)

- Red bar - "Could not complete log in" 
	- maybe this can be removed?
		- may be related to canvas/LTI cookie issues
		- might not need this anymore? might have been Safari only
	- showing up all the time now
- Getting results - Planet Earth 
- **Collection detail page/search**
	- **getting 500 from backend browse page**
	- **spins forever since search never completes**
- Contact form
	- It's here, probably good enough for testing.
	- Layout has a couple issues like selector inline 
- Catalog browse/search
	- Layout issues
	- thumbnails ok
	- "more" button not working in sidebar filters
-Media Item page
	- poster image edit not rendering right (seems to work)
	details/files tabs run together in sidebar
	- delete confirmation modal not working "Are you sure?" - Chris thinks might be bootstrap/SASS-related
	- issue with data attributes not being inherited?
		other instances of "Are You Sure might be broken too"
		- yes, i.e. Playlist Get a new link and Delete Selected (only shows No, Cancel and button doesn't work)
		- Delete Playlist one seems to display, but does not actually delete the item
	- Timelines
		Create a timeline works
	- Get a new link broken here too
	- Delete doesn't work here either - seems to be doing GET without /delete query parameter
		- Filtering working
		- Access Control modal doesn't work
- Selected Items
	- Bulk update stuff is working
	- Unchecking select all doesn't deselect. selecting it doesn't select all, either
		- or on search results page
		- selector we're using probably isn't working anymore
		- 
Encoding Dashboard
- Looks good

Manage
- Mange Groups looks good
- Manage Users also looks good
	- "Become" works
- Manage Worker Jobs looks good
- Manage Content looks good
	- Assign Staff Roles layout needs work
	- Create Item 
	- Sidebar layout uneven
	- Resource Description - Remove buttons broken
	- Under Note(s), pulldowns not working for at least Statement of responsibility and usage
	- Structural metadata editor not displaying/working correctly
		- all the modals seem to have issues
	- Access Control seems OK
- Media object section selector broken
	- Embedding 
	- Add structure to playlist not working - modal 
	

LTI Context
- Avalon dev/staging need to be setup
	- Not sure if this is actually working or not, can't really test now
	- Embedding seems to work
	
- New/edit playlist
	- seems to work, layout reasonable
	- datatables look fine

**Comment by apertome** [comment]
Here are screenshots, these should roughly correspond with the above list. Can improve formatting later if needed.

![avalon_devdetailed_could_not_log_in](https://user-images.githubusercontent.com/6306575/160928235-1edaf0d9-a2d1-417a-bced-3c6e294418ee.png)
![avalon_devdetailed_media_listing_layout](https://user-images.githubusercontent.com/6306575/160928287-9115816f-0357-4b1e-9282-ac5d796b45bf.png)
![avalon_devdetailed_view_by_2_radiobuttons_selected](https://user-images.githubusercontent.com/6306575/160928288-c38005e4-beb4-4a76-a16a-0db99916e1de.png)
![avalon_dev_500_from_collection_landing_page](https://user-images.githubusercontent.com/6306575/160928291-6ddbf90d-78ad-4d2e-ab14-ad9ceeeffd55.png)
![avalon_dev_colllection_layout_overlapping](https://user-images.githubusercontent.com/6306575/160928295-067511e8-4b04-4f40-8cd3-42d43a4e49c9.png)
![avalon_dev_contact_us_layout](https://user-images.githubusercontent.com/6306575/160928297-00cccbb0-8688-4785-a0df-0ae62f38500a.png)
![avalon_dev_catalog_browse_layout](https://user-images.githubusercontent.com/6306575/160928299-c54a0f20-7912-4aea-8922-9134c943e026.png)
![avalon_dev_bootstrap_not_defined](https://user-images.githubusercontent.com/6306575/160928300-710a710a-4b35-46a5-9907-4702d1a9458a.png)
![avalon_dev_poster_edit_layout](https://user-images.githubusercontent.com/6306575/160928304-3d9d8e35-3718-4b49-9b53-640fafd4e541.png)
![avalon_dev_details_files_run_together](https://user-images.githubusercontent.com/6306575/160928305-989c52bb-c346-48da-8638-cb409f4b49e3.png)
![avalon_dev_delete_confirm_modal_not_working](https://user-images.githubusercontent.com/6306575/160928307-66cc4f53-5bc2-4561-9618-469cd09ac517.png)
![avalon_dev_get_new_playlist_modal_no_buttons](https://user-images.githubusercontent.com/6306575/160928308-3f3d19c6-3f24-4e95-a388-3a15d3850b5c.png)
![avalon_dev_access_control_modal_not_working](https://user-images.githubusercontent.com/6306575/160928311-70bfffee-8e2c-496d-909d-3e1aa0fe23f5.png)
![avalon_dev_item_edit_sidebar_layout](https://user-images.githubusercontent.com/6306575/160928312-45a0e7c9-d027-4e8c-94af-0b6f36b4edc4.png)
![avalon_dev_assign_staff_roles](https://user-images.githubusercontent.com/6306575/160928313-73da1582-b309-4381-9de7-4f63f62e0bde.png)
![avalon_dev_edit_mo_manage_files_no_buttons](https://user-images.githubusercontent.com/6306575/160928315-86f01a83-eda6-4fa1-8f37-ec724dfebe10.png)
![avalon_dev_edit_description_remote_buttons_broken](https://user-images.githubusercontent.com/6306575/160928317-718bb59e-e097-415a-9f49-d4c4b2dc85a4.png)
![avalon_dev_edit_res_desc_statement_of_responsibility_layout](https://user-images.githubusercontent.com/6306575/160928320-31669397-3d0d-4185-92cc-7a9447d97562.png)
![avalon_structure_edior_broken](https://user-images.githubusercontent.com/6306575/160928323-a770de13-bd3c-445d-b270-fe129f1ffd67.png)
![avalon_media_object_section_layout](https://user-images.githubusercontent.com/6306575/160928326-ffc2f1ce-dd74-49e6-b181-62ba854296b9.png)
![avalon_dev_structure_add_to_playlist_broken](https://user-images.githubusercontent.com/6306575/160928327-4cf2cb68-acf9-4aa4-bc0a-da5ec6b8e2c7.png)

**Comment by cjcolvar** [comment]
Streaming isn't working in development environments.  Probably due to SameSite attribute on cookies being different in http vs. https contexts.
