### ISSUE TITLE
Regression test avalon-dev

### ISSUE THREAD

**Issue by apertome** [avalonmediasystem/avalon#4654]
# Description
Perform the full set of Avalon test scripts on the current develop branch to catch any regressions stemming from the Rails 6 upgrade.

# Done Criteria
- [x] Perform the Avalon test scripts and create bug reports for anything that is not displaying or responding correctly

**Comment by joncameron** [comment]
Hey @ccsxw6 I’m using ZenHub in GitHub, [click this link](https://app.zenhub.com/workspaces/avalon-5bff96674b5806bc2bf90276/board) to join my workspace and see other features available in GitHub or [download the ZenHub extension](https://www.zenhub.com/extension) and sign up with your GitHub account. 
  _Posted using [ZenHub](https://www.zenhub.com)_
