### ISSUE TITLE
Improve docker/docker-compose documentation

### ISSUE THREAD

**Issue by apertome** [avalonmediasystem/avalon#4661]
A user pointed out that it's difficult to tell the difference between installing Avalon from `avalon` vs `avalon-docker`.

- [ ] What use cases is the `avalon` deployment supposed to cover?
- [ ] What use cases is the `avalon-docker` deployment supposed to cover?
- [ ] it appears that installing from the `avalon` project gets you more configurability -- but is that true, or is `avalon-docker` just not as well documented?

Additionally, the Docker install docs could be more clear in general.

**Comment by cjcolvar** [comment]
The docker-compose.yml files in `avalon` and `avalon-docker` are different and take different approaches to configuration / environment variable setting.  We should pick one approach and stick with it.

**Comment by cjcolvar** [comment]
`SMTP_ADDRESS` and `SMTP_PORT` are set in `dotenv.example` but I don't think they are actually used anywhere.  Instead these should be `SETTINGS__EMAIL__CONFIG__ADDRESS` and `SETTINGS__EMAIL__CONFIG__PORT` instead.

**Comment by joncameron** [comment]
This can also include the conversation of the approach we want to use, how we point people to our Docker images, and where Dockerfiles for services are.
