### ISSUE TITLE
Missing identifier_in_use for Noid::Rails

### ISSUE THREAD

**Issue by seanlw** [avalonmediasystem/avalon#4672]
While testing Avalon 7.3.0 I came across a situation where the Noid::Rails minter was returning identifiers that were tombstoned in Fedora. Although this situation should be extremely rare I wanted to bring this to your attention.

**Problem:** Creating new media objects would fail and return `Ldp::Gone`. Caused by a new media object identifier tombstoned in Fedora.

**Solution:** Set identifier_in_use function for Noid::Rails to check for existing or gone identifiers in Fedora

Adding the following to `config/initializers/noid-rails.rb` fixes the issue

```
config.identifier_in_use = lambda do |id|
  ActiveFedora::Base.exists?(id) || ActiveFedora::Base.gone?(id)
end
```

**Comment by cjcolvar** [comment]
Good catch!  Would you have time to create a pull request for this change?

**Comment by seanlw** [comment]
pull request made #4673
