### ISSUE TITLE
Format and Position of Metadata Information on Catalog Page

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4675]
# Description
The display of the metadata text and its layout in the listing of results in /catalog has shifted due to dependency updates. These should be restored to their previous states.

The metadata appears to be printing in a string representing an array value, for example:
> Date: ["1996"]
> Main contributors: ["Mahler, Gustav, 1860-1911."]

# Done Looks Like
- [ ] Metadata values (Date, Main contributors etc.) are presented as text and not wrapped as strings or array values
- [ ] Metadata appears to the right of the title and icon

# Screenshots
## Current
<img width="944" alt="Screen Shot 2022-04-20 at 11 47 23 AM" src="https://user-images.githubusercontent.com/1406618/164271465-b31853bd-f431-4d4d-bcf8-823c8e0d8895.png">

## Expected
<img width="930" alt="Screen Shot 2022-04-20 at 11 47 36 AM" src="https://user-images.githubusercontent.com/1406618/164271492-3fe89621-aa85-4062-846e-88ae07832653.png">

**Comment by joncameron** [comment]
Probably a Blacklight override that isn't quite right.

**Comment by cjcolvar** [comment]
#4685
