### ISSUE TITLE
Restore search constraints

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#4689]
The search constraints bar is missing after the blacklight upgrade.

![image](https://user-images.githubusercontent.com/1053603/165554978-826afdfe-02f5-439f-9574-c71f4c2ca769.png)

A place to start with this is to add `<%= render 'constraints' %>` before `<%= render 'search_results' %>` in `app/views/catalog/index.html.erb`.  This renders something but it looks very different than before.

**Comment by joncameron** [comment]
@cjcolvar I think the new style looks good! Let's adopt that.
