### ISSUE TITLE
homepage in Timeliner IIIF Presentation 3.0 manifest contains single object rather than array

### ISSUE THREAD

**Issue by jwd** [avalonmediasystem/avalon#4705]
# Description
Reported by @benwbrum in looking at compatibility of Avalon IIIF manifests with AudiAnnotate (https://github.com/hipstas/AudiAnnotate):

There seems to be a problem in the manifests produced from Timeliner: https://demo.avalonmediasystem.org/timelines/43/manifest.json

The homepage in this manifest is not an array of JSON objects as specified in the v3 spec, but rather a single object.

# Done Criteria
- [ ] homepage property is represented as an array in Timeliner manifests

**Comment by cjcolvar** [comment]
This is fixed for new timelines but will need additional work to migrate existing timelines.  Do you think this is sufficient or should we work on migrating existing timelines?
