### ISSUE TITLE
Add Checkouts Page to Nav Bar

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4720]
# Description
Adding the Checkouts page to Avalon's top-level navigation.

# Done Criteria
- [x]  "Checkouts (x)" link displays in the nav bar between Playlists and Selected Items, where x is the user's number of current checkouts
- [ ] "Checkouts" link does not appear to unauthenticated users

# Mockup
![Screen Shot 2022-03-16 at 2.45.58 PM.png](https://images.zenhubusercontent.com/5cc1c0106d0be2229caf2d9e/97e40055-e022-427e-acf2-bfecc51de30d)

**Comment by Dananji** [comment]
This is not in avalon-dev yet, since we are merging the work to a separate branch (cd_lending) till we cut 7.4 release from `develop` branch.
