### ISSUE TITLE
Add Lending Period Defaults to Form on Collection Admin Page

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4728]
# Description
When CDL is enabled, each collection's admin page should have additional elements on the form to edit the collection's default lending period. 

# Done Looks Like
- [ ] Collection model updated to include lending period 
- [ ] When a collection is created, the collection should inherit the application-level default for lending period
- [ ] The collection admin page has form elements where users can change the day and hour values for the collection's default lending period

# Notes
- A partial may apply to collection/media object/bulk updates UI and be able to updated to work across these contexts

**Comment by jlhardes** [comment]
Considering the following properties right now:

https://schema.org/eligibleDuration (associated with an Offer so I'm not sure if this property works on the Work itself, but it might)

https://schema.org/loanTerm (this is really meant for financial loans, so probably not a great fit)

https://w3id.org/timebank#hasExpectedDuration ([Timebank Ontology](https://tobiasgrubenmann.github.io/Ontologies/Timebank/0.2/index.html#hasExpectedDuration) for peer-to-peer service exchange so not e-commerce but still might want the subject to be the action - the lending request - and not the Work. The lending request has to be tied to the Work, though, so maybe this property or schema:eligibleDuration can be understood to express the type of duration?)
