### ISSUE TITLE
Modal Buttons Do Not Close Modal

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4770]
# Current Behavior
Some modals with buttons to take an action take the action when clicked, but the modal does not close and the user is not redirected as intended. The modal simply remains on the page; closing the modal and/or refreshing the page with updates shows that the actions did indeed happen.

# Expected
- [x] "Create Collection" button in create collection modal
- [x] "Update Collection" button in edit collection modal (collection admin page)
- [x] "Add to Playlist" button (add section to playlist modal)
close after taking the action.

**Comment by joncameron** [comment]
data-loading buttons used here: changes the text and processes the request then closes. This was also removed in Bootstrap 4.

**Comment by cjcolvar** [comment]
Fixed by #4776.
