### ISSUE TITLE
Fix Common Situations Where Avalon Returns 500

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4800]
# Description
Avalon returns 500s in many scenarios when it should fail gracefully, and instead should have a standard error response.

# Areas to Fix That Return 500
- [x] Bots Hitting OAuth Routes

https://app.honeybadger.io/projects/54117/faults/50910846
To resolve: LTI routes (i.e. /auth/lti/callback?target=noid) returns a user-facing error message (something like "authentication could not be completed for this request" via a splash message and/or a redirect to the home page.

- [x] Controlled Vocabularies  Missing

If the rightsstatement portion of Avalon's controlled_vocabulary.yml file is not present, attempting to render the resource description portion of a media object's edit page will result in a 500. This probably also applies to the other controlled vocabularies we use on the description page (identifier_types and note_types) as well as the collection create/edit modal (unit).

- [x] Student View in Canvas

When using the 'Student View' feature in Canvas which allows instructors to view the Canvas course as a student would see it, using a tool that connects to Avalon's LTI auth returns a 500.

- [x] Requests with Unauthorized Tokens 

https://app.honeybadger.io/projects/54117/faults/38184369
We should raise an unauthorized error instead of 500 when there is a stale token.

- [x] When the RMD service doesn't return
Experienced in IU production.

**Comment by joncameron** [comment]
At minimum, have something that catches the exception and returns something nicer, without having to log it to Honeybadger.

**Comment by joncameron** [comment]
Proposed general error message: 
"There was an error with this request."
For auth:
"You are not authorized to access this content."

Larger question: there are a lot of hardcoded strings for these in different areas of the application, some of which are duplicated. Could these be extracted to config/i18n files so we can reference a common set instead of inlining the text?

**Comment by joncameron** [comment]
Proposed general error message: 
"There was an error with this request."
For auth:
"You are not authorized to access this content."

Larger question: there are a lot of hardcoded strings for these in different areas of the application, some of which are duplicated. Could these be extracted to config/i18n files so we can reference a common set instead of inlining the text?

**Comment by masaball** [comment]
@cjcolvar and @joncameron, I've looked around but am not sure how exactly RMD is integrated or what the specific error is that the service not returning produces. Do we have any more info on that one? Also, is RMD integrated in a way that it makes sense to add error catching to the core application or would it make more sense to add it to the IU specific since RMD is an IU thing, correct?

For the student view in Canvas, I went into the Canvas course for LTI testing and poked around in there. There is an LTI auth link in the assignments section which leads to an error page. Is that the sort of behavior being referenced in the ticket or is something else meant by "tool that connects to Avalon's LTI auth route"? (Sidenote, the canvas course is really out of date. There are a lot of links/references to Mallorn, `avalon-pilot.dlib.indiana.edu`, etc. Is that something we should look into updating?)

**Comment by masaball** [comment]
@joncameron I expect it would be doable to move most, if not all, messaging into i18n files though it will probably be a fairly large task. We would need to identify all the places that have hardcoded strings, determine whether there are any similar phrasings that can be condensed to one reference, and then actually make the changes. Still probably worth an investigation to see how big a problem we have.

**Comment by cjcolvar** [comment]
@masaball The RMD integration is in the IU fork for customization/deploys.  We could pair on this or I could take care of it.

**Comment by masaball** [comment]
@cjcolvar Let's go ahead and pair on this. I think it would be beneficial for me to see your approach on it and talk through it.

**Comment by joncameron** [comment]
Is the PR ready to merge, or do the Code Climate tests need to be fixed? The changes look good to me 👍

**Comment by masaball** [comment]
Thanks for the reminder Jon. I went and fixed the ones that it made sense to fix. The `html_safe` test is not an issue and I think the "Favor format over string#%" is also fine to ignore. So once the rest of the test suite finishes running again, it should be good to merge.
