### ISSUE TITLE
Error when try to check-out item without authenticating

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#4836]
Checkout/return buttons should not appear if user is not authenticated.
 
@joncameron I assume the media is not available if not checked out. Seems like instead of disappearing, the checkout button should take user to the authentication page?

![image.png](https://images.zenhubusercontent.com/62d989a70c79cb5218735cd6/043050b4-d3c8-4d44-ae12-7b4d976372e2
)

**Comment by joncameron** [comment]
I agree, it makes more sense for the user to be taken to the auth page.

**Comment by cjcolvar** [comment]
We already do something like that here: https://github.com/avalonmediasystem/avalon/blob/main/app/views/errors/restricted_pid.html.erb

**Comment by joncameron** [comment]
Another approach: use a similar message as in the restricted_pid page, which appears in the player when the current session isn't authenticated (instead of the current text and Borrow button).

**Comment by joncameron** [comment]
This isn't possible with the change requested in #4838.
