### ISSUE TITLE
Return button and timer persist when CDL has been turned off

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#4841]
If Controlled Digital Lending is turned off while any items are checked out, the return button and timer still render on the item view page.![Screenshot_20220819_105607.png](https://images.zenhubusercontent.com/6266ac58486bbe54ed59bf57/90273692-9fbb-442c-882e-fc8a27c0da8d)

This is probably an unlikely case to come up in real world use, but a conditional should be added to handle this.

**Comment by joncameron** [comment]
May already be resolved in develop; can be closed if so!

**Comment by masaball** [comment]
Resolved already in work @Dananji had done. Closing.
