### ISSUE TITLE
Roadmap Building

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4852]
# Description
Following on from  our recent [roadmap brainstorm ](https://docs.google.com/document/d/1bgSbyZpJcAJCe3Lal2WaDc5FkZDLDVr4CBFUb_3tKYE/edit), update the roadmap document, assign rank and priority, and set timelines.

# Done Criteria
- [x] Priority roadmap items identified.
- [x] Roadmap updated to include features and approximate timeline
- [ ] Epics created

**Comment by elynema** [comment]
Ruby 2.7 is EOL end of March 2023; Rails 6.0 is EOL in June 2023. Rails 7 / Ruby 3.1 upgrade in 7.6?

**Comment by elynema** [comment]
@joncameron Meant to share this awhile ago, but I aligned some thoughts for the next couple of releases here: https://docs.google.com/document/d/10Fm0XismDrYeapZxkEV9C2hECOIHpXIowPnZgH0PI90/edit

**Comment by joncameron** [comment]
Going to close this now; I've added 7.5.1 for a bugfix release as discussed.
