### ISSUE TITLE
Sanitize Filenames Before File Processing

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4855]
# Description
Following on from investigation in #3926; fixing issues caused by characters in filenames. Using a subset of the AWS object guidelines would be ideal. [Mason's notes](https://github.com/avalonmediasystem/avalon/issues/3926#issuecomment-1226430308) in that ticket contain more detailed information.

## Safe Characters

- Alphanumeric characters 	
    0-9
    a-z
    A-Z
- Special characters 	
   Hyphen (-)
    Underscore (_)

# Done Looks Like
- [x] Filename sanitization happens before any further handling and processing (consistently and adapter-independent)
  - [x] Characters not matching the safe set above in filenames are changed to a value within the safe set (unsafe characters are always changed to underscore or hyphen)
  - [x] Spaces in filename are replaced with underscores
  - [x] Periods in the filename removed (excluding the standard period between the name and the extension). 
- [x] Hard-coded [check to fail non-ASCII characters](https://github.com/avalonmediasystem/avalon/blob/90832296809f3684405acb7b4e44d7ed0720d92e/app/services/master_file_builder.rb#L37) removed 
- [ ] Cut release for Active Encode
- [ ] Update gemfile in Avalon
- [ ] PR to Avalon to set threshold (0, or 95%)

**Comment by joncameron** [comment]
Single sanitizing step before adapters are called, instead of repeating within the adapter itself.

**Comment by cjcolvar** [comment]
Maybe the sanitization can go into a `before_create` callback that lives in an `ActiveEncode::Sanitization` module?

**Comment by masaball** [comment]
The changes to active encode handle double quotes fine, but Avalon had some trouble with locating the file to send to ActiveEncode. This was due to an automatic conversion of `"` into `%22`, the unicode representation. Conversion to unicode does not seem to be an issue with other special characters. When the new ActiveEncode is brought in, I have a commit prepared to handle this case.
