### ISSUE TITLE
ActiveEncode ffmpeg error messages need refinement

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#4860]
Upgrading to ActiveEncode 1.0 brings with it capture of the ffmpeg error log.  This allows encodes to surface stderr output which might be non-fatal instead of failing encodes.  Running this in producation at IU has revealed that ffmpeg can be very verbose at the default log level (sometimes greater than 16MB).  This leads to overflowing the DB column for raw_object of ActiveEncode::EncodeRecord, poor UX in the encode dashboard and item view page (which only care about the first value in the encode's errors), and sometimes solr indexing errors when trying to tokenize the ffmpeg logging.

I think we should do a few things to improve this:
- Change the default ffmpeg loglevel to "error" to reduce the amount of logging
- Invert the order of the errors on the encode object so failure error messages appear first before the dump of the stderr output
- Add a human-readable, explanatory note to the errors on the encode object before the dump of the stderr output to improve UX when the encode doesn't fail.  "Error encountered during encoding. Check ffmpeg log for more details."

Implementing these changes will require PRs to ActiveEncode and Avalon and probably a patch or minor release of ActiveEncode.

References
`-loglevel` https://ffmpeg.org/ffmpeg.html
Related ActiveEncode issue which came up when investigating this: https://github.com/samvera-labs/active_encode/issues/110

**Comment by cjcolvar** [comment]
ActiveEncode was already setting the ffmpeg loglevel to `error` so I did some testing with one of the files that generated these long error logs and found that all of the logging was `error` level.  As a result I think we need to bump loglevel to `fatal`.  I think it might also be nice to set the `level` flag which will log the level of the message in brackets before the message (e.g. `[error] Skipping invalid frame`)

**Comment by cjcolvar** [comment]
I think all of these changes are handled in https://github.com/samvera-labs/active_encode/pull/111

**Comment by joncameron** [comment]
I approved but didn't merge https://github.com/samvera-labs/active_encode/pull/111
