### ISSUE TITLE
Handle Ldp::Gone errors in ApplicationJob

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#4869]
We see a number of job failures in production from jobs being enqueued and running after objects have been deleted.  The Ldp::Gone failure will never resolve on future retries because the object will never be resurrected.  We should handle this case better so it doesn't error and waste resources by retrying the job.  We should be able to cover all failure cases by handling Ldp::Gone errors in a rescue block in ApplicationJob.

# Done Criteria
- [ ] Handle failure cases in a way that doesn't raise Ldp::Gone errors

**Comment by joncameron** [comment]
https://app.honeybadger.io/projects/54117/faults/95485115

**Comment by joncameron** [comment]
When an item is deleted and jobs are still enqueued, things don't proceed properly and the enqueued jobs all fail out with 500 errors.

**Comment by joncameron** [comment]
I tried creating and deleting an item in dev while watching the log but I wasn't able to trigger the LDP or maybe couldn't find the error in the log. Still going to close this as QA'd as this as it will most likely be seen in production.
