### ISSUE TITLE
Investigate Uppy.io - OneDrive/Sharepoint Support in Avalon

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4870]
# Description
Microsoft OneDrive/Sharepoint is a widely available storage service used by institutions such as IU with contracts for Microsoft services. File upload with BrowseEverything should support this cloud storage service in addition to the Google Drive functionality recently added in Avalon, or we should investigate another library that could fill this role.

# Done Criteria
- Investigate uppy.io as a Browse Everything alternative
- Investigation into writing an adapter for Browse Everything to support Microsoft cloud storage - is this a worth the effort or should we look to another library?

**Comment by cjcolvar** [comment]
API documentation is here: https://learn.microsoft.com/en-us/onedrive/developer/rest-api/?view=odsp-graph-online

**Comment by joncameron** [comment]
Here's one library I came across: https://uppy.io/.

**Comment by joncameron** [comment]
Also: https://github.com/msg7086/rb1drv

**Comment by elynema** [comment]
Uppy is more of a component library. Requires Node 14. Dananji will try a prototype.

There are other lightweight JS libraries that allow other features like drag and drop, resumable uploads, multiple files.

**Comment by elynema** [comment]
Timeliner build tools are only compatible with Node 12. However, Avalon brings in Timeliner as a built tool, so that should not impact Node 14 for Avalon. Digirati offered to look at upgrading Timeliner build to Node 14 at some point.

**Comment by elynema** [comment]
Google Drive integration requires a node server - can write with Express.js. Or can bundle inside the Avalon Docker container so that it comes up with all other services. Dananji will create a ticket for this and talk to Chris.

**Comment by cjcolvar** [comment]
Uppy provides a docker image for the Companion server which we could add into our docker-compose. See:
https://uppy.io/docs/companion/
https://hub.docker.com/r/transloadit/companion
https://github.com/transloadit/uppy/blob/main/packages/%40uppy/companion/KUBERNETES.md

**Comment by elynema** [comment]
Jon D. noted that Uppy does not currently support Sharepoint, which is what our staff would use for any shared drives. Need to investigate whether this could reasonably be added.
