### ISSUE TITLE
Reduce Custom Images for Avalon Docker

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4887]
# Description
We use custom images in our Docker Compose setup that may be better suited to be newer versions of these dependencies or community packages.

# Done Criteria
- [ ] Evaluate and list existing custom images to retire
- [ ] Replace previous custom images with community versions as possible

**Comment by cjcolvar** [comment]
With the upgrade to Fedora 6, the only custom images left in our docker-compose.yml are avalon and nginx used for VOD streaming.  Both of these require custom builds so I think we can close this ticket as done.  (When the ticket was created both fedora and solr also required custom images which is no longer the case.)
