### ISSUE TITLE
iOS 12 MCO Login

### ISSUE THREAD

**Issue by ccsxw6** [avalonmediasystem/avalon#4900]
Unable to login to MCO with iOS 12. Getting an Error - Stale Request message each time. 

# Done Criteria
- [ ] Added to MCO issues page in the IU KnowledgeBase

**Comment by joncameron** [comment]
This is probably from the SAML auth flow (outside of Avalon). Could be an issue with the device or syncing.

**Comment by cjcolvar** [comment]
I tried iOS12 with Safari and Firefox on BrowserStack and was able to successfully login on both.

**Comment by elynema** [comment]
@ccsxw6 Chris S. can you try this again? Looks like it might have been a temporary issue.

**Comment by ccsxw6** [comment]
I just tried it again with an iPhone XS with iOS 12 on Safari and Chrome, and I'm still getting the same Error - Stale Request.

**Comment by cjcolvar** [comment]
@ccsxw6 A few questions to help me debug:
- Did you test with browser stack or a physical device?  
- Is this logging into MCO or mco-staing?
- Are you logging in with your personal IU account, a guest account, or a group account?

**Comment by ccsxw6** [comment]
@cjcolvar I used the live interactive cross browser testing feature with browserstack. I had the same issue with MCO and mco-staging. I would be logging in with my personal IU account, but I get the Error - Stale Request message before being able to enter my login information

**Comment by elynema** [comment]
@ccsxw6 Let's take a look at this on Monday since no one else has been able to replicate.

**Comment by ccsxw6** [comment]
Here's an image of the error! Replicated with Emily and Jon today. 
<img width="913" alt="Screenshot 2022-10-17 115323" src="https://user-images.githubusercontent.com/72877761/196224976-22d69fdc-e275-4131-a3f0-46f6501ec102.png">

**Comment by joncameron** [comment]
We have iOS 10+ listed on our supported platforms page (https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957953567/Supported+Browsers+and+Platforms). This could be something to put on the MCO issues page: https://kb.iu.edu/d/anzb

**Comment by joncameron** [comment]
Submitted update to KB doc.

**Comment by joncameron** [comment]
https://kb.iu.edu/d/anzb
