### ISSUE TITLE
Cache SOLR requests for Media Objects with many items/sections

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#4902]
### Description
Media Objects with hundreds of items/sections can take as much as 60+ seconds to load. The largest portion of this load time is due to hundreds of SOLR requests that get made.
![Screenshot_20221004_155353.png](https://images.zenhubusercontent.com/6266ac58486bbe54ed59bf57/6aa0ad59-a65c-4a56-b33c-7ec7a5b43436)
Implementing caching on the #post method in policy_aware_modification.rb should improve load times. If we can cache all objects in advance, all further requests for data about the object should hit the cache and be super fast.

[faraday-http-cache](https://github.com/sourcelevel/faraday-http-cache) is the most likely route for caching.

# Done Criteria
- [ ] Explore caching strategies
- [ ] Evaluate rewriting of code to reduce overall requests
- [ ] Explore Presenter pattern - central point for caching for UI

**Comment by cjcolvar** [comment]
FWIW It looks like permissions queries are getting cached (at least within a request) by BlacklightAccessControls.
https://github.com/projectblacklight/blacklight-access_controls/blob/089cb43377086adba46e4cde272c2ccb19fef5ad/lib/blacklight/access_controls/ability.rb#L24

**Comment by masaball** [comment]
Chris and I looked at a couple options for implementing caching and ultimately decided to rework [SpeedyAF](https://github.com/samvera-labs/speedy_af) so that it will initialize a bulk load of the SOLR queries, which will allow the subsequent requests to pull from memory instead of querying the server.

The implementation is currently set up on MCO-Staging. As of now, it has reduced the time spent in SOLR on some objects by a factor of about 50. However, there is something happening in the background that is still causing items to load at the same, or worse, rates as before. We are looking into this phantom time, as well as options for reducing time spent in ActiveFedora.

**Comment by cjcolvar** [comment]
I'm working on a PR to speedy_af which should lead to a release.  Once that is done, then I will open a PR into avalon to pull in that release and make a few small changes in avalon.
