### ISSUE TITLE
Deploy new version of Timeliner

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#4907]
# Done criteria
 - New version of timeliner deployed to timeliner.dlib.indiana.edu

# Notes
IUBLibTech org in Github is the canonical home for Timeliner (combines our changes).

**Comment by cjcolvar** [comment]
Currently, it looks like staging and production both get built and deployed from the default branch.  I think we should make a `demo` branch which will deploy to production.  The default branch will continue to deploy to staging so all new changes will be automatically deployed, but we can have control over what gets deployed to production.  This would also allow for some customization of production, if needed.
Also as part of this work, we should rename the default branch to `main` to keep in line with other avalon projects.

**Comment by joncameron** [comment]
Already completed
