### ISSUE TITLE
User Notification When CDL Item is Available

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4915]
# Description
Being able to request notification when an item is available would be helpful to users. Currently there is a "check back later" message in the media player area.

"This item is due to be returned on #{date} at #{time}."

"Please sign in to see this item's availability"

# Done Criteria
- [ ] User can take an action to choose to be notified when an item is available
- [ ] When the item is returned, the user is emailed by the application 

# Button Text
"Notify me when this item is available"

# Email Text
#{item} is now available to be checked out. Click here to view this item: #{url}"

# Notes
- Does a hold queue need to be implemented? What if multiple people request a notification?

**Comment by elynema** [comment]
Waiting for feedback from MSU about a hold queue.

**Comment by elynema** [comment]
Per Joan Lindsay @ MSU on 10/25/2022

After further discussions, it seems that email notifications isn’t something we need to pursue at this time.  Having the due date publicly visible should be sufficient.

@joncameron Ok to close this issue?

**Comment by joncameron** [comment]
Yes, closing this one.
