### ISSUE TITLE
Timeliner manifest endpoint

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#4917]
### Description

While testing Timeliner generated manifests on various IIIF AV manifest consumers, an issue was raised that the Timeliner manifest endpoint does not respond to an `id` (https://demo.avalonmediasystem.org/timelines/59/manifest), but only to a `uri`(https://demo.avalonmediasystem.org/timelines/59/manifest.json) 

While the general Avalon manifest endpoint responds to both:
e.g.: `id`: https://demo.avalonmediasystem.org/media_objects/pk02cb02n/manifest and `uri`: https://demo.avalonmediasystem.org/media_objects/pk02cb02n/manifest.json

This was reported in, https://docs.google.com/document/d/17qoXCuOfKUxwDAh73Xxrykj1TCxZ0HzkPdchGj8HCLA/edit?usp=sharing

# Done Criteria
- [ ] Specify default format/extension in our Rails routing with Timelines

**Comment by joncameron** [comment]
Can confirm by retrieving https://demo.avalonmediasystem.org/timelines/59/manifest in the browser.
