### ISSUE TITLE
Deploy CORS headers fix to avalon demo site 

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#4918]
# Description
Issue #4763 was a fix for CORS headers in Avalon's manifests. Jon Dunn and the IIIF AV working group have asked us to push this specific fix out to the demo site in order to enable them to complete testing with Avalon-generated manifests in IIIF viewers (particularly Universal Viewer).

# Done Criteria
 - #4763 deployed to https://demo.avalonmediasystem.org/
 - #4917 deployed as well

**Comment by elynema** [comment]
Note @Dananji reports that #4763 does not appear to be fixed on Avalon demo site.

**Comment by elynema** [comment]
Can this be closed?

**Comment by cjcolvar** [comment]
Should we wait until https://github.com/avalonmediasystem/avalon/pull/4949 is merged and deployed to demo?

**Comment by elynema** [comment]
Good point. I was thinking that the initial work this ticket referred to was done, but you are correct that this task is just going to come up again. Waiting is good.
