### ISSUE TITLE
Problematic Behavior After Disabling CDL

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4925]
# Description
We're seeing odd behavior in the Avalon dev environment when attempting to disable CDL after it has been enabled (via settings). This needs to be investigated to see why this is the case and what the specifics are.

# Done Criteria
- Investigation into CDL behavior after disabling
- Could this be ameliorated by making CDL a collection-level disable/enable?

**Comment by elynema** [comment]
Dananji noted that the following morning (10/19), CDL had been disabled after attempting to disable it and restart the service the afternoon prior.

**Comment by joncameron** [comment]
Closing for a ticket to reflect the real issue that needs to be tested as per the comment above.
