### ISSUE TITLE
CDL Testing: Embeds, Playlists, IIIF manifests

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4926]
# Description
Are the embedded player, playlists and IIIF manifests working as expected when CDL is enabled? These routes need to be checked and tested to make sure the behavior is what we want.

# Note
Stream token checks will only assign a stream token if the item is checked out, so embedded player should still be able to get the streaming token once it's checked out.

# Done Criteria
- [x] Test media outside of the item page to ensure CDL functionality is working in those contexts

**Comment by elynema** [comment]
Hide embed link for CDL items and user facing message that says "this item cannot be embedded" in its place.

**Comment by elynema** [comment]
What happens in playlist after a user returns an item that was checked out and added to playlist?
