### ISSUE TITLE
Upgrade faraday

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#4933]
# Description
We should be able to upgrade to a 1.x or 2.x version of faraday.  This should also resolve the following deprecation warnings we're now getting.

```
Top level ::CompositeIO is deprecated, require 'multipart/post' and use `Multipart::Post::CompositeReadIO` instead!
Top level ::Parts is deprecated, require 'multipart/post' and use `Multipart::Post::Parts` instead!
```

# Done Criteria
- [x] Faraday updated and testing done as needed

See https://github.com/lostisland/faraday-multipart/pull/6

**Comment by elynema** [comment]
Done as part of #5088.
