### ISSUE TITLE
Closed captions not displaying in full screen on iOS

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#4935]
This is happening in production MCO, as well as avalon-dev, which suggests it's not related to the mediaElement.js upgrade. This issues was found across Chrome, Safari, and Firefox. When the video goes full-screen, the closed captions do not show. The captions do appear to show when the video is not closed caption, but iOS seems to default to full screen when you start playing a video, which makes it hard to test fully. When I clicked for picture in picture, the captions displayed in the player on the page, even though the video was showing in the picture in picture window.

Chrome on Android devices as well as on desktop (including Mac) seems to work as expected.

Example I used in testing: https://media.dlib.indiana.edu/media_objects/bk128b05q

# Note
iOS takes over with the native player, possibly; we need to make sure we're supplying the caption file in a way that iOS renders it in other surfaces/contexts.

# Done
- [ ] Investigate why this behavior occurs and how to ensure captions render on iOS

**Comment by cjcolvar** [comment]
Maybe all we need to do is add an attribute (`x-webkit-airplay="deny"`) to the video tag?
https://github.com/videojs/video.js/issues/6999

**Comment by joncameron** [comment]
https://github.com/mediaelement/mediaelement/blob/master/docs/installation.md#closed-captioning

**Comment by elynema** [comment]
It looks to me like quite a bit of video content is being chopped off when I hit full-screen in landscape mode, potentially because the browser window is still showing? This is iPhone 14 on Chrome.

![Screen Shot 2022-12-01 at 1.03.38 PM.png](https://images.zenhubusercontent.com/62d989a70c79cb5218735cd6/a25517e8-246f-4312-9175-5d97089f1353)

**Comment by Dananji** [comment]
I couldn't find a way to fix this. I think it'd be better to revert this change and use iOS's native player in fullscreen mode as it was before and list this as a known issue with the workaround we found (selecting captions in order CC -> English) to make captions work in the native player in fullscreen mode.

**Comment by elynema** [comment]
@Dananji I agree. @joncameron your thoughts?

**Comment by joncameron** [comment]
@Dananji @elynema After testing this out I agree that it would be best to revert. This does work in that captions render but there's lots of little issues with this method—browser UI elements still visible, changing device orientation snaps it out of the view you'd expect. It seems more trouble than it's worth, and flagging as a known issue until the actual best practice can be implemented seems good.

**Comment by joncameron** [comment]
Reverting this in favor of #4951
