### ISSUE TITLE
Embeds for CDL

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4940]
# Description
For CDL items there isn't a strong use case for embedding, and rather than handle the many cases in which it would not work correctly with CDL enabled, we can disable embedding for these items by displaying a message to users.

# Done Critiera
- [x] The embed link on the item page does not display on CDL items
- [x] Embeds display a user facing message that says "this item cannot be embedded"

**Comment by elynema** [comment]
@joncameron @masaball I see there is no embeds tab under Share for CDL items. I don't see a message that says "this item cannot be embedded" - did we decide to forego that in favor of just removing the entire Embed section?

**Comment by masaball** [comment]
I had understood the purpose of the message to be embeds that had already been created as opposed to replacing the link on the embed tab. As such, I added that message to the embedded player to be rendered for the circumstance if CDL were turned on for a collection where there were already be existing embeds and just completely hid the embed tab for CDL items. 

Was that the original intent @joncameron or should that be reworked?

**Comment by elynema** [comment]
We *did* want to display an error message to display in the embedded player, you are correct. I'm not sure if that is the best language (I thought instead we wanted to re-direct users to log in?).

**Comment by joncameron** [comment]
This is a good approach, but the the error message could be updated to be more clear to the user.

**Comment by joncameron** [comment]
Should the Embed panel be visible rather than hidden, and have a user-facing message about inability to embed on CDL collections? Probably yes.

**Comment by elynema** [comment]
@masaball @joncameron I think the new language you've used is fine, Mason. Let's get this PR merged for QA.

**Comment by joncameron** [comment]
Looks good!
