### ISSUE TITLE
Sharepoint Support in Uppy

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4946]
# Description
Uppy does not support Sharepoint currently: https://github.com/transloadit/uppy/issues/3837, but they encourage anyone to develop this functionality as a community project: https://uppy.io/docs/community-projects

# Done Criteria
- [x] Investigate means to enable connection to Sharepoint in Uppy
- [x] Create and estimate issues for adding this functionality if feasible

**Comment by Dananji** [comment]
From the investigation I found the following:

1. A fork of the Uppy repository with some initial work that had been done to integrate SharePoint support (https://github.com/szh/uppy/commit/29324c59943e6d01c5825e221913aa0c22877f89). This is a good starting point. There were some refactoring made in the Uppy code after this fork had been made. So I refactored these changes added to a fork of my own to test the code (https://github.com/Dananji/uppy/tree/sharepoint-investigation). And tested it with my personal Microsoft account (a free account without SharePoint), these changes adds new folder with the name 'Other Remote Drives' in the view to show the available SharePoint sites according to the code (the first unnamed folder in the screenshot contains the user's personal OneDrive files and folders).

![remote-drives.jpg](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/0bb84073-9da5-4bdf-8f82-51df40337931)

2. Website to see the endpoints available within the API, https://developer.microsoft.com/en-us/graph/graph-explorer.

As far as I understand, implementing this is feasible but a long-term project with figuring out both technical aspect of things with the API and permissions related work on IU's side. 

Please feel free to add feedback and do further investigation as necessary :)

**Comment by joncameron** [comment]
Following up: #5161
