### ISSUE TITLE
Copy playlist create options do not trigger redirects or reloads

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#4962]
When a user chooses the "Create and Edit" option, the playlist is copied but the user is not redirected to the edit page.

When a user is on the playlist table page and chooses to copy a playlist, the "Create" and "Create and Edit" buttons do not trigger a reload/redirect or close the modal. The playlist will be copied, but the user has to manually reload the page for the new copy to appear in the table.

**Comment by joncameron** [comment]
Could be related to Boostrap and modal upgrades. This seems like a regression.

**Comment by elynema** [comment]
Verified working in Chrome and Firefox.
