### ISSUE TITLE
Sorting playlist table by "Created" or "Updated" causes errors

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#4963]
The UI for the playlist table indicates that sorting is available on the "Created" and "Updated" columns, however when a user attempts to sort by either column they get a `DataTables warning: table id=Playlists - Ajax error.`

Sorting for those two columns needs to be reconfigured or removed.

**Comment by joncameron** [comment]
Probably a 500 server side error on returning the data.
