### ISSUE TITLE
Confirmation text for deleting items from a playlist differs between browsers

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#4964]
On Firefox, the confirmation for deleting an item(s) from a playlist is "Submit Query". On Chrome, the confirmation just says "Submit". 

![firefox.png](https://images.zenhubusercontent.com/6266ac58486bbe54ed59bf57/9cca936c-0e4b-44b2-a469-e0ef934c68aa)

![chrome.png](https://images.zenhubusercontent.com/6266ac58486bbe54ed59bf57/c63209b0-a85b-49e9-ba09-b870e2d2c53a)

Message should be consistent across all browsers.

**Comment by joncameron** [comment]
Due to browser defaults; this could be explicitly set to define the label text.

**Comment by joncameron** [comment]
Tested in dev 👍
