### ISSUE TITLE
Shared playlist login does not return user to the playlist

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#4965]
![playlist_login.png](https://images.zenhubusercontent.com/6266ac58486bbe54ed59bf57/1907976a-72e2-4188-95e6-a03733594b43)

If a user is not already authenticated and accesses a playlist they have a direct link for, the playlist page prompts the user to try logging in. The login link takes the user to the main login page but then redirects them to the Avalon homepage after they have logged in, requiring the user to re-navigate to the shared playlist.

Users should be round-tripped back to the shared playlist after logging in.

**Comment by joncameron** [comment]
This could be a redirect failing after login issue across the application.

**Comment by joncameron** [comment]
@elynema Playlists aren't accessible through LTI, so it sounds like testing is complete! We also don't have a means to test LTI on dev at the moment—we have to test on mco-staging against canvas-staging.

**Comment by elynema** [comment]
@joncameron It was on our list to test the login for LTI since changes were made to the overall login redirect, but we can do that as part of mco-staging smoke test as needed.
