### ISSUE TITLE
Error Processing Files With Missing Metadata

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4967]
# Description
Uploading webm files, and probably other containers that can be missing certain technical metadata, can result in an error and hung encoding job . Avalon's version of mediainfo and the latest version didn't appear to handle some files properly, and ffprobe wasn't functioning properly in initial testing as well. We should evaluate how to handle files with missing technical metadata that are otherwise fine. 

# Done Criteria
- [x] Decide what measures that are possible to take to accommodate files with these issues

**Comment by joncameron** [comment]
Limited to files generated by youtube-dl, or occurring for all webm files? Header issues could be problematic here.

**Comment by masaball** [comment]
Active Encode PR: https://github.com/samvera-labs/active_encode/pull/121

**Comment by masaball** [comment]
PR for pass through adapter changes: https://github.com/samvera-labs/active_encode/pull/123

**Comment by masaball** [comment]
PR for active encode version bump: https://github.com/samvera-labs/active_encode/pull/125

**Comment by joncameron** [comment]
Tested on dev with file_without_metadata.low.webm. Everything worked as expected with the exception of the poster/thumbnail image, which displayed the default icon and could not be updated using the usual method in the UI. I'll create a new issue for that.
