### ISSUE TITLE
Bad State for Create Collection Modal

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4975]
# Description
When creating a new collection via the the "create collection" button in the pop-up interface, the request to create the collection can fail and the user receives an error message. When re-opening the modal, the "create collection" button on the interface greyed out and the text changes to "saving...". 

# Expected Behavior
- [ ] When the modal is opened, the create collection button does not retain the grayed-out "saving..." state from a previous opening.

# Notes from Chris
I think what happened here is that the original create request failed but without a page reload the modal got into an odd state leading to this confusing behavior.  I wonder if we can fix that or if it would be better UX to avoid the modal and use a real page for collection creation.

**Comment by elynema** [comment]
Potential Bootstrap upgrade regression.

**Comment by Dananji** [comment]
After investigating this issue further, I realized this is not similar to what happened with copy playlist modals (as I mentioned when discussing this). Hence changing the estimate to 2 from 1.

**Comment by joncameron** [comment]
Proposed: move this from a modal to a page, and let Rails routing handle things.

**Comment by elynema** [comment]
Solution was to create a separate page for create collection, rather than a modal. Tested in Chrome / Firefox on Mac and Safari on iPhone and looks good. Tested trying to access create collection URL when not logged in; routed properly for both admin and non-admin accounts.
