### ISSUE TITLE
Aspect is Wrong in Fullscreen

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4986]
# Description
The video in an example item is in vertical orientation. The aspect maps correctly to the player on the page, but in fullscreen it doesn't show the full dimensions of the video

Example item:
https://avalon-staging.dlib.indiana.edu/media_objects/np193916n 

# Expected Behavior
- [ ] Aspect ratio is preserved when going fullscreen, in the same way it fits the dimensions of the media player within the page (letter or pillarboxed as needed)

**Comment by joncameron** [comment]
See if this still persists after reverting full-screen changes for iOS.

**Comment by elynema** [comment]
Testing with a vertical orientation video on avalon-dev in Firefox and Chrome; aspect ratio was retained in full-screen.
