### ISSUE TITLE
Upgrade Process for Terraform Script

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4991]
# Description
Updating our script for upgrades AWS installs of Avalon. While upgrading the Avalon demo, documenting the process and completing the tasks below.

# Done Criteria
- [x] Investigate upgrade process 
- [x] Determine changes to Terraform script as needed
- [x] Do it — Document process on wiki

**Comment by cjcolvar** [comment]
Decided not to pursue a pure terraform upgrade process at this time.  Instead document the existing process which involves running codebuild to create a new docker image and deploy it.

**Comment by cjcolvar** [comment]
https://github.com/avalonmediasystem/avalon-terraform/pull/39
