### ISSUE TITLE
Invalid URI Error

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5007]
# Description
When a non-expected value gets passed in for the NOID when requesting a media object or masterfile, the system throws an error. We can find a better way to handle requests? This is possibly something that Rails can provide.

# Done Criteria
- [ ] Bad ID values are handled before making requests to Fedora etc
- [ ] Quick pattern match/regex applied to IDs before further routing

(Timeboxed to a 3)

**Comment by cjcolvar** [comment]
Can use `noid` to test if a the request param is a valid id or not: https://github.com/samvera/noid-rails#minting-and-validating-identifiers

**Comment by joncameron** [comment]
Tested on dev with a bunch of crazy strings and I received the "Unknown item" page instead of a 500 each time.
