### ISSUE TITLE
Investigate Dependencies Requiring Ruby 3 Upgrade

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5017]
# Description
Evaluating our dependencies and creating a list of what needs to be upgraded to Ruby 3.

# Done Criteria
- [ ] List generated of Avalon dependencies and what version of Ruby they're on

**Comment by cjcolvar** [comment]
Need to upgrade to `rdf` 3.2 in order to use newer `ldp` which supports ruby 3.
This includes upgrading avalon to use `rdf-vocab` 3.2+ which is pinned to < 3.1.5 in order to keep old ebucore schema.
Also need to upgrade `active_fedora-datastreams` to use `rdf` 3.2+.

**Comment by elynema** [comment]
I believe the only Samvera dependencies we're waiting on are:

 active_fedora
 hydra-head
 noid-rails (This has a PR waiting to be merged which adds support)

**Comment by cjcolvar** [comment]
The dependencies that we're waiting for PRs to be merged and releases cut are:
- ActiveTriples
- active_fedora (draft PR ready)
- hydra-head (draft PR ready)
- noid-rails (draft PR ready)
- active_fedora-datastreams (draft PR ready)

**Comment by elynema** [comment]
Working toward ActiveTriples - may need to tackle at January Developer Congress. Working on a pull request to edtf-ruby (outside of Samvera), but they are normally responsive.

**Comment by elynema** [comment]
`om` helps us read/write MODS. Fell out of favor in switch from Fedora 3 to Fedora 4, since Fedora 4 uses RDF. A good inflection point to remove use of this would be when changing our datastore, including moving to Valkyrie.

**Comment by joncameron** [comment]
We can go back and get our forks on proper releases before cutting a release.
