### ISSUE TITLE
Upgrade to Rails 6.1

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5018]
# Description
Before upgrading to Rail 7, Avalon should be upgraded to Rails 6.1 first. 

# Done Criteria
- [ ] Update Rails within Avalon
- [ ] Test and Resolve Issues

# Steps
- Upgrade dependencies to 6.1
- Upgrade Avalon to 6.1
- Test and evaluate

**Comment by joncameron** [comment]
Kick off the build with an upgrade and see what breaks!

**Comment by cjcolvar** [comment]
`samvera-persona` doesn't allow rails 6.1+.  I'm looking into fixing that now.

**Comment by cjcolvar** [comment]
PR with passing tests: https://github.com/samvera-labs/samvera-persona/pull/57

**Comment by elynema** [comment]
We have a fork of media-info gem. Looks like media-info gem has been updated; we may want to investigate moving off fork back onto gem.
