### ISSUE TITLE
Improve performance of Media Object to_solr method

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5022]
From the investigation for #4939, the `to_solr` method in the media object model is the main source of slow down when saving media objects. When an object has many children, the processing time for retrieving the section IDs can be 15+ seconds and retrieving section labels can be dozens or hundreds of individual requests so those parts of `to_solr` are the most important to tackle.

Retrieving the section IDs uses a method defined by `ordered_aggregation` which is brought in from ActiveFedora or SpeedyAF so improvements to performance may necessitate behavior overrides in Avalon or changes to those gems.

Additionally, the `to_solr` method can be called 2 or more times depending on the workflow step, increasing load times even further. If it is safe to do so we should find a way to cache the `to_solr` calls or make it so that the method is only called once.

Looking for a 50% speed-up (hopefully more), but this is a starting goal and things might shake out differently depending on changes made.

# Done Criteria
- [x] Deep dive
- [x] Updates to code stemming from investigation

**Comment by elynema** [comment]
Work so far: Investigating kicking the Solr indexing out to a background job. Pull duration from Solr object instead of Active Fedora. Save of a 300 item object so far taking 10 seconds through console (big improvement over what it was before).

**Comment by joncameron** [comment]
Merge draft PR for this (more tests TBD), then close this issue.

**Comment by joncameron** [comment]
There should be more tests done (manual) before closing this to make sure things are behaving as expected. 
- Creating
- Editing
- Search results
- View pages, the player, manifests look good to end users after editing
- Things that are aggregated around the media object level (section titles, searching on words in structural metadata)

**Comment by elynema** [comment]
@charumitraravi did QA on this; closing.
