### ISSUE TITLE
Collection posters cannot have filenames with UTF-8 characters

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5027]
### Steps to reproduce:
1. Create a collection
2. Click Upload Poster
3. Choose a image file with a filename with UTF-8 characters (e.g. `きた!.jpg`)

### Expected Behavior
Image file should be uploaded and stored as the collection poster image

### Actual Behavior
Avalon raises an error: `incompatible character encodings: ASCII-8BIT and UTF-8`

![image](https://user-images.githubusercontent.com/1053603/211411609-1d28bcd3-1016-4698-9670-d8bd90411dbd.png)

**Comment by joncameron** [comment]
Notes: Active Storage was fine, but the reading back and rendering of the file is most likely the issue here.
