### ISSUE TITLE
SME Renders with No Waveform

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5038]
# Description
The SME should be able to handle manifests that have media but not accompanying waveforms.

Notes:
- With peaks.js there is a peaks calculator that could be used. Use of that needs to be investigated; takes a long time to render on long media. 
- Could also calculate the empty waveform and present that in SME, with note that it is not an accurate representation and is for use before waveform generation completes

# Done Criteria
- [x] Investigation into best method for dealing with lack of waveform data
- [x] When no waveform data is present, the SME still renders
- [x] A message to the user lets them know that no waveform will be rendered

# Definition of Done
- [x] If the media is a stream media file, SME can't generate waveform data. So it will display an empty waveform
- [x] If the video file is <= 5 minutes, a waveform will be generated on the fly
- [x] if the video file is >5 minutes, no waveform will be generated. Error message will read "No available waveform data". The waveform area of the SME will look flat.

**Comment by elynema** [comment]
Allow users to enter an external manifest URL to display in the SME demo site.

**Comment by Dananji** [comment]
When there is no waveform data specified in the IIIF manifest; 
- if the media file duration is less than 10 minutes => use WebAudio API to generate the waveform dataset using Peaks' `webAudio` option. This takes a while for larger files so we limit the use of this option for media files with duration less than 10 minutes.
- if not => create a dummy waveform dataset using `waveform-data` library (https://github.com/bbc/waveform-data.js) and feed it into the Peaks initialization method using `waveformData` option. And then display a persistent alert on the page with the message 
`Waveform data is not available (Using auto-generated dummy data instead).` OR appreciate it, if you can think of better wording to convey this message @joncameron :)

**Comment by joncameron** [comment]
How about: 
"No available waveform data."

Will/can the dummy waveform be flat?

**Comment by Dananji** [comment]
@joncameron This is how the dummy waveform data looks in the Peaks UI:

![waveofrm-dummy.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/2685192c-939d-4b6a-bf78-a21f6fed61a8)

Yes it's mostly flat.

**Comment by elynema** [comment]
In this scenario, are we just not creating waveform data for the files because it will take took long? If that's the case, I like Jon's proposal.

**Comment by elynema** [comment]
QA depends on #5079 getting pushed to the SME demo site. All this is waiting behind issues with #5086

**Comment by elynema** [comment]
@Dananji I am not seeing a waveform for this item that is 4:40 in length? https://media.dlib.indiana.edu/media_objects/js957061p/manifest.json
