### ISSUE TITLE
IIIF manifests must have an ID in the annotation and annotation body

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5040]
# Description
Last year Chris and I tried to add an ID to the annotation component for ticket #4597. After updating the IIIF manifest gem, we appear to have never updated the Gemfile.lock to use the updated gem (Avalon is currently using v0.6 when IIIF Manifest is on v1.2). 

In investigating for #5020 I updated my local Gemfile, however Avalon generated manifests were still missing the Annotation ID attribute. Additionally, when I added it manually I still received errors about the Annotation Body missing its ID.

Not sure if this is on the Avalon side or with the iiif_manifest gem.

# Done Criteria
- [ ] Generation of the Annotation field and its child components needs to be looked over again
- [ ] Ensure that any Annotation components and all their children are being properly assigned IDs

**Comment by masaball** [comment]
IIIF Manifest PR: https://github.com/samvera/iiif_manifest/pull/91

Looking at the [cookbook recipe for `choice`](https://iiif.io/api/cookbook/recipe/0033-choice/), we actually do not need an extra ID in the annotation body. The player I received that error on must not be set up to parse the `choice` construct and the error generated relates to standard manifest generation. As such, the PR only adds the id value at the Annotation level when generating the `choice` construct.

**Comment by elynema** [comment]
Verified that the Annotation is showing an ID on this item: https://avalon-dev.dlib.indiana.edu/media_objects/fj236208t/manifest.json

See `{"type":"Annotation","motivation":"painting","id":"https://avalon-dev.dlib.indiana.edu/media_objects/fj236208t/manifest/canvas/ng451h49f/annotation_page/a79dc591-36ae-4ffb-a82b-ffd48ae4474d/annotation/a72e856c-1ad2-4fbc-b12e-7e6a046d1974","target":"https://avalon-dev.dlib.indiana.edu/media_objects/fj236208t/manifest/canvas/ng451h49f"`

Annotation body does not have an ID.
