### ISSUE TITLE
7.5.1 Release Prep

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5041]
# Done Criteria
- [x] Compile fixed bugs to pull together for a 7.5.1 bugfix release

# PRs for 7.5.1
- https://github.com/avalonmediasystem/avalon/pull/5006
- https://github.com/avalonmediasystem/avalon/pull/5010
- https://github.com/avalonmediasystem/avalon/pull/5011
- https://github.com/avalonmediasystem/avalon/pull/5021
- https://github.com/avalonmediasystem/avalon/pull/5029
- https://github.com/avalonmediasystem/avalon/pull/5030
- https://github.com/avalonmediasystem/avalon/pull/5035
- https://github.com/avalonmediasystem/avalon/pull/5042
- https://github.com/avalonmediasystem/avalon/pull/5043
- https://github.com/avalonmediasystem/avalon/pull/5045
- https://github.com/avalonmediasystem/avalon/pull/5046

#5012, #5044, and #5025

**Comment by elynema** [comment]
This is pushed out to avalon-staging and needs to be tested.
