### ISSUE TITLE
Retain view of player / transcript for items with many sections

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5047]
# Description
The item page is works poorly for items that have many sections or lots of structural metadata. Currently, navigating a long list of sections requires scrolling the media player out of view. 

Users want to see the video or audio player and see the structure or description at the same time. Likewise, users want to transcript text and the player at the same time.

# Examples
- https://purl.dlib.indiana.edu/iudl/media/t64g650w9m
- https://purl.dlib.indiana.edu/iudl/media/d96k02k17z

# Done Looks Like
- [ ] Pre-existing UX design for player flexibility found and reviewed if possible
- [ ] Decision made on how to display player for this use case
- [ ] Styling changed to retain player within view

# Notes
- Timeboxed to a 3
- Floating the player is a top pick for a way to accommodate these use cases
- Sticking the player at the top of the page upon scroll is another possible option
- We could include our local UX expert for assistance in developing an improved user interface
- If we are moving Ramp to replace mediaelement.js, this work should be considered (and completed) in light of Ramp

**Comment by elynema** [comment]
Met with Matt Fitzwater yesterday and included this in our design request. If we scroll the sections, floating this may be less important.

**Comment by joncameron** [comment]
Styling changes will be incorporated as part of the broader redesign ticket.
