### ISSUE TITLE
Catalog not displaying item metadata

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5073]
The catalog is not displaying item information properly. I created a new Media Object with this metadata:
![Screenshot_20230222_104103.png](https://images.zenhubusercontent.com/6266ac58486bbe54ed59bf57/bbc8126f-6593-4166-ab12-477616332b72)
This is the display of that same item in the catalog:
![Screenshot_20230222_103411.png](https://images.zenhubusercontent.com/6266ac58486bbe54ed59bf57/b02ccc4e-5ba5-459d-8350-d3114df138a6)

This behavior can also be triggered for existing media objects by performing an action that causes the media object to save. May be related to the changes made for the to_solr performance improvement work.

**Comment by masaball** [comment]
Running searches for the full title or pieces of the title fail, so definitely an issue with the indexing.

**Comment by elynema** [comment]
Tested with new item and updating title, summary, contributor, main contributor, and date. All showed up in catalog view, search, and in facets.
