### ISSUE TITLE
Unit metadata not displaying for existing collections

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5074]
![Screenshot_20230222_102932.png](https://images.zenhubusercontent.com/6266ac58486bbe54ed59bf57/29beb6f4-2caf-4621-8511-f0c3b9cb3944)
On the item view page the Unit is not displaying correctly.  As can be seen in the screenshot it is being displayed as "/collections". This should read "Default Unit" or whatever Unit the collection belongs to.

This only occurs with existing collections. Any media object already belonging to the collection and new media objects that are created within the collection will display this metadata.

Unit information displays as expected for media obejcts added to a newly created collection. The display can also be fixed by re-saving the existing collection but that save triggers the behavior described in #5073 for all child items of the collection.

**Comment by joncameron** [comment]
Existing items displayed the Unit name for me, but when I created a new media object I saw the issue again after getting through the edit pages:
![Screenshot 2023-03-03 at 12.46.28 PM.png](https://images.zenhubusercontent.com/5cc1c0106d0be2229caf2d9e/69d33856-7d44-4d72-a245-cd7fc7022246)

**Comment by cjcolvar** [comment]
@joncameron I think this was an issue with bad data.  This didn't happen for me when I created a new collection and new item within that collection.  So I went to the collection for the item above and clicked Edit Collection and then save which populated the correct unit RDF predicate.  After that the item was fixed.

**Comment by elynema** [comment]
Tested editing metadata for an existing item in Testing collection in Default Unit on avalon-dev and for a new item added to that collection and a new item in a new collection. All seemed to work fine.
