### ISSUE TITLE
Colons Break Searching

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5089]
# Description
After a certain amount of colons in the title, search results do not display an item.

# Done Criteria
- [ ] Search results display when matched on title, regardless of characters within the title string

# Example
[Clio : 1983 Clio international preliminaries : Craft : Classic : Misc]

**Comment by cjcolvar** [comment]
I can reproduce this with Solr 6 but not with Solr 8.

**Comment by cjcolvar** [comment]
I made a hacky PR (#5101)  to remove unquoted colons from search strings but it broke other queries so I abandoned it.

**Comment by joncameron** [comment]
Another possibility is to find a quick fix and add as a customization to IU Avalon. This can move to the local project board.
