### ISSUE TITLE
Long filename expand/less not working for filenames with spaces

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5091]
# Description

Originally assumed this was a local Rivet styling issue, but seems to be a core issue handling filenames with spaces. Only older filenames have spaces, as spaces are now replaced by underscores (so this cannot be replicated on new uploads). 

See details in https://github.iu.edu/AvalonIU/Avalon/issues/144. 

Example:  https://mco-staging.dlib.indiana.edu/media_objects/3x816r63s/edit?step=file-upload

# Done Looks like

- [x] Long filenames are truncated by default (even if they have spaces)
- [x] expand/show less box allows viewing full filenames for filenames that are truncated filenames (even if they have spaces)
- [x] hover text shows full filename

Mason thinks this should be an easy fix to warp the variable in quotation marks when title attribute is assigned.

**Comment by elynema** [comment]
Section labels that are filled out will be used in lieu of filenames. Section labels were not going through truncation code; that has been added now.

**Comment by joncameron** [comment]
Looked good to me on mco-staging.
