### ISSUE TITLE
7.6 Testing

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5098]
# Test tasks
- [x] Batch ingest (Jon)
- [x] Media Player (Dananji)
- [x] Collection and item creation (Charu)
- [x] Edit Structure (Charu)
- [x] supplemental files (Emily)
- [x] transcripts (Emily)
- [x] Playlists (Emily)
- [x] Selected Items (Charu)
- [x] System management (Jon)
- [x] Access control - collection level (Emily)
- [x] LTI workflow (Jon)

Testing should be completed on https://avalon-staging.dlib.indiana.edu. To make sure permissions are working, test functionality with administrator and manager user. Aim to test on Firefox and Chrome and then also on an iOS and Android device.

Device testing is done via BrowserStack (you are welcome to test on your own mobile device if you would like). Info about how to get access to BrowserStack is available here: https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1963294731/Testing (Charu, let us know if you don't have access to that page). You will have to configure local testing (see note on that page) to test avalon-staging as it requires VPN.

Goal to begin testing around 3/15/2023.

**Comment by Dananji** [comment]
Tested media player on;
- Physical machine (Ubuntu): Firefox and Chrome
- BrowserStack: 
  - Android devices: Galaxy S23 (Firefox, Chrome), Google Pixel 7 (Firefox, Chrome)
  - iOS devices: iPhone 14 (Safari, Chrome), iPad 10th (Safari, Chrome)
  - Windows: Firefox, Chrome only. Edge keeps crashing on BrowserStack  
  - Mac: Safari, Firefox

**Fullscreen was not properly working in BrowserStack for desktop browsers for Windows and Mac. But this was tested on my machine thoroughly.

Found 1 issue on Android devices: #5118
