### ISSUE TITLE
Series Information in Metadata and Navigation

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5100]
# Description
Investigate series information (for metadata in Avalon) and add examples to ticket.

See [use case](https://docs.google.com/document/d/1zjvEJOJEINtaIyqYnvrsGJDXgKWUGDiL00AUxnKkwhw/edit) documented by IULMIA.

Requirements potentially include:

- repeatable Series field
- imports metadata from filmdb and IUCAT
- provides navigable hyperlink in the record view to show results for other items with that same series label
- field is indexed for searching
- potential desire to establish controlled series names to prevent mis-typing - could this be handled very simply with auto-complete? alternatively, could have a series entity with notes (but how/where would those notes display to the user?)

# Done Looks Like
- [ ] Compile use cases into a document
- [ ] Decisions made about how to handle Series metadata in objects and in UI
- [ ] New issues created

**Comment by elynema** [comment]
@joncameron Are you working on this one?

**Comment by joncameron** [comment]
I am—I just assigned myself.

**Comment by joncameron** [comment]
See #5272, #5269, #5273
