### ISSUE TITLE
Cannot delete users on avalon-dev or avalon-staging

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5103]
# Description

Charu and I were working on deleting and re-adding users for testing purposes and found the delete user functionality to be broken in both instances. 

On avalon-dev, I got a Persona error (I must have a timeline). I don't know if this might relate to the Ruby 3.2 upgrade? Or is this a problem that has always been there?

![image.png](https://images.zenhubusercontent.com/62d989a70c79cb5218735cd6/750cdf49-bc58-43d5-be69-0d43967abea1)

On avalon-staging, I'm getting this:

![image.png](https://images.zenhubusercontent.com/62d989a70c79cb5218735cd6/8d33e2f7-57ad-4a3c-a68d-c1a7bced4101)

The user I attempted to delete (elynema@iu.edu) has multiple Timelines in both instances.

The user was not actually deleted in either instance. If this is a longstanding issue, it can wait until after 7.6. If it's tied into the upgrade somehow, we should probably try to address it now.

# Definition of done

- [ ] delete user link on Manager Users page removes user
- [ ] Timelines associated with user should also be deleted (Is this the correct behavior?)

**Comment by elynema** [comment]
This bug is present on main, so not a new bug introduced as part of 7.6 work.

**Comment by joncameron** [comment]
Cascade the deletes to the timeline to avoid database errors.
