### ISSUE TITLE
[SME] Autopopulated end time for timespan doesn't have any valid parents

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5110]
For some files (possibly when shorter than 60 sec) the end time for a span is autopopulated with a valid value but which doesn't yield any valid parent headings.  Valid parents are found when the end time is adjusted to be shorter.

### Steps to reproduce
- Go to the problem item on avalon-dev: https://avalon-dev.dlib.indiana.edu/media_objects/3n203z084/edit?step=structure
- For the first section `sample-30s.mp4`, click `Edit Structure` then `Edit Structure` to open the SME
- Click `Add a timespan`
- Notice that the end time is autopopulated with `30.465` and that the `Child Of` dropdown has no options listed
- Change end time to `30.464` and notice that the `Child Of` dropdown now includes the root heading

**Comment by Dananji** [comment]
I tested this, and this seems to be an inconsistency with rounding time values in the code as Chris mentioned. 

When I went through the steps with the debugger on, in the dev tools in the browser; it produced the `Child Of` dropdown list with the root heading. This is without changing the autopopulated values in the form.
