### ISSUE TITLE
Add Timeout to FFmpeg Process 

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5117]
# Description
FFmpeg processes used for generating waveforms are hanging in the IU Avalon instances, tying up system resources and sometimes requiring a manual server cull of zombie processes. If they are not exiting as expected, Avalon needs to implement a timeout value to kill these FFmpeg instances.

Investigation issue (https://github.com/avalonmediasystem/avalon/issues/4709).

# Done Criteria
- [ ] Add timeout value for FFmpeg waveform process (15 minutes)
and possibly:
- [ ] Code change to avoid hangs (possibly refactor IO buffering)

**Comment by elynema** [comment]
Note that in #4709, @masaball already implemented a 1 hour timeout. We may need to re-discuss whether everyone is satisfied with that solution in the long-term.

**Comment by joncameron** [comment]
Created #5155; closing this as we've already implemented the timeout.
