### ISSUE TITLE
Player controls get hidden on playing timespans

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5119]
Reference:
https://avalon-staging.dlib.indiana.edu/media_objects/h415p952n

Steps to reproduce:
1.Open any item that has a media with timespans created. (Can test the item under the reference above).
2. Click on the timespan

Observed:
There is some random text shown momentarily on top of the video, and the video starts playing. The player controls (ie, pause,play, etc) gets hidden. https://images.zenhubusercontent.com/3336925/03cb99cf-55a6-4039-a8da-efeae0850b04/screen_recording_2023_03_13_at_1_15_13_pm__1___1_.mov

Expected:
The media player controls should be shown, and the player's progress bar indicator should visually skip to the start of the timespan.

**Comment by elynema** [comment]
@Dananji Charu was able to replicate the behavior where the media player controls disappeared on mco-staging, so it sounds like at least that part is not related to 7.6.

**Comment by charumitraravi** [comment]
@elynema @Dananji 
I was finding a few more player related issues in android and iOS , and I wanted to mention these here.

iOS (Safari browser):
Upon playing a media file, I was able to see multiple instances of the player on top of each other 
[Please check the video attached -https://images.zenhubusercontent.com/3336925/3f66d456-1b71-4a69-84cf-7d6e02f8ad0e/ios_safari.mp4 ]

Android - Chrome :
1.The same issue faced in the chrome web browser.This time, the issue happened when i was trying to play the video from the middle 
[Please check the video for reference -https://images.zenhubusercontent.com/3336925/2b843935-77d3-4d23-a2dc-f141b2203c88/android_chrome.mp4 ]

**Comment by Dananji** [comment]
The code to fix the player controls getting hidden is in the ME.js code. This is one more custom code snippet we have now in the ME.js code, which we need to test for when we upgrade ME.js.
Google sheet with the customizations in ME.js: https://docs.google.com/spreadsheets/d/1cfWEnROuov1cU5gi0ZjKT5HyKx7kjvxIU8XE_-tsLWM/edit#gid=18329696

**Comment by charumitraravi** [comment]
@elynema @Dananji 
Tested this issue on audio and video files, with multiple combinations of timespans and on the web (Chrome, Firefox) and Mobile devices (iOS - Safari, Android - chrome), and the player is working fine and the above issue looks fixed.

There was a slight behavioral change which I observed in the Firefox browser, which should'nt be a major impact for the user. Here is the video attached for reference:
https://images.zenhubusercontent.com/3336925/deb6965e-7eeb-4586-a846-3f87eb8f1e23/screen_recording_2023_03_29_at_2_03_05_pm.mov

Details of the above issue:
When I click on a time span (in the dev environment, where the fix for the above issue is pushed), the player progress bar disappears, although It can be viewed again when I hover over the player. I wanted to mention this behavior change, since this is not happening in staging (as shown in the video.)

**Comment by elynema** [comment]
@joncameron This is a minor behavior change; are you ok to close? Should we document this as a new issue?

**Comment by charumitraravi** [comment]
@joncameron I don't think it is necessary to document a new issue, since it is just a minor change. We can close this issue.

**Comment by charumitraravi** [comment]
Update: 
In android devices, I found that this issue is persisting, in a a different scenario: 

Steps: 
1. In an android device, Open a video file and start playing. 
2.While the video is playing, skip to the middle of the video through the player's progress bar. 

Observed:
The text is flashed on top of the player

@joncameron @Dananji @elynema

**Comment by charumitraravi** [comment]
@Dananji @elynema @joncameron 
The above issue looks fixed for the most part, except when I try an edge case scenario where when i skip through the progress bar fast manually (swipe through the progress bar), I can see some text on the player. This is seen in the web browser as well [Please find the attached screen [grab].]([url](url)) Although, the main issue, where the user actions were getting blocked, is fixed now. If this is just a negligible issue that wouldn't affect the user much, this can be ignored for now. @joncameron Let us know how we can go about this.

Note: I am unable to add attachments here, hence sending the screen recording on slack

**Comment by joncameron** [comment]
Will add to known issues; new issue to resolve at https://github.com/avalonmediasystem/avalon/issues/5148.
