### ISSUE TITLE
Directories and Files Not Appearing in Drive Adapter for Browse Everything

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5120]
# Description
Google Drive integration in Browse Everything is able to authenticate, but the listing of folders and files isn't working as expected. Subfolders do not appear under "My Drive", and no files or folders appear beneath the first child of the Shared Drives node.

# Environment
- Avalon staging, Firefox 111

# Expected Behavior
- Files and folders appear in Browse Everything as they exist in Drive's hierarchy

# Screenshot
![Screenshot 2023-03-22 at 1.47.12 PM.png](https://images.zenhubusercontent.com/5cc1c0106d0be2229caf2d9e/4097fb5c-8ed4-4de1-8193-788466cfdb58)

**Comment by joncameron** [comment]
Probably a conflict between Browse Everything versions and our specific customizations.

**Comment by elynema** [comment]
Importing into Browse Everything requires http URL, which was an issue with some of the sanitization added to Active Encode. This is an existing issue on MCO, so will include in 7.6 and cherrypick to MCO.

**Comment by joncameron** [comment]
Verified that it's working on avalon-dev. I connected to my IU drive and uploaded Lunchroom Manners from our Avalon team shared Drive: https://avalon-dev.dlib.indiana.edu/media_objects/hx11xf25t.
