### ISSUE TITLE
Applying collection level permissions to existing items in a collection requires saving twice

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5140]
# Description
After changing the item access or special access permissions for a collection at the collection level, applying those changes to ALL items in the collections requires saving twice. This happens consistently whether I choose to replace or add to existing special access entries. Applying to existing items a second time in the same way produces consistent results. This does not seem to be a data population error, as the item level records display the correct permissions populated from the collection (they're just not showing up for the user).

Assigning staff roles for the collection works as expected (but it's possible I just missed this in testing?). Removing special access or item access permissions seems to work fine the first try.

The video provides a screencast demonstrating this issue with voiceover.

https://images.zenhubusercontent.com/3336925/2d16685f-4d84-42d0-bff7-210ddcd3e315/video1361683169.mp4

**Comment by elynema** [comment]
Chris will put in a PR today with monkeypath to override gem. Need to re-test access control on existing and new items, especially collections where we first noticed this issue.

**Comment by cjcolvar** [comment]
Overrides PR: #5144

**Comment by joncameron** [comment]
I couldn't reproduce; will test on staging again before release.
