### ISSUE TITLE
FFmpeg Process Hangs During Waveform Generation

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5155]
# Description
FFmpeg processes used for generating waveforms are hanging in the IU Avalon instances, tying up system resources and sometimes requiring a manual server cull of zombie processes. A timeout value has been added to make sure these are cleaned on the server, but if they are not exiting as expected we should investigate why that's the case and resolve the problem.

Waveform jobs can take from 30-60 minutes for media with long durations.

Scaling up in Sidekiq could create issues with resource contention and CPU saturation. One waveform could complete fairly quickly on staging, but in production could run for hours. Running a lot of jobs concurrently on mco-staging could be a way to test this.

# Done Criteria
- [x]  Investigation into why processes don't return properly
- [x]  Code change to resolve (possibly need to refactor IO buffering or CPU saturation)

**Comment by cjcolvar** [comment]
Hanging resolved by #6035 and by reducing the number of parallel threads allocated to waveform jobs to 5 per process (down from 30).  This configuration is specific to IU production as core has only one sidekiq process which uses the default 10 threads for all queues.

**Comment by joncameron** [comment]
Waveform generation has vastly improved with the new changes and has been running successfully in our production environment.
