### ISSUE TITLE
Add Poster Image to Media Object IIIF Manifest

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5167]
# Description
Avalon-generated IIIF manifests do not contain the correct URLs to the poster image still used to represent the media, which renders in the player before playback. The placeholder canvas IIIF property will be added Avalon's IIIF manifest generation to properly present the poster image in spec.

https://iiif.io/api/presentation/3.0/#placeholdercanvas

# Done Criteria
- [x] Update the IIIF manifest gem so that  manifests contain placeholder canvas or other appropriate type and correct reference to media poster image
- [x] Update gem within Avalon and confirm and test changes

**Comment by Dananji** [comment]
PR in `iiif_manifest` gem repo: https://github.com/samvera/iiif_manifest/pull/95

**Comment by elynema** [comment]
Go ahead and test this in Avalon by pulling in a branch so that we aren't trying to make a iiif-manifest release multiple times as we work on changes.

**Comment by elynema** [comment]
Looks good to me. Tested with a media object with both 1 and 2 files.
