### ISSUE TITLE
Add Ramp to Playlist Show Page

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5168]
# Description

On playlist page, Avalon utilizes the mediaelement.js player to play items from the playlist. This player needs to be replaced with Ramp. With the playlist modeled in IIIF as a manifest with multiple canvases, the Ramp video player and structure components can be used to provide the video playback and the list of items in the playlist.

The rest of the playlist page should remain more or less as is and be powered by Avalon, rather than Ramp. This includes the playlist tags, and share.

Right now, the auth check for each object makes playlist loading very slow.

See #167 for the work to create the add marker button/action.

## Handling Restricted Content
It's expected that playlists in Avalon may include content which is inaccessible—either because the user has not authenticated to the repository, or because the user is not authorized for access. These items should still exist within the playlist, but be shown to the user as inaccessible.

A placeholderCanvas should be used to present information to the user that this is restricted access. For these items, the media player does not need to be rendered.

- StructuredNavigation Ramp component should work as needed for the list of playlist items

# Questions
 - If we just display [Playlist] : playlist title at the top of the page (in Avalon) that's good enough
   - Flexibility in Ramp will also allow easier layout on Playlist page
 - What needs to be added to view metadata details as they currently appear on the playlist show page?
   - Decisions made in #5279

# Done Looks Like
- [x] MediaElement.js replaced with IIIFPlayer
- [x] Existing playlist item listing replaced with the StructuredNavigation component
- [x] Playlist markers are rendered similarly to how they are currently in playlist items
- [x] Related items do not display
- [x] Auto-play component in Ramp appears above the structured navigation with playlist items
- [x] When a playlist item is restricted from access for the current user, on the playlist page:
  - [x] A lock item displays next to the playlist item title in the list of playlist items
  - [x] There is an empty canvas item in the manifest

**Comment by elynema** [comment]
A note about captions. Because captions are not duplicated under the CC button I'm wondering if captions are only playing from the HLS manifest rather than the IIIF manifest in this context?

**Comment by elynema** [comment]
Playlist with 48 items takes almost 20 seconds to load. Is this on par with current performance? https://avalon-dev.dlib.indiana.edu/playlists/5

**Comment by elynema** [comment]
Current status of restricted items is that they show a lock icon next to label in the structured nav (but otherwise no other indication they are restricted). When clicked on they display a message in the player "You do not have permission to playback this item." There is no prev/next canvas button in the player b/c there are no player controls. @joncameron Does this meet requirements for this issue?

They are currently not auto-advancing; reported as bug on ramp #269.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzBqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--348a6e2390db1437d7761bdb855d34a3e5807807/image.png)

**Comment by elynema** [comment]
@joncameron @Dananji Source item metadata is not showing up here. Do we want to assume that will be implemented as part of Ramp #252 and remove it from done criteria for this issue?

**Comment by elynema** [comment]
Moved this back to in progress to handle display of 'Inaccessible Item" title. It is ok to continue to use 'inaccessible item' instead of 'restricted item.'

**Comment by elynema** [comment]
@masaball Do we have a way to avoid having the 'Inaccessible Item" canvas title displaying below the media item when the playlist item ends? It seems like that situation should be reserved for when there is a truly inaccessible item selected.

**Comment by masaball** [comment]
Yes, we can rework it to not display when an item has ended.

**Comment by elynema** [comment]
@charumitraravi Can you finish QA for the bug identified on this? When auto-play is turned off, the title under the media player should continue to display the title of the playlist item, even when playback of the playlist item has ended. The same should happen if you re-play the playlist item after it ends using the replay button in the media player.

**Comment by charumitraravi** [comment]
@elynema I have verified the above case: when autoplay is turned off, the title under the media player continues to display the title of the playlist item , even after replay. 
I could also notice the issue where the item name remains the same (intermittently for the next 3–4 items) when the player auto-advances to the next item in the playlist (which is similar to the issue we confirmed earlier where the item name is not updated properly in the playlist )
