### ISSUE TITLE
Add Ramp to Media Object Page

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5169]
# Description
Replacing MediaElement.js with Ramp. Preliminary recommendation is to have descriptive metadata presented by a Ramp component, as well as the structured metadata. We'd also like to investigate having add to playlist functionality included in Ramp.

# Done looks like
- [ ] Ramp reads the manifest and renders components accurately within the Avalon media object page framework
- [ ] Ramp functions as expected; structure navigation, player, and transcript components works in sync with each other
- [ ] File download button does not display in player (content will be shown in a separate component)

**Comment by elynema** [comment]
A significant amount of metadata is already being added to the IIIF manifests produced by Avalon. (ex: https://avalon-staging.dlib.indiana.edu/media_objects/ns0646018/manifest.json). See #5170 for work to identify fields not there and determine if they can be added.

Still need to review how the Ramp components are put together on a page and which items of the media object page we want rendered by Ramp.

**Comment by elynema** [comment]
multiple canvases - was not loading the new canvas in the player when selected in the structure. This ended up being a change in Ramp to fix.

**Comment by elynema** [comment]
Transitions when auto-play moving between mixed canvases (video to audio and audio to video) are not working. Event that occurs when reach the end of the file is not firing.
