### ISSUE TITLE
Add Supplemental Files to IIIF Manifest

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5172]
# Description
What is best practice for including references to supplemental files in the manifests? This should be determined and implemented so that Avalon's IIIF manifests contain the proper objects for relaying the list of supplemental files and their types.

Per the IIIF #av community, transcripts / captions should be supplementing annotations. All other files should be rendering properties.

Further details are in this [document](https://docs.google.com/document/d/1JVRER8qCkRHxWt6Zd3wbwznDTLfx-Wln/edit#), including a copy of the #av slack transcript discussion.

# IIIF Reference
- [General info](https://iiif.io/api/cookbook/recipe/0231-transcript-meta-recipe/) on transcripts, captions, and subtitles
- [Cookbook recipe](https://iiif.io/api/cookbook/recipe/0219-using-caption-file/) for captions/transcripts as `supplementing` annotations
- [IIIF spec](https://iiif.io/api/presentation/3.0/#rendering) for `rendering`
- [Main cookbook recipe](https://iiif.io/api/cookbook/recipe/0046-rendering/) for alternate representations via the `rendering` property
- [Cookbook recipe](https://iiif.io/api/cookbook/recipe/0017-transcription-av/) with `rendering` example of a downloadable transcript
- [List](https://iiif.io/api/presentation/3.0/#type) of `type` values currently available for `rendering` property

# Questions
- [x] How do we handle the `type`, `label`, and `format` values for the rendering property?
 - Answer: populate `format` from the file's mime-type and use that value to determine `type` as best as possible. Primarily utilize the `type` value of `Text` and `Image`, although we could also use `Video` and `Audio` as well. mime-types that don't fit into those categories could be labeled as `Dataset`.

# Done Criteria
- [x] Transcript files appear in IIIF manifest as supplementing annotations at the canvas level
- [x] Caption files appear in IIIF manifest as supplementing annotations at the canvas level
- [x] all other supplemental files appear in IIIF manifest as rendering properties at the canvas level
- [x] For supplemental files as rendering properties, populate format and type are populated according to rules listed above
- [x] supplemental files associated with the media object, rather than a section, appear as rendering properties at the manifest level
- [ ] Test record with multiple caption files to ensure they appear in the IIIF manifest and can be selected in Ramp

**Comment by elynema** [comment]
Need to specify how we want supplemental files to appear in IIIF - annotations, rendering, and how to identify transcripts vs. captions.

**Comment by elynema** [comment]
From Glenn Robson re: vocab for the `type` value of a `rendering` property: I think that is the current list. There is a location in the registry for adding new types here: https://iiif.io/api/registry/ but it is currently empty. If you want to propose a type not listed in the specification we now have a process to take these additions through the TRC and get them added to the registry.
