### ISSUE TITLE
Embedded Player

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5179]
# Description
Configuring Ramp for the embedded player context.

Need to make changes in the embed code in Avalon as it now uses a ME.js instance. Potential first round solution for 7.7 release is simply to have Avalon instantiate a video.js player for embeds. video.js has the ability to provide some configuration as it is instantiated. 

A more complex solution may be to create a Ramp component for an embedded player with additional customization / configuration, but we've decided to instantiate Ramp normally instead.

# Definition of Done
- [x] /embed routes serve embedded media player
- [x] Audio adjustment widget works for both audio and video
- [x] Includes link back to item in MCO - button in toolbar
- [x] For audio items, plays auto quality by default. No quality selector for audio items
- [x] For video items, title displays in top of player hyperlinked back to MCO item
- [x] Embed URLs respect media fragments (can start media at a single timepoint)
- [ ] If time, investigate if we can add a user configuration to determine whether title displays in the embedded player for video

**Comment by Dananji** [comment]
Resources found from a quick investigation:
1. https://videojs.com/guides/embeds/
2. https://github.com/videojs/video.js/tree/f1558c660bbc132b23dbd63b2f3cdf7b6e60d00b/sandbox
3. https://github.com/videojs/video.js/blob/f1558c660bbc132b23dbd63b2f3cdf7b6e60d00b/CONTRIBUTING.md#sandbox-test-directory
4. Use automatic setup of VideoJS via `data-setup={}` where it can contain a valid JSON object with VideoJS options

**Comment by elynema** [comment]
Note that we have on our list to make the Ramp audio adjustment a vertical slider rather than a horizontal one. Need to test how this works with embedded player for audio only files.

**Comment by joncameron** [comment]
Blocked by #samvera-labs/ramp:189

**Comment by elynema** [comment]
Note that some browsers are no longer allowing Javascript in an iframe to use local storage, so we can't rely on use of local storage in this version of embedded player.
