### ISSUE TITLE
Metadata Generation Updates

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5182]
# Description
- `<pre>` tags don't need to be retained in descriptive metadata in the IIIF manifest.
- multiple values for a metadata key should be separate strings within an array rather than the single concatenated string (https://iiif.io/api/presentation/3.0/#metadata)

# Done Looks Like
- [x] Remove pre tags from the allow-list for serializing metadata
- [x] Remove pre tags from IIIF manifest
- [x] Multi-value fields are represented as an array of strings in the metadata section of a manifest
- [x] Quick review of any other tags we're inserting into IIIF manifest metadata (users could be putting these in).

https://github.com/avalonmediasystem/avalon/blob/524f197a66785fc8fc0e63a59fe8bd7253852205/app/helpers/application_helper.rb#L96-L105

**Comment by elynema** [comment]
Content, like summaries, that comes from Omeka often has formatting tags. Would be nice to actually render those.

**Comment by cjcolvar** [comment]
See example in cookbook for multiple values for a single metadata field.
https://iiif.io/api/cookbook/recipe/0118_multivalue/
