### ISSUE TITLE
Mark machine-generated transcripts in IIIF manifest

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5201]
# Descriptions

Marking a transcript as machine-generated on the back-end was completed in #5143. Because we are transitioning to use of IIIF manifests to display supplemental files in Ramp components as part of 7.7 release, we did not implement the front-end form machine-generated transcripts in that issue.

In order to be able to display transcripts as machine-generated in a Ramp supplemental file component, the IIIF manifest needs to indicate that they are machine-generated.

From discussion on the #av in iiif workspace, we talked with Mat Jordan at Northwestern about labeling transcripts as machine-generated.

Since it has been recommended that transcripts be supplementing annotations, he suggested:

Could that tag be carried in the label of the annotation body?
"label": { "en": ["Transcript (Generated)"] }

Dananji noted that we could get in trouble if we are looking for the English words "Transcript (Generated)" to base functionality because the label could be in another language. From the viewer perspective, it might be ok to display any label associated with a supplementing AV annotation at the start of the transcript. We'd have to make the label in the IIIF manifest more of a note, like "Machine-generated transcript may contain errors."

On the download side, though, we either need a short label to add to the filename, or we need to actually cue off the text of the label.

# Done Looks Like
- [x] Investigation into where best to note this information in the manifest
- [x] Supplemental files that represent transcripts have a label in the IIIF manifest that contains the text "(machine-generated)"

**Comment by elynema** [comment]
In #194, the Ramp transcript component checks the label of the supplemental annotation for the words "(machine-generated)" and bases logic on display/download on that.

**Comment by Dananji** [comment]
@elynema The properties I came across when reading through the WebAnnotation model which we might be able to use to indicate machine generated transcript annotations in a IIIF manifest is the creator, generator properties (https://www.w3.org/TR/annotation-model/#other-properties). This might not be the best approach, but could be a starting point to do more research?

**Comment by elynema** [comment]
When I set one of the transcripts on the third section of this item to be machine-generated, the flag seems to save, but it's not populating out to the IIIF manifest. It worked when I saved the transcript on this item as machine-generated, though (and showed up in the manifest). Not sure what is the important difference between these 2 records.
