### ISSUE TITLE
IIIF Manifests for Playlists

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5203]
# Description
Create a service that serializes a playlist as a manifest. Each playlist item is a canvas on the manifest. Markers on playlist items should also be serialized.

See more details on the [investigation ticket](https://github.com/avalonmediasystem/avalon/issues/4222) around modeling playlists in IIIF. Note that metadata for the playlist item (beyond label) will be brought in from the parent manifest on the fly and does not need to be modeled in the canvas. In future work, a user's set of playlists may be  modeled as a collection of manifests.

# Questions
- [x] How to model playlist markers in IIIF? Looks like they could be simple annotations on the canvas, using w3 web annotation motivation of `highlighting`. See https://www.w3.org/TR/annotation-model/#motivation-and-purpose

# Manifest Details
- Descriptive metadata for playlist items can be brought in from the item manifest (dereferenced)
- Playlist manifests are a single document
- Each playlist item has its own Canvas

# Example
 - https://figgy.princeton.edu/viewer#?manifest=https://figgy.princeton.edu/concern/playlists/6f4551de-cb4c-4c2e-9798-b0c405e7d91b/manifest&c=&m=&s=&cv=&rid=

# Definition of Done
- [ ] Avalon Playlists serialize to IIIF using iiif_manifest
- [x] Endpoint service created (/manifest.json on the end of a playlist URL)
- [x] Presenter objects created to pass information to iiif_manifest (different than media object serialization)
- [x] Playlist manifest label contains '[Playlist]' text to identify as a playlist
- [x] Each playlist item canvas references it's parent manifest via `partOf`
- [x] Playlist manifest indicates autoplay (autoadvance) behavior as a default (https://iiif.io/api/presentation/3.0/#behavior)
- [ ] Markers are included for each playlist item (inline within manifest)

# Notes
- Writing markers/annotations can use a service, but not needed for this case (reading and serializing markers from database to manifest). This can be a separate ticket for creating a marker annotation service in Avalon.
- Highlighting motivation may be an option for demarcing this in IIIF: https://www.w3.org/TR/annotation-model/#motivation-and-purpose
- Controlling Ramp is possible in Avalon for autoadvance using JS

**Comment by joncameron** [comment]
Possibility of using fragment selectors for representing markers, or appending media fragment to targets pointing to canvas in manifest would be the two primary approaches for implementation.

**Comment by joncameron** [comment]
https://github.com/avalonmediasystem/avalon/pull/5264
