### ISSUE TITLE
UI Patterns for detailed scrub in Existing Media Players

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5216]
# Description
Comparing and discussing existing UI patterns for detailed scrub interface in web media players.

@joncamer will create and flesh out an initial document to catalog these.

**Comment by elynema** [comment]
Youtube -- when scrubbing, there is a note to "pull up for precise seeking". I rather like the way their model opens the detailed scrub within the player itself. 

![image.png](https://images.zenhubusercontent.com/62d989a70c79cb5218735cd6/3cf70f73-4796-4f8a-89a0-5945c49e6997)

**Comment by joncameron** [comment]
Document: https://docs.google.com/document/d/1rHdCV-08V1Kbxdm-gzmS5Vgd4lvzNhPXtz3dnt0mk0I/edit

**Comment by elynema** [comment]
Precision Seek is different than what Li'l Scrub does, which is give you a separate time rail to navigate track by track.
