### ISSUE TITLE
Show machine-generated option for transcripts before edit is selected

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5228]
# Description

Currently, when you click Edit next to a transcript, you have the option to check a box to mark it machine-generated. However, after hitting Save, there's no indication in the UI that the transcript has been marked as machine-generated unless you click Edit again.

![image.png](https://images.zenhubusercontent.com/62d989a70c79cb5218735cd6/86d3f54a-003f-4ea2-b383-f8815b1d99b1)

![image.png](https://images.zenhubusercontent.com/62d989a70c79cb5218735cd6/d8470c55-27cb-413b-9e4d-c24ff5c5a6cd)

I propose that it would be useful to include a marker in the transcript section next to any machine-generated transcript before the Edit button is clicked. That could be a note that says "(machine-generated)" after the label for the file, or it could be a right-aligned note next to the Edit button that says "machine-generated" (might make sense since that is where the checkbox is).

Additionally, when a user uploads a transcript, it's not obvious that they have the option to mark it as machine-generated. You click the Upload button, select a file, and then it shows up in the list. Does it make any sense for the new file that was just added to show up in Edit mode (where the label can be edited and the machine-generated box checked) as soon as it uploads? Or would that create a weird user interaction?

This is not high priority for 7.7 release, as it is user interaction rather than base functionality. Identifying which transcript is machine-generated while displaying in the list seems higher priority than changing the upload interaction.

# Done Looks Like
- [ ] Choose an icon to indicate that a transcript has been marked as machine-generated
- [ ] Icon present in the row for a transcript indicating machine-generated origins
- [ ] Tool-tip displays additional text for user context

**Comment by joncameron** [comment]
Could use an icon for this purpose (which one? could investigate) with tooltip for info. Or text in that area—something to indicate to the user that the transcript is here.

**Comment by Dananji** [comment]
@joncameron and @elynema I've used an icon from FontAwesome (`fa-laptop`) in this work. But if there's a more suitable icon for this we can change this as needed.

**Comment by joncameron** [comment]
I created #6039 to switch the icon out—I think the more generic gears would work better than the laptop icon for machine-generated documents. Otherwise looks and works great!
