### ISSUE TITLE
Increased Indexing through SpeedyAF

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5236]
# Description
Continuing to speed up Avalon by reducing calls to Fedora by proxying with SpeedyAF.

# Changes/Indexing updates
- Poster/thumbnail images (in Search andCollection search)
- Masterfile routes (captions, waveform in SME, embed, HLS manifest, caption manifest, structure, transcript)
- Item show page
- Presentation 3.0 Manifests

# Steps for QA testing
- Search checking poster/thumbnail images
- Create a new media object adding multiple files, filling out all fields including multiple values for multi-valued fields, and adding supplemental files.  Check that all data appears correct on item view page and all attached files are retrievable and correct.
- Test embedding one of the sections
- Add sections to a playlist and test playlist playback and loading of related metadata.
- Test intercom push
- Load IIIF manifest in Ramp and check all metadata is correct
- Test Avalon API checking all read routes work as expected
- Browse items and select some items then go to the Manage Selected page and test bulk actions
- Create a timeline and test playback
- test permissions across users for at least one function
- Test media object special access permissions especially leases (time-limited access grants)

# Done Looks Like
- [x] Updates to indexing to reduce calls to Fedora across the endpoints listed above

# Future Work:
- Oembed (MasterFilesController)
- ApplicationController#fetch_object (affects SupplementalFilesController and ObjectsController)
- MediaObjectsController (move_preview, confirm_remove, destroy, set_active_file)
- Admin::GroupsController#check_for_sole_managers
- Uses of `load_and_authorize_resource` or `load_resource`
- Checks for is_a? class in views or other code
- app/views/media_objects/_add_to_playlist_form.html.erb

**Comment by elynema** [comment]
Note that this needs fairly extensive testing, so should be held to release and not cherry-picked to MCO.

**Comment by cjcolvar** [comment]
This now covers nearly all routes that don't modify and save objects.  I think there are still a few that I didn't get to including creating/editing MediaObjects, Objects controller (and other places that fetch_object is used), and MasterFile oembed.
