### ISSUE TITLE
Implement mini annotation server in Avalon for playlist markers

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5240]
# Description

Build annotation server functionality (endpoints) into Avalon to be used by Ramp to create playlist markers as annotations. Look at https://github.com/PenguinParadigm/annotot for a sample interface for creating, editing, and deleting annotations for a canvas. Will be necessary to include authorization on endpoints, as a playlist owner can create/edit/delete, but a playlist may be shared publicly so that anyone can view the markers.

the annotation service needs to be declared in the IIIF manifest for the playlist.

See #167 for more context.

# Questions
- [x] Note that for our initial implementation of IIIF manifests for playlists, the proposal is to include the markers in the manifest generated for the playlist, which should mean that Ramp won't need an endpoint to get markers, because it should already have them?
- Yes, the manifest should already contain marker/annotation information
- [ ] Should create/edit/delete marker service be declared in the manifest if the current user can't access them? 
- Link to marker service will only be included in the manifest if the current user is the playlist owner. Marker service as an endpoint should have Avalon auth in front of it to make sure people can't just call the marker service back-end

# Done Looks Like
- [ ] IIIF manifest for a playlist includes service declaration for created/edit/delete annotations
- [ ] service allows creation of `highlighting` annotations
- [x] annotations can be created, edited, or deleted for a specific canvas (item)

**Comment by joncameron** [comment]
More discussion needed on this before moving forward.

**Comment by elynema** [comment]
Mason suggested that if we handle this logic when generating the playlist manifest (only include the service when the user has the ability to access them based on Avalon's auth), then it means that users who are not part of the MCO system won't be able to create annotations. If we want external users to have the ability to create annotations, we would have to use some kind of IIIF auth. If we're not worried about that yet (since our annotations are really a part of the Avalon system), then we could consider auth at time of manifest generation.

Note that the media object manifest is currently restricted on who can view it (it's access level in Avalon) and the credentials of the person requesting it. So currently, only manifests for publicly available items can actually be read by external users?

**Comment by joncameron** [comment]
We will create our own more simple first-pass implementation for markers rather than use an external annotation library. We may come back to this in the future.

**Comment by elynema** [comment]
@joncameron I thought this issue was for the work needed to create our own implementation?
