### ISSUE TITLE
Error when requesting media_objects index json when user belongs to many groups/virtual groups

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5242]
# Description
Seen in production (https://app.honeybadger.io/projects/54117/faults/97117493). Affects the Avalon Ingest API.

This error is due to the solr request uri being too big for a GET request.  In other places we've overridden ActiveFedora to allow switching solr requests to POST instead of GET.  In this case, ActiveFedora relation#to_a calls #find_each which ends up calling `ActiveFedora::SolrService.instance.conn.paginate` which bypasses our overrides.  A possible solution to this is to override `RSolr::Client#build_request` to fallback to `ActiveFedora::SolrService.default_http_method` instead of `:get`.  This would allow for configuring the default http method used by rsolr and would not require us to handle all of the cases in ActiveFedora or Avalon code where we reach into rsolr and execute methods directly instead of going through ActiveFedora::SolrService.

# Done Looks Like
- [ ] Override `RSolr::Client#build_request` to fallback to `ActiveFedora::SolrService.default_http_method` instead of `:get`

**Comment by joncameron** [comment]
https://github.com/avalonmediasystem/avalon/pull/6020#pullrequestreview-2280796955
> If the rest of the test suite is passing then I think that should be sufficient to prove that this override is working.
