### ISSUE TITLE
Items Appear as CDL Items Even When They Shouldn't 

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5255]
# Description
On avalon-dev some items are displaying as CDL items, even when it's not enabled at the collection level. 

# Example
- Collections without CDL enabled:
  - https://avalon-dev.dlib.indiana.edu/admin/collections/m613mx563
    - https://avalon-dev.dlib.indiana.edu/media_objects/gt54kn002 (this item seems fine)
  - https://avalon-dev.dlib.indiana.edu/admin/collections/p2676v52c
    - https://avalon-dev.dlib.indiana.edu/media_objects/fj236208t  (item appears as CDL)

**Comment by joncameron** [comment]
Could possibly be an indexing/environment/data issue rather than a bug.

**Comment by cjcolvar** [comment]
I reindexed the collections on avalon-dev and this appears to be resolved.
