### ISSUE TITLE
Replace Existing UI with Ramp Components on Object Show Page

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5256]
# Description
Continuing from previous work in #5169 to add Ramp to the media object show page. The Media player has its own issue #5262.

Note that overall page design and styling and styling of structured navigation is not part of this issue. Work with the Ramp structured navigation component to add accordion and expand/collapse functionality should be part of Ramp #191.

# Done Looks Like
- [x] MetadataDisplay component replaces the existing metadata/details section
- [x] StructuredNavigation replaces the current sections div (styling of structured nav is not part of this issue)
- [x] SupplementalFiles component replaces the Files panel
- [x] Transcript component moves to top right to display as a tab (see design in #5202 for where/how transcript should display)

**Comment by elynema** [comment]
This issue should focus on bringing transcript, metadata component, and files component from Ramp into the tabbed section in the top right of the page.

**Comment by elynema** [comment]
Dananji asked about the Access Restrictions and Fedora Objects panels because they are not in the new designs from Matt. Jon C. recommended moving Access Restrictions (which includes CDL lending period) into the IIIF manifest to display as part of the metadata section. The link to the MODS XML (currently not in the IIIF manifest) and the Fedora Objects info are recommended to move to the Edit page, probably under Manage Files. Jon C. will create 2 new tickets for these 2 items.

**Comment by elynema** [comment]
Most item page tests are failing now b/c Rspec cannot access the page as rendered within the React components. Dananji tried a few drivers, but will work with Chris on this.

**Comment by elynema** [comment]
Note: have Charu help QA this, so she can do feature testing and make sure we have test cases that cover functionality.

**Comment by charumitraravi** [comment]
QA Completed
1. Resource meta data is not fully shown 
2. Links not working as expected in structured nav (Known issue)
3. Section Supplemental files are not shown under files unless there is atleast one item supplemental file (Known issue)

**Comment by elynema** [comment]
@charumitraravi Does https://github.com/avalonmediasystem/avalon/issues/5387 cover the first item in your list? I believe the other issues have been documented already.

**Comment by charumitraravi** [comment]
@elynema Yes it does. Will update the comment as known issue.
