### ISSUE TITLE
Add Series Metadata to Object View, Catalog Search

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5269]
# Description
Series metadata should appear on the item page and in search when present in a record.

# MODS
- `<relatedItem type=“series”>` element with `type` attribute
-  `<titleInfo/title>` is a child of `relatedItem` and contains the series name.
  
## Example
```
<relatedItem type="series">
  <titleInfo>
    <title>1962 Clio Winners</title>
  </titleInfo>
</relatedItem>
```

Additional info resources from Julie:
> The MODS to RDF white paper actually shows some examples on the MODS XML side that can be helpful too (starting page 43): https://samvera-repo.hykuup.com/concern/generic_works/b922d5e1-abfe-4305-a696-0c6d72c962ff
> 
> There are also examples of using the relatedItem element in the MODS user guide: https://www.loc.gov/standards/mods/userguide/relateditem.html

# Done Looks Like
- [ ] Series metadata corresponds to the correct MODS field
- [x] Series is a repeatable field 
- [x] Series appears in media objects responses from the JSON API
- [x] Series appears in IIIF manifest metadata
- [ ] Series is copied over when records are copied via Intercom (Push)
- [x] Series Facet added to Catalog view
- [x] Series field added to descriptive metadata listing in object view
  - [x] Series is hyperlink to a catalog search for series name + the current collection
- [ ] Documentation: Add Series to Descriptive Metadata Listing (https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957954564/Supported+Field+Names)

**Comment by joncameron** [comment]
Series will also need to be in the Intercom push and API outputs.

**Comment by joncameron** [comment]
Series will also need to be in the Intercom push and API outputs.

**Comment by joncameron** [comment]
@masaball updated with details on the MODS elements

**Comment by elynema** [comment]
Note: Have Charu help QA this to do feature testing and make sure test cases are written.

**Comment by charumitraravi** [comment]
Finished QA on this item. So far, no issues.
