### ISSUE TITLE
Add Caption Field to Batch Ingest Manifest

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5285]
# Description
Caption files can be uploaded in the web interface but cannot be attached to media files via Avalon's batch ingest feature. Users should be able to add information to the manifest for caption files to be ingested and attached to the appropriate media file.

# Done Looks Like
- [x] Caption File field can be passed in as a column in a batch manifest following a File value
- [x] Caption File Language can be passed in as an optional additional column following Caption File
- [x] Caption File Label can be passed in as an optional additional column following Caption File
- [x] Caption File with Optional Caption File Label & Optional Language Field are Repeatable
- [x] If the Caption File Language value is not within the controlled vocabulary Avalon uses for this field, set this to be the default (English or default set in Avalon config)
- [x] Caption File, Label, and Caption File Language added to [Supported Field Names](https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957954564/Supported+Field+Names) documentation
- [ ] Example batch manifest template update in Avalon docs

**Comment by joncameron** [comment]
Extra parsing work needed to ensure that repeatable fields contained within repeatable fields are processed correctly.

**Comment by masaball** [comment]
[Metadata Fields](https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957954564/Metadata+Fields)

* Caption File
    * Caption files listed in the manifest file must have the correct path noted for where those files are located in the Avalon dropbox, relative to the manifest file. Additionally, all caption files must include a file extension. If necessary, include any directories or subdirectories.
    * Only repeatable following a file entry.
    * Label and Language can be listed in any order following the caption file they are describing.
    * Caption File can be updated or removed later via the Section Files menu on the Manage Files page.
* Caption Label
    * Only repeatable following a caption file entry.
    * Caption Label is used for display in caption/subtitle selection menu in the player. If left blank or otherwise not included the caption filename will be used as the caption label.
    * Editable after ingest in the Section Files menu on the Manage Files page.
* Caption Language
    * Only repeatable following a caption file entry.
    * Caption language should describe the language of the caption content. Only terms or codes from the [MARC Code list for Languages may be used](https://www.loc.gov/marc/languages/). Entering a language term not from the list will set the caption language to the default defined in the settings.yml file. If left blank or otherwise not included the caption language will be set to the default defined in the settings.yml file.
    * Editable after ingest in the Section Files menu on the Manage Files page.


[Adding caption files via batch](https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957953586/Batch+Ingest+Package+Format)

The Batch Ingest Package can include WebVTT or WebSRT captions files. Avalon supports ingest of multiple caption files per media file. Caption files in the manifest file must have the correct path noted for where those files are located in the Avalon dropbox, relative to the manifest file. Additionally, all caption files must include a file extension. If necessary, include any directories or subdirectories. Caption files can be updated or removed later in the Section Files menu on the Manage Files page.

**Comment by joncameron** [comment]
Will add the caption file to the example manifest package in https://github.com/avalonmediasystem/avalon/issues/5862
