### ISSUE TITLE
Removing user from managers group should give warning if still a manager of a group

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5289]
A user must belong to the managers group in order to be a manager of a collection.  If the user is removed from the managers group they get demoted to editor in all collections where they were a manager.  This happens without warning and can have the side effect of leaving a collection without a manager which will fail validations.  One possible fix for this is to give a warning when attempting to remove a user from the managers group if they are a manager of any collections.  This would mirror the approach taken for warning when deleting a collection that still has items in it.  This could be either a warning or a requirement to remove the user from all collections where they are manager prior to being removed from the managers group.

Simple implementation would be blocking the remove action until the user being removed from the Manager group is removed from all Manager status on collections across the repository.

# Done Looks Like
- [ ] When attempting to remove a user from the Manager group, if the user is still listed as Manager on a collection then a flash message appears
- [ ] Flash message: " Please remove this user from all Manager roles before removing them from the Manager group."

**Comment by masaball** [comment]
It looks like we do already check if a user is the sole manager of a collection and [prevent the removal if so](https://github.com/avalonmediasystem/avalon/blob/main/app/controllers/admin/groups_controller.rb#L118), so we shouldn't be leaving any collections managerless. 

@cjcolvar Do you remember if you actually saw collections being left without managers? Could be there is a bug in the current implementation if so. 

Assuming there is not a bug, is the current implementation sufficient or should it be changed/augmented as suggested to require manual removal from all collections before removal from group?

**Comment by cjcolvar** [comment]
I don't remember.  I tried on MCO-staging and got a flash error message when I attempted to remove a sole manager.  I think that's fine and this ticket can probably be closed.
