### ISSUE TITLE
LocalStorage Not Available in iFrame Causes Error

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5328]
# Description
LocalStorage is not available inside an iframe unless users change a setting to allow it. This is potentially the cause of loading issues seen on the Indiana Broadcast History Archive site. 

Pull #5307 

Local board issue: https://github.iu.edu/AvalonIU/Avalon/issues/171

**Comment by cjcolvar** [comment]
Only happens in Chrome browser currently.

**Comment by elynema** [comment]
Tested on avalon-dev; not actually working yet, will need to come back to this.

**Comment by elynema** [comment]
Would like to re-test this before pushing it out.

**Comment by joncameron** [comment]
@cjcolvar I tested this on mco-staging in Chrome and was at least not seeing the localStorage errors that were there previously. Is this OK to close now?

**Comment by cjcolvar** [comment]
Sure.  If this is working on mco-staging are we ready to push it to production (https://github.iu.edu/AvalonIU/Avalon/issues/179)?

**Comment by joncameron** [comment]
Yep, I think so. Closing this one.
