### ISSUE TITLE
Valid Transcripts Don't Load

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5329]
# Description
In avalon-dev no transcript files are loading. The transcript files seem to attach OK and download as expected but don't render.

See https://avalon-dev.dlib.indiana.edu/media_objects/gx41mh844 for an example.

# Done Looks Like
- [ ] Transcripts load successfully in the transcript component on the media object view page.

**Comment by masaball** [comment]
I checked the item linked in the ticket and am seeing the transcript loading fine on the first item. We need to confirm whether the behavior described here is still occurring elsewhere.

As said in standup, I encountered application freezes on the second item so will create a ticket to more deeply investigate what might be happening with that item.

**Comment by joncameron** [comment]
As noted this is no longer an issue; closing!
