### ISSUE TITLE
 Test titles with multiple colons

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5330]
# Description
Remove the workaround (see #5089) from Solr 6 if it's working in Solr 9. Solr 9 is running on avalon-dev, and this should be tested there.

Example problematic title: [Clio : 1983 Clio international preliminaries : Craft : Classic : Misc]

# Done Looks Like
- [x] Titles with multiple semi-colons tested on dev (create, display, index)
- [x] Searching on a full title containing multiple semi-colons returns expected results

**Comment by elynema** [comment]
Chris tested this in Solr 9 on mco-staging and it works fine with the workaround commented out. Chris will submit a pull request to remove that workaround.

**Comment by cjcolvar** [comment]
Tested on avalon-dev, which runs Solr 9 and does not have the workaround, and everything looked good.  The workaround is only on MCO and Dark Avalon.
