### ISSUE TITLE
[BUG] Ramp components not displaying on media object page for some items

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5350]
**Describe the bug**
For some items, the Ramp components are not displaying on the media object page 

**To Reproduce**
1. Two examples I have found so far: https://avalon-dev.dlib.indiana.edu/media_objects/r207tp32d and https://avalon-dev.dlib.indiana.edu/media_objects/fj236208t 
2. Only media item title and top row of buttons (ex: edit / unpublish / delete) show on page. The rest of the page is blank, no media player, etc.

**Expected behavior**
Should see media player, structured navigation, metadata, transcript, and supplemental files rendered by Ramp.

**Screenshots/Screen Recording**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbkp5IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4cb0e76c6b4df1b345b4c9c9e63cae7893cb36a0/image.png)

**Environment (please complete the following information):**
 - Device / platform: Mac laptop
 - OS: Monterey
 - Browser: Chrome
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
7.7

**Additional notes**
Looks like Ramp div is populated on page, but nothing in it. Probably one of the checks is failing and has not been failed.

**Comment by joncameron** [comment]
Ramp is loading but there are multiple checks on Rails streams and other things going into the manifest, and something is failing that causes it to not render. Updated Rails variables aren't properly being passed into Ramp. Checks aren't working properly and so nothing in the React component is rendering.

**Comment by joncameron** [comment]
@masaball I checked the two example items in the ticket and they're still not loading for me, with an `Uncaught TypeError: item.items[0] is undefined` error in the console.

**Comment by masaball** [comment]
@joncameron Sorry, I should have made a comment here when we closed #5375. The current fix for this is on the Ramp side but those changes have not been pulled into Avalon yet. If you take the example manifests and try them on the Ramp demo site, they should load up fine without that error.
