### ISSUE TITLE
Display of Inaccessible Items in Playlists

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5356]
# Description
Inaccessible items are represented with placeholderCanvas elements in the IIIF manifest. These can have a time length value, and we could add this explicitly to that the default auto-play behavior will display the placeholderCanvas message to the user ("this item is deleted/inaccessible"), then advance to the next after the time specified on the placeholderCanvas.

Related: do we need the auto-advance toggle on the item page? 
In the example of YouTube, there is a countdown where the user can interact with the interface (stop the timer before things advance). This could be more about giving the user the ability to interact with it, with an action they can use to stop this.

If we add a duration to the placeholderCanvas, we could display this time in the UI; if not specified in the manifest, default to 10 seconds. Ramp currently tries to read the message from the placeholderCanvas and supplies a default message if none is present; we could use the same strategy for the placeholderCanvas.

# Done Looks Like
- [ ] placeholderCanvases representing inaccessible files have a duration of 10 seconds where the placeholderCanvas message is displayed in the Avalon manifest
- [ ] 10 seconds is also the default for those elements which don't have an explicit duration
- [ ] When auto-play is designated, advance to the next file after this duration

**Comment by elynema** [comment]
@joncameron I believe this work was completed as part of Ramp #269. However, the default time period for display of inaccessible items was set to 3 seconds, rather than 10 seconds as specified here. Do you have a preference for the longer time period?

**Comment by joncameron** [comment]
Yes, this is a duplicate now. I think 10 seconds is a better length of time and got approval during team discussion, and I'll close this and open a new issue just for updating that value.

**Comment by elynema** [comment]
Separate issue Ramp #316 to lengthen the default time period for display
