### ISSUE TITLE
Add Explicit Canvas Reference to Manifest Ranges

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5368]
# Description
In Avalon IIIF manifests it's possible for structural metadata to contain a single childless div. In context of the current manifest layout, canvases aren't able to be referenced directly from ranges other than the implicit order of elements in the JSON. Canvas references should be included in the structure section of the manifest to ensure that parsing and display is handled correctly.

Childless divs can exist at arbitrary locations in the structure hierarchy; regardless of where they are in the structure they should have links to a canvas. Our approach should ultimately handle these gracefully; we may need to create an additional issue to accommodate these nested divs rather than the simpler case of a childless div at the top level.

See https://github.com/samvera-labs/ramp/issues/217 for previous discussion.

# Done Looks Like
- [x] Generate links to canvases in the manifest when structural metadata includes childless divs

**Comment by masaball** [comment]
My approach in #5375 was too broad for this use case. Chris and I chose to close that PR without merging so we could reexamine what approach we want to take for childless divs.

**Comment by elynema** [comment]
The problem we are trying to solve: if there is a canvas with no segments (like a single childless div), then the structured navigation component does not have the canvas information it needs to link the player to switch between canvases. Canvas could only be navigated using the next/previous buttons in the player.

In Avalon, when a section (canvas) is clicked on playback begins at the start of the canvas. The structured navigation will navigate to any timespans within canvas at the appropriate time as the media plays.

**Comment by elynema** [comment]
Would still be good to test in Mirador and Clover, if we can find a Clover demo site.

**Comment by elynema** [comment]
Mirador working; having trouble getting the player to load in Clover.

**Comment by Dananji** [comment]
I tested this in Clover, it doesn't have any issues with parsing the Manifest. It doesn't display structure like the other viewers, so this pattern should be okay to use.

**Comment by elynema** [comment]
Second section on this item has a childless div (a heading with no timespan). The section title properly loads the section in the player when you click on it: https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p
