### ISSUE TITLE
Session Overflow

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5377]
## Description

MCO and other IU instances have continued to run into occasional issues with session overflow, particularly in high traffic or when bots many many requests. This should be investigated to see if this can be fixed or alleviated. This may be caused by StreamTokens growing without bounds, as Chris noted in a comment below.

## Done Looks Like
- [ ] Add a limit clause to StreamToken#purge_expired! (along with a sort) to only keep the most recent tokens in the session
- [ ] Limit value is 2000 (proposed increase from Chris' comment below; is this reasonable?)

**Comment by cjcolvar** [comment]
SiteImprove testing for accessibility issues hit this many times this weekend.  Interestingly most of the errors were in the oembed endpoint (~1500) and only a few in the show page (8).
https://app.honeybadger.io/projects/54117/faults/89400041

**Comment by elynema** [comment]
This could be pulled out of 7.8 if needed for time.
