### ISSUE TITLE
Add functionality to "Expand All Sections" button

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5379]
With the media object page redesign, we are trying to implement an accordion style list for the structured navigation. Part of this is an "Expand All Sections" button. This button has been added to the page but still needs to be wired to the structured navigation once the accordion style list has been implemented.

See Ramp [Ramp 247](https://github.com/samvera-labs/ramp/issues/247)

# Done Looks Like
- [x] Expand Sections button should read "v Expand x Sections" where X = the number of sections. 
- [x] After button is clicked and sections are expanded, it should read "^ Close x sections"
- [x] expand all / collapse all button does not appear if none of the sections have any structure
- [x] Structure should be expanded by default when media object page loads
- [x] While a media item is playing, if it is actively playing a section with structure, structure should expand all by default so that the structure can be seen.

If it's challenging to include the # of sections in the button b/c the button is living outside of the Ramp context, we can re-evaluate that done looks like criteria.

**Comment by joncameron** [comment]
Implemented as a CSS change and could either be in Avalon or Ramp; could be a part of the StructuredNav component within Ramp if done that way (or a component used within StructuredNav). Probably makes more sense to do it in Avalon right now, and could be moved into Ramp in the future if that seems to make more sense.

**Comment by Dananji** [comment]
While a section is playing the structure is expanded whether it has any active timespan or not. This is because of Ramp re-rendering the structured navigation component with every state update (triggered in this case by playback).

**Comment by charumitraravi** [comment]
QA completed. Dod items are verified. Although the behavior feels a little odd that when the user tries to close the sections while a media file is playing. It forcibly closes back. [Refer [Screen recording](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWZLQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--06dc28c6168dd6b3d930c679c9e807660fc3fefb/Expand-collapse%20button.mov)].

**Comment by Dananji** [comment]
@charumitraravi This behavior is expected with this first pass implementation as I've mentioned. This is something that can be handled on the Ramp side hopefully, when re-design the state management.

**Comment by joncameron** [comment]
Opened samvera-labs/ramp#298 for eventually fixing the behavior with collapse during media playback.
