### ISSUE TITLE
[BUG] SME not loading data in Fedora 6 Avalon intermittently

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5383]
**Describe the bug**
For 3 of the 4 test items on Avalon sandbox, attempting to load the SME and edit structure causes some type of problem. Note that this seems to be intermittent.

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. click on file from Browse
1. Click on edit from the media object page
2. Click on structure in left nav, then click on Edit Structure

Some records then provided several errors in the SME, others just never loaded. Waveforms also did not show up in the SME.

**Expected behavior**
Should display waveform, video if it exists, and the editor to add timespans and headings.

**Screenshots/Screen Recording**
If applicable, add screenshots or a screen recording to help explain your problem.

Here are some examples:

1. Spins forever: https://avalon-sandbox.dlib.indiana.edu/media_objects/w9505044z/edit?step=structure
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbHpiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2d7180cd9c9c3fb55359ce1884dd493ffb54b747/image.png)

2. Does not load. Error message: "Error retrieving the media stream": https://avalon-sandbox.dlib.indiana.edu/media_objects/2z10wq20d/edit?step=structure (1st section: file_example_MOV_700kB.mov)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbUhiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--ee3e26113e521c4eb3b54fbbd0a9cc8b6e1b1ff3/image.png)

3. Loads, but says "No available waveform data" : https://avalon-sandbox.dlib.indiana.edu/media_objects/2z10wq20d/edit?step=structure (third section: sample-2.mp4)
4. [Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbVhiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--69aa449cc167b4bda39ce53466ca4800f4be383f/image.png)

4. Does not load. Error messages: "Error fetching IIIF manifest." : https://avalon-dev.dlib.indiana.edu/media_objects/7d278t00k/edit?step=structure 

**Environment (please complete the following information):**
 - Device / platform: Mac laptop
 - OS: Mac OS Monterey
 - Browser: Chrome
- [ ] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo
- [ x] avalon-sandbox

**Release:**
Fedora 6 + 7.7

**Additional notes**
Any additional information or notes that may be helpful in diagnosing or fixing the problem.

**Comment by elynema** [comment]
Note: the specific examples listed in this issue no longer exist on avalon-sandbox, as archivo-staging data was migrated into that instance.

**Comment by elynema** [comment]
When the section has captions, SME attempts to retrieve the captions from the HLS manifest, but fails. Generates "Error retrieving IIIF manifest" error.

**Comment by elynema** [comment]
For no available waveform data error, there is a threshold for auto-generating waveform (file duration).

**Comment by elynema** [comment]
Tested SME with a newly created item on avalon-sandbox, where streaming should not be an issue. SME still spins forever. https://avalon-sandbox.dlib.indiana.edu/media_objects/3b5918656/edit?step=structure

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkVMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a2213cebd8ccd791c78f2e202f017af78d6e523e/image.png)

**Comment by elynema** [comment]
I have not been able to find SME issues on avalon-dev, except for the issues for sections with captions. Seems to be limited to the Fedora 6 installation.

**Comment by Dananji** [comment]
I checked the code for SME's threshold for duration when generating waveform data using the JS framework, and it's 300 seconds (5 mins). So for the 3rd example, it should have actual waveform data instead of the dummy data.

**Comment by joncameron** [comment]
Closing since this is limited to the sandbox environment.
