### ISSUE TITLE
[BUG] Section supplemental files are not displayed until an item supplemental file is added

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5384]
**Describe the bug**
If section files are added to an item, they are not displayed on the media object page under the Files tab until an item supplemental file is added.

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. Go to any item on avalon-dev or avalon-sandbox. If nobody edits the record, here is a [current example](https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p) on avalon-dev.
2. Add a supplemental file to a section. It could be a caption, transcript, or supplemental file. Make sure there are no Item supplemental files (delete them if there are)
3. Save and preview
4. Under Transcripts tab, it says "No valid transcript(s), found, please check again." Under Files tab it says, "No supplemental file(s) in manifest

**Screenshots/Screen Recording**
Here is the current example on avalon-dev:

The final section has caption, transcript, and section supplemental files:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBblhjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--4c7c3154384ba7fb4964bfd7cfb0f38930d6dcce/image.png)

No files display in the UI:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbmJjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--a3e834ca7b6ea76cacf05a821ab0799aaf33ab55/image.png)

**Environment (please complete the following information):**
 - Device / platform: Mac laptop
 - OS: Mac OS Monterey
 - Browser: Chrome
- [ x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo
- [ ] avalon-sandbox

**Release:**
7.7

**Comment by elynema** [comment]
Seems like an issue with parsing the IIIF manifest.

**Comment by Dananji** [comment]
This was a bug in Ramp. Once the PR is merged, bring in a new build of Ramp into Avalon to test this.

**Comment by elynema** [comment]
Ready to QA on avalon-dev

**Comment by charumitraravi** [comment]
QA completed. Also tested the scenario by adding just the item section file without section files, and having both section and item files. There were no issues
