### ISSUE TITLE
[BUG] Auto-play of some sections seems to break Ramp and causes player to disappear

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5385]
**Describe the bug**
When auto-play reaches the third section of [this record](https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p), the media player disappears and does not play. 

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. Go to https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p
2. Select the 2nd section and let it play (you can skip ahead in the file)
3. When it auto-advances to the third section, the media player disappears

**Screenshots/Screen Recording**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdUhiIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--3ae3bc3bafee2f680ae4bda63c74a638ad8add57/image.png)

**Environment (please complete the following information):**
 - Device / platform: Mac laptop
 - OS: Mac OS Monterey
 - Browser: Chrome
- [ x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
7.7

**Comment by elynema** [comment]
Current Ramp build in Avalon does not auto-advance by default. This can't be tested until we add auto-advance behavior into media object manifests.

**Comment by masaball** [comment]
Original bug on Avalon-dev is not reproducible on the example item because of changes to manifest generation. The player is still breaking but that is because there is an item-less canvas in the manifest now and we have not implemented the handling for that situation in Ramp yet.

Editing the manifest to remove the blank canvas and testing directly in Ramp did not result in the player disappearing but there was a console error related to a function attempting to set a start time from an undefined object. A fix for that error is being added by Ramp [#270](https://github.com/samvera-labs/ramp/pull/270). Once that PR is merged and brought into Avalon, we are probably good to close this issue.

**Comment by elynema** [comment]
We believe this is resolved, although the original example linked still has problems for a different reason. Moving to QA, although it may not be possible to fully QA. Test sample of media objects. Will need to re-create issue if we encounter the behavior again after this.

**Comment by elynema** [comment]
Let's hold on QA for this one while waiting for Ramp #270, which is in next sprint.

**Comment by elynema** [comment]
This should be ready for QA now.

**Comment by charumitraravi** [comment]
The player disappearing issue seems to be resolved now. Although, I do find a number of items showing the following error:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3pkQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--010dfccbbbd0c5755dc89fd5e69087c492918a72/Screenshot%202023-11-15%20at%2011.46.15%20PM.png)
Some other examples:
https://avalon-dev.dlib.indiana.edu/media_objects/8049g504g
https://avalon-dev.dlib.indiana.edu/media_objects/ng451h485

**Comment by elynema** [comment]
@cjcolvar See Charu's comment above for an example item that has the "failed to fetch manifest" error.

**Comment by elynema** [comment]
@charumitraravi Did you finish QA of this once the multiple sections issue was fixed on avalon-dev?

**Comment by charumitraravi** [comment]
When I did QA for this item, there was no "failed to fetch manifest" issue due to multiple sections. I believe it happened a week after I tested this. Did you want me to retest this again now?

**Comment by elynema** [comment]
@charumitraravi, ah, so you were saying above that QA was completed. Presumably this specific item is giving errors because it is actually missing derivatives. I'll go ahead and close this.
