### ISSUE TITLE
[BUG] Media player and structured navigation disappear during conversion process

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5386]
**Describe the bug**
When a new section is uploaded to an item that already has sections, the media player and structured navigation disappear during the conversion process for the new section.

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. On avalon-dev, add a section file to an existing item.
2. Preview the file immediately.
3. You will see only a "Conversion status" bar with no player and no ability to see other sections.

**Expected behavior**
On mco-staging, the player displays with the first section, and other sections can be displayed and selected and played from the structured navigation. The new section can be selected from structured navigation and poster displays, but can't be played.

**Screenshots/Screen Recording**
On avalon-dev, if a new section file is converting, no player / structured metadata displays:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcExjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2c9d0ffea686743e454ab59abd984cd67ff4005d/image.png)

On mco-staging, if a new section file is converting, the other sections can be played. Even the new section can be selected with poster displaying; just can't play content.
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBckhjIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--aa1577ddfb7748db7c1d5e4dba9ad85fba926f6b/image.png)

**Environment (please complete the following information):**
 - Device / platform: Mac laptop
 - OS: Mac OS Monterey
 - Browser: Chrome
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
7.7

# Done Looks Like
- [x] First pass implementation of adding text to a placeholderCanvas element for sections current being transcoded so Ramp can render and display existing sections with derivatives in place
- [x] Leave existing object-level encoding progress bar at the top of the page, with hard reload once conversion has completed
- [x] For the section that is not yet converted, Display an error message when user clicks on it: "This item is still processing. Please check back later."

# Question
- Can we have an empty set in the manifest and render that gracefully in Ramp?

**Comment by elynema** [comment]
What are user notification requirements when items are being converted? Historically, was there a progress bar for each individual section, in addition to a larger conversion process flash message. What are the requirements now?

May be able to have a canvas with placeholderCanvas to display a poster image for section(s) that are being converted (like we use for playlists with inaccessible items).

In order to keep a conversion bar on the media object page, we'd probably need to do some kind of polling mechanism on the Avalon side.

**Comment by joncameron** [comment]
Options
- placeholderCanvas with a "check back later message"
- progress bar displayed in the media player
- move conversion panel to the top of the page (sitting outside of ramp)
- visual cue in structural navigation that's not the current tiny progress bar (construction pylon emoji or similar icon to indicate state of converting/non-converting

**Comment by charumitraravi** [comment]
@masaball 
I created an issue last week with 4 sections and the media files are still under processing status.
https://avalon-dev.dlib.indiana.edu/media_objects/kw52j8067
Could this be an impact of this bug fix?

**Comment by masaball** [comment]
Yes, it looks like there is an issue with this fix affecting those items.

**Comment by masaball** [comment]
So this bug fix appears to be working as expected for this media object. There is a backlog of jobs in avalon-dev's sidekiq and the files you uploaded are still enqueued so have not even started processing yet. There are around 84 background jobs enqueued, some over 2 weeks old. It's avalon-dev so it would probably be safe to kill some of the jobs and try to get it moving again but it would probably be good to get a deeper look before starting to randomly kill jobs.

@cjcolvar, can you take a look at the background jobs processing on avalon-dev and see why it might have gotten stuck?

**Comment by masaball** [comment]
So this bug fix appears to be working as expected for this media object. There is a backlog of jobs in avalon-dev's sidekiq and the files you uploaded are still enqueued so have not even started processing yet. There are around 84 background jobs enqueued, some over 2 weeks old. It's avalon-dev so it would probably be safe to kill some of the jobs and try to get it moving again but it would probably be good to get a deeper look before starting to randomly kill jobs.

@cjcolvar, can you take a look at the background jobs processing on avalon-dev and see why it might have gotten stuck?

**Comment by elynema** [comment]
I ran into a weird issue when I uploaded files #3 and #4 on this item where once conversion finished, the page reloaded and seemed to get stuck in a reload loop - probably reloaded 4 times before it settled. I then tried to replicate and get a screen recording and couldn't. I'll have to try again with a new item.

**Comment by charumitraravi** [comment]
@elynema I tried to replicate the issue you mentioned by uploading items for existing items as well as new items multiple times. I was **not able to replicate** it.
