### ISSUE TITLE
Smoke test Fedora 6 instance with migrated data

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5389]
# Description

https://avalon-sandbox.dlib.indiana.edu is now running an instance of Avalon with Fedora 6 containing data migrated from https://archivo-staging.dlib.indiana.edu (Fedora 4).

The Fedora 6 instance has already had basic smoke testing on creation / deletion of data. At this point, we primarily want to test that records migrated properly from Fedora 4 and that the migrated records can be edited.

Note that this version also includes the work being done for 7.7 release on the develop branch, so there may be bugs related to that. It's fine to report any/all bugs found.

Ideally, we'd like smoke test to be done by end of day Monday, October 2.

# Definition of Done

Test these functions:
- [ ] Edit resource description for migrated media object
- [ ] Add/edit structured metadata to a section for a migrated media object
- [ ] access control functionality is working in Fedora 6 installation : hide from search results, item access, and special access
- [ ] check that section order remains the same for a migrated media object with multiple sections
- [ ] resource description data is persisted for a migrated media object
- [ ] structured metadata is persisted for a migrated media object
- [ ] captions, transcripts, and supplemental files are persisted for a migrated media object
- [ ] access control data is persisted for a migrated media object
- [ ] access control / collection metadata is persisted for a migrated collection
- [ ] unit metadata is persisted for a migrated unit
- [ ] delete a migrated media object
- [ ] delete a migrated collection

**Comment by cjcolvar** [comment]
Note that playback of content will not work because the streams are pointing to production Archivo and avalon-sandbox isn't authorized to use those streams.

**Comment by elynema** [comment]
@cjcolvar Here is what Charu has documented so far (she's not done testing yet): https://docs.google.com/spreadsheets/d/16U-trbpFbW-JzdCjZHoNyf6WbvmiPvcLve7Jo3ncFwA/edit#gid=50357226

In particular, I'd take a look at the migration of access data at the collection level. Charu is reporting that managers are being converted to editors in the migration.

**Comment by elynema** [comment]
After further testing, Charu also noted some more errors in spreadsheet: errors when assigning staff roles at the collection level, and deleted items can still be accessed via their URL.

Per chris: I haven't looked into SME not loading, but the other two issues I resolved by correcting configuration issues (fixing DB connection for background jobs and copying the controlled_vocabulary.yml from archivo-staging).
