### ISSUE TITLE
Create re-usable batch ingest for a many-sectioned item

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5397]
# Description

We need to create at least one many-sectioned item to test performance in various environments (in particular, with Ramp and with Fedora 6). This would probably be easiest to do with a batch ingest file.

Item needs to have at least 100 sections.

I believe this zip file may already have some assts and a csv for batch ingest of a 100 section item: https://drive.google.com/file/d/1ee9iAsD8H9EakhDmTHj1zYz61AzGiEnA/view?usp=drive_link

There may be an issue with repeating sections of the same file if the file is deleted off the dropbox once it's processed for the first time.

# Done looks like
- [x] 100 section item created on avalon-dev
- [x] 100 section item created on avalon-sandbox
- [x] 100 second item created on avalon-staging

**Comment by cjcolvar** [comment]
I created a batch with a 100 section item based upon the  and loaded it in avalon-sandbox and avalon-staging.  I still need to load it into avalon-dev and store it in the google drive.

**Comment by cjcolvar** [comment]
Uploaded to google drive -> Avalon Media System -> Application Testing -> Quality Assurance -> Regular Test Objects
Batch spreadsheet uses archivist1@example.com user so that user must have privileges in the collection the batch is being loaded.  Takes about 30-45 minutes to load fully.

**Comment by cjcolvar** [comment]
avalon-dev: https://avalon-dev.dlib.indiana.edu/media_objects/76537133j
avalon-staging: https://avalon-staging.dlib.indiana.edu/media_objects/cf95jb46b
avalon-sandbox: https://avalon-sandbox.dlib.indiana.edu/media_objects/kh04dp75f

**Comment by joncameron** [comment]
👍👍👍
I created and uploaded a corresponding zip in the same folder for a 200 section item. It has the same media file and structure but with twice the width.
