### ISSUE TITLE
Test performance of large many-sectioned item(s) in Fedora 6

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5398]
# Description

Because Avalon is still using Active Fedora with Fedora 6, there may still be performance issues with large, many-sectioned items. Would like to compare timing adding / deleting a section and editing resource description for a large many-sectioned item.

Recommend upgrading avalon-staging up to date the branch that has 7.7 performance improvements as a Fedora 4 comparison with Fedora 6 on avalon-sandbox. Avalon-staging is running in a production environment, like avalon-sandbox.

# Done Looks Like
- [x] Update avalon-staging with 7.7 performance improvements
- [x] Compare timing for adding / deleting a section and editing resource description on avalon-staging and avalon-sandbox.

**Comment by cjcolvar** [comment]
I tested creating 100 section item via batch, adding a new section, and publishing the item.  I didn't test delete.  

Fedora 4 = avalon-staging
Fedora 6 = avalon-sandbox.

Batch ingest a 100 section item into Avalon:
Fedora 4 - 32 minutes 13 seconds
Fedora 6 - 44 minutes 6 seconds

Add another section to that item:
Fedora 4 - 85 seconds
Fedora 6 - 504 Gateway timeout - 35 minutes 55 seconds (left object broken?)

Publish the item (simple save):
Fedora 4 - 12 seconds
Fedora 6 - 6 seconds

**Comment by joncameron** [comment]
# Staging
Deleting from https://avalon-staging.dlib.indiana.edu/media_objects/cf95jb46b:
Delete section 100: 50.62s
Delete section 99: 48.93s
Delete section 98: 49.87s

Resource Description Save (97 sections): 11.37s

# Sandbox
Deleting from https://avalon-sandbox.dlib.indiana.edu/media_objects/cv43nw90r:
Delete section 100: 40.01s
Delete section 99: 36.28s
Delete section 98: 40.19s

Resource Description Save (97 sections): 6.66s
