### ISSUE TITLE
Add auto-advance to IIIF manifests for media objects

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5399]
# Description

To match IIIF spec, Ramp no longer auto-advanced from Canvas to Canvas by default. For playback to auto-advance on media object pages in Avalon, need to add the auto-advance behavior to the manifest in Avalon.

# Definition of done
- [x] IIIF manifest for media objects specify auto-advance just like playlist manifests
- [x] Test to see that the auto-advance happens with this change

**Comment by elynema** [comment]
@charumitraravi Giving you this one to QA. This change means that on avalon-dev, playback should auto-advance from one file to the next on a given item.

**Comment by charumitraravi** [comment]
QA completed. Verified items with audio as well as video files. Although, when the player auto advances, the page jumps down to the structured navigation once the video starts playing.
