### ISSUE TITLE
Do not display structured navigation if only 1 section with no structure

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5401]
# Description 

Current Avalon behavior is not to display section / structured navigation if there is only 1 section. Does this mean the IIIF manifest should not include a `structures` component in this case?

Example on avalon-dev with single section showing: https://avalon-dev.dlib.indiana.edu/media_objects/r207tp32d

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOFlMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2214f98a30b80b5d85186611170ecf9802c8e338/image.png)

MCO example with no section display: https://media.dlib.indiana.edu/media_objects/d217qq80h

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOGdMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ea6a43d7209c02e28d78b41c44d4a5de47c5e6e/image.png)

In Ramp, even if there is no structures section in the IIIF manifest, a message will display: "No structures in the manifest" instead of pulling in the structured navigation.

Is it ok to retain the display of a single section, or do we want to find a solution to tell Ramp we don't want to display this message?

**Comment by elynema** [comment]
Create Timeline and Add to Playlist are relying on structure to work, so keeping display of structured nav even if only 1 section seems like it will work well and provides consistent behavior.

**Comment by joncameron** [comment]
We'll retain the current behavior where Ramp always displays the StructuredNav component. It makes sense that this will always display and even for single section items that the section information would display to the user regardless of whether structure is attached.
