### ISSUE TITLE
Button text wrapping to 2 lines

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5402]
# Description

On avalon-dev, button text such as Create Thumbnail, Create Timeline, and Share button are wrapping to 2 lines as window gets narrower, which looks weird.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1lMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a3df37a836883b8ce2df739a522e0061db79686e/image.png)

On MCO, this doesn't happen and the button text just gets smaller:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1FMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cba2f457091f6f7e0039510da95e2871853d34e1/image.png)

**Comment by joncameron** [comment]
👍
