### ISSUE TITLE
Move Location of Admin Buttons on Item Page

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5405]
# Description
As a collection staff member, it's hard to currently find the Edit button as it is in the middle of the page, rather than left-aligned, in addition to the change moving the admin buttons to below the player. After team discussion, we decided to move the admin buttons back to their original location above the player.

# Done Looks Like
- [ ] Admin buttons are moved to below the navbar and above the player

# Admin Button Location Mockup
<img width="872" alt="Untitled-1" src="https://github.com/avalonmediasystem/avalon/assets/1406618/874fa757-e665-412d-9f1b-9293b2750c69">

**Comment by joncameron** [comment]
Another possibility is having the admin and user action buttons in separate rows:
<img width="763" alt="button_rearrangement" src="https://github.com/avalonmediasystem/avalon/assets/1406618/1ede705c-9b05-43fb-8b88-be2780ce1928">

**Comment by joncameron** [comment]
Admin buttons moving back above the player could be one easy fix, to match previous Avalon layout. But having the buttons for both admin and user actions on a single row seems like.

**Comment by joncameron** [comment]
- Create new issue for adding icons to the three user actions buttons (not just Share as is currently)

**Comment by elynema** [comment]
@joncameron Are you ready to pull this into next sprint pulling admin buttons above player, or do you want to play around with it some more?

**Comment by joncameron** [comment]
I think this is ready since pulling the admin buttons above the player as before seemed like the best idea. I'll update the issue description accordingly.
