### ISSUE TITLE
Test playlist page on mobile devices

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5409]
# Description

Need to test to make sure that page layout is flowing as it should on small screen devices. Also test at up to 200% zoom on a mobile device.

**Comment by elynema** [comment]
@charumitraravi Is this one you are ready to get started on? There's only 1 small bit that is currently missing from the playlist page, so I think it's ready for an initial evaluation.

**Comment by charumitraravi** [comment]
QA completed
1.Autoplay is not not working [IOS]
2.Play button alignment is not proper [iOS and android]
3. Unable to forward the video using scrubber [iOS and Android]

**Comment by elynema** [comment]
@charumitraravi Can you review open existing bugs to determine if these are new and then create bug issues if they are?

1. Sounds new
2. Looks like a duplicate of #5426 
3. Is this a duplicate of #5433?
