### ISSUE TITLE
[BUG] Media object page - Page automatically scrolls up and down while interacting with the media object elements

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5422]
**Describe the bug**
When there are multiple sections in the media file, the first section plays fine. After the second section, the page misbehaves:
1. Scrolling down : [Refer recording 1] - When I click on the video to pause/play , it scrolls down, making the video go out of view for the user. 
2. Scrolling up and jumping back and forth: [Refer recording 2] - When I scroll down and click on a section to play, the page scrolls up to the media player (which is expected), but the page keeps jumping back up and down, and at one point, the media player disappears. 

**To Reproduce**
1. Login to the Avalon dev account, and navigate to an item having multiple sections. 
2. Play the sections one by one on its own
3. Try to pause/play the media

**Expected behavior**
The page should stay on the part where the user intended it to, without jumping anywhere. 

**Screenshots/Screen Recording** 
1. **Recording 1** - Scrolling down
  https://drive.google.com/file/d/1hRwhaSjvLL88m3exREBgna9rNfi8R1i-/view?usp=drive_link

2.**Recording 2** - Jumping up and down and media player disappearing
  
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNkl0QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3dc9de14cad351b3fcefdfc0e70d0f2628fdfc1f/jumping%20up%20and%20down.mov)

**Environment (please complete the following information):**
 - Device / platform - Laptop
 - OS: - Mac Os
 - Browser - All major browsers
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
v7.7

**Comment by joncameron** [comment]
A one-line change that wasn't intended to go through that can be changed.

**Comment by joncameron** [comment]
I tested iOS in Browserstack and in Firefox on desktop and was no longer seeing the jumping behavior.
