### ISSUE TITLE
[BUG] reCAPTCHA error 

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5424]
**Describe the bug**

On the [Contact Us page form](https://avalon-dev.dlib.indiana.edu/comments), see this error:

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzArQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--08e3ec955399a0314bb0c97ef30424d46dd5d7e4/image.png)

**Expected behavior**
In MCO, no captcha displays.

**Environment (please complete the following information):**
 - Device / platform: Mac OS laptop
 - Browser: Chrome
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
7.7

**Comment by joncameron** [comment]
Probably a configuration thing where avalon-dev is hooked to the wrong key or wrong value (we can switch to reCAPTCHA v3 for avalon-dev as well)

**Comment by cjcolvar** [comment]
Avalon-dev was missing the additional configuration keys in its settings file.  I put those in and restarted and it looks good.
```
  type: "v3"
  v3:
    minimum_score: 0.3
```
