### ISSUE TITLE
[BUG] Mobile UI/UX issues in the Media object page

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5426]
**Describe the bug**

1. Content in scrollable divs (either structured navigation or metadata) can overflow onto the footer when in landscape mode only. Currently seeing on iOS only (tested in Chrome on iPhone and Pixel 8).
Structured navigation example
<img width="1732" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMldxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2cf55fdd068462a0757d4904860fa2738f315afc/IMG_5476.jpg" alt="IMG_5476.jpg" />

Metadata example
<img width="1732" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkNxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f1081a9b2180a09de757be7042a59b0f4ccdb339/IMG_5475.PNG" alt="IMG_5475.PNG" />

2. Large play button is not centered on the media player. Occurs on both Android and iOS. <br />
<img width="369" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMStxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4fb31a4c68a5d38c91c4bab496344635b740bde8/IMG_5474.PNG" alt="IMG_5474.PNG" />

3. No padding between the scrollable structured navigation component and the details/transcripts/files tabs. Occurs on both Android and iOS.
<img width="359" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzZxQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b6d78111117fd71580af9f315cf6509c328303e9/screenshot-Google%20Pixel%208%20Pro-14.0.png" alt="screenshot-Google Pixel 8 Pro-14.0.png" />

# Done Looks Like
- [x] In landscape mode, footer text always falls below the bottom of the container for tallest div / component on both Android and iOS devices
- [x] Large play button is center in the media player in both portrait and landscape mode on Android and iOS devices
- [x] A small amount of whitespace padding flows after the end of the structured navigation component and before the start of the tabs with metadata / transcript / files when in portrait mode on Android and iOS devices.

**Comment by elynema** [comment]
We should make some individual issues for some of these:

- create a combined issue for #3,4, and 5
- create issue for #8
- create an issue for #6

**Comment by elynema** [comment]
I think #4 could be added on to #5429, as that issue will involve changing the styling a bit of the of structured navigation.

#5 should be a new issue - player icons / player is getting cut off.

#1,3, and 6 could probably stay on this issue as UX adjustment items, I think.

**Comment by elynema** [comment]
Tweaking with CSS can be relatively challenging. This could be lower priority as it is about look and feel for mobile users only.

**Comment by elynema** [comment]
@Dananji Still seeing the issue of content overlap with footer on Android Chrome / Firefox and in Safari on iOS; only in landscape mode. Weirdly, it's working ok in Chrome on iPhone. It's not a problem on iPad, either (presumably b/c this acts more like a desktop).

<img width="700" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNW9aQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d97296ad47bd3d96fa7d716bb1583d2c6715fad1/bs_realdroid_Mobile_Samsung%20Galaxy%20S22-12.0-1080x2340%20%282%29.jpg" alt="bs_realdroid_Mobile_Samsung Galaxy S22-12.0-1080x2340 (2).jpg" />

Padding before tabs and play button look good on Android and iPhone / iPad.

**Comment by joncameron** [comment]
Bugs fixed! I tested all three issues on both iOS and Android Chrome.
