### ISSUE TITLE
Make it clear structured navigation is a scrollable element

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5429]
# Description
Currently, the structured navigation component below the player on the media object page is a scrollable element. However, it's not at all obvious to the user that it is scrollable. In this example, it just looks like there are only 3 sections (but there are actually 5).

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEZXQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--812a534787d7ed122342215d7062cedf72ca810c/image.png)

# Done Looks Like
- [ ] Scrollbar always appears for StructuredNav when there is content overflow for Chrome and Safari

**Comment by joncameron** [comment]
This may already be changed in Ramp; https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p and https://avalon-dev.dlib.indiana.edu/media_objects/76537133j are displaying the scrollbar by default.

**Comment by elynema** [comment]
@joncameron I'm not seeing the scrollbar in Chrome until I actually start scrolling. It does not show up always or on mouse-over.

![image](https://github.com/avalonmediasystem/avalon/assets/109625239/cc0dc310-3f08-420e-a4e2-0618d1448699)

**Comment by elynema** [comment]
Want to force scrollbars for both webkit and mozilla, since always show scrollbar setting is not on by default in Firefox. Atishi requested we make this change prior to user testing as it is a usability issue.

**Comment by masaball** [comment]
As far as I have been able to determine, firefox/mozilla does not support custom scrollbar settings basically at all. On non-mozilla browsers, scrollbars can be edited with [::webkit-scrollbar pseudo-elements](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar). But Webkit is not used/supported by [mozilla](https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar#browser_compatibility).

In terms of standardized CSS elements, the only scrollbar related ones I have found are for setting the [color and width of the scrollbar](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scrollbars_styling) (fun to note that these properties are only compatible in firefox). There are no styling options that override browser or OS level settings for the scrollbars. 

It does look like there are some JS libraries such as [simplebar](https://github.com/Grsmto/simplebar) or [overlay-scrollbar](https://github.com/KingSora/OverlayScrollbars) that provide the ability to make custom CSS scrollbars that override/overwrite the browser display. @Dananji, @elynema, @joncameron what do we think about bringing a new dependency into ramp for scrollbar display? 

And if we want to pursue that route, Dananji would you be able to vet the libraries/plugins? Besides having the setting/feature to override auto-hide I'm not sure what other considerations would need to be taken into account before bringing in a new library.

**Comment by masaball** [comment]
Change for chrome/safari has been merged to Ramp and will be brought into Avalon before the user testing week of 11/13. Handling for firefox will be more fully discussed and investigated later and brought in as a future PR.

**Comment by joncameron** [comment]
Tested and working (scrollbar visible to start) in Chrome 111 on macOS Catalina in Browserstack.

Regarding scrollbars: I have doubts that a library like simplebar would fix this issue, since it "keeps the native overflow: auto scroll" behavior, which is the thing that doesn't seem to be respected anymore by Firefox in certain OS situations. And given that Edge is now Webkit-based, I don't trust that they won't do a rug-pull and put OS defaults for scrollbars above the CSS pseudo selectors for webkit in the future.

That there is no styling or markup available to force a scrollbar in all cases without resorting to some sort of shim is frustrating, but this feels like something we can come back to, or alternatively have some different UI in place to clearly indicate a scrollable area when scrollbars are hidden or thinly styled by default.

**Comment by charumitraravi** [comment]
QA completed. The definition of done is verified on Chrome and Safari
