### ISSUE TITLE
[BUG] - iPhone - Closed caption icon is misbehaving in the media player

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5431]
**Describe the bug**
1. CC button is appearing when video/audio is played, even when the item does not have captions. 
 Ex: https://avalon-dev.dlib.indiana.edu/media_objects/zs25x844t 
2. Icons move after video/audio is played (refer screen recording)  - settings icon moves towards the right and disappears. Presumably this is because the CC button has appeared. 
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUpMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bbf40e98fe0166e9194f29b0edb2ca56504090ec/cc%20button%20appearing.mp4)
3.CC button is not shown in the media player when an item with captions is first opened. When the media item starts playing, the CC button does show up (may be related to #2 bug above). 
4.Does it make sense to show subtitles when there is no cc? Also, it can be observed that the subtitles menu shows an option called "cc" even though the video did not have any subtitles [iPhone]
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTVPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--88c8f66db0e6f6d329ac247cfdd2fbe83d7435eb/subtitles-ios.jpeg)
 

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. Go to the media object page containing multiple video/audio files

**Environment (please complete the following information):**
 - Device / platform - iPhone mini
 - OS: iOS
 - Browser - Safari, Chrome
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
v7.7

**Comment by Dananji** [comment]
> Icons move after video/audio is played (refer screen recording) - settings icon moves towards the right and disappears. Presumably this is because the CC button has appeared.

I tested the HLS example in the [VideoJS site](https://videojs.com/), and it seems the behavior there is similar to what we are seeing with our implementation. From what I've read in issues other people have reported, iOS handles the captions on its own overriding the VideoJS behavior.

**Comment by elynema** [comment]
I am not seeing issue #1 anymore.

For issue #2 and #3, the CC icon shows up briefly in the videojs player when the video is played and just before the native player opens on iOS devices. The placement of buttons seems ok now, but it is strange that the CC button doesn't show up until the content plays. Presumably this has to do with the captions being provided in the HLS manifest?

For #4, the subtitles menu does appear in the native iOS player even when there are no captions. It presents the options off, auto (recommended), and CC. That CC option does not show up when there are captions. I'm not sure if this is behavior that can be changed or not.

**Comment by Dananji** [comment]
> For issue #2 and #3, the CC icon shows up briefly in the videojs player when the video is played and just before the native player opens on iOS devices. The placement of buttons seems ok now, but it is strange that the CC button doesn't show up until the content plays. Presumably this has to do with the captions being provided in the HLS manifest?

Yes, that was my understanding from what I read. iOS handles the captions in the HLS manifest overriding VideoJS's behavior which causes this behavior.

> For #4, the subtitles menu does appear in the native iOS player even when there are no captions. It presents the options off, auto (recommended), and CC. That CC option does not show up when there are captions. I'm not sure if this is behavior that can be changed or not.

We cannot access iOS's native player within the JS code. If there isn't another solution we can implement in Avalon this could be documented as a known issue.

**Comment by elynema** [comment]
I'm going to close this as I think it is "good enough" for release. @joncameron Is #4 something that is worth documenting as a known issue?
