### ISSUE TITLE
[BUG] iPhone - Share options are open by default when an item is opened 

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5432]
**Describe the bug**
The share options are shown by default when I open an item and cannot be closed. All action buttons (edit, etc.) disappear. [intermittent]
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWRMQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f0389101f0ba3b636441b2fd986a4b4587423cd4/RecordIt-1697639032.mp4)

**To Reproduce**
1.Go to the media object page containing multiple section files on an ios device.

**Environment (please complete the following information):**
 - Device / platform -  iPhone mini
 - OS: iOS
 - Browser- Safari, Chrome
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
Is this issue associated with a specific release? [e. g. 7.6]

**Additional notes**
Any additional information or notes that may be helpful in diagnosing or fixing the problem.

**Comment by joncameron** [comment]
Retested and this bug is no longer present; closing.
