### ISSUE TITLE
[BUG] iOS - Scrubber movement is not smooth in full screen 

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5433]
**Describe the bug**
Scrubber does not advance properly in full screen - The scrubber movement is not smooth in full screen - it moves after every few seconds. This happens for pretty much every item in iOS; more intermittent in Android. 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL05OQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--168f742a7779d111913cd1598f8d06805152aa14/RecordIt-1697658563.mp4)

**To Reproduce**
1.Login to the avalon site, and navigate to the media iobject page containing multiple section files on an iOS device

**Environment (please complete the following information):**
 - Device / platform - iPhone mini, iPAD (intermittent)
 - Browser Safari, Chrome
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
v7.7

**Comment by elynema** [comment]
This bug is weird, but doesn't really actually break the user's experience, so might be able to de-prioritize from 7.7 release.

**Comment by joncameron** [comment]
Retest and close

**Comment by elynema** [comment]
This seems to be working reasonably across iPhone and iPad. There have been many changes made since this issue was created. Closing.
