### ISSUE TITLE
[BUG] - Media playback issues in iOS devices 

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5434]
**Describe the bug**

1. Video corrupted issue - Found a weird issue on Apple devices (iphone and ipad) - it says the videocannot be played (aborted) as it is corrupted or the browser does not support, although i could play the file on Android and the web on the same browser (chrome, safari)
data: https://avalon-dev.dlib.indiana.edu/media_objects/0g354f213

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3BPQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3967844820f084f409ec27b9d3a567939e1b1d4b/video_corruptyed.jpeg)

2.Page hangs/misbehaves/becomes unresponsive/too slow while playing large videos (~20 mins) -(So far observed on  iphone only)
Observed: Media player controls (eg pause, play, rewind) and closing the player would not work. Although the player closes, the sound will still play in the background, or the page freezes.
Data: https://avalon-dev.dlib.indiana.edu/media_objects/fj236208t

**To Reproduce**
1. Login to the avalon account and open a media object with multiple section files on an iOS device

**Environment (please complete the following information):**
 - Device / platform-  iPhone mini, iPad
 - OS: iOS
 - Browser - Safari,Chrome
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
v7.7

**Comment by elynema** [comment]
I tested the Lunchroom Manners video (https://avalon-dev.dlib.indiana.edu/media_objects/fj236208t) on my iPhone Mini. Because it is iOS, it opens in native player. The native player does have the 10 second fast forward / backward buttons that are not available via web playback. 

I found that activities like fast forward or seeking ahead in the video worked, but VERY slowly. There was a multi-second lag after I did those before the video actually jumped. I was able to get the video player to crash pretty reliably by playing the video for 15 seconds and then trying to use the button to seek backward 10 seconds. 

Charu reports that she is seeing these issues both on and off campus (so on and off VPN), and not just with this specific example.

**Comment by elynema** [comment]
For #1, had the same issue with https://avalon-dev.dlib.indiana.edu/media_objects/0g354f213. It gives a media playback abort message. Could there be some issue related to the file type of the original file? Or perhaps some corrupted metadata about the file?

**Comment by joncameron** [comment]
Timeboxed to a 3 since this will require some investigation.

**Comment by elynema** [comment]
For #1 above, https://avalon-dev.dlib.indiana.edu/media_objects/0g354f213 is no longer crashing on my iPhone over VPN, but is playing correctly.

For #2 above, I'm still able to get the native playing on iOS to crash when I start seeking back and forth in the video, especially using the 10 seconds back button in the native player. The progress bar is still pretty laggy. 

I have not tested on Browserstack at this point, only on an iOS device over VPN.

**Comment by elynema** [comment]
@masaball @Dananji This solution seems to be working on iPhones. However, when testing on the iPad in Browserstack, it's NOT forcing open the native iOS player. 

In Safari on the iPad, we are seeing exactly the same player we do in Safari on a computer, both in non-full screen and full screen mode. It is being non-responsive, just as described in this ticket, although that could also be the issue we are seeing in Safari on computer in Ramp #338. https://github.com/samvera-labs/ramp/issues/338

In Chrome on an iPad, it will play non-full screen in Chrome but if you open full screen it appears to try to leverage the native player. Unfortunately, the scrubbing and other buttons in the non-full screen player in Chrome on the iPad is also showing huge latency / unresponsiveness. After a few attempts to scrub, the media player controls disappear and then don't come back for many seconds when I click on the video. The native player on iPad is also unresponsive when attempting to scrub, jump forward/back. If I attempt to scrub, then the player stops responding to play/pause, etc.

**Comment by elynema** [comment]
I will close this issue because iPhones are working now (probably the bigger use case), but open a new issue for issues with iPads.
