### ISSUE TITLE
[BUG] Media player controls are not working properly on Android devices

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5435]
**Describe the bug**
1.Android only  -Unable to move the scrubber to skip ahead/rewind the video when in non-full screen mode

2. Android only - Video pause and play does not work when I click on the video in non-full screen mode - Need to click on the pause/play button in the player's control bar

**To Reproduce**
1.Navigate to the media object page on a mobile device.

**Environment (please complete the following information):**
 - Device : Samsung s20 fe
 - OS: Android
 - Browser : Chrome, Firefox, Safari
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
v7.7

# Done Looks Like
- [x] Investigation into this issue and how to resolve
- [x] Progress bar scrubber works with touch input
- [x] Media plays and pauses from touch input on media element

**Comment by joncameron** [comment]
@charumitraravi Can you retest? I couldn't reproduce in Chrome on a Galaxy S10 or Safari on iPhone 13 in Browserstack.

**Comment by charumitraravi** [comment]
@joncameron 
For both issues 1 and 2, the video has to play in the non full screen mode, and oddly, it doesn't seem to happen in the first few seconds of the video (maybe try after running the video for 15-20 seconds. I was able to reproduce it consistently)

**Comment by joncameron** [comment]
Thanks Charu! I could reproduce: and the console is flooding with errors on this one so something is definitely not right:

<img width="406" alt="Screenshot 2023-11-09 at 5 57 00 AM" src="https://github.com/avalonmediasystem/avalon/assets/1406618/5d66faa5-e0d6-4692-8e40-7714df8a2862">

**Comment by elynema** [comment]
Video pause / play is working when clicking on either the video or the pause/play button in non-full screen mode on an Android device. The scrubber is also working.

Volume cannot be adjusted in non-full screen or full-screen player mode. It just toggles back and forth between muted and un-muted when you click on it to try to open the slider. This is only on video; audio volume can be adjusted. @masaball want me to push this bug to a new issue?

**Comment by masaball** [comment]
@elynema Yes, I think it makes sense for that to be made into its own issue.
