### ISSUE TITLE
Really long filenames break ingest

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5436]
Pulled over from local board [#174](https://github.iu.edu/AvalonIU/Avalon/issues/174)

# Description
[Chris]: It appears that really long filenames overflow the encode dashboard database record for the title field: https://app.honeybadger.io/projects/54117/faults/99716515
A DB migration may be needed to modify that column to change the datatype or a truncation of that field in ActiveEncode::EncodeRecord before attempting to save it.

[Chris]: I ran into this when trying to load a batch on avalon-sandbox as part of https://github.com/avalonmediasystem/avalon/issues/5397. avalon-sandbox was using minio for the dropbox and a mysql database when this happened. I temporarily worked around it by increasing the size of title to varchar(1000) and display_title to varchar(750).
This should probably be moved to the core board and handled there.

# Done Looks Like
- [ ] A user can ingest a filename with up to 256 characters either by web upload or batch ingest

**Comment by elynema** [comment]
Move this over to mco-staging for testing and consider deploying out to production?

**Comment by joncameron** [comment]
Tested with filename `hereisareallylongfilenamewithnospacesorextracharacterscommathatistosaynothingwhichshouldcreateproblemsinfilenamehandlingotherthanthefacethatitisjustveryverylongandthatisthelongopenparenthesislolcloseparenthesisandshortofit.MOV`,
227 total characters and things worked as expected: https://avalon-dev.dlib.indiana.edu/media_objects/mw22v546v.
The encoding dashboard, however, expanded horizontally to fit this, which looks funky but could be changed with truncation of the filename in the table.
