### ISSUE TITLE
[BUG] Full screen button is hidden in the media player (Android)

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5438]
Full screen button is hidden (Android ) 
Note: This issue is reproducible only on the portrait mode

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. Login as an Avalon user on an android device, and open an item. 

**Expected behavior**
All the icons should be visible in the media player 

**Screenshots/Screen Recording**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3BOQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0ef9a87ed580a552ede1580b435e33a8de47f473/Screenshot%202023-10-18%20at%203.58.58%20PM.png)

**Environment (please complete the following information):**
 - Device / platform - Samsung s20 fe
 - OS: Android
- Browser - Chrome, Safari
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
v7.7

**Additional notes**
Any additional information or notes that may be helpful in diagnosing or fixing the problem.

**Comment by joncameron** [comment]
I'm going to close this since this issue derives from Video.js and is the same video player issue as reported in #5410, which will be marked as "known issue".
