### ISSUE TITLE
[BUG] Add to playlist bugs

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#5453]
### Description

Bugs reported from QA and discussions:
- Editing the title resets when I click on any of the radio buttons again/ edit time selection 
- When user has the add to playlist form open, and clicks a spot in the media file outside of any timespan, the current track option should be disabled and the current track name text (in parentheses) should be removed, since there is no current track.

### Done Looks Like
- [x] Edits made in the input fields for the title, description are retained when checking the radio buttons (even the same option)
- [x] Current track option should be visibly blocked (text color) and should have empty parenthesis when playhead is moved out of any timespan in the player

### Notes

Add to playlist form doesn't get updated with playback once it is collapsed, i.e. it doesn't get updated with player's `timeupdate` event. It takes the state of the player and structured navigation at the time it is opened and populates the form(s). 

However it gets updated with the user scrubbing, which corresponds to the `seeked` event in the player.

**Comment by Dananji** [comment]
With the changes to the manifests in avalon to include Canvas information for section level Range items, Ramp now displays the structure highlight in the time-rail for the total duration when the playhead is outside of a timespan structure element as seen in the image below. In this case we always have an active track in the player and structured navigation. 

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeEM1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--51f47ac85b6037be4183c0d12524adafd75280c4/image.png)

Question: with this change in place what does it mean for disabling current track option?

**Comment by charumitraravi** [comment]
QA verified -  items with single sections with structure are verefied. Although for more extensive testing, we need to verify items with multiple sections and structures, which is blocked due to [5479](https://app.zenhub.com/workspaces/avalon-5bff96674b5806bc2bf90276/issues/gh/avalonmediasystem/avalon/5479)

**Comment by charumitraravi** [comment]
Additional observations:
1.Although "Current track" is disabled, clicking on that option shows the Title and description prompt.
Refer [Screen recording](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM29iQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc203c227d738a1300144bb5d69b16929b17c7fc/Screen%20Recording%202023-11-29%20at%202.55.03%20PM.mov)


is this expected?

**Comment by elynema** [comment]
@charumitraravi Yes, that is a bug. Clicking on the disabled track option should not open the title and description prompt.

Have you tested this with multiple sections and structures now that those are available again?

**Comment by elynema** [comment]
@Dananji Pulling this back to In Progress because Charu identified a bug - when you click on the disabled "Current track" option when first opening the Add to Playlist outside of a track, the title/description fields still open up.
