### ISSUE TITLE
[BUG] Add to playlist button gets disabled intermittently

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5461]
**Describe the bug**
The add to playlist button gets disabled intermittently for some of the sections/timelines within the sections within an item
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK091QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6eb850416a6722e48ebef565e4a7d9e28fcbb52f/image.png)

**To Reproduce**
1.Navigate to an item, and using the add to playlist button,  add a section or a track to a playlist
2.Now select a different section/timeline in the same item. 
(or)
Refresh the page and try to select a section/timeline

The "Add to playlist"  button will be disabled

**Expected behavior**
The user should be able to access the "add to playlist" under all scenarios.

**Screenshots/Screen Recording**
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK3l1QVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--90ef365a0f3d62774434eec2456546287cb90926/Screen%20Recording%202023-11-07%20at%2010.32.18%20AM.mov)

**Environment (please complete the following information):**
 - Device / platform - Laptop
 - OS: Mac OS
 - Browser - Chrome, Safari
 - 
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
v7.7

**Comment by charumitraravi** [comment]
https://samvera.slack.com/archives/G2E762545/p1699369453007639
Adding the slack conversation here for refrence.

**Comment by joncameron** [comment]
Need to reproduce this and check the console logs to get a better idea of what might be occurring.

**Comment by elynema** [comment]
Can we grab a console error when this is happening? Dananji has not been able to reproduce. @elynema

**Comment by elynema** [comment]
@Dananji I'm attaching another video here that was taken with the console window open in case that helps.
[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkt3QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cc9989ceb645a8fe0853364ed3b9272d51df8575/Screen%20Recording%202024-01-09%20at%202.05.14%20PM.mov)

**Comment by elynema** [comment]
@Dananji I'm still seeing this issue in Chrome, Firefox, and Safari on my Mac laptop. When the Add to playlist button remains disabled, the Create Thumbnail button is enabled. I wasn't sure if they were both supposed to be relying on the same event.

Here's a video with the console open in Chrome:

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1h4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--80f5d58a2795bf599f19d813488388b9d18e2519/Screen%20Recording%202024-01-23%20at%204.32.56%20PM.mov)

**Comment by elynema** [comment]
This appears to be working in Safari, Chrome, and Firefox on MacOS laptop. Worked in Safari and Chrome on iPad. Would not be bad to test in Android if possible.
