### ISSUE TITLE
Consolidate player listener related code

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5473]
In many of the partials on the Media Object page there is javascript to wait for the player to finish loading and then perform actions, particularly placing event listeners onto the player or other elements within the Ramp context. All of this code should be DRY-ed up and consolidated for easier maintenance.

Known media object partials containing the same or similar code:
- _timeline.html.erb
- _thumbnail.html.erb
- _add_to_playlist.html.erb
- _share.html.erb
- _item_view.html.erb

It hasn't been finished/merged yet, but the playlist page work also includes a similar function in 7.7.

# Done Looks Like
- [ ] Pull the "adding event listener" code into its own module
- [ ] Call functions in partials rather than have duplication

# QA
 - test all event buttons: add to playlist, create thumbnail, create timeline, share section, transcript

**Comment by joncameron** [comment]
We have a lot of intervals polling for player events; this will be helpful to clean up. Everything should be consolidated into a single place for ease of maintenance.

**Comment by joncameron** [comment]
Tested all of the actions in the QA section and they all worked as expected.
