### ISSUE TITLE
MediaObject#show setting up instance variables unnecessarily slowing down page

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5477]
# Description
The MediaObject#show action setup a number of instance variables for the player which may not be necessary now that ramp is rendering pretty much all of the item show page.  The work to setup these variables are also duplicative given ramp requests the IIIF manifest. I'm guessing that section information is being fetched from solr and stream tokens setup which aren't used at all.  `@media_object` is probably still needed for certain authorization checks but we can make sure that SpeedyAF isn't loading any children relations that aren't needed.  (See note in #5476)

# Done Looks Like
- [ ] MediaObject#show action is cleaned up to include only what is needed to render ramp and the show page.

**Comment by cjcolvar** [comment]
I did a quick investigation on this and found that it will be a bit harder than I had anticipated.  It also revealed some functionality gaps that we will probably need to address before release.

Functionality that needs to be added to ramp:
- Ability to pass starting canvas into ramp (also need to make sure share links/embed code/etc. match starting canvas)
- Ability to pass starting time (`t=`) into ramp

The player page needs to setup media object and master file objects on page load in order to populate the share panel.  It seems like there are two options for handling this: put all of the needed information into the IIIF manifest or have the page dynamically request `/stream`.  (`/stream` is an endpoint that provides share links, embeds, etc.) I'd favor the former if it makes sense.

Possible changes to avoid needing `/stream` endpoint which provides share panel information:
- Put homepage property on canvas for share url
- Use homepage properties for "Share this resource"
- Is there a place in the IIIF manifest to include information needed for the embed code?

Other places where media object/master file information is needed:

- When initializing Avalon ramp component lots of information is passed in including: master file count, has_structuralMetadata, transcripts, supplemental files, etc.
- `_item_view.html.erb` needs current stream for oembed links in header
- Some other partials need `ordered_master_file_ids`, `@masterFiles`, and `@media_object.master_files`

**Comment by joncameron** [comment]
# Generated Issues
Ability to pass starting canvas into ramp (also need to make sure share links/embed code/etc. match starting canvas): #5493
Ability to pass starting time (t=) into ramp: #5508
Adding Share informatino to the IIIF manifest: #5502

**Comment by joncameron** [comment]
Looking again at Solr calls for the item show page might be the only quick win at the moment.
Cleaning up /stream would be a nice to have but probably isn't going to help page generation speeds.

**Comment by cjcolvar** [comment]
Wrote up new issue for the rest of the work mentioned in my comment above: https://github.com/avalonmediasystem/avalon/issues/5543
