### ISSUE TITLE
[BUG] Manifest generation fails for some items

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5479]
When an item is opened, the media does not load and an error message "Failed to fetch Manifest. Please check again."

Update:
Observed that this issue is occuring for most of the items with more than one section. If I manually add a section to an item with one section, the manifest fetching fails

**To Reproduce**
Steps to reproduce the behavior, including the results:
1.Open an item form the item list page
eg: https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p

**Expected behavior**
The item contents should be displayed 

**Screenshots/Screen Recording**
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMUQrQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e1442b118291b21eaafdaafc7f4fbd8eefe4427/Screenshot%202023-11-22%20at%202.14.58%20PM.png)

**Environment (please complete the following information):**
 - Device / platform : All devices
 - OS: All Os
 - Browser: All browsers
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
v7.7

**Additional notes**
@Dananji 's comment:
It seems for some of the items the manifest generation fails, and the error seems to be related to stream tokens looking at the network  response. This is new and could be related to the work merged in https://github.com/avalonmediasystem/avalon/pull/5478 yesterday

**Comment by elynema** [comment]
Chris said he would take a look at this today.

**Comment by cjcolvar** [comment]
This should be fixed now and can be retested on avalon-dev.

**Comment by charumitraravi** [comment]
Qa completed.
