### ISSUE TITLE
Word Documents Not Rendered

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5482]
# Description
Word documents should display in the transcript component but are currently not displaying.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNWNTQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--aa79cb8df1e0b5b94beeb1bdc3198eeec854626f/Screenshot%202023-11-28%20at%2010.02.25%E2%80%AFAM.png)

See section 2 of https://avalon-dev.dlib.indiana.edu/media_objects/gf06g267d

# Done Looks Like
- [ ] .doc files render in the Ramp transcript component

**Comment by elynema** [comment]
I tested uploading a .doc file to the third section of this item: https://avalon-dev.dlib.indiana.edu/media_objects/gf06g267d.

It is an option on the transcript component, but when selected the content doesn't actually load (I just get a loading icon).[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMXdWQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c28550db4d8dbb57546da3debb4dd9e582a2c4f3/image.png)

**Comment by Dananji** [comment]
In the original issue, the `.doc` file in the 2nd section has the type `text/html` in the Manifest. 
Transcript component in Ramp uses either the `content-type` in the fetch request or the file extension in the resource URL to determine the file type and handle presentation accordingly. With this particular file the type is derived to be `text/html` by the transcript-parser, which Ramp doesn't display in the transcript component.

![image](https://github.com/avalonmediasystem/avalon/assets/1331659/1d9909a0-d4fa-4f99-95ce-f96ed8356acb)

And I'm able to see the `.doc` file in the 3rd section of the same item in `avalon-dev`;
![image](https://github.com/avalonmediasystem/avalon/assets/1331659/60c048bd-12cc-4a21-bf76-b4086580fa17)

**Comment by elynema** [comment]
Currently, the transcript component works only with .doc, .docx, .vtt, .json, and plain text. The manifest is declaring this file to be text/html, which is not supported.

**Comment by Dananji** [comment]
As it turns out, Transcript component never worked with `.doc` files when we swapped the previous transcript viewer with the iframe to `mammoth.js`. It only works with `.docx` files.
I made necessary code changes to display a proper error message to the user, and updated the documents to specify that it only works with `.docx` files.
