### ISSUE TITLE
CSRF token issues with playlist markers

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5485]
When attempting to create, edit, and delete markers on the new ramp based playlist page we receive a "422 Unprocessable Entity" error. This is caused by the CSRF token check failing.

It may be possible to [inject the token into the request headers](https://guides.rubyonrails.org/v6.0.0/working_with_javascript_in_rails.html#cross-site-request-forgery-csrf-token-in-ajax), though this could be difficult because we would need to intercept every non-GET request coming from the component and insert the token.

We could also store the CSRF token in a cookie and have Ramp read the token into the request header, see [here](https://blog.eq8.eu/article/rails-api-authentication-with-spa-csrf-tokens.html) and [here](https://medium.com/codex/deploying-a-rails-api-react-app-with-sessions-and-csrf-tokens-d33d2924639).

It is also possible to disable CSRF checking by controller or action, so we could turn it off for just the needed marker actions. However, that adds security risks that we probably want to avoid. 

Maybe there are other approaches? If we're lucky, Ramp [#298](https://github.com/samvera-labs/ramp/issues/298) might resolve this. (Now deemed unlikely).

# Done Looks Like
- [x] Investigation and figuring out what done looks like and how to handle this issue

**Comment by joncameron** [comment]
Tested samvera-labs/ramp/#298 and standard CRUD actions were successful so I'm going to close this as well. +1 @masaball
