### ISSUE TITLE
[BUG] After copy playlist, modal does not close

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5490]
# Description

On the playlist page, if I click the Copy Playlist button, and then create a new playlist, the copy playlist modal stays open instead of closing so I can see the original playlist page. This happens regardless of whether I select "Create" or "Create and Edit" from the modal.

Note that new playlists are created as expected.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd0VqQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9ffaf81b369d2a329c922d6ede129238ab851560/image.png)

# Done Looks like

- [x] Based on current behavior in mco-staging, if I click the "Create" button, the modal should close and I should see the original playlist I was copying.
- [x] If I click the "Create and Edit" button, the edit page for the new playlist should load automatically.

**Comment by joncameron** [comment]
Probably another modal/Coffeescript issue.

**Comment by elynema** [comment]
See #5491 for notes about coffeescript that may be related

**Comment by joncameron** [comment]
Tested and working for me in dev.
