### ISSUE TITLE
[BUG] Copy Playlist is not Redirecting with `Create and Edit`

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#5491]
### Description

Copy playlist function in the playlist show page, doesn't redirect to the copied playlist's edit page when `Create and Edit` button is clicked.

Steps to reproduce:
1. Navigate to a playlist view page
2. Click on `Copy Playlist`
3. Click on `Create and Edit` button in the modal

The redirect works for the copy function in the playlist index page.

### Done Looks Like
- [ ] When using the `Copy Playlist` function on the playlist page, the user is redirected to the copied playlist's edit page when `Create and Edit` button is clicked

**Comment by joncameron** [comment]
Redirect is coming in from an existing coffeescript, and it's probably not getting initialized properly inside the React component. Functional but the Coffeescript is probably breaking.
