### ISSUE TITLE
Section Route Loads Ramp to the Correct Section in Item

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5493]
# Description
Routes for masterfiles aren't working as intended because Avalon and Ramp are missing some setup to initialize the player with the desired section ID.

For example, the URL https://avalon-dev.dlib.indiana.edu/media_objects/gf06g267d/section/d217qp50k should load the 2nd section of the item into the media player (the section with ID d217qp50k), but the first section of an item is loaded regardless of the route.

Avalon will need to send a prop to Ramp, and Ramp can read that and initialize accordingly.

# Done Looks Like
- [x] The response from a section/master_file route initializes Ramp with the section ID loaded into the player

**Comment by cjcolvar** [comment]
Add ramp prop that hooks up to existing variable for handling manifest's start canvas attribute.  Should pass canvas id which can be constructed by Avalon from request url params without having to look up list of master file ids.  If ramp doesn't find a match it can fall back to first canvas.  This ticket is for the Avalon side and a ticket will be written for the ramp work.
