### ISSUE TITLE
Let Tabbed Nav Content Fill Column Height

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5498]
# Description
When the Details panel  a long list of metadata, it expands vertically and is capped at a maximum height. The maximum height should match the height of the structured nav. This is the same for the Transcript and Files tab as well—content should extend to the bottom of the col-sm-4 parent element.

# Screenshots
## Current
<img width="1363" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2RSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8e8757e0d6a0a993026a6da656a78e4fb4e39d28/Screenshot%202023-12-12%20at%2010.40.37%E2%80%AFAM.png" alt="Screenshot 2023-12-12 at 10.40.37 AM.png" />

## Mockup
<img width="1725" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2xSQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--811ef447ec28d7b34ac9ec882ec01ef9ccc78ee7/Screenshot%202023-12-12%20at%2010.41.59%E2%80%AFAM.png" alt="Screenshot 2023-12-12 at 10.41.59 AM.png" />

# Done Looks Like
- [ ] The maximum height of the tab panel should be the maximum height of the containing column, to match the bottom of the structuredNav component

**Comment by joncameron** [comment]
I've updated the description to include all of the tabbed content since it's the same parent element and they should all fill the entire column height if there is content to fill it.

**Comment by elynema** [comment]
@Dananji This doesn't seem to be working quite right. In this [example](https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p), there is white space within the Details tab at the bottom when there should be content displaying:

<img width="1207" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDIzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e6c79f3f6dbbef83900c03d2ce516191fa65739e/image.png" alt="image.png" />

And in a second [example](https://avalon-dev.dlib.indiana.edu/media_objects/707957642), the Details tab extends down to the bottom of the structured navigation component, even though there isn't content to fill it.

<img width="1207" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeCszQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3f2218ce08ba790ddcde7b6fd0a1e2d438f60768/image.png" alt="image.png" />

The bottom of the tab container should not extend further than the content within, and it's max height should fill the space available with the height of the structured navigation div.

I can replicate these issues in Chrome, Firefox, and Safari on MacOS.
