### ISSUE TITLE
[BUG] Title of playlist items does not always appear after switching sections

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5503]
# Description
QA on section switching for playlist items. This could be related to the other issue for unavailable items not updating in the section label text in a playlist.

# To Reproduce
- Go to https://avalon-dev.dlib.indiana.edu/playlists/5
- Click black and forth between playlist items, and watch the title under the media player to see if it updates when you select a new playlist item
- If title does not update when clicking on a playlist item that is not restricted (no lock icon), that's a new bug and we need to know if it is reproducible.

# Done Looks Like
- [x] Playlist item title changes to the currently active item when switching between items

**Comment by joncameron** [comment]
Charu can follow up with more testing for the playlist page.

**Comment by charumitraravi** [comment]
@elynema @joncameron 
I am able to replicate the issue, for unrestricted playlist items as well. While the title is updated for some items  with a slight delay, for others, it is taking longer/does not update. 
Please refer to this [screen recording].(https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekk2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dd7d235f1d4c5be038d8b3d0595ca2cc58fa583c/Screen%20Recording%202023-12-06%20at%2011.21.49%20AM.mov)

I checked a few other playlists as well, like https://avalon-dev.dlib.indiana.edu/playlists/32, and I was able to replicate the issue in different browsers too, with and without logging in. 
Please let me know if a separate bug is needed for this.

**Comment by elynema** [comment]
@charumitraravi This can serve as the bug. Did you notice any pattern in when it happened? The example you showed looked like it happened fairly early in the clicking - like the second or third playlist item you clicked on, and then it didn't recur.

**Comment by Dananji** [comment]
Need to test this again after #5550 is merged

**Comment by masaball** [comment]
No longer able to replicate. Seems to have been resolved by #5550.
