### ISSUE TITLE
Speed Up Manifest Generation

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5505]
# Description
Since Avalon now expects a full IIIF manifest document to be rendered, the speed at which the application can generate and serve the json manifest is critical to user experience. There hasn't been too much investigation yet but future performance improvements could be found in the iiif-manifest gem used by Avalon.

**Comment by cjcolvar** [comment]
These two PRs remove duplicate calls that were expensive and taking up a lot of time.  With these two changes the 125 section item manifest generation time dropped to 2.5s from 5.4s

https://github.com/samvera/iiif_manifest/pull/105
https://github.com/samvera/iiif_manifest/pull/106

**Comment by elynema** [comment]
I'm seeing a total load time of about 5 seconds for our 125 item media objects, which feels like an improvement.
