### ISSUE TITLE
Ramp Initializes with Time Fragment in URL

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5508]
# Description
Avalon currently takes a time fragment value that sets the player's current active progress to the value specified in the time value. Ramp can take this but Avalon is not yet set up to initialize Ramp to set the start time using the specified time.

# Examples
https://media.dlib.indiana.edu/media_objects/nk322d627?t=16
Loads the item page, loads the first stream, then sets the player position to 16 seconds in
https://media.dlib.indiana.edu/media_objects/nk322d627/section/pn89d812k?t=16
Load the item page, loads the second stream (section pn89d812k) into the player, then sets the player position to 16 seconds in

# Done Looks Like
- [ ] Time fragments as URL parameters are passed to Ramp in Avalon and media playback begins at the specified time

**Comment by cjcolvar** [comment]
Add ramp prop that hooks up to existing variable for handling manifest's start time offset attribute.  This ticket is for the Avalon side and a ticket will be written for the ramp work.
