### ISSUE TITLE
Condense Solr Calls for Item Show Page

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5509]
# Description
Refactoring Solr queries has helped speed up page load time for item show pages. Looking at this again and making sure the smallest number of calls to Solr happens could be an easy win for load times in the context of the 7.7 release.

# Done Looks Like
- [x] Investigation into Solr usage during item show page renders
- [x] Unnecessary calls refactored as needed

**Comment by elynema** [comment]
Multiple calls were being made to SpeedyAF, which are now condensed. 100 section item went from 8 seconds to 2 seconds. This should be all the low-hanging fruit for the manifest / item show page.
