### ISSUE TITLE
[BUG] Playlist items - Opening a playlist item in a new tab shows a routing error

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5514]
**Describe the bug.**
The page link for a playlist item opened in a new tab is broken and shows a routing error. 
Eg: For this [playlist](https://avalon-dev.dlib.indiana.edu/playlists/32) ,this is  the [second item opened in a new tab](https://avalon-dev.dlib.indiana.edu/playlists/32/manifest/canvas/36#t=0.0,) and the page is broken.

**To Reproduce**
1.Open any playlist with items.
2.Select one of the items, right click on it and choose the option "Open link in a new tab"

**Expected behavior**
A new tab should open, and  the marker should be positioned next to the item that was selected.

**Screenshots/Screen Recording**
<img width="1627" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlpGQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ebba26e10dd48f3a1a90f4b1450f3ca3ff9d55c/Screenshot%202023-12-08%20at%2010.54.41%20AM.png" alt="Screenshot 2023-12-08 at 10.54.41 AM.png" />

**Environment (please complete the following information):**
 - Device / platform : All devices
 - OS: All OS
 - Browser : All browsers
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
v7.7

URL that gets generated now in MCO: https://media.dlib.indiana.edu/playlists/5209?position=1

Existing URLs as above should also be supported and would not redirect currently.

Homepage property in the canvas could be the URL used for copying and bookmarking. Section PURLs end up going to the /section route as well. Avoid putting hompages on the ranges in the manifest.

# Done Looks Like
- [ ] Homepage attribute added to manifest to contain the positional URL (1-2 points)
  - [ ] Set up canvas presenter to serialize the value in the manifest
- [ ] Playlist route URLs with position parameter return the playlist view page with the specified playlist item active (one-based numbering) (2-3 points in Ramp)
  - [ ] https://avalon-dev.dlib.indiana.edu/playlists/18?position=2 in the browser goes to view page for playlist 18 and sets the second item in the playlist as active
- [ ] Links for playlist items are of the syntax: https://avalon-dev.dlib.indiana.edu/playlists/18?position=4

**Comment by elynema** [comment]
Could this be related to #5493?

**Comment by joncameron** [comment]
Solution should be the same as #5493, in terms of parsing the URL and feeding the start canvas that value into Ramp.

**Comment by elynema** [comment]
Current URLs generated for a playlist item in a playlist look like https://mco-staging.dlib.indiana.edu/playlists/33?position=2. Can we continue to support that format for backward compatibility? This is a question to explore with Jon C.

Add a homepage attribute with PURL directly to the canvas/fragment to the item in the structured navigation. This would need to fall on the Canvas, rather than the Range. A single Range can have multiple items/canvases in the IIIF spec. 


Clickable URL in structured nav could be a PURL that can be interpreted by Avalon and loaded in a new window. There could also be a data attribute that is utilized by Ramp to actually load content when user clicks on an item in structured navigation.

We see the same issue with the timespans in the structured navigation on the media item page. Historically, we did provide a PURL for these timespans if user saves that URL.

**Comment by elynema** [comment]
Alternative solution is to have Avalon support the Canvas URLs that are already used in structured nav and abandon the PURLs. Example: https://avalon-dev.dlib.indiana.edu/playlists/18/manifest/canvas/33#t=0.0,

**Comment by elynema** [comment]
Alternative solution is to have Avalon support the Canvas URLs that are already used in structured nav and abandon the PURLs. Example: https://avalon-dev.dlib.indiana.edu/playlists/18/manifest/canvas/33#t=0.0,

**Comment by elynema** [comment]
Alternative solution is to have Avalon support the Canvas URLs that are already used in structured nav and abandon the PURLs. Example: https://avalon-dev.dlib.indiana.edu/playlists/18/manifest/canvas/33#t=0.0,

**Comment by elynema** [comment]
Alternative solution is to have Avalon support the Canvas URLs that are already used in structured nav and abandon the PURLs. Example: https://avalon-dev.dlib.indiana.edu/playlists/18/manifest/canvas/33#t=0.0,

**Comment by elynema** [comment]
Alternative solution is to have Avalon support the Canvas URLs that are already used in structured nav and abandon the PURLs. Example: https://avalon-dev.dlib.indiana.edu/playlists/18/manifest/canvas/33#t=0.0,

**Comment by joncameron** [comment]
@joncamer to break this into an Avalon issue and a Ramp issue for the respective bits of work

**Comment by joncameron** [comment]
Broken into #5607 and samvera-labs/ramp#366
