### ISSUE TITLE
Error When Navigating Tabs on Item Page When No Transcripts Present

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5520]
# Description
When an item does not have transcripts, no transcript tab is displayed in the tab list. When navigating through the tabs with the arrow keys, however, there is a bug that that results in displaying a non-existent transcript tab section. 

This bug report originates from QA on https://github.com/samvera-labs/ramp/issues/294, which was a similar but unrelated problem.

# Example
[Screen Recording](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUluQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--de30a04d7a297623d565b875dbb131ae50c39f98/Screen%20Recording%202023-12-01%20at%201.52.46%20PM.mov)

# Done Looks Like
- [ ] Navigating through the list of tabs with the arrow keys does not display a non-existent transcript tab

**Comment by joncameron** [comment]
Z-index in CSS could be a way to resolve this by moving it from tab order.

**Comment by elynema** [comment]
Working fine on Chrome. Having trouble testing on Safari b/c I can't navigate to the tabs with the tab key (tab order, including shift+tab to go backwards skips the Details / Files tabs). When I click directly on a tab, the arrow keys don't navigate through the tabs, but activate player hotkeys. Presumably this is b/c the tabs are not in the tab order in Safari (see #5585)?

**Comment by elynema** [comment]
Tabs seem to be working properly in Safari now.
