### ISSUE TITLE
[BUG] Copy timeline modal does not refresh after selecting Create/Create and Edit

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5528]
**Describe the bug**
On the Timelines page that lists all timelines, if you select Copy, and then either Create or Create and Edit, the new timeline is created, but the modal remains open and the page does not refresh. 

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. Go to the Timelines page 
2. Click Copy for a specific timeline
3. Select Create or Create and Edit
4. Nothing appears to happen

**Expected behavior**
- [ ] After selecting Create, the modal should close and the Timelines page should refresh so user can see the new timeline
- [ ] After selecting Create and Edit, the modal should close the Edit page should open for the newly created timeline

**Environment (please complete the following information):**
 - Device / platform: laptop
 - OS: macOS
 - Browser: Chrome
- [ x] avalon-dev
- [ ] avalon-staging
- [x] mco-staging
- [ ] mco-production
- [x] demo

**Release:**
This problem was reported happening in 7.5 by another Avalon user and I confirmed that it was still happening in 7.6 on the demo site and mco-staging, as well as on avalon-dev.

**Comment by joncameron** [comment]
Similar but may not be exactly like the bug with Copy Playlist.

**Comment by elynema** [comment]
Tested fine in Chrome, Safari, and Chrome on iOS.
