### ISSUE TITLE
[BUG] Transcripts tab does not always appear / disappear when switching sections (intermittent)

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5529]
**Describe the bug**
The appearance and disappearance of the Transcripts tab when switching between sections that do and don't have transcripts seems buggy. Sometimes, the tab remains even when there is no transcript. Sometimes it does not appear when there is a transcript.

**To Reproduce**
Here are 2 example records where this behavior has been observed intermittently:
- https://avalon-dev.dlib.indiana.edu/media_objects/kw52j8067
- https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p

For the first item, I've most often been able to reproduce when clicking between 1st and 4th section, or between the 1st, 3rd, and 4th section. The general behavior I have seen is the transcript tab does not appear when the 4th section is selected. Try reloading the page and clicking around again if you're not able to reproduce the first time around.

Charu reports that the tab display errors can happen both when manually selecting sections on on auto-play.

Second item looks like it needs another issue as the 4th and 5th section are refusing to load when clicked on.

**Expected behavior**
- [ ] The Transcript tab should always disappear when a section loads via manual selection or auto-play that does not have any transcripts
- [ ] The Transcripts tab should always appear when a section loads via manual selection or auto-play that has a transcript
- [ ] We are aware that sometimes a Transcript tab will remain showing briefly with a "no transcripts" message as a new section is loading, but it should always disappear quickly.

**Environment (please complete the following information):**
 - Device / platform: laptop
 - OS: macOS
 - Browser: Chrome
- [ x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
Is this issue associated with a specific release? [e. g. 7.6]

**Additional notes**
Any additional information or notes that may be helpful in diagnosing or fixing the problem.

**Comment by elynema** [comment]
Just had this happen with this record: https://avalon-dev.dlib.indiana.edu/media_objects/000000000

**Comment by joncameron** [comment]
Behavior may need to be reworking to use React states rather than player load state.

**Comment by elynema** [comment]
Tested these 3 items in Chrome, Safari, and Firefox on Mac and can't get the problem to recur, so it seems to be fixed.
