### ISSUE TITLE
Error When Selecting Section Still Being Transcoded

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5531]
# Description
When a section which is still transcoding, selecting it for playback on the item page will briefly show the standard "still processing" message before all Ramp components disappear and a manifest error message appears.

# To Reproduce
- Add a file to an existing item
- While the file is transcoding, select the section in the structuredNav component
- The media player will be blank with the "file still processing" message as expected
- After the message above has appeared for a brief moment, this message appears to the user:
<img width="1142" alt="Screenshot 2023-12-19 at 9 02 38 AM" src="https://github.com/avalonmediasystem/avalon/assets/1406618/8d840d68-bd90-4a15-8dd6-3a7be70a552d">

# Done Looks Like
- [ ] Ramp does not display an error message about the manifest to the user when a section whose file is still transcoding is selected

**Comment by joncameron** [comment]
Ramp issue; error is happening in one of the components and Ramp is crashing. 
@joncameron switch to Ramp repository

**Comment by elynema** [comment]
Closing this; recreated as https://github.com/samvera-labs/ramp/issues/334
