### ISSUE TITLE
Check media object and playlist page with SiteImprove browser plug-in

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5532]
# Description

We don't want to go backwards in terms of accessibility issues in SiteImprove when we deploy 7.7 at IU. Since we made many changes to the media object and playlist page, we should use the SiteImprove browser plugin to test them and create issues for any problems that are noted at level of conformance A and AA.

# Done Looks Like
- [x] Check media object page / player 
- [x] Check playlist page / player
- [x] New issues created and with Epic = SiteImprove Accessibility Issues

**Comment by cjcolvar** [comment]
Created three issues for the media object page:
- #5564
- #5565
- #5566
 
The three issues above are also present on the playlist page along with one other:
- #5567

I created these issues in the avalon repo but I think that are all contained within ramp.
