### ISSUE TITLE
Speed up rendering of media object page elements: transcript, add to playlist

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5533]
# Description

There are a few noticeable lags in page rendering on the media object page. Investigate if it is possible to speed any of these up.

- [ ] On page load, it takes some time for the Add to playlist button to become actionable.
- [ ] When switching between sections, there is often a noticeable visual delay for the Transcripts tab to appear / disappear. For example, if the new section has no transcript, the tab will remain in place long enough for the user to see the "no transcript" message before it disappears.

**Comment by joncameron** [comment]
Already covered by work done on Ramp and Avalon since this issue was created.
