### ISSUE TITLE
[BUG] List of users does not show on Manage Users page in Safari

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5553]
**Describe the bug**
On the Manage Users page, no list of users displays in Safari. The page displays normally in Chrome. The add or invite user box still shows up, so the page is not completely failing to load, but there is nothing below it.

<img width="1285" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMkd1QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0f3019bdbfaef26a776867c652e954e153542070/safari-Manage%20users.png" alt="safari-Manage users.png" />

Confirmed that this is happening in Safari only (not Chrome or Firefox) and it is also happening on mco-staging, so it's not a 7.7 regression issue.

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. Log in as an admin (archivist 1)
2. Go to Manage -> Manage Users

**Expected behavior**
Below the panel to Add or invite user via email, there should be a list of existing users with a search box just above it.

**Environment (please complete the following information):**
 - Device / platform: laptop
 - OS: MacOS
 - Browser: Safari only
- [x] avalon-dev
- [ ] avalon-staging
- [x] mco-staging
- [ ] mco-production
- [ ] demo

**Comment by elynema** [comment]
Safari seems to be having an issue with a regular expression:

<img width="1238" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjJ2QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6a176b90026671bb7204e22db0bf149a9f82e494/image.png" alt="image.png" />

**Comment by elynema** [comment]
Will likely need to re-write the regex for the column sort functionality, as Safari may not support lookback regex. Safari is available via BrowserStack for testing.

**Comment by joncameron** [comment]
Putting this in the "known issues" list and punting it to next release could be reasonable if time needs to be allocated to more high priority issues.

**Comment by elynema** [comment]
This seems to be working now; perhaps there was a change in Safari!
