### ISSUE TITLE
Provide setting to store waveform job temp files in specified directory instead of ruby default /tmp

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5557]
Avalon allocates 10 sidekiq worker threads for all background jobs while at IU we allocate an additional 30 worker threads exclusively to the waveform job queue.  With #5546 certain scenarios will create temp wav files on disk while processing waveform jobs.  These files can be 1+ GB for longer section files and by default ruby puts temp files in /tmp on linux systems.  I'm concerned that under full load the wav temp files might fill available space in /tmp.  Providing a configuration setting for where temp files get created could allow an implementor to choose a different location than /tmp which might have more disk space.

# Done Looks Like
- [ ] Configuration setting added for temp file location

**Comment by joncameron** [comment]
No longer relevant.
