### ISSUE TITLE
Link back to source item from Source Item Details on playlist page

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5562]
# Description

Currently, MCO provides a link back to the source item and section under Source Item Details on the playlist page. In the new playlist page design, this is not included in the Source Item Details, and there is no way to link directly back to the source item.

Avalon 7.6 includes both the masterfile and media object, for example:
ABY9017A from Candide / Leonard Bernstein ; [based on the book by Voltaire ; lyrics by Richard Wilbur ; with additional lyrics by John La Touche ... et al. ; orchestrations by Leonard Bernstein and Hershy Kay]. 

For 7.7, having just a link to the object page is sufficient.

# Question
In the current playlist manifests, the `partOf` URL value contains the /manifest route. Does this need to be retained, or can it hold just the direct URL to the media object view route? Or would the `homepage` attribute be better to use?

# Done Looks Like
- [ ] Item title in the Source Item Details panel is a hyperlink to the object view page

**Comment by elynema** [comment]
This came up as an important need for David Cartledge, as he wants way more metadata than what we're showing in source item details.

**Comment by elynema** [comment]
@joncameron Should this be linking to the section rather than the object view page?

**Comment by joncameron** [comment]
Item titles are hyperlinked as expected. I'll create a new issue for the possible enhancement of using the section link instead of the media object link.
