### ISSUE TITLE
Structured nav uses invalid aria role 'structure'

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5564]
A 1.3.1 Info and Relationships
Some roles are invalid

Only some of the roles assigned to this element are defined in WAI-ARIA.
Why is this an issue
Occurrences of this issue
1
role='structure'
Use roles defined in WAI-ARIA.

Happening on
```
<div data-testid="structured-nav" class="ramp--structured-nav" role="structure" aria-label="Structural content">
```

Found on https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p using SiteImprove browser extension

# Done Looks Like
- [ ] Remove role attribute from this div and re-test in SiteImprove

**Comment by joncameron** [comment]
Could switch the role? Links in the structure are what the screen reader will see; this is a div with this role set, and this attribute could be removed.

**Comment by cjcolvar** [comment]
Maybe this should be `role="list"`?  Related to #5566
