### ISSUE TITLE
Element IDs are not unique for player SVG controls

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5565]
A 4.1.1 Parsing
Element IDs are not unique

Two or more elements on this page have the same id value. These should be unique.

Duplicates include:
- #SVGRepo_bgCarrier
- #SVGRepo_tracerCarrier
- #SVGRepo_iconCarrier

Found on https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p using SiteImprove browser extension

**Comment by joncameron** [comment]
Could be inherent in Video.js or due to our use of custom components.

**Comment by elynema** [comment]
Looks good in SiteImprove browser plugin on avalon-dev. Still see the error on avalon-staging, so I think this is a fix.
