### ISSUE TITLE
Form field missing a label on autoplay toggle button

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5567]
A 4.1.2 Name, Role, Value
Form field missing a label

Every form element should have a descriptive text label.

Checkbox field<input name="auto-advance-toggle">
Add a label, making sure it's properly associated with the form field.

Found on https://avalon-dev.dlib.indiana.edu/playlists/51 using SiteImprove browser extension.

**Comment by joncameron** [comment]
Should the text be the same as label text or something like "enable autoplay/disable autoplay"?
