### ISSUE TITLE
[BUG] Unable to create new timelines

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5568]
**Describe the bug**
Attempting to create a new timeline using the custom time option results in an error page. I also encountered the error screen at least once when attempting to create a timeline from a single-section object without structure.

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. Go to https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p
2. Click on "Create Timeline" button
3. Select custom
4. Click "Create Timeline"
5. Receive error page

**Expected behavior**
A new timeline gets created containing the custom range

**Screenshots/Screen Recording**
<img width="864" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVMzQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--76c1bee86e9447746b4b903ae7cc00c7287bef38/Screenshot_20240110_170026.png" alt="Screenshot_20240110_170026.png" />

**Environment (please complete the following information):**
 - Laptop
 - OS: Ubuntu 22.04
 - Firefox
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Additional notes**
I have not tried every create timeline option, so this issue may affect other create timeline situations than just the two mentioned.

**Comment by joncameron** [comment]
I tested on latest Safari and Chrome in browserstack and was unable to reproduce; Timelines were created successfully in all situations.
