### ISSUE TITLE
IIIF validator errors on playlists with inaccessible items

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5571]
# Description

For inaccessible items, we are using a placeholderCanvas. I created a playlist with one accessible and one inaccessible item. Then I put it through a IIIF Presentation 3.0 validator. Numerous errors result.

The playlist manifest renders as expected in Ramp and Avalon, so this is a question of compliance with IIIF spec.

playlist manifest: https://avalon-dev.dlib.indiana.edu/playlists/55/manifest.json
playlist in avalon: https://avalon-dev.dlib.indiana.edu/playlists/55

IIIF validator I used: https://presentation-validator.iiif.io/

# Done Looks Like
- [ ] Investigation into resolving validation errors for manifests with inaccessible items

**Comment by joncameron** [comment]
Probably because of empty elements in our manifest.

**Comment by Dananji** [comment]
The request playlist manifest in `avalon-dev` timed out in the validator.

I tried a [public playlist](https://demo.avalonmediasystem.org/playlists/113) [manifest](https://demo.avalonmediasystem.org/playlists/113/manifest.json) from avalon demo site: 

### Validation Results:
_URL Tested: https://demo.avalonmediasystem.org/playlists/113/manifest_

#### Error 1 of 5.
Message: {'id': None, 'type': 'Text', 'format': 'text/plain', 'label': {'none': ['You do not have permission to playback this item.']}} is not valid under any of the given schemas

    Detail:
    Path: /items[1]/placeholderCanvas/items[0]/items[0]/body/[{'id': None, 'type': 'Text', 'format': 'text/plain', 'label': {'none': ['You do not have permission to playback this item.']}} is not valid under any of the given schemas]
    Description:

    {"id":null,"type":"Text","format":"text/plain","label":"{ ... }"}

**Fix suggestion: _`id: null` in the `body` of the `placeholderCanvas` for the inaccessible item_**

#### Error 2 of 5. 
Message: {'type': 'Canvas', 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder', 'items': [{'type': 'AnnotationPage', 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder/annotation_page/a4828b84-1493-48fe-a8cf-f7ab7651bfa5', 'items': [{'type': 'Annotation', 'motivation': 'painting', 'body': {'id': None, 'type': 'Text', 'format': 'text/plain', 'label': {'none': ['You do not have permission to playback this item.']}}, 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder/annotation_page/a4828b84-1493-48fe-a8cf-f7ab7651bfa5/annotation/44013b83-aac6-4e8c-94cd-4319a1fd83ea', 'target': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder'}]}]} is not valid under any of the given schemas

    Detail:
    Path: /items[1]/placeholderCanvas/[{'type': 'Canvas', 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder', 'items': [{'type': 'AnnotationPage', 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder/annotation_page/a4828b84-1493-48fe-a8cf-f7ab7651bfa5', 'items': [{'type': 'Annotation', 'motivation': 'painting', 'body': {'id': None, 'type': 'Text', 'format': 'text/plain', 'label': {'none': ['You do not have permission to playback this item.']}}, 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder/annotation_page/a4828b84-1493-48fe-a8cf-f7ab7651bfa5/annotation/44013b83-aac6-4e8c-94cd-4319a1fd83ea', 'target': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder'}]}]} is not valid under any of the given schemas]
    Description:

    {"type":"Canvas","id":"https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder","items":"[ ... ]"}

**Fix suggestion: _missing `height` and `width` properties in the `placeholderCanvas` for inaccessible item_**

Error 3 of 5. 
Message: 'items' is a required property

    Detail: AnnotationPage id, type and items required
    Path: /items[1]/items[0]/['items' is a required property]
    Description:

    {"type":"AnnotationPage","id":"https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/annotation_page/9b366b75-a973-44af-aade-2a0db339be58"}

**Fix suggestion: _no `items` list in the in the `AnnotationPage` for the empty `Canvas`_**

Notes: The error in the validator says an AnnotationPage `must` have `items` property, while the IIIF spec 3.0 indicated it `may` have an `items` list. Maybe we need at least an empty `items` list?
From the IIIF 3.0 spec for `AnnotationPage`:
> An Annotation Page must have an HTTP(S) URI given in id, and may have any of the other properties defined in this specification or the Web Annotation specification. The Annotations are listed in the items property of the Annotation Page.

#### Error 4 of 5.
Message: {'type': 'Canvas', 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090', 'items': [{'type': 'AnnotationPage', 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/annotation_page/9b366b75-a973-44af-aade-2a0db339be58'}], 'label': {'none': ['Restricted item']}, 'partOf': [{'type': 'manifest', 'id': 'https://demo.avalonmediasystem.org/media_objects/sb3978503/manifest'}], 'metadata': [{'label': {'en': ['Title']}, 'value': {'en': ["Sample Clock"]}}, {'label': {'en': ['Date']}, 'value': {'en': ['2020-02-22']}}], 'homepage': [{'type': 'Text', 'id': 'https://demo.avalonmediasystem.org/playlists/113?position=2', 'label': {'none': ['Playlist Item 2']}}], 'placeholderCanvas': {'type': 'Canvas', 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder', 'items': [{'type': 'AnnotationPage', 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder/annotation_page/a4828b84-1493-48fe-a8cf-f7ab7651bfa5', 'items': [{'type': 'Annotation', 'motivation': 'painting', 'body': {'id': None, 'type': 'Text', 'format': 'text/plain', 'label': {'none': ['You do not have permission to playback this item.']}}, 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder/annotation_page/a4828b84-1493-48fe-a8cf-f7ab7651bfa5/annotation/44013b83-aac6-4e8c-94cd-4319a1fd83ea', 'target': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder'}]}]}} is not valid under any of the given schemas

    Detail:
    Path: /items[1]/[{'type': 'Canvas', 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090', 'items': [{'type': 'AnnotationPage', 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/annotation_page/9b366b75-a973-44af-aade-2a0db339be58'}], 'label': {'none': ['Restricted item']}, 'partOf': [{'type': 'manifest', 'id': 'https://demo.avalonmediasystem.org/media_objects/sb3978503/manifest'}], 'metadata': [{'label': {'en': ['Title']}, 'value': {'en': ["Sample Clock"]}}, {'label': {'en': ['Date']}, 'value': {'en': ['2020-02-22']}}], 'homepage': [{'type': 'Text', 'id': 'https://demo.avalonmediasystem.org/playlists/113?position=2', 'label': {'none': ['Playlist Item 2']}}], 'placeholderCanvas': {'type': 'Canvas', 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder', 'items': [{'type': 'AnnotationPage', 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder/annotation_page/a4828b84-1493-48fe-a8cf-f7ab7651bfa5', 'items': [{'type': 'Annotation', 'motivation': 'painting', 'body': {'id': None, 'type': 'Text', 'format': 'text/plain', 'label': {'none': ['You do not have permission to playback this item.']}}, 'id': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder/annotation_page/a4828b84-1493-48fe-a8cf-f7ab7651bfa5/annotation/44013b83-aac6-4e8c-94cd-4319a1fd83ea', 'target': 'https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090/placeholder'}]}]}} is not valid under any of the given schemas]
    Description:

    {"type":"Canvas","id":"https://demo.avalonmediasystem.org/playlists/113/manifest/canvas/1090","items":"[ ... ]","label":"{ ... }","partOf":"[ ... ]","metadata":"[ ... ]","homepage":"[ ... ]","placeholderCanvas":"{ ... }"}

**Fix suggestion: _missing `height` and `width` properties in the `Canvas` for the inaccessible item_**

#### Error 5 of 5. 
Message: None is not of type 'object'

    Detail: Language string, must have a language and value must be an array.
    Path: /structures[0]/label/[None is not of type 'object']
    Description:

    null

**Fix suggestion: _root node of `structures` property has `label: null` which should be a language map_**

Notes: https://iiif.io/api/presentation/3.0/#language-of-property-values

**Comment by Dananji** [comment]
I tested a [media object](https://demo.avalonmediasystem.org/media_objects/vd66vz95s) [manifest](https://demo.avalonmediasystem.org/media_objects/vd66vz95s/manifest.json) from demo, and got the following error which is same as the 5th error above for playlist manifest.

### Validation Results:
_URL Tested: https://demo.avalonmediasystem.org/media_objects/vd66vz95s/manifest_

#### Error 1 of 1. 

Message: None is not of type 'object'

    Detail: Language string, must have a language and value must be an array.
    Path: /structures[0]/label/[None is not of type 'object']
    Description:

    null
