### ISSUE TITLE
Switch AWS email delivery method to :ses

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5576]
Looks like the delivery method name in `aws-sdk-rails` changed from `:aws_sdk` to `:ses` in version 3.0.5 and we missed it.  I'm not sure if the old name is still working or if email isn't sending with this configuration.  See https://github.com/aws/aws-sdk-rails/blob/9218da10a18399dfb968e09d7a48496a5416a229/CHANGELOG.md?plain=1#L108-L109

**Comment by cjcolvar** [comment]
FWIW it looks like Avalon upgraded from `aws-sdk-rails` 1.01 to 3.1.0 in Avalon 7.2 which was released in 2020.

**Comment by joncameron** [comment]
I tested a user invite via persona and the email came through without issue. Closing this as no longer needed.
