### ISSUE TITLE
Investigate complying with stricter email spam filtering

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5577]
Google and Yahoo will be enforcing stricter email spam filtering starting in 2/2024.  We should make sure that emails Avalon sends, in particular from AWS installs, to ensure it follows best practices to ensure emails get delivered.

See:
https://blog.google/products/gmail/gmail-security-authentication-spam-protection/
https://blog.postmaster.yahooinc.com/post/730172167494483968/more-secure-less-spam
https://aws.amazon.com/blogs/messaging-and-targeting/an-overview-of-bulk-sender-changes-at-yahoo-gmail/

**Comment by joncameron** [comment]
We'll check this after deploying to the demo site in AWS.

**Comment by cjcolvar** [comment]
@joncameron If you tested and emails are coming through to a gmail address then I think we can close this.
