### ISSUE TITLE
Include playlist item descriptions in IIIF manifest for playlists

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5581]
# Description

When adding a track or custom timespan to a playlist, the add to playlist form provides the user the option to create a description for the playlist item. This description is appearing in the IIIF playlist manifest (under the metadata element, under "Description" (see https://avalon-dev.dlib.indiana.edu/playlists/33/manifest.json) but is not being displayed by Ramp.

Here is what a playlist item description looks like in MCO currently:

<img width="1212" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNXpRQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9607ece0acda9032543f1959536a426b0165d501/image.png" alt="image.png" />

It displays immediately below the playlist item title below the player.

The Avalon component is already rendering the playlist item title on this page but when the playlist item is loaded, the playlist item title is not read from the manifest but from the title value stored in the DOM. So the playlist is not being read at that point and this might be trickier. But the description will need to get passed into the structure or DOM via data-attributes if the description value is in the manifest.

# Done Looks Like
- [x] Playlist item description is present in the manifest 
  - [x] (value written into the `summary` element of the playlist item's range (or canvas—either would be OK and canvas would be simpler with the iiif-manifest gem) in the structure element of the manifest) *or*
  - [ ] "Playlist Item Description" keypair is written into the manifest under the metadata for a Canvas and is treated in a special way
- [x] Playlist item descriptions written into the DOM as data-attribute values 
- [x] Playlist description value is rendered below the playlist item title on the playlist view page

# Implementation
Which IIIF field to use?
- summary (https://iiif.io/api/presentation/3.0/#summary)
- within the existing `metadata` listing (drawing from the record's descriptive metadata)
  - "Description" or some other specifically used field in the metadata could be keyed on to provide this, i.e. "Playlist Item Description"
- within an annotation

**Comment by elynema** [comment]
Presumably we will also need an issue to display this value in Ramp? Is the playlist item title display coming from Ramp or from Avalon?

**Comment by joncameron** [comment]
Title on the playlist view page is coming from Avalon, so this should all be within Avalon. This may not need to touch Ramp if we're rendering this playlist item description underneath the playlist item title.

**Comment by cjcolvar** [comment]
PRs created:
https://github.com/samvera/iiif_manifest/pull/107
https://github.com/samvera-labs/ramp/pull/350
#5587

**Comment by elynema** [comment]
It looks like the selected solution was to add the playlist item description as a `summary` element under the `Canvas`.

**Comment by joncameron** [comment]
Looks good to me! Tested with https://avalon-dev.dlib.indiana.edu/playlists/33.

**Comment by elynema** [comment]
@joncameron I tested this in Chrome, and it seemed to be working, but I ran into a complicated separate issue that I wrote up that got me distracted. I don't think I have tested in Safari.

**Comment by joncameron** [comment]
I tested in Safari and playlist item description appears as expected there; closing.
