### ISSUE TITLE
[BUG] Up/down hotkeys for media player not working in Chrome

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5585]
# Description

The up/down arrow keys are supposed to raise / lower volume in the media player as hotkeys, particularly when any media player control is selected. This up/down arrow keys are not affecting volume either when a media player control is selected or at any time on the page.

See https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957953669/Accessibility

Are there other hotkeys besides spacebar and arrow keys?
"M" for mute was previously used in Avalon, but undocumented on the wiki (although present in previous test cases).

Tested in Chrome. Up/down keys may be working in Firefox. This may be another issue dependent on Browser/OS settings.

# Done Looks Like
- [x] Tested across multiple browsers
- [ ] Up arrow should raise volume and down arrow lower volume in player as long as no input is selected on the page
- [x] Update documentation on when hotkeys should be active

**Comment by joncameron** [comment]
Test with a selection of browsers to see what the conditions are for this to not be working or to be working.,

**Comment by elynema** [comment]
I've confirmed that up and down arrow keys are not working as hotkeys for me in Chrome or Firefox  (on MacOS Monterey). I can't really test Safari right now b/c it has so many other issues with playback.

**Comment by joncameron** [comment]
Needs retesting now—working in some contexts and not others. Coming back again to browser/OS flags that might be affecting input.

**Comment by elynema** [comment]
I've now confirmed that it is working in Safari and Firefox for me as well as Jon C. I hadn't realized it was already at full volume when I tried to make it louder.

However, Chrome is still not working on my MacOS laptop - when I click up/down arrows the page is scrolling up and down, which seems to indicate the hotkeys aren't getting caught.

**Comment by elynema** [comment]
Issue is with all hotkeys when player is actively selected (through tab or mouse click). The m hotkey has been implemented. Jon C. is re-writing that up as a new bug issue, so closing this.
