### ISSUE TITLE
Change Default for Segment/Substructure Option in Add to Playlist Form

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5588]
# Description
In user testing a majority of users desired the default behavior for "add to playlist" to be adding each structure segment as a separate item. This can be made the default.

# Done Looks Like
- [x] "Create playlist items for each track/subsection" is checked by default when "Current Section" or "All Sections" is selected in the Add to Playlist form

**Comment by elynema** [comment]
This looks good to me in Safari and Chrome and Firefox. I have not tested on mobile devices at this point.
