### ISSUE TITLE
Playlist Page - Structured Nav Extends to Parent Container Height

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5589]
# Description
On the playlist page the structured-nav Ramp element is given a max height value, which crops it unnecessarily within the parent element on the item page (see screenshot). This should change in the same way it changed on the item page (#5498).

# Done Looks Like
- [ ] Height of structured-nav div (.ramp--structured-nav) extends to the full height of the parent element

# Screenshot
<img width="571" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL1QrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cfbad8bce21f5cfcae70350b219788158dc78217/Screenshot%202024-01-23%20at%203.58.50%E2%80%AFPM.png" alt="Screenshot 2024-01-23 at 3.58.50 PM.png" />

**Comment by elynema** [comment]
@Dananji In Chrome and Firefox, I see that the playlist item container is the height of the page and scrollable:

<img width="1288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGNnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e4572ede2ee5be87707beb7b65598d53214f38a1/image.png" alt="image.png" />


In Safari, no scroll is getting engaged within the playlist item container, so it just gets really long:

<img width="1279" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNGdnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7300f46a799b733af293fee1b8a45e9044727010/image.png" alt="image.png" />

In Chrome and Firefox where it is scrolling, I'm not seeing the "scroll to see more" styling; maybe that has not been merged yet.

**Comment by elynema** [comment]
Firefox on Android is not expanding the size of the structured navigation on the playlist page. This is low priority; perhaps I should create a new bug.

<img width="823" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL0FqQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--abad94610e49bbc91a122f370ef3e6ce804fcbfa/bs_realdroid_Mobile_Google%20Pixel%207-13.0-1080x2400%20%281%29.jpg" alt="bs_realdroid_Mobile_Google Pixel 7-13.0-1080x2400 (1).jpg" />

**Comment by elynema** [comment]
With hard refresh, the playlist item section is scrolling in Safari.

**Comment by elynema** [comment]
Can we add a little bit of padding between the border of the structured nav and the text of the playlist items?

**Comment by elynema** [comment]
@Dananji I'm seeing the padding and "scroll to see more" message now across Safari, Chrome, and Firefox. Is there an easy way to make the "scroll to see more" message wider so it doesn't wrap to so many lines vertically?

<img width="1288" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL2drQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--dc5d59f08584ae68466568b43956dfd291d58096/image.png" alt="image.png" />

**Comment by Dananji** [comment]
It should be. I'll check it out.

**Comment by Dananji** [comment]
Do we want this change in item view page? Currently it looks like this;
<img width="771" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNUVsQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9007f065653f440419273e6fbb01e8bf439c21fa/Screenshot%202024-02-02%20at%201.24.33%E2%80%AFPM.png" alt="Screenshot 2024-02-02 at 1.24.33 PM.png" />

**Comment by joncameron** [comment]
@Dananji Yeah, it would be great to have the text on a single line for both.

**Comment by elynema** [comment]
@Dananji Yes, it should be no more than 1 line in the structured nav on item view page. I know the playlist item list is narrower, so may be hard to get it to one line there as well, but 1 line there (or 2 if needed) would be best.

**Comment by Dananji** [comment]
Since we need this in both places I did the change in Ramp instead of overriding the CSS in Avalon.

**Comment by joncameron** [comment]
I tested across desktop and mobile and confirmed that the "Scroll to see more" box is now a single line. Looks good!
