### ISSUE TITLE
Visible label and aria label do not match for quality selector button

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5590]
# Description

Visible label and accessible name do not match
The accessible name of any interactive element should contain its visible text label.

"auto" vs. "stream quality"

It is complaining about the quality selector icon in mediaelement.js media player. I believe it is this specific element where the aria-label and button text do not match that is a problem (I'm not sure why this button has text since it does not display?)

`<button type="button" aria-controls="mep_0" title="Stream Quality" aria-label="Stream Quality" tabindex="0">auto</button>`

<img width="1139" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG54QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97d482bcbd58c0ad2737776b9afddfb33c9cf5ee/image.png" alt="image.png" />

**Comment by joncameron** [comment]
The text is being updated with the current quality level, and so js on the page will need to be looked at to make sure this text can be removed and nothing is trying to still update the body of that element.

**Comment by cjcolvar** [comment]
Probably need to make adjustments in me.js quality plugin.
https://github.iu.edu/AvalonIU/Avalon/blob/mco-production/vendor/assets/javascripts/mediaelement/plugins/quality-avalon.js

**Comment by elynema** [comment]
Closing this as Avalon is no longer using mediaelement.js.
