### ISSUE TITLE
Text is clipped when resized - quality selector

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5591]
# Description

Identified by SiteImprove browser plugin on this page: https://mco-staging.dlib.indiana.edu/media_objects/xd07h8220

Text is clipped when resized
Visitors should be able to scale text to 200% without losing any information.

Problems often arise when overflow: hidden is used to prevent text from rendering outside of a specified area. This clips the content at the edge of its container and makes the overflow invisible.

It may be complaining about the default text 'auto' that is assigned to the quality selector. If that is removed (if not needed), this might resolve? I'm not sure if it is also complaining about the stream quality options, but if so, I would think it would complain about each, rather than just the 'auto' text.

`<button type="button" aria-controls="mep_0" title="Stream Quality" aria-label="Stream Quality" tabindex="0">auto</button>`

<img width="1139" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWp4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--374f294c42e77bb1d2341e7aaabfe77a94a87cfa/image.png" alt="image.png" />

<img width="512" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOW54QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6445451ac57a79bffd45d8f275dec2d33ef763fa/image.png" alt="image.png" />

**Comment by joncameron** [comment]
May be solved by #5590, since these are coming from the same source.

**Comment by elynema** [comment]
Closing this as Avalon is no longer using mediaelement.js.
