### ISSUE TITLE
[BUG] Files tab is jumping back and forth between tab heights

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5592]
# Description

When the Files tab is opened, the tab height is jumping back and forth visibly between 2 different tab heights without any interaction from the user. This is happening across Chrome, Safari, and Firefox. 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzd4QWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8fe472221394fa5e9f573a2db37ff001ac5d500/Screen%20Recording%202024-01-23%20at%205.28.59%20PM.mov)

**Comment by joncameron** [comment]
Needs to be retested after an existing PR is merged.

**Comment by joncameron** [comment]
Needs to be retested after an existing PR is merged.

**Comment by Dananji** [comment]
Moving this to QA since this seems to be fixed now in avalon-dev.

**Comment by elynema** [comment]
tested across Chrome, Safari, and Firefox and looks fine now.
