### ISSUE TITLE
[BUG] Skip transcoding conversion jobs fail

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5594]
# Description

When attempting to upload a file for a new section and checking the "skip transcoding" box, the conversion job fails.

Example: https://avalon-dev.dlib.indiana.edu/encode_records/758
```
Status: Failed

Adapter: ActiveEncode::EngineAdapters::PassThroughAdapter

Adapter Job ID: ea361b7a-1dd2-4078-a08f-136b0c85a426

Title:

Error Message: /tmp/amp-demo-amia-2023.mp420240125-8-882k4z does not exist or is not accessible

Job Started: 01/25/24 04:25:17 PM

```

# Done Looks Like
- [ ] Files are processed successfully when the "Skip Transcoding" option is selected during web and batch upload

**Comment by elynema** [comment]
Skip transcoding is working properly on mco-staging but failing with the same error on avalon-staging, so it is either something due to the container environment or the 7.7 release.

**Comment by elynema** [comment]
Chris looked into this a bit, and it is related to the minio configuration, but the fix is probably going to be a bit complex and is probably a longer-standing issue. Jon C. confirmed this is happening on the avalon demo site as well, which is running 7.6. It is probably ok to list this as a known issue and then fix it in the next release (or put out a patch if someone needs a fix sooner).

**Comment by elynema** [comment]
Added this to known issues page, but not sure I got the wording exactly right. We would like to fix this in 7.8/8.0 release.

**Comment by cjcolvar** [comment]
I ended up working on this more and came up with a solution that involves changes to `active_encode` and avalon.  Do we want to try to roll that into this release or should I write it up and we can bring it in first thing in 7.8?

**Comment by elynema** [comment]
@cjcolvar @joncameron  I tested batch ingest with skip transcoding using our [test batch ingest fixture](https://drive.google.com/file/d/1b7ApYAWrUSk18UrDctEPd6FIFYVV_0Fu/view?usp=sharing) on avalon-dev. The manifest includes a file that is ingested with skip transcoding = 'yes' but has 3 different quality derivative files in the asset folder. While the other 2 worked (1 with skip transcoding on a single file and 1 without skip transcoding), this one failed with this error:
`
undefined method `close' for #<Addressable::URI:0x216038 URI:s3://masterfiles/dropbox/7_7_regression_test/assets/OrganClip.low.mp4>`

The file is definitely sitting there in minio; could this be an issue with this fix?

Uploading through the web interface in Avalon is working fine with and without skip transcoding.

**Comment by cjcolvar** [comment]
@elynema That's a known issue (https://github.com/avalonmediasystem/avalon/issues/4970) and the error message looks pretty much the same so I'm fairly certain that it is unrelated to this fix.

**Comment by joncameron** [comment]
The batch failure for skip transcoding should be fixed in the near future, but for the purposes of this ticket/release I think this is resolved.
