### ISSUE TITLE
Embeds Don't Fit to Container

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5598]
# Description
Embeds no longer fit with the width and height of the container; they now exhibit scroll bars, which dampers the user experience. The styling should be the same as Avalon 7.6, where the media elements and toolbar scaled to letter/pillarbox as needed so that all elements were within the body of the parent without inducing scrollbars.

# Examples
Example of the same video embed in an iframe of the same height and width:
## Embed from avalon-dev
<img width="514" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBODcrQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--684fdc1317db87887ed420c263dce9b2c1472c97/Jan-25-2024%2015-54-20.gif" alt="Jan-25-2024 15-54-20.gif" />

## Embed from MCO-Staging
<img width="514" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOC8rQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--9988afcf050721915c9ee0c079428fa231d5e20d/Jan-25-2024%2015-54-49.gif" alt="Jan-25-2024 15-54-49.gif" />

**Comment by joncameron** [comment]
Could be an issue with Solr field changes where a value has changed; right height for audio/video?

**Comment by elynema** [comment]
@joncameron This looks ok to me, but you should try it again too.

**Comment by joncameron** [comment]
Looks good! Tested and regression tested across browsers.
