### ISSUE TITLE
Playlist Routes Take Positional URL Parameter

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5607]
# Description
Avalon should use and resolve playlist URLs containing a position identifier, and set the item at the specified position as active on page load. This returns to the existing way of doing it as 7.6

# Done Looks Like
- [x] Homepage attribute added to manifest to contain the positional URL (1-2 points)
- [x] Set up canvas presenter to serialize the value in the manifest
- [x] Check query parameter and write that to the props passed into Ramp
- [x] https://avalon-dev.dlib.indiana.edu/playlists/18?position=2 in the browser goes to view page for playlist 18 and sets the second item in the playlist as active
- [x] Links for playlist items are of the syntax: https://avalon-dev.dlib.indiana.edu/playlists/18?position=4

**Comment by joncameron** [comment]
I tested this and the positional URLs worked great. The links for playlist items are still shaped like `https://avalon-dev.dlib.indiana.edu/playlists/18/manifest/canvas/23#t=0.0,` and don't resolve currently.

**Comment by masaball** [comment]
The changes for the StructuredNav to provide the correct links are on the Ramp side and I don't think a new build has been brought into Avalon in a couple weeks? So that is probably the issue there. Glad to hear the positional URLs were working for you!

**Comment by Dananji** [comment]
Related Ramp changes were brought into Avalon in #5737
