### ISSUE TITLE
[BUG] Cannot scroll down to Save button in update access control modal for Selected Items on iPhone portrait mode

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5616]
# Description

There is a very specific bug in both Chrome and Safari on iPhone (not iPad) when trying to use the "update access control" modal under Selected Items. In this instance, the user cannot scroll down far enough to click on the Save button. As soon as user lifts their finger from scrolling, the Save button jumps down off-screen again.

This only seems to happen in portrait mode. It is not a problem on Android or iPad.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNaQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1cc3765e576f51016458a50cac0531646fa7a220/Screen%20Recording%202024-01-31%20at%205.40.11%20PM.mov)

**Comment by joncameron** [comment]
Should be able to be changed in CSS but could be tricky.

**Comment by joncameron** [comment]
Save button for the modal is now always accessible. This change did pop the text fields and drop-downs out past the end of the modal, but that's very minor and I'm OK with that for now:
![Screenshot 2024-08-26 at 12 09 55 PM](https://github.com/user-attachments/assets/80eb9a56-05a3-4e32-8343-547749c9f33d)
