### ISSUE TITLE
[BUG] Volume controls overlap quality selector after volume adjustment for audio items

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5625]
**Describe the bug**
Progress bar changes sizes after manually adjusting volume on audio items.

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. Go to https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p
2. Select item 5 "02 Tr02_La citta eterna.mp3" from the structured Nav
3. Adjust the volume using the volume slider
4. See the progress bar extend to the right, forcing the slider and the quality selector to overlap.

**Expected behavior**
Volume button and slider do not shift when volume is changed.

**Screenshots/Screen Recording**

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBekVtQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--64b5f0fa839e2c46293de948e4e24a7039f29c2b/screenRecording-2-2-2024-15-14.mp4)

**Environment (please complete the following information):**
 - Device / platform: Laptop
 - OS: Ubuntu 22.04
 - Browser: Seen in Chrome 121.0.6167.139 (Official Build) (64-bit) and Firefox 122.0
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
7.7

**Comment by masaball** [comment]
After opening this ticket I realized it was probably actually a Ramp issue and so tested it on the Ramp demo site. The issue is present there. @joncameron feel free to close this and move the ticket over to Ramp repo.

**Comment by joncameron** [comment]
Issue in Ramp repository: https://github.com/samvera-labs/ramp/issues/377
@masaball
