### ISSUE TITLE
[BUG] Share by link URL for playlist doesn't provide access to logged in users

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5631]
# Description

Share by link should allow any logged in Avalon user to view a playlist. When using this link and logged in as a different user, I get an error message rather than the playlist: `"Failed to fetch manifest. Please try again."`

<img width="1210" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUF1QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8443cfb94cd5bb395b03d6115c87475693b057b2/image.png" alt="image.png" />

Example playlist: https://avalon-dev.dlib.indiana.edu/playlists/60
Share by link URL: https://avalon-dev.dlib.indiana.edu/playlists/60?token=uxss8nJxK4SbJhJWRhZDhQ

**Comment by joncameron** [comment]
Tested with inaccessible items in a share-by-link playlist and everything worked as expected besides known existing bug samvera-labs/ramp#394.
