### ISSUE TITLE
[BUG] Auto-play toggle is not clickable in playlist

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5632]
# Description

Attempting to click on the auto-play toggle does nothing - toggle does not change to off and playlist items continue to auto-play.

Tested in both Safari and Chrome on Mac so far.

# Done Looks Like
- [ ] Clicking the auto-play toggle changes auto-play state off/on

**Comment by joncameron** [comment]
Markup issues are making this a non-toggleable component; will need to investigate how to do this without also breaking accessibility requirements.

**Comment by joncameron** [comment]
Works again, and autoplay worked as expected when toggling off and on.
