### ISSUE TITLE
Auto-play of playlists does not work in iOS

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5637]
# Description 

For playlists in iOS, once one video finishes playing, the next cues up but does not start to play. This happens in both Safari and Chrome, regardless of whether video playback is in full screen mode using the native player or playing within the web page on iPad. This also happens on iPhone in both Safari and Chrome.

This has not been observed even in full screen mode in Chrome on Android or chrome/Firefox on laptop.

Looking at mco-staging to try to compare with past behavior:

- On iPad, the auto-play does not advance in non-full screen mode or full screen mode in Safari. In Chrome, auto-play works in both full screen and non-full screen mode. 
- On iPhone, auto-play works in Safari but not in Chrome.

This suggests it is a partial regression.

Note: I have not tested this with audio only items, but presumably it will act in the same way.

**Comment by masaball** [comment]
I thought I was able to replicate this when I initially looked at it end of day yesterday, but this morning I have not been able to reproduce it. Playlist autoplay from avalon-dev has been working as expected on every iOS device I've tested with on browserstack. @elynema would you be able to retest or provide your test playlist?

**Comment by elynema** [comment]
@masaball @joncameron I am getting a wild variation on this issue across devices and iOS versions and browsers.

iPad iOS 15
- works in Safari
- does not work in Chrome

iPad iOS 16
- Works on in Chrome when video is not played full screen
- Does not work in Safari or when video is played full screen in Chrome

iPad iOS 17
 - Works in Safari and Chrome
 
iPhone iOS 15
 - Does not work in Safari or Chome

iPhone iOS 16
 - Does not work in Safari or Chrome
 
iPhone iOS 17
 - Works in Safari and Chrome

Given that this is working across both browsers in iOS 17, I am tempted to close this? I have no idea how hard it might be to troubleshoot something that varies across iOS versions like this.
