### ISSUE TITLE
[BUG] Playlist drop-down does not default to first playlist on iOS versions 17.x

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5641]
# Description

In mobile devices with iOS 17+. when the user clicks on Add to playlist, the playlist drop-down does not default to the first playlist. Instead, it displays the text 'Add new playlist'. User cannot click on the 'Add new playlist' text to actually add a playlist unless they first select a different playlist in the drop-down and then go back.

Older versions of iOS do not run into this issue. 

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUU4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12baf24735d26d4c4c501204588282a4556d2a43/RPReplay_Final1707335950.mov)

# Done Looks Like
- [ ] The first playlist (alpha order) should be selected by default when the user clicks Add to Playlist for an item. 
- [ ] 'Add new playlist' usually is available above the list of playlists if the user opens the drop-down, is bolded, and opens up a new modal to create a playlist if the user clicks on it.

**Comment by joncameron** [comment]
That dropdown is populated by some coffeescript; something in that could not be working as intended in iOS 17+.

**Comment by Dananji** [comment]
During implementation I tested this on;
- Firefox, Chrome, and Safari in Sonoma 14.4
- Chrome and Safari in iOS 17.4 and 16
- Chrome in Android 14

**Comment by elynema** [comment]
@charumitraravi Would you be willing to take a look at this one on avalon-dev for QA?

**Comment by charumitraravi** [comment]
For some reason, I am unable to select "Add to playlist" on iOS devices (both safari and chrome browsers) on avalon-dev. "Add to playlist", "Create timeline", and create thumbnail buttons are disabled.


![IMG_5872](https://github.com/avalonmediasystem/avalon/assets/52535309/eebc3288-b243-4309-839f-cac38351cf62)

**Comment by elynema** [comment]
Moving this back to In Progress due to issue Charu reported.

**Comment by elynema** [comment]
@Dananji Moving this back to In Progress due to the issue that Charu reported here.

**Comment by elynema** [comment]
@charumitraravi Can you re-test this?

**Comment by charumitraravi** [comment]
QA completed. The fix is working as expected
