### ISSUE TITLE
[BUG] Dynamically creating a new playlist from playlist drop-down in Add to playlist causes playlist to appear twice in drop-down

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5642]
# Description

# To reproduce

- Click on Add to Playlist
- Select 'Add new playlist' option
- Use the modal to create a new playlist
- Open the playlist drop-down again

You will see the playlist you just created shows up twice in the list of available playlists. It should be selected, but there will be another occurrence of it right above the selected option in the list.

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeTA4QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--04c22a189724da6467460c7b8a8d86699033d937/Multiple_instances_playlist.mp4)

Note that since the drop-down automatically selects the playlist you just created, most users probably aren't going to re-open that drop-down. Also, the duplication goes away on re-load, since the playlist isn't actually duplicated. So this seems relatively low priority.

# Done Looks Like

- [x] After user has filled out the modal to create a new playlist from the playlist drop-down available after selecting Add to Playlist, the new playlist should be auto-selected in the playlist drop-down.
- [x] If the user opens the playlist drop-down to view options, the new playlist should only show up once

**Comment by joncameron** [comment]
Not device-specific. Coffeescript is probably doing something.

**Comment by joncameron** [comment]
Looks good! Works as expected now, with no duplication.
