### ISSUE TITLE
[BUG] Due Date not appearing for checked out items in Safari on iOS devices

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5643]
# Description

While the due date for checked out CDL items seems to be showing for users (not the person who checked it out) ok in most contexts, it is still not working for Safari on iOS.

Sample record used for testing: https://avalon-dev.dlib.indiana.edu/media_objects/k930bx02c

Tested across several iOS versions on both iPhone and iPad with same results:

<img width="559" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMnREQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1db0e55884c445af450e3feeefa9dcb56bee64f2/bs_realios_Tablet_iPad%20Pro%2012.9%202021-17.0.jpg" alt="bs_realios_Tablet_iPad Pro 12.9 2021-17.0.jpg" />

<img width="365" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM1JEQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b93b91b56c1b7c874d738072eb9cbe0d740ee63/bs_realios_Mobile_iPhone%2015-17.0.jpg" alt="bs_realios_Mobile_iPhone 15-17.0.jpg" />

**Comment by joncameron** [comment]
readyState DOM event triggers the JS—probably something in iOS where this same event is not happening.

**Comment by masaball** [comment]
I have been unable to replicate this issue on Avalon-dev or my local instance. I have tested various phones running iOS 13-17 on browserstack and 2 or 3 iPads. Due date appeared as expected on all of them.

**Comment by elynema** [comment]
Moving this into QA for another round of testing by Jon / Emily / Charu. Sounds like we can close this!

**Comment by joncameron** [comment]
Looks good! Tested and working as expected.
