### ISSUE TITLE
Mute Hotkey Not Working in Chrome

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5645]
# Description
Mute hotkeys are working for audio items but not video in Firefox, but not for any items in Chrome and I noticed some buggy behavior there.

# To Reproduce
- Load https://avalon-dev.dlib.indiana.edu/playlists/49 in Chrome:
-   Pressing the 'm' key at page load toggles mute
-   Click play in the media player for the first playlist item (video)
-   The 'm' key no longer works to toggle mute
-   Click the last item in the playlist (an audio item)
-   'm' key does not toggle mute
-   Click the 'Play' button in the media player
-   'm' key now toggles mute as expected

# Done Looks Like

**Comment by joncameron** [comment]
Needs more testing; which hotkeys is this affected (just mute)?

**Comment by elynema** [comment]
Behavior of other hotkeys is also impacted. For example:
- spacebar (hotkey to start/stop playback often does not work when a section title is selected on the media object page. 
- spacebar also does not reliably start/stop video when user selects a playlist item on a playlist
- spacebar does not work when a tab heading is selected

This playlist provides an example: https://avalon-dev.dlib.indiana.edu/playlists/56. So far, the pattern I have found here is very odd: Select a playlist item, spacebar hotkey doesn't work. Select another, spacebar hotkey works. Select another and spacebar hotkey doesn't work again. It seems to alternate back and forth working/not working. This pattern also happens on the media item page when selecting sections.

Also some oddities when you tab into the media player controls:
 - spacebar (the hotkey to start/stop video) is triggering the button behavior. That is supposed to be reserved for the 'enter' button
 - spacebar does not reliably start/stop video when controls in the media player are selected

**Comment by elynema** [comment]
First pass on this on the Ramp demo site in Safari on macOS looked good.

**Comment by elynema** [comment]
So far, I have tested all hotkeys in Safari and Chrome on macOS on media item and playlist pages. I wrote up a couple of new issues for smaller things, but they are otherwise working in these environments.

Still need to test on some mobile devices.

**Comment by joncameron** [comment]
I'll create a (very low priority) issue to investigate what the best practice is for keyboards connected to mobile devices (should iOS respect hotkeys for the media player?).
