### ISSUE TITLE
Update License Headers

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5647]
# Description
Code files with the license header block need to be updated to include 2024.

# Done Looks Like
- [x] License header blocks updated for 2024

**Comment by cjcolvar** [comment]
A long time ago we built a tool for identifying files that need to have license headers added and files that need it updated then would automatically do that.  In the past I've temporarily put this gem into Gemfile.local locally and then removed it after running.  After running it I've combed over the changes to make sure that we're not adding it to files we didn't write and that it is doing it correctly.  See usage instructions on the gem: https://github.com/avalonmediasystem/license_header/blob/main/README.md#usage
