### ISSUE TITLE
Update Gem File and Tag Dependency Repos

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5649]
# Done Looks Like
- [ ] Tag dependency repos
- [ ] Update gemfile to point to those tags

**Comment by joncameron** [comment]
@masaball Is this ready to be closed since the new versions of iiif-manifest and active-encode are tagged?

**Comment by masaball** [comment]
Yes, should be good to close. The updated gemfile is up on Avalon-dev.
