### ISSUE TITLE
[BUG] Captions are showing up twice on screen on iPad, macOS Safari, iPhone

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5650]
# Description

When captions are enabled both in the native player and in the Ramp player, they show up twice in the video.

This is occurring on iPad both Safari and Chrome across multiple iOS versions, desktop Safari, and iPhone Safari in non-fullscreen mode.

# To reproduce
1. Begin playback on a video item that has captions in Chrome
2. Start full-screen playback and turn on subtitles in the native player
3. Exit full-screen and return to playback in the browser
4. Turn on CC via the gadget in Ramp
5. captions will display twice in the video

[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMWhJQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c1ccf44c9a860014b1c459e324126404aaea386a/Screen%20Recording%202024-02-09%20at%201.08.54%20PM.mov)

**Comment by joncameron** [comment]
Updated to reflect that this is also an issue in desktop Safari

**Comment by elynema** [comment]
@joncameron I'm unable to replicate this issue on MacOS Safari. It does not use the native player; it uses a Ramp player even when full screen. Can you provide more information about this?

**Comment by elynema** [comment]
Here is a scenario I found in Chrome on iPad (Chrome uses the native player):

- Load page with video with captions
- Captions are turned on in Ramp by default
- Start playback fullscreen. 
- Captions do not display in native player b/c I haven't turned them on in the past in the native player on this device (it remembers last setting you selected)
- Turn captions on in native player so I can see them
- Exit full screen. Now captions are showing twice in Ramp.

This sequence of events seems more probably than others I have found for actually happening in the real world. While usage of Chrome on iOS is relatively low (probably don't need to worry too much about), usage of Chrome on Macintosh is quite high. Unfortunately, based on user agent, we probably can't separate out usage of Chrome on desktop/laptop vs. usage of Chrome on iPad in our analytics.


[Private Zenhub Video](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd3BRQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--97d26072222a3f2ce8c48fd5aeccf2c5409fc438/Screen%20Recording%202024-02-12%20at%205.49.19%20PM.mov)

**Comment by joncameron** [comment]
I couldn't reproduce in Browserstack but could in my local machine Safari, so for me this is probably a settings issue and not applicable in desktop Safari generally.

**Comment by joncameron** [comment]
I couldn't reproduce in Browserstack but could in my local machine Safari, so for me this is probably a settings issue and not applicable in desktop Safari generally.

**Comment by joncameron** [comment]
One point of investigation is removing the VTT files from the HLS manifests we generate. If we're only going to be using file references outside of the context (like the player putting everything together from the IIIF manifest). We could instead be supplying the text tracks to the native player outside of the HLS manifest. But, Video.JS may not give us the tools to interact with the native player in a more granular way.

**Comment by elynema** [comment]
This is resolved in 7.7.1 with removal of VTT files from HLS manifests. See #5722, Ramp #443
