### ISSUE TITLE
Retain Captions Settings For User Sessions

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5651]
# Description
In addition to the volume level, captions settings (whether captions are enabled or not) should also carry over from section to section or item to item so users do not need to select these again in each instance.

# Done Looks Like
- [ ] Avalon stores caption on/off state for application sessions
- [ ] When a user navigates between item pages or sections, caption state is retained and captions are enabled/disabled according to that value
- [ ] Avalon default caption selection is not changed (this ticket is only for captions being enabled/disabled, not tracking which captions are selected for a particular item or section)

**Comment by joncameron** [comment]
Chris wasn't seeing an event for text track changes; we'll need to look and see if there's a way to be notified when users change the captions setting so it can be stored.

**Comment by joncameron** [comment]
We could get more information about the text track and label and could be stored, and fall back to default if nothing's found.

**Comment by Dananji** [comment]
I made the relevant changes in Ramp for the player. @cjcolvar is there anything else that needs to be implemented on Avalon-side for this work?

**Comment by joncameron** [comment]
👍
