### ISSUE TITLE
Spacebar Not Working as Play/Pause Hotkey

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5652]
# Description
The spacebar does not work as a play/puase toggle if the user has clicked on a section header (ok if user has clicked on a timespan within structured navigation) or if user has tabbed to a control in the player like prev/next (spacebar activates that button). I'm also finding that the play/pause toggle is not working when playlist items are selected, as well. 

Documentation says enter, not space, should trigger the button. Right now it looks like when a section is selected, pressing spacebar is moving the video forward frame by frame (for video).

# To Reproduce
- Go to https://avalon-dev.dlib.indiana.edu/media_objects/gf06g267d
- Click the second section "Legislative Organization of..."
- Press the spacebar key
- Play/pause does not toggle as expected
- Styling changes on the first segment in the structure when spacebar is pressed (?)
- 

# Environment
Tested in Safari on macOS.

**Comment by joncameron** [comment]
Needs to be tested on the demo site.

**Comment by elynema** [comment]
With Ramp #409 on demo site, this seems to be working ok now. Needs to be re-tested once that is rolled into Avalon.
