### ISSUE TITLE
Hotkey issues for playlists in Safari

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5656]
# Description

Hotkeys are being very flaky during media playback in the playlist context in Safari on macOS. 

The mute hotkey is only working for the first playlist item. After advancing to the second (or later) either through next canvas or by selecting a playlist item, it often (but not always) doesn't work. 

I believe the pattern matches what is described in #5652; hotkeys only seem to be working in Safari every other item when selecting section headers or playlist items. So for example, they don't work if you select the first item a playlist, then do work for whatever playlist item you select next, then don't work for whichever item is selected third.

**Comment by joncameron** [comment]
Needs to be retested; may be fixed with a recent commit.

**Comment by elynema** [comment]
With Ramp #409 re-tested in Ramp demo site with playlists in Safari and this is working. Need to re-test once that gets rolled into Avalon.
