### ISSUE TITLE
Keyboard pops up when opening playlist drop-down on Android devices

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5663]
# Description

On Android devices (Chrome), when the user attempts to add an item to a playlist, the typeahead box seems to be automatically selected, and the keyboard immediately pops up on screen, which makes it difficult to select a playlist from the drop-down menu. The user can either close the keyboard or scroll the screen up to be able to access the drop-down, so there is a workaround. On iOS devices, the keyboard doesn't open until the user actually clicks on the text input at the top of the drop-down, which allows filtering of playlists. This seems like a more desirable user experience.

To reproduce:

1. Open a media item
2. Select Add to playlist
3. Click on the playlist drop-down to select a playlist
4. the keyboard pops up

<img width="363" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2xjQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--925a3630ceba41e260e8b064b9f9b93ceec16c3c/bs_realdroid_Mobile_Samsung%20Galaxy%20S23-13.0-1080x2340%20%283%29.jpg" alt="bs_realdroid_Mobile_Samsung Galaxy S23-13.0-1080x2340 (3).jpg" />

Ideally, since this is a drop-down and not a text input field, the keyboard should not pop up.

# Done Looks Like
- [x] Change focus on mobile (iOS and Android) so that the typeahead field is not selected by default in the "add to playlist" form

**Comment by joncameron** [comment]
iPhone behavior may technically be the bug: default behavior does seem to be having the input field focused.
