### ISSUE TITLE
Hotkeys do not work when user selects a tab (details, transcript, files)

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5666]
# Description

If the user tabs to or clicks on a tab header on the media item page in Avalon (Details, Transcript, or Files) in Chrome, the media player hotkeys stop working.

In version prior to 7.7, if the user clicked on Details or Files headers, the player hotkeys still worked.

Note that this behavior is not exactly the same across browsers. In Safari, the hotkeys still work if you click on a tab header, but not if you navigate to a tab header using the tab key.

# Done Looks Like
- [ ] Media player hotkeys (except left/right arrow keys) are active after a tab label has been selected
- [ ] When a visual tab is selected in interface, left/right arrow keys should move user through the tabs, with enter to select an unselected tab

**Comment by joncameron** [comment]
The hotkey function excludes the tabs intentionally because it was interfering with keyboard navigation of tabs (arrow key to move between tabs would also jump time in the video). Filtering for events doesn't need to be as aggressive at it is. We can keep everything bubbling up except the arrow keys when the tabs have focus.

**Comment by Dananji** [comment]
According to [W3C documentation](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/examples/tabs-automatic/), when focused on Tab UI, only right and left arrow keys are used to move through the tab list. Therefore in Ramp, the code was altered only to block right and left arrow keys events when focused on a Tab UI.

Testing note: all the hotkeys work EXCEPT for right/left arrow keys when focused on a Tab in the UI.

**Comment by joncameron** [comment]
Created #5744; otherwise this worked as expected in Chrome and Safari.
