### ISSUE TITLE
No website URL label generated for collection if not entered by user

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5668]
# Description

SiteImprove noticed that for the Edward and Naomi Feil Collection, there is a website URL, but no website label. This is causing the create of an `<a>` tag with no link text (so it doesn't actually display).

Collection record: https://media.dlib.indiana.edu/collections/00000m29p

<img width="1341" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2xoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--94fad156f36de8267d133e51c9c3eb5114400709/image.png" alt="image.png" />

<img width="1091" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2RoQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c9e9b56edadca569306865a555cc04bb2fdd10aa/image.png" alt="image.png" />

In this scenario, Avalon should auto-generate link text to match the website URL.

**Comment by joncameron** [comment]
Looks good as per testing with https://avalon-dev.dlib.indiana.edu//collections/8k71nh08w.
