### ISSUE TITLE
[BUG] Captions are duplicated in embedded player

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5682]
# Description

Any caption that is available for an item is duplicated in the CC widget for the embedded player. Here is an example of what this looks like:

<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHB2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b7e5fd484fc59cb64abd89c06290866b03167a83/image.png" alt="image.png" />

Here you can see that there is only 1 caption for this record:

<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNHR2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3358eef4032d3391bb8675822862bf89faa748e3/image.png" alt="image.png" />

Record: https://avalon-staging.dlib.indiana.edu/media_objects/37720c74n

**Comment by masaball** [comment]
I expect that this is another case of us creating track elements to feed into the VideoJS player and then the VideoJS player adding duplicates to that list from information in the HLS manifest. The embedded player does not go through Ramp so filtering of the player tracks is not touched.

**Comment by joncameron** [comment]
I'm still seeing two captions listed on staging for the first section of https://avalon-staging.dlib.indiana.edu/media_objects/37720c74n:
<img width="680" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE4wQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb50569c0d1a363bf8bbf96835a18bdab6c2da97/Screenshot%202024-02-20%20at%201.47.58%E2%80%AFPM.png" alt="Screenshot 2024-02-20 at 1.47.58 PM.png" />

**Comment by elynema** [comment]
Looks good on avalon-dev in Safari and Chrome; will test on avalon-staging, as well.
