### ISSUE TITLE
[BUG] Creating a timespan for a section when a track is selected does not create a timespan that spans the full section

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5684]
# Description

If I select a track in the structured navigation and click Create Timeline, and select the first option, which represents the entire section, I do not get a timespan that spans the entire section. Instead, I get a timeline that spans only the tracks in that section. Any minutes that covered by those tracks are not included in the timeline.

This seems to be a regression from MCO, where a similar action creates unlabeled bubbles for time not covered by a timespan.

Here is the example item and the Create Timeline option selected:

<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3R2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d9369922b31e7bb8525ce87ac3dc429b9eb4d1bc/image.png" alt="image.png" />

Here is the timeline that was created; it represents only 6 of the 15 minutes in the video:

<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3h2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1e20dcfd3f43b82cd3751710d38a7ea767883ad6/image.png" alt="image.png" />

Item: https://avalon-staging.dlib.indiana.edu/media_objects/v405s9361

In MCO, I tried something similar, and ended up with this timeline:

<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzF2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--45ffe70206d61f38a67f2b40f932b426038ab2e6/image.png" alt="image.png" />

Example item: https://media.dlib.indiana.edu/media_objects/jm215f41x

**Comment by joncameron** [comment]
First option in the form may be doing the action of the section option (as in the example above). Create Timeline modal had updates and there may be a wrong reference.

**Comment by elynema** [comment]
@charumitraravi Could you QA this bug on avalon-dev?

**Comment by charumitraravi** [comment]
Verified the fix and it is now working as expected. 

Eg:
https://avalon-dev.dlib.indiana.edu/media_objects/c821gj77m
<img width="300" alt="Screenshot 2024-06-13 at 11 21 29 AM" src="https://github.com/avalonmediasystem/avalon/assets/52535309/c60365ad-55d5-47a3-b1af-db9c98788490">

<img width="400" alt="Screenshot 2024-06-13 at 11 21 16 AM" src="https://github.com/avalonmediasystem/avalon/assets/52535309/ad21a62d-8891-4167-8b4a-e7b71a308bb5">
