### ISSUE TITLE
[BUG] Create timeline button does not always enable on page refresh

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5685]
# Description

When loading a refreshing a media item page, the Create Timeline button fairly frequently remains disabled. I have not observed this behavior in avalon-dev, but am seeing it fairly frequently in avalon-staging.

<img width="1479" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEJ2QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f5eddb1dc1b17f20e13ad2dff625a3ac6bd25225/image.png" alt="image.png" />

Example item: https://avalon-staging.dlib.indiana.edu/media_objects/v405s9361
Another example: https://avalon-staging.dlib.indiana.edu/media_objects/ns0646018

There does appear to be a JS error in the console on avalon-staging; not sure if it is related since it shows up regardless of whether Create timeline button gets enabled, but I don't see it on avalon-dev.

`Unsafe attempt to load URL https://avalon-staging-minio.dlib.indiana.edu/supplementalfiles/5q4qgso3gh8qzkrgl5s53is9g1b2?response-content-disposition=attachment%3B%20filename%3D%22s7526w20z-VolcanoNaturesInferno.vtt%22%3B%20filename%2A%3DUTF-8%27%27s7526w20z-VolcanoNaturesInferno.vtt&response-content-type=text%2Fvtt&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=minio%2F20240219%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240219T223301Z&X-Amz-Expires=300&X-Amz-SignedHeaders=host&X-Amz-Signature=d36793684e6691fc67ee8bbe6a00a057f3cb898da35b4f7009f181ed04f4eb52 from frame with URL https://avalon-staging.dlib.indiana.edu/media_objects/ns0646018. Domains, protocols and ports must match.`

**Comment by joncameron** [comment]
This appears to be working on avalon-dev; I couldn't reproduce there now. @cjcolvar could you add this to staging so I can test there too?

**Comment by joncameron** [comment]
Looks good! Could not reproduce with either example item on staging.
