### ISSUE TITLE
[BUG] Create Thumbnail Button for Audio

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#5693]
**Describe the bug**

In Avalon 7.7 create thumbnail button was removed from the player's control bar and implemented external to the player with Ramp integration. And the new `Create Thumbnail` button is displayed for both audio and video, while in Avalon 7.6 create thumbnail was a functionality only for video items.
Avalon does not have poster images associated with audio items yet, therefore it seems like this functionality is not applicable to audio items.

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. Go to any audio item page
3. Click on `Create Thumbnail` button
4. See the modal popup

**Expected behavior**
No `Create Thumbnail` button for audio items ?

**Screenshots/Screen Recording**

In Avalon 7.6:

_Audio player:_
![Screenshot 2024-02-20 at 2 10 53 PM](https://github.com/avalonmediasystem/avalon/assets/1331659/636ced71-58bd-4ac1-9f4f-c2724e0871f4)

_Video player:_
![Screenshot 2024-02-20 at 2 11 44 PM](https://github.com/avalonmediasystem/avalon/assets/1331659/88d6e7d5-cb2c-4b1c-a654-f1fda2950701)

In Avalon 7.7:

_Audio player:_
![Screenshot 2024-02-20 at 2 13 38 PM](https://github.com/avalonmediasystem/avalon/assets/1331659/a90db051-5194-4182-b64e-94cf39ab04fd)

_Create thumbnail modal:_
![Screenshot 2024-02-20 at 2 07 07 PM](https://github.com/avalonmediasystem/avalon/assets/1331659/5b8d5132-6f5f-4175-8967-837c4dd56985)

**Release:**
Is this issue associated with a specific release? Avalon 7.7

# Done Looks Like
- [x] Create Thumbnail button is enabled when a video section is active and disabled when an audio section is active

**Comment by joncameron** [comment]
Button disabled for audio items as expected in dev. Tested on an item with both audio and video and the button enables/disables as appropriate.
