### ISSUE TITLE
Removing VTT Files From HLS Manifests

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5695]
# Description
One point of investigation in fixing the double caption issue in Apple's media player is removing the VTT files from the HLS manifests we generate. If we're only going to be using file references outside of the context (like the player putting everything together from the IIIF manifest), we could instead be supplying the text tracks to the native player outside of the HLS manifest. But, Video.JS may not give us the tools to interact with the native player in a more granular way.

# Done Looks Like
- [ ] Investigation into removing VTT file references from HLS manifest

# Questions
- Will removing this fix the double caption display issue? (#5650)
- Will multiple captions show up in native player? (https://github.com/samvera-labs/ramp/issues/405)
- Will this cause captions to not be available in the native player?
- Is changing CSS for the native player to hide overlay captions there an option?
- Does this solution work for embedded player?

**Comment by joncameron** [comment]
Is changing CSS for the native player to hide overlay captions there an option?

**Comment by Dananji** [comment]
1. [Sample IIIF Manifest](https://gist.githubusercontent.com/Dananji/a3ec009d4922b772962498173b0a5aca/raw/a18480cee491eb6b2a13963c35b3a34ca3a6e399/distinct-captions.json) with an [HLS stream](https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p/section/c821gj76b) without captions from `avalon-dev` with a `supplementing` annotation with the following Video.js options, in Chrome, iPad iOS 17: 
```
...
html5: {
  nativeTextTracks: IS_MOBILE && !IS_ANDROID
}
```

|  | Ramp player | Native player |
| ------------- | ------------- | ------------- |
| First Caption Selected | ![screenshot-iPad Pro 12 9 2021-17 0](https://github.com/avalonmediasystem/avalon/assets/1331659/ccb58619-c0a4-4079-859f-8049411ff0b7) | ![screenshot-iPad Pro 12 9 2021-17 0(4)](https://github.com/avalonmediasystem/avalon/assets/1331659/1c878c59-aa7f-440f-bfe1-2b8e8eac0af1) |
| Second Caption Selected | ![screenshot-iPad Pro 12 9 2021-17 0(2)](https://github.com/avalonmediasystem/avalon/assets/1331659/9d5914e1-2064-471f-ae32-65575c0e9598) | ![screenshot-iPad Pro 12 9 2021-17 0(19)](https://github.com/avalonmediasystem/avalon/assets/1331659/7062a803-15a0-4273-98ae-e5a92bcb201f) |

_______________________________________________________________________________________________________
2. [Cookbook captions manifest](https://iiif.io/api/cookbook/recipe/0219-using-caption-file/manifest.json) with the same Video.js options;

| Ramp player  | Native player |
| ------------- | ------------- |
| ![screenshot-iPad Pro 12 9 2021-17 0(1)](https://github.com/avalonmediasystem/avalon/assets/1331659/647506b7-a7bf-49c7-920e-6d047fca1013) | ![screenshot-iPad Pro 12 9 2021-17 0(20)](https://github.com/avalonmediasystem/avalon/assets/1331659/f12cb410-62ac-409b-b33d-f438094670bc) |

_______________________________________________________________________________________________________
[Avalon IIIF Manifest](https://avalon-dev.dlib.indiana.edu/media_objects/gf06g267d/manifest.json) from `avalon-dev` with the same Video.js options;

|  | Ramp player | Native player |
| ------------- | ------------- | ------------- |
| First Caption Selected | ![screenshot-iPad Pro 12 9 2021-17 0(18)](https://github.com/avalonmediasystem/avalon/assets/1331659/6d0b8896-65f4-4341-869f-9d9feb178d6d) | ![screenshot-iPad Pro 12 9 2021-17 0(16)](https://github.com/avalonmediasystem/avalon/assets/1331659/fdd5f017-fcb0-461f-923d-f181c56dc250) |
| Second Caption Selected | ![screenshot-iPad Pro 12 9 2021-17 0(10)](https://github.com/avalonmediasystem/avalon/assets/1331659/13cea727-4ad8-45da-9fa4-38ef45a3e861) | ![screenshot-iPad Pro 12 9 2021-17 0(17)](https://github.com/avalonmediasystem/avalon/assets/1331659/92239611-b404-4700-b209-ff752348c5ad) |

3. [Same Avalon manifest](https://avalon-dev.dlib.indiana.edu/media_objects/gf06g267d/manifest.json) with the following Video.js options;
```
...
html5: {
  nativeTextTracks: IS_MOBILE && !isStream && !IS_ANDROID
},
```

| Ramp player | Native player |
| ------------- | ------------- |
| ![screenshot-iPad Pro 12 9 2021-17 0(21)](https://github.com/avalonmediasystem/avalon/assets/1331659/bdd9b346-932d-446a-96bc-5ae769e2edd7) | ![screenshot-iPad Pro 12 9 2021-17 0(22)](https://github.com/avalonmediasystem/avalon/assets/1331659/c8b612b3-797b-416d-83a2-bd8805eb8918) |


Observations:
- Native player in iOS is able to display captions build by the Video.js instance in Ramp for both HLS streams and `.mp4` files in a given IIIF Manifest.
- No duplication of the captions were observed when using the Video.js option `nativeTextTracks: IS_MOBILE && !IS_ANDROID`. In the both IIIF manifests in 1 & 3, there was a captions option built into the captions menu which did not populate text track overlay on top of the video in both Ramp and native player instances. And from a first glance these empty options seem to be populated from the HLS manifest captions.

**Comment by Dananji** [comment]
For the embedded player, it seems reversing the changes in https://github.com/avalonmediasystem/avalon/pull/5688 would make it possible to feed captions into the Video.js instance instead of using captions generated by the HLS manifest.

**Comment by Dananji** [comment]
After a conversation with Emily; came to the conclusion that, presenting captions in the IIIF Manifest is the best approach at the moment. The reasoning behind this decision are;
- Embedding captions only in the HLS manifest would be useful if Avalon intended to share media items as raw files, which is not a use-case. Avalon expects to share resources via IIIF manifests and within embedded player.
- In embedded player context, Avalon can build the player instance with captions provided via `track` HTML elements to the Video.js instance instead of relying on HLS captions.
- At the moment there is no way to indicate the presence of embedded captions in the media resource in the IIIF Presentation 3.0 API. Therefore, IIIF manifests are not able to convey the availability of embedded captions. The only way to access the captions presented in this manners (i.e. in the HLS manifest) would be to paint the Canvas in a IIIF viewer, which supports HLS. To evaluate HLS support in other IIIF A/V viewers listed in the [IIIF Viewer Matrix](https://iiif.io/api/cookbook/recipe/matrix/#audiovisual-recipes), I tested one of the [public items](https://avalon-dev.dlib.indiana.edu/media_objects/gf06g267d) in `avalon-dev` in these viewers;
    - UV: loads the manifest into the viewer, but does not support streaming
    - Mirador: loads the manifest into the viewer, but does not support streaming
    - Clover: loads all Annotations with `supplementing` motivation from the IIIF Manifest + HLS captions into the player's captions menu. And this particular example the same file is used as a caption and a transcript, thus populating the captions menu with the same file 3 times.

**Comment by elynema** [comment]
If we utilize IIIF manifest captions only, we do lose the caption settings options in iPads and iPhones. 

If we put the captions only in HLS manifest, not in IIIF manifest, there's no indication in IIIF manifest that there are captions unless the canvas is painted in a viewer that supports HLS. So for this reason, we prefer IIIF manifest captions now.

**Comment by elynema** [comment]
@joncameron @Dananji Should we proceed with a new issue to actually remove the VTT files from HLS manifests? Do we need further discussion?

**Comment by Dananji** [comment]
There are still some issues with captions in iOS context. Related new issue with details: https://github.com/samvera-labs/ramp/issues/451
Testing note: not ready to be tested on iOS devices yet.

**Comment by Dananji** [comment]
One more issue related to caption selection: https://github.com/samvera-labs/ramp/issues/452
