### ISSUE TITLE
Caption migration script fails for unexpected caption formats

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5707]
# Description

Looks like it is getting hung up on the mime type of existing captions not matching expected mime types (only text/srt and text/vtt).  On mco-staging the mime types I'm seeing are:
["application/octet-stream", "text/srt", "text/vtt", "text/plain", "text/vtt;charset=utf-8"]

Rake task is failing on an item with "application/octet-stream"; validation is happening in the supplemental files model, not the rask task. 

Does Ramp need this specific mime type? No, Ramp passes through directly to Video.js for captions; (for transcripts, reads headers in response and checks against the list of allowed types). Video.js does expect WebVTT but we'll need to test if it will reject captions with an unexpected mime type.

# Done Looks Like
- [x] Validation skipped for captions during migration (rake task)
- [x] Double checking to confirm that SRT will work with Video.js

**Comment by masaball** [comment]
@joncameron @elynema I just tested an SRT caption file against Video.js and it did not work. The caption option is generated in the menu and the video plays fine but no captions display. In the console there is a parsing error:
<img width="790" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNVd6QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--042de196113db759c113c3c19378ab4b23a871ae/Screenshot_20240305_124647.png" alt="Screenshot_20240305_124647.png" />

So it looks like video.js likely does not care about the mime type, but it is expecting WebVTT formatting and does not parse other caption formats.

**Comment by elynema** [comment]
Jon C. just came to a similar conclusion and created #5712. Since we already have SRT captions in MCO, I think we need to find a way to support them, both in this migration script and in Ramp itself. 

@masaball Does it make sense for this issue to be focused on skipping validations in the rake task and #5712 to focus on figuring out a way to get Ramp to support more than just SRT?

After that, we'll have the other captions in MCO that are neither VTT or SRT. Chris ran the numbers this morning:
`{"text/srt"=>919, "text/vtt"=>1357, "application/octet-stream"=>83, "text/plain"=>4, "text/vtt;charset=utf-8"=>1}`

Do those 88 need to be examined individually to determine what they are post-upgrade?

If we can only support SRT and VTT for captions, we also really need to put restrictions on the upload.

**Comment by masaball** [comment]
I think leaving this issue as just skipping validation and having any additional work for caption compatibility being handled in #5712 makes sense.

The 88 non SRT/VTT files will most likely need to be checked individually to see what format they are in. I expect, besides the `"text/vtt;charset=utf-8"` file, that they will all be SRT format but we'll see.

As for restricting upload, we already have the validation on saving a Supplemental File that checks the mime type for `text/vtt` or `text/srt` if it is meant to be a caption so it should not be possible for users to upload wrong-typed files through the section file edit form. 

What's confusing is that there was validation in place for the legacy caption format as well. I would assume the files were added before the validation was put in place or they were added manually through the console.
