### ISSUE TITLE
Mechanism to programmatically load captions/transcripts to existing records

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5710]
# Description

Adding Transcript files to a record currently requires manual upload in the UI. Several use cases exist where we may need to be able to automatically load captions/transcripts generated elsewhere into records that already exist in MCO. We should be able to specify whether the file should be a caption, transcript, or both, as well as the particular item and section to attach it to. 

This should be added to the Avalon API: how can we enhance the API to add files to records? Is there a specific way to best do this that would also open up the possibility of adding media files, captions, supplemental files etc. using HTTP requests?

Use cases:
- Loading oral history transcripts from oralhistory.iu.edu site into pre-existing records in MCO
- Loading captions for Clio awards collection generated from Whisper
- Ability to write a script to load captions we pay to be generated by 3Play into MCO (so a student doesn't have to do this by hand one by one)
- If we build an integration with AMP where users can request to send one MCO record, a collection, or a group of records to AMP to create transcripts, then MCO needs to be able to pull the caption/transcript back into the MCO records when they are available. Ideally this would be automated as a regular job.
- 

# Done Looks Like
- [ ] /masterfile/supplemental_files route respects API token authentication

**Comment by joncameron** [comment]
One option: write up the routes that exist and make sure they work well programmatically (auth via API key in headers etc.)

**Comment by joncameron** [comment]
@joncameron Update done looks like

**Comment by joncameron** [comment]
What other routes are available? Right now we have something like avalon-dev.dlib.indiana.edu/master_files/nv935286k/supplemental_files/276/captions.

**Comment by joncameron** [comment]
Adding JSON responses to these routes would be the ideal. 

What are the options for moving the caption/transcript files in and out? What makes the most sense for POSTing a file? This could be expanded to match what we currently have.

**Comment by joncameron** [comment]
Probably worth it to enhance the API instead of just starting with API auth on the existing routes the receive form data. Implementing standard API responses around these seems doable (~3 points). I'll rewrite/write a new issue to capture what the expectations are for interacting with the API and the routes so we can add this in full.

**Comment by elynema** [comment]
@joncameron I'd like to get this into 7.8 release. Has a new issue been created as the above comment suggested?

**Comment by elynema** [comment]
Closing this as a dupe of #5801.
