### ISSUE TITLE
Transform SRT to VTT for Caption Files

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5712]
# Description
Avalon 7.6 allowed for SRT files to be uploaded as captions, bit in 7.7, Ramp is not able to display SRT captions, only VTT (this is a Video.js limitation). Avalon should be able to accept SRT files as well as WebVTT files as valid captions.

As of 3/5/24, there are 919 captions already existing in MCO that are in SRT file format. 

# Done Looks Like
- [ ] Users can add files in SRT format as captions to sections
- [x] SRT files are transformed to VTT when requested through the /captions route
- [x] SRT files display as expected in the media player when captions are enabled

**Comment by elynema** [comment]
Suggestion from Mason's research: So it looks like video.js likely does not care about the mime type, but it is expecting WebVTT formatting for its parsing and does not parse other caption formats.

VideoJS team a few years ago suggested a method for converting [SRT to VTT on the fly](https://github.com/videojs/video.js/issues/5923#issuecomment-482061934) but the most robust solution would probably be doing the conversion on file ingest. This would require another round of remediation of currently existing caption files though.

**Comment by joncameron** [comment]
Could be small in scope, depending on tools available for conversion.

**Comment by elynema** [comment]
Potential gem for conversion? https://github.com/opencoconut/webvtt-ruby

**Comment by joncameron** [comment]
@masaball 
I was able to attach an SRT and see it in the player, but there's another issue popping up: validation is failing when Saving on the Manage Files edit page. Adding a caption file will send the caption data to Avalon, refresh the page, and display the "Supplemental file successfully added." message. But when selecting "Continue", I got the splash error message.

To reproduce:
- Create a new item
- Upload the lunchroom manners mp4
- Upload the lunchroom manners SRT caption file
- Select "Continue"
- The masterfile disappears and the user receives a validation error:
<img width="1154" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmJUQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c5268a46bf119e52d0206ab7bc9d4e965776170f/Screenshot%202024-03-12%20at%2011.55.04%E2%80%AFAM.png" alt="Screenshot 2024-03-12 at 11.55.04 AM.png" />
Refreshing the page will bring back the masterfile in the listing, and moving onto the Resource Description page by clicking the URL to it also does not error. It seems like maybe there's some validation not succeeding on this page in particular.

Test item: https://avalon-dev.dlib.indiana.edu/media_objects/8s45q877v. I converted the VTT for Lunchroom Manners to an SRT with FFmpeg and uploaded it to the test media folder: https://drive.google.com/drive/folders/1EJZ2ABWlvNqAClt1VLWvOx3qJcMsUYYo.

Testing in dev, I was able to add an SRT file to a section even with the above error and then see it appear as captions as expected in the media player on the item page, so the SRT->VTT path seems to be working as expected.

**Comment by masaball** [comment]
I am unable to replicate the error. Everything uploads fine for me and hitting 'Continue' takes me to the Resource Description page with no fuss. May be a weird caching issue on your end?

**Comment by joncameron** [comment]
Mason found that this was due to the the way the steps work in the Edit page flow. If you create a new object, upload a file, save, then move on to the resource description form or the view page, and then _back_ to Manage Files and save there again, you see the error which is in this case because the descriptive metadata isn't validated. This is a side effect of the unintuitive "steps" system of item creation in Avalon. 

For the purposes of this ticket uploading SRT files works as expected.
