### ISSUE TITLE
[BUG] Supplemental file doesn't properly set mime type of certain files

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5714]
# Description

Validation for supplemental files was updated/added with changes as part of 7.7. However, the new SupplementalFile creation code is not setting mime type explicitly. The old code does an explicit lookup of the mime type based on file extension: `Mime::Type.lookup_by_extension(captions_ext.slice(1..-1)).to_s`.  The new code does not have that check and just uses what the computer or browser thinks the mime type is, which for SRT files might be 'text/plain'? 

# Done Looks Like
  - [x] Ensure that Supplemental Files are created with the proper mime types, rather than relying on computer/browser
  - [x] Verify the type validation being performed for caption files in 7.7 codebase ('text/vtt', 'text/srt')

**Comment by joncameron** [comment]
I tested VTT and SRT files being added as captions and both seem good from what I can tell.
