### ISSUE TITLE
Caption Button Not Underlined When Active in Embedded Player

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5717]
# Description
The colored underline beneath the CC button in the player to indicate captions are on does not display in the embedded player.

# Examples
## item page
<img width="752" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeis3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5877c54c91e37c8de41243874a236487985305b2/Screenshot%202024-03-06%20at%201.41.12%E2%80%AFPM.png" alt="Screenshot 2024-03-06 at 1.41.12 PM.png" />

## embedded
<img width="610" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMEM3QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e3e28f166f92b8df1c5dc4d751d7a2148f86750f/Screenshot%202024-03-06%20at%201.41.05%E2%80%AFPM.png" alt="Screenshot 2024-03-06 at 1.41.05 PM.png" />

# Done Looks Like
- [ ] CC icon has a highlighting underline when captions are on in the embedded player.

**Comment by joncameron** [comment]
The bare Video.js instance is missing what Ramp provides in this instance.

**Comment by joncameron** [comment]
This can also be resolved when replacing the embedded player from bare Video.js to Ramp.

**Comment by elynema** [comment]
This appears to be resolved with Ramp as the embedded player.
