### ISSUE TITLE
Implement HasCaptions and HasTranscript facets

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5727]
# Description

This field(s) can be populated (or may be populated already) in Solr based on existence of caption or transcript for any section in a media object.

These 2 facets could be combined into a single facet, but we would want multi-select at that point, which we do not have for any facets at this time.

# Done Looks Like

 - [x] 2 new facets up in user facets
 - [x] Facet labels are 'Has Captions' and 'Has Transcript'
 - [x] Values for each facet are 'Yes' and 'No'
 - [x] If a media item has a caption for any section, it should be marked as 'Yes' for 'Has Captions'
 - [x] If a media item has transcript for any section, it should be marked as 'Yes' for Has Transcript'

**Comment by joncameron** [comment]
<img width="413" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNi9hQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f857715ee15af0dd42c6984850f06ca7eba5c773/Screenshot%202024-03-13%20at%201.47.58%E2%80%AFPM.png" alt="Screenshot 2024-03-13 at 1.47.58 PM.png" />
