### ISSUE TITLE
Show "found in" hints to indicate where search terms were found

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5728]
# Description

Show "found in" hints to indicate to user if search term(s) were found in:

- metadata: descriptive metadata only
- section labels + structure: section labels + any sub-structure
- transcript

# Done Looks Like

 - [x] show found in results below metadata for each item in search results as:
Found in: metadata (5)
Found in: sections (6)
 - [ ] if there is a zero count for either of these 3 parts (metadata, transcripts, sections), do not display that part
 - [x] do not show "found in" when results are showing from a browse, not search
 - [ ] For phrase searches with quotes, only media objects with that phrase should be returned, but the "found in" counts should be the same as if no quotes.

**Comment by joncameron** [comment]
Can wait until previous investigation; will need to look at highlighting in Solr.

**Comment by elynema** [comment]
Currently storing transcript as text, not text_en, so stemming is probably not happening. May want to re-consider this. Metadata hits are coming from a field with the entire MODS as text_en.

**Comment by masaball** [comment]
The new query set up to facilitate "Found in" hints and return transcript results adjusted the way that results are returned in the solr document. Previously, I think the entire solr document was being returned. The new query structure explicitly searches for specific fields. A quick audit of the code indicated that the minimum fields that need to be returned for parity with current Avalon are:

- has_model_ssim
- id
- title_tesi
- abstract_ssi
- date_issued_ssi
- date_created_ssi
- duration_ssi
- section_id_ssim
- avalon_resource_type_ssim

Most of these are to make sure that the metadata on the search page is properly filled. `avalon_resource_type_ssim` is necessary for displaying the thumbnails.

**Comment by joncameron** [comment]
Created #5903 for not displaying zero-count field results, otherwise this is working as expected in my testing.
