### ISSUE TITLE
Ability to mark captions as transcripts

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5729]
# Description

Collection staff are able to mark captions as "treat as transcript" in the Manage Files page. When this happens, the caption file should appear as a transcript in the transcript component. It also should register as a transcript for 'Has Transcript' and should be indexed for transcript searching and show up as hits in transcript when searching. 

Caption should only show up as a caption on Manage Files and not be duplicated as a Transcript. In the future, we may want to enable this functionality at the collection level, as well.

See #5736 

# Done Looks like

 - [x] checkbox next to language field in caption list with label "Treat as transcript" when editing
 - [x] when checked, caption text appears in transcript component
 - [x] when checked, caption text is searched and returned as hits in transcript
 - [ ] when checked, media item shows up in 'Has Caption' and 'Has Transcript' facet as 'Yes'
 - [x] when checked, caption file is only available for download once from the Files tab (transcripts will not be downloadable from Files tab)

**Comment by joncameron** [comment]
Should it show up in the Files tab as well on the item page?

**Comment by joncameron** [comment]
The 'transcript' tag could be added to the file in the application and much of the functionality may work from there. Filtering will probably need to be in place on the supplemental file page because we don't want the duplication there.

**Comment by elynema** [comment]
@charumitraravi This one is also pretty well set up in terms of Done Looks Like. Can you QA this? The work has been done to index transcripts in the main index on avalon-dev, so any caption marked as transcript on the Manage Files section for an item should be indexed into the main search box.

The Has Captions and Has Transcript facets will show up on the Browse page when you are logged into Avalon-dev as a manager.

**Comment by charumitraravi** [comment]
**when checked, caption text is searched and returned as hits in transcript** and **When checked, media item shows up in 'Has Caption' and 'Has Transcript' facet as 'Yes'**  - These conditions are failing. The caption is not being properly indexed as a transcript, making it unsearchable and not filtering correctly under the 'Has Transcript' facet.

**Comment by cjcolvar** [comment]
I'm not able to reproduce the failure for the first condition (*when checked, caption text is searched and returned as hits in transcript*), but I'm able to reproduce the failure of the second (*when checked, media item shows up in facets as Yes*) if I check the `Treat as transcript`, click `Save` for the caption, and then go directly to `Preview` without saving the item.  Once the item is saved (clicking the `Continue` button in the edit workflow) then it appears in the 'Has Transcript` facet as 'Yes'.

@charumitraravi Is there a particular item where the first condition is failing?  Were you seeing the failure for the second condition with a different flow than I described above?

**Comment by charumitraravi** [comment]
@cjcolvar 

https://avalon-dev.dlib.indiana.edu/media_objects/4x51hj01t

- You can check this item. If I search for the transcripts/caption, ie, with the keyword "yellowstone" or the full name of the caption, the item does appear in the search results 
- Yes, If I select 'continue' button in the edit workflow, it appears when the 'Has Transcript` facet is selected as 'Yes'.

**Comment by elynema** [comment]
@cjcolvar I have verified having issues when a Caption is marked to treat as a transcript, the item is still showing up as not having a transcript in the Has Transcript filter. 

This is true for this item currently:https://avalon-dev.dlib.indiana.edu/media_objects/hm50tr769.

I have not tested to verify whether clicking 'Continue' will make it show up properly in the Has Transcripts facet, but it doesn't seem like that step should be required as the setting value is already saved and remembered and the text is already populated into the index?

**Comment by elynema** [comment]
@charumitraravi For the example you listed, when I search the term 'lilly library' or 'lilly' I am getting this item in the search results. The transcript search is also working. Is there a problem you are still seeing with the indexing/searching of this caption?
https://avalon-dev.dlib.indiana.edu/media_objects/4x51hj01t

**Comment by charumitraravi** [comment]
@elynema 
I am able to get the item in the search resutls as well, If I search for 'Lilly library' . I was under the impression that the item would get indexed in the Search search results based on the name of the transcript/caption converted to transcript. I was trying to search 'yellowstone_whisper' and could not see the [item](https://avalon-dev.dlib.indiana.edu/media_objects/4x51hj01t) in the search results. I believe that isn't an expected behavior.

**Comment by elynema** [comment]
@charumitraravi Correct. We are not indexing transcript file names, just the contents of the transcripts.

Closing this as we have moved the work to update Has Transcripts and Has Captions facets whenever supplemental files are added/removed (not just when the media object is saved) to #5892.
