### ISSUE TITLE
Mark Captions As Machine Generated

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5731]
# Description
Transcript files can now be marked as "Machine generated", but this does not apply to caption files which are often similar, if not the same file, and are worthwhile to be marked as machine generated for user notification.

# Done Looks Like
- [x] Caption files can be marked as machine-generated
- [x] " (machine-generated)" appears next to the label displayed to users in the captions menu within the media player

**Comment by joncameron** [comment]
<img width="826" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2phQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bd4cc2a9470d4284e6c2e59b26f33e2f2b4632e6/Screenshot%202024-03-13%20at%202.02.45%E2%80%AFPM.png" alt="Screenshot 2024-03-13 at 2.02.45 PM.png" />

**Comment by joncameron** [comment]
Existing code needs to be applied to captions; styling might be the tricky part to add a new checkbox to the form.

**Comment by joncameron** [comment]
Options need to be discussed about how we'll actually do the styling here, two ideas:
- Add a new row to each caption listed
- Change the "Machine Generated" text label into an icon with a tooltip

**Comment by masaball** [comment]
@joncameron With the new option of 'Treat as Transcript' included, there is not room for all edit options for the captions to exist on a single row. The simplest styling option would be to move the checkboxes down to their own row below the label and language text boxes. Other options floated were potentially breaking the edit options out into a modal (not ideal), or creating some sort of icon(s) and tooltips to cut down how much real estate is necessary for the checkboxes. Are there other design schemes that might work?

For this ticket, it would probably be easiest to do the multiple edit rows and then see how we feel about it. We could then have a more in depth conversation on the design of the page and if/how it could be reworked, if necessary.

**Comment by masaball** [comment]
@joncameron Here are a few ways that we could approach laying out the page:
<img width="638" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUF5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--189e1c59ff60f80d8a1054821d0b2d689554e396/Screenshot_20240403_144129.png" alt="Screenshot_20240403_144129.png" />

This is @cjcolvar's suggestion of using toggleable buttons. The specific color choices are placeholders, but red for off and blue for on. Implementing this requires shrinking the input fields for the Label and Language to get the buttons to fit, but that does not seem like the worst tradeoff?

<img width="630" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVF5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--af86784e1b703d50dcbfbac17329eab49cf392a1/Screenshot_20240403_151139.png" alt="Screenshot_20240403_151139.png" />

Shrinking the input fields could also be used to have regular checkbox display within a single line.

<img width="636" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWN5QkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--56c6d8ad2c8456f07318c2b02256403d989e63cb/Screenshot_20240403_162837.png" alt="Screenshot_20240403_162837.png" />

And finally, we could have the check boxes on a separate line below the input fields. This option could also use the toggle-able button design from the first option, I just did not implement a mockup for that.

**Comment by joncameron** [comment]
Let's go with the last mockup option—having the check boxes on a separate row below the Label and Language fields. We can definitely continue to improve the styling on this but this approach seems both simple and functional for the time being.
