### ISSUE TITLE
Do not allow users to attach captions to files without video

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5741]
# Description

The audio player does not have a place to display captions, so we have disabled the CC widget for audio in #5681. Users need to upload captions as transcripts instead. Removing the captions upload option for audio files might actually help improve the likelihood that files are uploaded as transcripts instead.

# Done Looks Like

 - [x] If user uploads an audio-only item, when they clicked edit for that file under Manage Files, there will be no captions option

**Comment by joncameron** [comment]
Can leverage existing is audio/is video hinting in Avalon.
