### ISSUE TITLE
Create Thumbnail Doesn't Work (Demo)

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5743]
# Description
On Terraform-based Avalon instances like the demo.avalonmediasystem.org, thumbnail images are unable to be set. Using the modal to select a new poster/thumbnail seems to hit a 500 error on the POST to /still for a masterfile.

# To reproduce
- Go to https://demo.avalonmediasystem.org/media_objects/wh246s463 or another item on Demo
- Attempt to update the poster image
- Poster image does not update

# Done Looks Like
- [ ] Poster/thumbnail image update is successful when selecting the "Update Poster Image" button from the "Create Thumbnail" modal

**Comment by elynema** [comment]
nginx caching on thumbnails and poster images, but nothing to expire cache when these are updated in the application. This is impacting terraform sites. After 30 minutes, when the cache expires, the new thumbnails should show up.

**Comment by cjcolvar** [comment]
The caching layer is setup in `avalon-docker` on the `aws_min` branch which is only used by `avalon-terraform`.

Here's the config:
https://github.com/avalonmediasystem/avalon-docker/blob/aws_min/cache.conf
and the nginx docs for these directives:
nginx.org/en/docs/http/ngx_http_proxy_module.html

We should figure out how to expire the cache for thumbnail/posters or maybe consider disabling the cache until we can figure out a better solution.

**Comment by joncameron** [comment]
@cjcolvar What do you think would be best? I'm fine with commenting out lines for the Docker install if that resolves the issue in that enviroment. I can create a new issue either way.

**Comment by cjcolvar** [comment]
I'll make this change in `avalon-docker` and we can revisit caching another time.  This change will be on the `aws_min` branch so it only affects the Terraform environment.

Completed here: https://github.com/avalonmediasystem/avalon-docker/commit/5b3405852a5608c2510de951c56d10e8462001e6
