### ISSUE TITLE
Highlight search results in currently displayed transcript

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5753]
# Description

After user enters a search or search is passed through from the Found In: transcript link on search results: show yellow highlighting in currently visible transcript. Each term that was entered in search should be highlighted independently. If user selects a new section and opens a new transcript, search term should be retained and search terms should be highlighted.

To get search terms to be highlighted, does Ramp make an API call to get the results/highlights? When switch sections, does Ramp need to query search API to get new hits from back-end? Initially, it probably makes sense to make a separate request out to get results, perhaps each time a section is loaded.

After Ramp gets hits from back-end search API, it can cache results; this is how transcripts are handled.

If we decide not to implement IIIF Content Search at all, this could be just a Javascript search of loaded transcript text.

## Current highlight color in transcript component
![Screenshot 2024-05-01 at 2 57 23 PM](https://github.com/avalonmediasystem/avalon/assets/1406618/2a3df1d2-a7f1-40bd-80e2-fad3161a5982)

# Done Looks Like
- [x] When the transcript search is active (a user enters a search term in the text field and selects Return) matches are highlighted in the Ramp transcript display component
- [x] Moving back and forth between search hits changes the currently rendered section of the transcript document but does not seek in the player
- [x] Highlighting is via background-color styling property or text decoration (we could explore both options or mix and match for active/inactive)
- [x] Active search hit has a specific background-color or text decoration
- [x] Non-active search hits (matches that are not the current item in the transcript search navigator/pager) have a separate background color or text decoration
- [x] Color contrast is checked on the colors used for highlighting to make sure they're within WCAG 2 contrast guidelines

**Comment by joncameron** [comment]
This could be closed with the merge of the Third Wave Transcript component update—wait and reevaluate to see if this is still needed.

**Comment by elynema** [comment]
Let's leave this open and use this as an evaluation / testing issue for once the IIIF content search response content is integrated into the search widget to make sure it is behaving in a reasonable fashion.

**Comment by elynema** [comment]
In the code provided by Third Wave, highlighting of results in the transcript is done with bold, underline, and text color change. The active search hit is highlighted with a background color on the entire cue. The transcript text does scroll forward and back as you use arrows to page through results, but the video does not seek unless the user clicks on the cue in the transcript.

Looking at contrast, the dark green used in the Ramp demo site to highlight all results is fine for color contrast with the white background of the transcript component.  The black text in the highlighted active result (which has a light green background), is also fine. The dark green of a result and the light green background of the currently highlighted result are also ok for contrast. The only thing that doesn't meet contrast is between the normal white transcript background and the light green background used for the currently active search result. I'm not sure that is an issue that needs to be resolved?

**Comment by elynema** [comment]
@Dananji Which highlight color did you adjust? I'm still seeing a fail here between the color of the highlighted cue and the background white. Perhaps you adjusted a different color?

<img width="1402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmVWQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--29510712c07be09c7453608f3dd117586d0c967f/image.png" alt="image.png" />

**Comment by Dananji** [comment]
I adjusted the highlight color (the green for the search match that's underlined).

**Comment by Dananji** [comment]
I tested the color contrasts in `avalon-dev` with 3 different accessibility checkers. And do not get a contrast error for the highlights. Which highlight are you seeing this error on? Is is the green highlight on grey background or the green highlight on light-green background?

**Comment by elynema** [comment]
Ok. I hadn't seen a contrast error for the green highlighted text color. But we definitely don't want there to be a contrast error there, so good you resolved that.

 The contrast error is visible in the image I attached when you see this issue in Zenhub: https://app.zenhub.com/workspaces/avalon-5bff96674b5806bc2bf90276/issues/gh/avalonmediasystem/avalon/5753

It's the green background color for the active search highlight against the white background color of the page. But as I mentioned, I'm not sure this is actually an accessibility issue as the background color highlight is not technically required to identify the currently active search result?

**Comment by Dananji** [comment]
I'm not seeing a contrast error in any of accessibility checkers for that particular highlight. I'm using WAVE extension, Siteimprove extension in Firefox and Axe in Chrome.

**Comment by elynema** [comment]
Ok, I will go ahead and close this one.
