### ISSUE TITLE
SRT Captions Do Not Appear in Media Player

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5765]
# Description
SRT captions are not appearing in the media player when attached to a file. Tested in latest Safari, Firefox and Chrome.

# Example
- https://avalon-dev.dlib.indiana.edu/media_objects/5999n3392
- 
This item has the .srt captions file, and in network traffic https://avalon-dev.dlib.indiana.edu/master_files/qr46r082r/supplemental_files/294/captions seems like it's successfully returning the data transformed into VTT format, but the captions button does not appear in the media player.

# Done Looks Like
- SRT format caption files appear as captions in the media player when present for a file

**Comment by masaball** [comment]
Copying over from slack: It looks like the IIIF manifest still has the format as `text/srt` instead of `text/vtt` . This seems to prevent Ramp from properly handling the track. Changing the serialization to reflect that captions will always be streamed out as `text/vtt` should fix the issue.
