### ISSUE TITLE
[BUG] NoMethodError: undefined method `full_messages' for []:Array in SupplementalFilesController#create

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5784]
It appears that if the creation of a SupplementalFile fails (or under certain failure conditions) then this error gets raised.  It could be that our code is just wrong and we should be calling `full_messages` on something else or not at all.  I think we can determine this by writing some tests that exercise this bit of the code.

https://github.com/avalonmediasystem/avalon/blob/45088cb458928e3139dc45771936345fa8afc0a1/app/controllers/supplemental_files_controller.rb#L50

https://app.honeybadger.io/projects/54117/faults/82392074

## Done Looks Like
- [ ] Figure out the right method to call in this case
- [ ] Change the call to make sure errors when saving, or raising errors returns something to users besides a standard system error message
- [ ] Add test cases

**Comment by joncameron** [comment]
👍
