### ISSUE TITLE
Phrase Searching for Search Within (Content Search)

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5787]
# Description

Aviary automatically assumes a multi-term search entered in the search within context. Do we need to support phrase searching using quotes for the search within functionality on the media object page in Avalon?

This will depend on how Solr is queried.

Search will split terms on whitespace and search for individual terms in the transcript by default. Phrase searching could be possible using the highlighting feature in Solr, but not with term counts used in normal searching.

The handling of this will depend on how things go with the existing functionality. It may not be a hard requirement but will be something easier to move forward with when we see it in action.

### Example Item
https://avalon-dev.dlib.indiana.edu/media_objects/x920fw86z/manifest.json

### Example Query Values
- `"indiana university"` vs
- `indiana university`

## Questions To Be Answered
- [ ] How is the query sent to Solr?
- [ ] How are the results being returned (currently non-phrase)? 
- [ ] Is it harder to make Ramp be non-implicit phrase searching, or to make the back-end do phrase searching? (Back-end might be easier overall)
- [ ] What are we sending as escaped or sanitized input?
  - [ ] People should be able to enter punctuation without the app breaking
  - (rsolr has a sanitizing function already being used, quotes getting stripped out)
- [ ] What are the use cases? How might someone do search within, like searching for a phrase vs searching for two words in a transcript? 
 - on the item page, users are generally using search more like Ctrl+f browser search probably, so makes sense to do an implicit phrase search
- [ ] Gather examples of use cases
- [ ] How hard will it be to implement phrase searching with Content Search, as it currently works within in the JS Third Wave implementation?

* Searches done in Aviary:
  * https://indiana.sharepoint.com/:x:/r/sites/msteams_635f8a/_layouts/15/Doc.aspx?sourcedoc=%7B8B8A2AC4-CAAF-4DA1-A44E-B00891E49158%7D&file=Most%20Popular%20Search%20Terms%20Main%20Page.csv&action=default&mobileredirect=true

**Comment by joncameron** [comment]
Current query probably isn't respecting quotes in submitted requests.

**Comment by joncameron** [comment]
New issue: make content search API work with phrase searching

**Comment by joncameron** [comment]
See #5897 for testing, since this is implemented.
