### ISSUE TITLE
Change Default Web Upload File Size Limit

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5790]
# Description
Avalon's file size limit for web upload is currently set to a default of 2 GB. This seems unnecessarily low and and an artificial restriction at this point, and this value can be removed unless specified in the system config.

# Done Looks Like
- [x] Limit is disabled if [max_upload_size](https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957954807/Configuration+Files) is not present in config (:none)
- [x] Avalon respects :none value for web upload files (no rejection of files based on size in server file handling)

**Comment by cjcolvar** [comment]
It is currently possible for implementors to increase this via a setting but we could increase the default to something larger than 2GB.  Given our interest in removing the limit entirely in some cases, I wonder if we should add a configuration setting value like `-1` to disable the limit.

**Comment by joncameron** [comment]
Need to make sure the handling is working properly; multiple files uploaded at the same time through web upload might have an appended filename and could cause issues, but maybe not. Removing the limit completely would be a reasonable default at this point as well.

**Comment by elynema** [comment]
max_upload_size is commented out in settings.yml for avalon-dev. I don't see a message about max upload size in the UI, and I was able to start uploading a 3.8G file. 

I have not tested the :none option for max_upload_size.

**Comment by elynema** [comment]
Tested with max_upload_size: none on avalon-dev and seemed to work for 3.8G file.
