### ISSUE TITLE
Test latency of search within and transcript searching on full dataset from mco-staging

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5794]
# Description

Indexing and/or storing transcripts could cause changes in performance of the Solr index in ways we don't anticipate once we have a full dataset from MCO into the index. We would like to test in advance to make sure that change is not highly impactful in a negative way.

In addition, we want to be sure that implementing search within as IIIF content search, which introduces network latency, will not be too slow. We don't want to be blindsided by heavy searching of these documents in Solr if frequently/commonly used.

## Questions
- Adding transcripts to Solr: will that have a significant impact on performance?
- How performant is this in the context of search within, where we're searching the transcript document in Solr? What can we expect from the search query overhead?

# Done Looks Like
 - [ ] Benchmark some catalog searches in current mco-staging to have as comparison data
- [ ] Take a snapshot of mco-staging Solr index (roll back to snapshot after testing)
- [ ] Index transcripts within the Solr index (add database field, or do without?)
- [ ] Test Solr queries against mco-staging Solr and benchmark response times
  - [ ] Catalog search queries
  - [ ] Search within queries (Content Search)

**Comment by elynema** [comment]
Note that we would prefer to do this once we have our first release candidate.

**Comment by joncameron** [comment]
We could wait until re-indexing on mco-staging is complete, but it should be the case now that there are "has transcript" items in mco-staging now that are successfully indexed and ready for testing.

**Comment by cjcolvar** [comment]
Initial testing done in https://docs.google.com/spreadsheets/d/1Q61Udq-UuqV67KjlIGl0UhIJlYEafNEZSrodrgceYyQ/edit?usp=sharing

**Comment by elynema** [comment]
Chris will test times again this morning now that migration has bombed on mco-staging to see if that improves the response times. If not, take a look at whether the multiple queries for "Found in" results can be combined into a mega-query.

**Comment by elynema** [comment]
Chris discovered that "Found in" is already gathered into a single query. He was able to improve performance by reducing the calls out to Solr to check ability to access the limited access facets and using existing data already pulled back from Solr to form links to media objects, rather than querying out to speedyAF again.

PR:https://github.com/avalonmediasystem/avalon/pull/5963

Per his testing after the code re-work (not in the spreadsheet linked): But so far performance is tons better for searching expect for the sorting case. 100 results loads in 4s and 10 results in 1s.

**Comment by elynema** [comment]
Re-tested search on main site, selected items, collections, manage collections and all seemed to be working.
