### ISSUE TITLE
Declare IIIF content search service in media object manifest

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5795]
## Description
Per the Content Search API, the service can be declared on any resource; our scope will be at the canvas level.

### Example Block
```
  "service": [
    {
      "id": "avalon.xyz/media_objects/hd76s004z/master_file/ft848q60n/search",
      "type": "SearchService2"
    }
  ]
```

## Done Looks Like
- [x] Each canvas resource contains a search service block with the appropriate URI for the search service on that particular masterfile

**Comment by joncameron** [comment]
iiif_manifest already includes services that can be added at the canvas level.

**Comment by joncameron** [comment]
Cue and other information don't need to be defined up front and will be part of the service query result.

**Comment by joncameron** [comment]
Search service is showing up in manifests under canvas elements as expected:

```
      "service": [
        {
          "type": "SearchService2",
          "id": "https://avalon-dev.dlib.indiana.edu/master_files/2f75r800t/search"
        }
```
