### ISSUE TITLE
Chunking for Transcript Documents in Solr

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5812]
## Description
Carrying on from #5730, we'll need to decide how to put transcript documents into Solr to meet our needs for query matching. In particular, the documents should be broken up into chunks that can be returned in IIIF Content Search API responses, which will then be handled by the transcript search component in Ramp for display and navigation.

### Transcript types and chunking strategy
VTT and SRT: Time and text for each cue
Word and Plain Text: Paragraphs

## Done Looks Like
- [x] Example documents added to this ticket for the 4 main transcript types
- [x] Valid transcripts (types listed above) are indexed into Solr in a way that makes it possible to query and return in IIIF Content Search format responses
- [x] Figure out parsing on the documents for indexing

**Comment by masaball** [comment]
Here are the test files I created and have been using for the initial work on this issue (zenhub did not like the VTT or SRT extension so I uploaded them as `.txt` files). VTT and SRT use approximately the first minute of Lunchroom Manners captions. Plain Text and Docx use a chunk of the first chapter of the `spec/fixtures/public-domain-book.txt`:

[chunk_test.docx](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1BHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0fa4ce3fa812f3dd32c4f30687777200c0fb4c27/chunk_test.docx)

[chunk_test.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1RHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5ef301be5bd813824acfea4c2a283bede113dc8a/chunk_test.txt)

[vtt_chunk_test.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1hHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ccd26fbd4db6853315a4276d4c7617ef8f0b4f15/vtt_chunk_test.txt)

[srt_chunk_test.txt](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2pHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8928201c4f89031ffed88d7ef657e4f0b693dec3/srt_chunk_test.txt)
