### ISSUE TITLE
Query Change for Has Transcript and Has Caption Facets 

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5817]
## Description
Changing the facet query to populate based on absence of field, to avoid requiring a re-index for all items. This will allow "No" values to be populated by the absence of the field _or_ the existence of the explicit No value in the field, ensuring the counts are correct even when the explicit value hasn't been added to the index.

Also change facet query to look for presence of caption or transcript on the masterfile rather than on the media object itself. This means we don't have to maintain that data on the media object as well and don't have to reindex the media objects to add this functionality.

# Done Looks Like
- [ ] Facet counts for Has Transcript and Has Caption "No" values are marked the absence of the field _or_ the existence of the explicit No value in the field
- [ ]  Change facet query to look for presence of caption or transcript on the masterfile rather than on the media object itself

**Comment by joncameron** [comment]
This one could wait; could be moot if something else changing in 7.8 is requiring a re-index on media objects anyway.

**Comment by elynema** [comment]
@joncameron @masaball @cjcolvar I think we decided not to worry about this one? Were we already requiring some reindexing in 7.8?

**Comment by joncameron** [comment]
No longer relevant since we're already doing re-indexing as part of the current release.
