### ISSUE TITLE
Playlist LTI Share Links Not Working

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5823]
## Description
- Create a public playlist containing an item authorized for a Canvas course site
- Add the LTI share link for the playlist as an "External URL" module item (with "open in new tab" selected or not)
- When the module item is launched, the user is not authenticated and the user sees the homepage with error messages

## Error (after selecting the module item in Canvas with the LTI share link for the playlist)
![Screenshot 2024-05-06 at 12 13 45 PM](https://github.com/avalonmediasystem/avalon/assets/1406618/93caf3c1-754f-4cc5-ac92-10d532cab16b)

## Same Error for Inline Embed (not "open in new tab")
![Screenshot 2024-05-29 at 12 11 14 PM](https://github.com/avalonmediasystem/avalon/assets/1406618/a4bc96ce-5333-400b-a42c-7e4a9ebafee0)

## Done Looks Like
- [x] LTI Share URL for Playlists Work as an External Tool (not URL) within Canvas (Playlist is displayed as expected)
- [ ] Avalon documentation updated to indicate the difference when adding content to the LMS that needs the LTI POST credentials

**Comment by joncameron** [comment]
Q: Does this also occur when we don't set "open in new tab"?

**Comment by cjcolvar** [comment]
I tested this and found that the LTI share links work when added as an "External Tool" but not as an "External Url".  Is it important that these work as "External Url" specifically?  I think that the LTI params hash isn't being sent with "External Url" and that's why login fails.

**Comment by joncameron** [comment]
I'm going to update our documentation as Emily suggested and close this issue.

**Comment by joncameron** [comment]
https://samvera.atlassian.net/wiki/x/AQBBn
