### ISSUE TITLE
Poster Images Stretched In Media Player

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5832]
## Description
Videos that do not match the ratio of the media player are stretched to fit.

## Example
https://avalon-dev.dlib.indiana.edu/master_files/4m90dv50r
- thumbnail (https://avalon-dev.dlib.indiana.edu/master_files/4m90dv50r/thumbnail) is 640x360
- original media is 720x1280 vertical orientation

### Before Playback
![Screenshot 2024-05-16 at 11 52 52 AM](https://github.com/avalonmediasystem/avalon/assets/1406618/4bc2eeb6-a5fa-43ac-b365-2a891addf783)

### During Playback
![Screenshot 2024-05-16 at 11 53 08 AM](https://github.com/avalonmediasystem/avalon/assets/1406618/67164ebe-655e-4660-808e-0eb48bb8b4aa)

## Done Looks Like
- [ ] Thumbnails are saved in the original aspect ratio with the same pixel width and height as the source

**Comment by masaball** [comment]
@joncameron Can you retest this? I downloaded the media file from the linked item and have tried uploading it locally and into a new item on Avalon-dev and the thumbnail is created how I would expect:
<img width="607" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOU5JQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b26156aa0aa92af0910f023b05d0da58b4b593d9/Screenshot_20240607_133114.png" alt="Screenshot_20240607_133114.png" />

I also tested the results of creating a new thumbnail and that also generated the image with the proper aspect ratio. 

Maybe this example item was a weird one-off glitch?

**Comment by joncameron** [comment]
After testing it looks like this is due to the media file and how Avalon is storing metadata. 

Two files to demonstrate: https://drive.google.com/drive/folders/1tlKzE2l-p61uSveianBbb6Db54G1YO2s
- pexels-roman-odintsov-7691954 (correct ratio stored in record)
- IMG_4190 (shows as the correct ratio in media player but not in thumbnail)

IMG_4190.MOV is hevc taken from my iPhone. It's a vertical video, but inside the MOV it's being stored as a horizontal ratio, then the rotation is marked in item metadata. Here's FFprobe output for this file:

```
 Stream #0:0[0x1](und): Audio: aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 164 kb/s (default)
      Metadata:
        creation_time   : 2024-01-26T15:32:32.000000Z
        handler_name    : Core Media Audio
        vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](und): Video: hevc (Main 10) (hvc1 / 0x31637668), yuv420p10le(tv, bt2020nc/bt2020/arib-std-b67), 1280x720, 2302 kb/s, 30 fps, 30 tbr, 600 tbn (default)
      Metadata:
        creation_time   : 2024-01-26T15:32:32.000000Z
        handler_name    : Core Media Video
        vendor_id       : [0][0][0][0]
        encoder         : HEVC
      Side data:
        DOVI configuration record: version: 1.0, profile: 8, level: 3, rpu flag: 1, el flag: 0, bl flag: 1, compatibility id: 4
        displaymatrix: rotation of -90.00 degrees
        Ambient Viewing Environment, ambient_illuminance=314.000000, ambient_light_x=0.312700, ambient_light_y=0.329000
```

You can see this error clearly here: https://avalon-dev.dlib.indiana.edu/encode_records/942. 
The input is reported at 1280x720, but the derivatives are in the 720x1280 ratio. This is probably because Avalon is naively taking the width and height and not accounting for aspect metadata.

Updating the masterfile with correct metadata for these types of situations would be best, possibly based on the end output of the encoding process. Or maybe there's some way could get the computed actual width and height accounting for rotation and other factors, and store that in the record.

**Comment by elynema** [comment]
After transcoding, the aspect ratio is reflected accurately on the derivatives. If the aspect ratio on the master file doesn't match the info from the derivative file, prioritize the aspect ratio from the derivative.

**Comment by masaball** [comment]
After discussion, Chris and I decided that the specific circumstances that were causing this issue are edge case enough that we will not provide a backfill for existing items, at least for the moment. So the fix being implemented will only affect newly created items. In the upgrade documentation we will include instructions for fixing individual items from the console e.x. something along the lines of:

```
master_file = MasterFile.find(:master_file_id)
deriv = master_file.derivatives.where(quality_ssi: "high").first
master_file.display_aspect_ratio = (deriv.width.to_f / deriv.height.to_f).to_s
master_file.save!
```

**Comment by elynema** [comment]
@joncameron  This looks to me like it is working, but probably need Jon to re-test with his original media item.

**Comment by joncameron** [comment]
Working as expected for this media:
<img width="770" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeS9GQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2ca3334a770b624ead2555262be8bbfb52b5b300/Screenshot%202024-07-09%20at%2010.22.36%E2%80%AFAM.png" alt="Screenshot 2024-07-09 at 10.22.36 AM.png" />
