### ISSUE TITLE
[Regression] MediaObject json changes in Avalon 7.7

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5834]
Avalon 7.7 made all read-only requests be handled with data from Solr instead of Fedora including `/media_object/<id>.json`  While doing work on removing the ordered_aggregation relationship I found that https://github.com/avalonmediasystem/avalon/blob/c1a19e0a89fdea66ba40f7a1a93fd66c6dbe21aa/spec/controllers/media_objects_controller_spec.rb#L1191-L1211 was failing due to differences between the fedora objects and solr document.

- `record_identifier` isn't indexed so it is empty (`[]`) in Avalon 7.7 responses
  - Does `record_identifier` need to be in the media object json?
  - It gets passed in intercom so pushed records might be missing this, but ...
  - Whenever a mods document is saved it will add `record_identifier` if missing
  - Would it be better to not include in intercom push and instead always generate this for all MODS documents (new or pushed)?
- `avalon_resource_type` values are lower-case in Fedora but titlized in the solr document (https://github.com/avalonmediasystem/avalon/blob/c1a19e0a89fdea66ba40f7a1a93fd66c6dbe21aa/app/models/mods_behaviors.rb#L55)
  - This feels like a minor bug but one that could trip up services or processes which do exact string matching

## More Details
On MCO for the record Jon references above the difference in json when fetching from fedora vs. solr (speedy-af).  Unfortunately there are some more differences:
```
-   :avalon_resource_type=>["sound recording"],
+   :avalon_resource_type=>["Sound Recording"],
-   :identifier=>["AAY8650", "avalon:34123", "h53w827h39"],
+   :identifier=>["aay8650", "avalon:34123", "h53w827h39"],
-   :uniform_title=>["Bauernkantate"],
-   :statement_of_responsibility=>"J.S. Bach.",
+   :uniform_title=>[],
+   :statement_of_responsibility=>nil,
-   :format=>[],
-   :resource_type=>["sound recording"],
+   :format=>nil,
+   :resource_type=>["Sound Recording"],
-   :subject=>["Cantatas, Secular", "TBA"],
+   :subject=>["\n    Cantatas, Secular\n  ", "\n    TBA\n  "],
-   :record_identifier=>["http://127.0.0.1:8984/fedora4/rest/objects/avalon/nk/32/2d/62/nk322d627"],
+   :record_identifier=>[],
-   :bibliographic_id=>"AAY8650",
-   :bibliographic_id_label=>"other",
+   :bibliographic_id=>nil,
+   :bibliographic_id_label=>nil,
```

How critical are some of these? Which are surfaced in the UI vs which don't need to be represented?

## Done Looks Like
- [ ] Explore whether the fields above are the only ones that aren't matching
- [ ] Test against an example item in avalon-dev that has all available metadata fields filled
- [ ] Resolve missing or changed fields between Fedora and Solr

**Comment by cjcolvar** [comment]
Identifier is indexed downcased so that case will be standardized for searching like we do for purls.  Is it okay for this field to not match the input case?  Otherwise we could index the case sensitive value into a new solr field and use that in cases other than searching.  Master Files also have this attribute so we'd need to do the same thing there in order to return case sensitive values in the json response.  Of course we'd need to reindex all media objects and master files in order to populate this new solr field. We're already planning on reindexing media objects but not master files.

**Comment by joncameron** [comment]
If we can make it return in the case provided without a reindex, let's do that.
If we can't, it looks like it's appearing in the correct case in the edit and view pages, so this may be just in the json response.

**Comment by cjcolvar** [comment]
Outside of the JSON api responses it appears that `other_identifiers` is used in the IIIF manifest (show view) and the edit form while `identifiers` is only used for searching including permalink resolution.  In order to maintain case-insensitive searching and avoid a reindex of MediaObjects and MasterFiles, we can make the loss of the exact case of the identifier a known issue which we can address at a later time.

**Comment by joncameron** [comment]
Test item on dev with the same cat key: https://avalon-dev.dlib.indiana.edu/media_objects/j38606956.json
- Bibliographic ID and label are now present
- avalon resource type is OK as-is
- identifier is now an empty array (we could remove this at some point)
- record identifier has the fedora uri as expected
- statement of responsibility and uniform title are populated as expected
- subject doesn't have extra whitespace and newline characters
