### ISSUE TITLE
Enforce Identical Strings for avalon_resource_type in Solr and Fedora

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5836]
## Description
`avalon_resource_type` values are lower-case in Fedora but titlized in the solr document (https://github.com/avalonmediasystem/avalon/blob/c1a19e0a89fdea66ba40f7a1a93fd66c6dbe21aa/app/models/mods_behaviors.rb#L55)
This feels like a minor bug but one that could trip up services or processes which do exact string matching.

See https://github.com/avalonmediasystem/avalon/issues/5834 for original reported issue.

## Done Looks Like
- [x] Don't titlize avalon_resource_type values in Solr (make the index match Fedora)
- [x] Add helper method to Titlize in Blacklight display for resource type facet
- [x] `avalon_resource_type` in `media_objects/id.json` response is lower-case
- [x] Format facet on search results only has Titlized values (`Moving Image` and `Sound Recording`)

**Comment by elynema** [comment]
We should note what the done looks from a testing perspective. What should we see if it is working correctly as expected?

**Comment by cjcolvar** [comment]
@elynema I added two additional done looks like criteria which are easier to test.
