### ISSUE TITLE
Add migration to backfill parent_id onto existing supplemental files

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5855]
## Description
In the work done for transcript search, we added a new field to SupplementalFile to point to the parent object (`parent_id`). We will need some way to backfill this field on existing files.

@cjcolvar's suggestion:

>  I was thinking a rake task in avalon_migrations.rake  that would more or less be:
> 
> 1. Find all objects with supplemental files in solr
> 2. For each object's `supplemental_file_json_ssim` go through ids and load supplemental file, add `parent_id` and save unless `parent_id.present?`

Since `update_index` is run in a callback after updates, this backfill will likely also take care of getting existing transcripts indexed but we will need to test to make sure it works as expected.

## Done Looks Like
- [ ] Rake task created for parent_id backfill

**Comment by elynema** [comment]
@masaball Has this been run on avalon-dev yet, or will it work to test there? I'm thinking we should run this in an environment where we have identified an old transcript that is not yet indexed so we can verify the part about also getting existing transcripts indexed.

**Comment by masaball** [comment]
parent_id backfill has already been run on Avalon-dev, looking back through slack.

**Comment by elynema** [comment]
Ok, so let's leave this in QA until we have a PR on avalon-staging and then we can test there?

**Comment by masaball** [comment]
That sounds good :+1:

**Comment by joncameron** [comment]
@masaball What's the best way to test this now? The items I'm looking at with transcripts (ex: https://avalon-staging.dlib.indiana.edu/media_objects/79407x19s) already seem to be indexed—they're coming up with transcript hits in search.

**Comment by cjcolvar** [comment]
FWIW I ran the migration on staging and it worked perfectly as far as I could tell.  All items got indexed except for 7 which didn't have parent objects.

**Comment by joncameron** [comment]
I'm going to call it good and close this issue then.
