### ISSUE TITLE
Long Playlist Description Crowds Playlist Item List

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5857]
## Description
The playlist description field has been updated to allow for more content. The side effect of this in our current styling is that long descriptions take up all of the space in the sidebar component area. We can use the existing pattern found on the collections index description field, with See More and See Less links to show and hide the full amount of text.

## Example
![Screenshot 2024-06-10 at 8 23 46 AM](https://github.com/avalonmediasystem/avalon/assets/1406618/65451458-a388-469e-9761-bd45477f080c)

## Mockups
![shomore](https://github.com/avalonmediasystem/avalon/assets/1406618/94f7c9fc-ef82-4325-baee-228ef15d5a45)

![showless](https://github.com/avalonmediasystem/avalon/assets/1406618/8be7eca0-cff4-4191-a5a9-c62f393f90dc)

## Done Looks Like
When the playlist description is longer than 4 lines:
- [ ] "Show More" and Show Less" links display
- [ ] "Show More" displays all of the text in the description
- [ ] "Show Less" returns the text to a truncated display capped at 4 lines

**Comment by elynema** [comment]
@charumitraravi Can you QA this one?

**Comment by charumitraravi** [comment]
@charumitraravi 
The see more/see less feature works as expected. But for longer descriptions (~120 words, the Playlist items get hidden, and only the title is visible)

<img width="200" alt="Screenshot 2024-06-26 at 10 36 49 AM" src="https://github.com/avalonmediasystem/avalon/assets/52535309/10334856-d765-4255-a1a1-264a70488b54">

For more than 150 words, the text starts to overflow beyond the page edge. 
<img width="300" alt="Screenshot 2024-06-26 at 10 40 02 AM" src="https://github.com/avalonmediasystem/avalon/assets/52535309/07bbce0f-5760-4ce3-8649-ddbb7ad96ddf">

**Comment by elynema** [comment]
@masaball Looks like the Done Looks Like for this specific issue was resolved properly. However, the Done Looks Like does not describe behavior when the full playlist description is expanded, which we unfortunately still need to solve for. I can resolve this, but will need to create a new issue.
