### ISSUE TITLE
Delete does not cascade to child supplemental files

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5871]
# Description

When a media object or master file is deleted associated supplemental files are not removed, leaving orphan files in the system. Will leave orphaned supplemental files in database and on disk/in s3 bucket.

Delete callback may not work; may need to manually add a loop through supplemental files in the delete action in the controllers.

Old orphaned supplemental files could be cleaned up in the future by looking for files that aren't linked to any media files / master files.

# Done Looks Like

- [x] When a media object or master file is deleted, any associated supplemental files (caption, transcript, other supplemental file) should be deleted from ActiveStorage.

**Comment by elynema** [comment]
Not sure how often we are deleting things that have supplemental files, and this does not seem to be a new problem, so this is probably not a 7.8 requirement.

**Comment by joncameron** [comment]
* I added a file to an item
* confirmed the existence of the file in `/container-data/minio/supplementalfiles`
* deleted the item
* confirmed that the file was no longer in `supplementalfiles`
