### ISSUE TITLE
[BUG] Add to Playlist, Create Timeline, and Create Thumbnail buttons sometimes do not get enabled

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5885]
**Describe the bug**
Sometimes, the Add to Playlist, Create Timeline, and Create Thumbnail buttons never get enabled on page load. So far, this is seen on Android and iOS mobile devices, mostly after reloading the page numerous times.

Once this happens, reloading the page does not seem to re-enable the buttons. Starting playing the video and then reloading the page may re-enable the buttons.

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. As an example where we have seen this happen, go to https://avalon-dev.dlib.indiana.edu/media_objects/fj236208t on iOS/Safari or Android Chrome.
2. Reload the page repeatedly until you see that these buttons remain gray.

**Expected behavior**
These buttons should become enabled once the player is ready. We could conceivably enable them immediately on page load in the mobile context, where we seem to be having issues, but if they are enabled too early before the player is ready, they will have bad data and not work properly.

**Questions**

- How many people are using these 3 buttons in the mobile context? Can we determine this via Google Analytics to help figure out how much of an issue this is?

**Environment (please complete the following information):**
 - Device / platform: Android / iOS iPhone
 - Browser: Chrome / Safari
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
Is this issue associated with a specific release? [e. g. 7.6]

**Additional notes**
Any additional information or notes that may be helpful in diagnosing or fixing the problem.

**Comment by elynema** [comment]
Dananji is not sure how we could fix this better than we already have. The buttons are supposed to be on an interval that checks every second to see if the player is ready and then enable themselves.

**Comment by joncameron** [comment]
I tried on iOS Safari and Chrome on Android and could reproduce after many refreshes. I'll also check the analytics and add that information.

**Comment by joncameron** [comment]
Can no longer reproduce 👍
