### ISSUE TITLE
IIIF manifest link tweaks

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5887]
# Description

Currently, the link to the IIIF manifest is in the "Share this resource" panel labeled as "IIIF manifest". This is fine, but the IIIF manifest logo should be next to the "IIIF Manifest" label to help IIIF users find it. 

<img width="1257" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmlVQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--512b5bad06b421aa5adaa56f1dfad5e469761693/image.png" alt="image.png" />

# Done Looks Like 

- [ ] IIIF logo displays immediately following 'IIIF Manifest' label

See #5733 for the original work

**Comment by elynema** [comment]
Dananji did not add .json because the ID listed in the manifest does not have .json.

Ex: `"id": "https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p/manifest"`

**Comment by cjcolvar** [comment]
@elynema Either with or without the `.json` extension should work so we could switch to making the extension explicit if that's preferable.

**Comment by elynema** [comment]
@Dananji The iiif manifest logo is showing up really big in Chrome and Safari for me:

<img width="1402" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBdzJyQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b8b2f46b5d998fa5334c592b5f484859285de7b1/image.png" alt="image.png" />

**Comment by Dananji** [comment]
Did you try a hard reload of the page? It seems to be working for me.

**Comment by elynema** [comment]
I had to variously hard reload and delete cache, but it seems to look fine now.
