### ISSUE TITLE
Fix time cue parsing for SRT files

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5896]
# Description
Avalon is currently producing time fragments with the form `00:00:42.540,00:00:45,420` when processing SRT files for transcript searching. The second/millisecond delimiter in a time fragment identifier should be a period, so the second half of that cue, `45,420`, is improperly formatted.

`time_cue = split_text[1].sub(',', '.').gsub(/\s-->\s/, ',')` is the parser to edit the caption time cue formatting into fragment identifier format. Using `.sub` was an oversight in initial implementation, because it only subs the first match. We need to change it to a method that will sub out all matches.

# Done Looks Like
- [x] All millisecond delimiters in time fragments are `.` (change sub to gsub)
- [x] Add test case for parsing

**Comment by joncameron** [comment]
Time fragments look good now: https://avalon-dev.dlib.indiana.edu/master_files/q237hs039/search?q=bungle
