### ISSUE TITLE
Investigate how to remove old deleted supplemental files from index on avalon-dev

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5901]
Spinning this task off from #5892 for after 7.8 code is ready.

Supplemental Files that have been indexed and then deleted prior to implementation of the changes for #5892 are still going to be present in the index, which can cause errors and erroneous matches with the search service. This should only be a problem on Avalon-Dev, but we still need to come up with a strategy for cleaning the index.

Would doing a basic reindex clear out entries that no longer have a corresponding database object? Or do we need to do something more complex such as grabbing all the supplemental file ids from solr and directly checking the existence of each to determine if something should be removed from the index? Is there another approach that might be better?

# Done Looks Like
- [x] Investigate method
- [x] Execute cleanup/deletion

**Comment by joncameron** [comment]
Can wait until 7.8 RC or full release.

**Comment by masaball** [comment]
Running the `rake avalon:reindex` task did not remove any entries from the index. It looks like the task queries the database and then runs `update_index` on everything that gets returned. Since these files no longer exist in the database, the update script does not see them/know they exist to remove them.

Manually deleting the supplemental file solr documents and then forcing an index to repopulate would have been possible but seemed overkill to nuke the index and rebuild in this case.

I ended up running a query for solr documents with `has_model_ssim:SupplementalFile` and then checking for the existence of a database record:
```
ActiveFedora::SolrService.query('has_model_ssim:SupplementalFile', rows: 300).each do |file|
    begin
        GlobalID::Locator.locate(file['id'])
    rescue ActiveRecord::RecordNotFound
        ActiveFedora::SolrService.delete(file['id'])
    end
end
ActiveFedora::SolrService.commit
```
`ActiveFedora::SolrService.query('has_model_ssim:SupplementalFile', rows: 300).count` returned 252 entries before running the script and 234 entries afterwards, so there were not many orphaned index entries. 

`SupplementalFile.all.count` returns 260 items, so there are some files that have not made it into the index but that can be taken care of at another point.
