### ISSUE TITLE
Content search does not return all hits in a long plain text file

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#5915]
### Description

When searching `whitaker` in the https://avalon-dev.dlib.indiana.edu/media_objects/g158bh28p/ the [content search](https://avalon-dev.dlib.indiana.edu/master_files/s1784k75z/search?q=whitaker) response returns 188 hits.
While the transcript file named `transcripts(1) (1).txt` in the 5th section shows 192 (from browser search - `Ctrl`+`F`) hits.

This transcript is a `.txt` file with a long text block without any line breaks in it.

### Done Looks Like

- [x] Returns all 192 matches in the transcript

### Related
https://github.com/samvera-labs/ramp/issues/513

**Comment by joncameron** [comment]
👍
