### ISSUE TITLE
Short playlist description breaks display of description and tags

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5925]
# Description
<img width="403" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmJXQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f23eba901c1bfb3348abee4089b95d892ed40030/Screenshot_20240712_091713.png" alt="Screenshot_20240712_091713.png" />

# Done Looks Like
- [x] There should be a new row after the playlist description so following elements don't wrap to the same line as the description

**Comment by joncameron** [comment]
![Screenshot 2024-07-29 at 4 53 53 PM](https://github.com/user-attachments/assets/182b6977-39cd-4361-bb5d-93066624f311)
👍
