### ISSUE TITLE
Play Icon Misaligned

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5927]
# Description
The play icon that appears when the media isn't playing is out of alignment with it's circle container—it should be centered.

# Screenshot
<img width="748" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNDdYQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--77da298ad9d529a8066b9e416b66836ed08aea24/Screenshot%202024-07-12%20at%2012.00.31%E2%80%AFPM.png" alt="Screenshot 2024-07-12 at 12.00.31 PM.png" />

# Done Looks Like
- [ ] Triangular play icon is centered within the containing circle

**Comment by Dananji** [comment]
The related change was made in Ramp code. And the change applies for both play icon and volume slider thumb's vertical alignment (https://github.com/samvera-labs/ramp/issues/559).

Once it is brought into Avalon, appearance for both play icon and volume slider thumb in item view page, playlists, and embeds needs to re-tested.

**Comment by joncameron** [comment]
Looks good!
