### ISSUE TITLE
Provide a setting to change where Rack tempfiles are stored

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5948]
An issue was encountered with large file uploads where the Rack::Multipart middleware can end up producing large (7+ GB) temp files. Having these large temp files written during upload filled up the root file space, which can cause major issues with other functionalities on the server. 

The [default factory used to produce the temp files](https://www.rubydoc.info/gems/rack/Rack/Multipart/Parser#TEMPFILE_FACTORY-constant) writes to `Dir.tmpdir` which returns the Operating System's temp filepath. For Linux systems this will usually be `/tmp`. If the root system is constrained on storage, `/tmp` may not be large enough to handle these temp files. Rack::Multipart can take an environment variable, `env[RACK_MULTIPART_TEMPFILE_FACTORY]`, to override the default factory. @cjcolvar suggested that we could add an entry to Settings where implementers could define a filepath that is not storage constrained, then have an initializer which checks that entry and sets the environment variable as necessary.

# Done Looks Like
 - [x] setting in settings.yml file for the path to upload temp files
 - [x] setting should be commented out by default, which would fallback to default used by Rack
 - [x] parser should check that path exists, if not, fall back to default and put out error message to log file

**Comment by elynema** [comment]
Without this feature, we have to manually define the default temp file location in code for MCO.

**Comment by elynema** [comment]
This is merged to avalon-dev and using default values at this point in time. Mason and Chris tested this on mco-staging with a different temp file location and ensured that it did work there.

**Comment by masaball** [comment]
For testing: 
1. Check the logs for the POST request of the file upload: `Started POST "/master_files" for 140.182.72.228 at 2024-08-01 09:49:35 -0400`
2. A couple lines down from that will be an entry for the request parameters: 
```
Parameters: {
  "authenticity_token"=>"[FILTERED]", 
  "container_id"=>"br86bv39m", 
  "step"=>"file_upload", 
  "Filedata"=>[#<ActionDispatch::Http::UploadedFile:0x00007fcb8f2de260 @tempfile=#<Tempfile:/tmp/RackMultipart20240801-2491473-7yybef.mp4>, @content_type="video/mp4", @original_filename="lunchroom_manners.mp4", @headers="Content-Disposition: form-data; name=\"Filedata[]\"; filename=\"lunchroom_manners.mp4\"\r\nContent-Type: video/mp4\r\n">], 
  "id"=>"br86bv39m", 
  "original"=>""
}
```
3. Find the 'Filedata' entry: 
```
"Filedata"=>[
  #<ActionDispatch::Http::UploadedFile:0x00007fcb8f2de260 
  @tempfile=#<Tempfile:/tmp/RackMultipart20240801-2491473-7yybef.mp4>, 
  @content_type="video/mp4", 
  @original_filename="lunchroom_manners.mp4", 
  @headers="Content-Disposition: form-data; name=\"Filedata[]\"; filename=\"lunchroom_manners.mp4\"\r\nContent-Type: video/mp4\r\n">
]
```
4. Check the `@tempfile` entry in "Filedata": `@tempfile=#<Tempfile:/tmp/RackMultipart20240801-2491473-7yybef.mp4>`

The file path should match what has been set in the Settings.yml file. So it should read `Tempfile:/user/defined/path/RackMultipart...` instead of `/tmp/RackMultipart...`.

It does not look like this can be tested on core Dev or Staging because they are containerized using Minio/S3. Their file upload params include 
```
"selected_files"=>{"0"=>{"url"=>"s3://masterfiles/uploads/34dd8c9e-b99c-4d30-83a4-9c23dfe19b26/meow.wav"}}
```
instead of the tempfile construction.

**Comment by joncameron** [comment]
I'll leave this in QA for now and when mco-staging is updated to 7.8 retest and close.

**Comment by joncameron** [comment]
Check to make sure this config is in prod and test in prod, then close this issue.

**Comment by joncameron** [comment]
Tested successfully in production with an 8 GB file.
