### ISSUE TITLE
Test API Ingest for MP3s Served by Nginx in AWS

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5976]
# Description
Along with testing ingest, we'll need to test using the API with bibliographic import. Will bib import run automatically when an item is created with certain fields populated?

## Ingest Testing
- Use a large file to make sure derivative file size is not an issue for this setup of serving the stream
- Test bibimport capabilities for API-based record creation

For this project, Coha will set up for serving an SRU service that their Avalon can consume populating the record metadata.

Currently the changes to support MP3 streaming is on demo. We can test against demo as it runs the same 

## Examples on Demo
https://demo.avalonmediasystem.org/media_objects/9g54xh933

https://demo.avalonmediasystem.org/media_objects/cv43nx098 (non-functional)
> MP3 with "skip transcoding": This item is unable to be played because of missing streaming derivatives. Please contact support to report this error: avalon@dlib.indiana.edu. 

# Done Looks Like
- [x] Testing done against demo with ingest API, including ingest of metadata from bibimport
- [x] Testing done on different platforms to ensure streaming is functional for MP3 files
- [x] Evaluate whether this should be merged into core as well

**Comment by joncameron** [comment]
Notes from initial testing:
Some values that should have been populated in the API POST and PUT requests are not getting filled out in the data:
- percent_complete and status_code for the section
- mime_type for the derivative
 
Chris was able to fix the record I had created by API by manually changing fields in the console. More investigation needed about why this information isn't populating. It may be a regression or some other thing we'll need to implement to make sure all the values get set and so allow the media to be streaming from Video.js properly. With no mime type, Ramp throws a Video.js error and the media player is permanently grayed out.

**Comment by joncameron** [comment]
Need to test the API with bibimport yet since these records will need to do a metadata request upon creation to populate from the SRU service.

**Comment by elynema** [comment]
Need to ensure that the bibimport works now that there are multiple possible external sources to pull from.

**Comment by elynema** [comment]
@joncameron I am still confused about whether we've tested bibimport as part of API ingest. Can you clarify whether more testing is still needed here?

**Comment by joncameron** [comment]
Bibimport is tested and working as expected. The `import_bib_record` can be passed in and the API documentation is correct for importing metadata upon ingest from a configured service.

## Example
```
    "fields": {   
        "bibliographic_id": "19594027"
    },
    "import_bib_record": "true"
```
I'll close this now. We answered yes to merging this work into core, and the next step is setting auth up on these streams: #6002.
