### ISSUE TITLE
Rebase Fedora 6 Branch and Ensure All Tests Pass

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5977]
# Description
Getting the Fedora 6 branch that was previously created and worked on rebased to get current with 7.8/dev and fixing any failing tests afterward.

# Done Looks Like
- [x] Rebase existing branch with Fedora 6 work
- [x] Get all unit tests passing with Avalon on Fedora 6

**Comment by joncameron** [comment]
The other Fedora 6 Upgrade Epic issues can wait until this is done for further detail and pointing. Chris will take a look and add more details to Epic issues.

**Comment by joncameron** [comment]
- rebased Fedora 6 on Avalon 7.8
- develop is up to R3.3 and Rail 7.2, and we'll need to rebase onto the most recent develop
- rebasing will involve rebasing the other fedora 6 branches into the Samvera gems to their respective 7.2 branches

**Comment by joncameron** [comment]
Moved back to Current Sprint; need to look again at the Samvera gems. May make sense to wait until the end of the current sprint to incorporate more settled state of core component gems.

**Comment by elynema** [comment]
All core components got releases that needed releases except for Valkyrie and Bulkrax. Still have some things in labs that it would be good to get releases cut.

samvera-persona may need a release and may have some speedy-af changes that need a release.

Merge and cut an ActiveFedora branch - ActiveFedora 16 will be Fedora 6, not Fedora 4.
