### ISSUE TITLE
Fix generation of supplemental file download links in IIIF manifest

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5991]
Current generation of supplemental file download links causes all supplemental files, whether they are attached to a media object or master file, to have the route `/media_objects/#master_file_id/supplemental_files/#sup_file_id` in the rendering property of the IIIF Manifest. This is because the logic for the [rendering links is based on the current object](https://github.com/avalonmediasystem/avalon/blob/37cfbea682640796d9d33f4069c8a773537f581e/app/models/concerns/iiif_supplemental_file_behavior.rb#L35), which is always going to be a media object when building the manifest.

These improper links do not cause any issues with downloading the files. Looking at our routes, both endpoints redirect to `GET /supplemental_files/#sup_file_id` so the object id being wrong does not cause an issue. 

However, it would still be good to fix it so the proper parent object type is reflected for the supplemental files. This would be for consistency with the rest of our manifest generation and so humans looking at the manifest are able to see at a glance which supplemental files are attached to the media object itself and which are attached to master files.

# Done Looks Like
 - [ ] If a supplemental file is attached to a masterfile, rather than a media object, the manifest should contain a route to the supplemental file that references the masterfile instead of the media object (for the benefit of humans).

**Comment by joncameron** [comment]
👍
