### ISSUE TITLE
Improve authentication documentation

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#6006]
# Description

Existing documentation is here, but may be out of date: https://samvera.atlassian.net/wiki/spaces/AVALON/pages/1957954712/Adding+Okta+Authentication

Is it possible to create a general authentication page / documentation that describes the various ways to set up auth in Avalon?

**Comment by cjcolvar** [comment]
This looks like a duplicate of #6005.

**Comment by joncameron** [comment]
Merged this into #6005.
