### ISSUE TITLE
ExtractStillJob should use MasterFile#hls_streams instead of #stream_details

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#6015]
ExtractStillJob and possibly other places in the code can be optimized by removing the unnecessary overhead of #stream_details when only the HLS streams are needed. 

See https://github.com/avalonmediasystem/avalon/blob/37cfbea682640796d9d33f4069c8a773537f581e/app/models/master_file.rb#L592
Related https://app.honeybadger.io/projects/54117/faults/110786422

# Done Looks Like
- [x] Switch ExtractStillJob from using #stream_details unnecessarily

**Comment by elynema** [comment]
@joncameron @masaball Any ideas about how to QA this one?

**Comment by joncameron** [comment]
I tested this by creating a new item via web upload and testing thumbnail/poster creation, which worked as expected. I also created an object via API with only medium and low quality levels, and successfully created thumbnails using this object as well.
