### ISSUE TITLE
ExtractStillJob should fail gracefully when high derivative isn't present

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#6016]
# Description
If a section doesn't have a `high` derivative when the thumbnail/poster generation runs a NoMethodError is raised.  Instead it should drop down to a lower quality derivative or a more helpful and specific error should be raised.  There may also be a timing issue where the ExtractStillJob is enqueued too early and should instead only be enqueued after the high derivative has been saved and indexed.

See https://github.com/avalonmediasystem/avalon/blob/37cfbea682640796d9d33f4069c8a773537f581e/app/models/master_file.rb#L592
and https://app.honeybadger.io/projects/54117/faults/110501887

# Done Looks Like
- [x] ExtractStillJob should use the next available derivative stream if the high derivative is unavailable

**Comment by joncameron** [comment]
👍
