### ISSUE TITLE
Bad encode status shouldn't break encode dashboard

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#6018]
# Description
In production there were a few records which had received `nil` statuses for unknown reasons.  This caused the encode dashboard to break (index and view pages) when it attempted to display one of these records.  I manually fixed the statuses in the rails console but the dashboard shouldn't break when bad data is encountered.

See https://app.honeybadger.io/projects/54117/faults/101593057 and https://app.honeybadger.io/projects/54117/faults/110202917

- How should the dashboard display if there is a nil value?
- Is investigation needed for encodes returning nil?

# Done Looks Like
- [ ] 'nil' status for encodes doesn't prevent encode dashboard from rendering

**Comment by joncameron** [comment]
Potentially a bug in ActiveEncode or time drift between expected duration and ffmpeg output causing the nil state.

**Comment by elynema** [comment]
Mason demoed this and everything looked fine. @joncameron @cjcolvar @masaball I'm not sure if there is a good way to QA this?

**Comment by cjcolvar** [comment]
I think the only way to test this is to manually make bad data. If we don't want to spend that much time then maybe we could check that the encode dashboard works and call that good enough.  Over time in production we'll see if the problem ever comes up again.

**Comment by joncameron** [comment]
I replicated this by manually entering bad data for an encode record on dev. I confirmed that it displays as "null" now and doesn't block rendering of the table.
![Screenshot 2024-11-12 at 2 32 32 PM](https://github.com/user-attachments/assets/b82e28e4-eb62-43b3-8801-40c895089719)
