### ISSUE TITLE
Remove extra saves from Edit step models

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#6071]
Each step of the edit process has its own model which interfaces with the avalon-workflow gem to perform updates. In avalon-workflow, the [update method saves the object](https://github.com/avalonmediasystem/avalon-workflow/blob/1c188a2be9255ebd8b0b959f04dbf5f888715fb9/lib/avalon/workflow/workflow_controller_behavior.rb#L56). 

In all, or nearly all, of our models for the edit steps we explicitly save the media object as well. The [resource_description_step saves the media object twice in certain cases](https://github.com/avalonmediasystem/avalon/blob/37cfbea682640796d9d33f4069c8a773537f581e/app/models/resource_description_step.rb#L27) (the `update_attributes` method performs a save, immediately followed by another save after exiting the if/else block). I am unsure how much overall this would reduce timings, but we should try to remove the extra saves so that each step is only performing one save.

# Done Looks Like
- [ ] Remove extraneous saves from the edit step save actions

**Comment by elynema** [comment]
The old avalon_workflow gem was saving objects, but then avalon was also explicitly saving. Removed the secondary save from avalon code.

**Comment by abankhele** [comment]
I have tested the following actions: record creation, editing structure metadata, modifying access control, and adding a new section. All functionalities performed smoothly, with no issues encountered.
