### ISSUE TITLE
[BUG]  Playlist items display past footer on playlist page

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#6083]
# Description
On the playlist page, when there is a long list of playlist items, the box is displaying over top of the page footer. This was observed in both Chrome and Safari on desktop.

Example playlist: https://avalon-dev.dlib.indiana.edu/playlists/124

<img width="1392" alt="image" src="https://github.com/user-attachments/assets/54fa974f-bf5d-4c40-b66b-631ecf3959f4">

# Done Looks Like
- [ ] Playlist items listing matches the max height of the other Ramp elements

**Comment by joncameron** [comment]
![Screenshot 2024-10-29 at 2 53 11 PM](https://github.com/user-attachments/assets/cdacd173-d55a-4570-8a76-d8e7cac32cc0)
👍 Displaying as expected.

**Comment by elynema** [comment]
@joncameron @Dananji This is not working in Chrome:

<img width="1260" alt="image" src="https://github.com/user-attachments/assets/875dbadf-7e4b-47c6-ab2b-16ca4cb7b0c0">

**Comment by Dananji** [comment]
It is working for me in Chrome. Maybe it needs a hard reload?

**Comment by elynema** [comment]
@Dananji Can't believe my typo. Yes, it is working in Chrome. It is not working in **Safari**. I apologize for the mistake.

**Comment by Dananji** [comment]
On first page load the playlist items list was overflowing footer on a normal browser window. I checked the CSS to make sure it has the code change I made, and it was still on the old CSS. But opening it up on a private browser window seems to be displaying it with the latest CSS changes.

<img width="1019" alt="Screenshot 2024-10-30 at 2 56 13 PM" src="https://github.com/user-attachments/assets/fb5fdc1e-f426-4510-b452-79f74aa982f4">

@elynema Could you please try this on a private browser window to see whether you are able to see the same results?

**Comment by elynema** [comment]
@Dananji Yes, looks good now on all devices! I will close this.
