### ISSUE TITLE
[BUG] File Upload via Google Drive in Dropbox Option Fails

### ISSUE THREAD

**Issue by abankhele** [avalonmediasystem/avalon#6122]
**Describe the bug**
Uploading files from Google Drive via the "Dropbox" option fails and results in an error.

**To Reproduce**

1. Steps to reproduce the behavior, including the results:
2. Go to 'https://avalon-dev.dlib.indiana.edu/'
3. Select Manage Content.
4. Click Create an Item.
5. Choose Open Dropbox and set the source to Google Drive.
6. Select a video file to upload and click Submit.
7. Observe that the upload fails, and an error message is displayed.

**Expected behavior**
The media file should upload successfully without any errors.

**Screenshots/Screen Recording**

<img width="1346" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnZEQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--486e76e036d7b8308f30baed4da202200b2f8831/image.png" alt="image.png" />

**Environment (please complete the following information):**
 - Device / platform: Desktop
 - OS: macos
 - Browser : Chrome
- [x] avalon-dev
- [x] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Comment by elynema** [comment]
Seems to be be working fine for uploading both to an existing item and creating a new item. Thumbnails not being created for videos uploaded; reported as #6133.
