### ISSUE TITLE
[BUG] Incorrect links to items in search results

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#6124]
**Describe the bug**
Search results list items with the title or id of the item as a link into the detailed view of the item.  Blacklight by default makes this link `/catalog/:id`  but we have overridden it to use our controller `/media_objects/:id`.  The issue appears to be that Avalon's overrides to blacklight helpers are not getting loaded correctly.  This appears to only be an issue in the production environment and not development which leads me to believe it might be related to zeitwerk autoloading.

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. Go to avalon-staging.dlib.indiana.edu
2. Click on Browse
3. Hover over search result links and inspect the link url

**Comment by joncameron** [comment]
👍
