### ISSUE TITLE
Have Sharepoint return only joined Teams drives, not all accesible Sites

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#6126]
The initial implementation for supporting Sharepoint sites pulls in every site that a user has access to. In a large organization, this can result in an overwhelming amount of results that is very difficult for a user to parse and navigate through even after some level of filtering. By limiting results to only team drives that a user is explicitly a member of we should be able to get a more concise, relevant, and usable listing.

From #6111:
>There is a /me/joinedTeams endpoint in the microsoft graph API. For me this returns 3 options (Library Technologies, Digital Accessibility, and Eviada). Using the teams ID, we can query the /groups/{group_id}/drives series of endpoints to get the child drives and files for each specific team.

## Done Looks Like
- [x] Sharepoint integration in browse everything is reworked to use `joinedTeams` instead of `sites` endpoints

**Comment by elynema** [comment]
Tested for audio and video item. Uploaded fine and did create a thumbnail for the video item.

**Comment by joncameron** [comment]
Works great! I created #6135 for something I saw while testing, where the auth flow needed to be gone through twice. I'll test that again in a different environment as well.
