### ISSUE TITLE
Create General user documentation for end users

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#814]
### So that
An end user understands how to work with Avalon

### Done looks like
First draft of concise, clear documentation is written and published about core user - centered features.

TO BE Clarified : 

- [ ] General user interface
- [ ] Using playlists
- [ ] Public vs private items
- [ ] Accessing through an LTI (Maybe?). (E.g. Institutions often offer access through an LTI Like Canvas, Blackboard, etc. Access a campus LTI is different per institution. )
- [ ] add section for collection manager's guide on leases

**Comment by davidschober** [comment]
Note, POS, and Debs will own this type of user -facing documentation.

**Comment by joncameron** [comment]
This issue was moved to avalonmediasystem/avalon-planning#5
