### ISSUE TITLE
as a developer I want to create a staging and deploy method for mallorn

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#816]
### So that 

Our stage/test server is running the latest version of Avalon and has a better Bamboo deploy. 

Deploy process needs to be improved because the syadmins do not like needing to give developers root on another server just to push to mallorn 

I would like to consider implementing a stage branch that auto deploys to mallorn 

So then the workflow to add a new feature to Avalon would be: 

- New branch off develop, implement feature/bugfix/etc there 
- merge feature branch into develop and a developer reviews it on lancelot 
- if everything is good: merge develop into stage (like how we merge develop into master on release) 
- if things are not good, revert the merge into develop and continue working in the feature branch 

Then on release, we would merge stage into master rather than develop

### Done Looks Like:	

Mallorn has a better Bamboo deploy

- [x] Fix Bamboo
- [x] Setup new github staging branch
- [x] Setup Bamboo to deploy new branch to mallorn

**Comment by phuongdh** [comment]
New Bamboo now at http://pine.dlib.indiana.edu:8125/browse/AVALON
Mallorn is set to production and deploys off avalon/staging branch
