### ISSUE TITLE
Add Support for Ruby 2.3

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#823]
Per Chris S. the only change needed for devs to run 2.3.1 is to add support for mri_23 for byebug in our gemfile (see note in comments)

### Done looks like
- [ ] All Devs are using ruby 2.3.1.
- [ ] Support for mri_23 for byebug in our gem file

**Comment by csyversen** [comment]
I've been running avalon on 2.3 and 2.3.1 for around two months now and I believe cj colvar has too without having any issues. Can we change the done to 'all devs are using ruby 2.3.1' or something along those lines? (The only change we need to make is to add support mri_23 for byebug in our gemfile)

**Comment by davidschober** [comment]
Sure. Edited...
