### ISSUE TITLE
Easily edit/import structural metadata

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#828]
## Done looks like

An editor can edit structural metadata using a visual interface. The visual interface can possibly be as simple as "markers". [see 854](https://waffle.io/avalonmediasystem/avalon/cards/5759b9b6eb9d6a6401e6216f)

**Comment by davidschober** [comment]
[see 854](https://waffle.io/avalonmediasystem/avalon/cards/5759b9b6eb9d6a6401e6216f) can we use the same/similar method?
