### ISSUE TITLE
Document migration path from Variations

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#829]
## DONE

documentation on the tools and pathways that IU has used for the Variations migration is completed and published.  

- [x] Document specifically IU's migration
- [x] Documentation on import tools
- [ ] Jon Dunn signs off

**Comment by lealeelu** [comment]
This is what I have so far: https://wiki.dlib.indiana.edu/display/VarVideo/IU%27s+Example+Migration+from+Variations+to+Avalon
I don't think it will help going too much deeper into how we did it without people asking us for help. There's too much to cover to make an easy how-to guide.

**Comment by lealeelu** [comment]
I would like to add the documentation that https://github.com/avalonmediasystem/avalon/issues/1002 is going to create so that I can add a link to it.

**Comment by joncameron** [comment]
Chris will review, then Maria and I will look over it and send it to Jon for sign-off.
