### ISSUE TITLE
Develop AWS infrastructure diagram

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#832]
### So That
We begin to have ideas about how our AWS infrastructure could be laid out 

### Done Looks Like
AWS Infrastructure from Stanford and/or other institutions is examined and ideas regarding a potential infrastructure for Avalon is made.

- [ ] Talk to Stanford / Giarlo / Frost about their AWS infrastructure.
- [ ] Look at Hybox  work [Here's the link to the repo](https://github.com/hybox/aws).

**Comment by davidschober** [comment]
We should look at Sufia's work.

**Comment by davidschober** [comment]
This is the final/ polished diagram
