### ISSUE TITLE
Document NU costs for AWS to inform SAAS

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#835]
### Description
As part of our grant obligation, lyrasis should come up with a working pricing model for AWS SAAS. This is a reminder issue for us to get this information. 

### Blocked By
This is on Lyrasis—they will need to provide the pricing model. NU can add information as necessary from the pilot. 

### Tasks:
- [ ] NU to put notes from NU AWS Pilot
- [ ] Work with Lyrasis to make sure they produce a pricing model

**Comment by davidschober** [comment]
This should be scoped for pilot pricing.

**Comment by davidschober** [comment]
Note, after NU runs this in production we will have real figures.

**Comment by davidschober** [comment]
@joncameron I can document this for the next cycle. It's pretty straight forward.

**Comment by davidschober** [comment]
abandoning. Lyrasis is using a different model. NU will handle as part of sc presentation

**Comment by mcwhitaker** [comment]
@davidschober I thought we had agreed that NU's cost model would be used as part of the deliverables for the grant since it is the only example we have for AWS.

pinging @jwd for his input.
