### ISSUE TITLE
Investigate AWS setup best practices

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#846]
### So That
We have a better understanding of how we're we should set up our systems. 

### Done Looks like

We publish a first draft of an infrastructure map (or document)

- [x] look into hybox diagram and setup. https://github.com/hybox/aws
- [ ] touch base with hybox team
- [x] possibly push hybox setup button and see what happens.
- [x] Look at hybox setup [here's the diagram](https://cloud.githubusercontent.com/assets/111218/16077301/e8a0dc6c-32ef-11e6-80b4-e9e74c18973e.png)
- [ ] attach draft here

**Comment by phuongdh** [comment]
[Cloud Formation](https://cloud.githubusercontent.com/assets/1304657/16690702/26a19a1a-44f7-11e6-9f99-2ebad3256125.png)
