### ISSUE TITLE
Refine rubocop profile

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#851]
Second phase of Rubocop profile.

### Done looks like 
input on this one

**Comment by csyversen** [comment]
I think this will be brought up organically as we use rubocop more. Beyond getting rubocop to be part of our build/merge process, I don't think there's a defined second phase yet.

**Comment by davidschober** [comment]
Cool. Chris, feel free to close it as irrelevant. I put this in from Jira.

**Comment by csyversen** [comment]
closed!
