### ISSUE TITLE
As a user I want to delete markers

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#857]
### Done Looks Like

A marker should be able to be deleted by a user with confirmation.
(user clicks the Delete button for the marker)

- [x] controller action for delete_marker
- [x] UI element for delete marker in playlist show page
- [ ] test written

**Comment by davidschober** [comment]
## Done

A marker should be able to be deleted a by user with a confirmation. Base design on the  [design story](https://waffle.io/avalonmediasystem/avalon/cards/5759b9b6eb9d6a6401e6216f)
