### ISSUE TITLE
Loading Bookmarks Loads All Bookmarked Objects into Memory

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#861]
### Steps To Reproduce
- Select many items while browsing
- Click 'Manage Selected Items' in the navbar
  The page will take a very long time to load and display.
### Notes

This bug was originally written to reflect that the root cause was all of the selected items (bookmarks) being loaded into memory. Chris C mentioned that this might not truly be the case, and that further investigation would be needed. 
### Done Looks Like

Slow page load times are investigated. New stories are created if speed ups are possible.

**Comment by joncameron** [comment]
Not fixing this low priority bug to focus on Avalon 7.
