### ISSUE TITLE
Batch ingest fails ungracefully when email address doesn't map to avalon user.

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#862]

**Comment by davidschober** [comment]
It's a matter of sending and email to the default email if there is no email.

**Comment by davidschober** [comment]
Team, how hard would it be to get this one into 5.1.2?

**Comment by mschnaars** [comment]
Has this issue changed with the new batch ingest process?

**Comment by cjcolvar** [comment]
Yes, this is a case that is handled now.  When the user can't be found an email is sent to an administrator.

**Comment by davidschober** [comment]
closing as stale.
