### ISSUE TITLE
review documentation and develop plan for rewriting with multiple audiences in mind

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#863]
### So That:	
Librarians, decision makers, and developers feel that they understand what Avalon is and would be comfortable discussing these things with a developer that may not have any previous knowledge of Avalon.
### Done Looks Like:	
Generate an overview of documentation for popular or well-written open source projects, start to organize our existing content and create an outline of what we have and what we need.

**Comment by joncameron** [comment]
This issue was moved to avalonmediasystem/avalon-planning#2
