### ISSUE TITLE
Long filename extends out of player section

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#866]
See attached screenshot.

Reproduce:
1. Upload and ingest a file with long name
2. Go to Preview

Observed: filename extends out of its container and player section

Expected: filename is truncated or wrapped to fit

**Comment by davidschober** [comment]
![bugs](https://cloud.githubusercontent.com/assets/4803230/15943694/dbc49ce4-2e4f-11e6-812b-77de2b9f1012.png)

**Comment by cjcolvar** [comment]
@davidschober Could you verify this is fixed?

**Comment by davidschober** [comment]
/Users/dsc712/Desktop/Screen Shot 2016-06-22 at 11.10.39 AM.png

**Comment by davidschober** [comment]
It looks like this is mostly fixed. There's one small issue in the upper left corner <http://lancelot.dlib.indiana.edu/media_objects/avalon:sample-mahler-symphony-3>

screenshot in nex

**Comment by davidschober** [comment]
![screen shot 2016-06-22 at 11 10 39 am](https://cloud.githubusercontent.com/assets/4803230/16274356/e3169f90-386a-11e6-9608-2ca379b8fdee.png)

**Comment by cjcolvar** [comment]
Take another look at this please.

**Comment by davidschober** [comment]
I'm still seeing the funny overlapping of the now playing in chrome, safari and firefox on lancelot. If we're sinking too much time, we can fire off a new bug for the now playing indicator. (testing on lancelot)

**Comment by bkeese** [comment]
@davidschober : One more look please. I think it's good now.

**Comment by davidschober** [comment]
Woohoo! That looks great. Make it so.
