### ISSUE TITLE
verify documentation, switch flags

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#867]
Verify documentation on wiki and make final updates as necessary.

- [x] Update Wiki landing page 
- [x] verify and update [guide to configuration ](https://wiki.dlib.indiana.edu/pages/viewpreviousversions.action?pageId=513777120)
- [x] remove "vagrant" option from [technical doc](https://wiki.dlib.indiana.edu/display/VarVideo/Technical+Documentation)
- [x] verify and remove "in progress" note from [upgrading from 4 - 5](https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+4.0+to+Avalon+5.0)
- [x] verify and change release 4.0 to release 5..0 on [VM image installation instructions](https://wiki.dlib.indiana.edu/pages/viewpage.action?pageId=515277053)
- [x] verify and change release 4.0 to release 5.0 in note on [Manual Puppet Install](https://wiki.dlib.indiana.edu/display/VarVideo/Manual+Puppet+Install)
- [x] verify and change release 4.0 to 5.0 on [Manual Install Instructions](https://wiki.dlib.indiana.edu/display/VarVideo/Manual+Installation+Instructions)
- [x] publish release notes and send URL to Debs

**Comment by davidschober** [comment]
@joncameron 

Can you let Debs and I know when this is done?

**Comment by joncameron** [comment]
@davidschober Yep, I'll let you know. Working on finishing it up now, but probably will be done sometime this weekend.
