### ISSUE TITLE
start using waffle in an organized way, including automated workflow syntax

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#868]
Devs should review waffle best practices and start using the automated workflow syntax so we don't need to move cards. 

[recommended workflow](https://github.com/waffleio/waffle.io/wiki/Recommended-Workflow-Using-Pull-Requests-&-Automatic-Work-Tracking)

[FAQ with helpful hints](https://github.com/waffleio/waffle.io/wiki/FAQs)

- [ ] Create a project to contain administrative issues (server upgrades, OOO, etc) so as not to flood the avalon github issues
- [ ] Move current non-code issues into aforementioned repo (https://github-issue-mover.appspot.com/)
- [ ] Create a gist cheatsheet of syntax for ease of use (or find a current one)

**Comment by joncameron** [comment]
New repo could be called something along the lines of "Avalon planning", "POs say the darndest things", etc.

**Comment by davidschober** [comment]
Just to be clear. The private repo would only be for internal notes, etc. User stories/ features would still be public in preparation for community sprints.
