### ISSUE TITLE
begin research into Fedora 4

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#878]
So developer developers without fedora 4 knowledge feel generally caught up. 

Done looks like

Developers feel like they can contribute to technical stories.

- [ ] Run through migration tool from previous sprint on local dev machine
- [ ] get latest version of jetty w/ fedora and solr on local dev machine

**Comment by joncameron** [comment]
This issue was moved to avalonmediasystem/avalon-planning#1
