### ISSUE TITLE
Captions intermittenly don't show up in player

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#880]
Steps:
1. Load an item with captions, ie http://lancelot.dlib.indiana.edu/media_objects/avalon:sample-beginning-responsibility-lunchroom
2. Try refreshing or logging out

Observed: CC button shows in player then quickly disappears. No captioning during playback

Bug does not seem to be happening with Wowza instead of Red5.

**Comment by bkeese** [comment]
This appears to be a race condition between the check for loaded caption files and the request/response time for loading a caption file.
