### ISSUE TITLE
create a fedora 4 dev avalon (Greenfield)

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#901]
### Done Looks Like
Testing dev server that we can deploy our ongoing work is stood up...

A working Fedora 4 based instance of Avalon controlled by Bamboo Deploy.  Feature parity with Lancelot but based on Fedora 4

- [x] Fedora 4 Installed
- [x] Solr 6.1 Installed
- [x] Matterhorn Installed
- [x] Red5 or Wowza Installed For Streaming
- [x] Ability to deploy Avalon to this server via Bamboo 
- [x] Documentation on installing Fedora 4 and Solr 5, namely how it differs from our current practice.

**Comment by phuongdh** [comment]
https://wiki.dlib.indiana.edu/display/VarVideo/Setup+a+server+for+Hydra+10+development
