### ISSUE TITLE
look at fedora migrate gem

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#902]
### Done Looks Like

An understanding of the Fedora Migrate Gem and the Migration Interest Group

- [ ] Review Fedora Migrate Gem and changes to it since we last tested it
- [ ] Reach out to the Migrate Interest Group to learn about experiences of others

**Comment by joncameron** [comment]
This will be timeboxed... 1 or 2 people going over the code history.

**Comment by davidschober** [comment]
It looks like the migrate gem is the pick.
