### ISSUE TITLE
upgrade hydra and active fedora

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#903]
### Done Looks Like

A deployable version of Avalon using either Hydra 9 or 10.  All tests do not need to pass, the App just needs to be testable.  

- [x] Determine if WebALC/RightsMetadata requires movement to Hydra 9 or Hydra 10 (refs #905)
- [ ] Create deployable branch

**Comment by joncameron** [comment]
Timeboxed to an 8- reassess if needed.
