### ISSUE TITLE
Knowledge spike: Migration Gem

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#906]
### Done Looks Like

A working and documented gem for migrating content from a Fedora3 to Fedora4 instance.

- [x] get gem loading in avalon context migrate gem stood up
- [ ]  Ensure Old Fedora3 pids are preserved (refs #836)
- [ ]  issues that occur from that. duped with #1310

**Comment by joncameron** [comment]
1st step: Stand up the generic migrate gem
