### ISSUE TITLE
Make Batch Ingest Work

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#907]
Timeboxed to test an fix issues as they appear. If the amount of issues or fixes goes beyond the timebox, new issues will be created. 
### Done Looks Like
- [ ] Manually test that Batch Ingest works
- [ ] Batch ingests of content into Fedora 4 based Avalon are tested
- [ ] New issues squashed or created as new issues

**Comment by davidschober** [comment]
Validate after active encode fix #1306

**Comment by cjcolvar** [comment]
Changes have been merged and deployed to spruce which should fix this. Please retest.

**Comment by anirudhpillai16** [comment]
Batch ingest works fine hence closing this issue.
