### ISSUE TITLE
Package 5.0.1 Release

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#915]
### Done Looks Like
- [x] Bump footer version number to 5.0.1
- [x] Package OVA with Avalon 5.0.1
- [x] Push OVA to server for users to download
- [x] Test that OVA works
- [x] Update http://www.avalonmediasystem.org/downloads/avalon-installer-flat.tar.gz
- [x] Symlink latest version of OVA to http://www.avalonmediasystem.org/downloads/avalon-vm.ova 
- [x] Update Wiki landing page 
- [x] Update Wiki documentation @joncameron 
- [x] publish release notes and send URL to Debs @Debs4Avalon

**Comment by davidschober** [comment]
- [ ] Update Wiki landing page 
- [ ] verify and update [guide to configuration ](https://wiki.dlib.indiana.edu/pages/viewpreviousversions.action?pageId=513777120)
- [ ] remove "vagrant" option from [technical doc](https://wiki.dlib.indiana.edu/display/VarVideo/Technical+Documentation)
- [ ] verify and remove "in progress" note from [upgrading from 4 - 5](https://wiki.dlib.indiana.edu/display/VarVideo/Upgrading+Avalon+4.0+to+Avalon+5.0)
- [ ] verify and change release 4.0 to release 5..0 on [VM image installation instructions](https://wiki.dlib.indiana.edu/pages/viewpage.action?pageId=515277053)
- [ ] verify and change release 4.0 to release 5.0 in note on [Manual Puppet Install](https://wiki.dlib.indiana.edu/display/VarVideo/Manual+Puppet+Install)
- [ ] verify and change release 4.0 to 5.0 on [Manual Install Instructions](https://wiki.dlib.indiana.edu/display/VarVideo/Manual+Installation+Instructions)
- [ ] publish release notes and send URL to Debs
