### ISSUE TITLE
I want to import my playlists into Avalon

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#920]
### Done Looks Like

A page where the user can upload a variations playlist file and have an Avalon Playlist automatically generated from it.

- [ ] Upload page designed
- [ ] Function for converting playlistxml (variations) to playlist model in SQL
- [ ] tests for conversion of playlists
- [ ] user friendly errors that are easy for them to pass to support

**Comment by joncameron** [comment]
### Design for the page

#### Text above the items
"Errors were encountered with the following items.
"The following errors were encountered when attempting import."

#### List of Items
Only the items which had errors are shown. The current style for the items  stay as they are:
* Red circle with an X next to the item.
* The item's name.
* Text describing the error.

The error text "Master file is required" needs to be changed to "No matching item found" to make more sense to users.  All of the other error messages can stay the way they currently are.

#### Text below the list of items

"This playlist is still able to be imported but will not contain the items listed above. Other errors may also be present  and may contain other errors. 

For technical assistance regarding these error messages please _use our contact form_." ('use our contact form' is a hyperlink to the 'comments' page).

Red Cancel button (text: "Cancel") with the Import button directly to the right.
