### ISSUE TITLE
Create multi-threaded migration script for Fedora and Solr

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#927]
### Done Looks Like

Once the single-threaded migration is done, @carrickr can talk through the parallel gem.  
- [ ] create documentation for users on how to tune so they don't blow up machine by spawning Fedora and SOLR threads. 
- [x] Re-indexing is multi-threaded
- [x] The script contains the ability to specify the number of threads to use

**Comment by davidschober** [comment]
@carrickr to talk through it at a swarm, then decided how to attack it.

**Comment by joncameron** [comment]
@carrickr Has any work been done on this yet? Or should this issue be mainly for doing the testing and documentation?

**Comment by davidschober** [comment]
@cjcolvar you grabbed this as part of sprint 126 it looks like. I'll add it to the milestone.

**Comment by cjcolvar** [comment]
:+1:

**Comment by davidschober** [comment]
@cjcolvar it looks like this got merged in, this is done, correct?

**Comment by cjcolvar** [comment]
I was leaving this open because documentation hasn't been written yet.

**Comment by davidschober** [comment]
Sounds good.
