### ISSUE TITLE
MBK OOO 7/7

### ISSUE THREAD

**Issue by mbklein** [avalonmediasystem/avalon#930]

**Comment by mcwhitaker** [comment]
This issue was moved to avalonmediasystem/avalon-planning#15

**Comment by mcwhitaker** [comment]
This issue was moved to avalonmediasystem/avalon-planning#17

**Comment by mcwhitaker** [comment]
This issue was moved to avalonmediasystem/avalon-planning#18

**Comment by mcwhitaker** [comment]
This issue was moved to avalonmediasystem/avalon-planning#19
