### ISSUE TITLE
As a metadata expert I want automated data validation

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#939]
### So That

We can verify that Datastreams in Fedora 3 correctly became Bitstreams in Fedora 4 and we have high confidence that datastreams migration was successful.
### Done Looks like
- [ ] Checksum validations have run and problems are identified in a report.
- [ ] verify the old fedora3 pid was preserved
- [ ] Items in fedora 3 exist in fedora 4 - problems listed in a report
- [ ] New issues written as needed
- [ ] the migration tool provides whoever runs it with an array of all fedora3 pids migrated
- [ ] the documentation tells users to take the fedora3 pid list (item above) and compare it to the pid list in their current fedora3 repo

**Comment by davidschober** [comment]
For a first run if we have a report that just says "these items didn't make it" should fine.

**Comment by davidschober** [comment]
@carrickr says it's "eeeeeasy"

**Comment by carrickr** [comment]
@davidschober I'll knock it over on the bus ride home!

**Comment by carrickr** [comment]
- [ ] identify all files that are brought over are checksums
- [ ] verify the old fedora3 pid was preserved
- [ ] create a report of problems

**Comment by davidschober** [comment]
Note, this will stay in the sprint but be picked up as part of the migration tool itself. This will act a checklist.
