### ISSUE TITLE
Multiple instances of  same video are created if user keeps on clicking upload button while video is uploading.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#940]
Browsers:- Chrome 50, IE11, Firefox 47, Safari 8

Steps to Reproduce

1. Launch mallorn.dlib.indiana.edu on browser.
2. Login with valid credentials and navigate to manage content.
3. Choose existing collection and create an item.
4. Upload any video from local computer.
5. Click upload 4-5 times while video is uploading.

Observe multiple instances of same video appear under Associated files once uploading finishes.

**Comment by anirudhpillai16** [comment]
![upload_issue](https://cloud.githubusercontent.com/assets/15963595/16457447/8ab90714-3de9-11e6-8e23-770a9c35c1ec.jpg)

**Comment by davidschober** [comment]
Per discussion, we will be changing the state of button to "loading" while video is loading.
