### ISSUE TITLE
As a user I want to see marker positions on the media player

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#941]
### So That
It's easy for a user to visually get an idea of where markers lie in the timespan of a playlist item.

### Done Looks Like

 An icon or icons appear on the media player indicating where on the timeline Marker points are (see designs below).

If there are multiple markers close together they will simply be drawn on top of each other. Differentiating markers that are close in time point will be done by way of the table below the media player.

_Example Images_
![markers revised](https://cloud.githubusercontent.com/assets/1406618/16689448/025394d4-44f1-11e6-88b5-b66127067757.png)

![marker_example](https://cloud.githubusercontent.com/assets/1406618/16468200/b47c582e-3e18-11e6-8a93-cfaa0a975994.png)

![marker_example2](https://cloud.githubusercontent.com/assets/1406618/16468203/b825258c-3e18-11e6-94ae-ab634da173f9.png)
The first marker in the above image would be representing three markers that are very close together in Time values.

**Comment by davidschober** [comment]
We are re-scoping to just add markers. Grouping and clickable markers will be a separate story.
