### ISSUE TITLE
As a user I want the option to begin playback from a Marker position

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#942]
### So That
Users can more quickly play back from a Marker position. Currently playback from a Marker will only begin if the media is already being played, and the Marker's name is clicked, moving the playhead (playing back from that point, since the media player was already playing back).

### Done Looks Like
A Play icon is visible to the left side of the Marker's Name in each row of the table below the media player that contains Markers. Clicking this Play icon will begin playback at the Marker's Time value.

_Mock-up example image:_
![marker_list_playicon](https://cloud.githubusercontent.com/assets/1406618/16467103/d61454a0-3e13-11e6-8a40-f50535873a42.png)

**Comment by davidschober** [comment]
need to discuss with @joncameron

**Comment by davidschober** [comment]
Abandoned we decided that this adds an unnecessary redundant actions.
