### ISSUE TITLE
As a Variations user I want a tool in Avalon to import my Variations Bookmarks

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#946]
## So That 
I can use my Variations bookmarks in Avalon.

# Done looks like
- [ ] A tool that reads the exported Variations bookmarks in json format and imports the bookmarks creating avalon users in the process if the user does not exist.

**Comment by davidschober** [comment]
We decided to only import active variations users so as to not introduce too much noise.

**Comment by bkeese** [comment]
The tool is implemented as a rake task to be run  by a system administrator. Before the tool is run, Variations content must have been migrated from Variations to Avalon, and the Variations bookmark export script must have been run to generate the JSON bookmark file.
