### ISSUE TITLE
Model Investigation

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#957]
Explore and choose whether we can make the investment now or whether we want to pull in deprecreted code related to model getter/setters

This is a timebox.

**Comment by davidschober** [comment]
@mbklein and @csyversen after working on this one can you grab fedora 4 model stories for this sprint that make sense?

**Comment by mbklein** [comment]
I think the best stopgap measure before we refactor the models would be to use delegators where possible, and a mixin of getter/setters where we can't. We don't necessarily need to to be as abstract and indirect as the legacy AF code. Just something that will get the job done cleanly.
