### ISSUE TITLE
[Smartphones Specfic]:- entire duration is not visible under time when user accesses edit option under marker.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#965]
Environment:- Android/iOS Devices (expect  tablets and iPad)

Steps to Reproduce

1. Launch Avalon on any device.e.g:- iPhone6 and safari.
2. Login with valid credentials and navigate to playlist.
3. Access any playlist with marker.
4. Access marker under video and access edit button.

Observe duration under time is partially visible.

**Comment by anirudhpillai16** [comment]
![landscape_time](https://cloud.githubusercontent.com/assets/15963595/16812436/16b30c3a-48fb-11e6-8cdb-fad9bb472412.jpg)
![portrait_time](https://cloud.githubusercontent.com/assets/15963595/16812437/16b53bc2-48fb-11e6-85bf-560f638e64cb.jpg)

**Comment by joncameron** [comment]
It's now slightly more visible, but not fully—I think it's a good compromise though. And the action icons shrinking down for smaller size layouts look great. 
![screen shot 2016-07-18 at 11 10 37 am](https://cloud.githubusercontent.com/assets/1406618/16919661/a415ddd8-4cd8-11e6-9b2a-6cc6547d360b.png)
