### ISSUE TITLE
Tabbing on "Create New Collection" can escape modal  scope

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#969]
### Steps to reproduce
- Click "Create Collection" button on the admin collections page
- Backtab one or more times

The focus escapes the modal—goes first to "Create Collection" button, then the Avalon Search field.
### Test Environment

Firefox 47 on OS 10.11, Lancelot running 5.x
### Done Looks Like

Backtabbing does not escape the modal form area—it  instead stops at the X in the upper right corner.

**Comment by davidschober** [comment]
closing as stale.
