### ISSUE TITLE
[Web Specific]:- Last video or audio under playlist doesn't return to it's default state and shows playing even after reaching end of time.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#971]
Environment: - Safari 8, Firefox 47, Chrome 50, IE11, Edge 11
lancelot.dlib.indiana.edu
mallorn.dlib.indiana.edu

Steps to Reproduce
1. Launch URL on any browser mentioned above.
2. Login with valid credentials and access Playlists from nav bar.
3. Access and play any playlist.

Observe last video shows playing even after reaching it's end time and doesn't return to its default state. If user clicks pause, video  returns to it's original state but doesn't play again if accessed.

Note:- 1. This issue is not reproducible on Smartphones or Tablets.  (video returns to its default state automatically)
2. This issue is not reproducible on paw paw.

Please refer link below for video:

https://drive.google.com/drive/u/0/folders/0B-Lv-tiSRqEuMEtlMkYyRkVUYlE

File name:- Last_item_Playlist

Done Looks like

Last Video should return to it's original state and user should be able to play the video again.

**Comment by davidschober** [comment]
see 
#1067

**Comment by davidschober** [comment]
closing, stale.
