### ISSUE TITLE
As a developer I want to have a team meeting regarding actor nouns

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#993]
## Done Looks Like

Look in to how CurationConcerns and other Ruby projects use the nouns like presenters, renderers, etc.  Decide which ones we might want to use and what would move from models and controllers into these new nouns.

**Comment by davidschober** [comment]
Chris Colvard, Michael and Carrick to meet Monday 8/8 after standup

**Comment by carrickr** [comment]
Result of the meeting is a decision to avoid actor nouns in 6.0.  As we alter the models to use Fedora 4 we'll mark code that could be refactored into nouns with code comments, but the refactoring will not occur until 7.0.
