### ISSUE TITLE
Refactor Avalon configuration

### ISSUE THREAD

**Issue by mbklein** [avalonmediasystem/avalon#998]
The following files need to become optional/obsolete:

* `authentication.yml`
* `avalon.yml`
* `database.yml` 
* `fedora.yml`
* `lti.yml`
* `matterhorn.yml`
* `role_map_ENVIRONMENT.yml`
* `solr.yml`

**Comment by mbklein** [comment]
Most of them (`database`, `fedora`, `matterhorn`, `solr`) can be done simply with environment variable substitution. The others are more complicated and may require more sophisticated serialization or rethinking of how to store their values.

**Comment by mbklein** [comment]
Paths pointing to executables should be replaced by symlinks into `[RAILS_ROOT]/bin`

**Comment by mbklein** [comment]
This set of environment variables covers all of the current values in `avalon.yml`, but needs to be wired up:

```
APP_NAME=avalon
FEDORA_NAMESPACE=avalon
AVALON_URL=http://avalon:80/
DROPBOX_PATH=/srv/avalon/dropbox
DROPBOX_URI=sftp://localhost${DROPBOX_PATH}
MEDIAINFO_PATH=/usr/local/bin/mediainfo
STREAM_BASE=/streamfiles
STREAM_SERVER=wowza
STREAM_TOKEN_TTL=20
STREAM_RTMP_BASE=rtmp://streaming/avalon
STREAM_HTTP_BASE=http://streaming:1935/avalon/_definst_
STREAM_DEFAULT_QUALITY=low
SYSTEM_GROUPS=administrator,group_manager,manager
MASTER_FILE_STRATEGY=move
MASTER_FILE_PATH=/masterfile_storage
FFMPEG_PATH=/usr/bin/ffmpeg
CONTROLLED_VOCABULARY=config/controlled_vocabulary.yml
EMAIL_COMMENTS=avalon-comments@example.edu
EMAIL_NOTIFICATION=avalon-notifications@example.edu
EMAIL_SUPPORT=avalon-support@example.edu
SMTP_ADDRESS=smtp.example.edu
SMTP_PORT=587
SMTP_DOMAIN=example.edu
SMTP_USER_NAME=foo
SMTP_PASSWORD=blargh
SMTP_AUTHENTICATION=plain
SMTP_ENABLE_STARTTLS_AUTO=false
SMTP_OPENSSL_VERIFY_MODE=client_once
```

**Comment by davidschober** [comment]
We would also want something that spits out all of these variables. Maybe a Rake task.

**Comment by davidschober** [comment]
Per MBK Rails looks for an environment variable first and falls back to a YML. So theoretically you can fall back on the config in dev. Not ideal, but one could. We should code it so it can use environment variables.

**Comment by carrickr** [comment]
In rails console, ENV will show all environment variables, ex:

ENV
 => {"rvm_bin_path"=>"/Users/carrickr/.rvm/bin", "TERM_PROGRAM"=>"Apple_Terminal", "GEM_HOME"=>"/Users/carrickr/.rvm/gems/ruby-2.1.7", "TERM"=>"xterm-256color", "SHELL"=>"/bin/bash", "IRBRC"=>"/Users/carrickr/.rvm/rubies/ruby-2.1.7/.irbrc", "TMPDIR"=>"/var/folders/fp/9t76spcs2nl40dx36mxp2ccdts78wv/T/", "Apple_PubSub_Socket_Render"=>"/private/tmp/com.apple.launchd.Xo8mCaALyI/Render", "TERM_PROGRAM_VERSION"=>"361.1", "MY_RUBY_HOME"=>"/Users/carrickr/.rvm/rubies/ruby-2.1.7", "TERM_SESSION_ID"=>"0DEFF8B8-12B8-4C9F-B8BE-983996C4AC2B", "rvm_stored_umask"=>"0022", "USER"=>"carrickr", "_system_type"=>"Darwin", "rvm_path"=>"/Users/carrickr/.rvm", "SSH_AUTH_SOCK"=>"/private/tmp/com.apple.launchd.Q322OAMDLS/Listeners", "__CF_USER_TEXT_ENCODING"=>"0x7593A39B:0x0:0x0", "rvm_prefix"=>"/Users/carrickr", "PATH"=>"/Users/carrickr/.rvm/gems/ruby-2.1.7/bin:/Users/carrickr/.rvm/gems/ruby-2.1.7@global/bin:/Users/carrickr/.rvm/rubies/ruby-2.1.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/carrickr/.rvm/bin", "rvm_loaded_flag"=>"1", "PWD"=>"/Users/carrickr/avalon", "LANG"=>"en_US.UTF-8", "_system_arch"=>"x86_64", "XPC_FLAGS"=>"0x0", "_system_version"=>"10.11", "XPC_SERVICE_NAME"=>"0", "rvm_version"=>"1.26.11 (master)", "HOME"=>"/Users/carrickr", "SHLVL"=>"1", "LOGNAME"=>"carrickr", "GEM_PATH"=>"/Users/carrickr/.rvm/gems/ruby-2.1.7:/Users/carrickr/.rvm/gems/ruby-2.1.7@global", "RUBY_VERSION"=>"ruby-2.1.7", "SECURITYSESSIONID"=>"186a6", "rvm_user_install_flag"=>"1", "_system_name"=>"OSX", "_"=>"/Users/carrickr/.rvm/rubies/ruby-2.1.7/bin/irb", "LINES"=>"36", "COLUMNS"=>"139"} 

In the OS shell something like printenv will put all all the variables

**Comment by carrickr** [comment]
Also for .yml defined ones, you can use Rails.application.config to sell all the variables or Rails.application.config.foo to get foo's value.
